### PR TITLE
fix(outputs.mqtt): Preserve leading slash in topic

### LINKED ISSUE #14583: [outputs.mqtt] The leading forward slash in mqtt topic is removed
### Relevant telegraf.conf

```toml
[[outputs.mqtt]]
servers = ["tls://x.x.x.x:31883"]
username = "xxxx"
#password = "xxxx"
client_id = "xxx"
password = "xxx"
topic = "/sys/ProductKey/DeviceId/thing/event/property/post"
protocol = "3.1.1"
qos = 1
tls_ca = "certs/root.crt"
keep_alive = 3000
connection_timeout = "5s"
insecure_skip_verify = true
timeout = "2s"
```

### Logs from Telegraf

```text
timeout error (will provide tomorrow once I have access)
```

### System info

Telegraf 1.29.1

### Docker

_No response_

### Steps to reproduce

1. use `[outputs.mqtt]` and the topic name with leading forward slash, e.g. `/sys/ProductKey/DeviceId/thing/event/property/post`.
2. run telegraf with the config file

### Expected behavior

The plugin should send the messages to the MQTT topic.

### Actual behavior

The error `Could not publish message to MQTT server: timeout` is printed to stdout.

If the MQTT debug log is enabled, the target topic is printed (the topic is `sys/ProductKey/DeviceId/thing/event/property/post`). To enable MQTT debug logs,  add the code snippets from `paho.mqtt.golang`'s [README](https://github.com/eclipse/paho.mqtt.golang?tab=readme-ov-file#logging) to the function `NewMQTTv311Client` in telegraf source code.

As I see the leading forward slash is trimed.

### Additional info

The leading forward slash is not recommended in the topic:
* https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/#avoid-leading-forward-slash
* https://docs.aws.amazon.com/whitepapers/latest/designing-mqtt-topics-aws-iot-core/mqtt-design-best-practices.html

However, some of the IoT platform doesn't respect the recommendation.

### PR DESCRIPTION
**Pull request by zhangyuan**
## Summary

When using the output plugin [MQTT Producer Output Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/mqtt) and setting the topic with leading forward slash (e.g. `/sys/productKey/deviceId/thing/event/property/post`), the plugin sends messages to the topic with the leading forward slash trimmed (e.g. `sys/productKey/deviceId/thing/event/property/post`)

Though it's not recommended to use leading forward slash in MQTT topic in many places, some of the cloud IoT platform uses the topics with it, unfortunately (e.g. Aliyun IoT platform 😕 ). 

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #14583

### CODE REVIEW

**Review by powersj — COMMENTED** [review]
@zhangyuan,

Thanks for the issue and the PR. I have simplified the PR a little bit. Can you please download the new artifacts and verify it resolves the issue still?

Thanks!

**Comment by zhangyuan** [comment]
@powersj 

I just tested binary [linux_amd64.tar.gz](https://output.circle-artifacts.com/output/job/cc965dfa-e403-42b2-8050-97593a6317d4/artifacts/0/build/dist/telegraf-1.30.0~350320b2_linux_amd64.tar.gz) and it works for me 👏 .

Looking forward to merging it. Thank you.

**Review by powersj — APPROVED** [review]

**Comment by zhangyuan** [comment]
Just fixed the email in the commit history and rebase the branch, no changes to the code.

**Comment by Hipska** [comment]
What if this would be replaced  https://github.com/influxdata/telegraf/blob/b72be8e97d7cd5c7148c82133e2eb5656e4fe41a/plugins/outputs/mqtt/topic_name_generator.go#L47-L51
by
```go
	for i, p := range strings.Split(b.String(), "/") {
		if i == 0 || p != "" {
			ts = append(ts, p)
		}
	}
```

**Review by Hipska — APPROVED** [review]

File: plugins/outputs/mqtt/topic_name_generator.go [hunk 1]
```diff
@@ -54,5 +54,8 @@ func (t *TopicNameGenerator) Generate(hostname string, m telegraf.Metric) (strin
 	if topic == "" {
 		return m.Name(), nil
 	}
+	if strings.HasPrefix(b.String(), "/") {
+		topic = fmt.Sprintf("/%s", topic)
```
Comment (srebhan) [inline plugins/outputs/mqtt/topic_name_generator.go:58]:
```suggestion
		topic = "/" + topic
```

**Review by srebhan — COMMENTED** [review]
@zhangyuan, just one small simplification from my side...

**Review by srebhan — APPROVED** [review]
Thanks @zhangyuan!

**Comment by Hipska** [comment]
🤷 https://github.com/influxdata/telegraf/pull/14582#issuecomment-1898288539
