### PR TITLE
plugins/filestat: Skip missing files

### LINKED ISSUE #7315: plugins/filestat: probing files that don't exist results in `Unable to get info for file "/does/not/exist", possible permissions issue`
### Relevant telegraf.conf:

```toml
[[inputs.filestat]]
  files = ["/does/not/exist"]
```

### System info:

Telegraf 1.14.0-1 from the `bionic` repo `https://repos.influxdata.com/ubuntu/`.

### Steps to reproduce:

1. Ensure the file `/does/not/exist` does not exist
2. Setup an input config with the configuration snippet above & restart telegraf
### Expected behavior:

If the file doesn't exist: No log message.

If the file does exist but can't be probed (e.g. on an unreadable directory): A log message giving the actual error.

### Actual behavior:

1. In system logs: telegraf logs that it can't probe the file, but guesses incorrectly that the permissions are wrong: `[inputs.filestat] Unable to get info for file "/does/not/exist", possible permissions issue`
2. The filestat measurement about the file is correctly reported with `exists: 0`.

### Additional info:

A PR exists for this issue, at #6940: it attempts to fix this with an additional configuration flag. I think that is unnecessary & will submit another PR with a less config-heavy fix.

### PR DESCRIPTION
**Pull request by antifuchs**
This PR attempts to fix #7315, the same problem as #6940, but without adding a config flag.

Previously, the filestat plugin would check for a file's existence, and then try to compute all sorts of things for the missing file, which failed and resulted in a log message about possible permission errors.

Now, the plugin just skips the file if it exists. If an error is encountered probing an existing file, the plugin now logs that error, too, instead of hazarding a guess at permission problems.

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated. (no update needed)
- [x] Has appropriate unit tests: Added a test.

### CODE REVIEW

**Review by srebhan — COMMENTED** [review]
I'm not sure we want to ignore the files silently. What if the user misspelled the filename? He probably will notice quite late (when analyzing the data). So my guts-feeling is we should log at least once.
How about adding a `map[string]bool` to the struct for remembering which filename was logged already and output a warning on the first encounter of the missing file. Then set the map entry for the file to `true` and skip any further warning-outputs...

How does that sound to you?

**Comment by srebhan** [comment]
@antifuchs any update?

**Comment by antifuchs** [comment]
Ah, sorry I missed this! I will look into getting this implemented.

**Comment by antifuchs** [comment]
@srebhan Updated - I hope this reflects what you had in mind.

File: plugins/inputs/filestat/filestat.go [hunk 1]
```diff
@@ -35,11 +35,18 @@ type FileStat struct {
 
 	// maps full file paths to globmatch obj
 	globs map[string]*globpath.GlobPath
+
+	// files that were missing - we only log the first time it's not found.
+	missingFiles map[string]struct{}
+	// files that had an error in Stat - we only log the first error.
+	filesWithErrors map[string]struct{}
```
Comment (srebhan) [inline plugins/inputs/filestat/filestat.go:42]: How about
```suggestion
	missingFiles map[string]bool
	// files that had an error in Stat - we only log the first error.
	filesWithErrors map[string]bool
```

File: plugins/inputs/filestat/filestat.go [hunk 2]
```diff
@@ -85,12 +92,24 @@ func (f *FileStat) Gather(acc telegraf.Accumulator) error {
...
 				fields["exists"] = int64(0)
+				acc.AddFields("filestat", fields, tags)
+				if _, ok := f.missingFiles[fileName]; !ok {
+					f.Log.Warnf("File %q not found", fileName)
+					f.missingFiles[fileName] = struct{}{}
+				}
+				continue
+			} else {
+				delete(f.missingFiles, fileName)
 			}
```
Comment (srebhan) [inline plugins/inputs/filestat/filestat.go:103]: I think you can simplify it to
```suggestion
				if ! f.missingFiles[fileName] {
					f.Log.Warnf("File %q not found", fileName)
					f.missingFiles[fileName] = true
				}
				continue
			}
			f.missingFiles[fileName] = false
```

File: plugins/inputs/filestat/filestat.go [hunk 3]
```diff
@@ -85,12 +92,24 @@ func (f *FileStat) Gather(acc telegraf.Accumulator) error {
...
 			if fileInfo == nil {
-				f.Log.Errorf("Unable to get info for file %q, possible permissions issue",
-					fileName)
+				if _, ok := f.filesWithErrors[fileName]; !ok {
+					f.filesWithErrors[fileName] = struct{}{}
+					f.Log.Errorf("Unable to get info for file %q: %v",
+						fileName, err)
+				}
 			} else {
+				delete(f.filesWithErrors, fileName)
```
Comment (srebhan) [inline plugins/inputs/filestat/filestat.go:112]: See above. Use a string/bool map.

**Review by srebhan — CHANGES_REQUESTED** [review]
Please use a `map[string]bool` instead. See the comments in the code. Otherwise looks good!

**Comment by antifuchs** [comment]
Restructured to use string/bool maps, hope that works for you

**Review by srebhan — APPROVED** [review]
Looks good to me.

File: plugins/inputs/filestat/filestat.go [hunk 4]
```diff
@@ -35,11 +35,18 @@ type FileStat struct {
 
 	// maps full file paths to globmatch obj
 	globs map[string]*globpath.GlobPath
+
+	// files that were missing - we only log the first time it's not found.
+	missingFiles map[string]bool
+	// files that had an error in Stat - we only log the first error.
+	filesWithErrors map[string]bool
```
Comment (ssoroka) [inline plugins/inputs/filestat/filestat.go:42]: fyi, struct{} uses no memory.
```suggestion
	// files that were missing - we only log the first time it's not found.
	missingFiles map[string]struct{}
	// files that had an error in Stat - we only log the first error.
	filesWithErrors map[string]struct{}
```

**Review by ssoroka — APPROVED** [review]
I'm a bit concerned that the memory use of this grows infinitely on directories with a lot of files going in/out. I guess I'm okay merging it, but I think we should come back and fix that up.

File: plugins/inputs/filestat/filestat.go (hunk 4 above)
Comment (antifuchs) [reply plugins/inputs/filestat/filestat.go:42]: Agreed that a `struct{}` map would use less memory, but then again it'll use about as much memory as the number of files configured to be checked, whose config structure already use memory ... it comes out a wash, I feel like.
