### PR TITLE
fix: pool detection and metrics gathering for ZFS >= 2.1.x

### LINKED ISSUE #8862: Updated ZFS measurements for OpenZFS 2.0
### Proposal:

With release of OpenZFS 2.0 the telegraf plugin should be updated

### Current behavior:

Alot of metrics are locked on linux to old behavior of ZFS 0.7-0.8

### Desired behavior:

With release of ZFS 2.0 the codebased have been unified between FreeBSD and Linux where commands and metrics should be available for both OS. 

### Use case: 

With current behavior for linux we can't collect criticial data to ensure pool is healthy.

### PR DESCRIPTION
**Pull request by aaronjwood**
### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

partially resolves #8862 

I moved to ZFS 2.1.1 the other day and noticed my pool metrics broke. After a bit of investigation I found out that things have changed significantly under the hood. I have this diff deployed to one of my servers and can show it working:
Screenshot from 2021-11-12 12-44-09

### CODE REVIEW

**Comment by aaronjwood** [comment]
Did the lint rules change recently? It seems to be flagged a lot of things in the ZFS plugin README that I didn't touch.

**Comment by srebhan** [comment]
Hey @aaronjwood, thanks for looking into this. From your changes it looks like the PR is breaking backward compatibility, i.e. you cannot use a zfs  < 2.1.x with the PR (e.g. by changing the proc-file path). Is my understanding correct? And if so, can we somehow test for the present zfs version to be compatible with both formats?

**Comment by aaronjwood** [comment]
> Hey @aaronjwood, thanks for looking into this. From your changes it looks like the PR is breaking backward compatibility, i.e. you cannot use a zfs  < 2.1.x with the PR (e.g. by changing the proc-file path). Is my understanding correct? And if so, can we somehow test for the present zfs version to be compatible with both formats?

Hi, it should not. I fall back to checking the old kstat path if the new one doesn't exist. There is also a fallback for how the actual file contents are parsed. I've also added some tests that write out a kstat with the new format/filename to exercise the new code paths.

Do you see an issue with it?

**Review by srebhan — COMMENTED** [review]
@aaronjwood I now see your approach and it's fine IMO. Sorry for having missed it in the first pass...

Given that the format changed I suspect/fear that this might happen again in the future. So I 
wonder if we should be prepared and approach this in a slightly more general way. How about moving the probing to a `probeVersion` function returning a format identifier (e.g. 1, 2, 3...). Based on this version we have different `gather..._vX()` functions for `X in {1,2,3,...}` that are tailored to the format of this version. This way we would have a clear structure and avoid complex if/else flow handlings dependent on versions. If there is common code, we can factor that into more general functions parameterized by the version-specific functions. What do you think?

**Comment by aaronjwood** [comment]
> @aaronjwood I now see your approach and it's fine IMO. Sorry for having missed it in the first pass...
> 
> Given that the format changed I suspect/fear that this might happen again in the future. So I 
> wonder if we should be prepared and approach this in a slightly more general way. How about moving the probing to a `probeVersion` function returning a format identifier (e.g. 1, 2, 3...). Based on this version we have different `gather..._vX()` functions for `X in {1,2,3,...}` that are tailored to the format of this version. This way we would have a clear structure and avoid complex if/else flow handlings dependent on versions. If there is common code, we can factor that into more general functions parameterized by the version-specific functions. What do you think?

No worries. What you suggest sounds good to me. I'll try and find some time in the coming weeks to change this. Things are a bit tight with the holidays coming up :)

**Comment by aaronjwood** [comment]
FWIW I'll try out the changes I pushed up just now over the weekend. I don't have the ability to put a new binary on my server at the moment :)

**Comment by aaronjwood** [comment]
Yep, still looking good on my server.

File: plugins/inputs/zfs/zfs_linux.go [hunk 1]
```diff
@@ -45,36 +80,99 @@ func getTags(pools []poolInfo) map[string]string {
...
-		return err
+func gather(lines []string, fileLines int) ([]string, []string, error) {
+	if len(lines) != fileLines {
+		return nil, nil, errors.New("Expected lines in kstat does not match")
 	}
 
 	keys := strings.Fields(lines[1])
 	values := strings.Fields(lines[2])
+	if len(keys) != len(values) {
+		return nil, nil, fmt.Errorf("Key and value count don't match Keys:%v Values:%v", keys, values)
```
Comment (srebhan) [inline plugins/inputs/zfs/zfs_linux.go:91]: Errors should start with lowercase letters in Golang...
```suggestion
		return nil, nil, fmt.Errorf("key and value count don't match Keys:%v Values:%v", keys, values)
```

File: plugins/inputs/zfs/zfs_linux.go [hunk 2]
```diff
@@ -45,36 +80,99 @@ func getTags(pools []poolInfo) map[string]string {
...
-	lines, err := internal.ReadLines(pool.ioFilename)
-	if err != nil {
-		return err
-	}
-
-	if len(lines) != 3 {
-		return err
+func gather(lines []string, fileLines int) ([]string, []string, error) {
+	if len(lines) != fileLines {
+		return nil, nil, errors.New("Expected lines in kstat does not match")
```
Comment (srebhan) [inline plugins/inputs/zfs/zfs_linux.go:85]: Errors should start with lowercase letters in Golang...
```suggestion
		return nil, nil, errors.New("expected lines in kstat does not match")
```

File: plugins/inputs/zfs/zfs_linux.go [hunk 3]
```diff
@@ -93,10 +191,10 @@ func (z *Zfs) Gather(acc telegraf.Accumulator) error {
 		kstatPath = "/proc/spl/kstat/zfs"
 	}
 
-	pools := getPools(kstatPath)
+	pools, err := getPools(kstatPath)
 	tags := getTags(pools)
 
-	if z.PoolMetrics {
+	if z.PoolMetrics && err == nil {
```
Comment (srebhan) [inline plugins/inputs/zfs/zfs_linux.go:197]: Shouldn't we simply return on the error?
```golang
	pools, err := getPools(kstatPath)
	if err != nil {
		return fmt.Errorf("cannot get pools: %v", err)
	}
	tags := getTags(pools)

	if z.PoolMetrics {
```

**Review by srebhan — COMMENTED** [review]
This is an amazing update @aaronjwood! Some small leftovers, but we are almost good to go. I really love the new structure.

File: plugins/inputs/zfs/zfs_linux.go (hunk 3 above)
Comment (aaronjwood) [reply plugins/inputs/zfs/zfs_linux.go:197]: I was trying to keep the original behavior of collecting the rest of the metrics even when there may be an error (or the config is not enabled) around collecting pool metrics.

I can change it to error our immediately if you'd prefer.

Comment (srebhan) [reply plugins/inputs/zfs/zfs_linux.go:197]: I'm happy with your code if this reproduces the previous behavior. Please keep the code you have and I will mark this as resolved. :-)

Comment (aaronjwood) [reply plugins/inputs/zfs/zfs_linux.go:197]: Sounds good, thanks!

**Comment by aaronjwood** [comment]
Should be all set now :) Thanks for the reviews. Looking forward to having this upstreamed!

**Review by srebhan — APPROVED** [review]
Looks good to me. Thanks for the nice work @aaronjwood!

**Review by MyaLongmire — APPROVED** [review]
Thank you for this pr!
