### PR TITLE
fix(inputs.filecount): Respect symlink files with FollowSymLinks

### LINKED ISSUE #13250: Filecount-Plugin - Don't follow File-Symlinks
### Use Case

Currently, if you want to monitor the sizes of certain directories, you would be best to use the Filecount-Plugin.

Directories, which are symlinks, and should not be considered can be excluded via `follow_symlinks = false`.

Consider following situation:

```
lrwxrwxrwx 1 root root         36 Sep 27  2022 ubuntu-22.04-minimal-app-a.tgz -> disks-ubuntu-22.04-minimal-srv-a.tgz
lrwxrwxrwx 1 root root         36 Sep 27  2022 ubuntu-22.04-minimal-app-b.tgz -> disks-ubuntu-22.04-minimal-srv-a.tgz
lrwxrwxrwx 1 root root         36 Sep 27  2022 ubuntu-22.04-minimal-app-c.tgz -> disks-ubuntu-22.04-minimal-srv-a.tgz
lrwxrwxrwx 1 root root         36 Sep 27  2022 ubuntu-22.04-minimal-app-d.tgz -> disks-ubuntu-22.04-minimal-srv-a.tgz
lrwxrwxrwx 1 root root         36 Sep 27  2022 ubuntu-22.04-minimal-app-e.tgz -> disks-ubuntu-22.04-minimal-srv-a.tgz
lrwxrwxrwx 1 root root         36 Sep 27  2022 ubuntu-22.04-minimal-app-f.tgz -> disks-ubuntu-22.04-minimal-srv-a.tgz
lrwxrwxrwx 1 root root         36 Sep 27  2022 ubuntu-22.04-minimal-cch-a.tgz -> disks-ubuntu-22.04-minimal-srv-a.tgz
lrwxrwxrwx 1 root root         36 Sep 27  2022 ubuntu-22.04-minimal-cch-b.tgz -> disks-ubuntu-22.04-minimal-srv-a.tgz
-rw-r--r-x 1 root root  800161942 Jan  3 13:52 disks-ubuntu-22.04-minimal-srv-a.tgz
```

This will result in the file `disks-ubuntu-22.04-minimal-srv-a.tgz` being counted 9 times.

### Expected behavior

Using a dedicated config-setting (e.g. `follow_file_symlinks = false`), one should be able to stop telegraf following file-symlinks to determine the amount of bytes occupied in the target directory.

### Actual behavior

There is currently no way to prevent this.

### Additional info

Telegraf-metric:
```
1683537101000000000 57440 /home/test    devstack 608295075691
```
Actual size:
```
# du -sh /home/test/
233G /home/test
```

### PR DESCRIPTION
**Pull request by DStrand1**
## Summary
`godirwalk` does not automatically filter out symlink files with its `FollowSymbolicLinks` config option. Changes to calling `Fstat` if needed to respect the settings, where before it would call `Stat` and automatically follow the link

## Checklist

- [X] No AI generated code was used in this PR

## Related issues
resolves #13250

### CODE REVIEW

File: plugins/inputs/filecount/filecount.go [hunk 1]
```diff
@@ -244,6 +244,21 @@ func (fc *FileCount) Gather(acc telegraf.Accumulator) error {
 	return nil
 }
 
+func (fc *FileCount) resolveLink(path string) (os.FileInfo, error) {
```
Comment (DStrand1) [inline plugins/inputs/filecount/filecount.go:247]: This still disregards the regular only setting, since it only calls Lstat if FollowSymlinks is false. I think it may need a bit more refactoring to get that to work as expected without aggressive repeated calls to Stat and Lstat

Comment (srebhan) [reply plugins/inputs/filecount/filecount.go:247]: Fine with me.

**Review by srebhan — APPROVED** [review]
Looks good to me. Thanks @DStrand1!

**Review by powersj — APPROVED** [review]
