### PR TITLE
fix(parsers.json_v2): Respect string type for objects and arrays

### LINKED ISSUE #16602: Telegraf expands JSON objects/arrays into separate fields even when type = "string"
### Relevant telegraf.conf

```toml
[[inputs.mqtt_consumer.json_v2.field]]
  path    = "metadata"
  rename  = "metadata"
  type    = "string"

[[inputs.mqtt_consumer.json_v2.field]]
  path    = "active_issues"
  rename  = "active_issues"
  type    = "string"
```

### Logs from Telegraf

```text
events,controller_id=C_abcd1234,event_type=METER_CONNECTION_QUALITY,topic=controller/C_abcd1234/events state="BAD",severity="CRITICAL",active_issues_type="METER_CONNECTION_QUALITY",active_issues_since="2025-03-10T05:59:22.146Z",active_issues_last_update="2025-03-10T08:20:26.506Z",active_issues_state="BAD",active_issues_severity="CRITICAL",active_issues_metadata_failures="59",active_issues_metadata_failureRate="0.98" 1741594827000000000
```

### System info

Telegraf 1.33.3

### Docker

_No response_

### Steps to reproduce

1. Example input JSON:
```
{
  "timestamp": "2025-03-10T08:20:26.506Z",
  "event": {
    "type": "METER_CONNECTION_QUALITY",
    "state": "BAD",
    "metadata": {
      "failures": 59,
      "failureRate": "0.98"
    },
    "severity": "CRITICAL"
  },
  "active_issues": [
    {
      "type": "METER_CONNECTION_QUALITY",
      "since": "2025-03-10T05:59:22.146Z",
      "last_update": "2025-03-10T08:20:26.506Z",
      "state": "BAD",
      "severity": "CRITICAL",
      "metadata": {
        "failures": 59,
        "failureRate": "0.98"
      }
    }
  ]
}

```

### Expected behavior

Telegraf should store `metadata` and `active_issues` as plain strings:

```
metadata: {"failures": 59, "failureRate": "0.98"}
active_issues: [{"type": "METER_CONNECTION_QUALITY","since": "2025-03-10T05:59:22.146Z","last_update": "2025-03-10T08:20:26.506Z","state": "BAD","severity": "CRITICAL","metadata": {"failures": 59,"failureRate": "0.98"}}]
```

### Actual behavior

Telegraf expands the nested structure into separate fields instead:

```
active_issues_last_update: 2025-03-10T08:20:21.468Z
active_issues_metadata_failureRate: 0.98
active_issues_metadata_failures: 59
active_issues_severity: CRITICAL
active_issues_since: 2025-03-10T05:59:22.146Z
active_issues_state: BAD
active_issues_type: METER_CONNECTION_QUALITY
controller_id: C_abcd1234
event_type: METER_CONNECTION_QUALITY
severity: CRITICAL
time: 2025-03-10T08:20:21Z
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skartikey**
## Summary

Fixes a bug where the JSON v2 parser ignored type = "string" configuration for JSON objects and arrays, incorrectly expanding them into separate fields instead of preserving them as JSON strings.

**Example**
Before (broken):
```
active_issues_type="METER_CONNECTION_QUALITY"
active_issues_state="BAD"
metadata_failures="59"
```

After (fixed):
```
active_issues="[{\"type\":\"METER_CONNECTION_QUALITY\",\"state\":\"BAD\",\"metadata\":{\"failures\":59}}]"
metadata="{\"failures\":59,\"failureRate\":\"0.98\"}"
```

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #16602

### CODE REVIEW

File: plugins/parsers/json_v2/parser_test.go [hunk 1]
```diff
@@ -105,6 +106,155 @@ func TestParserEmptyConfig(t *testing.T) {
...
+	require.True(t, ok, "metadata should be a string, got %T", metadataField)
+	assert.Contains(t, metadataStr, "failures", "metadata should contain the JSON content")
+	assert.Contains(t, metadataStr, "failureRate", "metadata should contain the JSON content")
+
+	activeIssuesField, ok := metric.GetField("active_issues")
+	require.True(t, ok, "active_issues field should exist")
+	activeIssuesStr, ok := activeIssuesField.(string)
+	require.True(t, ok, "active_issues should be a string, got %T", activeIssuesField)
+	assert.Contains(t, activeIssuesStr, "METER_CONNECTION_QUALITY", "active_issues should contain the array content")
+	assert.Contains(t, activeIssuesStr, "since", "active_issues should contain the array content")
```
Comment (srebhan) [inline plugins/parsers/json_v2/parser_test.go]: NO `assert`s please! We put in a major effort to get rid of `assert` so please use `require` instead!

**Review by srebhan — COMMENTED** [review]
Thanks for your fix @skartikey! Just one comment in the code and fearful vision of this potentially breaking existing users. ;-) But I agree it's the right thing to do.

File: plugins/parsers/json_v2/parser_test.go (hunk 1 above)
Comment (skartikey) [reply plugins/parsers/json_v2/parser_test.go]: I have replaced it with require.

**Review by srebhan — APPROVED** [review]
Thanks @skartikey!
