### PR TITLE
fix: Add mariadb_dialect to address the MariaDB differences in INNODB_METRICS

### LINKED ISSUE #7968: gather_innodb_metrics fails on MariaDB 10.5.4+
### Relevant telegraf.conf:

```toml
[[inputs.mysql]]
  gather_innodb_metrics = true
```

### System info:

* Linux 3.10.0-1127.18.2.el7.x86_64
* MariaDB-server-10.5.4-1.el7.centos.x86_64

### Steps to reproduce:

1. Enable gather InnoDB metrics in Telegraf's inputs_mysql.conf plugin (`gather_innodb_metrics = true`)
2. Restart Telegraf

### Expected behaviour:

MySQL/MariaDB metrics successfully collected.

### Actual behavior:

The following error will be reported:

```code
E! [inputs.mysql] Error in plugin: Error 1054: Unknown column 'status' in 'where clause'
```

### Additional info:

The problem is the following query in the mysql plugin:

```go
innoDBMetricsQuery = `
SELECT NAME, COUNT
FROM information_schema.INNODB_METRICS
WHERE status='enabled'
`
```

The status column has changed in recent versions of MariaDB (not sure if it's the same for MySQL). The correct query should be:

```go
innoDBMetricsQuery = `
SELECT NAME, COUNT
FROM information_schema.INNODB_METRICS
WHERE ENABLED=1;
`
```

### PR DESCRIPTION
**Pull request by MarcHagen**
### Required for all PRs:

- [x] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #7968

### CODE REVIEW

**Comment by powersj** [comment]
@MarcHagen - thanks for this PR! Could you rebase or update your PR with master. That should fix tests.

**Comment by MarcHagen** [comment]
@powersj I've rebased on the master branch and forced push the changes, but failed on a mac test? (tcp_listener) which i didn't touch, so that always fun.

**Comment by MarcHagen** [comment]
@powersj Nice, seems all tests are passed now. Thank you for restarting that flaky test :)

**Comment by MarcHagen** [comment]
@powersj I've rebased from master to resolve the merge conflicts. Assuming the test will pass, maybe getting this merged?

File: plugins/inputs/mysql/mysql.go [hunk 1]
```diff
@@ -230,6 +230,11 @@ const (
         SELECT NAME, COUNT
         FROM information_schema.INNODB_METRICS
         WHERE status='enabled'
+    `
+	innoDBMetricsQueryMariadb = `
+        SELECT NAME, COUNT
+        FROM information_schema.INNODB_METRICS
+        WHERE ENABLED=1
```
Comment (powersj) [inline plugins/inputs/mysql/mysql.go:237]: @MarcHagen thanks for this, and it looks like folks have tested it on mariadb versions 10.5 and newer. 

What will happen to a user on mariadb versions older than 10.5? I ask since it looks like 10.2, 10.3, and 10.4 have had releases this year already.

Comment (MarcHagen) [reply plugins/inputs/mysql/mysql.go:237]: @powersj Below 10.5 that query will indeed fail.

Then we need to change the `if m.MariadbDialect` to check for version with something like `SELECT version()` that we then can regex `10\.[1-4].*` ?

What is your opinion on that?

Comment (MarcHagen) [reply plugins/inputs/mysql/mysql.go:237]: Or something like this, `EXECUTE IMMEDIATE` is instroduced in MariaDB 10.2.3  
```
EXECUTE IMMEDIATE CONCAT("
SELECT NAME, COUNT
FROM information_schema.INNODB_METRICS
WHERE ", IF(version() REGEXP '10\.[1-4].*',"status='enabled'", "ENABLED=1"), "
");
```

Comment (powersj) [reply plugins/inputs/mysql/mysql.go:237]: That sounds good, my aim is to avoid breaking existing users on older, still supported versions. As such the version check seems to make the most sense.

If you could give that a try and let me know what version you are able to try it on, that would be great!

Comment (MarcHagen) [reply plugins/inputs/mysql/mysql.go]: I've tested the query against 10.1 (expected fail, is EOL) 10.2, 10.5 and 10.6 servers.
From 10.2 up to 10.6 all works fine. Seems to me a good solution for the version gap between <10.5 and >10.5

**Review by powersj — APPROVED** [review]
Thank you for driving this!

**Review by MyaLongmire — APPROVED** [review]

**Comment by nerijus** [comment]
With telegraf 1.22.2 (where this fix is included) and mariadb 10.6.5 we are getting:
```
[inputs.mysql] Error in plugin: Error 1054: Unknown column 'status' in 'where clause'
```

**Comment by powersj** [comment]
@nerijus can you see what columns are in that table? The [docs here](https://mariadb.com/kb/en/information-schema-innodb_metrics-table/) seem to expect the status column.

**Comment by MarcHagen** [comment]
@nerijus 
Please set ::

mariadb_dialect = true

**Comment by nerijus** [comment]
It seems mariadb >=10.5 no longer has `status` column. mariadb 10.4:
```
MariaDB [information_schema]> DESC INNODB_METRICS;
+-----------------+--------------+------+-----+---------+-------+
| Field           | Type         | Null | Key | Default | Extra |
+-----------------+--------------+------+-----+---------+-------+
| NAME            | varchar(193) | NO   |     |         |       |
| SUBSYSTEM       | varchar(193) | NO   |     |         |       |
| COUNT           | bigint(21)   | NO   |     | 0       |       |
| MAX_COUNT       | bigint(21)   | YES  |     | NULL    |       |
| MIN_COUNT       | bigint(21)   | YES  |     | NULL    |       |
| AVG_COUNT       | double       | YES  |     | NULL    |       |
| COUNT_RESET     | bigint(21)   | NO   |     | 0       |       |
| MAX_COUNT_RESET | bigint(21)   | YES  |     | NULL    |       |
| MIN_COUNT_RESET | bigint(21)   | YES  |     | NULL    |       |
| AVG_COUNT_RESET | double       | YES  |     | NULL    |       |
| TIME_ENABLED    | datetime     | YES  |     | NULL    |       |
| TIME_DISABLED   | datetime     | YES  |     | NULL    |       |
| TIME_ELAPSED    | bigint(21)   | YES  |     | NULL    |       |
| TIME_RESET      | datetime     | YES  |     | NULL    |       |
| STATUS          | varchar(193) | NO   |     |         |       |
| TYPE            | varchar(193) | NO   |     |         |       |
| COMMENT         | varchar(193) | NO   |     |         |       |
+-----------------+--------------+------+-----+---------+-------+
17 rows in set (0.001 sec)
```
mariadb 10.6:
```
MariaDB [information_schema]> DESC INNODB_METRICS;
+-----------------+-------------------------------------------------------------------+------+-----+---------+-------+
| Field           | Type                                                              | Null | Key | Default | Extra |
+-----------------+-------------------------------------------------------------------+------+-----+---------+-------+
| NAME            | varchar(193)                                                      | NO   |     |         |       |
| SUBSYSTEM       | varchar(193)                                                      | NO   |     |         |       |
| COUNT           | bigint(21)                                                        | NO   |     | 0       |       |
| MAX_COUNT       | bigint(21)                                                        | YES  |     | NULL    |       |
| MIN_COUNT       | bigint(21)                                                        | YES  |     | NULL    |       |
| AVG_COUNT       | float                                                             | YES  |     | NULL    |       |
| COUNT_RESET     | bigint(21)                                                        | NO   |     | 0       |       |
| MAX_COUNT_RESET | bigint(21)                                                        | YES  |     | NULL    |       |
| MIN_COUNT_RESET | bigint(21)                                                        | YES  |     | NULL    |       |
| AVG_COUNT_RESET | float                                                             | YES  |     | NULL    |       |
| TIME_ENABLED    | datetime                                                          | YES  |     | NULL    |       |
| TIME_DISABLED   | datetime                                                          | YES  |     | NULL    |       |
| TIME_ELAPSED    | bigint(21)                                                        | YES  |     | NULL    |       |
| TIME_RESET      | datetime                                                          | YES  |     | NULL    |       |
| ENABLED         | int(1)                                                            | NO   |     | 0       |       |
| TYPE            | enum('value','status_counter','set_owner','set_member','counter') | NO   |     | NULL    |       |
| COMMENT         | varchar(193)                                                      | NO   |     |         |       |
+-----------------+-------------------------------------------------------------------+------+-----+---------+-------+
17 rows in set (0.000 sec)
```

**Comment by MarcHagen** [comment]
> It seems mariadb >=10.5 no longer has `status` column. mariadb 10.4:
> 
> ```
> MariaDB [information_schema]> DESC INNODB_METRICS;
> +-----------------+--------------+------+-----+---------+-------+
> | Field           | Type         | Null | Key | Default | Extra |
> +-----------------+--------------+------+-----+---------+-------+
> | NAME            | varchar(193) | NO   |     |         |       |
> | SUBSYSTEM       | varchar(193) | NO   |     |         |       |
> | COUNT           | bigint(21)   | NO   |     | 0       |       |
> | MAX_COUNT       | bigint(21)   | YES  |     | NULL    |       |
> | MIN_COUNT       | bigint(21)   | YES  |     | NULL    |       |
> | AVG_COUNT       | double       | YES  |     | NULL    |       |
> | COUNT_RESET     | bigint(21)   | NO   |     | 0       |       |
> | MAX_COUNT_RESET | bigint(21)   | YES  |     | NULL    |       |
> | MIN_COUNT_RESET | bigint(21)   | YES  |     | NULL    |       |
> | AVG_COUNT_RESET | double       | YES  |     | NULL    |       |
> | TIME_ENABLED    | datetime     | YES  |     | NULL    |       |
> | TIME_DISABLED   | datetime     | YES  |     | NULL    |       |
> | TIME_ELAPSED    | bigint(21)   | YES  |     | NULL    |       |
> | TIME_RESET      | datetime     | YES  |     | NULL    |       |
> | STATUS          | varchar(193) | NO   |     |         |       |
> | TYPE            | varchar(193) | NO   |     |         |       |
> | COMMENT         | varchar(193) | NO   |     |         |       |
> +-----------------+--------------+------+-----+---------+-------+
> 17 rows in set (0.001 sec)
> ```
> 
> mariadb 10.6:
> 
> ```
> MariaDB [information_schema]> DESC INNODB_METRICS;
> +-----------------+-------------------------------------------------------------------+------+-----+---------+-------+
> | Field           | Type                                                              | Null | Key | Default | Extra |
> +-----------------+-------------------------------------------------------------------+------+-----+---------+-------+
> | NAME            | varchar(193)                                                      | NO   |     |         |       |
> | SUBSYSTEM       | varchar(193)                                                      | NO   |     |         |       |
> | COUNT           | bigint(21)                                                        | NO   |     | 0       |       |
> | MAX_COUNT       | bigint(21)                                                        | YES  |     | NULL    |       |
> | MIN_COUNT       | bigint(21)                                                        | YES  |     | NULL    |       |
> | AVG_COUNT       | float                                                             | YES  |     | NULL    |       |
> | COUNT_RESET     | bigint(21)                                                        | NO   |     | 0       |       |
> | MAX_COUNT_RESET | bigint(21)                                                        | YES  |     | NULL    |       |
> | MIN_COUNT_RESET | bigint(21)                                                        | YES  |     | NULL    |       |
> | AVG_COUNT_RESET | float                                                             | YES  |     | NULL    |       |
> | TIME_ENABLED    | datetime                                                          | YES  |     | NULL    |       |
> | TIME_DISABLED   | datetime                                                          | YES  |     | NULL    |       |
> | TIME_ELAPSED    | bigint(21)                                                        | YES  |     | NULL    |       |
> | TIME_RESET      | datetime                                                          | YES  |     | NULL    |       |
> | ENABLED         | int(1)                                                            | NO   |     | 0       |       |
> | TYPE            | enum('value','status_counter','set_owner','set_member','counter') | NO   |     | NULL    |       |
> | COMMENT         | varchar(193)                                                      | NO   |     |         |       |
> +-----------------+-------------------------------------------------------------------+------+-----+---------+-------+
> 17 rows in set (0.000 sec)
> ```

Yes we know that’s why this PR is created, set the mariadb_dialect = true to fix this.

**Comment by nerijus** [comment]
Seting `mariadb_dialect = true` helps, but I thought that telegraf discovers mariadb version itself:
```
	innoDBMetricsQueryMariadb = `
        EXECUTE IMMEDIATE CONCAT("
            SELECT NAME, COUNT
            FROM information_schema.INNODB_METRICS
            WHERE ", IF(version() REGEXP '10\.[1-4].*',"status='enabled'", "ENABLED=1"), "
        ");
```
?

**Comment by MarcHagen** [comment]
> Seting `mariadb_dialect = true` helps, but I thought that telegraf discovers mariadb version itself:
> 
> ```
> 	innoDBMetricsQueryMariadb = `
>         EXECUTE IMMEDIATE CONCAT("
>             SELECT NAME, COUNT
>             FROM information_schema.INNODB_METRICS
>             WHERE ", IF(version() REGEXP '10\.[1-4].*',"status='enabled'", "ENABLED=1"), "
>         ");
> ```
> 
> ?

No it does automatically diff between MySQL and MariaDB.
the mariadb_dialect already exists for other type of queries done by Telegraf.

When mariadb_dialect = true,
It only figures out the MariaDB version to be compatible with ‘status’ column (<=10.4) and ‘enabled’ column (with the newer versions >=10.5)

**Comment by martingg88** [comment]
is this change already included in master branch?
