### PR TITLE
fix(inputs.x509): Multiple sources with non-overlapping DNS entries.

### LINKED ISSUE #11623: [inputs.x509_cert] Using wrong server name for verification
### Relevant telegraf.conf

```toml
# Reads metrics from a SSL certificate
  [[inputs.x509_cert]]
    ## List certificate sources
    sources = ["smtp://server-A.org:587", "smtp://server-B.org:25"]
```

### Logs from Telegraf

```text
No specific logs, only wrong output.
```

### System info

Telegraf 1.23.2

### Docker

_No response_

### Steps to reproduce

Run Telegraf with the above config against two servers with non-overlapping DNS entries.

### Expected behavior

Certificates are reported to be valid in the metrics (`verification=valid`) as they are valid.

### Actual behavior

Instead of reporting the certificates valid, all certificates of the second `source` will be reported invalid similar to

```text
> x509_cert,common_name=server-B.com,host=telegraf-7fdffb564-97r6k,issuer_common_name=Some\ Certificate\ Authority\ -\ G2,public_key_algorithm=RSA,san=server-B.org, www.server-B.org, sub.server-B.org,serial_number=e077f23dd76b209f,signature_algorithm=SHA256-RSA,source=smtp://server-B.org:25,verification=invalid age=14708051i,enddate=1679151227i,expiry=19592748i,startdate=1644850427i,verification_code=1i,verification_error="x509: certificate is valid for server-B.org, www.server-B.org, sub.server-B.org, not server-A.org" 1659558478000000000
```

It is important to note that the error message indicates that the certificate chain of `server-B.org` is checked against `server-A.org` or more generally speaking against the first of the `sources` enumerated.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by srebhan**
- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #11623 

This PR fixes an issue for `https`, `tcp` and `smtp` certificate validation when using multiple sources with non-overlapping DNS entries in the certificates. That is if the DNS name of the first source is not valid in, at least one, other certificates.

The error results from a stateful behavior of the `serverName()` function, evaluating the `c.tlsCfg.ServerName` entry and returning this with priority in combination with setting exactly this field (`c.tlsCfg.ServerName`) when getting the certificate via `getCert()`. After getting the first source (e.g. `server-A.org`), the, previously empty, `c.tlsCfg.ServerName` field is set to `server-A.org` in `getCert()`. While the `https` and `tcp` variants of the function is emptying the field (leading to issues where the name was set by the user), the `smtp` variant leaves the field as is. Due to the fact that `getCert()` also uses `serverName()` to get the property, any further call to `getCert()` will not be able to overwrite the setting as `c.tlsCfg.ServerName` is now set (to `server-A.org`) and this is returned with priority. Therefore, from now on (after the first call to `getCert()`), `serverName()` will _always_ return the name of the first entry in `sources`!
As the server name is also used to verify the certificate in `Gather()`, the verification of all certificates runs against the name of the first entry in `sources`, which will fail in case that name is not in the certificates of any of the other sources!

The PR removes the state in `c.tlsCfg` by cloning the configuration for certificate retrieval. This way, only user-set names are returned by `serverName()` and thus the verification works.

### CODE REVIEW

**Review by MyaLongmire — APPROVED** [review]
Looks good to me. Thanks for doing this @srebhan

**Comment by chrism417** [comment]
Tested this on my end and it fixed my issue with 5 mail servers in one source file.  Thanks so much @srebhan 

image

**Review by MyaLongmire — COMMENTED** [review]
The linter is complaining `var-naming: var downloadTlsCfg should be downloadTLSCfg`. Once that is renamed it looks good to me.

File: plugins/inputs/x509_cert/x509_cert.go [hunk 1]
```diff
@@ -363,6 +366,15 @@ func (c *X509Cert) Gather(acc telegraf.Accumulator) error {
...
 			} else {
+				c.Log.Debugf("Invalid certificate at index %2d!", i)
+				c.Log.Debugf("  cert DNS names:    %v", cert.DNSNames)
+				c.Log.Debugf("  cert IP addresses: %v", cert.IPAddresses)
+				c.Log.Debugf("  opts.DNSName:      %v", opts.DNSName)
+				c.Log.Debugf("  verify options:    %v", opts)
+				c.Log.Debugf("  verify error:      %v", err)
+				c.Log.Debugf("  location:          %v", location)
+				c.Log.Debugf("  tlsCfg.ServerName: %v", c.tlsCfg.ServerName)
+				c.Log.Debugf("  ServerName:        %v", c.ServerName)
```
Comment (reimda) [inline plugins/inputs/x509_cert/x509_cert.go:377]: It seems like this invalid cert info could be more useful as metric fields instead of console debug messages. I think if we log it like this, it might not be clear to the user what cert is invalid. They might think the invalid cert was found when any telegraf plugin connected to a service and not know it is from x509_cert.

Comment (srebhan) [reply plugins/inputs/x509_cert/x509_cert.go:377]: I don't think we should expose these _internal_ information as fields. There already is a `verification_code` field which contain the info. I just added this to be able to quickly look into "hey, telegraf says the cert is invalid but it is valid" issues. Should I remove the info then?

**Comment by srebhan** [comment]
@MyaLongmire 

> The linter is complaining `var-naming: var downloadTlsCfg should be downloadTLSCfg`. Once that is renamed it looks good to me.

fixed.

**Comment by srebhan** [comment]
@MyaLongmire can you maybe add your approval again so it is obvious that you are OK with the latest changes!?

**Review by MyaLongmire — APPROVED** [review]

File: plugins/inputs/x509_cert/x509_cert.go (hunk 1 above)
Comment (reimda) [reply plugins/inputs/x509_cert/x509_cert.go:377]: On second thought, for a user to see these they'll have to turn on debug logging and the messages will start with "[inputs.x509_cert]" so they shouldn't confuse anyone.

When debugging it will be useful to have opts available.

**Review by reimda — APPROVED** [review]
