### PR TITLE
fix(inputs.http_response): Fix for IPv4 and IPv6 addresses when interface is set

### LINKED ISSUE #8451: http_response plugin have issues when urls list contains IPv4 and IPv6 addresses
Issue is present only when `interface` is set to proper value in `telegraf.conf`

### Relevant telegraf.conf for Windows:
```toml
[[inputs.http_response]]
  ## List of urls to query.
  urls = ["http://127.0.0.1:15000/hello", "http://[::1]:15000/hello"]

  ## Interface to use when dialing an address
  interface = "Loopback Pseudo-Interface 1"
```

### Relevant telegraf.conf for Linux:
```toml
[[inputs.http_response]]
  ## List of urls to query.
  urls = ["http://127.0.0.1:15000/hello", "http://[::1]:15000/hello"]

  ## Interface to use when dialing an address
  interface = "lo"
```

### System info:
1. Telegraf 1.16.2 (but probably there is problem since `interface` was added to plugin here: https://github.com/influxdata/telegraf/pull/6006 - so from Telegraf 1.12.0)
2. Windows 10 Pro and Ubuntu 18

### Steps to reproduce:
1. Start web server which listens on the TCP6 and TCP4 networks. For example:
```
	http.HandleFunc("/hello", func(writer http.ResponseWriter, request *http.Request) {
		fmt.Fprintf(writer, "hello\n")
	})
	http.ListenAndServe(":15000", nil)
```
2. Verify that web server responds successfully for `http://127.0.0.1:15000/hello` and `http://[::1]:15000/hello` (using web browser or `curl`)
3. Run Telegraf in Windows with given config (be sure that proper name of loopback interface is used).
4. Run Telegraf in Linux with given config (be sure that proper name of loopback interface is used).

### Expected behavior:
1. Web server starts successfully.
2. Web server responds successfully for `http://127.0.0.1:15000/hello` and `http://[::1]:15000/hello`.
3. Telegraf for Windows successfully monitors both URLs.
3. Telegraf for Linux successfully monitors both URLs.

### Actual behavior:
1. Web server starts successfully.
2. Web server responds successfully for `http://127.0.0.1:15000/hello` and `http://[::1]:15000/hello`.
3. Telegraf for Windows successfully monitors only `http://[::1]:15000/hello` URL:
```
http_response,host=win10,method=GET,result=connection_failed,server=http://127.0.0.1:15000/hello result_type="connection_failed",result_code=3i 1606058770000000000
http_response,host=win10,method=GET,result=success,server=http://[::1]:15000/hello,status_code=200 content_length=6i,result_type="success",result_code=0i,response_time=0.0020097,http_response_code=200i 1606058770000000000
```
4. Telegraf for Linux successfully monitors only `http://127.0.0.1:15000/hello` URL:
```
http_response,host=ubuntu,method=GET,result=success,server=http://127.0.0.1:15000/hello,status_code=200 result_code=0i,response_time=0.02016597,http_response_code=200i,content_length=6i,result_type="success" 1606058900000000000
http_response,host=ubuntu,method=GET,result=connection_failed,server=http://[::1]:15000/hello result_type="connection_failed",result_code=3i 1606058900000000000
```
### Additional info:
**Why Telegraf for Windows fails for IPv4 URL `http://127.0.0.1:15000/hello` and Telegraf for Linux fails for IPv6 URL `http://[::1]:15000/hello`?**
It is because in this line https://github.com/influxdata/telegraf/blob/b39c1974a23507a1892979c4401d135778a52fad/plugins/inputs/http_response/http_response.go#L209 plugin chooses first available address for given interface. In my case it is IPv6 for Windows and IPv4 for Linux.

**Would it work if any address ordering solution is provided (so the same address would be chosen 
independently from OS type)?**
No, they would just fail for the same address type. Other address type would still not work. It is because HTTP Client with chosen address is configured per plugin and not per provided URL.

### PR DESCRIPTION
**Pull request by zak-pawel**
## Summary

This PR solves the problem that existed in the scenario where the `urls` list contains mix of IPv4 and IPv6 addresses and the `interface` is config file set.
Until now, the plugin chooses the first available address for the given interface. In my case, it was IPv6 for Windows and IPv4 for Linux. Because of this, the plugin worked incorrectly with IPv4 addresses for Windows and IPv6 addresses for Linux.

Here is a list of the most important things done in this PR:

- Each `URL` now has its own `httpClient` (until now, one `httpClient` was used to handle all `URLs`).
- Each `URL` provided in the config and each address for the given `interface` in the config is parsed and checked to see if it is an IPv4 or IPv6 address.
  - I didn't find methods in the standard library (or in other dependencies) that would do this correctly and handle both `url.URL` and `net.IPNet`. That's why I added [github.com/seancfoley/ipaddress-go](https://github.com/seancfoley/ipaddress-go) lib. The topic of parsing addresses is complex enough that I didn't see the point in doing it myself. If any of the reviewers have an idea on how to do this better, I would be happy to hear it :)
- Each `URL` has a `httpClient` assigned that matches the address format (IPv4 or IPv6).
- Configuration checking and initializing defaults have been moved from `Gather` to `Init`.
  - This changes the behavior of the plugin slightly, which will now fail immediately if:
    - parsing the regular expression from `h.ResponseStringMatch` fails
    - at least one of the `URLs` provided in the config cannot be parsed
    - at least one of the `URLs` provided in the config is not of type `http` or `https`
    - another problem occurs while creating the `httpClient` for the `URL`
 
  (previously, these errors could occur in `Gather`, which did not cause the plugin to fail, but rather resulted in recurring errors in the logs)

Thanks to this PR, the `http_response` plugin tests for `Windows` are re-enabled.

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #8451

### CODE REVIEW

File: plugins/inputs/http_response/http_response.go [hunk 1]
```diff
@@ -16,13 +16,15 @@ import (
...
-	"github.com/benbjohnson/clock"
 	"github.com/influxdata/telegraf"
 	"github.com/influxdata/telegraf/config"
 	"github.com/influxdata/telegraf/internal"
 	"github.com/influxdata/telegraf/plugins/common/cookie"
 	"github.com/influxdata/telegraf/plugins/common/tls"
 	"github.com/influxdata/telegraf/plugins/inputs"
+
+	"github.com/benbjohnson/clock"
+	"github.com/seancfoley/ipaddress-go/ipaddr"
```
Comment (srebhan) [inline plugins/inputs/http_response/http_response.go:27]: This should go before the telegraf imports...

File: plugins/inputs/http_response/http_response.go [hunk 2]
```diff
@@ -138,14 +145,47 @@ func localAddress(interfaceName string) (net.Addr, error) {
...
+		if hostAddr := host.AsAddress(); hostAddr != nil {
+			if ipv6 := hostAddr.ToIPv6(); ipv6 != nil {
+				return true, ipv6.GetZone().String()
+			}
 		}
 	}
 
-	return nil, fmt.Errorf("cannot create local address for interface %q", interfaceName)
+	return false, ""
+}
```
Comment (srebhan) [inline plugins/inputs/http_response/http_response.go:178]: Can this be

```golang
func isURLInIPv6(address url.URL) (bool, string) {
	host := ipaddr.NewHostName(address.Host)
	if err := host.Validate(); err != nil {
		return false, ""
	}
	if hostAddr := host.AsAddress(); hostAddr != nil {
		if ipv6 := hostAddr.ToIPv6(); ipv6 != nil {
			return true, ipv6.GetZone().String()
		}
	}

	return false, ""
}
```

File: plugins/inputs/http_response/http_response.go [hunk 3]
```diff
@@ -138,14 +145,47 @@ func localAddress(interfaceName string) (net.Addr, error) {
...
+
+// isIPNetInIPv6 returns true only when IPNet can be represented in IPv6 format.
+// For other cases (address cannot be successfully parsed or is in IPv4 format), it returns false.
+func isIPNetInIPv6(address *net.IPNet) bool {
+	ipAddr, err := ipaddr.NewIPAddressFromNetIPNet(address)
+	if err == nil {
+		return ipAddr.ToIPv6() != nil
+	}
+
+	return false
```
Comment (srebhan) [inline plugins/inputs/http_response/http_response.go:188]:
```suggestion
	return err == nil && ipAddr.ToIPv6() != nil
```

**Review by srebhan — COMMENTED** [review]
Awesome work @zak-pawel! Just a few small comments...

File: plugins/inputs/http_response/http_response.go (hunk 1 above)
Comment (zak-pawel) [reply plugins/inputs/http_response/http_response.go]: Right, my bad.

File: plugins/inputs/http_response/http_response.go (hunk 2 above)
Comment (zak-pawel) [reply plugins/inputs/http_response/http_response.go]: It can :)

File: plugins/inputs/http_response/http_response.go (hunk 3 above)
Comment (zak-pawel) [reply plugins/inputs/http_response/http_response.go]: Done

**Review by srebhan — APPROVED** [review]
Thanks @zak-pawel!

**Review by powersj — APPROVED** [review]

File: plugins/inputs/http_response/http_response.go [hunk 4]
```diff
@@ -138,14 +145,43 @@ func localAddress(interfaceName string) (net.Addr, error) {
...
+
+			// choose interface address in the same format as server address
+			if ipNetInIPv6 == urlInIPv6 {
+				// leaving port set to zero to let kernel pick, but set zone
+				return &net.TCPAddr{IP: naddr.IP, Zone: zone}, nil
+			}
+		}
+	}
+
+	return nil, fmt.Errorf("cannot create local address for interface %q and server address %q", interfaceName, address.String())
```
Comment (Mic92) [inline plugins/inputs/http_response/http_response.go:161]: This seems to break the case when the address is a hostname instead of an ip address:

```
Error running agent: could not initialize input inputs.http_response: cannot create local address for interface "tinc.retiolum" and server address "http://transmission.r/transmission/web/"
```
