### PR TITLE
GitHub webhooks: check signature

### LINKED ISSUE #1661: Missing HMAC validation of events in GithubWebhook
## Bug report

[GithubWehook](https://github.com/influxdata/telegraf/blob/e603825e37d7548a4c046416a399cb7fdea45b6f/plugins/inputs/webhooks/github/github_webhooks.go#L24) does not validate event's value of `X-Hub-Signature` that provide authentication of incoming messages.

It's a security issue, currently this webhook access any incoming events.
### Expected behaviour:

Get `secret` (that's shared with github) from the config file and use it to verify authenticity of incoming events. [Github documentation](https://developer.github.com/webhooks/#delivery-headers).

### PR DESCRIPTION
**Pull request by francois2metz**
Fix #1661  

I added the check of the signature to github webhooks. If no secret is set in the config file, no check is performed (make it backward compatible).

### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: plugins/inputs/webhooks/github/github_webhooks.go [hunk 1]
```diff
@@ -29,6 +33,13 @@ func (gh *GithubWebhook) eventHandler(w http.ResponseWriter, r *http.Request) {
 		w.WriteHeader(http.StatusBadRequest)
 		return
 	}
+
+	if gh.Secret != "" && !checkSignature(gh.Secret, data, r.Header["X-Hub-Signature"][0]) {
```
Comment (phemmer) [inline plugins/inputs/webhooks/github/github_webhooks.go]: This will panic if the header `X-Hub-Signature` doesn't exist. It's recommended to use `r.Header.Get("X-Hub-Signature")` instead.

Same thing with the `X-Github-Event` up above. I know it's pre-existing code, but would probably be good time to fix it.

Comment (francois2metz) [inline plugins/inputs/webhooks/github/github_webhooks.go]: Great! Fixed.

**Comment by francois2metz** [comment]
Note: I tested that in production: with and without secret, and with a non matching secret.

File: plugins/inputs/webhooks/github/github_webhooks.go [hunk 2]
```diff
@@ -23,12 +27,19 @@ func (gh *GithubWebhook) Register(router *mux.Router, acc telegraf.Accumulator)
...
-	eventType := r.Header["X-Github-Event"][0]
+	eventType := r.Header.Get("X-Github-Event")
 	data, err := ioutil.ReadAll(r.Body)
 	if err != nil {
 		w.WriteHeader(http.StatusBadRequest)
 		return
 	}
+
+	if gh.Secret != "" && !checkSignature(gh.Secret, data, r.Header.Get("X-Hub-Signature")) {
+		log.Printf("I! Fail to check the github webhook signature\n")
```
Comment (sparrc) [inline plugins/inputs/webhooks/github/github_webhooks.go]: this should be `E!`?

File: plugins/inputs/webhooks/github/github_webhooks.go [hunk 3]
```diff
@@ -105,3 +116,14 @@ func NewEvent(data []byte, name string) (Event, error) {
 	}
 	return nil, &newEventError{"Not a recognized event type"}
 }
+
+func checkSignature(secret string, data []byte, signature string) bool {
+	return hmac.Equal([]byte(signature), []byte(generateSignature(secret, data)))
+}
+
+func generateSignature(secret string, data []byte) string {
```
Comment (sparrc) [inline plugins/inputs/webhooks/github/github_webhooks.go]: instead of generating the signature on every github event, you should generate it just once and then cache for future calls

Comment (francois2metz) [inline plugins/inputs/webhooks/github/github_webhooks.go]: The generation is dependant of the body of the event. Not sure what I can cache. The string to byte op?

Comment (sparrc) [inline plugins/inputs/webhooks/github/github_webhooks.go]: right, nevermind then

File: plugins/inputs/webhooks/github/github_webhooks.go (hunk 2 above)
Comment (francois2metz) [inline plugins/inputs/webhooks/github/github_webhooks.go]: Fixed

**Comment by danielnelson** [comment]
Can you add this to the changelog?

**Comment by francois2metz** [comment]
Rebased and updated the changelog and the readme.
