### PR TITLE
logparser: allow numbers in ident & auth parameters

### LINKED ISSUE #1810: Logparser common log format error (nginx/apache)
## Bug report
Using the logparser plugin to parse nginx access log files does not parse http basic auth requests when the username contains a digit or spaces.

Applies to both the _COMMON_LOG_FORMAT_ and _COMBINED_LOG_FORMAT_ grok pattern. Issue may be relevant for apache logs as well.

### Relevant telegraf.conf:
```
# Stream and parse log file(s).
[[inputs.logparser]]
  files = ["/var/log/nginx/access.log"]
  from_beginning = false

  [inputs.logparser.grok]
    patterns = ["%{COMMON_LOG_FORMAT}"]
    measurement = "nginx_access_log"
```

### System info:
```
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02) x86_64 GNU/Linux
```
```
Telegraf - version 1.0.0
```
```
nginx version: nginx/1.6.2
```

### Steps to reproduce:

1. Set up _telegraf.conf_ file as above
2. Echo the examples to the logfile (see additional info)
3. Telegraf will not match the grok pattern to the log

### Expected behavior:
Telegraf matches the log file using either the _COMMON_LOG_FORMAT_ or the _COMBINED_LOG_FORMAT_ and passes the log onto the outputs.

### Actual behavior:
When the username contains digits the log is ignored. When containing spaces words are parsed as other attributes (e.g. _client_ip_ will be parsed as one of the words).

### Additional info:
Here are some example logs that causes the error:

Using numbers in the http basic auth username:
```
127.0.0.1 - username123 [25/Sep/2016:00:19:43 +0200] "GET / HTTP/1.1" 401 590 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
```

Using spaces in the http basic auth username:
```
127.0.0.1 - my username here [25/Sep/2016:00:17:36 +0200] "GET / HTTP/1.1" 401 590 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
```

### PR DESCRIPTION
**Pull request by sparrc**
### Required for all PRs:

- [x] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] README.md updated (if adding a new plugin)

fixes #1810

### CODE REVIEW

File: plugins/inputs/logparser/grok/influx_patterns.go [hunk 1]
```diff
@@ -53,7 +53,7 @@ RESPONSE_TIME %{DURATION:response_time_ns:duration}
 EXAMPLE_LOG \[%{HTTPDATE:ts:ts-httpd}\] %{NUMBER:myfloat:float} %{RESPONSE_CODE} %{IPORHOST:clientip} %{RESPONSE_TIME}
 
 # Wider-ranging username matching vs. logstash built-in %{USER}
-NGUSERNAME [a-zA-Z\.\@\-\+_%]+
+NGUSERNAME [a-zA-Z0-9\.\@\-\+_%]+
```
Comment (phemmer) [inline plugins/inputs/logparser/grok/influx_patterns.go]: Just curious, if the field is delimited by spaces, why not match any non-space character?

Comment (sparrc) [inline plugins/inputs/logparser/grok/influx_patterns.go]: no particular reason, I'm just following logstash's example: https://github.com/elastic/logstash/blob/v1.4.2/patterns/grok-patterns#L1

Comment (sparrc) [inline plugins/inputs/logparser/grok/influx_patterns.go]: I've changed the COMMON LOG FORMAT pattern to match NOTSPACE for ident and auth. I wasn't able to find any information regarding character limitations on these. It appears that even whitespace is allowed based on #1810, but hopefully it's not very common.
