### PR TITLE
fixes #1987 custom docker repos with non-standard port

### LINKED ISSUE #1987: Docker input plugin imagename/version split does not work if private registry with port in url is used
## Bug report

The docker input plugin splits the image name and image version at the colon.

python:3

results in

container_image: python
container_version: 3

but the image name may contain a private registry url which contains a port, also with a colon for separation.

eg.

registry.domain.com:5000/monitoring/cadvisor:internal.0.23

This results in

container_image: registry.domain.com:
container_version: 5000/monitoring/cadvisor

### System info:

Telegraf Docker image telegraf:alpine

### PR DESCRIPTION
**Pull request by alex-sherwin**
Fixed for parsing docker image name / image version to account for the case of a custom docker repo which uses a non-standard port, for example `mycompany.net:4443/someimage:sometag`

### CODE REVIEW

**Comment by sparrc** [comment]
from ci: `run 'go fmt ./...' to format your source code.`

File: plugins/inputs/docker/docker.go [hunk 1]
```diff
@@ -221,14 +221,17 @@ func (d *Docker) gatherContainer(
...
-	//   ie, rabbitmq:3-management
-	imageParts := strings.Split(container.Image, ":")
-	imageName := imageParts[0]
+	// the image name sometimes has a version part, or a private repo
+	//   ie, rabbitmq:3-management or docker.someco.net:4443/rabbitmq:3-management
+	imageName := ""
 	imageVersion := "unknown"
-	if len(imageParts) > 1 {
-		imageVersion = imageParts[1]
+	if (strings.LastIndex(container.Image, ":") > -1) {
```
Comment (sparrc) [inline plugins/inputs/docker/docker.go]: you don't need to put the parentheses around the `if` condition, it may work but it's not generally used in Go code.

File: plugins/inputs/docker/docker.go [hunk 2]
```diff
@@ -221,14 +221,17 @@ func (d *Docker) gatherContainer(
...
+		imageVersion = container.Image[strings.LastIndex(container.Image, ":")+1:]
```
Comment (sparrc) [inline plugins/inputs/docker/docker.go]: store a temp index variable rather than calling strings.LastIndex 3 times

**Comment by alex-sherwin** [comment]
Apologies, first time contributing go code... Added a temp var for the index and applied gofmt

**Comment by sparrc** [comment]
no problem, thanks for fixing the requested changes!

File: plugins/inputs/docker/docker.go [hunk 3]
```diff
@@ -221,14 +221,18 @@ func (d *Docker) gatherContainer(
...
-	//   ie, rabbitmq:3-management
-	imageParts := strings.Split(container.Image, ":")
-	imageName := imageParts[0]
+	// the image name sometimes has a version part, or a private repo
+	//   ie, rabbitmq:3-management or docker.someco.net:4443/rabbitmq:3-management
+	imageName := ""
 	imageVersion := "unknown"
-	if len(imageParts) > 1 {
-		imageVersion = imageParts[1]
+	imageVersionMarkerIndex := strings.LastIndex(container.Image, ":")
```
Comment (sparrc) [inline plugins/inputs/docker/docker.go]: I know it goes against other languages but general Go style dictates the use of short variable names. Since this is an index that is scoped just within these 3 lines of code, just call it `i` (instead of `imageVersionMarkerIndex`). You can add a comment explaining what it is exactly if you like.
