### PR TITLE
fix(outputs.wavefront): flush metric buffer before reaching overflow

### LINKED ISSUE #10009: [output.wavefront] "immediate_flush" flag doesn't work if sdk buffer becomes full
### Relevent telegraf.conf

```toml
[[outputs.wavefront]]
  immediate_flush = true

[agent]
  metric_buffer_limit = 1000000
```

### System info

Telegraf 1.16.3

### Docker

_No response_

### Steps to reproduce

1. High metric volume fills output buffer to >50k

I don't have a good method for doing this on demand

### Expected behavior

If the "immediate_flush" flag is set to true then the buffer internal to the wavefront sdk should not impact Telegraf performance

### Actual behavior

Once the buffer is full, an error is emitted in the Write function before the "immediate_flush" flag is checked.  The error is repeated on every flush interval.

This also causes input progress to stop.  In my case reading from Kafka topics can be observed to fall behind.  Restarting Telegraf allows some progress to be made but progress stops if the wavefront sdk buffer becomes full again.

### Additional info

I think this can be fixed with a simple change https://github.com/influxdata/telegraf/compare/master...PhoenixRion:master

I have reached out to Wavefront as well to ask for their input.

Sample error log `E! [agent] Error writing to outputs.wavefront: Wavefront sending error: buffer full, dropping line: ...`

### PR DESCRIPTION
**Pull request by astp-okta**
# Required for all PRs

- [ ] Updated associated README.md. (not needed as this is a quick bufix)
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #10009

Fixes bug introduced in telegraf 1.25.0 where after brief period of ~10mins depending on metric load, telegraf begins erroring with `Error writing to outputs.wavefront: wavefront sending error: buffer full, dropping line`. This patch flushes the buffer when it becomes full and continues outputting as expected.

### CODE REVIEW

File: plugins/outputs/wavefront/wavefront.go [hunk 1]
```diff
@@ -122,21 +122,24 @@ func (w *Wavefront) Write(metrics []telegraf.Metric) error {
...
+					if err != nil {
+						return err
 					}
-					return fmt.Errorf("wavefront sending error: %w", err)
+					// Try again.
+					err = w.sender.SendMetric(point.Metric, point.Value, point.Timestamp, point.Source, point.Tags)
+				}
+				if err != nil {
+					if isRetryable(err) {
+						return fmt.Errorf("wavefront sending error: %v", err)
```
Comment (Hipska) [inline plugins/outputs/wavefront/wavefront.go:138]:
```suggestion
						return fmt.Errorf("wavefront sending error: %w", err)
```

File: plugins/outputs/wavefront/wavefront.go [hunk 2]
```diff
@@ -122,21 +122,24 @@ func (w *Wavefront) Write(metrics []telegraf.Metric) error {
 		for _, point := range w.buildMetrics(m) {
 			err := w.sender.SendMetric(point.Metric, point.Value, point.Timestamp, point.Source, point.Tags)
 			if err != nil {
-				if isRetryable(err) {
-					if flushErr := w.sender.Flush(); flushErr != nil {
-						w.Log.Errorf("wavefront flushing error: %v", flushErr)
+				if strings.Contains(err.Error(), "buffer full, dropping line") {
+					// The internal buffer in the Wavefront SDK is full. To prevent data loss,
+					// we flush the buffer (which is a blocking operation) and try again.
+					w.Log.Debug("SDK buffer overrun. Forcibly flushing the buffer")
```
Comment (Hipska) [inline plugins/outputs/wavefront/wavefront.go:128]:
```suggestion
					w.Log.Debug("SDK buffer overrun, forcibly flushing the buffer")
```

**Review by Hipska — COMMENTED** [review]
I'm not really following what you are trying to do here. If I read the original code, it was also flushing the buffer and then retry sending on next interval.

So you want the retry happen already in the same interval? I think you could reuse the `if isRetryable(err)` block for that..

**Comment by astp-okta** [comment]
!signed-cla

**Comment by astp-okta** [comment]
> I'm not really following what you are trying to do here. If I read the original code, it was also flushing the buffer and then retry sending on next interval.
> 
> So you want the retry happen already in the same interval? I think you could reuse the `if isRetryable(err)` block for that..

Yes exactly it seems the retry is necessary to happen in the same interval and based on testing, it seems the first check to flush the buffer causes telegraf to crash before it reaches the next interval to retry. I have not yet tried reusing the `if isRetryable(err)`, but instead decided to search directly for the one error that seems to create this edge case, `buffer full, dropping line` to minimize the change's effect on other error scenarios.

File: plugins/outputs/wavefront/wavefront.go [hunk 3]
```diff
@@ -122,21 +122,24 @@ func (w *Wavefront) Write(metrics []telegraf.Metric) error {
...
-					if flushErr := w.sender.Flush(); flushErr != nil {
-						w.Log.Errorf("wavefront flushing error: %v", flushErr)
+				if strings.Contains(err.Error(), "buffer full, dropping line") {
+					// The internal buffer in the Wavefront SDK is full. To prevent data loss,
+					// we flush the buffer (which is a blocking operation) and try again.
+					w.Log.Debug("SDK buffer overrun, forcibly flushing the buffer")
+					err = w.sender.Flush()
+					if err != nil {
+						return err
 					}
```
Comment (Hipska) [inline plugins/outputs/wavefront/wavefront.go:132]:
```suggestion
					if err = w.sender.Flush(); err != nil {
						return fmt.Errorf("wavefront flushing error: %w", err)
					}
```

**Review by Hipska — CHANGES_REQUESTED** [review]

**Comment by Hipska** [comment]
Could you merge current master branch? I think that might solve the linter problem.

**Comment by astp-okta** [comment]
> Could you merge current master branch? I think that might solve the linter problem.
I caught the fork up to main master branch, is that what you meant?

File: plugins/outputs/wavefront/wavefront.go [hunk 4]
```diff
@@ -123,20 +123,22 @@ func (w *Wavefront) Write(metrics []telegraf.Metric) error {
...
-					return fmt.Errorf("wavefront sending error: %w", err)
+					// Try again.
+					err = w.sender.SendMetric(point.Metric, point.Value, point.Timestamp, point.Source, point.Tags)
+				}
+				if err != nil {
+					if isRetryable(err) {
+						return fmt.Errorf("wavefront sending error: %w", err)
+					}
+					w.Log.Errorf("non-retryable error during Wavefront.Write: %v", err)
+					w.Log.Debugf("Non-retryable metric data: Name: %v, Value: %v, Timestamp: %v, Source: %v, PointTags: %v ", point.Metric, point.Value, point.Timestamp, point.Source, point.Tags)
```
Comment (Hipska) [inline plugins/outputs/wavefront/wavefront.go:140]: Linter is complaining this line is too long, consider this:
```suggestion
					w.Log.Debugf("non-retryable metric data: %+v", point)
```

**Review by Hipska — CHANGES_REQUESTED** [review]

File: plugins/outputs/wavefront/wavefront.go [hunk 5]
```diff
@@ -123,20 +123,22 @@ func (w *Wavefront) Write(metrics []telegraf.Metric) error {
 			err := w.sender.SendMetric(point.Metric, point.Value, point.Timestamp, point.Source, point.Tags)
 			if err != nil {
 				if isRetryable(err) {
-					if flushErr := w.sender.Flush(); flushErr != nil {
-						w.Log.Errorf("wavefront flushing error: %v", flushErr)
+					// The internal buffer in the Wavefront SDK is full. To prevent data loss,
+					// we flush the buffer (which is a blocking operation) and try again.
```
Comment (powersj) [inline plugins/outputs/wavefront/wavefront.go:127]: Can you help me understand this comment. Does a retryable error always mean that the buffer is full? Based on the comments on `isRetryable` everything is retryable except an empty metric name.

File: plugins/outputs/wavefront/wavefront.go [hunk 6]
```diff
@@ -123,20 +123,22 @@ func (w *Wavefront) Write(metrics []telegraf.Metric) error {
...
+					w.Log.Debug("SDK buffer overrun, forcibly flushing the buffer")
+					if err = w.sender.Flush(); err != nil {
+						return fmt.Errorf("wavefront flushing error: %w", err)
 					}
-					return fmt.Errorf("wavefront sending error: %w", err)
+					// Try again.
+					err = w.sender.SendMetric(point.Metric, point.Value, point.Timestamp, point.Source, point.Tags)
```
Comment (powersj) [inline plugins/outputs/wavefront/wavefront.go:133]: Can we check the error again directly here in the same block, this will clean up the logic below as well, as it is weird to start with `isRetryable` above and then check again below.

**Review by powersj — COMMENTED** [review]
Thanks - just a couple questions

File: plugins/outputs/wavefront/wavefront.go (hunk 5 above)
Comment (astp-okta) [reply plugins/outputs/wavefront/wavefront.go:127]: Yeah, I believe `isRetryable` includes more than just the buffer full. From our testing, it is in that interval due where the buffer full error surfaces.

File: plugins/outputs/wavefront/wavefront.go (hunk 6 above)
Comment (astp-okta) [reply plugins/outputs/wavefront/wavefront.go:133]: good point, might as well check in the same block to improve readability

File: plugins/outputs/wavefront/wavefront.go [hunk 7]
```diff
@@ -123,20 +123,22 @@ func (w *Wavefront) Write(metrics []telegraf.Metric) error {
...
+						return fmt.Errorf("wavefront flushing error: %w", err)
+					}
+					// Try again.
+					err = w.sender.SendMetric(point.Metric, point.Value, point.Timestamp, point.Source, point.Tags)
+					if err != nil {
+						if isRetryable(err) {
+							return fmt.Errorf("wavefront sending error: %w", err)
+						}
+						w.Log.Errorf("non-retryable error during Wavefront.Write: %v", err)
+						w.Log.Debugf("non-retryable metric data: %+v", point)
```
Comment (powersj) [inline plugins/outputs/wavefront/wavefront.go:139]: I think you still want these outside the original isRetryable check

**Review by powersj — COMMENTED** [review]
one final comment, think you moved the two log messages in too far

File: plugins/outputs/wavefront/wavefront.go (hunk 7 above)
Comment (astp-okta) [reply plugins/outputs/wavefront/wavefront.go]: ah thank you for flagging, my mistake

**Review by srebhan — APPROVED** [review]
Thanks for fixing this @astp-okta!
