### PR TITLE
fix(inputs.opcua): Handle session invalidation between gather cycles

### LINKED ISSUE #16735: OPCUA Input Plugin `reading registered nodes failed after 1 attempts` even when setting `use_unregistered_reads = true`
### Relevant telegraf.conf

```toml
[[inputs.opcua]]
  name = "kepware"
  endpoint = "opc.tcp://{domain}:49320"
  connect_timeout = "10s"
  request_timeout = "5s"
  session_timeout = "20m"
  interval = "{interval}"
  collection_offset = "{collection_offset}"
  security_policy = "Basic256Sha256"
  security_mode = "SignAndEncrypt"
  auth_method = "UserName"
  username = "{kep_user}"
  password = "{kep_pass}"
  timestamp = "source"
  client_trace = false
  tagexclude = ["host", "id"]
  fieldexclude = ["Quality"]
  nodes = [
    {nodes}
  ]
  [inputs.opcua.request_workarounds]
    use_unregistered_reads = true
```

### Logs from Telegraf

```text
2025-04-07T17:20:50Z E! [inputs.opcua] Error in plugin: reading registered nodes failed after 1 attempts: The session id is not valid. StatusBadSessionIDInvalid (0x80250000)
2025-04-07T17:20:55Z E! [inputs.opcua] Error in plugin: reading registered nodes failed after 1 attempts: The session id is not valid. StatusBadSessionIDInvalid (0x80250000)
2025-04-07T17:21:00Z E! [inputs.opcua] Error in plugin: reading registered nodes failed after 1 attempts: The session id is not valid. StatusBadSessionIDInvalid (0x80250000)
2025-04-07T17:21:05Z E! [inputs.opcua] Error in plugin: reading registered nodes failed after 1 attempts: The session id is not valid. StatusBadSessionIDInvalid (0x80250000)
2025-04-07T17:21:10Z E! [inputs.opcua] Error in plugin: reading registered nodes failed after 1 attempts: The session id is not valid. StatusBadSessionIDInvalid (0x80250000)
2025-04-07T17:21:15Z E! [inputs.opcua] Error in plugin: reading registered nodes failed after 1 attempts: The session id is not valid. StatusBadSessionIDInvalid (0x80250000)
2025-04-07T17:21:20Z E! [inputs.opcua] Error in plugin: reading registered nodes failed after 1 attempts: The session id is not valid. StatusBadSessionIDInvalid (0x80250000)
2025-04-07T17:21:25Z E! [inputs.opcua] Error in plugin: reading registered nodes failed after 1 attempts: The session id is not valid. StatusBadSessionIDInvalid (0x80250000)
2025-04-07T17:21:30Z E! [inputs.opcua] Error in plugin: reading registered nodes failed after 1 attempts: The session id is not valid. StatusBadSessionIDInvalid (0x80250000)
2025-04-07T17:21:35Z E! [inputs.opcua] Error in plugin: reading registered nodes failed after 1 attempts: The session id is not valid. StatusBadSessionIDInvalid (0x80250000)
2025-04-07T17:21:40Z E! [inputs.opcua] Error in plugin: reading registered nodes failed after 1 attempts: The session id is not valid. StatusBadSessionIDInvalid (0x80250000)
2025-04-07T17:21:45Z E! [inputs.opcua] Error in plugin: reading registered nodes failed after 1 attempts: The session id is not valid. StatusBadSessionIDInvalid (0x80250000)
```

### System info

public.ecr.aws/docker/library/telegraf:1.34.0-alpine

### Docker

_No response_

### Steps to reproduce

1. Start up telegraf with the included config
2. View the logs
3. See the `reading registered nodes failed after 1 attempts` error

### Expected behavior

`reading registered nodes failed after 1 attempts` is not expected in the logs when setting `use_unregistered_reads = true`

### Actual behavior

`reading registered nodes failed after 1 attempts` shows up in the logs

### Additional info

I am communicating with KepServerEX 6.14

### PR DESCRIPTION
**Pull request by skartikey**
## Summary

The OPC UA plugin encountered an alternating success/failure pattern when using the `use_unregistered_reads = true` setting. This manifested as:

1. First read would succeed
2. Second read would fail with `StatusBadSessionIDInvalid` error
3. Third read would succeed
4. Fourth read would fail again

This occurred because even with `use_unregistered_reads = true`, the plugin wasn't properly handling session invalidation between gather cycles. When a server invalidated the session (which happens periodically in most OPC UA servers), the client attempted to use the same session on the next read operation. Since the session was no longer valid, this caused errors every other gather cycle.

## Fix Details

The fix addresses this by:

1. Adding a `lastSessionError` flag to track when session errors occur
2. Modifying the connection management to force reconnection when a session error is detected
3. Adding a consecutive error counter to detect and recover from persistent connection issues
4. Improving error messages to accurately reflect whether registered or unregistered nodes are being used

These changes ensure that after a session error, the next gather cycle performs a full reconnection and establishes a fresh session, rather than trying to reuse the invalid one.

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #16735

### CODE REVIEW

**Review by srebhan — COMMENTED** [review]
Thanks @skartikey for the fix! Some comments/questions in the code...

File: plugins/inputs/opcua/opcua.go [hunk 1]
```diff
@@ -28,16 +31,26 @@ func (*OpcUA) SampleConfig() string {
...
 func (o *OpcUA) Gather(acc telegraf.Accumulator) error {
 	// Will (re)connect if the client is disconnected
 	metrics, err := o.client.currentValues()
 	if err != nil {
+		o.consecutiveErrors++
+		// If we've had multiple consecutive errors, force session invalidation
+		// to ensure the next gather cycle will perform a full reconnection
+		if o.consecutiveErrors > 1 {
+			o.client.lastSessionError = true
+		}
```
[the remark this answers is not in the document]
Comment (skartikey) [reply plugins/inputs/opcua/opcua.go:47]: In OPC UA communication, not all errors require a full reconnection. Some errors are transient (network glitches, timing issues) and may resolve on the next attempt without needing to rebuild the entire session. Forcing session invalidation and reconnection on every single error would be inefficient.

File: plugins/inputs/opcua/read_client.go [hunk 2]
```diff
@@ -158,26 +173,52 @@ func (o *readClient) read() error {
...
+		return "unregistered"
+	}
+	return "registered"
+}
+
+// SimulateSessionInvalidation forces the client to mark the session as invalid
+// to test recovery behavior. This is exposed primarily for testing.
+func (o *readClient) SimulateSessionInvalidation() {
+	o.lastSessionError = true
+}
```
[the remark this answers is not in the document]
Comment (srebhan) [reply plugins/inputs/opcua/read_client.go:223]: And I don't like those "only for testing" functions as they introduce unnecessary code and increase the binary! The tests are living in the same package as the implementation so there naturally is no encapsulation anyway! For the clarity argument:

```golang
// Simulate session invalidation e.g. due to network error or server reset
client.lastSessionError = true
```

Furthermore, the clarity can be enhanced throughout the code by changing `client.lastSessionError` to `client.sessionInvalid`... ;-)

File: plugins/inputs/opcua/opcua.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (skartikey) [reply plugins/inputs/opcua/opcua.go]: @srebhan added the config for the reconnect error threshold

File: plugins/inputs/opcua/read_client.go [hunk 3]
```diff
@@ -55,18 +60,26 @@ func (rc *readClientConfig) createReadClient(log telegraf.Logger) (*readClient,
 		rc.ReadRetryTimeout = config.Duration(100 * time.Millisecond)
 	}
 
+	// Set default for ReconnectErrorThreshold if not configured
+	reconnectThreshold := rc.ReconnectErrorThreshold
+	if reconnectThreshold == 0 {
+		reconnectThreshold = 1 // Default value
+	}
+
```
Comment (srebhan) [inline plugins/inputs/opcua/read_client.go:68]: I don't think this is necessary as a threshold of zero should work the same way as one...

File: plugins/inputs/opcua/read_client.go [hunk 4]
```diff
@@ -158,26 +181,46 @@ func (o *readClient) read() error {
...
+		lastErr = err
+
+		isSessionError := errors.Is(err, ua.StatusBadSessionIDInvalid) ||
+			errors.Is(err, ua.StatusBadSessionNotActivated) ||
+			errors.Is(err, ua.StatusBadSecureChannelIDInvalid)
+
+		// Flag session error for next cycle if encountered
+		if isSessionError {
+			o.lastSessionError = true
+		}
```
Comment (srebhan) [inline plugins/inputs/opcua/read_client.go:201]:
```suggestion
		// Flag session error for next cycle if encountered
		if errors.Is(err, ua.StatusBadSessionIDInvalid) ||
		   errors.Is(err, ua.StatusBadSessionNotActivated) ||
		   errors.Is(err, ua.StatusBadSecureChannelIDInvalid) {
			o.forceReconnect = true
		}
```

File: plugins/inputs/opcua/read_client.go [hunk 5]
```diff
@@ -158,26 +181,46 @@ func (o *readClient) read() error {
...
+				nodeTypeLabel(o.Workarounds.UseUnregisteredReads), count, lastErr)
+		case isSessionError:
 			// Retry after the defined period as session and channels should be refreshed
 			o.Log.Debugf("reading failed with %v, retry %d / %d...", err, count, o.ReadRetries)
 			time.Sleep(o.ReadRetryTimeout)
 		default:
 			// Non-retryable error, there is nothing we can do
-			return fmt.Errorf("reading registered nodes failed: %w", err)
+			return fmt.Errorf("reading %s nodes failed: %w",
+				nodeTypeLabel(o.Workarounds.UseUnregisteredReads), err)
```
Comment (srebhan) [inline plugins/inputs/opcua/read_client.go:215]:
```suggestion
			return fmt.Errorf("reading %s nodes failed: %w", 				nodeTypeLabel(o.Workarounds.UseUnregisteredReads), err)
```

File: plugins/inputs/opcua/opcua_test.go [hunk 6]
```diff
@@ -437,3 +437,177 @@ use_unregistered_reads = true
 	require.EqualValues(t, map[string]string{"tag1": "override", "tag2": "val2"}, o.client.NodeMetricMapping[3].MetricTags)
 	require.EqualValues(t, map[string]string{"tag1": "val1", "tag2": "val2"}, o.client.NodeMetricMapping[4].MetricTags)
 }
+
+func TestUnregisteredReadsAndSessionRecovery(t *testing.T) {
```
Comment (srebhan) [inline plugins/inputs/opcua/opcua_test.go:441]: Integration tests must have `Integration` in their name otherwise they will never be executed (see [Makefile](https://github.com/influxdata/telegraf/blob/c31d402b7295e07a7279da8d16bf9f93367d98ba/Makefile#L154))!

Same for the other integration test below...

File: plugins/inputs/opcua/read_client.go [hunk 7]
```diff
@@ -150,6 +171,8 @@ func (o *readClient) read() error {
 	}
 
 	var count uint64
+	var lastErr error
```
[the remark this answers is not in the document]
Comment (skartikey) [reply plugins/inputs/opcua/read_client.go:174]: Initially thought `lastErr` was necessary due to variable scoping concerns with `err` being reassigned each iteration. However, since `lastErr = err` happens immediately after each `Read` call with no intervening code, both variables always have identical values when the loop exits. Removing the redundant `lastErr` and using `err` directly in the final error message.

File: plugins/inputs/opcua/read_client.go (hunk 4 above)
Comment (skartikey) [reply plugins/inputs/opcua/read_client.go:201]: `isSessionError` is getting used in the switch case as well, that's why I put it in a variable.

Comment (srebhan) [reply plugins/inputs/opcua/read_client.go:201]: Looking closer on this, why do you move this out of the `switch` statement? You could set `forceReconnect` in there too.

Comment (skartikey) [reply plugins/inputs/opcua/read_client.go]: The `if isSessionError` must stay separate from the switch case. We need to set `o.forceReconnect = true` for EVERY session error (including when retries are exhausted), but the `case isSessionError:` only handles retry logic when we haven't exceeded the limit. Moving it into the case would miss setting the flag when `count > o.ReadRetries`.

**Review by srebhan — APPROVED** [review]
Thanks @skartikey!

**Review by mstrandboge — APPROVED** [review]

**Comment by marcv81** [comment]
FYI: https://github.com/influxdata/telegraf/issues/17014

**Comment by jminardi** [comment]
I tried running the latest code (1.34.4) and I am still seeing the alternating success/failure loop. Reading through the code it seems like this PR didn't really fix the core problem as it still needs to detect a failure before performing a full reconnect attempt. When I am doing long polling intervals (greater than 1m) I always get a failure in between each success.

Maybe I am misunderstanding how to properly use this new code. What specific settings should I be using to prevent the alternating failure scenario?

**Comment by skartikey** [comment]
@jminardi I did some investigation and this is what's happening.

The `reconnect_error_threshold` setting controls how many consecutive errors trigger a forced reconnection, but it still requires **at least one failure** to detect session issues. With long polling intervals (>1 minute), OPC UA sessions often become stale between reads, leading to the alternating pattern you're experiencing:

1. First read fails (stale session detected)
2. Reconnection is forced for next cycle  
3. Second read succeeds (fresh session)
4. Session becomes stale again during long wait
5. Cycle repeats

Currently, the code prevents setting `reconnect_error_threshold = 0` because it forces any zero value to default to 1. However, I'll submit a change that allows `reconnect_error_threshold = 0` to enable reconnection before every read attempt - this will be particularly useful for long polling intervals like yours.

The fix will distinguish between "not configured" (uses default of 1) versus "explicitly set to 0" (forces reconnection every cycle), giving you the proactive reconnection behavior you need to eliminate the alternating success/failure pattern.

**Comment by jminardi** [comment]
@skartikey Thank you, that sounds perfect!
