### PR TITLE
Run scheduled flushes in background

### LINKED ISSUE #2262: Flush jitter causes input collection to freeze
During my tests it looks like flush_jitter causes input plugins to freeze the collection. 

To reproduce this quickly is rather easy:

1. Set interval to a small value, eg. 10s
2. Set flush_jitter to a bigger value than interval, eg. 20s
3. Set a frequent flush_interval, eg. 1s (so chances are higher of getting flush_jitter bigger than interval to be able to see the errors)

I could reproduce this on version 1.1.x and in the master branch.

### Actual behavior
Error messages like: 
` E! ERROR: input [inputs.cpu] took longer to collect than collection interval (10s)`

And debug messages like:
` D! Input [inputs.cpu] gathered metrics, (10s interval) in 33.689740435s`

### Expected behavior
Collection should work as usual, flush should be handled accordingly with the jitter delay

### PR DESCRIPTION
**Pull request by sparrc**
doing this unblocks incoming metrics while waiting for a flush to take
place.

we have to create a semaphore so that we can
'skip' flushes that try to run while a flush is already running.

closes #2262

### Required for all PRs:

- [x] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] README.md updated (if adding a new plugin)

### CODE REVIEW

File: agent/agent.go [hunk 1]
```diff
@@ -295,8 +296,18 @@ func (a *Agent) flusher(shutdown chan struct{}, metricC chan telegraf.Metric) er
...
-			a.flush()
+			go func() {
+				select {
+				case semaphore <- struct{}{}:
+					internal.RandomSleep(a.Config.Agent.FlushJitter.Duration, shutdown)
+					a.flush()
+					<-semaphore
+				default:
+					// skipping this flush because one is already happening
+					log.Println("D! Skipping a scheduled flush because there is" +
```
Comment (phemmer) [inline agent/agent.go]: I think this would be better as a warning. If the flush operation is taking so long that it's overlapping into the next flush, then the admin should investigate. Either their flush interval is too short, or something is causing a slow down.

Comment (sparrc) [inline agent/agent.go]: true, I'll make it a warning
