### PR TITLE
fix(inputs.internet_speed): Fix server_id_include filter logic

### LINKED ISSUE #18408: internet_speed server_id_include not working
### Relevant telegraf.conf

```toml
[[inputs.internet_speed]]
  interval = "1m"
  server_id_include = ["71497"]
```

### Logs from Telegraf

```text
2026-02-24T11:28:55Z D! [outputs.http] Buffer fullness: 0 / 10000 metrics
2026-02-24T11:29:00Z D! [inputs.system] Reading users: open /var/run/utmp: no such file or directory
2026-02-24T11:29:00Z D! [inputs.internet_speed] using server 17449 in Leeds (speedtest.razorblue.net.uk.prod.hosts.ooklaserver.net:8080)
2026-02-24T11:29:05Z D! [inputs.system] Reading users: open /var/run/utmp: no such file or directory
2026-02-24T11:29:05Z D! [outputs.http] Wrote batch of 60 metrics in 1.143758ms
2026-02-24T11:29:05Z D! [outputs.http] Buffer fullness: 0 / 10000 metrics
```

### System info

Telegraf 1.37.3, Ubuntu 24.04, Docker version 29.2.1

### Docker

_No response_

### Steps to reproduce

1. Run telegraf container with config to target a specific server for speed test.

### Expected behavior

internet_speed should only use the server id provided in `server_id_include`

### Actual behavior

different servers are used, possibly automatically chosen as the server does vary

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skartikey**
## Summary

The server selection loop mixed filter matching with a latency fallback in the same iteration, causing server_id_include to be silently ignored when the target server ID was not present in the fetched server list.
Additionally, the include filter default was inverted (false instead of true), meaning the filter never actually matched when unconfigured, selection relied entirely on the fallback latency path.

Fixes the selection logic to properly skip non-matching servers and return an error when filters are configured but no servers match, instead of silently falling back to an unrelated server.

## Checklist

- [x] No AI generated code was used in this PR
- [ ] AI generated code used in this PR follows the [InfluxData Policy on AI-Generated Code Contributions][policy]

[policy]: https://www.influxdata.com/ai-generated-code-contributions-policy

## Related issues

resolves #18408

### CODE REVIEW

File: plugins/inputs/internet_speed/internet_speed.go [hunk 1]
```diff
@@ -170,30 +170,33 @@ func (is *InternetSpeed) findClosestServer() error {
...
-			if minLatency > server.Latency.Milliseconds() {
-				minLatency = server.Latency.Milliseconds()
-				selectIndex = index
-			}
+		if server.Latency > 0 && server.Latency.Milliseconds() < minLatency {
+			minLatency = server.Latency.Milliseconds()
+			selectIndex = index
+		} else if selectIndex == -1 {
+			selectIndex = index
 		}
```
Comment (srebhan) [inline plugins/inputs/internet_speed/internet_speed.go]: I think this is correct but wouldn't

```suggestion
		if selectIndex == -1 {
			// Select the first server we found and store the latency if it is valid
			selectIndex = index
			if server.Latency > 0 {
				minLatency = server.Latency.Milliseconds()
			}
		} else if server.Latency > 0 && server.Latency.Milliseconds() < minLatency {
			// Select the server if it has a lower latency than the previous one
			selectIndex = index
			minLatency = server.Latency.Milliseconds()
		}
```

this be more obvious?

File: plugins/inputs/internet_speed/internet_speed_test.go [hunk 2]
```diff
@@ -2,12 +2,104 @@ package internet_speed
...
 	"testing"
+	"time"
 
+	"github.com/showwin/speedtest-go/speedtest"
 	"github.com/stretchr/testify/require"
 
 	"github.com/influxdata/telegraf/testutil"
 )
 
+func TestSelectServerIncludeFilter(t *testing.T) {
```
Comment (srebhan) [inline plugins/inputs/internet_speed/internet_speed_test.go]: Can we please split this test into one where we expect errors and one where we don't?!

Comment (skartikey) [reply plugins/inputs/internet_speed/internet_speed_test.go]: Good suggestion, did the changes.
