### PR TITLE
Prevent connection leak by closing unused connections in amqp output

### LINKED ISSUE #4921: AMQP output with max_messages > 0 keeps opening new connections
### Relevant telegraf.conf:
```
[[outputs.amqp]]
brokers = [ "amqps://rabbit1:5671/", "amqps://rabbit2:5671/", "amqps://rabbit3:5671/",]
username = "foo"
password = "bar"
max_messages = 100
exchange = "telegraf"
delivery_mode = "persistent"
tls_ca = "/etc/telegraf/ssl/ca-chain.crt"
tls_key = "/etc/telegraf/ssl/telegraf-client.key"
tls_cert = "/etc/telegraf/ssl/telegraf-client.crt"
```
### System info:
```
Ubuntu 16.04.5 LTS
Telegraf 1.8.2 (git: HEAD 996a91f2)
```

### Repro steps
1. setup 1+ rabbitmq instances
2. configure telegraf to publish to rabbitmq
3. set max_messages (perhaps to a low value) and wait

### Expected behavior:
Whenever a new connection is established due to reaching `max_messages`, the old connections should be closed.

### Actual behavior:
Connection amount seems to increase indefinitely, which consumes memory and sockets.

### PR DESCRIPTION
**Pull request by glinton**
Resolves #4921

### CODE REVIEW

File: plugins/outputs/amqp/amqp.go [hunk 1]
```diff
@@ -249,7 +249,7 @@ func (q *AMQP) Write(metrics []telegraf.Metric) error {
 
 	if q.sentMessages >= q.MaxMessages && q.MaxMessages > 0 {
 		log.Printf("D! Output [amqp] sent MaxMessages; closing connection")
-		q.client = nil
+		q.client.Close()
```
Comment (danielnelson) [inline plugins/outputs/amqp/amqp.go]: I think we need to set q.client = nil afterwards since this triggers a new connection in publish.
