### PR TITLE
fix(agent): Error out if configuration directory is not readable

### LINKED ISSUE #16600: Telegraf silently ignores config directory when permission denied
### Relevant telegraf.conf

```toml
N/A
```

### Logs from Telegraf

```text
2025-03-09T15:28:14Z I! Loading config: /etc/telegraf/telegraf.conf
2025-03-09T15:28:14Z I! Starting Telegraf 1.33.3 brought to you by InfluxData the makers of InfluxDB
2025-03-09T15:28:14Z I! Available plugins: 236 inputs, 9 aggregators, 33 processors, 26 parsers, 63 outputs, 6 secret-stores
2025-03-09T15:28:14Z I! Loaded inputs: cpu disk diskio kernel mem processes swap system
2025-03-09T15:28:14Z I! Loaded aggregators:
2025-03-09T15:28:14Z I! Loaded processors:
2025-03-09T15:28:14Z I! Loaded secretstores:
2025-03-09T15:28:14Z I! Loaded outputs: influxdb_v2
2025-03-09T15:28:14Z I! Tags enabled: host=154a69e9fc65
2025-03-09T15:28:14Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"154a69e9fc65", Flush Interval:10s
2025-03-09T15:28:14Z W! [agent] The default value of 'skip_processors_after_aggregators' will change to 'true' with Telegraf v1.40.0! If you need the current default behavior, please explicitly set the option to 'false'!
2025-03-09T15:28:14Z D! [agent] Initializing plugins
2025-03-09T15:28:14Z D! [agent] Connecting outputs
2025-03-09T15:28:14Z D! [agent] Attempting connection to [outputs.influxdb_v2]
2025-03-09T15:28:14Z D! [agent] Successfully connected to outputs.influxdb_v2
2025-03-09T15:28:14Z D! [agent] Starting service inputs
2025-03-09T15:28:20Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/sys/firmware/efi/efivars"): no such file or directory
2025-03-09T15:28:20Z D! [inputs.system] Reading users: open /var/run/utmp: no such file or directory
2025-03-09T15:28:20Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/dev/hugepages"): no such file or directory
2025-03-09T15:28:20Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-sysusers.service"): no such file or directory
2025-03-09T15:28:20Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-tmpfiles-setup-dev.service"): no such file or directory
....
```

### System info

Telegraf 1.33.3 on Docker

### Docker

```yaml
version: '3.2'

services:
  [...]
  telegraf:
    image: telegraf:latest
    command: telegraf --config-directory /etc/telegraf/telegraf.d --debug
    pid: "host"
    ports:
      - "8092:8092"
      - "8094:8094"
      - "8125:8125"
    volumes:
      - ./config/telegraf:/etc/telegraf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /etc:/host/etc:ro
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
    restart: always
```

### Steps to reproduce

1. Create a /etc/telegraf/telegraf.conf that _is_ readable by telegraf
2. Create a /etc/telegraf/telegraf.d directory with configurations that is not readable by telegraf
3. Start Telegraf with or without `--config-directory /etc/telegraf/telegraf.d`

### Expected behavior

Telegraf should throw an error and refuse to start up when it cannot read the configuration directory.

### Actual behavior

Telegraf starts and only reads the telegraf.conf file but ignores the configuration directory.

### Additional info

```$ ls -la config/telegraf
total 250
drwxr-xr-x 3 root root      4 Mar  9 16:26 .
drwxr-xr-x 4 root root      5 Mar  9 15:57 ..
-rw-r--r-- 1 root root 381175 Mar  9 15:52 telegraf.conf
drwx------ 2 root root      6 Mar  9 15:46 telegraf.d
```

### PR DESCRIPTION
**Pull request by srebhan**
## Summary

Currently Telegraf will **silently** ignore any configuration directory specified via command-line if this directory cannot be read by the Telegraf user. This is bad because users will see missing plugins but get no indication whatsoever on what is going on.

This PR will error out if the directory cannot be read.

## Checklist

- [x] No AI generated code was used in this PR
- [ ] AI generated code used in this PR follows the [InfluxData Policy on AI-Generated Code Contributions][policy]

[policy]: https://www.influxdata.com/ai-generated-code-contributions-policy

## Related issues

resolves #16600

### CODE REVIEW

File: cmd/telegraf/telegraf_test.go [hunk 1]
```diff
@@ -0,0 +1,175 @@
...
+				require.NoError(t, os.Chmod(filepath.Join(root, entry), perm))
+			}
+			// Make sure we can delete the directory
+			defer func() {
+				//nolint:gosec // It's okay to set permissions to rwx------ for the temporary dir
+				require.NoError(t, os.Chmod(filepath.Join(root, "telegraf.d"), 0700))
+			}()
+
+			// Setup Telegraf
+			internal.Version = "0.0.0"
```
Comment (skartikey) [inline cmd/telegraf/telegraf_test.go:199]: This mutates a global without cleanup, which could affect parallel tests. A `t.Cleanup` to restore the original value would make it safe.

File: cmd/telegraf/telegraf_test.go [hunk 2]
```diff
@@ -0,0 +1,226 @@
...
+	"syscall"
+	"testing"
+
+	"github.com/stretchr/testify/require"
+
+	"github.com/influxdata/telegraf/internal"
+)
+
+func TestGetConfigFiles(t *testing.T) {
+	// Drop priviledges as user root as root can access any file despite
```
Comment (skartikey) [inline cmd/telegraf/telegraf_test.go]:
```suggestion
	// Drop privileges as user root as root can access any file despite
```

File: cmd/telegraf/telegraf_test.go [hunk 3]
```diff
@@ -0,0 +1,226 @@
...
+	// restricted permissions
+	if os.Geteuid() == 0 {
+		if runtime.GOOS != "linux" {
+			t.Skip("Dropping priviledges is only supported on Linux")
```
Comment (skartikey) [inline cmd/telegraf/telegraf_test.go]:
```suggestion
			t.Skip("Dropping privileges is only supported on Linux")
```

File: cmd/telegraf/telegraf_test.go [hunk 4]
```diff
@@ -0,0 +1,226 @@
...
+		filepath.Join(root, "telegraf.d", "inputs.conf"),
+		filepath.Join(root, "telegraf.d", "outputs.conf"),
+	}
+	require.NoError(t, agent.getConfigFiles())
+	require.ElementsMatch(t, expected, agent.configFiles)
+}
+
+func TestLoadConfigurationsPermissions(t *testing.T) {
+	if os.Geteuid() == 0 {
+		t.Skip("Dropping priviledges is only supported on Linux")
```
Comment (skartikey) [inline cmd/telegraf/telegraf_test.go]:
```suggestion
		t.Skip("Dropping privileges is only supported on Linux")
```

File: cmd/telegraf/telegraf_test.go [hunk 5]
```diff
@@ -0,0 +1,226 @@
...
+				"telegraf.conf",
+				filepath.Join("telegraf.d", "inputs.conf"),
+				filepath.Join("telegraf.d", "outputs.conf"),
+			},
+		},
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			// Drop priviledges as user root as root can access any file despite
```
Comment (skartikey) [inline cmd/telegraf/telegraf_test.go]:
```suggestion
			// Drop privileges as user root as root can access any file despite
```

File: cmd/telegraf/telegraf_test.go [hunk 6]
```diff
@@ -0,0 +1,226 @@
...
+	root := t.TempDir()
+
+	// Top-level configuration file containing a minimal agent section
+	content := `
+[agent]
+  interval = "10s"
+`
+	require.NoError(t, os.WriteFile(filepath.Join(root, "telegraf.conf"), []byte(content), 0600))
+
+	// Create a configuration directory containg two files
```
Comment (skartikey) [inline cmd/telegraf/telegraf_test.go]:
```suggestion
	// Create a configuration directory containing two files
```

File: cmd/telegraf/telegraf_test.go [hunk 7]
```diff
@@ -0,0 +1,226 @@
...
+			root := t.TempDir()
+
+			// Top-level configuration file containing a minimal agent section
+			content := `
+[agent]
+  interval = "10s"
+`
+			require.NoError(t, os.WriteFile(filepath.Join(root, "telegraf.conf"), []byte(content), 0600))
+
+			// Create a configuration directory containg two files
```
Comment (skartikey) [inline cmd/telegraf/telegraf_test.go]:
```suggestion
			// Create a configuration directory containing two files
```
