### PR TITLE
fix(inputs.win_wmi): Free resources to avoid leaks

### LINKED ISSUE #16179: [[inputs.win_wmi]] dropped values - Error in plugin: Object server is stopping when OLE service contacts it
### Relevant telegraf.conf

```toml
[[inputs.win_wmi]]
   name_override = "mymeasurement"
   interval = "1m"

   [[inputs.win_wmi.method]]
     namespace = 'root\default'
     class_name = "StdRegProv"
     method = "GetDWordValue"
     [inputs.win_wmi.method.arguments]
       hDefKey = '2147483650'
       sSubKeyName = 'Software\Microsoft\windows NT\CurrentVersion'
       sValueName = 'UBR'
     [inputs.win_wmi.method.fields]
       uValue = "ole_stop_test01"

  [[inputs.win_wmi.method]]
    namespace = 'root\default'
    class_name = "StdRegProv"
    method = "GetStringValue"
    [inputs.win_wmi.method.arguments]
      hDefKey = '2147483650'
      sSubKeyName = 'Software\Microsoft\windows NT\CurrentVersion'
      sValueName = 'CurrentBuild'
    [inputs.win_wmi.method.fields]
         sValue = "ole_stop_test02"
```

### Logs from Telegraf

```text
[inputs.win_wmi] Error in plugin: Object server is stopping when OLE service contacts it
```

### System info

Telegraf 1.31.3, 1.32.1 e.g. Windows 2019/2016

### Docker

_No response_

### Steps to reproduce

1. Run given telegraf config (query at least two values with `[[inputs.win_wmi.method]]`
2. Usually after some hours You will see inside Telegraf log ERROR messages "_[inputs.win_wmi] Error in plugin: Object server is stopping when OLE service contacts it_"
3. When this error occurs, `[[inputs.win_wmi.method]]` does not successfully query value, so "sValue" is null/empty/<no value>

### Expected behavior

In case of this error "Object server is stopping when OLE service contacts it" (CO_E_SERVER_STOPPING 0x80080008), Telegraf should retry query until inputs timeout has been reached or try to avoid this error.

### Actual behavior

Error occurs and metric is not created.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by srebhan**
## Summary

This PR attempts to fix the issues seen in #16179. While I'm not able to reproduce the issues, it seems like restricting the threading model for calling the COM object more to a serialized chain for each thread. Furthermore, the PR adds error prefixes to better localize the error and makes error handling more strict. Additionally, the PR frees the `property` resource properly which could otherwise lead to a memory leak.

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

based on #16781 
resolves #16179

### CODE REVIEW

**Review by skartikey — COMMENTED** [review]
Not directly related to your changes, but I noticed this line:

```go
outputRaw, err := service.CallMethod("ExecMethod", "StdRegProv", m.Method, inputParamsRaw)
```

Would it make sense to replace the hardcoded `"StdRegProv"` with `m.ClassName` for flexibility?

```go
outputRaw, err := service.CallMethod("ExecMethod", m.ClassName, m.Method, inputParamsRaw)
```

Also, it looks like only some COM objects are being released. Every COM object created via `ToIDispatch()` should have a corresponding `Release()` call. It might be worth adding:
```go
defer service.Release()
defer class.Release()
defer classMethods.Release()
// and so on...
```

Let me know your thoughts on this!

**Comment by srebhan** [comment]
@skartikey moved out the threading model fix to #16781 and fixed the hard-coded class-method in #16782. Will update this PR to free the resources correctly shortly. Thanks for spotting all those issues!

File: plugins/inputs/win_wmi/method.go [hunk 1]
```diff
@@ -102,127 +103,163 @@ func (m *method) execute(acc telegraf.Accumulator) error {
 	if err != nil {
 		return fmt.Errorf("failed calling method ConnectServer: %w", err)
 	}
-	service := serviceRaw.ToIDispatch()
 	defer serviceRaw.Clear()
+	service := serviceRaw.ToIDispatch()
+	defer service.Release()
```
Comment (skartikey) [inline plugins/inputs/win_wmi/method.go:108]: @srebhan  Great changes to fix the threading model issue. I noticed one potential improvement regarding error handling in the deferred cleanup functions:

For critical COM resources, it might be worth considering handling potential errors during cleanup. Something like:

```go
defer func() {
    if err := locator.Release(); err != nil {
        log.Printf("Error releasing locator: %v", err)
    }
}()
```

For a more comprehensive approach, you could collect these errors:

```go
var errs []error
defer func() {
    if err := locator.Release(); err != nil {
        errs = append(errs, fmt.Errorf("error releasing locator: %w", err))
    }
}()
```

Then at the end of the function, decide whether to log them or return them based on severity. This helps with debugging potential resource leaks when things go wrong.

Just a suggestion to consider for future enhancements. The current change looks good to me!

Comment (srebhan) [reply plugins/inputs/win_wmi/method.go:108]: Hmmm what would be the gain? If we get an error during release we cannot do anything anyway. So what should happen with the generated errors?

**Review by skartikey — APPROVED** [review]
@srebhan Nicely Done!

**Review by skartikey — APPROVED** [review]
@srebhan Nicely handled, given how tricky this one is, we'll keep an eye post-merge, but this looks like a solid approach.

**Review by mstrandboge — APPROVED** [review]
