### PR TITLE
fix(outputs/stackdriver): cumulative interval start times

### LINKED ISSUE #7758: stackdriver output plugin sends CUMULATIVE metrics incorrect
1. Telegraf 1.14 with input plugins diskio end net gathers Counter type metrics (for example net/bytes_sent)
2. Stackdriver output plugin sends these metrics to google cloud's Stackdriver

But stackdriver shows these metrics as flatline without value changes: 

image

When I try to get metrics timeSeries details:
`https://content-monitoring.googleapis.com/v3/projects/XXXX/timeSeries?filter=metric.type%20%3D%20%22custom.googleapis.com%2Fk3s-ns%2Fdiskio%2Fread_bytes%22&interval.startTime=2020-06-28T00%3A00%3A00Z&interval.endTime=2020-06-29T00%3A00%3A00Z&key=YYYYY`

I get response:
`{
  "unit": "{not_a_unit}"
}`

Sending same metrics to InfluxDB works correctly and values are written correctly. I assume that this is some issue with stackdriver output plugin and wrong usage of Google's API.

### PR DESCRIPTION
**Pull request by n-oden**
### Required for all PRs:

- [X] Updated associated README.md.
- [X] Wrote appropriate unit tests.
- [X] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #7758 

Cumulative metrics, when posted to google cloud monitoring (nee
Stackdriver), require a TimeInterval with a start time that corresponds
to the last time at which the counter/cumulative metric was reset to
zero, cannot overlap previous intervals, and cannot be more than 25
hours in the past:

https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TimeInterval

The stackdriver output plugin had been creating StartTimes of
`Thu Jan 1 00:00:01 UTC 1970` leading to bizarre behavior: stackdriver graphs
would reflect flatlined fractional values no matter what data telegraf
was sending, and direct queries to the projects.timeSeries.list API
would initially return the last handful of posted values but then
eventually return only `{"unit": "not_a_unit"}` for the same query,
presumably due to stackdriver having GC'ed the invalid intervals on the
backend.

So, herein:

- create a cache of start times and observed last values for all counter metrics (keyed by name, tags and field)
- reset the start time of a cache entry if the newest value is less than the previous observed value (counter reset)
- reset the start time of a cache entry if it is greater than 24 hours old
- while we're at it, use the telegraf logger rather than the base golang logger

### CODE REVIEW

**Comment by n-oden** [comment]
Note that as mentioned in the readme update, even with this change there is the potential for undefined behavior if one of the underlying counters resets without telegraf restarting in concert with it.  Doing this "right" would probably involve caching a separate start time and the last observed value for each counter metric and resetting the start time any time the metric resets, which seems to somewhat cut against the grain of telegraf's normal near-statelessness on the output side, but if there's interest I could attempt to implement that.

**Comment by n-oden** [comment]
Actually, having thought on it a bit, the per-metric cache really seems to be the only way to do this: setting the start time to the process start time means that if the input source starts exposing a new counter >25 hours after we start, that counter will never make it to stackdriver.

So, an update, complete with unit tests.

**Comment by n-oden** [comment]
@sspaink @Hipska @powersj Could I get a look taken at this? (Apologies in advance if I've missed a step here.)

**Comment by srebhan** [comment]
I guess this would benefit from plugin state-persistence (PR #9476)?

File: plugins/outputs/stackdriver/counter_cache.go [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+
+type CounterCacheEntry struct {
+	LastValue *monpb.TypedValue
+	StartTime *tspb.Timestamp
+}
+
+func (cce *CounterCacheEntry) Reset(ts *tspb.Timestamp) {
+	// always backdate a reset by -1ms, otherwise stackdriver's API will hate us
+	cce.StartTime = tspb.New(ts.AsTime().Add(time.Millisecond * -1))
+}
```
Comment (srebhan) [inline plugins/outputs/stackdriver/counter_cache.go:30]: I think none of the functions nor the structs need to be exported as they live in the same `stackdriver` package.

File: plugins/outputs/stackdriver/counter_cache.go [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+
+func (cc *CounterCache) get(key string) (*CounterCacheEntry, bool) {
+	cc.RLock()
+	value, ok := cc.cache[key]
+	cc.RUnlock()
+	return value, ok
```
Comment (srebhan) [inline plugins/outputs/stackdriver/counter_cache.go:36]: You can simplify this to
```suggestion
	cc.RLock()
	defer cc.RUnlock()
	return cc.cache[key]
```
Using defer here is strongly recommended in general as it prevents returning with a lock held.

File: plugins/outputs/stackdriver/stackdriver.go [hunk 3]
```diff
@@ -69,6 +56,18 @@ var sampleConfig = `
   #   location = "eu-north0"
 `
 
+// Stackdriver is the Google Stackdriver config info.
+type Stackdriver struct {
+	Project        string
+	Namespace      string
```
Comment (srebhan) [inline plugins/outputs/stackdriver/stackdriver.go:62]: Can you please add TOML tags for those two options.

File: plugins/outputs/stackdriver/stackdriver.go [hunk 4]
```diff
@@ -8,28 +8,17 @@ import (
...
-	Log            telegraf.Logger   `toml:"-"`
+	"google.golang.org/api/option"
+	"google.golang.org/genproto/googleapis/api/metric"
+	"google.golang.org/genproto/googleapis/api/monitoredres"
 
-	client *monitoring.MetricClient
-}
+	mon "cloud.google.com/go/monitoring/apiv3/v2"
+	monpb "google.golang.org/genproto/googleapis/monitoring/v3"
+	tspb "google.golang.org/protobuf/types/known/timestamppb"
```
Comment (srebhan) [inline plugins/outputs/stackdriver/stackdriver.go:20]: Can you please revert renaming the aliases to reduce the diff to a minimum. This eases reviews. Feel free to submit renaming in an additional PR.

File: plugins/outputs/stackdriver/stackdriver.go [hunk 5]
```diff
@@ -241,78 +244,83 @@ func (s *Stackdriver) Write(metrics []telegraf.Metric) error {
...
-	case metricpb.MetricDescriptor_GAUGE:
-		return &monitoringpb.TimeInterval{
-			EndTime: &timestamppb.Timestamp{
-				Seconds: end,
-			},
+	kind metric.MetricDescriptor_MetricKind,
+	value *monpb.TypedValue,
+	m telegraf.Metric,
+	f *telegraf.Field,
+	cc *CounterCache,
```
Comment (srebhan) [inline plugins/outputs/stackdriver/stackdriver.go:251]: I think most of those variables are required to get the`start` and `end`-time which was passed in directly before. So how about moving determination of start and end-time to an own function and leave this function as is?

**Review by srebhan — COMMENTED** [review]
Thanks for approaching this @n-oden! While the overall approach looks good, I have some comments in the code. Please try to reduce the non-related changes (renaming of aliases, reordering of imports, etc) to an absolute minimum and submit them as separate PRs to ease review. Furthermore, do you think it's possible to leave `getStackdriverTimeInterval()` as is and instead determine the `start` and `end` times in a separate function?

**Comment by n-oden** [comment]
hey @srebhan glad to finally have a review for this!  Your comments seem reasonable; I'll try to get them all addressed today or tomorrow.

File: plugins/outputs/stackdriver/counter_cache.go (hunk 1 above)
Comment (n-oden) [reply plugins/outputs/stackdriver/counter_cache.go:30]: 👍

File: plugins/outputs/stackdriver/counter_cache.go (hunk 2 above)
Comment (n-oden) [reply plugins/outputs/stackdriver/counter_cache.go:36]: 👍

File: plugins/outputs/stackdriver/stackdriver.go (hunk 3 above)
Comment (n-oden) [reply plugins/outputs/stackdriver/stackdriver.go:62]: 👍

File: plugins/outputs/stackdriver/stackdriver.go (hunk 4 above)
Comment (n-oden) [reply plugins/outputs/stackdriver/stackdriver.go:20]: Fair enough.  I'm going to leave them as-is in counter_cache.go unless you object.

File: plugins/outputs/stackdriver/counter_cache.go (hunk 2 above)
Comment (n-oden) [reply plugins/outputs/stackdriver/counter_cache.go:36]: actually this seems to end up needing to be:

```
func (cc *counterCache) get(key string) (*counterCacheEntry, bool) {
	cc.RLock()
	defer cc.RUnlock()
	value, ok := cc.cache[key]
	return value, ok
}
```

...because the compiler really does't like trying to directly return the map lookup even though it seems like it _should?_

```
plugins/outputs/stackdriver/counter_cache.go:35:2: not enough arguments to return
	have (*counterCacheEntry)
	want (*counterCacheEntry, bool)
```

**Comment by srebhan** [comment]
@n-oden sorry for taking so long to come to this... :-(

File: plugins/outputs/stackdriver/counter_cache.go (hunk 2 above)
Comment (srebhan) [reply plugins/outputs/stackdriver/counter_cache.go:36]: Ah right, I always forget about this stupidity. :-)

File: plugins/outputs/stackdriver/stackdriver.go (hunk 5 above)
Comment (n-oden) [reply plugins/outputs/stackdriver/stackdriver.go:251]: 👍

**Comment by n-oden** [comment]
@srebhan should be good to go, I think!

File: plugins/outputs/stackdriver/stackdriver.go [hunk 6]
```diff
@@ -156,11 +159,19 @@ func (s *Stackdriver) Write(metrics []telegraf.Metric) error {
 
 			metricKind, err := getStackdriverMetricKind(m.Type())
 			if err != nil {
-				s.Log.Errorf("Get metric failed: %s", err)
+				s.Log.Errorf("Get kind for metric '%s' type '%T' field '%s' failed: %s", m.Name(), m.Type(), f, err)
```
Comment (srebhan) [inline plugins/outputs/stackdriver/stackdriver.go:162]: Please use the `%q` formatter which quotes strings, maybe check throughout the code
```suggestion
				s.Log.Errorf("Get kind for metric %q (%T) field %q failed: %s", m.Name(), m.Type(), f, err)
```

File: plugins/outputs/stackdriver/stackdriver.go [hunk 7]
```diff
@@ -156,11 +159,19 @@ func (s *Stackdriver) Write(metrics []telegraf.Metric) error {
...
 			}
 
-			timeInterval, err := getStackdriverTimeInterval(metricKind, StartTime, m.Time().Unix())
+			startTime, endTime := getStackdriverIntervalEndpoints(
+				metricKind,
+				value,
+				m,
+				f,
+				s.counterCache,
+			)
```
Comment (srebhan) [inline plugins/outputs/stackdriver/stackdriver.go:172]: Can we maybe copy the content of `getStackdriverIntervalEndpoints` here as it saves a few lines and makes reading easier. Not a must, but I think it will save us some lines.

File: plugins/outputs/stackdriver/stackdriver.go [hunk 8]
```diff
@@ -276,10 +299,12 @@ func getStackdriverMetricKind(vt telegraf.ValueType) (metricpb.MetricDescriptor_
 		return metricpb.MetricDescriptor_GAUGE, nil
 	case telegraf.Counter:
 		return metricpb.MetricDescriptor_CUMULATIVE, nil
-	case telegraf.Histogram, telegraf.Summary:
-		fallthrough
+	case telegraf.Histogram:
+		return metricpb.MetricDescriptor_METRIC_KIND_UNSPECIFIED, fmt.Errorf("histograms not yet supported")
+	case telegraf.Summary:
+		return metricpb.MetricDescriptor_METRIC_KIND_UNSPECIFIED, fmt.Errorf("summary metrics not supported")
```
Comment (srebhan) [inline plugins/outputs/stackdriver/stackdriver.go:305]: This is also unrelated.

**Review by srebhan — COMMENTED** [review]
@n-oden thanks for the update. I have some more comments, but we are almost there I think.

File: plugins/outputs/stackdriver/stackdriver.go (hunk 6 above)
Comment (n-oden) [reply plugins/outputs/stackdriver/stackdriver.go:162]: Reasonable; do you have an opinion about the case of the variable being at end of string after a colon, e.g. on L243?

File: plugins/outputs/stackdriver/stackdriver.go (hunk 7 above)
Comment (n-oden) [reply plugins/outputs/stackdriver/stackdriver.go:172]: actually my goal here was to make this easier to add a test for.  In penance... I'm adding a test. :)

File: plugins/outputs/stackdriver/stackdriver.go (hunk 8 above)
Comment (n-oden) [reply plugins/outputs/stackdriver/stackdriver.go:305]: 👍

File: plugins/outputs/stackdriver/stackdriver.go (hunk 7 above)
Comment (srebhan) [reply plugins/outputs/stackdriver/stackdriver.go:172]: Ok. Then please do not split the params into lines and keep everything on a single line for readability. I guess that will fit in 120 cols... ;-)

File: plugins/outputs/stackdriver/stackdriver.go (hunk 6 above)
Comment (srebhan) [reply plugins/outputs/stackdriver/stackdriver.go]: For line 243, that's OK IMO. I usually use `%q` to highlight that piece or (and more importantly) to see if there are leading or trailing spaces etc... I'm also fine with `%s` just not with `'%s'` as this is what `%q` is for. :-)

Comment (n-oden) [reply plugins/outputs/stackdriver/stackdriver.go]: 👍 okay, then I think we're good here.

File: plugins/outputs/stackdriver/stackdriver.go (hunk 7 above)
Comment (n-oden) [reply plugins/outputs/stackdriver/stackdriver.go:172]: 👍

**Comment by n-oden** [comment]
@srebhan all done I think?

File: plugins/outputs/stackdriver/stackdriver_test.go [hunk 9]
```diff
@@ -447,3 +448,112 @@ func TestGetStackdriverLabels(t *testing.T) {
 	labels := s.getStackdriverLabels(tags)
 	require.Equal(t, QuotaLabelsPerMetricDescriptor, len(labels))
 }
+
+func TestGetStackdriverIntervalEndpoints(t *testing.T) {
+
```
Comment (srebhan) [inline plugins/outputs/stackdriver/stackdriver_test.go:453]: Remove the empty line to make the linter happy.

File: plugins/outputs/stackdriver/stackdriver_test.go [hunk 10]
```diff
@@ -447,3 +448,112 @@ func TestGetStackdriverLabels(t *testing.T) {
...
+					require.GreaterOrEqual(t, startTime.AsTime().UTC().Unix(), later.UTC().Unix())
+				}
+			}
+
+			if idx%2 == 0 {
+				require.Equal(t, now, endTime.AsTime())
+			} else {
+				require.Equal(t, later, endTime.AsTime())
+			}
+
```
Comment (srebhan) [inline plugins/outputs/stackdriver/stackdriver_test.go:555]: Remove the empty line to make the linter happy.

File: plugins/outputs/stackdriver/stackdriver_test.go [hunk 11]
```diff
@@ -447,3 +448,112 @@ func TestGetStackdriverLabels(t *testing.T) {
...
+		}
+	}
+
```
Comment (srebhan) [inline plugins/outputs/stackdriver/stackdriver_test.go:558]: Remove the empty line to make the linter happy.

File: plugins/outputs/stackdriver/stackdriver_test.go [hunk 12]
```diff
@@ -447,3 +448,112 @@ func TestGetStackdriverLabels(t *testing.T) {
...
+				log.Fatal(err)
+			}
+			if value == nil {
+				log.Fatalf("Got nil value for metric %q field %q", m, f)
+			}
+
+			metricKind, err := getStackdriverMetricKind(m.Type())
+			if err != nil {
+				log.Fatalf("Get kind for metric %q (%T) field %q failed: %s", m.Name(), m.Type(), f, err)
+			}
```
Comment (srebhan) [inline plugins/outputs/stackdriver/stackdriver_test.go:527]:
```suggestion
			require.NoErrorf(t, err, "get kind for metric %q (%T) field %q failed: %v", m.Name(), m.Type(), f, err)
```

File: plugins/outputs/stackdriver/stackdriver_test.go [hunk 13]
```diff
@@ -447,3 +448,112 @@ func TestGetStackdriverLabels(t *testing.T) {
...
+
+	for idx, m := range metrics {
+		for _, f := range m.FieldList() {
+			value, err := getStackdriverTypedValue(f.Value)
+			if err != nil {
+				log.Fatal(err)
+			}
+			if value == nil {
+				log.Fatalf("Got nil value for metric %q field %q", m, f)
+			}
```
Comment (srebhan) [inline plugins/outputs/stackdriver/stackdriver_test.go:522]:
```suggestion
			require.NotNilf(t, value, "got nil value for metric %q field %q", m, f)
```

File: plugins/outputs/stackdriver/stackdriver_test.go [hunk 14]
```diff
@@ -447,3 +448,112 @@ func TestGetStackdriverLabels(t *testing.T) {
...
+			telegraf.Counter,
+		),
+	}
+
+	for idx, m := range metrics {
+		for _, f := range m.FieldList() {
+			value, err := getStackdriverTypedValue(f.Value)
+			if err != nil {
+				log.Fatal(err)
+			}
```
Comment (srebhan) [inline plugins/outputs/stackdriver/stackdriver_test.go:519]:
```suggestion
			require.NoError(t, err)
```

**Review by srebhan — COMMENTED** [review]
The linter found some more... :-)

File: plugins/outputs/stackdriver/stackdriver_test.go (hunk 12 above)
Comment (n-oden) [reply plugins/outputs/stackdriver/stackdriver_test.go:527]: 👍

File: plugins/outputs/stackdriver/stackdriver_test.go (hunk 13 above)
Comment (n-oden) [reply plugins/outputs/stackdriver/stackdriver_test.go:522]: 👍

File: plugins/outputs/stackdriver/stackdriver_test.go (hunk 14 above)
Comment (n-oden) [reply plugins/outputs/stackdriver/stackdriver_test.go:519]: 👍

Comment (n-oden) [reply plugins/outputs/stackdriver/stackdriver_test.go:519]: (There's a bunch of older stuff in this test file that could also use NoError/NotNil; I'll clean that up in the next PR)

File: plugins/outputs/stackdriver/stackdriver_test.go (hunk 10 above)
Comment (n-oden) [reply plugins/outputs/stackdriver/stackdriver_test.go:555]: 👍

**Review by srebhan — APPROVED** [review]
Looks good to me. Thanks for fixing this long-standing issue @n-oden!

**Review by powersj — APPROVED** [review]
