### PR TITLE
fix(inputs.prometheus): Set the timeout for slow running API endpoints correctly

### LINKED ISSUE #12485: [inputs.prometheus] Error in plugin: Client.Timeout exceeded while awaiting headers)
### Relevant telegraf.conf

```toml
[[inputs.prometheus]]
  urls = ["http://localhost:9710/probe?target=https://fortigate.local:8443"]
  response_timeout = "120s"
  metric_version = 2
```

### Logs from Telegraf

```text
E! [inputs.prometheus] Error in plugin: error making HTTP request to http://localhost:9710/probe?target=fortigate.local:8443: Get "http://localhost:9710/probe?target=https://fortigate.local:8443": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

### System info

Telegraf 1.25.0, Debian 10 (20220310-944), AWS

### Docker

_No response_

### Steps to reproduce

1. Use telegraf version 1.25.0
2. Use https://github.com/bluecmd/fortigate_exporter 

### Expected behavior

`Telegraf` can scrape metrics for that prometheus exporter.

### Actual behavior

When using version 1.25.0 telegram can't scrape metrics and trows the following error:

`E! [inputs.prometheus] Error in plugin: error making HTTP request to http://localhost:9710/probe?target=fortigate.local:8443: Get "http://localhost:9710/probe?target=https://fortigate.local:8443": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ZPascal**
- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #12485 

*Description:*
The issue was related to a missed timeout configuration inside http client to establish a connection to an slow responsed Promtheus endpoint.

### CODE REVIEW

File: plugins/inputs/prometheus/prometheus_test.go [hunk 1]
```diff
@@ -137,6 +138,36 @@ func TestPrometheusGeneratesMetricsAlthoughFirstDNSFailsIntegration(t *testing.T
...
+		_, err := fmt.Fprintln(w, sampleTextFormat)
+		require.NoError(t, err)
+	}))
+	defer ts.Close()
+
+	p := &Prometheus{
+		Log:             testutil.Logger{},
+		URLs:            []string{ts.URL},
+		URLTag:          "url",
+		ResponseTimeout: config.Duration(time.Second * 5),
```
Comment (powersj) [inline plugins/inputs/prometheus/prometheus_test.go:153]: Thanks for the test, can you put up a test that causes the timeout to get hit as well please?

File: plugins/inputs/prometheus/prometheus.go [hunk 2]
```diff
@@ -163,6 +163,9 @@ func (p *Prometheus) Init() error {
 	}
 
 	ctx := context.Background()
+	// The parameter should be replaced in future with a new name called timeout to directly parse the configuration.
+	// I've decided to handle it not directly because, it's a breaking change.
```
Comment (powersj) [inline plugins/inputs/prometheus/prometheus.go:167]: Like to avoid TODO comments, I would either deprecate the option now, or probably remove the comments as this will be good going forward.

**Review by powersj — COMMENTED** [review]
Thanks for tracking this down and putting up a PR! Two comments inline

File: plugins/inputs/prometheus/prometheus.go (hunk 2 above)
Comment (ZPascal) [reply plugins/inputs/prometheus/prometheus.go:167]: I'll remove it and place the topic in a separate GitHub issue.

File: plugins/inputs/prometheus/prometheus_test.go (hunk 1 above)
Comment (ZPascal) [reply plugins/inputs/prometheus/prometheus_test.go:153]: Sure. I'll do that.

**Review by powersj — APPROVED** [review]
Thank you!

**Review by srebhan — APPROVED** [review]
Looks good to me. Thanks for the nice fix @ZPascal!
