### PR TITLE
Change hddtemp to always put temperature in value field

### LINKED ISSUE #1904: input hddtemp: Strange data? Why not just use value?
### Relevant telegraf.conf:

```
[[inputs.hddtemp]]
address = "127.0.0.1:7634"
devices = ["*"]
```
### System info:

Telegraf - version 1.0.1
ubuntu 14.04
### Steps to reproduce:
1. Just run hddtemp input
### Expected behavior:

The temperature should be in the value field and not a new field for each disk?
### Actual behavior:

2016-10-16-110545_1229x455_scrot

### PR DESCRIPTION
**Pull request by jonaz**
### Required for all PRs:
- [x] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] README.md updated (if adding a new plugin)

Also added unit tests which was missing in hddtemp plugin.
this should resolve #1904 

Im not sure how to handle data migration? Perhaps a config entry to handle the new format which defaults to the old?

### CODE REVIEW

**Comment by phemmer** [comment]
I think it would be cleaner to bring that `go-hddtemp` package into the main `hddtemp` plugin. Having it as a package makes the code messy. And the new changes just end up wasting memory having to deal with interfaces, empty struct pointers, persisting the object, etc. Plus it's all of 61 lines long, not worth having an entirely separate package for.

But that's just my opinion. I'll leave it up to the repo maintainers to decide :-)

**Comment by jonaz** [comment]
That's not something my issue addresses. It only addresses #1905 and the code structure is as it was.

But my opinion is that single responsibility principle should apply here and keeping it as it is does enforce that and does also enhances composability.

**Comment by phemmer** [comment]
> That's not something my issue addresses. It only addresses #1905 and the code structure is as it was.

But your PR is making design changes that are unrelated to the issue being addressed, solely for the sake of being able to create a unit test. If we're going to make design changes, we should do it right.

**Comment by jonaz** [comment]
"right" is obviously opinionated. I remember reading that back in 2012. I'm not against moving the struct in ```go-hddtemp``` up one level. Feel free to do that in a separate PR if you like.

**Comment by MendelGusmao** [comment]
I'm not against the move as long as the license is kept. When I first wrote this piece of code, go-hddtemp was an external dependency and sparrc suggested to add a license then copy its entire code to telegraf's tree.

**Comment by MendelGusmao** [comment]
Also, I don't think a migration plan is needed. The sensors plugin had a major refactoring a few months ago that completely changed the schema and as long as I know - I mean "at least in Github" - there were no complaints. Considering that newer plugins have less users and the data value, I don't think we really need to be that protective to hddtemp measurements.

File: plugins/inputs/hddtemp/hddtemp.go [hunk 1]
```diff
@@ -53,7 +61,7 @@ func (h *HDDTemp) Gather(acc telegraf.Accumulator) error {
 				}
 
 				fields := map[string]interface{}{
-					disk.DeviceName: disk.Temperature,
+					"value": disk.Temperature,
```
Comment (goller) [inline plugins/inputs/hddtemp/hddtemp.go]: Could this just be `temperature` instead of value?

**Comment by sparrc** [comment]
LGTM but please update the README with what the metrics look like that get collected by this plugin.

I realize this is not currently there, but please add it along with this PR.

**Comment by jonaz** [comment]
@goller changed to temperature
@sparrc updated readme with fields, tags and example output.

**Comment by sparrc** [comment]
thanks @jonaz

**Comment by jonaz** [comment]
@sparrc is this considered feature or bugfix?
