### PR TITLE
Fix InfluxDB UDP line splitting (#5438)

### LINKED ISSUE #5438: InfluxDB UDP output plugin not splitting large measurements
Telegraf's UDP output is not splitting outgoing measurement lines based on the udp_payload. It seems like the this block is never executed as serializer alway exists:  https://github.com/influxdata/telegraf/blob/master/plugins/outputs/influxdb/udp.go#L46

### Relevant telegraf.conf:
```
[[outputs.influxdb]]
  urls = ['udp://metrics-udp:22001/']
  database = "tg_udp"
  precision = "s"
  timeout = "5s"
  user_agent = "telegraf"
  udp_payload = 1400
```
### System info:
Tested on Telegraf 1.9.4 but issue seems to be still in HEAD 

### Steps to reproduce:

1. Set a udp_payload value in the [[outputs.influxdb]] plugin which is lower the size of some measurement lines.
2. Check the UDP datagram sizes with tcpdump.

### Expected behavior:
The datagrams should be split to be under the udp_payload size.

### Actual behavior:
The udp_payload parameter is disregarded and no split is performed. Measurements larger than udp_payload size are sent as single datagrams. For very large measurements a "message too long" error is produced.

### PR DESCRIPTION
**Pull request by oplehto**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [x] Has appropriate unit tests.

Fixes #5438 

- Set MaxLineBytes correctly
- Split the data to utilize as much of the datagram as possible (even with MaxLineBytes set correctly each metric that did not fit into the first datagram was split up separately)
- Split the byte slice from serializer to separate UDP datagrams if there are multiple lines

### CODE REVIEW

File: plugins/outputs/influxdb/udp.go [hunk 1]
```diff
@@ -96,7 +98,11 @@ func (c *udpClient) Write(ctx context.Context, metrics []telegraf.Metric) error
 			continue
 		}
 
-		_, err = c.conn.Write(octets)
+		scanner := bufio.NewScanner(bytes.NewReader(octets))
+		scanner.Split(scanLines)
+		for scanner.Scan() {
+			_, err = c.conn.Write(scanner.Bytes())
+		}
```
Comment (danielnelson) [inline plugins/outputs/influxdb/udp.go]: For 1.10, I think I will experiment with doing a metric splitter before the Serialize step, so we don't need to parse the serialized data.  There might be some duplication of the serialize code but I think it will be worth it, and also string fields can contain unescaped newlines in line protocol so there is a potential flaw with this (#4942).

I think we are going to do a 1.9.5, and this will be a more appropriate change for it.

File: plugins/serializers/influx/influx_test.go [hunk 2]
```diff
@@ -275,6 +275,22 @@ var tests = []struct {
 		),
 		output: []byte("cpu abc=123i 1519194109000000042\ncpu def=456i 1519194109000000042\n"),
 	},
+	{
+		name:     "split_fields_overflow",
```
Comment (danielnelson) [inline plugins/serializers/influx/influx_test.go]: This test passes without the change to the serializer, is it possible to modify it to require the change?

File: plugins/outputs/influxdb/udp.go (hunk 1 above)
Comment (oplehto) [reply plugins/outputs/influxdb/udp.go]: I completely agree doing the change you proposed is a sensible approach. This was just a stopgap to get things working with minimal modifications to the existing code.

File: plugins/serializers/influx/influx_test.go (hunk 2 above)
Comment (oplehto) [reply plugins/serializers/influx/influx_test.go]: The test now fails if the change is not implemented
