### PR TITLE
fix(inputs.chrony): Use DGRAM for the unix socket

### LINKED ISSUE #15549: [chrony] unix socket connection is broken
### Relevant telegraf.conf

```toml
[[inputs.chrony]]
    server = "unix:///var/run/chrony/chronyd.sock"
    metrics = ["activity", "tracking", "sources", "sourcestats"]
```

### Logs from Telegraf

```text
[pid 612402] write(9, "\6\1\0\0\0,\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 416 <unfinished ...>
[pid 612402] <... write resumed>)       = 416
[pid 612402] read(9,  <unfinished ...>
[pid 612402] <... read resumed>0xc003368400, 1024) = -1 EAGAIN (Resource temporarily unavailable)
```

### System info

1.13 - 78cbf533d2

### Docker

_No response_

### Steps to reproduce

1. Use the chrony plugin
2. Set the server to be `unix:///var/run/chrony/chronyd.sock`
3. Launch telegraf as root (or at least as a user that con use the unix socket)
4. See it hang

### Expected behavior

The chrony plugin should work

### Actual behavior

The plugin hangs *when using the unix socket* when:
- telegraf is launched as root
- or the connection is manually specified to use the socket

The reasons are two fold:
- Chrony uses datagram (`unixgram`) unix socket and not stream (`unix`) ones.
- The socket should be duplicated in order not to hang other connections to it

Here is a working [example by facebook](https://github.com/facebook/time/blob/4db09adcc1ec9ae3b6dda1dfcf41db77ca89b246/cmd/ntpcheck/checker/chrony.go#L38)

### Additional info

I guess this is hard to reproduce, because the unix socket is rarely used as telegraf cannot talk to it (thus it instead connects via UDP to the chrony deamon).

The unix socket is however needed to access the `serverstats` metrics. Most of the other ones can be reached using the udp socket.

### PR DESCRIPTION
**Pull request by Frankkkkk**
## Summary
We must use the DGRAM type when connecting to the chrony socket. On top of that, the socket must be duplicated in order to allow concurrent calls to it.

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #15549

### CODE REVIEW

File: plugins/inputs/chrony/chrony.go [hunk 1]
```diff
@@ -48,6 +68,7 @@ func (c *Chrony) Init() error {
 		}
 		switch u.Scheme {
 		case "unix":
+		case "unixdram":
```
Comment (srebhan) [inline plugins/inputs/chrony/chrony.go:71]:
```suggestion
		case "unix", "unixdram":
```

File: plugins/inputs/chrony/chrony.go [hunk 2]
```diff
@@ -90,7 +111,10 @@ func (c *Chrony) Start(_ telegraf.Accumulator) error {
 		}
 		switch u.Scheme {
 		case "unix":
-			conn, err := net.DialTimeout("unix", u.Path, time.Duration(c.Timeout))
+			// Actually we need a unixgram connection, allow this typo
+			// FALLTHROUGH
+		case "unixgram":
```
Comment (srebhan) [inline plugins/inputs/chrony/chrony.go:116]: Please fuse the two cases using
```golang
		case "unix", "unixgram":
```

File: plugins/inputs/chrony/chrony.go [hunk 3]
```diff
@@ -38,6 +40,24 @@ func (*Chrony) SampleConfig() string {
...
+		&net.UnixAddr{Name: local, Net: "unixgram"},
+		&net.UnixAddr{Name: address, Net: "unixgram"},
+	)
+	if err != nil {
+		return nil, err
+	}
+	//socket.c:bind_unix_address
+	if err := os.Chmod(local, 0666); err != nil { // #nosec G302: needs permission to the directory too
+		return nil, err
+	}
```
Comment (srebhan) [inline plugins/inputs/chrony/chrony.go:57]: Why do "others" need to get access? Even write access?

File: plugins/inputs/chrony/chrony.go [hunk 4]
```diff
@@ -38,6 +40,24 @@ func (*Chrony) SampleConfig() string {
 	return sampleConfig
 }
 
+// dialUnix opens an unixgram connection with chrony
+func dialUnix(address string) (*net.UnixConn, error) {
+	base, _ := path.Split(address)
```
Comment (srebhan) [inline plugins/inputs/chrony/chrony.go:45]:
```suggestion
	base := path.Base(address)
```

File: plugins/inputs/chrony/chrony.go [hunk 5]
```diff
@@ -38,6 +40,24 @@ func (*Chrony) SampleConfig() string {
...
+	local := path.Join(base, fmt.Sprintf("chronyc.%d.sock", os.Getpid()))
+	conn, err := net.DialUnix("unixgram",
+		&net.UnixAddr{Name: local, Net: "unixgram"},
+		&net.UnixAddr{Name: address, Net: "unixgram"},
+	)
```
Comment (srebhan) [inline plugins/inputs/chrony/chrony.go:50]: Why do you need to setup a local address? Why did you remove the timeout used before? Couldn't you let the OS figure out the local socket and use
```golang
net.DialTimeout("unixgram", u.Path, time.Duration(c.Timeout))
```
instead?

**Review by srebhan — COMMENTED** [review]
Thanks for your contribution @Frankkkkk! I do have some questions and comments in the code. One additional request is to somewhere add a comment with a reference to a document stating that the socket has to be unixgram! Looking forward to the next round!

File: plugins/inputs/chrony/chrony.go (hunk 3 above)
Comment (Frankkkkk) [reply plugins/inputs/chrony/chrony.go:57]: TBH, I have no idea why, The chrony C client does the same. If you remove the chmod or only have 664/644 it doesn't work. If you have a reason/fix, I'd be happy to hear it :-)

File: plugins/inputs/chrony/chrony.go (hunk 5 above)
Comment (Frankkkkk) [reply plugins/inputs/chrony/chrony.go:50]: Same as above, it doesn't work and fails with a -EAGAIN. Don't know why. The C client does the same

File: plugins/inputs/chrony/chrony.go (hunk 3 above)
Comment (srebhan) [reply plugins/inputs/chrony/chrony.go:57]: Is there a way to bring this up in the chrony project? TBH: I'm a bit hesitant to move this into the code where it will make up for a reasonable source of trouble in the future and poses a security issue as we now open up the communication to chrony for everyone...

Comment (Frankkkkk) [reply plugins/inputs/chrony/chrony.go:57]: Let me change the documentation and get back to you

Comment (Frankkkkk) [reply plugins/inputs/chrony/chrony.go]: fixed; thanks!

File: plugins/inputs/chrony/chrony.go [hunk 6]
```diff
@@ -47,7 +63,7 @@ func (c *Chrony) Init() error {
 			return fmt.Errorf("parsing server address failed: %w", err)
 		}
 		switch u.Scheme {
-		case "unix":
+		case "unix", "unixdram":
```
Comment (srebhan) [inline plugins/inputs/chrony/chrony.go:66]: Are we sure that this **has to be** a dgram socket? Or is both possible? If the latter, we should implement both and let the user decide...

**Review by srebhan — COMMENTED** [review]
Some more questions...

File: plugins/inputs/chrony/README.md [hunk 7]
```diff
@@ -42,6 +42,15 @@ See the [CONFIGURATION.md][CONFIGURATION.md] for more details.
...
 ```
 
+## Rights
+
+To use the unix socket, telegraf must be able to talk to it. Please ensure that
+the telegraf user is a member of the `chrony` group or telegraf won't be able to
+use the socket!
+
+The unix socket is needed in order to use the `serverstats` metrics. All other
+metrics can be gathered using the udp connection.
```
[the remark this answers is not in the document]
Comment (Frankkkkk) [reply plugins/inputs/chrony/README.md:52]: Serverstats: https://gitlab.com/chrony/chrony/-/blob/master/cmdmon.c?ref_type=heads#L129 (`PERMIT_AUTH`)
Tracking: https://gitlab.com/chrony/chrony/-/blob/master/cmdmon.c?ref_type=heads#L108 (`PERMIT_OPEN`)
Sourcestats: https://gitlab.com/chrony/chrony/-/blob/master/cmdmon.c?ref_type=heads#L109 (`PERMIT_OPEN`)

Authz logic is here: https://gitlab.com/chrony/chrony/-/blob/master/cmdmon.c?ref_type=heads#L1571

Technically, there are other commands, but they are not used by the metrics gathered by telegraf

File: plugins/inputs/chrony/chrony.go (hunk 6 above)
Comment (powersj) [reply plugins/inputs/chrony/chrony.go]: hmm I swear this worked as I had it set up locally when we landed #14629, however I do see an error about the type.

```
2024-06-26T19:31:30Z E! [agent] Starting input inputs.chrony: dialing "unix:///run/chrony/chronyd.sock" failed: dial unix /run/chrony/chronyd.sock: connect: protocol wrong type for socket
```

I think what I was using the UDP port via `udp://127.0.0.1:323`. I have confirmed the same behavior on Ubuntu Bionic and Ubuntu Focal as well, so let's remove the old support.

File: plugins/inputs/chrony/README.md (hunk 7 above)
[the remark this answers is not in the document]
Comment (srebhan) [reply plugins/inputs/chrony/README.md:52]: Ok I see. Thanks for pointing this out!

File: plugins/inputs/chrony/chrony.go (hunk 6 above)
Comment (srebhan) [reply plugins/inputs/chrony/chrony.go]: Ok, as the past code seems to never have worked, even though I could swear I tested it and ported it from old code, I would say we just convert the `unix` to dgram and **not** introduce `unixdgram`. @powersj what do you think?

Comment (Frankkkkk) [reply plugins/inputs/chrony/chrony.go]: Can you try with the `serverstats` plugin please ? Because it's the only one that needs the socket :-)

File: plugins/inputs/chrony/chrony.go [hunk 8]
```diff
@@ -38,6 +41,27 @@ func (*Chrony) SampleConfig() string {
 	return sampleConfig
 }
 
+// dialUnix opens an unixgram connection with chrony
+func dialUnix(address string) (*net.UnixConn, error) {
+	dir := path.Dir(address)
+	local := path.Join(dir, fmt.Sprintf("chrony-telegraf-%s.sock", uuid.New().String()))
+	// XXX TODO: remove the file at the end
```
[the remark this answers is not in the document]
Comment (Frankkkkk) [reply plugins/inputs/chrony/chrony.go:48]: TBH I don't really know how to do that cleanly. Because a defer removes it early. Could you recomend something to me ? i.e . a new `conn` struct or similar ? Thanks!

File: plugins/inputs/chrony/chrony.go (hunk 6 above)
Comment (powersj) [reply plugins/inputs/chrony/chrony.go]: @srebhan agreed

@Frankkkkk yep looks like that fails currently as well with `got status UNAUTH (2)`.

**Comment by Frankkkkk** [comment]
@powersj @srebhan Can we recap what is needed for this MR/issue to be closed ?

Do we agree that we still need unix sockets in order to access the serverstats metrics (which are quite helpful IMHO)?

If so, then:
- Is the dialUnix function okay with you? We still need to remove the sock file at the end. Should I create an intermediate struct ? What do you recommend ?


Thanks!

**Comment by srebhan** [comment]
@Frankkkkk I would say
1. Do not add "unixgram" as a scheme but fix the existing "unix" one with the `dialUnix` function as is.
2. Close and remove the local socket file in the [`Stop()` function of the plugin](https://github.com/influxdata/telegraf/blob/95a17d9d9caa7e4c0da679d6bab940eac651ece8/plugins/inputs/chrony/chrony.go#L133). For this you probably need to store the filename in the plugin struct I guess.
3. Clarify if the file permissions really have to be `0666` or if we can find a solution with `0660` or even `0600`. Fix the linter warning accordingly.

Regarding item 3: I don't think we can accept `0666` as this opens the socket to everyone posing a security issue. I would rather want to see either a user-specified permission and/or chgrp'ing the socket to the `chrony` group (probably also a user setting). @powersj what do you think?

**Comment by Frankkkkk** [comment]
Regarding the `unixgram` vs `unix`, I don't think it will work with `unix` as it's basically 2 different protocols. Trying it it says:
```
2024-06-27T21:44:06Z E! [agent] Starting input inputs.chrony: dialing "unix:///run/chrony/chronyd.sock" failed: dial unix /run/chrony/chrony-telegraf-e04231d6-396a-452b-b1de-78681a384010.sock->/run/chrony/chronyd.sock: connect: protocol wrong type for socket
```

Without 666 it doesn't work. I don't know why. Maybe we should check that before proceeding further..

Looking at `chronyc`, it basically does the same, that's interesting:
```
bind(3, {sa_family=AF_UNIX, sun_path="/var/run/chrony/chronyc.160046.sock"}, 110) = 0
chmod("/var/run/chrony/chronyc.160046.sock", 0666) = 0
connect(3, {sa_family=AF_UNIX, sun_path="/var/run/chrony/chronyd.sock"}, 110) = 0
```


Pinging @mlichvar, one of the fathers of chrony: can you help us here? Thanks!

**Comment by mlichvar** [comment]
chronyd normally runs under a non-root user, so the client's socket needs to have permissions or ownership set in such a way that chronyd will be able to write to it (to send the response). Access to the socket is still protected by the permissions/ownership of the /var/run/chrony directory.

**Comment by srebhan** [comment]
@Frankkkkk sorry for the confusion I cause! :-( What I meant with
>  unixgram vs unix,

is to use the code you do have now but using a dgram socket if the user specifies a `unix:///my/socket` instead of making the user specifying `unixgram:///my/socket`...

@mlichvar thanks for chiming in! Would it work if we set the group of the socket to chrony's group and set 0660? I guess it would and would improve security, wouldn't it?

**Comment by mlichvar** [comment]
`/run/chrony` should be accessible only to the chrony group, so I don't think changing group on the socket would do anything. To me it seems like an unnecessary complication.

File: plugins/inputs/chrony/chrony.go [hunk 9]
```diff
@@ -38,6 +41,27 @@ func (*Chrony) SampleConfig() string {
...
+		&net.UnixAddr{Name: address, Net: "unixgram"},
+	)
+
+	if err != nil {
+		return nil, err
+	}
+
+	if err := os.Chmod(local, 0666); err != nil {
+		return nil, err
+	}
```
Comment (powersj) [inline plugins/inputs/chrony/chrony.go:60]: @jdstrand can you please review this and the conversation in the PR please? Thanks

Comment (jdstrand) [reply plugins/inputs/chrony/chrony.go:60]: @powersj - I can confirm that locally `/run/chrony` is `_chrony:_chrony` 0750 so having the socket set to `0666` would not be a problem on this system. I'm puzzled why `0666` makes things work when the directory presumably would also have these restrictive permissions so the socket should've been denied regardless of the socket permissions. Where 0666 works and 0660 or 0600 doesn't, can someone confirm the ownership and permissions on the `/run/chrony` directory, what user telegraf is running as and what group membership that user has?

I'm inclined for our code to create the socket with the minimal privileges that telegraf needs and not make assumptions about the run directory, but until we understand why 0666 was needed, I can't make a recommendation.

(AFAIK, telegraf doesn't have the concept of dropping privileges (please correct me) and it is simply started as the desired user. So, for `root` I wouldn't expect `0666` to have been needed and for `telegraf` I would've expected the socket creation to have failed since only the `_chrony` *owner* has write to the directory to create the socket).

Comment (powersj) [reply plugins/inputs/chrony/chrony.go:60]: @Frankkkkk could you share the following on your system:

1. the ownership and permissions on the /run/chrony
2. what user telegraf was running as
3. the groups that user belongs to?

@jdstrand in terms of ownership this is what I see:

On Ubuntu Jammy:

```shell
root@j1:~# stat /run/chrony
  File: /run/chrony
  Size: 80        	Blocks: 0          IO Block: 4096   directory
Device: 61h/97d	Inode: 334         Links: 2
Access: (0750/drwxr-x---)  Uid: (  106/ _chrony)   Gid: (  113/ _chrony)
Access: 2024-07-08 20:09:21.502577346 +0000
Modify: 2024-07-08 20:09:21.502577346 +0000
Change: 2024-07-08 20:09:21.502577346 +0000
 Birth: 2024-07-08 20:09:21.502577346 +0000
```

On Arch:

```shell
❯ stat /run/chrony
  File: /run/chrony
  Size: 80        	Blocks: 0          IO Block: 4096   directory
Device: 0,23	Inode: 5275        Links: 2
Access: (0750/drwxr-x---)  Uid: (  956/  chrony)   Gid: (  956/  chrony)
Access: 2024-07-08 14:10:06.419406121 -0600
Modify: 2024-07-08 14:10:06.422520696 -0600
Change: 2024-07-08 14:10:06.422520696 -0600
 Birth: 2024-07-08 14:10:06.419406121 -0600
```

**Comment by Frankkkkk** [comment]
Hi,
Sorry, don't have the time for that right now, but if I recall correctly, it didn't work with 660.

I'll try to report back, but not before some weeks.
Thanks & Cheers

**Comment by srebhan** [comment]
@Frankkkkk of course the telegraf-user (the one executing the telegraf) need to be in the correct group... :-)

**Comment by powersj** [comment]
> Where 0666 works and 0660 or 0600 doesn't, can someone confirm the ownership and permissions on the /run/chrony directory, what user telegraf is running as and what group membership that user has?

Confirmed that 0660 hangs:

```sh
root@j1:~# stat /run/chrony
  File: /run/chrony
  Size: 120       	Blocks: 0          IO Block: 4096   directory
Device: 4ah/74d	Inode: 342         Links: 2
Access: (0750/drwxr-x---)  Uid: (  106/ _chrony)   Gid: (  113/ _chrony)
Access: 2024-07-19 15:15:09.536385535 +0000
Modify: 2024-07-19 15:13:19.722551918 +0000
Change: 2024-07-19 15:13:19.722551918 +0000
 Birth: 2024-07-19 15:09:35.908770107 +0000
root@j1:~# whoami
root
root@j1:~# groups
root
```

**Comment by powersj** [comment]
Having the socket with 0660 and ensuring it matches the `_chonry` group's GID works.

Is the way forward then to expose new config options for the group (default: _chrony) and permissions (default: 0660) and only try creating this socket if the user is trying to collect serverstats metrics?

```toml
[[inputs.chrony]]
    server = "unixgram:///run/chrony/chronyd.sock"
    metrics = ["serverstats"]
[[outputs.file]]
```

```diff
diff --git plugins/inputs/chrony/chrony.go plugins/inputs/chrony/chrony.go
index 784f8e929..dfddd1b06 100644
--- plugins/inputs/chrony/chrony.go
+++ plugins/inputs/chrony/chrony.go
@@ -9,6 +9,7 @@ import (
        "net"
        "net/url"
        "os"
+       "os/user"
        "path"
        "strconv"
        "syscall"
@@ -55,7 +56,19 @@ func dialUnix(address string) (*net.UnixConn, error) {
                return nil, err
        }
 
-       if err := os.Chmod(local, 0666); err != nil {
+       if err := os.Chmod(local, 0660); err != nil {
+               return nil, err
+       }
+
+       group, err := user.LookupGroup("_chrony")
+       if err != nil {
+               return nil, err
+       }
+       gid, err := strconv.Atoi(group.Gid)
+       if err != nil {
+               return nil, err
+       }
+       if err := os.Chown(local, os.Getuid(), gid); err != nil {
                return nil, err
        }
```

```s
root@j1:~# ./telegraf --config config.toml --once
2024-07-24T19:59:07Z I! Loading config: config.toml
2024-07-24T19:59:07Z I! Starting Telegraf 1.32.0-2fcfc3eb brought to you by InfluxData the makers of InfluxDB
2024-07-24T19:59:07Z I! Available plugins: 234 inputs, 9 aggregators, 32 processors, 26 parsers, 60 outputs, 6 secret-stores
2024-07-24T19:59:07Z I! Loaded inputs: chrony
2024-07-24T19:59:07Z I! Loaded aggregators: 
2024-07-24T19:59:07Z I! Loaded processors: 
2024-07-24T19:59:07Z I! Loaded secretstores: 
2024-07-24T19:59:07Z I! Loaded outputs: file
2024-07-24T19:59:07Z I! Tags enabled: host=j1
2024-07-24T19:59:07Z I! [agent] Hang on, flushing any cached metrics before shutdown
chrony_serverstats,host=j1,source=/run/chrony/chronyd.sock ntp_drops=0i,ntp_timestamps=0i,cmd_hits=5i,cmd_drops=0i,log_drops=0i,ntp_hits=0i,ntp_auth_hits=0i,ntp_interleaved_hits=0i,ntp_span_seconds=0i,nke_hits=0i,nke_drops=0i 1721851147000000000
2024-07-24T19:59:07Z I! [agent] Stopping running outputs
```

**Comment by powersj** [comment]
@srebhan,

I've pushed a commit, https://github.com/influxdata/telegraf/pull/15552/commits/46fc4df9c3b73e2e023fcc27907eea170e9abeee, which includes a few TODO I'd like your feedback on.

File: plugins/inputs/chrony/README.md [hunk 10]
```diff
@@ -40,8 +40,23 @@ See the [CONFIGURATION.md][CONFIGURATION.md] for more details.
...
   # metrics = ["tracking"]
+
+  ## Socket group & permissions
+  ## If the user requests collecting metrics via unix socket, then it is created
+  ## with the following group and permissions.
+  # socket_group = "chrony"
+  # socket_perms = "0660"
 ```
 
+## Rights
```
Comment (srebhan) [inline plugins/inputs/chrony/README.md:51]: How about
```suggestion
## Local socket permissions
```

**Review by srebhan — COMMENTED** [review]
Just one small comment about the README section naming... Other than that the PR looks good.

**Review by srebhan — APPROVED** [review]
Perfect thanks @Frankkkkk and @powersj! And thanks @mlichvar for your great input!

**Review by DStrand1 — APPROVED** [review]
