### PR TITLE
Fix nsq_consumer regression by avoiding connection to an empty list of servers

### LINKED ISSUE #9502: inputs.nsq_consumer fails after upgrading to 1.19.x
We use nsq_consumer to move messages from nsq to Influx

This setup has been running for ages (at least three years) but broke after upgrading to Telegraf 1.19.1; downgrading to 1.18.3 fixes the issue.

### Relevant telegraf.conf:
```toml
[agent]
  interval = "10s"
  debug = true

[[inputs.nsq_consumer]]
  nsqlookupd = ["nsqdev:4161"]
  topic = "cisco-telemetry-influx"
  channel = "to_influxdb_stor03"
  data_format = "influx"
  max_in_flight = 5000

[[outputs.influxdb]]
  urls = [ "http://127.0.0.1:8086" ]
  database = "cisco-telemetry"
```

### System info:

- Telegraf version: 1.19.1 (also tested on 1.19.0 and 1.20.0)
- OS: Ubuntu 16.04 (also tested on Ubuntu 18.04)

### Steps to reproduce:

```
2021-07-14T05:31:54Z I! Starting Telegraf 1.19.1
2021-07-14T05:31:54Z I! Loaded inputs: nsq_consumer
2021-07-14T05:31:54Z I! Loaded aggregators: 
2021-07-14T05:31:54Z I! Loaded processors: 
2021-07-14T05:31:54Z I! Loaded outputs: influxdb
2021-07-14T05:31:54Z I! Tags enabled: host=stor03
2021-07-14T05:31:54Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"stor03", Flush Interval:10s
2021-07-14T05:31:54Z D! [agent] Initializing plugins
2021-07-14T05:31:54Z D! [agent] Connecting outputs
2021-07-14T05:31:54Z D! [agent] Attempting connection to [outputs.influxdb]
2021-07-14T05:31:54Z D! [agent] Successfully connected to outputs.influxdb
2021-07-14T05:31:54Z D! [agent] Starting service inputs
2021-07-14T05:31:54Z D! [inputs.nsq_consumer] INF    1 [cisco-telemetry-influx/to_influxdb_stor03] querying nsqlookupd http://nsqdev:4161/lookup?topic=cisco-telemetry-influx
2021-07-14T05:31:54Z D! [inputs.nsq_consumer] INF    1 [cisco-telemetry-influx/to_influxdb_stor03] (nsq-dev:4150) connecting to nsqd
2021-07-14T05:31:54Z D! [inputs.nsq_consumer] WRN    1 [cisco-telemetry-influx/to_influxdb_stor03] (nsq-dev:4150) max RDY count 2500 < consumer max in flight 5000, truncation possible
2021-07-14T05:31:54Z D! [inputs.nsq_consumer] INF    1 [cisco-telemetry-influx/to_influxdb_stor03] () connecting to nsqd
2021-07-14T05:31:54Z E! [telegraf] Error running agent: starting input inputs.nsq_consumer: dial tcp: missing address
```

In this scenario nsqdev is a different host returned by nsqlookupd.

### Expected behavior:

Telegraf should connect to the nsqd servers returned by nsqlookupd.

### Actual behavior:

Telegraf fails with the error message `Error running agent: starting input inputs.nsq_consumer: dial tcp: missing address`

### Additional info:

Data returned by nsqlookupd (`curl http://nsqdev:4161/lookup?topic=cisco-telemetry-influx`)

```json
{"channels":["to_influxdb_stor03"],"producers":[{"remote_address":"10.20.30.134:46928","hostname":"nsq-dev","broadcast_address":"nsq-dev","tcp_port":4150,"http_port":4151,"version":"1.0.0-compat"}]}
```

### PR DESCRIPTION
**Pull request by srebhan**
### Required for all PRs:
- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.

resolves #9502 

As a fallout of the linter-fixes we now check return code when trying to connect to servers specified in `nsqd`. However, if this option is omitted, which is valid when using `nsqlookupd`, the server list stays empty. In turn the attempt to connect to this empty list of servers fails as can be expected. Previously (<v1.19), this error went unnoticed as the returned error was not checked.

This PR now checks if the server-list specified in `nsqd` (and for backward-compatibility `server`) is empty and omits the attempt to connect to this empty list. Furthermore, we check if at least either `nsqd` or `nsqlookupd` has entires.

### CODE REVIEW

**Review by sspaink — APPROVED** [review]
Thanks for fixing this!

File: plugins/inputs/nsq_consumer/nsq_consumer.go [hunk 1]
```diff
@@ -134,15 +135,28 @@ func (n *NSQConsumer) Start(ac telegraf.Accumulator) error {
 		return nil
 	}))
 
+	// For backward compatibility
+	if n.Server != "" {
+		n.Nsqd = append(n.Nsqd, n.Server)
```
Comment (ssoroka) [inline plugins/inputs/nsq_consumer/nsq_consumer.go:140]: documentation says we _prepend_ it to the list, but we're appending it here. Could be a concern if the server connection list order matters?

File: plugins/inputs/nsq_consumer/nsq_consumer.go [hunk 2]
```diff
@@ -134,15 +135,28 @@ func (n *NSQConsumer) Start(ac telegraf.Accumulator) error {
...
+	}
+
+	// Check if we have anything to connect to
+	if len(n.Nsqlookupd) == 0 && len(n.Nsqd) == 0 {
+		return fmt.Errorf("either 'nsqd' or 'nsqlookupd' needs to be specified")
+	}
```
Comment (ssoroka) [inline plugins/inputs/nsq_consumer/nsq_consumer.go:146]: what do you think about moving the server len checks to an `func (n *NSQConsumer) Init() error` function? This way it can error on startup that the configuration is invalid, rather than at connect time.
That might also help with another potential issue; if the Start function is called more than once (say connection failure), the above code will keep appending to the  n.Nsqd slice.

**Review by ssoroka — CHANGES_REQUESTED** [review]
Looks like a great change, just have a few minor comments

File: plugins/inputs/nsq_consumer/nsq_consumer.go (hunk 1 above)
Comment (srebhan) [reply plugins/inputs/nsq_consumer/nsq_consumer.go:140]: First of all thanks a lot for the review!
Regarding the order, I just used what was done before in this plugin (previous line 143). I can change this, should I?

File: plugins/inputs/nsq_consumer/nsq_consumer.go (hunk 2 above)
Comment (srebhan) [reply plugins/inputs/nsq_consumer/nsq_consumer.go:146]: Your point is perfectly valid and makes sense to me. I tried to touch as little as possible as this is a regression fix. Do you want me to fix this in this PR?

File: plugins/inputs/nsq_consumer/nsq_consumer.go (hunk 1 above)
Comment (reimda) [reply plugins/inputs/nsq_consumer/nsq_consumer.go:140]: We should probably change the docs to say append. If the plugin appended before, changing it to prepending might cause incompatibility.

File: plugins/inputs/nsq_consumer/nsq_consumer.go (hunk 2 above)
Comment (reimda) [reply plugins/inputs/nsq_consumer/nsq_consumer.go:146]: Let's merge the regression fix as-is so it's in 1.19.1 tomorrow and make another pr to implement Steven's recommendation.

**Review by reimda — APPROVED** [review]
