### PR TITLE
fix(agent): Reject negative collection_offset

### LINKED ISSUE #18175: Negative collection_offset Causes Multiple Executions
### Relevant telegraf.conf

```toml
/etc/telegraf# cat telegraf.conf
[[inputs.exec]]
  interval = "30s"
  commands = ["python3 /etc/telegraf/test.py"]
  timeout = "3s"
  collection_offset = "-15s"
  data_format = "influx"

[[outputs.file]]
  files = ["stdout", "/etc/telegraf/test_output.txt"]


/etc/telegraf# cat test.py 
print("metric,tag1=1,tag2=2 value=1")
```

### Logs from Telegraf

```text
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
2025-12-31T13:07:48Z D! [inputs.exec] Previous collection has not completed; scheduled collection skipped
```

### System info

Ubuntu 24.04.3 , Telegraf 1.37.0

### Docker

When running with a negative offset Telegraf is executing the python script multiple times, when running with a positive offset there are no issues.

### Steps to reproduce

1. Copy telegraf.conf config above to /etc/telegraf folder.
2. Copy python script to /etc/telegraf folder and make executable.
3. Run /usr/bin/telegraf --config telegraf.conf with the config of collection_offset = "-15s" to see the problem, run the same command again with collection_offset = "5s" and the issue no longer happens.
...

### Expected behavior

I would expect telegraf to run the command / script once at 15s before the set interval rate.

### Actual behavior

I appears to be running it multiple times and printing the results multiple times.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by majiayu000**
## Summary

Based on the review feedback from @srebhan on #18178, this PR takes the simpler approach of **rejecting invalid offset values at startup** rather than normalizing them:

- **Negative agent-level collection_offset** → error at startup in `runAgent`
- **Negative per-input collection_offset** → error during config load in `buildInput`
- **Negative per-input interval** → error during config load in `buildInput`

This avoids the ambiguity of silently normalizing negative offsets, which could mean different things to different users.

## Changes

- Add agent-wide negative `collection_offset` check in `runAgent` (`cmd/telegraf/telegraf.go`), alongside existing interval/flush_interval checks
- Add per-input negative `interval` and `collection_offset` checks in `buildInput` (`config/config.go`)
- No changes to `NewTicker` signature or behavior

## Checklist

- [ ] No AI generated code was used in this PR
- [x] AI generated code used in this PR follows the [InfluxData Policy on AI-Generated Code Contributions][policy]

[policy]: https://www.influxdata.com/ai-generated-code-contributions-policy

## Related issues

supersedes #18178
resolves #18175

### CODE REVIEW

File: internal/clock/ticker.go [hunk 1]
```diff
@@ -23,7 +24,17 @@ type Ticker struct {
...
 }
 
-func NewTicker(interval, jitter, offset time.Duration, opt ...Option) *Ticker {
+func NewTicker(interval, jitter, offset time.Duration, opt ...Option) (*Ticker, error) {
+	if interval <= 0 {
+		return nil, fmt.Errorf("interval must be positive, got %s", interval)
+	}
+	if offset < 0 {
+		return nil, fmt.Errorf("negative offset %s is not allowed; use a positive offset instead, e.g. interval-offset = %s", offset, interval+offset)
+	}
```
Comment (Hipska) [inline internal/clock/ticker.go]: These checks should be moved to `func (c *Config) addInput` or `func (c *Config) buildInput`.

And agent-wide check for interval already exists at `func (t *Telegraf) runAgent`, so the agent-wide check for negative offset should also be there.

File: internal/clock/ticker.go [hunk 2]
```diff
@@ -23,7 +24,17 @@ type Ticker struct {
...
+	if offset >= interval {
+		return nil, fmt.Errorf("offset %s must be less than interval %s", offset, interval)
+	}
```
Comment (Hipska) [inline internal/clock/ticker.go]: I don't feel like this is something to be checked in `NewTicker`, but already before calling this in `func (a *Agent) runInputs` where you can know the input ID/name and its logger.

File: cmd/telegraf/telegraf.go [hunk 3]
```diff
@@ -456,6 +456,13 @@ func (t *Telegraf) runAgent(ctx context.Context, reloadConfig bool) error {
 		return fmt.Errorf("agent flush_interval must be positive; found %v", c.Agent.Interval)
 	}
 
+	if int64(c.Agent.CollectionOffset) < 0 {
+		return fmt.Errorf(
+			"agent collection_offset must not be negative, found %v; use a positive offset instead (e.g. interval - offset)",
+			c.Agent.CollectionOffset,
+		)
```
Comment (Hipska) [inline cmd/telegraf/telegraf.go]: This should be enough
```suggestion
		return fmt.Errorf("agent collection_offset must not be negative, found %v", c.Agent.CollectionOffset)
```

File: config/config.go [hunk 4]
```diff
@@ -1689,6 +1689,9 @@ func (c *Config) buildInput(name, source string, tbl *ast.Table) (*models.InputC
 	cp.Precision, _ = c.getFieldDuration(tbl, "precision")
 	cp.CollectionJitter, _ = c.getFieldDuration(tbl, "collection_jitter")
 	cp.CollectionOffset, _ = c.getFieldDuration(tbl, "collection_offset")
+	if cp.CollectionOffset < 0 {
+		return nil, fmt.Errorf("negative collection_offset %s is not allowed for input %s; use a positive offset instead (e.g. interval - offset)", cp.CollectionOffset, name)
```
Comment (Hipska) [inline config/config.go]:
```suggestion
		return nil, fmt.Errorf("negative collection_offset %q is not allowed for input %s", cp.CollectionOffset, name)
```

File: config/config.go
Comment (Hipska) [inline config/config.go:1691]: Maybe also add check for interval while w are here?

File: cmd/telegraf/telegraf.go (hunk 3 above)
Comment (majiayu000) [reply cmd/telegraf/telegraf.go]: Done — simplified to `return fmt.Errorf("agent collection_offset must not be negative, found %v", c.Agent.CollectionOffset)` as suggested.

File: config/config.go (hunk 4 above)
Comment (majiayu000) [reply config/config.go]: Done — updated to use `%q` and shortened the message as suggested.

File: config/config.go
Comment (majiayu000) [reply config/config.go:1691]: Good idea — added a negative interval check in `buildInput` as well.

File: internal/clock/ticker.go (hunk 1 above)
Comment (majiayu000) [reply internal/clock/ticker.go]: Done — validation is now in `buildInput` (per-input) and `runAgent` (agent-wide), not in `NewTicker`. The `NewTicker` signature remains `*Ticker` with no changes.

File: internal/clock/ticker.go (hunk 2 above)
Comment (majiayu000) [reply internal/clock/ticker.go]: Agreed — moved the checks out of `NewTicker` in the previous commit. No validation logic remains in `NewTicker`.

**Comment by srebhan** [comment]
@majiayu000 please restore the PR description template, especially the AI checkboxes and the "Related issues" section! The template is there for a reason namely to query relevant information we need to process the PR and a common structure so we can machine-read things.

Thank you!

File: internal/clock/ticker.go (hunk 1 above)
Comment (majiayu000) [reply internal/clock/ticker.go]: Done — validation is now in `buildInput` (per-input) and `runAgent` (agent-wide), not in `NewTicker`. The `NewTicker` signature remains `*Ticker` with no changes.

File: internal/clock/ticker.go (hunk 2 above)
Comment (majiayu000) [reply internal/clock/ticker.go]: Agreed — moved the checks out of `NewTicker`. Per-input validation is in `buildInput` where the input name is available for error messages.

File: cmd/telegraf/telegraf.go (hunk 3 above)
Comment (majiayu000) [reply cmd/telegraf/telegraf.go]: Done — simplified to `return fmt.Errorf("agent collection_offset must not be negative, found %v", c.Agent.CollectionOffset)` as suggested.

File: config/config.go (hunk 4 above)
Comment (majiayu000) [reply config/config.go]: Done — updated to use `%q` and shortened the message as suggested.

File: config/config.go
Comment (majiayu000) [reply config/config.go:1691]: Good idea — added a negative interval check in `buildInput` as well.

File: cmd/telegraf/telegraf.go [hunk 5]
```diff
@@ -456,6 +456,10 @@ func (t *Telegraf) runAgent(ctx context.Context, reloadConfig bool) error {
 		return fmt.Errorf("agent flush_interval must be positive; found %v", c.Agent.Interval)
 	}
 
+	if int64(c.Agent.CollectionOffset) < 0 {
+		return fmt.Errorf("agent collection_offset must not be negative, found %v", c.Agent.CollectionOffset)
+	}
+
```
Comment (srebhan) [inline cmd/telegraf/telegraf.go]: Can we please do this in the same place as all the other checks i.e. in [`config.go` when parsing the agent table](https://github.com/majiayu000/telegraf/blob/f025108149d036ea56f061d4e0bad88d5952702c/config/config.go#L628)!?

File: config/config.go [hunk 6]
```diff
@@ -1689,6 +1689,12 @@ func (c *Config) buildInput(name, source string, tbl *ast.Table) (*models.InputC
 	cp.Precision, _ = c.getFieldDuration(tbl, "precision")
 	cp.CollectionJitter, _ = c.getFieldDuration(tbl, "collection_jitter")
 	cp.CollectionOffset, _ = c.getFieldDuration(tbl, "collection_offset")
+	if cp.Interval < 0 {
+		return nil, fmt.Errorf("negative interval %q is not allowed for input %s", cp.Interval, name)
+	}
```
Comment (srebhan) [inline config/config.go]: Can we please have this as a separate PR!?

File: cmd/telegraf/telegraf.go (hunk 5 above)
Comment (majiayu000) [reply cmd/telegraf/telegraf.go]: Done — moved the agent-level `collection_offset` check to `config.go` in `LoadConfigData`, right after the agent table is parsed (alongside the existing agent config handling). Removed it from `runAgent` in `telegraf.go`.

File: config/config.go (hunk 6 above)
Comment (majiayu000) [reply config/config.go]: Understood — removed the per-input interval check from this PR. I'll submit it as a separate PR.

File: config/config.go [hunk 7]
```diff
@@ -640,6 +640,9 @@ func (c *Config) LoadConfigData(data []byte, path string) error {
 		if err = c.toml.UnmarshalTable(subTable, c.Agent); err != nil {
 			return fmt.Errorf("error parsing [agent]: %w", err)
 		}
+		if int64(c.Agent.CollectionOffset) < 0 {
```
Comment (Hipska) [inline config/config.go]: I don't think the int64 conversion is needed?
```suggestion
		if c.Agent.CollectionOffset < 0 {
```

Comment (majiayu000) [reply config/config.go]: Done — removed the `int64()` conversion. Direct comparison works since `Duration` is based on `int64`.

Comment (majiayu000) [reply config/config.go]: Done — removed the `int64()` conversion. Direct comparison works since `Duration` is based on `int64`.

Comment (Hipska) [reply config/config.go]: Are you intentionally always replying twice?

File: config/config.go
Comment (Hipska) [reply config/config.go:1691]: Please resolve comments when addressed.

File: config/config.go [hunk 8]
```diff
@@ -1689,6 +1692,9 @@ func (c *Config) buildInput(name, source string, tbl *ast.Table) (*models.InputC
 	cp.Precision, _ = c.getFieldDuration(tbl, "precision")
 	cp.CollectionJitter, _ = c.getFieldDuration(tbl, "collection_jitter")
 	cp.CollectionOffset, _ = c.getFieldDuration(tbl, "collection_offset")
+	if cp.CollectionOffset < 0 {
+		return nil, fmt.Errorf("negative collection_offset %q is not allowed for input %s", cp.CollectionOffset, name)
```
Comment (Hipska) [inline config/config.go]: The error trickles all the way where `addInput` gets called and then is prefixed with `error parsing <name>, `, so adding the name in the error is not strictly needed.
```suggestion
		return nil, fmt.Errorf("negative collection_offset %q is not allowed", cp.CollectionOffset)
```

File: config/config.go (hunk 7 above)
Comment (majiayu000) [reply config/config.go]: No, sorry about that — the duplicate replies were unintentional. I'll be more careful going forward.

File: config/config.go
Comment (majiayu000) [reply config/config.go:1691]: Understood — resolving addressed comments now.

File: config/config.go (hunk 8 above)
Comment (majiayu000) [reply config/config.go]: Done — removed the input name from the error message since `addInput` already prefixes it. Fixed in 5006ed0c7.

**Comment by skartikey** [comment]
@majiayu000 Thanks for the contribution!
