### PR TITLE
fix(inputs.s7comm): Allow PDU-size to be set as config option

### LINKED ISSUE #14042: inputs.s7comm PDU size exceeded
### Relevant telegraf.conf

```toml
[[inputs.s7comm]]
  server = "10.0.0.1:102"
  rack = 0
  slot = 2

  ## Metric definition(s)
  [[inputs.s7comm.metric]]
    name = "Sinumerik"

    fields = [
      {address= "DB170.R2",    name= "GrindTime Red",     },
      {address= "DB170.R6",    name= "GrindTime Blue",    },
      {address= "DB170.R10",   name= "LoadTime Red",      },
      {address= "DB170.R14",   name= "LoadTime Blue",     },
      {address= "DB170.R18",   name= "WheelWear Red",     },
      {address= "DB170.R22",   name= "WheelWear Blue",    },
      {address= "DB170.R26",   name= "WheelLimit Red",    },
      {address= "DB170.R30",   name= "WheelLimit Blue",   },
      {address= "DB170.R34",   name= "MeasPos Red",       },
      {address= "DB170.R38",   name= "MeasPos Blue",      },
  
      {address= "DB160.B36",   name= "WheelLoadRed",      },
      {address= "DB160.R38",   name= "WheelRPMRed",       },
      {address= "DB160.R42",   name= "WheelCurrentRed",   },
      {address= "DB160.R52",   name= "WheelMaxHoldRed",   },
      {address= "DB161.B36",   name= "WheelLoadBlue",     },
      {address= "DB161.R38",   name= "WheelRPMBlue",      },
      {address= "DB161.R42",   name= "WheelCurrentBlue",  },
      {address= "DB161.R52",   name= "WheelMaxHoldBlue",  },
  
      {address= "DB1050.X0.1",    name= "RedGrindingActive"     },
      {address= "DB1050.X2.1",    name= "BlueGrindingActive"    },
  
      {address= "DB21.X35.5",       name= "NC running"           },
      {address= "DB21.X36.6",       name= "Channnel Alarm active"},
  
      {address= "PE32.X32.1",  name= "Controll On"      },
      {address= "PE34.X34.2",  name= "Emergency Stop"   },
      {address= "PE32.X32.7",  name= "Automatic active" },
      {address= "PE2.X2.7",   name= "KeyPos0-Auto"     },
      {address= "PE2.X2.6",   name= "KeyPos1"          },
      {address= "PE3.X3.6",   name= "KeyPos2"          },
      {address= "PE4.X4.4",   name= "KeyPos3-Setup"    },
      
    ]

    ## Tags assigned to the metric
    [inputs.s7comm.metric.tags]
      device = "Sinumerik"


[[outputs.discard]]
```

### Logs from Telegraf

```text
2023-10-03T09:04:58Z I! Loading config: telegraf.conf
2023-10-03T09:04:58Z I! Starting Telegraf 1.29.0-99bb626b brought to you by InfluxData the makers of InfluxDB
2023-10-03T09:04:58Z I! Available plugins: 15 inputs, 9 aggregators, 29 processors, 24 parsers, 4 outputs, 5 secret-stores
2023-10-03T09:04:58Z I! Loaded inputs: s7comm
2023-10-03T09:04:58Z I! Loaded aggregators: 
2023-10-03T09:04:58Z I! Loaded processors: 
2023-10-03T09:04:58Z I! Loaded secretstores: 
2023-10-03T09:04:58Z I! Loaded outputs: discard
2023-10-03T09:04:58Z I! Tags enabled: host=XXXXX
2023-10-03T09:04:58Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"XXXXX", Flush Interval:10s
2023-10-03T09:04:58Z D! [agent] Initializing plugins
2023-10-03T09:04:58Z D! [agent] Connecting outputs
2023-10-03T09:04:58Z D! [agent] Attempting connection to [outputs.discard]
2023-10-03T09:04:58Z D! [agent] Successfully connected to outputs.discard
2023-10-03T09:04:58Z D! [agent] Starting service inputs
2023-10-03T09:05:00Z D! [inputs.s7comm] Reading batch 1...
2023-10-03T09:05:00Z E! [inputs.s7comm] Error in plugin: reading batch 1 failed: CPU : total data exceeds the PDU size
^C2023-10-03T09:05:07Z D! [agent] Stopping service inputs
2023-10-03T09:05:07Z D! [agent] Input channel closed
2023-10-03T09:05:07Z I! [agent] Hang on, flushing any cached metrics before shutdown
2023-10-03T09:05:07Z D! [outputs.discard] Buffer fullness: 0 / 10000 metrics
2023-10-03T09:05:07Z I! [agent] Stopping running outputs
2023-10-03T09:05:07Z D! [agent] Stopped Successfully
```

### System info

Telegraf 1.29, Ubuntu 22.04 LTS, S7 CPU 317-3PN/DP

### Docker

_No response_

### Steps to reproduce

1. Run Telegraf 1.29 s7comm plugin with more than 18 fields adressing S7 CPU 317-3PN/DP (Sinumerik 840D sl)

### Expected behavior

Successful request.

### Actual behavior

Request fails with errormessage  
```[inputs.s7comm] Error in plugin: reading batch 1 failed: CPU : total data exceeds the PDU size```

### Additional info

Suggestion: set PDU-size form config file. 

```
type S7comm struct {
	Server          string             `toml:"server"`
	Rack            int                `toml:"rack"`
	Slot            int                `toml:"slot"`
	Timeout         config.Duration    `toml:"timeout"`
	DebugConnection bool               `toml:"debug_connection"`
	Configs         []metricDefinition `toml:"metric"`
	Log             telegraf.Logger    `toml:"-"`
	BatchMaxSize    int                `toml:"pdu_size"`

	handler *gos7.TCPClientHandler
	client  gos7.Client
	batches []batch
}
```

```
if len(current.items) == s.BatchMaxSize {
	s.batches = append(s.batches, current)
	current = batch{}
}
```
Setting the PDU-Size to 18 resolves the issue on this PLC.

Would be happy to provide PR.

### PR DESCRIPTION
**Pull request by phagemann**
- [x] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [ ] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #14042 

Moved `const maxRequestsPerBatch` to be set from config file by keyword `pdu_size`

### CODE REVIEW

**Review by powersj — COMMENTED** [review]
Thanks for taking the time to put up a PR. One question inline, otherwise I'll defer to Sven on this one.

File: plugins/inputs/s7comm/type_conversions.go [hunk 1]
```diff
@@ -13,7 +13,7 @@ func determineConversion(dtype string, extra int) converterFunc {
 	switch dtype {
 	case "X":
 		return func(buf []byte) interface{} {
-			return (buf[0] & (1 << extra)) != 0
+			return buf[0] != 0
```
Comment (powersj) [inline plugins/inputs/s7comm/type_conversions.go:16]: Should this be in this PR?

Comment (phagemann) [reply plugins/inputs/s7comm/type_conversions.go:16]: Nope, your right. It is related to issue 14043. Gone remove this. This will resolve the unused param as well.

**Review by powersj — APPROVED** [review]

**Review by srebhan — APPROVED** [review]
Thanks for your contribution @phagemann!

**Comment by phagemann** [comment]
Thanks for your great work maintaining this project! =)
