### PR TITLE
Fix memory leak in couchbase input

### LINKED ISSUE #9495: Telegraf 1.19 lack of memory with couchbase plugin
I've tested this, and now we have another huge problem. I applied a new version of telegraf in a production environment and telegraf processes consumes a lot of memory and don't purge it. Memory usage is still increasing until instance stopped work. It happens only with telegraf with couchbase plugin

image

Zrzut ekranu 2021-07-13 o 09 47 15
In the second screenshot, you can see memory usage increasing and after downgrade to 1.18.3 back to normal stable consumption

Thread started here: https://github.com/influxdata/telegraf/pull/9448

### PR DESCRIPTION
**Pull request by akrantz01**
### Required for all PRs:

- [x] Updated associated README.md
- [x] Wrote appropriate unit tests.

resolves #9495 

Fixes a memory leak in the `couchbase` plugin by closing all pools after they are done being used. The leak showed up after updating to `go-couchbase` v0.1.0 in #9412. It appears to be caused by circular references between buckets and their corresponding pools (I think this is the cause, I'm not entirely sure though).

### CODE REVIEW

File: plugins/inputs/couchbase/couchbase.go [hunk 1]
```diff
@@ -70,34 +70,34 @@ func (cb *Couchbase) Gather(acc telegraf.Accumulator) error {
...
+	}
+
+	// `default` is the only possible pool name. It's a
+	// placeholder for a possible future Couchbase feature. See
+	// http://stackoverflow.com/a/16990911/17498.
+	pool, err := client.GetPool("default")
+	if err != nil {
+		return err
 	}
+	defer pool.Close()
```
Comment (ssoroka) [inline plugins/inputs/couchbase/couchbase.go:88]: why do we close the pool and not the connection? Also shouldn't we be reusing both?

Comment (akrantz01) [reply plugins/inputs/couchbase/couchbase.go:88]: Ideally, we would be reusing both. However, if we reuse the pool, there is no way to refresh the bucket map, so we wouldn't be able to get metrics for new buckets, and we would start erroring if a bucket gets deleted. 

We don't close the connection because there isn't a method to do that.

**Review by MyaLongmire — APPROVED** [review]
