### PR TITLE
fix(inputs.cisco_telemetry_mdt): add operation-metric and class-policy

### LINKED ISSUE #8261: cisco_telemetry_mdt not working correctly with XR telemetry probe for Y1731 statistics
### Relevant telegraf.conf:

```toml
# gRPC Dial-Out Telemetry Listener
[[inputs.cisco_telemetry_mdt]]
transport = "grpc"
service_address = ":57500"
```

### System info:

Telegraf 1.15.3
CentOS Linux release 7.8.2003 (Core)
Derived from Red Hat Enterprise Linux 7.8 (Source)
Testing against device running IOS-XR 7.1.2.32I

### Steps to reproduce:

1. Configure XR device with ethernet sla probes for Loss Measurement and Delay measurement
```
ethernet sla
 profile DM-Test1 type cfm-delay-measurement
  probe
   send burst every 60 seconds packet count 60 interval 1 seconds
   priority 3
   packet size 152
  !
  schedule
   every 1 minutes for 1 minutes
  !
  statistics
   measure round-trip-delay
    aggregate bins 10 width 2000
    buckets size 1 probes
    buckets archive 10
   !
   measure one-way-delay-sd
    aggregate bins 10 width 2000
    buckets size 1 probes
    buckets archive 10
   !
   measure one-way-delay-ds
    aggregate bins 10 width 2000
    buckets size 1 probes
    buckets archive 10
   !
   measure round-trip-jitter
    aggregate bins 10 width 2000
    buckets size 1 probes
    buckets archive 10
   !
   measure one-way-jitter-sd
    aggregate bins 10 width 2000
    buckets size 1 probes
    buckets archive 10
   !
   measure one-way-jitter-ds
    aggregate bins 10 width 2000
    buckets size 1 probes
    buckets archive 10
   !
  !
 !
  profile LM-Test2 type cfm-synthetic-loss-measurement
  probe
   send burst every 60 seconds packet count 60 interval 1 seconds
   priority 3
   packet size 152
  !
  schedule
   every 1 minutes for 60 seconds
  !
  statistics
   measure one-way-loss-sd
    aggregate bins 5 width 5
    buckets size 1 probes
    buckets archive 10
   !
   measure one-way-loss-ds
    aggregate bins 5 width 5
    buckets size 1 probes
    buckets archive 10
   !
  !
 !
```
2. Apply the probes to the interface
```
interface HundredGigE0/0/1/0.9 l2transport
 encapsulation dot1q 9
 mtu 9150
 ethernet service-activation-test
  permit all
 !
 ethernet cfm
  mep domain EVC service Y1731-Scale-EPNM9 mep-id 2
   sla operation profile DM-Test1 target mep-id 1
   sla operation profile LM-Test2 target mep-id 1
  !
 !
 ethernet loopback
  permit external
  permit internal
 !
 service-policy input 1R2C_PD-1000_v01
!
```
3.  Configure telemetry probe on the device for the oper YANG model with the ethernet sla statistics

```
sensor-group CFM
  sensor-path Cisco-IOS-XR-infra-sla-oper:sla/protocols/Cisco-IOS-XR-ethernet-cfm-oper:ethernet/Cisco-IOS-XR-ethernet-cfm-oper:statistics-historicals
 !
```

### Expected behavior:

Telegraf should parse the telemetry stream for both the loss measurement (LM-Test2) and delay measurement (DM-Test1)
### Actual behavior:

Telegraf only parses out the LM-Test2 data.  

```
{
	"fields": {
		"display_long": "Source: Interface HundredGigE0/0/1/0.244, Domain EVC\nDestination: Target MEP-ID 1",
		"display_short": "Hu0/0/1/0.244, dom EVC, to MEP-ID 1",
		"flr_calculation_interval": 60000,
		"operation_metric/bucket/average": 0,
		"operation_metric/bucket/contents/aggregated/bins/count": 0,
		"operation_metric/bucket/contents/aggregated/bins/lower_bound": 20,
		"operation_metric/bucket/contents/aggregated/bins/sum": 0,
		"operation_metric/bucket/contents/aggregated/bins/upper_bound": 100,
		"operation_metric/bucket/contents/bucket_type": "bucket-type-bins",
		"operation_metric/bucket/corrupt": 0,
		"operation_metric/bucket/data_lost_count": 0,
		"operation_metric/bucket/data_sent_count": 0,
		"operation_metric/bucket/duplicates": 0,
		"operation_metric/bucket/duration": 60,
		"operation_metric/bucket/lost": 60,
		"operation_metric/bucket/maximum": 0,
		"operation_metric/bucket/minimum": 0,
		"operation_metric/bucket/out_of_order": 0,
		"operation_metric/bucket/overall_flr": 0,
		"operation_metric/bucket/premature_reason": 0,
		"operation_metric/bucket/result_count": 0,
		"operation_metric/bucket/sent": 60,
		"operation_metric/bucket/standard_deviation": 0,
		"operation_metric/bucket/start_at": 1602524125,
		"operation_metric/bucket/suspect_cleared_mid_bucket": "false",
		"operation_metric/bucket/suspect_clock_drift": "false",
		"operation_metric/bucket/suspect_flr_low_packet_count": "false",
		"operation_metric/bucket/suspect_management_latency": "false",
		"operation_metric/bucket/suspect_memory_allocation_failed": "false",
		"operation_metric/bucket/suspect_misordering": "false",
		"operation_metric/bucket/suspect_multiple_buckets": "false",
		"operation_metric/bucket/suspect_premature_end": "false",
		"operation_metric/bucket/suspect_probe_restarted": "false",
		"operation_metric/bucket/suspect_schedule_latency": "false",
		"operation_metric/bucket/suspect_send_fail": "false",
		"operation_metric/bucket/suspect_start_mid_bucket": "false",
		"operation_metric/bucket/time_of_maximum": 0,
		"operation_metric/bucket/time_of_minimum": 0,
		"operation_metric/config/bins_count": 5,
		"operation_metric/config/bins_width": 5,
		"operation_metric/config/bucket_size": 1,
		"operation_metric/config/bucket_size_unit": "probes-per-bucket",
		"operation_metric/config/buckets_archive": 10,
		"operation_metric/config/metric_type": "metric-one-way-flr-ds",
		"operation_schedule/schedule_duration": 60,
		"operation_schedule/schedule_interval": 60,
		"operation_schedule/start_time": 25,
		"operation_schedule/start_time_configured": "false",
		"probe_type": "cfm-synthetic-loss-measurement",
		"specific_options/configured_operation_options/profile_name": "LM-Test2",
		"specific_options/oper_type": "operation-type-configured"
	},
	"name": "Cisco-IOS-XR-infra-sla-oper:sla/protocols/Cisco-IOS-XR-ethernet-cfm-oper:ethernet/statistics-historicals/statistics-historical",
	"tags": {
		"domain_name": "EVC",
		"host": "nso1.cisco.com",
		"interface_name": "HundredGigE0/0/1/0.244",
		"mep_id": "1",
		"path": "Cisco-IOS-XR-infra-sla-oper:sla/protocols/Cisco-IOS-XR-ethernet-cfm-oper:ethernet/statistics-historicals/statistics-historical",
		"profile_name": "LM-Test2",
		"source": "ncs540-49",
		"subscription": "Sub1"
	},
	"timestamp": 1602524226625000000
}
```
### Additional info:
Verified that the device is sending both data sets using raw TCP socket monitor.  This is an issue with Telegraf

### PR DESCRIPTION
**Pull request by dd-accedian**
… prefixes

fix metrics getting overwritten when there are multiple class policies and operation metrics

# Required for all PRs

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #8261

### CODE REVIEW

**Comment by srebhan** [comment]
@dd-accedian can you please sign the CLA and let me know once you are done?!?
We can only review and merge code where the author signed the CLA...

**Comment by ddaka** [comment]
!signed-cla

**Comment by dd-accedian** [comment]
!signed-cla

File: plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go [hunk 1]
```diff
@@ -406,7 +406,14 @@ func (c *CiscoTelemetryMDT) handleTelemetry(data []byte) {
...
 		// Parse values
 		for _, subfield := range content.Fields {
-			c.parseContentField(grouper, subfield, "", msg.EncodingPath, tags, timestamp)
+			prefix := ""
+			if subfield.Name == "operation-metric" {
+				prefix = subfield.Fields[0].Fields[0].GetStringValue()
+			}
+			if subfield.Name == "class-stats" {
+				prefix = subfield.Fields[0].Fields[1].GetStringValue()
+			}
```
Comment (srebhan) [inline plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go:415]: Can we please make this a `switch` statement in case more "names" are relevant later?
```suggestion
			switch subfield.Name {
			case "operation-metric":
				prefix = subfield.Fields[0].Fields[0].GetStringValue()
			case "class-stats":
				prefix = subfield.Fields[0].Fields[1].GetStringValue()
			}
```

**Review by srebhan — COMMENTED** [review]
@dd-accedian thanks for the contribution. I've just one small comment...

File: plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go (hunk 1 above)
Comment (dd-accedian) [reply plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go]: @srebhan it makes sense, I applied the suggested change

**Review by srebhan — APPROVED** [review]
Looks good to me. Thanks for the fix @dd-accedian!

**Review by powersj — APPROVED** [review]
