### PR TITLE
fix: Set the default value correctly

### LINKED ISSUE #9979: The default value is not set correctly (nvidia_smi plugin)
### Relevant telegraf.conf:

```toml
# Pulls statistics from nvidia GPUs attached to the host
[[inputs.nvidia_smi]]
## Optional: path to nvidia-smi binary, defaults to $PATH via exec.LookPath
# bin_path = "/usr/bin/nvidia-smi"

## Optional: timeout for GPU polling
# timeout = "5s"
```

### System info:

Windows 10

### Steps to reproduce:

1. Use the default plugin configuration.
2. Run.

### Expected behavior:

Gather properly or throw exception

### Actual behavior:

Neither gather correctly nor throw an exception

### Additional info:

After debugging, I found that the reason is that the **default value is not set correctly**
See [HERE](https://github.com/influxdata/telegraf/blob/8265969f523cddb601211e4f070fef4a56b7aae0/plugins/inputs/nvidia_smi/nvidia_smi.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L64)

See [PR9980](https://github.com/influxdata/telegraf/issues/9980)

### PR DESCRIPTION
**Pull request by since1986**
The smi path exception was thrown in Init() (previously thrown in Gather()), the purpose of this is to find the problem earlier

resolves #9979

### CODE REVIEW

File: plugins/inputs/nvidia_smi/nvidia_smi.go [hunk 1]
```diff
@@ -31,20 +32,34 @@ func (smi *NvidiaSMI) Description() string {
...
+		smi.BinPath, err = exec.LookPath("nvidia-smi")
+		if err != nil {
+			return errors.New("nvidia-smi not found: verify that nvidia-smi is installed and that nvidia-smi is in your PATH")
+		}
+	}
+	// fail-fast
 	if _, err := os.Stat(smi.BinPath); os.IsNotExist(err) {
-		return fmt.Errorf("nvidia-smi binary not at path %s, cannot gather GPU data", smi.BinPath)
+		return fmt.Errorf("nvidia-smi binary not at path %s", smi.BinPath)
 	}
```
Comment (srebhan) [inline plugins/inputs/nvidia_smi/nvidia_smi.go:56]: Can we please make this backward compatible using
```golang
	// fail-fast
	if _, err := os.Stat(smi.BinPath); os.IsNotExist(err) {
		path, patherr := exec.LookPath("nvidia-smi")
		if err != nil {
			return errors.New("nvidia-smi not found in %q and not in PATH; please make sure nvidia-smi is installed and/or is in PATH", smi.BinPath)
		}
		smi.BinPath = path
	}
```
and keeping the default for the binary at `/usr/bin/nvidia-smi`?

File: plugins/inputs/nvidia_smi/nvidia_smi.go [hunk 2]
```diff
@@ -31,20 +31,31 @@ func (smi *NvidiaSMI) Description() string {
...
 func (smi *NvidiaSMI) SampleConfig() string {
 	return `
-  ## Optional: path to nvidia-smi binary, defaults to $PATH via exec.LookPath
+  ## Optional: path to nvidia-smi binary, defaults "/usr/bin/nvidia-smi"
+  ## We will first try to locate the nvidia-smi binary with the explicitly specified value (or default value), 
+  ## if it is not found, we will try to locate it on PATH(exec.LookPath), if it is still not found, an error will be returned
   # bin_path = "/usr/bin/nvidia-smi"
 
-  ## Optional: timeout for GPU polling
+  ## Optional: timeout for GPU polling, defaults "5s"
```
Comment (srebhan) [inline plugins/inputs/nvidia_smi/nvidia_smi.go:39]: You don't need to add the `, defaults "5s"` here. The convention is that the default value is the commented value.

**Review by srebhan — COMMENTED** [review]
Nice, thanks for the update @since1986! Just one small comment left... :-)

File: plugins/inputs/nvidia_smi/nvidia_smi.go (hunk 2 above)
Comment (since1986) [reply plugins/inputs/nvidia_smi/nvidia_smi.go]: ok

File: plugins/inputs/nvidia_smi/README.md [hunk 3]
```diff
@@ -7,13 +7,19 @@ This plugin uses a query on the [`nvidia-smi`](https://developer.nvidia.com/nvid
 ```toml
 # Pulls statistics from nvidia GPUs attached to the host
 [[inputs.nvidia_smi]]
-  ## Optional: path to nvidia-smi binary, defaults to $PATH via exec.LookPath
+  ## Optional: path to nvidia-smi binary, defaults "/usr/bin/nvidia-smi"
+  ## We will first try to locate the nvidia-smi binary with the explicitly specified value (or default value), 
+  ## if it is not found, we will try to locate it on PATH(exec.LookPath), if it is still not found, an error will be returned
   # bin_path = "/usr/bin/nvidia-smi"
-
+
```
Comment (srebhan) [inline plugins/inputs/nvidia_smi/README.md:14]: Remove those spaces here... Sorry for being pedantic on this... :-S

**Review by srebhan — COMMENTED** [review]
Beautiful. Only some spaces left. Maybe set your editor to "trim trailing spaces"?

**Comment by srebhan** [comment]
@since1986 can you please update the PR description above as we now don't face a breaking change I think?

**Review by srebhan — APPROVED** [review]
Looks good to me. Thanks for your nice work @since1986!

**Review by powersj — APPROVED** [review]

**Comment by srebhan** [comment]
@since1986 for fixing the CI issue, try rebasing on the latest master. It would help us to understand what to do in similar cases.

Anyway @powersj  I think it's save to merge the PR despite the CI errors as those are only formatting issues in the README...
