### PR TITLE
fix: snmp marshal error

### LINKED ISSUE #10304: Telegraf 1.21.1: Marshal error with SNMP PowerNet MIB
### Relevent telegraf.conf

```toml
[[inputs.snmp]]
  agents = [ "SNIP" ]
  version = 2
  community = "SNIP"
  interval = "60s"
  timeout = "10s"
  retries = 3

  [[inputs.snmp.field]]
    name = "hostname"
    oid = "RFC1213-MIB::sysName.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "uptime"
    oid = "DISMAN-EXPRESSION-MIB::sysUpTimeInstance"

  [[inputs.snmp.field]]
    name = "model"
    oid = "PowerNet-MIB::upsBasicIdentModel.0"

  [[inputs.snmp.field]]
      name = "name"
      oid = "PowerNet-MIB::upsBasicIdentName.0"

  [[inputs.snmp.field]]
      name = "upsBasicBatteryTimeOnBattery"
      oid = "PowerNet-MIB::upsBasicBatteryTimeOnBattery.0"

  [[inputs.snmp.field]]
      name = "upsAdvBatteryRunTimeRemaining"
      oid = "PowerNet-MIB::upsAdvBatteryRunTimeRemaining.0"

  [[inputs.snmp.field]]
      name = "upsAdvBatteryReplaceIndicator"
      oid = "PowerNet-MIB::upsAdvBatteryReplaceIndicator.0"

  [[inputs.snmp.field]]
      name = "upsHighPrecBatteryCapacity"
      oid = "PowerNet-MIB::upsHighPrecBatteryCapacity.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsHighPrecBatteryTemperature"
      oid = "PowerNet-MIB::upsHighPrecBatteryTemperature.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsBasicOutputStatus"
      oid = "PowerNet-MIB::upsBasicOutputStatus.0"

  [[inputs.snmp.field]]
      name = "upsHighPrecOutputLoad"
      oid = "PowerNet-MIB::upsHighPrecOutputLoad.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsHighPrecOutputEfficiency"
      oid = "PowerNet-MIB::upsHighPrecOutputEfficiency.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsHighPrecOutputVoltage"
      oid = "PowerNet-MIB::upsHighPrecOutputVoltage.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsHighPrecInputLineVoltage"
      oid = "PowerNet-MIB::upsHighPrecInputLineVoltage.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsHighPrecOutputCurrent"
      oid = "PowerNet-MIB::upsHighPrecOutputCurrent.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsHighPrecOutputEnergyUsage"
      oid = "PowerNet-MIB::upsHighPrecOutputEnergyUsage.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsAdvOutputActivePower"
      oid = "PowerNet-MIB::upsAdvOutputActivePower.0"
      conversion = "float(0)"

  [[inputs.snmp.field]]
      name = "upsAdvOutputApparentPower"
      oid = "PowerNet-MIB::upsAdvOutputApparentPower.0"
      conversion = "float(0)"
```

### System info

Telegraf 1.21.1

### Docker

_No response_

### Steps to reproduce

1. Put this config in
2. Wait for it to pull
3. Observe error `2021-12-18T08:06:00Z E! [inputs.snmp] Error in plugin: agent SNIP: performing get on field model: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier`

### Expected behavior

It works

### Actual behavior

`2021-12-18T08:06:00Z E! [inputs.snmp] Error in plugin: agent SNIP: performing get on field model: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier`

### Additional info

This uses the PowerNet MIB from APC's website: https://www.apc.com/shop/us/en/products/PowerNet-MIB-v4-3-2/P-SFPMIB432
There is no errors loading the MIB, and playing around with gosmi's commandline tools and small test programs with it, it seems to be able to translate the descriptions to OIDs correctly.

This used to work before the switch to gosmi. Other MIBs (such as UPS-MIB) work fine.

Also worthy of note if I replace the string representations (`PowerNet-MIB::...`) with their full numeric representation, these errors vanish

### LINKED ISSUE #10305: Marshal error with SNMP plugin 1.21.0
### Relevent telegraf.conf

```toml
[[inputs.snmp]]
  agents = [ "udp://fgt01:161" ]
  version = 2
  timeout = "5s"
  retries = 3
  community = "public"
  name = "fortisnmp"

	[[inputs.snmp.field]]
		name = "hostname"
		oid = "SNMPv2-MIB::sysName.0"
		is_tag = true

	[[inputs.snmp.field]]
		name = "cpu"
		oid = "FORTINET-FORTIGATE-MIB::fgSysCpuUsage.0"

	[[inputs.snmp.field]]
		name = "memory"
		oid = "FORTINET-FORTIGATE-MIB::fgSysMemUsage.0"
```

### System info

Telegraf 1.20.0, Ubuntu 20.04.3.

### Docker

_No response_

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

No errors.

### Actual behavior

After upgrade to 1.21.0, the snmp agent is having trouble fetching certain OIDs.

```
telegraf[505949]: 2021-12-18T21:14:00Z E! [inputs.snmp] Error in plugin: agent 192.168.62.11:161: performing get on field signal: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier
telegraf[505949]: 2021-12-18T21:14:00Z E! [inputs.snmp] Error in plugin: agent 192.168.60.122:161: performing get on field model: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier
telegraf[505949]: 2021-12-18T21:14:10Z E! [inputs.snmp] Error in plugin: agent 192.168.60.1:161: performing get on field cpu: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier
telegraf[505949]: 2021-12-18T21:14:10Z E! [inputs.snmp] Error in plugin: agent 192.168.62.10:161: performing get on field signal: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier
telegraf[505949]: 2021-12-18T21:14:10Z E! [inputs.snmp] Error in plugin: agent 192.168.62.11:161: performing get on field signal: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier

```
### Additional info

_No response_

### PR DESCRIPTION
**Pull request by MyaLongmire**
### Required for all PRs:

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #10305, resolves #10304 

Thank you @Doridian for the debugging and the solution!! 
Store modules in an array of strings and then load them in as this ensures modules are loaded in the correct order. Also added better error messaging instead of the marshal: marshalPDU error.

### CODE REVIEW

File: internal/snmp/translate.go [hunk 1]
```diff
@@ -169,6 +174,10 @@ func SnmpTranslateCall(oid string) (mibName string, oidNum string, oidText strin
 			return oid, oid, oid, oid, out, err
 		}
 
+		if out.RenderNumeric() == "" {
+			return oid, oid, oid, oid, out, fmt.Errorf("cannot make %v numberic, please ensure all imported mibs are in the path", oid)
+		}
+
 		oidNum = "." + out.RenderNumeric() + end
```
Comment (Hipska) [inline internal/snmp/translate.go:181]: What do you think of this? Only render the OID once.
```suggestion
		if oidNum = out.RenderNumeric(); oidNum == "" {
			return oid, oid, oid, oid, out, fmt.Errorf("cannot make %v numeric, please ensure all imported mibs are in the path", oid)
		}

		oidNum = "." + oidNum + end
```

**Review by Hipska — CHANGES_REQUESTED** [review]

File: internal/snmp/translate.go (hunk 1 above)
Comment (MyaLongmire) [reply internal/snmp/translate.go]: you got it

**Review by Hipska — APPROVED** [review]

**Review by powersj — APPROVED** [review]

**Comment by Derek-K** [comment]
Just updated to 1.21.2-1, my APC UPS readings are back (except model and device name, but it could be my bad when I was trying to debug the issues earlier) Thanks!
