### PR TITLE
fix(internal): Fix time parsing for abbreviated timezones

### LINKED ISSUE #12960: Telegraf/golang does not parse timezone correctly from timestamp
### Relevant telegraf.conf

```toml
## The column to extract time information for the metric
  ## `csv_timestamp_format` must be specified if this is used.
  ## Will not be included as field in metric.
  csv_timestamp_column = "Timestamp"

  ## The format of time data extracted from `csv_timestamp_column`
  ## this must be specified if `csv_timestamp_column` is specified
  csv_timestamp_format = "2006-01-02 15:04:05 MST"

  ## The timezone of time data extracted from `csv_timestamp_column`
  ## in case of there is no timezone information.
  ## It follows the  IANA Time Zone database.
  csv_timezone = "Local"
```

### Logs from Telegraf

```text
N/A
```

### System info

Telegraf 1.26

### Docker

_No response_

### Steps to reproduce

TBD

### Expected behavior

Telegraf to parse the timestamp in the correct timezone.

### Actual behavior

Metric timestamp has incorrect offset.

### Additional info

Golang-nuts conversation: [Parsing time with timezones seem to fail](https://groups.google.com/g/golang-nuts/c/hDMdnm_jUFQ/m/yeL9IHOsAQAJ)

Workaround seems to be like this:
```golang
stamp, _ := time.Parse(layout, v)
loc, _ := time.LoadLocation(stamp.Location().String())
stamp, _ = time.ParseInLocation(layout, v, loc)
```

### PR DESCRIPTION
**Pull request by srebhan**
- [ ] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #12960
upstream issues https://github.com/golang/go/issues/56528, https://github.com/golang/go/issues/9617

Golang does not handle ambiguous timezones which holds true for almost all abbreviated timezones. As a workaround, (see [Golang discussion](https://groups.google.com/g/golang-nuts/c/hDMdnm_jUFQ/m/yeL9IHOsAQAJ)) we can parse times with abbreviated timezones first to get the timezone's _name_ and then forcefully parse the time-string in the found timezone. By doing this we can handle many of the abbreviated timezones correctly assuming the "most probable" of the ambiguous timezone abbreviations, e.g. "Mountain Standard Time" for "MST".

### CODE REVIEW

File: internal/internal.go [hunk 1]
```diff
@@ -391,5 +391,32 @@ func parseTime(format string, timestamp string, location *time.Location) (time.T
...
+	if !strings.Contains(format, "MST") {
+		return time.ParseInLocation(format, timestamp, loc)
+	}
+
+	// Golang does not parse times with ambiguous timezone abbreviations,
+	// but only parses the time-fields and the timezone NAME with a zero
+	// offset (see https://groups.google.com/g/golang-nuts/c/hDMdnm_jUFQ/m/yeL9IHOsAQAJ).
+	// To handle those timezones correctly we can use the timezone-name and
+	// force parsing the time in that timezone. This way we get the correct
+	// time for the "most probably" of the ambiguous timezone-abbreviations.
```
Comment (powersj) [inline internal/internal.go:404]: What does this mean in practice? For example, I live in MST/MDT. What happens if the logs I am parsing are actually from Malaysian standard time (the other MST).

File: internal/internal.go [hunk 2]
```diff
@@ -391,5 +391,32 @@ func parseTime(format string, timestamp string, location *time.Location) (time.T
...
+	ts, err := time.Parse(format, timestamp)
+	if err != nil {
+		return time.Time{}, err
+	}
+	zone, offset := ts.Zone()
+	if zone == "UTC" || offset != 0 {
+		return ts.In(loc), nil
+	}
+	abbrevLoc, err := time.LoadLocation(zone)
```
Comment (powersj) [inline internal/internal.go:413]: How does this resolve something like "MST"?

**Review by powersj — COMMENTED** [review]
I have questions about the behavior and what we are expecting from the change.

File: internal/internal.go [hunk 3]
```diff
@@ -391,5 +391,32 @@ func parseTime(format string, timestamp string, location *time.Location) (time.T
 	case "stampnano":
 		format = time.StampNano
 	}
-	return time.ParseInLocation(format, timestamp, loc)
+
+	if !strings.Contains(format, "MST") {
+		return time.ParseInLocation(format, timestamp, loc)
+	}
```
[the remark this answers is not in the document]
Comment (srebhan) [reply internal/internal.go:397]: Not sure why this should be opt-in!? You currently get an unexpected and **wrong** time for all timestamps with a timezone-abbreviation as the time-offset to UTC is **always** zero no matter which timezone you have in your string... For example `2023-06-01 12:00:00 MST` would result in `2023-06-01T12:00:00+0000` which is clearly wron as it should be `2023-06-01T05:00:00+0000` or `2023-06-01T12:00:00-0700` . Even worse printing the timestamp will display the original string as the zone abbreviation is kept but the offset is zero. I can make this an opt-in but I really don't see why someone wants this buggy behavior...

File: internal/internal.go (hunk 1 above)
Comment (srebhan) [reply internal/internal.go:404]: It means that zones like "MST" and "PST" are "Mountain standard" and "Pacific standard" as you probably would expect. Of you want to parse "Malaysian standard time" and use "MST" you are doomed. :-) However, I don't see any other way except for we have a way for the user to provide an _extensive_ (i.e. covering all abbreviations that _might_ occur) mapping of abbrev to time-offset...

File: internal/internal.go (hunk 2 above)
Comment (srebhan) [reply internal/internal.go:413]: See https://cs.opensource.google/go/go/+/refs/tags/go1.20.4:src/time/zoneinfo.go;l=662. It uses the zoneinfo file to resolve the abbreviation.

File: internal/internal.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (Hipska) [reply internal/internal.go:397]: Correct, this is a bug fix, not a new feature..

**Review by Hipska — APPROVED** [review]

File: internal/internal.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (powersj) [reply internal/internal.go:397]: Then I need to request two additions:

1) An agent-level option that sets this new behavior. Unlike other options you can set the default to the new behavior, but the user needs to have a way to opt-out.
2) Documentation that shows a user how to set the zone info.

While I understand you see the change as fixing wrong behavior, it does not fully correct the behavior for all our users. You said below a user should not use MST to mean Malaysian standard time, however that is an entirely valid use case and responding to a user to "not do that" is entirely unacceptable. Documentation will help resolve this.

Users who grab the new version of telegraf with this change will see timestamps that are affected by this, suddenly change. If a user comes to you and says you broke all my alerting or reporting because of this, then what? The option to opt-out will resolve this.

[the remark this answers is not in the document]
Comment (Hipska) [reply internal/internal.go:397]: These users need to set a location or timezone, as they are probably already doing since otherwise they would have wrong timestamps..

For CSV parsing this is done with `csv_timezone`, other parsers have similar option.

I agree to have documentation on how to set this advanced timezone info..

[the remark this answers is not in the document]
Comment (srebhan) [reply internal/internal.go:397]: @powersj I agree on the documentation point (item 2) but I strongly disagree with the option. The current situation is that everyone using abbreviations **now get the wrong time** and this also holds for MST meaning Malaysian! Even worse, currently we accept arbitrary timezone abbreviations, even those that do not exists e.g. `XYZ`, without error and **completely ignoring those** and return a time that is in UTC (offset zero). So your MST time is wrong and always as if you provided `UTC`. Relying on buggy behavior is bad and we will carry this flag till doomsday... :-(

[the remark this answers is not in the document]
Comment (powersj) [reply internal/internal.go:397]: I am not sure why you would strongly disagree with an opt-out feature ;) It is entirely optional, but gives users who get affected and need time to update a way out.

I do not disagree that the current situation is wrong behavior, but this change is breaking behavior. If we had broken this even 4 or 5 minor releases ago and are now fixing this, then this would not be needed.

**Comment by srebhan** [comment]
After a short discussion, we concluded to make the change in behavior more visible. @powersj does the warning and Changelog text work for you?

File: internal/internal.go [hunk 4]
```diff
@@ -391,5 +394,39 @@ func parseTime(format string, timestamp string, location *time.Location) (time.T
...
+	zone, offset := ts.Zone()
+	if zone == "UTC" || offset != 0 {
+		return ts.In(loc), nil
+	}
+	once.Do(func() {
+		log.Print("W! You are using abbreviated timezones for which parsing was fixed in v1.27.0.")
+		log.Print("W! Please remove any workarounds in place and check your resulting times carefully!")
+		log.Print("W! In case you experience any problems, please file an issue!")
+		log.Print("W! This message is only printed once...")
```
Comment (Hipska) [inline internal/internal.go:420]: 4 log messages ... Isn't that a bit to much to inform people of a bug being fixed?

File: internal/internal.go [hunk 5]
```diff
@@ -391,5 +394,39 @@ func parseTime(format string, timestamp string, location *time.Location) (time.T
...
+	if err != nil {
+		return time.Time{}, err
+	}
+	zone, offset := ts.Zone()
+	if zone == "UTC" || offset != 0 {
+		return ts.In(loc), nil
+	}
+	once.Do(func() {
+		log.Print("W! You are using abbreviated timezones for which parsing was fixed in v1.27.0.")
+		log.Print("W! Please remove any workarounds in place and check your resulting times carefully!")
```
Comment (powersj) [inline internal/internal.go:418]:
```suggestion
		log.Print("W! Please see the change log, remove any workarounds in place, and carefully check your data timestamps")
```

File: internal/internal.go [hunk 6]
```diff
@@ -391,5 +394,39 @@ func parseTime(format string, timestamp string, location *time.Location) (time.T
...
+		log.Print("W! In case you experience any problems, please file an issue!")
```
Comment (powersj) [inline internal/internal.go:419]:
```suggestion
		log.Print("W! If you experience any problems, please file an issue on GitHub")
```

File: internal/internal.go (hunk 4 above)
Comment (powersj) [inline internal/internal.go:420]:
```suggestion
```

File: CHANGELOG.md [hunk 7]
```diff
@@ -3,9 +3,19 @@
...
+  times with abbreviated timezones (i.e. the format ) the timezone information
+  is ignored completely and the _timestamp_ is located in UTC. This is a golang
+  issue (see [#9617](https://github.com/golang/go/issues/9617) or
+  [#56528](https://github.com/golang/go/issues/56528)). If you worked around
+  that issue, please remove the workaround before using v1.27+. In case you
+  experience issues with abbreviated timezones please file an issue!
+- Removal of old-style parser creation. This should not directly affect users as
+  it is an API change. All parsers in Telegraf are already ported to the new
+  framework. If you experience any issues with not being able to create parsers
+  let us know!
```
Comment (powersj) [inline CHANGELOG.md:18]: you removed the old-style parser creation bullet point, we probably do want that
```suggestion
  let us know!
  - Removal of old-style parser creation
```

Comment (Hipska) [reply CHANGELOG.md:18]: This whole mentioned section is exactly about that.

Comment (powersj) [reply CHANGELOG.md:18]: doh I was looking at the diff showing the missing line

File: internal/internal.go (hunk 6 above)
Comment (Hipska) [reply internal/internal.go:419]: IMHO this line can be removed, this counts for any problem experienced, not only for timezones.

File: internal/internal.go (hunk 5 above)
Comment (Hipska) [reply internal/internal.go:418]: Add this line to the previous log message to keep context

File: internal/internal.go (hunk 6 above)
Comment (srebhan) [reply internal/internal.go]: @Hipska I like to encourage people to report the stuff, so the line is well spend IMO. This worked quite well for the [gnmi plugin](https://github.com/influxdata/telegraf/blob/9c6cd94d6e46bba8ce1971685f17417b2409bd90/plugins/inputs/gnmi/gnmi.go#L33)...

**Review by powersj — APPROVED** [review]

File: internal/internal.go (hunk 6 above)
Comment (Hipska) [reply internal/internal.go]: Okay, but there it is in a single log message, not spread over multiple independent lines.. Please keep the messages together!
