### PR TITLE
fix[elasticsearch output]: add scheme to fix error in sniffing option

### LINKED ISSUE #10512: Elasticsearch Sniffing Broken
### Relevent telegraf.conf

```toml
## The full HTTP endpoint URL for your Elasticsearch instance
  ## Multiple urls can be specified as part of the same cluster,
  ## this means that only ONE of the urls will be written to each interval.
  urls = [ "http://node1.es.example.com:9200" ] # required.
  ## Elasticsearch client timeout, defaults to "5s" if not set.
  timeout = "5s"
  ## Set to true to ask Elasticsearch a list of all cluster nodes,
  ## thus it is not necessary to list all nodes in the urls config option.
  enable_sniffer = true
  ## Set to true to enable gzip compression
  enable_gzip = false
  ## Set the interval to check if the Elasticsearch nodes are available
  ## Setting to "0s" will disable the health check (not recommended in production)
  health_check_interval = "10s"
  ## HTTP basic authentication details
  # username = "telegraf"
  # password = "mypassword"
  ## HTTP bearer token authentication details
  # auth_bearer_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"

  ## Index Config
  ## The target index for metrics (Elasticsearch will create if it not exists).
  ## You can use the date specifiers below to create indexes per time frame.
  ## The metric timestamp will be used to decide the destination index name
  # %Y - year (2016)
  # %y - last two digits of year (00..99)
  # %m - month (01..12)
  # %d - day of month (e.g., 01)
  # %H - hour (00..23)
  # %V - week of the year (ISO week) (01..53)
  ## Additionally, you can specify a tag name using the notation {{tag_name}}
  ## which will be used as part of the index name. If the tag does not exist,
  ## the default tag value will be used.
  # index_name = "telegraf-{{host}}-%Y.%m.%d"
  # default_tag_value = "none"
  index_name = "telegraf-%Y.%m.%d" # required.

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

  ## Template Config
  ## Set to true if you want telegraf to manage its index template.
  ## If enabled it will create a recommended index template for telegraf indexes
  manage_template = true
  ## The template name used for telegraf indexes
  template_name = "telegraf"
  ## Set to true if you want telegraf to overwrite an existing template
  overwrite_template = false
  ## If set to true a unique ID hash will be sent as sha256(concat(timestamp,measurement,series-hash)) string
  ## it will enable data resend and update metric points avoiding duplicated metrics with diferent id's
  force_document_id = false

  ## Specifies the handling of NaN and Inf values.
  ## This option can have the following values:
  ##    none    -- do not modify field-values (default); will produce an error if NaNs or infs are encountered
  ##    drop    -- drop fields containing NaNs or infs
  ##    replace -- replace with the value in "float_replacement_value" (default: 0.0)
  ##               NaNs and inf will be replaced with the given number, -inf with the negative of that number
  # float_handling = "none"
  # float_replacement_value = 0.0
```

### Logs from Telegraf

Jan 13 00:04:10 b***** telegraf[58151]: 2022-01-13T00:04:10Z D! [agent] Successfully connected to outputs.file
Jan 13 00:04:10 b***** telegraf[58151]: 2022-01-13T00:04:10Z D! [agent] Attempting connection to [outputs.elasticsearch]
Jan 13 00:04:10 b***** telegraf[58151]: 2022-01-13T00:04:10Z E! [agent] Failed to connect to [outputs.elasticsearch], retrying in 15s, error was 'no active connection found: no Elasticsearch node available'
Jan 13 00:04:25 b***** telegraf[58151]: 2022-01-13T00:04:25Z E! [telegraf] Error running agent: connecting output outputs.elasticsearch: Error connecting to output "outputs.elasticsearch": no active connection found: no Elasticsearch node available

### System info

Telegraf 1.21.2, REHL8 Ubuntu18.04

### Docker

_No response_

### Steps to reproduce

1.  Enable sniffing for elastic search output
2. Start telegraf and try to ship logs.
...

### Expected behavior

Sniffing should find all elasticsearch nodes and configure the plugin.

### Actual behavior

It fails to find all elastic nodes due to issues with missing scheme for elastic sniffing

### Additional info

This is an issue of the elasticvsearch plugin not setting the scheme when enabling sniffing. 
https://github.com/olivere/elastic/issues/1569

As a result, the scheme must be set whenever sniffing is enabled. This is a simple fix and a PR will be sent with this bug.

### PR DESCRIPTION
**Pull request by zpriddy**
- [ N/A ] Updated associated README.md.
- [ N/A ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #10512

Set an elasticsearch configuration for `elastic.SetScheme()` matching the URL scheme from the first elastic address set in URLs. This enables the sniffing to search with the proper scheme for `https://` otherwise it will default to `http://`

We have an upstream issue opened as it seems like this should be done automatically with the elasticsearch plugin.. However currently it requires it to be configured when calling the plugin.

https://github.com/olivere/elastic/issues/1569

### CODE REVIEW

File: plugins/outputs/elasticsearch/elasticsearch.go [hunk 1]
```diff
@@ -4,17 +4,17 @@ import (
...
 	"strconv"
 	"strings"
 	"text/template"
 	"time"
 
 	"crypto/sha256"
 
-	"gopkg.in/olivere/elastic.v5"
-
 	"github.com/influxdata/telegraf"
```
Comment (srebhan) [inline plugins/outputs/elasticsearch/elasticsearch.go:18]: Please move the `"github.com/olivere/elastic"` import to where the line `"gopkg.in/olivere/elastic.v5" was before. We usually group the imports into "standard libraries" (e.g. fmt, net/url etc), "3rd party libraries" (like the elastic one) and "telegraf internal libraries" (everything stating with `github.com/influxdata/telegraf`).

File: plugins/outputs/elasticsearch/elasticsearch.go [hunk 2]
```diff
@@ -220,9 +220,15 @@ func (a *Elasticsearch) Connect() error {
 		Timeout:   time.Duration(a.Timeout),
 	}
 
+	elasticURL, err := url.Parse(a.URLs[0])
+	if err != nil {
+		return err
+	}
```
Comment (srebhan) [inline plugins/outputs/elasticsearch/elasticsearch.go:226]: As far as I see this is the approach used in the "official", isn't it? However, I'm not so sure it's a good one. Imagine, by chance, the first URL has `http` but all other URLs do have `https`... This will then throw away the majority of your nodes. Wouldn't it be better to either

1. Do a majority vote on the scheme.
2. Group the URLs by scheme and use multiple clients.

or a combination thereof?

**Review by srebhan — COMMENTED** [review]
Hey @zpriddy, thanks for tackling this issue! I have a minor comment and a question regarding scheme collection. To me using the first URL is not the best approch as it might leave you with only one possible not out of your set if, by chance, the first node is "special". I have some suggestions in the code, please have a look...

File: plugins/outputs/elasticsearch/elasticsearch.go (hunk 2 above)
Comment (archoversight) [reply plugins/outputs/elasticsearch/elasticsearch.go:226]: @srebhan all elastic search nodes in a cluster are required to use the same connection, either TLS is enabled for the cluster, or it is disabled for the cluster. Clients using the official libraries from Elastic also only ever support either TLS is enabled or TLS is disabled. You can NOT mix and match http vs https in the same cluster.

Most people will use a singular URL when sniffing (which may be a load balancer that sends requests to any one node that is up) and then sniffing will find all the other nodes.

Comment (srebhan) [reply plugins/outputs/elasticsearch/elasticsearch.go:227]: @archoversight understood. Thanks for clarifying this!

File: plugins/outputs/elasticsearch/elasticsearch.go [hunk 3]
```diff
@@ -220,9 +221,15 @@ func (a *Elasticsearch) Connect() error {
 		Timeout:   time.Duration(a.Timeout),
 	}
 
+	elasticURL, err := url.Parse(a.URLs[0])
+	if err != nil {
+		return err
```
Comment (srebhan) [inline plugins/outputs/elasticsearch/elasticsearch.go:226]: Can we please add some unique error text here to ease debugging?
```suggestion
		return fmt.Errorf("parsing URL failed: %v", err)
```

**Review by srebhan — APPROVED** [review]
@zpriddy thanks for your quick response. The code looks good, I just put one more minor comment there, but I can also live with this being merged as-is.

**Comment by srebhan** [comment]
@zpriddy please resolve the merge conflict.

**Comment by powersj** [comment]
Hi,

Can you please run `go mod tidy` and push one last time? That should fix tests. Thanks!

**Review by srebhan — APPROVED** [review]
Perfect. Thanks @zpriddy for working on this PR!

**Review by powersj — APPROVED** [review]
