### PR TITLE
fix(agent): Correctly truncate the disk buffer

### LINKED ISSUE #16314: buffer_strategy = "disk" stops working after a while
Recently I turned on `buffer_strategy = "disk"` for an application writing line protocol into telegraf's `inputs.influxdb_v2_listener` and telegraf writing into `outputs.influxdb_v2`.

* Telegraf version: 1.33.0 (and 1.32.x before it)
* amd64 Ubuntu (20.04 and 22.04)

### Background
At the time, I was using 1.32 and the setup was:

```
app.1 ----              ------> InfluxDB Dedicated
          v            /
app.2 --->8186:telegraf ------> local network OSS 2.x
          ^ ^          \
app.3 ----  |           ------> local network OSS 1.x
app.4 ------
```

This was all working fine with `memory`. After changing to `disk` things worked for awhile, but then I started getting client errors of this form:
```
Nov 13 17:18:26 host1 gunicorn[406]: ERROR:app.1: 2024-11-13 17:18:26,082 "Error while writing after 5 retries, giving up"
Nov 13 17:18:26 host1 gunicorn[406]: ERROR:app.1: 2024-11-13 17:18:26,082 "Error while writing: HTTPConnectionPool(host='localhost', port=8186): Read timed out. (read timeout=9.999086358991917)"
Nov 13 17:19:59 host1 gunicorn[434]: ERROR:app.4: 2024-11-13 17:19:59,665 "Error while writing after 5 retries, giving up"
Nov 13 17:19:59 host1 gunicorn[434]: ERROR:app.4: 2024-11-13 17:19:59,665 "Error while writing: HTTPConnectionPool(host='localhost', port=8186): Read timed out. (read timeout=9.997719279956073)"
Nov 13 17:20:56 host1 gunicorn[410]: ERROR:app.3: 2024-11-13 17:20:56,406 "Error while writing after 5 retries, giving up"
Nov 13 17:20:56 host1 gunicorn[410]: ERROR:app.3: 2024-11-13 17:20:56,406 "Error while writing: HTTPConnectionPool(host='localhost', port=8186): Read timed out. (read timeout=9.999581227020826)"
Nov 13 17:21:22 host1 gunicorn[408]: ERROR:app.2: 2024-11-13 17:21:22,407 "Error while writing after 5 retries, giving up"
Nov 13 17:21:22 host1 gunicorn[408]: ERROR:app.2: 2024-11-13 17:21:22,408 "Error while writing: HTTPConnectionPool(host='localhost', port=8186): Read timed out. (read timeout=9.999311759951524)"
```

There are no corresponding telegraf logs. The timeout is curious as it is all just under flush_interval which is set to `flush_interval = "10s"`.... (but see below)

Once I set it back to `memory`, the client errors went away.

As an additional data point, the client was seeing some intermittent network issues which might cause disconnects or slow downs. My goal was to deploy telegraf as a proxy between my clients and InfluxDB with `buffer_strategy = "disk"` as a safeguard so as not to lose points in the event of network errors and the like.

### Reproducer
In an effort to create a simple(r) reproducer, I created a python script to emulate a 'slow server':

<details>

```
#!/usr/bin/env python3

import getopt
from http.server import BaseHTTPRequestHandler, HTTPServer
import random
import sys
import time

class SlowServerHandler(BaseHTTPRequestHandler):
    delay: int = 10
    flaky: int = 0
    def slowdown(self, path: str) -> None:
        if path.startswith("/slow"):
            t = int(path[5:])
            if t == 0:
                return
            if t > 0 and t < 600:  # 1 sec to 10 min
                print("%s: delaying %d sec(s)..." % (path, t))
                time.sleep(t)
                return
            raise ValueError("should be integer >= 0 and <= 600")
        else:
            d = delay
            if self.flaky:
                d = random.randint(0, self.flaky)
            print("%s: delaying %d sec(s)..." % (path, d))
            time.sleep(d)
            return

    def fake_request(self):
        code = 200
        try:
            self.slowdown(self.path)
        except Exception:
            code = 500

        self.send_response(code)
        if code == 200:
            self.send_header("Content-type", "application/json")
        self.end_headers()
        if code == 200:
            try:
                self.wfile.write(b"{}\n")
            except Exception:
                print("%s: broken pipe (client disconnect?)" % self.path)

    def do_GET(self):
        self.fake_request()

    def do_POST(self):
        self.fake_request()

def run(delay: int, port: int, flaky: int):
    # XXX: validate delay and port
    addr = ('', port)
    httpd = HTTPServer(addr, SlowServerHandler)
    if flaky > 0:
        SlowServerHandler.flaky = flaky
    else:
        SlowServerHandler.delay = delay
    httpd.serve_forever()

if __name__ == '__main__':
    global delay
    try:
        opts, rest = getopt.getopt(sys.argv[1:], "hf:d:p:", [])
    except Exception:
        print("Bad args. See -h")
        sys.exit(1)

    port: int = 8000
    delay: int = 10
    flaky: int = 0
    for opt, arg in opts:
        if opt == "-h":
            print("""Usage: slow-server.py ARGS
 -h     this message
 -d N   set response delay in seconds (default=10)
 -p N   listen on port N
 -f N   simulate flaky server (0-N delay on every request)

GET and POST are supported an all paths and simply return an empty JSON
document after N delay seconds (as configured with '-d').

If the URL path starts with /slowN, then delay N seconds.
""")
            sys.exit(0)
        elif opt == "-d":
            delay = int(arg)
        elif opt == "-p":
            port = int(arg)
        elif opt == "-f":
            flaky = int(arg)
    try:
        run(delay, port, flaky)
    except KeyboardInterrupt:
        pass
```

</details>

Eg:
```
$ ./slow-server.py -h
Usage: slow-server.py ARGS
 -h     this message
 -d N   set response delay in seconds (default=10)
 -p N   listen on port N
 -f N   simulate flaky server (0-N delay on every request)

GET and POST are supported an all paths and simply return an empty JSON
document after N delay seconds (as configured with '-d').

If the URL path starts with /slowN, then delay N seconds.
```

I then setup telegraf to listen on port 8086 and write out to the local server and use `curl` in a loop to write out to the server. Specifically:

1. In one terminal, start the server without any added delays (ie, it isn't 'slow' yet): `$ python3 ./slow-server.py -d 0`
2. Create a telegraf configuration to proxy and use disk buffer
    ```
    $ cat ./telegraf.conf
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = "0s"
      hostname = ""
      omit_hostname = false

      # 'memory' or 'disk'
      buffer_strategy = "disk"
      buffer_directory = "/tmp/tg"

    # egress to slow server (must serve /api/v2/write)
    [[outputs.influxdb_v2]]
      urls = ["http://127.0.0.1:8000"]

    # ingress from curl, etc
    [[inputs.influxdb_v2_listener]]
      service_address = "127.0.0.1:8086"
      read_timeout = "10s"
      write_timeout = "10s"
      max_body_size = 0
    ```
3. create the disk buffer directory: `mkdir /tmp/tg`
4. start telegraf with `telegraf --config ./telegraf.config`

    <details>

    ```
    $ ~/code/telegraf --config ./telegraf.conf 
    2024-12-16T21:00:58Z I! Loading config: ./telegraf.conf
    2024-12-16T21:00:58Z W! Using disk buffer strategy for plugin outputs.influxdb_v2, this is an experimental feature
    2024-12-16T21:00:58Z I! WAL file not found for plugin outputs.influxdb_v2 (14c21c01a6d4a9f123336ae9b187b07a76ef66f7fc104dce4060725e0035d58a), this can safely be ignored if you added this plugin instance for the first time
    2024-12-16T21:00:58Z I! Starting Telegraf 1.33.0 brought to you by InfluxData the makers of InfluxDB
    2024-12-16T21:00:58Z I! Available plugins: 236 inputs, 9 aggregators, 33 processors, 26 parsers, 63 outputs, 6 secret-stores
    2024-12-16T21:00:58Z I! Loaded inputs: influxdb_v2_listener
    2024-12-16T21:00:58Z I! Loaded aggregators:
    2024-12-16T21:00:58Z I! Loaded processors:
    2024-12-16T21:00:58Z I! Loaded secretstores:
    2024-12-16T21:00:58Z I! Loaded outputs: influxdb_v2
    2024-12-16T21:00:58Z I! Tags enabled: host=sec
    2024-12-16T21:00:58Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"sec", Flush Interval:10s
    2024-12-16T21:00:58Z I! [inputs.influxdb_v2_listener] Started HTTP listener service on 127.0.0.1:8086
    ...at this point I hit Ctrl-c; notice no errors above from telegraf...
    2024-12-16T21:03:26Z I! [agent] Hang on, flushing any cached metrics before shutdown
    2024-12-16T21:03:27Z I! [agent] Stopping running outputs
    ```
    </details>

6. download a line protocol generator: `go install github.com/influxdata/influxdb-comparisons/cmd/bulk_data_gen@latest`
7. then send line protocol into telegraf in a loop. After a short while, telegraf starts outputting `curl: (52) Empty reply from server` instead of `HTTP/1.1 204 No Content`. Eg:
    ```
    $ while /bin/true ; do echo "# $(date)" ; ~/go/bin/bulk_data_gen | head -9999 > /tmp/lp && curl -i -X POST http://127.0.0.1:8086/api/v2/write --data-binary @/tmp/lp && sleep 10 ; done
    # Mon Dec 16 15:01:22 CST 2024
    using random seed 232901789
    2024/12/16 15:01:22 Using sampling interval 10s
    2024/12/16 15:01:22 Using cardinality of 9
    HTTP/1.1 100 Continue
    
    HTTP/1.1 204 No Content
    Date: Mon, 16 Dec 2024 21:01:30 GMT
    
    # Mon Dec 16 15:01:40 CST 2024
    using random seed 644661411
    2024/12/16 15:01:40 Using sampling interval 10s
    2024/12/16 15:01:40 Using cardinality of 9
    HTTP/1.1 100 Continue
    
    HTTP/1.1 204 No Content
    Date: Mon, 16 Dec 2024 21:01:49 GMT
    
    # Mon Dec 16 15:01:59 CST 2024
    using random seed 179797224
    2024/12/16 15:01:59 Using sampling interval 10s
    2024/12/16 15:01:59 Using cardinality of 9
    HTTP/1.1 100 Continue
    
    HTTP/1.1 204 No Content
    Date: Mon, 16 Dec 2024 21:02:08 GMT
    
    # Mon Dec 16 15:02:18 CST 2024
    using random seed 729922716
    2024/12/16 15:02:18 Using sampling interval 10s
    2024/12/16 15:02:18 Using cardinality of 9
    HTTP/1.1 100 Continue

    curl: (52) Empty reply from server
    # Mon Dec 16 15:02:29 CST 2024
    using random seed 79912443
    2024/12/16 15:02:29 Using sampling interval 10s
    2024/12/16 15:02:29 Using cardinality of 9
    HTTP/1.1 100 Continue
    
    curl: (52) Empty reply from server
    # Mon Dec 16 15:02:40 CST 2024
    using random seed 602442651
    2024/12/16 15:02:40 Using sampling interval 10s
    2024/12/16 15:02:40 Using cardinality of 9
    HTTP/1.1 100 Continue

    curl: (52) Empty reply from server
    ```

With this setup, I can see files getting populated in `/tmp/tg`. The client `curl` starts out outputting `HTTP/1.1 204 No Content` but after about a minute, I start seeing `curl: (52) Empty reply from server`. I believe this is successfully demonstrating the problem. Interestingly, the python server is showing telegraf writing throughout (it sends 1000 points at a time (due to `metric_batch_size = 1000`); see the terminal output where the server is running).

<details>

```
$ ./slow-server.py -d 0
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:23] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:24] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:24] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:25] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:26] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:27] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:28] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:28] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:29] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:29] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:38] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:41] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:42] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:43] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:44] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:45] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:45] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:46] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:47] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:48] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:49] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:01:58] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:00] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:01] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:02] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:03] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:04] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:04] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:05] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:06] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:07] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:08] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:18] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:19] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:20] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:21] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:22] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:23] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:24] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:25] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:26] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:28] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:28] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:29] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:30] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:31] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:33] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:34] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:35] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:36] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:37] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:38] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:38] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:40] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:41] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:42] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:43] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:45] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:46] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:47] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:48] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:49] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:50] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:51] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:53] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:54] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:55] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:57] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:58] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:02:59] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:03:00] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:03:02] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:03:03] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:03:05] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:03:06] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:03:07] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:03:09] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:03:10] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:03:12] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:03:13] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:03:15] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:03:17] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:03:18] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:03:19] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:03:21] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:03:23] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:03:24] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:03:26] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
/api/v2/write?bucket=&org=: delaying 0 sec(s)...
127.0.0.1 - - [16/Dec/2024 15:03:27] "POST /api/v2/write?bucket=&org= HTTP/1.1" 200 -
```

</details>

NOTE 1: once telegraf starts sending back empty responses, it does not recover even if I pause the client (ie, whenever the client resumes, telegraf will only send back empty responses). This is true whether telegraf is restarted or not. Only if I empty the `buffer_directory` will telegraf start sending back 204s (but it eventually only sends empty responses again)

NOTE 2: in the above I slept 10 seconds after the curl. If I use other values (eg, 11 seconds, 20 seconds, 30 seconds all after starting with an empty `buffer_directory`), I see the same thing. With a 10 second sleep, it took ~1 minute before seeing the empty responses. With 20 second sleep it took ~2 minutes before seeing empty responses. Since I'm sending 9999 at a time with curl (and telegraf is breaking that up into 1000 chunks), the number of metrics might be a factor (eg, ~60,000 metrics before it starts to show the problem).

NOTE 3: with the above, I haven't introduced 'slowness' with either `-f` or `-d`, but I see similar issues when doing so (but might see `did not complete within its flush interval` from telegraf depending on how slow I make the server). I provided the full script in case it is useful for other debugging and developing a fix for this issue.

### LINKED ISSUE #16500: Disk based buffer causes metric collection/publishing issues
### Relevant telegraf.conf

```toml
# Telegraf Configuration
#
# Telegraf is entirely plugin driven. All metrics are gathered from the
# declared inputs, and sent to the declared outputs.
#
# Plugins must be declared in here to be active.
# To deactivate a plugin, comment out the name and any variables.
#
# Use 'telegraf -config telegraf.conf -test' to see what metrics a config
# file would generate.
#
# Environment variables can be used anywhere in this config file, simply surround
# them with ${}. For strings the variable must be within quotes (ie, "${STR_VAR}"),
# for numbers and booleans they should be plain (ie, ${INT_VAR}, ${BOOL_VAR})


# Global tags can be specified here in key="value" format.
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  # user = "$USER"
  tenant = "redacted"
  region = "redactd"
  network = "redacted"


# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 25000

  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 20000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "3s"

  ## Collection offset is used to shift the collection by the given amount.
  ## This can be be used to avoid many plugins querying constraint devices
  ## at the same time by manually scheduling them in time.
  # collection_offset = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"

  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "5s"

  ## Collected metrics are rounded to the precision specified. Precision is
  ## specified as an interval with an integer + unit (e.g. 0s, 10ms, 2us, 4s).
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  ##
  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s:
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ##
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  precision = "0s"

  ## Log at debug level.
  debug = true
  ## Log only error level messages.
  quiet = false

  ## Log format controls the way messages are logged and can be one of "text",
  ## "structured" or, on Windows, "eventlog".
  # logformat = "text"

  ## Message key for structured logs, to override the default of "msg".
  ## Ignored if `logformat` is not "structured".
  # structured_log_message_key = "message"

  ## Name of the file to be logged to or stderr if unset or empty. This
  ## setting is ignored for the "eventlog" format.
  logfile = "/var/log/telegraf/telegraf.log"

  ## The logfile will be rotated after the time interval specified.  When set
  ## to 0 no time based rotation is performed.  Logs are rotated only when
  ## written to, if there is no log activity rotation may be delayed.
  logfile_rotation_interval = "0d"

  ## The logfile will be rotated when it becomes larger than the specified
  ## size.  When set to 0 no size based rotation is performed.
  logfile_rotation_max_size = "10MB"

  ## Maximum number of rotated archives to keep, any older logs are deleted.
  ## If set to -1, no archives are removed.
  logfile_rotation_max_archives = 5

  ## Pick a timezone to use when logging or type 'local' for local time.
  ## Example: America/Chicago
  # log_with_timezone = ""

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false

  ## Method of translating SNMP objects. Can be "netsnmp" (deprecated) which
  ## translates by calling external programs snmptranslate and snmptable,
  ## or "gosmi" which translates using the built-in gosmi library.
  snmp_translator = "gosmi"

  ## Name of the file to load the state of plugins from and store the state to.
  ## If uncommented and not empty, this file will be used to save the state of
  ## stateful plugins on termination of Telegraf. If the file exists on start,
  ## the state in the file will be restored for the plugins.
  # statefile = ""

  ## Flag to skip running processors after aggregators
  ## By default, processors are run a second time after aggregators. Changing
  ## this setting to true will skip the second run of processors.
  skip_processors_after_aggregators = true

  buffer_strategy = "disk"
  buffer_directory = "/var/lib/telegraf"
# Collect statistics about itself
[[inputs.internal]]
  ## If true, collect telegraf memory stats.
  collect_memstats = true

  ## If true, collect metrics from Go's runtime.metrics. For a full list see:
  ##   https://pkg.go.dev/runtime/metrics
  # collect_gostats = false

  tags = {influx_bucket_set = "general", influx_bucket = "tig_internal"}

# Read metrics about cpu usage
[[inputs.cpu]]
  ## Whether to report per-cpu stats or not
  percpu = true
  ## Whether to report total system cpu stats or not
  totalcpu = true
  ## If true, collect raw CPU time metrics
  collect_cpu_time = false
  ## If true, compute and report the sum of all non-idle CPU states
  ## NOTE: The resulting 'time_active' field INCLUDES 'iowait'!
  report_active = false
  ## If true and the info is available then add core_id and physical_id tags
  core_tags = false

  tags = {influx_bucket_set = "localhost", influx_bucket = "localhost"}




# Read metrics about disk usage by mount point
[[inputs.disk]]
  ## By default stats will be gathered for all mount points.
  ## Set mount_points will restrict the stats to only the specified mount points.
  # mount_points = ["/"]

  ## Ignore mount points by filesystem type.
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs", "efivarfs"]

  ## Ignore mount points by mount options.
  ## The 'mount' command reports options of all mounts in parathesis.
  ## Bind mounts can be ignored with the special 'bind' option.
  ignore_mount_opts = ['bind']
  tags = {influx_bucket_set = "localhost", influx_bucket = "localhost"}


# Read metrics about disk IO by device
[[inputs.diskio]]
  ## Devices to collect stats for
  ## Wildcards are supported except for disk synonyms like '/dev/disk/by-id'.
  ## ex. devices = ["sda", "sdb", "vd*", "/dev/disk/by-id/nvme-eui.00123deadc0de123"]
  # devices = ["*"]

  ## Skip gathering of the disk's serial numbers.
  skip_serial_number = false

  ## Device metadata tags to add on systems supporting it (Linux only)
  ## Use 'udevadm info -q property -n <device>' to get a list of properties.
  ## Note: Most, but not all, udev properties can be accessed this way. Properties
  ## that are currently inaccessible include DEVTYPE, DEVNAME, and DEVPATH.
  # device_tags = ["ID_FS_TYPE", "ID_FS_USAGE"]

  ## Using the same metadata source as device_tags, you can also customize the
  ## name of the device via templates.
  ## The 'name_templates' parameter is a list of templates to try and apply to
  ## the device. The template may contain variables in the form of '$PROPERTY' or
  ## '${PROPERTY}'. The first template which does not contain any variables not
  ## present for the device is used as the device name tag.
  ## The typical use case is for LVM volumes, to get the VG/LV name instead of
  ## the near-meaningless DM-0 name.
  # name_templates = ["$ID_FS_LABEL","$DM_VG_NAME/$DM_LV_NAME"]
  tags = {influx_bucket_set = "localhost", influx_bucket = "localhost"}


# Get kernel statistics from /proc/stat
[[inputs.kernel]]
  ## Additional gather options
  ## Possible options include:
  ## * ksm - kernel same-page merging
  ## * psi - pressure stall information
  # collect = []
  tags = {influx_bucket_set = "localhost", influx_bucket = "localhost"}


# Read metrics about memory usage
[[inputs.mem]]
  # no configuration
  tags = {influx_bucket_set = "localhost", influx_bucket = "localhost"}


# Get the number of processes and group them by status
[[inputs.processes]]
  ## Use sudo to run ps command on *BSD systems. Linux systems will read
  ## /proc, so this does not apply there.
  # use_sudo = false
  tags = {influx_bucket_set = "localhost", influx_bucket = "localhost"}


# Read metrics about swap memory usage
[[inputs.swap]]
  # no configuration
  tags = {influx_bucket_set = "localhost", influx_bucket = "localhost"}


# Read metrics about system load & uptime
[[inputs.system]]
  # no configuration
  tags = {influx_bucket_set = "localhost", influx_bucket = "localhost"}


# Read metrics about network interface usage
[[inputs.net]]
  ## By default, telegraf gathers stats from any up interface (excluding loopback)
  ## Setting interfaces will tell it to gather these explicit interfaces,
  ## regardless of status. When specifying an interface, glob-style
  ## patterns are also supported.
  # interfaces = ["eth*", "enp0s[0-1]", "lo"]

  ## On linux systems telegraf also collects protocol stats.
  ## Setting ignore_protocol_stats to true will skip reporting of protocol metrics.
  ##
  ## DEPRECATION NOTICE: A value of 'false' is deprecated and discouraged!
  ##                     Please set this to `true` and use the 'inputs.nstat'
  ##                     plugin instead.
  ignore_protocol_stats = true
  tags = {influx_bucket_set = "localhost", influx_bucket = "localhost"}


# Read TCP metrics such as established, time wait and sockets counts.
[[inputs.netstat]]
  # no configuration
  tags = {influx_bucket_set = "localhost", influx_bucket = "localhost"}


# Collect kernel snmp counters and network interface statistics
[[inputs.nstat]]
  ## file paths for proc files. If empty default paths will be used:
  ##    /proc/net/netstat, /proc/net/snmp, /proc/net/snmp6
  ## These can also be overridden with env variables, see README.
  proc_net_netstat = "/proc/net/netstat"
  proc_net_snmp = "/proc/net/snmp"
  proc_net_snmp6 = "/proc/net/snmp6"
  ## dump metrics with 0 values too
  dump_zeros       = true
  tags = {influx_bucket_set = "localhost", influx_bucket = "localhost"}


# Get standard chrony metrics, requires chronyc executable.
[[inputs.chrony]]
  ## Server address of chronyd with address scheme
  ## If empty or not set, the plugin will mimic the behavior of chronyc and
  ## check "unixgram:///run/chrony/chronyd.sock", "udp://127.0.0.1:323"
  ## and "udp://[::1]:323".
  # server = ""

  ## Timeout for establishing the connection
  # timeout = "5s"

  ## Try to resolve received addresses to host-names via DNS lookups
  ## Disabled by default to avoid DNS queries especially for slow DNS servers.
  # dns_lookup = false

  ## Metrics to query named according to chronyc commands
  ## Available settings are:
  ##   activity    -- number of peers online or offline
  ##   tracking    -- information about system's clock performance
  ##   serverstats -- chronyd server statistics
  ##   sources     -- extended information about peers
  ##   sourcestats -- statistics on peers
  # metrics = ["tracking"]

  ## Socket group & permissions
  ## If the user requests collecting metrics via unix socket, then it is created
  ## with the following group and permissions.
  # socket_group = "chrony"
  # socket_perms = "0660"
  tags = {influx_bucket_set = "localhost", influx_bucket = "localhost"}

[[inputs.x509_cert]]
  sources = ["file:////etc/puppetlabs/puppet/ssl/certs/alma95-0003.redacted.pem"]

# This file applies influx_bucket_set and influx_bucket tags on metrics as they flow through Telegraf. It is
# defaulted on all Telegraf instances, so it applies these tags to metrics everywhere it possibly can.
#
# Most metrics should be pre-tagged coming to Telegraf. Some metrics may go through Telegraf twice: once
# at the first point (e.g. to get into Kafka) and a second time going from Kafka to InfluxDB. Because of
# these two changes for metrics to be pre-tagged, we are using tagdrop to skip those already tagged. This
# means this processor does not replace existing tags, even if what it would add is different. It leaves
# the original tag in place.
#
# The order set here is important; otherwise the generic catch alls apply first, then none of the rest of
# the specific tags work because the generic tagging was already applied.


[[processors.override]]
  order = 1
  tagdrop = { "influx_bucket" = ["*"], "influx_bucket_set" = ["*"] }
  namepass = [
    "SessionInterference_packet_rx_*",
    "SessionInterference_context_engine_matches_cnt",
    "SessionInterference_context_engine_scan_cnt",
    "SessionInterference_context_engine_scanned_bytes",
    "SessionInterference_dp_client_data_bytes_*",
    "SessionInterference_dp_connection_data_in_out",
    "SessionInterference_dp_connection_other_new_removed",
    "SessionInterference_dp_connection_tcp_new_removed",
    "SessionInterference_dp_server_data_bytes_*",
    "SessionInterference_dp_session_cnt",
    "SessionInterference_file_id_results_cnt",
    "SessionInterference_first_byte_rx_*",
    "SessionInterference_formula_matches_cnt",
    "SessionInterference_formula_actions",
    "SessionInterference_frames_*",
    "SessionInterference_http_content_encoding",
    "SessionInterference_http_transfer_encoding",
    "SessionInterference_last_byte_rx_*",
    "SessionInterference_packet_rx_bytes_from_tu",
    "SessionInterference_parsing_*",
    "SessionInterference_proxy_init_cnt",
    "SessionInterference_proxy_scan_cnt",
    "SessionInterference_scanning_total",
    "pfm_http_bytes_*",
    "pfm_http_context_engine_matches_cnt",
    "pfm_http_context_engine_scan_cnt",
    "pfm_http_context_engine_scanned_bytes",
    "pfm_http_file_id_results_cnt",
    "pfm_http_formula_matches_cnt",
    "pfm_http_formula_actions",
    "pfm_http_parsing_*",
    "pfm_http_requests_fully_procssed",
    "pfm_http_requests_received",
    "pfm_http_scanning_total",
  ]
  tags = {influx_bucket_set = "pfm_stack", influx_bucket = "pfm_customer_durable"}

[[processors.override]]
  order = 2
  tagdrop = { "influx_bucket" = ["*"], "influx_bucket_set" = ["*"] }
  namepass = [
    "SessionInterference_*",
    "pfm_http_*",
    "formula_load_*",
  ]
  tags = {influx_bucket_set = "pfm_stack", influx_bucket = "pfm_ephemeral"}

[[processors.override]]
  order = 3
  tagdrop = { "influx_bucket" = ["*"], "influx_bucket_set" = ["*"] }
  namepass = [
    "plb_bytes_*",
    "plb_frames_*"
  ]
  tags = {influx_bucket_set = "pfm_stack", influx_bucket = "plb_customer_durable"}
  
[[processors.override]]
  order = 4
  tagdrop = { "influx_bucket" = ["*"], "influx_bucket_set" = ["*"] }
  namepass = [
    "plb_*",
  ]
  tags = {influx_bucket_set = "pfm_stack", influx_bucket = "plb_ephemeral"}


[[processors.override]]
  order = 5
  tagdrop = { "influx_bucket" = ["*"], "influx_bucket_set" = ["*"] }
  namepass = [
    "formula_distrib_*",
  ]
  tags = {influx_bucket_set = "pfm_stack", influx_bucket = "formula_distrib_ephemeral"}

[[processors.override]]
  order = 6
  tagdrop = { "influx_bucket" = ["*"], "influx_bucket_set" = ["*"] }
  namepass = [
    "cert_expire_date",
    "x509_cert"
  ]
  tags = {influx_bucket_set = "general", influx_bucket = "cert_expiration"}

[[processors.override]]
  order = 7
  tagdrop = { "influx_bucket" = ["*"], "influx_bucket_set" = ["*"] }
  namepass = [
    "chrony",
    "cpu",
    "disk",
    "diskio",
    "kernel",
    "mem",
    "net",
    "netstat",
    "nstat",
    "processes",
    "swap",
    "system",
    "win_*"
  ]
  tags = {influx_bucket_set = "localhost", influx_bucket = "localhost"}

[[processors.override]]
  order = 8
  tagdrop = { "influx_bucket" = ["*"], "influx_bucket_set" = ["*"] }
  namepass = [
    "ping",
  ]
  tags = {influx_bucket_set = "general", influx_bucket = "ping"}

[[processors.override]]
  order = 9
  tagdrop = { "influx_bucket" = ["*"], "influx_bucket_set" = ["*"] }
  namepass = [
    "portal_*",
    "customer_portal_*",
    "postgresql"
  ]
  tags = {influx_bucket_set = "general", influx_bucket = "customer_portal"}

[[processors.override]]
  order = 10
  tagdrop = { "influx_bucket" = ["*"], "influx_bucket_set" = ["*"] }
  namepass = [
    "internal_portal_*",
  ]
  tags = {influx_bucket_set = "general", influx_bucket = "internal_portal"}

[[processors.override]]
  order = 11
  tagdrop = { "influx_bucket" = ["*"], "influx_bucket_set" = ["*"] }
  namepass = [
    "f5telemetry",
    "f5telemetry_*",
  ]
  tags = {influx_bucket_set = "pfm_stack", influx_bucket = "f5_ephemeral"}

[[processors.override]]
  order = 12
  tagdrop = { "influx_bucket" = ["*"], "influx_bucket_set" = ["*"] }
  tags = {influx_bucket_set = "general", influx_bucket = "default"}
# Configuration for the Kafka server to send metrics to
[[outputs.kafka]]
  alias = "redacted_test-metrics"
  ## URLs of kafka brokers
  ## The brokers listed here are used to connect to collect metadata about a
  ## cluster. However, once the initial metadata collect is completed, telegraf
  ## will communicate solely with the kafka leader and not all defined brokers.
  brokers = ["kafka-metrics-0001.redacted:9092","kafka-metrics-0002.redacted:9092","kafka-metrics-0003.redacted:9092"]

  ## Kafka topic for producer messages
  topic = "test-metrics"

  ## The value of this tag will be used as the topic.  If not set the 'topic'
  ## option is used.
  # topic_tag = ""

  ## If true, the 'topic_tag' will be removed from to the metric.
  # exclude_topic_tag = false

  ## Optional Client id
  # client_id = "Telegraf"

  ## Set the minimal supported Kafka version.  Setting this enables the use of new
  ## Kafka features and APIs.  Of particular interested, lz4 compression
  ## requires at least version 0.10.0.0.
  ##   ex: version = "1.1.0"
  # version = ""

  ## The routing tag specifies a tagkey on the metric whose value is used as
  ## the message key.  The message key is used to determine which partition to
  ## send the message to.  This tag is preferred over the routing_key option.
  # routing_tag = "host"

  ## The routing key is set as the message key and used to determine which
  ## partition to send the message to.  This value is only used when no
  ## routing_tag is set or as a fallback when the tag specified in routing tag
  ## is not found.
  ##
  ## If set to "random", a random value will be generated for each message.
  ##
  ## When unset, no message key is added and each message is routed to a random
  ## partition.
  ##
  ##   ex: routing_key = "random"
  ##       routing_key = "telegraf"
  # routing_key = ""

  ## Compression codec represents the various compression codecs recognized by
  ## Kafka in messages.
  ##  0 : None
  ##  1 : Gzip
  ##  2 : Snappy
  ##  3 : LZ4
  ##  4 : ZSTD
  compression_codec = 0

  ## Idempotent Writes
  ## If enabled, exactly one copy of each message is written.
  # idempotent_writes = false

  ##  RequiredAcks is used in Produce Requests to tell the broker how many
  ##  replica acknowledgements it must see before responding
  ##   0 : the producer never waits for an acknowledgement from the broker.
  ##       This option provides the lowest latency but the weakest durability
  ##       guarantees (some data will be lost when a server fails).
  ##   1 : the producer gets an acknowledgement after the leader replica has
  ##       received the data. This option provides better durability as the
  ##       client waits until the server acknowledges the request as successful
  ##       (only messages that were written to the now-dead leader but not yet
  ##       replicated will be lost).
  ##   -1: the producer gets an acknowledgement after all in-sync replicas have
  ##       received the data. This option provides the best durability, we
  ##       guarantee that no messages will be lost as long as at least one in
  ##       sync replica remains.
  required_acks = 1

  ## The maximum number of times to retry sending a metric before failing
  ## until the next flush.
  max_retry = 3

  ## The maximum permitted size of a message. Should be set equal to or
  ## smaller than the broker's 'message.max.bytes'.
  # max_message_bytes = 1000000

  ## Producer timestamp
  ## This option sets the timestamp of the kafka producer message, choose from:
  ##   * metric: Uses the metric's timestamp
  ##   * now: Uses the time of write
  # producer_timestamp = metric

  ## Add metric name as specified kafka header if not empty
  # metric_name_header = ""

  ## Optional TLS Config
 
  tls_ca = "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

  ## Period between keep alive probes.
  ## Defaults to the OS configuration if not specified or zero.
  # keep_alive_period = "15s"

  ## Optional SOCKS5 proxy to use when connecting to brokers
  # socks5_enabled = true
  # socks5_address = "127.0.0.1:1080"
  # socks5_username = "alice"
  # socks5_password = "pass123"

  ## Optional SASL Config
  # sasl_username = "kafka"
  # sasl_password = "secret"

  ## Optional SASL:
  ## one of: OAUTHBEARER, PLAIN, SCRAM-SHA-256, SCRAM-SHA-512, GSSAPI
  ## (defaults to PLAIN)
  # sasl_mechanism = ""

  ## used if sasl_mechanism is GSSAPI
  # sasl_gssapi_service_name = ""
  # ## One of: KRB5_USER_AUTH and KRB5_KEYTAB_AUTH
  # sasl_gssapi_auth_type = "KRB5_USER_AUTH"
  # sasl_gssapi_kerberos_config_path = "/"
  # sasl_gssapi_realm = "realm"
  # sasl_gssapi_key_tab_path = ""
  # sasl_gssapi_disable_pafxfast = false

  ## Access token used if sasl_mechanism is OAUTHBEARER
  # sasl_access_token = ""

  ## Arbitrary key value string pairs to pass as a TOML table. For example:
  # {logicalCluster = "cluster-042", poolId = "pool-027"}
  # sasl_extensions = {}

  ## SASL protocol version.  When connecting to Azure EventHub set to 0.
  # sasl_version = 1

  # Disable Kafka metadata full fetch
  # metadata_full = false

  ## Maximum number of retries for metadata operations including
  ## connecting. Sets Sarama library's Metadata.Retry.Max config value. If 0 or
  ## unset, use the Sarama default of 3,
  # metadata_retry_max = 0

  ## Type of retry backoff. Valid options: "constant", "exponential"
  # metadata_retry_type = "constant"

  ## Amount of time to wait before retrying. When metadata_retry_type is
  ## "constant", each retry is delayed this amount. When "exponential", the
  ## first retry is delayed this amount, and subsequent delays are doubled. If 0
  ## or unset, use the Sarama default of 250 ms
  # metadata_retry_backoff = 0

  ## Maximum amount of time to wait before retrying when metadata_retry_type is
  ## "exponential". Ignored for other retry types. If 0, there is no backoff
  ## limit.
  # metadata_retry_max_duration = 0

  ## Data format to output.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
  data_format = "influx"

  # These are in order of how they are processed
  namepass = []
  namedrop = []
  tagpass = {"tenant"=["dev","test"]}
  tagdrop = {"tc_no_kafka_republish"=["true"]}
  metricpass = ''
  taginclude = []
  tagexclude = []

  ## NOTE: Due to the way TOML is parsed, tables must be at the END of the
  ## plugin definition, otherwise additional config options are read as part of
  ## the table

  ## Optional topic suffix configuration.
  ## If the section is omitted, no suffix is used.
  ## Following topic suffix methods are supported:
  ##   measurement - suffix equals to separator + measurement's name
  ##   tags        - suffix equals to separator + specified tags' values
  ##                 interleaved with separator

  ## Suffix equals to "_" + measurement name
  # [outputs.kafka.topic_suffix]
  #   method = "measurement"
  #   separator = "_"

  ## Suffix equals to "__" + measurement's "foo" tag value.
  ## If there's no such a tag, suffix equals to an empty string
  # [outputs.kafka.topic_suffix]
  #   method = "tags"
  #   keys = ["foo"]
  #   separator = "__"

  ## Suffix equals to "_" + measurement's "foo" and "bar"
  ## tag values, separated by "_". If there is no such tags,
  ## their values treated as empty strings.
  # [outputs.kafka.topic_suffix]
  #   method = "tags"
  #   keys = ["foo", "bar"]
  #   separator = "_"
[[outputs.kafka]]
  alias = "redacted_test-metrics"
  ## URLs of kafka brokers
  ## The brokers listed here are used to connect to collect metadata about a
  ## cluster. However, once the initial metadata collect is completed, telegraf
  ## will communicate solely with the kafka leader and not all defined brokers.
  brokers = ["kafka-metrics-0001.redacted:9092","kafka-metrics-0002.redacted:9092","kafka-metrics-0003.redacted:9092"]

  ## Kafka topic for producer messages
  topic = "test-metrics"

  ## The value of this tag will be used as the topic.  If not set the 'topic'
  ## option is used.
  # topic_tag = ""

  ## If true, the 'topic_tag' will be removed from to the metric.
  # exclude_topic_tag = false

  ## Optional Client id
  # client_id = "Telegraf"

  ## Set the minimal supported Kafka version.  Setting this enables the use of new
  ## Kafka features and APIs.  Of particular interested, lz4 compression
  ## requires at least version 0.10.0.0.
  ##   ex: version = "1.1.0"
  # version = ""

  ## The routing tag specifies a tagkey on the metric whose value is used as
  ## the message key.  The message key is used to determine which partition to
  ## send the message to.  This tag is preferred over the routing_key option.
  # routing_tag = "host"

  ## The routing key is set as the message key and used to determine which
  ## partition to send the message to.  This value is only used when no
  ## routing_tag is set or as a fallback when the tag specified in routing tag
  ## is not found.
  ##
  ## If set to "random", a random value will be generated for each message.
  ##
  ## When unset, no message key is added and each message is routed to a random
  ## partition.
  ##
  ##   ex: routing_key = "random"
  ##       routing_key = "telegraf"
  # routing_key = ""

  ## Compression codec represents the various compression codecs recognized by
  ## Kafka in messages.
  ##  0 : None
  ##  1 : Gzip
  ##  2 : Snappy
  ##  3 : LZ4
  ##  4 : ZSTD
  compression_codec = 0

  ## Idempotent Writes
  ## If enabled, exactly one copy of each message is written.
  # idempotent_writes = false

  ##  RequiredAcks is used in Produce Requests to tell the broker how many
  ##  replica acknowledgements it must see before responding
  ##   0 : the producer never waits for an acknowledgement from the broker.
  ##       This option provides the lowest latency but the weakest durability
  ##       guarantees (some data will be lost when a server fails).
  ##   1 : the producer gets an acknowledgement after the leader replica has
  ##       received the data. This option provides better durability as the
  ##       client waits until the server acknowledges the request as successful
  ##       (only messages that were written to the now-dead leader but not yet
  ##       replicated will be lost).
  ##   -1: the producer gets an acknowledgement after all in-sync replicas have
  ##       received the data. This option provides the best durability, we
  ##       guarantee that no messages will be lost as long as at least one in
  ##       sync replica remains.
  required_acks = 1

  ## The maximum number of times to retry sending a metric before failing
  ## until the next flush.
  max_retry = 3

  ## The maximum permitted size of a message. Should be set equal to or
  ## smaller than the broker's 'message.max.bytes'.
  # max_message_bytes = 1000000

  ## Producer timestamp
  ## This option sets the timestamp of the kafka producer message, choose from:
  ##   * metric: Uses the metric's timestamp
  ##   * now: Uses the time of write
  # producer_timestamp = metric

  ## Add metric name as specified kafka header if not empty
  # metric_name_header = ""

  ## Optional TLS Config
 
  tls_ca = "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

  ## Period between keep alive probes.
  ## Defaults to the OS configuration if not specified or zero.
  # keep_alive_period = "15s"

  ## Optional SOCKS5 proxy to use when connecting to brokers
  # socks5_enabled = true
  # socks5_address = "127.0.0.1:1080"
  # socks5_username = "alice"
  # socks5_password = "pass123"

  ## Optional SASL Config
  # sasl_username = "kafka"
  # sasl_password = "secret"

  ## Optional SASL:
  ## one of: OAUTHBEARER, PLAIN, SCRAM-SHA-256, SCRAM-SHA-512, GSSAPI
  ## (defaults to PLAIN)
  # sasl_mechanism = ""

  ## used if sasl_mechanism is GSSAPI
  # sasl_gssapi_service_name = ""
  # ## One of: KRB5_USER_AUTH and KRB5_KEYTAB_AUTH
  # sasl_gssapi_auth_type = "KRB5_USER_AUTH"
  # sasl_gssapi_kerberos_config_path = "/"
  # sasl_gssapi_realm = "realm"
  # sasl_gssapi_key_tab_path = ""
  # sasl_gssapi_disable_pafxfast = false

  ## Access token used if sasl_mechanism is OAUTHBEARER
  # sasl_access_token = ""

  ## Arbitrary key value string pairs to pass as a TOML table. For example:
  # {logicalCluster = "cluster-042", poolId = "pool-027"}
  # sasl_extensions = {}

  ## SASL protocol version.  When connecting to Azure EventHub set to 0.
  # sasl_version = 1

  # Disable Kafka metadata full fetch
  # metadata_full = false

  ## Maximum number of retries for metadata operations including
  ## connecting. Sets Sarama library's Metadata.Retry.Max config value. If 0 or
  ## unset, use the Sarama default of 3,
  # metadata_retry_max = 0

  ## Type of retry backoff. Valid options: "constant", "exponential"
  # metadata_retry_type = "constant"

  ## Amount of time to wait before retrying. When metadata_retry_type is
  ## "constant", each retry is delayed this amount. When "exponential", the
  ## first retry is delayed this amount, and subsequent delays are doubled. If 0
  ## or unset, use the Sarama default of 250 ms
  # metadata_retry_backoff = 0

  ## Maximum amount of time to wait before retrying when metadata_retry_type is
  ## "exponential". Ignored for other retry types. If 0, there is no backoff
  ## limit.
  # metadata_retry_max_duration = 0

  ## Data format to output.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
  data_format = "influx"

  # These are in order of how they are processed
  namepass = []
  namedrop = []
  tagpass = {"tenant"=["dev","test"]}
  tagdrop = {"tc_no_kafka_republish"=["true"]}
  metricpass = ''
  taginclude = []
  tagexclude = []

  ## NOTE: Due to the way TOML is parsed, tables must be at the END of the
  ## plugin definition, otherwise additional config options are read as part of
  ## the table

  ## Optional topic suffix configuration.
  ## If the section is omitted, no suffix is used.
  ## Following topic suffix methods are supported:
  ##   measurement - suffix equals to separator + measurement's name
  ##   tags        - suffix equals to separator + specified tags' values
  ##                 interleaved with separator

  ## Suffix equals to "_" + measurement name
  # [outputs.kafka.topic_suffix]
  #   method = "measurement"
  #   separator = "_"

  ## Suffix equals to "__" + measurement's "foo" tag value.
  ## If there's no such a tag, suffix equals to an empty string
  # [outputs.kafka.topic_suffix]
  #   method = "tags"
  #   keys = ["foo"]
  #   separator = "__"

  ## Suffix equals to "_" + measurement's "foo" and "bar"
  ## tag values, separated by "_". If there is no such tags,
  ## their values treated as empty strings.
  # [outputs.kafka.topic_suffix]
  #   method = "tags"
  #   keys = ["foo", "bar"]
  #   separator = "_"
[[outputs.kafka]]
  alias = "redacted_live-metrics"
  ## URLs of kafka brokers
  ## The brokers listed here are used to connect to collect metadata about a
  ## cluster. However, once the initial metadata collect is completed, telegraf
  ## will communicate solely with the kafka leader and not all defined brokers.
  brokers = ["kafka-metrics-0001.redacted:9092","kafka-metrics-0002.redacted:9092","kafka-metrics-0003.redacted:9092"]

  ## Kafka topic for producer messages
  topic = "live-metrics"

  ## The value of this tag will be used as the topic.  If not set the 'topic'
  ## option is used.
  # topic_tag = ""

  ## If true, the 'topic_tag' will be removed from to the metric.
  # exclude_topic_tag = false

  ## Optional Client id
  # client_id = "Telegraf"

  ## Set the minimal supported Kafka version.  Setting this enables the use of new
  ## Kafka features and APIs.  Of particular interested, lz4 compression
  ## requires at least version 0.10.0.0.
  ##   ex: version = "1.1.0"
  # version = ""

  ## The routing tag specifies a tagkey on the metric whose value is used as
  ## the message key.  The message key is used to determine which partition to
  ## send the message to.  This tag is preferred over the routing_key option.
  # routing_tag = "host"

  ## The routing key is set as the message key and used to determine which
  ## partition to send the message to.  This value is only used when no
  ## routing_tag is set or as a fallback when the tag specified in routing tag
  ## is not found.
  ##
  ## If set to "random", a random value will be generated for each message.
  ##
  ## When unset, no message key is added and each message is routed to a random
  ## partition.
  ##
  ##   ex: routing_key = "random"
  ##       routing_key = "telegraf"
  # routing_key = ""

  ## Compression codec represents the various compression codecs recognized by
  ## Kafka in messages.
  ##  0 : None
  ##  1 : Gzip
  ##  2 : Snappy
  ##  3 : LZ4
  ##  4 : ZSTD
  compression_codec = 0

  ## Idempotent Writes
  ## If enabled, exactly one copy of each message is written.
  # idempotent_writes = false

  ##  RequiredAcks is used in Produce Requests to tell the broker how many
  ##  replica acknowledgements it must see before responding
  ##   0 : the producer never waits for an acknowledgement from the broker.
  ##       This option provides the lowest latency but the weakest durability
  ##       guarantees (some data will be lost when a server fails).
  ##   1 : the producer gets an acknowledgement after the leader replica has
  ##       received the data. This option provides better durability as the
  ##       client waits until the server acknowledges the request as successful
  ##       (only messages that were written to the now-dead leader but not yet
  ##       replicated will be lost).
  ##   -1: the producer gets an acknowledgement after all in-sync replicas have
  ##       received the data. This option provides the best durability, we
  ##       guarantee that no messages will be lost as long as at least one in
  ##       sync replica remains.
  required_acks = 1

  ## The maximum number of times to retry sending a metric before failing
  ## until the next flush.
  max_retry = 3

  ## The maximum permitted size of a message. Should be set equal to or
  ## smaller than the broker's 'message.max.bytes'.
  # max_message_bytes = 1000000

  ## Producer timestamp
  ## This option sets the timestamp of the kafka producer message, choose from:
  ##   * metric: Uses the metric's timestamp
  ##   * now: Uses the time of write
  # producer_timestamp = metric

  ## Add metric name as specified kafka header if not empty
  # metric_name_header = ""

  ## Optional TLS Config
 
  tls_ca = "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

  ## Period between keep alive probes.
  ## Defaults to the OS configuration if not specified or zero.
  # keep_alive_period = "15s"

  ## Optional SOCKS5 proxy to use when connecting to brokers
  # socks5_enabled = true
  # socks5_address = "127.0.0.1:1080"
  # socks5_username = "alice"
  # socks5_password = "pass123"

  ## Optional SASL Config
  # sasl_username = "kafka"
  # sasl_password = "secret"

  ## Optional SASL:
  ## one of: OAUTHBEARER, PLAIN, SCRAM-SHA-256, SCRAM-SHA-512, GSSAPI
  ## (defaults to PLAIN)
  # sasl_mechanism = ""

  ## used if sasl_mechanism is GSSAPI
  # sasl_gssapi_service_name = ""
  # ## One of: KRB5_USER_AUTH and KRB5_KEYTAB_AUTH
  # sasl_gssapi_auth_type = "KRB5_USER_AUTH"
  # sasl_gssapi_kerberos_config_path = "/"
  # sasl_gssapi_realm = "realm"
  # sasl_gssapi_key_tab_path = ""
  # sasl_gssapi_disable_pafxfast = false

  ## Access token used if sasl_mechanism is OAUTHBEARER
  # sasl_access_token = ""

  ## Arbitrary key value string pairs to pass as a TOML table. For example:
  # {logicalCluster = "cluster-042", poolId = "pool-027"}
  # sasl_extensions = {}

  ## SASL protocol version.  When connecting to Azure EventHub set to 0.
  # sasl_version = 1

  # Disable Kafka metadata full fetch
  # metadata_full = false

  ## Maximum number of retries for metadata operations including
  ## connecting. Sets Sarama library's Metadata.Retry.Max config value. If 0 or
  ## unset, use the Sarama default of 3,
  # metadata_retry_max = 0

  ## Type of retry backoff. Valid options: "constant", "exponential"
  # metadata_retry_type = "constant"

  ## Amount of time to wait before retrying. When metadata_retry_type is
  ## "constant", each retry is delayed this amount. When "exponential", the
  ## first retry is delayed this amount, and subsequent delays are doubled. If 0
  ## or unset, use the Sarama default of 250 ms
  # metadata_retry_backoff = 0

  ## Maximum amount of time to wait before retrying when metadata_retry_type is
  ## "exponential". Ignored for other retry types. If 0, there is no backoff
  ## limit.
  # metadata_retry_max_duration = 0

  ## Data format to output.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
  data_format = "influx"

  # These are in order of how they are processed
  namepass = []
  namedrop = []
  tagpass = {}
  tagdrop = {"tc_no_kafka_republish"=["true"]}
  metricpass = '!(tags.tenant == "dev" || tags.tenant == "test") || tags.influx_bucket == "localhost" || tags.influx_bucket == "cert_expiration"'
  taginclude = []
  tagexclude = []

  ## NOTE: Due to the way TOML is parsed, tables must be at the END of the
  ## plugin definition, otherwise additional config options are read as part of
  ## the table

  ## Optional topic suffix configuration.
  ## If the section is omitted, no suffix is used.
  ## Following topic suffix methods are supported:
  ##   measurement - suffix equals to separator + measurement's name
  ##   tags        - suffix equals to separator + specified tags' values
  ##                 interleaved with separator

  ## Suffix equals to "_" + measurement name
  # [outputs.kafka.topic_suffix]
  #   method = "measurement"
  #   separator = "_"

  ## Suffix equals to "__" + measurement's "foo" tag value.
  ## If there's no such a tag, suffix equals to an empty string
  # [outputs.kafka.topic_suffix]
  #   method = "tags"
  #   keys = ["foo"]
  #   separator = "__"

  ## Suffix equals to "_" + measurement's "foo" and "bar"
  ## tag values, separated by "_". If there is no such tags,
  ## their values treated as empty strings.
  # [outputs.kafka.topic_suffix]
  #   method = "tags"
  #   keys = ["foo", "bar"]
  #   separator = "_"
```

### Logs from Telegraf

```text
2025-02-10T17:25:01Z W! [agent] ["outputs.kafka::live.iad_test-metrics"] did not complete within its flush interval
2025-02-10T17:25:01Z W! [inputs.system] Collection took longer than expected; not complete after interval of 10s
2025-02-10T17:25:01Z W! [inputs.swap] Collection took longer than expected; not complete after interval of 10s
2025-02-10T17:25:01Z W! [inputs.netstat] Collection took longer than expected; not complete after interval of 10s
2025-02-10T17:25:01Z W! [inputs.cpu] Collection took longer than expected; not complete after interval of 10s
2025-02-10T17:25:02Z W! [inputs.chrony] Collection took longer than expected; not complete after interval of 10s
2025-02-10T17:25:02Z W! [inputs.internal] Collection took longer than expected; not complete after interval of 10s
2025-02-10T17:25:02Z W! [inputs.mem] Collection took longer than expected; not complete after interval of 10s
2025-02-10T17:25:10Z W! [inputs.x509_cert] Collection took longer than expected; not complete after interval of 10s
2025-02-10T17:25:10Z W! [inputs.diskio] Collection took longer than expected; not complete after interval of 10s
2025-02-10T17:25:10Z W! [inputs.nstat] Collection took longer than expected; not complete after interval of 10s
2025-02-10T17:25:10Z W! [inputs.processes] Collection took longer than expected; not complete after interval of 10s
2025-02-10T17:25:10Z W! [inputs.disk] Collection took longer than expected; not complete after interval of 10s
2025-02-10T17:25:10Z W! [inputs.kernel] Collection took longer than expected; not complete after interval of 10s
2025-02-10T17:25:10Z W! [inputs.net] Collection took longer than expected; not complete after interval of 10s
2025-02-10T17:25:11Z W! [inputs.system] Collection took longer than expected; not complete after interval of 10s
2025-02-10T17:25:11Z W! [inputs.swap] Collection took longer than expected; not complete after interval of 10s
2025-02-10T17:25:11Z W! [inputs.netstat] Collection took longer than expected; not complete after interval of 10s
2025-02-10T17:25:11Z W! [inputs.cpu] Collection took longer than expected; not complete after interval of 10s
2025-02-10T17:25:12Z W! [inputs.chrony] Collection took longer than expected; not complete after interval of 10s
2025-02-10T17:25:12Z W! [inputs.internal] Collection took longer than expected; not complete after interval of 10s
2025-02-10T17:25:12Z W! [inputs.mem] Collection took longer than expected; not complete after interval of 10s

----
restart to enable debug logs
----

2025-02-10T18:36:41Z E! [inputs.chrony] Removing temporary socket "/run/chrony/chrony-telegraf-ab3bf21e-1cc1-4e3b-a0db-5ae5b1d9edf3.sock" failed: remove /run/chrony/chrony-telegraf-ab3bf21e-1cc1-4e3b-a0db-5ae5b1d9edf3.sock: permission denied
2025-02-10T18:36:41Z I! [agent] Hang on, flushing any cached metrics before shutdown
2025-02-10T18:36:41Z I! [agent] Stopping running outputs
2025-02-10T18:36:41Z I! Loading config: /etc/telegraf/telegraf.conf
2025-02-10T18:36:41Z I! Loading config: /etc/telegraf/telegraf.d/base.conf
2025-02-10T18:36:41Z I! Loading config: /etc/telegraf/telegraf.d/input-internal.conf
2025-02-10T18:36:41Z I! Loading config: /etc/telegraf/telegraf.d/input-localhost.conf
2025-02-10T18:36:41Z I! Loading config: /etc/telegraf/telegraf.d/input-puppetcert.conf
2025-02-10T18:36:41Z I! Loading config: /etc/telegraf/telegraf.d/output-kafka.conf
2025-02-10T18:36:41Z W! Using disk buffer strategy for plugin outputs.kafka, this is an experimental feature
2025-02-10T18:36:41Z W! Using disk buffer strategy for plugin outputs.kafka, this is an experimental feature
2025-02-10T18:36:41Z W! Using disk buffer strategy for plugin outputs.kafka, this is an experimental feature
2025-02-10T18:36:41Z I! Loading config: /etc/telegraf/telegraf.d/processor-tag-bucket.conf
2025-02-10T18:36:41Z I! Starting Telegraf 1.33.1 brought to you by InfluxData the makers of InfluxDB
2025-02-10T18:36:41Z I! Available plugins: 236 inputs, 9 aggregators, 33 processors, 26 parsers, 63 outputs, 6 secret-stores
2025-02-10T18:36:41Z I! Loaded inputs: chrony cpu disk diskio internal kernel mem net netstat nstat processes swap system x509_cert
2025-02-10T18:36:41Z I! Loaded aggregators:
2025-02-10T18:36:41Z I! Loaded processors: override (12x)
2025-02-10T18:36:41Z I! Loaded secretstores:
2025-02-10T18:36:41Z I! Loaded outputs: kafka (3x)
2025-02-10T18:36:41Z I! Tags enabled: host=alma95-0003.redacted network=redacted region=redacted tenant=redacted
2025-02-10T18:36:41Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"alma95-0003.redacted", Flush Interval:10s
2025-02-10T18:36:41Z D! [agent] Initializing plugins
2025-02-10T18:36:41Z D! [agent] Connecting outputs
2025-02-10T18:36:41Z D! [agent] Attempting connection to [outputs.kafka::redacted_test-metrics]
2025-02-10T18:36:41Z D! [agent] Successfully connected to outputs.kafka::redacted_test-metrics
2025-02-10T18:36:41Z D! [agent] Attempting connection to [outputs.kafka::redacted_test-metrics]
2025-02-10T18:36:41Z D! [agent] Successfully connected to outputs.kafka::redacted_test-metrics
2025-02-10T18:36:41Z D! [agent] Attempting connection to [outputs.kafka::redacted_live-metrics]
2025-02-10T18:36:41Z D! [agent] Successfully connected to outputs.kafka::redacted_live-metrics
2025-02-10T18:36:41Z D! [agent] Starting service inputs
2025-02-10T18:36:41Z D! [inputs.chrony] Connected to "udp://127.0.0.1:323"...
2025-02-10T18:36:51Z D! [inputs.x509_cert] Invalid certificate 1f9
2025-02-10T18:36:51Z D! [inputs.x509_cert]   cert DNS names:    [alma95-0003.redacted]
2025-02-10T18:36:51Z D! [inputs.x509_cert]   cert IP addresses: []
2025-02-10T18:36:51Z D! [inputs.x509_cert]   cert subject:      CN=alma95-0003.redacted
2025-02-10T18:36:51Z D! [inputs.x509_cert]   cert issuer:       CN=Puppet CA: provisioning-0001.redacted
2025-02-10T18:36:51Z D! [inputs.x509_cert]   opts.DNSName:      
2025-02-10T18:36:51Z D! [inputs.x509_cert]   verify options:    { 0xc0018d6e40 <nil> 0001-01-01 00:00:00 +0000 UTC [0] 0}
2025-02-10T18:36:51Z D! [inputs.x509_cert]   verify error:      x509: certificate signed by unknown authority
2025-02-10T18:36:51Z D! [inputs.x509_cert]   tlsCfg.ServerName: 
2025-02-10T18:36:51Z D! [inputs.x509_cert]   ServerName:        
2025-02-10T18:36:51Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-sysctl.service"): permission denied
2025-02-10T18:36:51Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-sysusers.service"): permission denied
2025-02-10T18:36:51Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-tmpfiles-setup-dev.service"): permission denied
2025-02-10T18:36:51Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-tmpfiles-setup.service"): permission denied
2025-02-10T18:36:54Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 126.143812ms
2025-02-10T18:36:56Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 149.050453ms
2025-02-10T18:36:56Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 198.327251ms
2025-02-10T18:36:56Z D! [outputs.kafka::redacted_live-metrics] Wrote batch of 25000 metrics in 477.581988ms
2025-02-10T18:36:57Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 230.172985ms
2025-02-10T18:36:57Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 131.284946ms
2025-02-10T18:36:58Z D! [outputs.kafka::redacted_live-metrics] Wrote batch of 25000 metrics in 213.511181ms
2025-02-10T18:36:59Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 215.768965ms
2025-02-10T18:37:00Z D! [outputs.kafka::redacted_live-metrics] Wrote batch of 25000 metrics in 283.884916ms
2025-02-10T18:37:00Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 180.424512ms
2025-02-10T18:37:01Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-sysctl.service"): permission denied
2025-02-10T18:37:01Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-sysusers.service"): permission denied
2025-02-10T18:37:01Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-tmpfiles-setup-dev.service"): permission denied
2025-02-10T18:37:01Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-tmpfiles-setup.service"): permission denied
2025-02-10T18:37:01Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 218.750123ms
2025-02-10T18:37:02Z D! [inputs.x509_cert] Invalid certificate 1f9
2025-02-10T18:37:02Z D! [inputs.x509_cert]   cert DNS names:    [alma95-0003.redacted]
2025-02-10T18:37:02Z D! [inputs.x509_cert]   cert IP addresses: []
2025-02-10T18:37:02Z D! [inputs.x509_cert]   cert subject:      CN=alma95-0003.redacted
2025-02-10T18:37:02Z D! [inputs.x509_cert]   cert issuer:       CN=Puppet CA: provisioning-0001.redacted
2025-02-10T18:37:02Z D! [inputs.x509_cert]   opts.DNSName:      
2025-02-10T18:37:02Z D! [inputs.x509_cert]   verify options:    { 0xc00ced9110 <nil> 0001-01-01 00:00:00 +0000 UTC [0] 0}
2025-02-10T18:37:02Z D! [inputs.x509_cert]   verify error:      x509: certificate signed by unknown authority
2025-02-10T18:37:02Z D! [inputs.x509_cert]   tlsCfg.ServerName: 
2025-02-10T18:37:02Z D! [inputs.x509_cert]   ServerName:        
2025-02-10T18:37:02Z D! [outputs.kafka::redacted_live-metrics] Wrote batch of 25000 metrics in 247.615815ms
2025-02-10T18:37:03Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 170.277466ms
2025-02-10T18:37:05Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 290.286934ms
2025-02-10T18:37:05Z W! [agent] ["outputs.kafka::redacted_test-metrics"] did not complete within its flush interval
2025-02-10T18:37:05Z W! [agent] ["outputs.kafka::redacted_test-metrics"] did not complete within its flush interval
2025-02-10T18:37:06Z D! [outputs.kafka::redacted_live-metrics] Wrote batch of 25000 metrics in 311.44424ms
2025-02-10T18:37:07Z W! [agent] ["outputs.kafka::redacted_live-metrics"] did not complete within its flush interval
2025-02-10T18:37:07Z D! [outputs.kafka::redacted_test-metrics] Buffer fullness: 748980 metrics
2025-02-10T18:37:07Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 149.666139ms
2025-02-10T18:37:09Z D! [outputs.kafka::redacted_test-metrics] Buffer fullness: 748979 metrics
2025-02-10T18:37:09Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 194.804707ms
2025-02-10T18:37:10Z D! [inputs.x509_cert] Invalid certificate 1f9
2025-02-10T18:37:10Z D! [inputs.x509_cert]   cert DNS names:    [alma95-0003.redacted]
2025-02-10T18:37:10Z D! [inputs.x509_cert]   cert IP addresses: []
2025-02-10T18:37:10Z D! [inputs.x509_cert]   cert subject:      CN=alma95-0003.redacted
2025-02-10T18:37:10Z D! [inputs.x509_cert]   cert issuer:       CN=Puppet CA: provisioning-0001.redacted
2025-02-10T18:37:10Z D! [inputs.x509_cert]   opts.DNSName:      
2025-02-10T18:37:10Z D! [inputs.x509_cert]   verify options:    { 0xc00e125bf0 <nil> 0001-01-01 00:00:00 +0000 UTC [0] 0}
2025-02-10T18:37:10Z D! [inputs.x509_cert]   verify error:      x509: certificate signed by unknown authority
2025-02-10T18:37:10Z D! [inputs.x509_cert]   tlsCfg.ServerName: 
2025-02-10T18:37:10Z D! [inputs.x509_cert]   ServerName:        
2025-02-10T18:37:10Z D! [outputs.kafka::redacted_live-metrics] Buffer fullness: 287813 metrics
2025-02-10T18:37:10Z D! [outputs.kafka::redacted_live-metrics] Wrote batch of 25000 metrics in 147.262621ms
2025-02-10T18:37:11Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-sysctl.service"): permission denied
2025-02-10T18:37:11Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-sysusers.service"): permission denied
2025-02-10T18:37:11Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-tmpfiles-setup-dev.service"): permission denied
2025-02-10T18:37:11Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-tmpfiles-setup.service"): permission denied
2025-02-10T18:37:13Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 141.633571ms
2025-02-10T18:37:14Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 173.655371ms
2025-02-10T18:37:16Z D! [outputs.kafka::redacted_live-metrics] Wrote batch of 25000 metrics in 348.550099ms
2025-02-10T18:37:18Z W! [agent] ["outputs.kafka::redacted_live-metrics"] did not complete within its flush interval
2025-02-10T18:37:19Z W! [agent] ["outputs.kafka::redacted_test-metrics"] did not complete within its flush interval
2025-02-10T18:37:20Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 123.045227ms
2025-02-10T18:37:20Z D! [inputs.x509_cert] Invalid certificate 1f9
2025-02-10T18:37:20Z D! [inputs.x509_cert]   cert DNS names:    [alma95-0003.redacted]
2025-02-10T18:37:20Z D! [inputs.x509_cert]   cert IP addresses: []
2025-02-10T18:37:20Z D! [inputs.x509_cert]   cert subject:      CN=alma95-0003.redacted
2025-02-10T18:37:20Z D! [inputs.x509_cert]   cert issuer:       CN=Puppet CA: provisioning-0001.redacted
2025-02-10T18:37:20Z D! [inputs.x509_cert]   opts.DNSName:      
2025-02-10T18:37:20Z D! [inputs.x509_cert]   verify options:    { 0xc00c6dda70 <nil> 0001-01-01 00:00:00 +0000 UTC [0] 0}
2025-02-10T18:37:20Z D! [inputs.x509_cert]   verify error:      x509: certificate signed by unknown authority
2025-02-10T18:37:20Z D! [inputs.x509_cert]   tlsCfg.ServerName: 
2025-02-10T18:37:20Z D! [inputs.x509_cert]   ServerName:        
2025-02-10T18:37:20Z W! [agent] ["outputs.kafka::redacted_test-metrics"] did not complete within its flush interval
2025-02-10T18:37:20Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-sysctl.service"): permission denied
2025-02-10T18:37:20Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-sysusers.service"): permission denied
2025-02-10T18:37:20Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-tmpfiles-setup-dev.service"): permission denied
2025-02-10T18:37:20Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-tmpfiles-setup.service"): permission denied
2025-02-10T18:37:21Z D! [outputs.kafka::redacted_test-metrics] Buffer fullness: 698981 metrics
2025-02-10T18:37:21Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 244.499572ms
2025-02-10T18:37:23Z D! [outputs.kafka::redacted_live-metrics] Buffer fullness: 237813 metrics
2025-02-10T18:37:23Z D! [outputs.kafka::redacted_live-metrics] Wrote batch of 25000 metrics in 246.784683ms
2025-02-10T18:37:28Z D! [outputs.kafka::redacted_test-metrics] Buffer fullness: 673982 metrics
2025-02-10T18:37:28Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 137.000615ms
2025-02-10T18:37:30Z W! [agent] ["outputs.kafka::redacted_test-metrics"] did not complete within its flush interval
2025-02-10T18:37:30Z D! [outputs.kafka::redacted_test-metrics] Buffer fullness: 673983 metrics
2025-02-10T18:37:30Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 159.584965ms
2025-02-10T18:37:30Z D! [inputs.x509_cert] Invalid certificate 1f9
2025-02-10T18:37:30Z D! [inputs.x509_cert]   cert DNS names:    [alma95-0003.redacted]
2025-02-10T18:37:30Z D! [inputs.x509_cert]   cert IP addresses: []
2025-02-10T18:37:30Z D! [inputs.x509_cert]   cert subject:      CN=alma95-0003.redacted
2025-02-10T18:37:30Z D! [inputs.x509_cert]   cert issuer:       CN=Puppet CA: provisioning-0001.redacted
2025-02-10T18:37:30Z D! [inputs.x509_cert]   opts.DNSName:      
2025-02-10T18:37:30Z D! [inputs.x509_cert]   verify options:    { 0xc00ae689c0 <nil> 0001-01-01 00:00:00 +0000 UTC [0] 0}
2025-02-10T18:37:30Z D! [inputs.x509_cert]   verify error:      x509: certificate signed by unknown authority
2025-02-10T18:37:30Z D! [inputs.x509_cert]   tlsCfg.ServerName: 
2025-02-10T18:37:30Z D! [inputs.x509_cert]   ServerName:        
2025-02-10T18:37:31Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-sysctl.service"): permission denied
2025-02-10T18:37:31Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-sysusers.service"): permission denied
2025-02-10T18:37:31Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-tmpfiles-setup-dev.service"): permission denied
2025-02-10T18:37:31Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-tmpfiles-setup.service"): permission denied
2025-02-10T18:37:31Z W! [agent] ["outputs.kafka::redacted_live-metrics"] did not complete within its flush interval
2025-02-10T18:37:32Z D! [outputs.kafka::redacted_live-metrics] Buffer fullness: 212813 metrics
2025-02-10T18:37:32Z D! [outputs.kafka::redacted_live-metrics] Wrote batch of 25000 metrics in 242.283889ms
2025-02-10T18:37:35Z W! [agent] ["outputs.kafka::redacted_test-metrics"] did not complete within its flush interval
2025-02-10T18:37:38Z D! [outputs.kafka::redacted_test-metrics] Buffer fullness: 648984 metrics
2025-02-10T18:37:39Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 146.661748ms
2025-02-10T18:37:41Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 180.469939ms
2025-02-10T18:37:41Z D! [inputs.x509_cert] Invalid certificate 1f9
2025-02-10T18:37:41Z D! [inputs.x509_cert]   cert DNS names:    [alma95-0003.redacted]
2025-02-10T18:37:41Z D! [inputs.x509_cert]   cert IP addresses: []
2025-02-10T18:37:41Z D! [inputs.x509_cert]   cert subject:      CN=alma95-0003.redacted
2025-02-10T18:37:41Z D! [inputs.x509_cert]   cert issuer:       CN=Puppet CA: provisioning-0001.redacted
2025-02-10T18:37:41Z D! [inputs.x509_cert]   opts.DNSName:      
2025-02-10T18:37:41Z D! [inputs.x509_cert]   verify options:    { 0xc00c6dc1e0 <nil> 0001-01-01 00:00:00 +0000 UTC [0] 0}
2025-02-10T18:37:41Z D! [inputs.x509_cert]   verify error:      x509: certificate signed by unknown authority
2025-02-10T18:37:41Z D! [inputs.x509_cert]   tlsCfg.ServerName: 
2025-02-10T18:37:41Z D! [inputs.x509_cert]   ServerName:        
2025-02-10T18:37:42Z W! [agent] ["outputs.kafka::redacted_live-metrics"] did not complete within its flush interval
2025-02-10T18:37:42Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-sysctl.service"): permission denied
2025-02-10T18:37:42Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-sysusers.service"): permission denied
2025-02-10T18:37:42Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-tmpfiles-setup-dev.service"): permission denied
2025-02-10T18:37:42Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-tmpfiles-setup.service"): permission denied
2025-02-10T18:37:43Z D! [outputs.kafka::redacted_live-metrics] Buffer fullness: 187813 metrics
2025-02-10T18:37:43Z D! [outputs.kafka::redacted_live-metrics] Wrote batch of 25000 metrics in 341.952999ms
2025-02-10T18:37:44Z W! [agent] ["outputs.kafka::redacted_test-metrics"] did not complete within its flush interval
2025-02-10T18:37:48Z W! [agent] ["outputs.kafka::redacted_test-metrics"] did not complete within its flush interval
2025-02-10T18:37:50Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-sysctl.service"): permission denied
2025-02-10T18:37:50Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-sysusers.service"): permission denied
2025-02-10T18:37:50Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-tmpfiles-setup-dev.service"): permission denied
2025-02-10T18:37:50Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/run/credentials/systemd-tmpfiles-setup.service"): permission denied
2025-02-10T18:37:51Z D! [outputs.kafka::redacted_test-metrics] Buffer fullness: 623985 metrics
2025-02-10T18:37:51Z D! [inputs.x509_cert] Invalid certificate 1f9
2025-02-10T18:37:51Z D! [inputs.x509_cert]   cert DNS names:    [alma95-0003.redacted]
2025-02-10T18:37:51Z D! [inputs.x509_cert]   cert IP addresses: []
2025-02-10T18:37:51Z D! [inputs.x509_cert]   cert subject:      CN=alma95-0003.redacted
2025-02-10T18:37:51Z D! [inputs.x509_cert]   cert issuer:       CN=Puppet CA: provisioning-0001.redacted
2025-02-10T18:37:51Z D! [inputs.x509_cert]   opts.DNSName:      
2025-02-10T18:37:51Z D! [inputs.x509_cert]   verify options:    { 0xc013bd3e90 <nil> 0001-01-01 00:00:00 +0000 UTC [0] 0}
2025-02-10T18:37:51Z D! [inputs.x509_cert]   verify error:      x509: certificate signed by unknown authority
2025-02-10T18:37:51Z D! [inputs.x509_cert]   tlsCfg.ServerName: 
2025-02-10T18:37:51Z D! [inputs.x509_cert]   ServerName:        
2025-02-10T18:37:51Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 97.210539ms
2025-02-10T18:37:53Z D! [outputs.kafka::redacted_test-metrics] Buffer fullness: 623984 metrics
2025-02-10T18:37:53Z D! [outputs.kafka::redacted_test-metrics] Wrote batch of 25000 metrics in 252.622682ms
2025-02-10T18:37:54Z W! [agent] ["outputs.kafka::redacted_live-metrics"] did not complete within its flush interval
2025-02-10T18:37:55Z W! [agent] ["outputs.kafka::redacted_test-metrics"] did not complete within its flush interval
2025-02-10T18:37:55Z D! [outputs.kafka::redacted_live-metrics] Buffer fullness: 162813 metrics
2025-02-10T18:37:56Z D! [outputs.kafka::redacted_live-metrics] Wrote batch of 25000 metrics in 481.428268ms
```

### System info

Telegraf 1.33.1 , Alma 9.5

### Docker

_No response_

### Steps to reproduce

Not 100% clear but enabling the disk buffer strategy and turning it off seemed to show a change as shown in the screen shot of one metric value below.

### Expected behavior

No metrics loss (provided disk is available)
When viewing collected data, no gaps
When viewing logs from telegraf, no collection did not complete messages

### Actual behavior

When running with the disk based buffer strategy, after a period of time, logs indicate that collection too longer than expected and did not complete.  This did not seem to show in the logs immediately after reboot with debug turned on.  WIll continue to monitor that aspect.  This results in inconsistent metrics making it hard if not impossible to monitor a host.

Image

### Additional info

_No response_

### LINKED ISSUE #16615: Telegraf is not flushing the buffer in downtime scenarios
### Relevant telegraf.conf

```toml
[agent]
  interval = "1s"
  metric_batch_size = 5
  flush_interval = "5s"
  flush_jitter = "5s"
  metric_buffer_limit = 10
  buffer_strategy = "disk"
  buffer_directory = "/data/var/telegraf/data"
  ## Log at debug level
  debug = true
  ## Log only error level messages
  quiet = false

# Read metrics from MQTT
[[inputs.mqtt_consumer]]
   servers = ["localhost:1883"]
   ## Topics subscribed to.
   topics = [
     "MON"
   ]
   data_format = "json"



# Send metrics to InfluxDB
[[outputs.influxdb_v2]]
  urls = ["http://url:8086"]
  token = "<token>"
  
 
  organization = "<org>"
  bucket = "<bucket name>"
```

### Logs from Telegraf

```text
2025-03-11T14:00:40Z I! Loading config: /data/config/telegraf/telegraf.conf
2025-03-11T14:00:40Z W! Using disk buffer strategy for plugin outputs.influxdb_v2, this is an experimental feature
2025-03-11T14:00:40Z I! Starting Telegraf 1.34.0 brought to you by InfluxData the makers of InfluxDB
2025-03-11T14:00:40Z I! Available plugins: 239 inputs, 9 aggregators, 33 processors, 26 parsers, 63 outputs, 6 secret-stores
2025-03-11T14:00:40Z I! Loaded inputs: mqtt_consumer
2025-03-11T14:00:40Z I! Loaded aggregators:
2025-03-11T14:00:40Z I! Loaded processors:
2025-03-11T14:00:40Z I! Loaded secretstores:
2025-03-11T14:00:40Z I! Loaded outputs: influxdb_v2
2025-03-11T14:00:40Z I! Tags enabled: host=xxx
2025-03-11T14:00:40Z I! [agent] Config: Interval:1s, Quiet:false, Hostname:"xxx", Flush Interval:5s
2025-03-11T14:00:40Z W! [agent] The default value of 'skip_processors_after_aggregators' will change to 'true' with Telegraf v1.40.0! If you need the current default behavior, please explicitly set the option to 'false'!
2025-03-11T14:00:40Z D! [agent] Initializing plugins
2025-03-11T14:00:40Z W! [inputs.mqtt_consumer] Server "localhost:1883" should be updated to use `scheme://host:port` format
2025-03-11T14:00:40Z D! [agent] Connecting outputs
2025-03-11T14:00:40Z D! [agent] Attempting connection to [outputs.influxdb_v2]
2025-03-11T14:00:40Z D! [agent] Successfully connected to outputs.influxdb_v2
2025-03-11T14:00:40Z D! [agent] Starting service inputs
2025-03-11T14:00:40Z I! [inputs.mqtt_consumer] Connected [localhost:1883]
2025-03-11T14:00:50Z D! [outputs.influxdb_v2] Buffer fullness: 55 metrics
2025-03-11T14:00:56Z D! [outputs.influxdb_v2] Buffer fullness: 55 metrics
2025-03-11T14:01:03Z D! [outputs.influxdb_v2] Buffer fullness: 55 metrics
2025-03-11T14:01:09Z D! [outputs.influxdb_v2] Buffer fullness: 55 metrics
2025-03-11T14:01:16Z D! [outputs.influxdb_v2] Buffer fullness: 55 metrics
2025-03-11T14:01:24Z D! [outputs.influxdb_v2] Buffer fullness: 55 metrics
2025-03-11T14:01:32Z D! [outputs.influxdb_v2] Buffer fullness: 55 metrics
2025-03-11T14:01:42Z D! [outputs.influxdb_v2] Buffer fullness: 55 metrics
2025-03-11T14:01:50Z D! [outputs.influxdb_v2] Buffer fullness: 55 metrics
2025-03-11T14:01:57Z D! [outputs.influxdb_v2] Buffer fullness: 55 metrics
2025-03-11T14:02:04Z D! [outputs.influxdb_v2] Buffer fullness: 55 metrics
2025-03-11T14:02:12Z D! [outputs.influxdb_v2] Buffer fullness: 55 metrics
```

### System info

Telegraf 1.33.3 and Telegraf 1.34

### Docker

_No response_

### Steps to reproduce

1. Run Telegraf using the configuration given. 
2. Simulate breakage of connection between Telegraf and Influxdb either by stopping Influxdb or changing the token to a bad one inside the Telegraf configuration. 
3. Undo step 2.

### Expected behavior

At the moment I try to configure Telegraf so that in a case of a downtime scenario (whether the machine running Telegraf has no internet or Influxdb is down) the metrics gathered while down will be sent after recovery. 
I intended to use buffer_strategy "disk" as solution, so that when for example the Influxdb is down, the buffer increases and when the Influxdb is back, telegraf flushes the buffer, buffer becoming empty.

### Actual behavior

After running my configurations I noticed two different situations after the simulated downtime:
1. Telegraf sends new metrics to Influxdb but the buffer fullness remains the same and is never flushed.
2. All the metrics that Telegraf should send to InfluxDb are stored in the buffer so the buffer keeps increasing and is never flushed.

### Additional info

Did I misunderstood how the setting buffer_strategy set to disk is working? Is there another approach to this problem?

Thank you, 
Bogdan

### LINKED ISSUE #16696: Disk buffer never truncated
### Relevant telegraf.conf

```toml
[agent]
  interval = "10s"
  buffer_strategy = "disk"
  buffer_directory = "/home/$user/bufferTest"

[[inputs.mem]]
[[inputs.cpu]]
[[inputs.disk]]

[[outputs.file]]
  files = ["/dev/null"]
```

### Logs from Telegraf

```text
2025-03-26T19:10:30Z D! [outputs.file] Wrote batch of 53 metrics in 264.11µs
2025-03-26T19:10:30Z D! [outputs.file] Buffer fullness: 2 metrics
```

### System info

Telegraf 1.34.0 and commit c17467b8cbef63def976f24af30e4f221e0061ec, Linux fedora 6.13.7-200.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Mar 13 17:46:13 UTC 2025 x86_64 GNU/Linux, baremetal

### Docker

The disk buffer is never truncated and therefore grows to infinity.

Unless I am mistaken, the issue seems fairly obvious in the code:
```go
func (b *DiskBuffer) BeginTransaction(batchSize int) *Transaction {
  ...
  offsets := make([]int, 0, batchSize)
  ...
  offset := 0
  for batchSize > 0 && readIndex < endIndex {
    ...
    offset++
    ...
    offsets = append(offsets, offset) // Offsets are always >= 1!
    ...
  }
  return &Transaction{Batch: metrics, valid: true, state: offsets}
}

func (b *DiskBuffer) EndTransaction(tx *Transaction) {
  ...
  offsets := tx.state.([]int)
  ... // some (or all) elements of offsets are added to b.mask
  if len(b.mask) == 0 || b.mask[0] != 0 { // b.mask[0] cannot be equal to 0, ever!
    ...
    return
  }
  ...
}
```

I've run telegraf 1.34.0 several times and am currently running the master branch's latest commit (as of when I am writing this). In the case of 1.34.0, I let it run for several days and the buffer grew to several tens of MBs in size, as reported by `du -hd 0`. In the case of the master branch, my buffer is at 2.6 MB after roughly 10 minutes

### Steps to reproduce

1. Run telegraf with the included configuration file.
2. Watch the disk buffer grow.

### Expected behavior

The buffer grows and shrinks as data gets added and removed.

### Actual behavior

The buffer grows and never shrinks.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by nagaflokhu**
## Summary

The disk buffer grows and never shrinks, as documented [here](https://github.com/influxdata/telegraf/issues/16696).

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #16314
resolves #16500
resolves #16615
resolves #16696

### CODE REVIEW

**Comment by nagaflokhu** [comment]
This fix appears to work in the tests I have run, but I am not confident that it actually always works.

File: models/buffer_disk.go [hunk 1]
```diff
@@ -223,7 +221,7 @@ func (b *DiskBuffer) EndTransaction(tx *Transaction) {
 
 	// Remove the metrics that are marked for removal from the front of the
 	// WAL file. All other metrics must be kept.
-	if len(b.mask) == 0 || b.mask[0] != 0 {
+	if len(b.mask) == 0 {
```
Comment (nagaflokhu) [inline models/buffer_disk.go:224]: I am not sure why, but if I left the second condition, my fix did not work, despite the changes above and below.

**Comment by nagaflokhu** [comment]
the buffer fullness debug messages appear not to work with my patch. e.g.:
2025-03-26T19:34:07Z D! [outputs.file] Buffer fullness: -818 metrics

File: models/buffer_disk.go [hunk 2]
```diff
@@ -147,13 +147,11 @@ func (b *DiskBuffer) BeginTransaction(batchSize int) *Transaction {
...
 	endIndex := b.writeIndex()
 	offset := 0
-	for batchSize > 0 && readIndex < endIndex {
+	for ; batchSize > 0 && readIndex < endIndex; readIndex, offset = readIndex+1, offset+1 {
 		data, err := b.file.Read(readIndex)
 		if err != nil {
 			panic(err)
 		}
-		readIndex++
-		offset++
```
Comment (srebhan) [inline models/buffer_disk.go:155]: This is no functional change. Can we please get this reverted to see the minimal change necessary to fix the problem?

Comment (nagaflokhu) [reply models/buffer_disk.go:155]: you are perhaps right in the case of `readIndex`, but I am pretty sure moving the increment of `offset` is in fact a functional change.

`offset` is being added into a slice in the body of the loops. putting `offset++` earlier in that same loop body guarantees that `offset` can *never be equal to 0* when it is added to the slice, whereas placing `offset++` *outside the body of the loop* means `offset` can be equal to 0 when it gets added to the slice, which seems to be the intended behaviour.

**Comment by nagaflokhu** [comment]
it might be a good idea to consider different approaches to dealing with the fact that the `wal` lib does not allow truncating all of its elements. four that come to mind (the first two being very similar to each other):

1. every time there is a write to the WAL, add a "sentinel" element in addition to the metrics being added. the sentinel is a well-known value that is impossible to obtain from serializing a metric. when reading from the WAL, ignore the sentinels. when truncating all metrics from the WAL, make sure to leave the latest write's sentinel in the WAL.
2. when trunctaing all metrics from the WAL, add a sentinel first, and then truncate everything except the sentinel. (why shouldn't this be possible?)
3. change the `wal` library such as to allow truncating everything from the WAL.
4. don't use the WAL library. it seems to me that, at an abstract level, what we want for this buffer is an on-disk deque, i.e. the possibility to add to/read from/remove from the front/back.

File: models/buffer_disk.go [hunk 3]
```diff
@@ -147,13 +147,11 @@ func (b *DiskBuffer) BeginTransaction(batchSize int) *Transaction {
 	readIndex := b.batchFirst
 	endIndex := b.writeIndex()
 	offset := 0
-	for batchSize > 0 && readIndex < endIndex {
+	for ; batchSize > 0 && readIndex < endIndex; readIndex, offset = readIndex+1, offset+1 {
```
Comment (srebhan) [inline models/buffer_disk.go:150]: Oh I see because we are adding this _before_ the rest of the code and you do it at the end... In this case it would be good to keep the `readIndex` as is and use the following

```golang
	for offset :=0; batchSize > 0 && readIndex < endIndex; offset++ {
```

Comment (nagaflokhu) [reply models/buffer_disk.go]: done

**Comment by nagaflokhu** [comment]
!signed-cla

File: models/buffer_disk.go (hunk 3 above)
Comment (nagaflokhu) [reply models/buffer_disk.go]: I was wondering if we were going to attempt to complete this PR? it seems like a pretty major issue with the disk buffer

**Comment by srebhan** [comment]
@nagaflokhu sorry for this being so slow! We do appreciate your effort on this! For moving forward with the PR, we need to check why the tests are failing now. If the tests were wrong initially, we need an explanation on why they were wrong and a fix to correct the test. Otherwise, if the tests are correct, we need to fix the code to get the tests to pass.
We also need to make sure that the present error is covered by a unit-test, i.e. add a test if there is none yet.

**Comment by nagaflokhu** [comment]
@srebhan I've now fixed the tests that were failing and added an assertion for regression purposes. I just ran the additional assertion on the code from the latest master branch commit, and it shows that the previous implementation was not working: accepting a transaction and ending it did not change the amount of entries in the buffer. the other assertion in the test I modified was passing because the mask had a length of 2.

**Comment by srebhan** [comment]
@nagaflokhu I took the liberty to push some commits to your branch including a unit-test and some missing pieces for fixing the issue. What do you think?

**Comment by nagaflokhu** [comment]
> @nagaflokhu I took the liberty to push some commits to your branch including a unit-test and some missing pieces for fixing the issue. What do you think?

very nice!

fwiw, I wonder if an alternative disk buffer design might not be simpler than having to manage a mask, but it looks to me like we're not going down that route, so let's move forward I guess.

**Comment by srebhan** [comment]
An alternative WAL implementation will not happen anytime soon so let's fix this!

**Review by srebhan — APPROVED** [review]
Thanks @nagaflokhu for pushing this forward!

**Comment by srebhan** [comment]
@mstrandboge and @skartikey approved this but as I'm involved in the code, please review both! Furthermore, review but do not merge yet until we get some confirmations it fixes the issue(s).

**Comment by skartikey** [comment]
The proposed fix looks solid and appears to resolve the issue with the buffer not shrinking properly. It correctly maintains the mask, handles the empty buffer case more consistently, and adjusts offsets after truncation as expected.

While reading through the code, I considered checking whether the condition `b.isEmpty = b.entries()-removeIdx <= 0` reliably detects when the buffer becomes empty. This would be a key area to investigate if shrinking were to fail. However, I later noticed that the `TestDiskBufferTruncate` test case already covers this scenario effectively. It verifies the buffer’s behavior across multiple batches and confirms that, when logically empty, no metrics are returned and the remaining masked entry is handled appropriately due to the WAL design.

The fix aligns well with what this test validates. Great work on this!

**Review by skartikey — APPROVED** [review]

**Comment by srebhan** [comment]
Thanks @skartikey for the thorough review!
