### PR TITLE
Fix postgres extensible text

### LINKED ISSUE #1600: postgresql_extensible plugin does not quote string values
### Relevant telegraf.conf:
```
[[inputs.postgresql_extensible]]
	[[inputs.postgresql_extensible.query]]
		sqlquery = "select 'foo' as bar"
```

### System info:

Version: current master (49988b1)

### Steps to reproduce:

1. `telegraf -config telegraf.conf -test`

### Expected behavior:
```
* Plugin: postgresql_extensible, Collection 1
> postgresql,host=x bar="foo" 1470627087634734894
```

### Actual behavior:
```
* Plugin: postgresql_extensible, Collection 1
> postgresql,host=x bar=foo 1470627087634734894
```

### Additional information:

The plugin needs to output text values as strings, not byte arrays, then they'll be encoded correctly.

### PR DESCRIPTION
**Pull request by phemmer**
### Required for all PRs:

- [X] CHANGELOG.md updated
- [X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Fixes #1600 

I also did some code cleanup on the nearby code so that it better follows golang coding standards (type switching & less nesting).

### CODE REVIEW

File: plugins/inputs/postgresql_extensible/postgresql_extensible.go [hunk 1]
```diff
@@ -266,29 +266,33 @@ func (p *Postgresql) accRow(meas_name string, row scanner, acc telegraf.Accumula
...
+				continue
 			}
-			if isATag == 0 {
-				fields[col] = *val
+			switch v := (*val).(type) {
+			case []byte:
+				tags[col] = string(v)
+			case int64:
+				tags[col] = fmt.Sprintf("%d", v)
 			}
```
Comment (phemmer) [inline plugins/inputs/postgresql_extensible/postgresql_extensible.go]: I have no idea why the code only supported `[]byte` and `int64` tags (though I suspect this is another bug), so I left it as is.

**Comment by phemmer** [comment]
Build failure appears unrelated to the changes in this PR as this PR does not touch the failing plugin, or any code the plugin uses:

```
2016/08/08 06:49:38 subject: telegraf, error: unable to parse 'cpu_load_short,host=server01 1422568543702900257': invalid field format
--- FAIL: TestRunParserAndGather (0.03s)
	Error Trace:	accumulator.go:188
			nats_consumer_test.go:83
	Error:		unknown measurement cpu_load_short
		

FAIL
FAIL	github.com/influxdata/telegraf/plugins/inputs/nats_consumer	0.154s
```

**Comment by sparrc** [comment]
thanks @phemmer
