### PR TITLE
fix(outputs.influxdb_v2): Handle serialization errors correctly

### LINKED ISSUE #17205: "no serializable fields" causes influxdb_v2 output to drop unrelated metrics in batch
### Relevant telegraf.conf

```toml
[[inputs.socket_listener]]
  alias = "collectd"
  data_format = "graphite"
  read_buffer_size = "256KiB"
  separator = "_"
  service_address = "tcp://:2003"
  templates = [
    "collectd.*.iwinfo.* .host.measurement.device.field*",
    "collectd.*.interface.* .host.measurement.device.field*",
    "collectd.*.netlink.* .host.measurement.device.field*",
    "collectd.*.cpu.* .host.measurement.cpu.field*",
    "collectd.*.processes.ps_state .host.measurement.field.state",
    "collectd.*.processes.fork_rate .host.measurement.field",
    "collectd.*.processes.* .host.measurement.process.field*",
    "collectd.*.load.* .host.measurement.field*",
    "collectd.*.memory.* .host.measurement.field*",
    "collectd.*.ping.* .host.measurement.field.target.target.target.target",
    "collectd.*.sensors.* .host.measurement.chip.field.feature",
    "collectd.*.uptime.* .host.measurement",
    ".host.measurement.field*"
  ]
  [inputs.socket_listener.tags]
    collectd = "true"

[[outputs.influxdb_v2]]
  bucket = "default"
  bucket_tag = "influxdb_target_bucket"
  content_encoding = "identity"
  exclude_bucket_tag = true
  influx_uint_support = true
  namedrop = [
    "log_*",
    "*_log",
    "win_eventlog",
    "syslog",
    "log"
  ]
  organization = "$INFLUXDB_V2_ORGANIZATION"
  token = "$INFLUXDB_V2_TOKEN"
  urls = [
    "http://influxdb-influxdb2:8085"
  ]
```

### Logs from Telegraf

```text
2025-06-17T23:47:36Z D! [outputs.file] Could not serialize metric: "ping,collectd=hostname,host=hostname,target=ip,telegraf=influxdb/telegraf-74fc7f69cc-dmbl6": no serializable fields
2025-06-17T23:47:36Z D! [outputs.file] Could not serialize metric: "ping,collectd=hostname,host=hostname,influxdb_target_bucket=compute,target=ip": no serializable fields
```

### System info

Telegraf 1.34

### Docker

_No response_

### Steps to reproduce

1. I have a collectd instance running on my router, performing a ping regularly. I am sending the ping information to Telegraf (to perform postprocessing before writing to Influx) via Graphite encoding.
2. Recently, one of the routers were decommissioned, and thus the ping metrics were no longer being reported. However, collectd encodes the data with the tags but not fields.
3. I noticed that the metric points from the host (and only the affected hosts) were missing, even for unrelated measurements.

### Expected behavior

Only the ping measurements should be dropped, the others should still be submitted.

### Actual behavior

Image

I removed the faulty Ping metric at ~7.55am. This is the system.uptime as reported by the host, and aggregated in Influx.

### Additional info

I managed to debug this only because I created a duplicate output for the affected measurements and encoded it to file. I saw that the log messages were printed only for the file output (which was my debug) and not the Influx v2 output. The dropped metrics count didn't show anything amiss. It seems like the batching code is dropping these unrelated metrics without showing any feedback it is doing so.

Removing the broken ping metrics from the source restored all my data points.

### LINKED ISSUE #17235: Debugging/Tracing input.exec: Sometimes it sends, sometimes it does not.
### Use Case

We are currently stuck in a situation, were we have five `inputs.exec` entries in our config - but out of all the five, _sometimes_ two of them do something and sometimes they do not. There are no errors in the Telegraf log, and none we could find in Event Viewer in general - yes, this is on Windows. All five of them have the same layout:

```toml
[[inputs.exec]]
  commands = [ "powershell.exe -NoProfile -ExecutionPolicy Bypass -Command \"&'C:/(...)/backupReplication.ps1' -ReportType backupRepository\"" ]
  interval = "1h"
  timeout = "180s"
  data_format = "json_v2"
  [[inputs.exec.json_v2]]
    measurement_name = "veeam.backupReplication.backupRepository"
    [[inputs.exec.json_v2.object]]
      path = "@this"
      tags = [ "RepositoryName" ]
```

This is why we need more debugging or tracing. Having gone through the recent releases and their changelogs, we have also played around with `debug = true`, as well as `log_level = "trace"` as recently introduced. Unfortunately, to no avail.

He spent the most time with the actual debugging and I went to read the commits, releases and code to try and find him pointers as to what he could try to do. Interestingly, this _did_ use to work in 1.27.

His summary:
- Using Telegraf 1.34.1 with multiple `inputs.exec` plugins scheduled at the same interval (e.g., every 10 minutes).
 - PowerShell processes for each `inputs.exec` are correctly launched (confirmed by observing Task Manager).
 - No errors, timeouts, or scheduling warnings are logged in Telegraf (debug logging enabled).
 - Some `inputs.exec` executions randomly fail to deliver metrics to InfluxDB despite the script always producing valid JSON output (verified via local file logging).
 - Issue did not occur in Telegraf 1.27 with identical configuration and system load. We only recently upgraded to 1.34.
 - Changing GOMAXPROCS had no effect.
  * This was my idea, as this behaviour was talked about a lot lately on r/golang and was mentioned to have it's behaviour changed. Mainly for containers, but I'd thought to just give it a try.
- Appears related to Telegraf’s stricter input scheduling since v1.30, where `inputs.exec` commands scheduled at the same interval may conflict or be silently skipped even when system resources are available.

### Expected behavior

Telegraf should either multi-thread `inputs.exec` properly or log skipped executions clearly.

Or, it should produce apropriate logs in debug/trace logging to indicate:
- When the command (and which one) was started,
- If it exited with a non-zero exit code
- If it was perhaps killed due to timeout or alike.

### Actual behavior

It quietly fails with no indication as to why or what caused it. Observing the logs on both InfluxDB and Telegraf brought us no closer. I will likely monkey-patch a local copy of Telegraf (local build) to use Go's stdlib `fmt.Println(...)` calls to just output _something_ to help us understand more about what is going on - or rather, what isn't.

### Additional info

As mentioned previously, this used to work just fine in 1.27. But due to other requirements, we opted to update the version of Telegraf we used in hopes to incorporate new plugins and features - but were now met with this. Veeam is a cruicial part of what we monitor here, and not having it reliably return information is a bit of a problem... Aside from wrapping the VBR Cmdlets in scripts and producing JSON out of it which can be parsed and understood by Telegraf, we hadn't found a better alternative. So, we rely on `inputs.exec` for the various information from this instead. It also gives us flexibility in perhaps adding other metadata from other Cmdlet calls in the future if we need or want to.

### PR DESCRIPTION
**Pull request by srebhan**
## Summary

The current code fails to handle serialization errors, e.g. due to `NaN` values or invalid field keys, as batching returns the serialization error straight away. Subsequently, the error triggers an early exit in the http client code because the `used` variable is zero.

This PR fixes two issues:

Do not return early in the http client if one of the batches does not contain any payload. Instead check if the size of the limited serializer is exceeded and if not continue to process the remaining batches. This prevents early exits and thus prevent the plugin to get stuck on serialization errors.

Reject metrics causing serialization errors to prevent infinite resend-loops and remove rejected metrics from the list of metrics acceptable later. Removing the metrics (or rather the indices) is required to not double-account the metric.

## Checklist

- [x] No AI generated code was used in this PR
- [ ] AI generated code used in this PR follows the [InfluxData Policy on AI-Generated Code Contributions][policy]

[policy]: https://www.influxdata.com/ai-generated-code-contributions-policy

## Related issues

resolves #17205 
resolves #17235

### CODE REVIEW

File: plugins/outputs/influxdb_v2/batching.go [hunk 1]
```diff
@@ -102,11 +103,23 @@ func (b *batch) split() (first, second *batch) {
...
 	body, serr := serializer.SerializeBatch(b.metrics, limit)
 	if serr != nil && !errors.Is(serr, internal.ErrSizeLimitReached) {
-		return int64(len(body)), serr
+		// When only part of the metrics failed to be serialized we should remove
+		// them from the normal handling and mark them as rejected for upstream
+		// to pass on this information
+		var werr *internal.PartialWriteError
+		if errors.As(serr, &werr) {
+			for i, idx := range slices.Backward(werr.MetricsReject) {
+				werr.MetricsReject[i] = b.indices[idx]
```
Comment (lowjoel) [inline plugins/outputs/influxdb_v2/batching.go:115]: Is the reversing of the order intentional? I'd imagine that the rejected metrics would still be in order; but slices.Backward reverses it?

(just a comment explaining logic is fine here)

File: plugins/outputs/influxdb_v2/http.go [hunk 2]
```diff
@@ -169,20 +169,30 @@ func (c *httpClient) Write(ctx context.Context, metrics []telegraf.Metric) error
...
-		if used == 0 {
-			limitReached = i
-			break
+			var werr *internal.PartialWriteError
+			if errors.As(err, &werr) {
+				writeErr.MetricsReject = append(writeErr.MetricsReject, werr.MetricsReject...)
+				writeErr.MetricsRejectErrors = append(writeErr.MetricsRejectErrors, werr.MetricsRejectErrors...)
+				writeErr.Err = werr.Err
+			} else {
+				writeErr.Err = err
```
Comment (lowjoel) [inline plugins/outputs/influxdb_v2/http.go:178]: nit: this can overwrite an earlier PartialWriteError -- is this intentional?

**Review by lowjoel — APPROVED** [review]
LGTM apart from some clarifications. I can't run this right now since I don't seem to be getting NaNs from my data source right now.

**Comment by senpro-ingwersenk** [comment]
Getting to it. Thanks for the ping; will come back with results in a bit!

File: plugins/outputs/influxdb_v2/batching.go (hunk 1 above)
Comment (srebhan) [reply plugins/outputs/influxdb_v2/batching.go:115]: If you look at the next line, we are deleting data from the `b.indices` slice. If you would not revert the order, i.e. start removing from the end but from the start, the indices would shift because you are removing elements from the start. However, I think we should make things more robust in the model code using this array. So good point. Will address in a separate PR.

File: plugins/outputs/influxdb_v2/http.go (hunk 2 above)
Comment (srebhan) [reply plugins/outputs/influxdb_v2/http.go:178]: Yes, the overriding happened before as the code only uses the last error as top-level error. The new part is to unwrap the partial error we get from the serialization as we merge it to this partial error.

File: plugins/outputs/influxdb_v2/batching.go (hunk 1 above)
Comment (lowjoel) [reply plugins/outputs/influxdb_v2/batching.go:115]: Yeah, I was tripping on the index logic quite a few times, maybe it's just me though 😅

**Comment by srebhan** [comment]
@lowjoel any chance you test the binary and report back in the issue?

**Comment by lowjoel** [comment]
> @lowjoel any chance you test the binary and report back in the issue?

I can test the binary but I don't have any NaNs that can trip the bug now - the source was sporadically causing the metric rejection because it was sporadically writing NaNs. I couldn't figure out how but it hasn't in a few weeks.

File: plugins/outputs/influxdb_v2/batching.go (hunk 1 above)
Comment (srebhan) [reply plugins/outputs/influxdb_v2/batching.go:115]: Ok I double checked the code and we do not enforce an order on the indices as the buffers do things robustly already. So no additional change required...

**Comment by srebhan** [comment]
Ok, as @senpro-ingwersenk gave a go and my unit-test reproduces the `NaN` case I think we are good for review...

**Review by skartikey — APPROVED** [review]
@srebhan The implementation is solid!
This correctly fixes the critical data loss bug where serialization errors would cause valid metrics to be dropped.

**Comment by IngwiePhoenix** [comment]
Oops, should've replied here instead of in #17235
Either way; LGTM! Seems to have resolved the issue and surfaced a new one - but none that seems to be too problematic.

Thank you for the PR!

**Comment by srebhan** [comment]
@IngwiePhoenix no worries, I always check both the issue and the PR, replying to both is fine... ;-)

**Review by mstrandboge — APPROVED** [review]
