### PR TITLE
fix(inputs.kafka_consumer): Mark messages that failed parsing

### LINKED ISSUE #14579: kafka_consumer should call markmessage on messages that failed parsing
### Use Case

I have a kafka topic that unfortunately has a mixture of json and avro messages!  I know this is very bad practice; I'm the consumer of the topic not the publisher, so I have to handle it.  I have configured telegraf to just consume the avro messages (these are the only ones that I care about).

Sometimes there are long stretches of json messages, and these will then fail the parsing since they are not valid binary avro messages.  I would like for these messages that failed parsing to be marked as processed so the offset of the partition can be updated even when there are no valid parseable message for a long span.

### Expected behavior

When a kafka message fails parsing, the message is still marked and can then be used to commit the consumer group's offset on the partition.

### Actual behavior

When a kafka message fails parsing, the message is ignored and will not be used as the offset to commit.

### Additional info

This diff would solve the problem, I believe:
```diff
	metrics, err := h.parser.Parse(msg.Value)
	if err != nil {
+ 		session.MarkMessage(msg, "")
		h.release()
		return err
	}
```

Although I think it may be preferable to include `session.MarkMessage` in the `h.release()` method so that we can ensure that the handling of messages that exceed max length and messages that fail parsing are released and marked identically. 

Happy to put up a PR if this would be an acceptable behavior change.

### PR DESCRIPTION
**Pull request by jkerfs**
## Summary
Mark kafka messages if they failed parsing so that consumer group's partition offsets are committed properly for messages that do not parse properly.

## Checklist

- [X] No AI generated code was used in this PR

## Related issues
resolves #14579

### CODE REVIEW

**Comment by jkerfs** [comment]
!signed-cla

File: plugins/inputs/kafka_consumer/kafka_consumer.go [hunk 1]
```diff
@@ -483,6 +483,7 @@ func (h *ConsumerGroupHandler) Handle(session sarama.ConsumerGroupSession, msg *
 
 	metrics, err := h.parser.Parse(msg.Value)
 	if err != nil {
+		session.MarkMessage(msg, "")
```
Comment (srebhan) [inline plugins/inputs/kafka_consumer/kafka_consumer.go:486]: Should we provide some metadata? Like
```suggestion
		session.MarkMessage(msg, "telegraf: failed parsing")
```

**Review by srebhan — COMMENTED** [review]
@jkerfs the code looks good, just one small question from my side...

File: plugins/inputs/kafka_consumer/kafka_consumer.go (hunk 1 above)
Comment (powersj) [reply plugins/inputs/kafka_consumer/kafka_consumer.go:486]: I don't think that metadata is meant for random strings or reasons. That metadata is passed to the markoffset call. There is a comment in the docs about other consumers using that string to restore state.

As we do not currently do that for other errors, I would be hesitant to start.

**Review by srebhan — APPROVED** [review]
Thanks for the fix @jkerfs!
