### PR TITLE
fix(inputs.tail): Fix data race when cleaning up unused tailers

### LINKED ISSUE #17571: Race condition in tail input tests
### Relevant telegraf.conf

```toml
N/A
```

### Logs from Telegraf

```text
N/A
```

### System info

N/A

### Docker

_No response_

### Steps to reproduce

https://app.circleci.com/pipelines/github/influxdata/telegraf/27606/workflows/9ed6cdc3-698b-45db-8dba-578ff60fa463/jobs/438200

### Expected behavior

N/A

### Actual behavior

N/A

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skartikey**
## Summary

Fixes a critical data race condition in the tail input plugin that was blocking multiple dependency updates due to increased detection frequency with testify v1.11.x.

The race condition occurred in `cleanupUnusedTailers()` between:
  - The telegraf tail plugin calling `Tell()` to get the current file offset
  - The tail library's internal goroutine calling `reopen()` which modifies the file handle

  ### Solution

  Removed the `Tell()` call during cleanup of tailers for files that no longer match glob patterns. This is a safe trade-off because:

  1. Files removed from glob patterns are typically rotated logs (e.g., `app.log` → `app.log.1`) that won't return with the same name
  2. The Stop() method still saves offsets when the plugin stops normally, preserving the primary use case
  3. Eliminates the race condition entirely rather than trying to work around it

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #17571

### CODE REVIEW

File: plugins/inputs/tail/tail.go [hunk 1]
```diff
@@ -351,16 +351,14 @@ func (t *Tail) cleanupUnusedTailers(currentFiles map[string]bool) error {
...
-				}
-			}
+			// NOTE: We intentionally do NOT save the offset here because:
+			// 1. There's a data race in the tail library between Tell() and reopen()
+			//    that could cause undefined behavior or incorrect offsets
+			// 2. Files removed from glob patterns are typically rotated logs that
+			//    won't return with the same name
+			// 3. The Stop() method will save offsets safely when the plugin stops
+			// This trade-off prioritizes stability over rare edge cases where a
+			// file temporarily doesn't match the glob and returns later.
```
Comment (srebhan) [inline plugins/inputs/tail/tail.go]: I see one issue with this: The `t.offsets` represent a state of the plugin that _might_ be persisted to disk. So Imagine the following situation: We read a new file with `t.offsets[fn]` being **zero** at this point. We now read a certain number of lines (say 10) and produce 10 metrics and suppose the `t.offsets[fn]` being `1280`.
Now someone moves the file away, triggering the `cleanupUnusedTailers` to stop that file but you removed the `Tell` call so the offset is stuck at **zero** instead of `1280`... Shortly after that Telegraf is stopped, the file restored and Telegraf is restarted with the initial index option being `saved-or-beginning`. Telegraf will, as it has an index of zero or non at all (not sure here), produce the previous 10 metrics **again** as it will read the file from beginning...

So what I want to ask is, is there a way to update the offsets, maybe after each "reception" of data? Or can we fix `tail` to avoid the race?

**Review by srebhan — COMMENTED** [review]
Thanks @skartikey! One question in the code...

File: plugins/inputs/tail/tail.go (hunk 1 above)
Comment (skartikey) [reply plugins/inputs/tail/tail.go]: @srebhan Excellent point! You're absolutely right about the state persistence issue. The missing Tell() call in cleanupUnusedTailers means we lose the current offset state when a file gets moved/removed, which would cause duplicate metrics on restart with `saved-or-beginning`.

  Let me investigate the best approach to fix this while avoiding the race condition. I'll look into either:
  1. Ensuring offsets get updated periodically during normal operation, or
  2. Fixing the race condition in the cleanup logic itself

  I'll come back with a solution that properly maintains the offset state. Thanks for catching this!

Comment (skartikey) [reply plugins/inputs/tail/tail.go]: @srebhan I’ve updated the fix based on your feedback. The new approach now preserves offsets correctly while avoiding the race condition.

The main change is to **stop the tailer first** and then call `Tell()` to get the offset. This works because:

1. `tailer.Stop()` waits until the internal goroutine is fully closed.
2. Once it’s stopped, there’s no concurrent access to the file handle.
3. We can then safely call `Tell()` and store the offset.

Let me know what you think!

File: plugins/inputs/tail/tail.go [hunk 2]
```diff
@@ -351,23 +351,25 @@ func (t *Tail) cleanupUnusedTailers(currentFiles map[string]bool) error {
 			// We need to stop tailing it and remove it from our list
 			t.Log.Debugf("Removing tailer for %q as it's no longer in the glob pattern", file)
 
-			// Save the current offset for potential future use
+			// Stop the tailer first to avoid race conditions
+			// This ensures the tail goroutine is no longer running when we call Tell()
+			err := tailer.Stop()
+			if err != nil {
```
Comment (srebhan) [inline plugins/inputs/tail/tail.go]: Reduce the scope of errors wherever possible. This avoids checking a previously checked error again or overriding the error before checking...

```suggestion
			if err := tailer.Stop(); err != nil {
```

File: plugins/inputs/tail/tail.go [hunk 3]
```diff
@@ -351,23 +351,25 @@ func (t *Tail) cleanupUnusedTailers(currentFiles map[string]bool) error {
...
+				t.Log.Errorf("Stopping tail on %q: %s", tailer.Filename, err.Error())
```
Comment (srebhan) [inline plugins/inputs/tail/tail.go]: Use the `%v` directive as it is shorter...

```suggestion
				t.Log.Errorf("Stopping tail on %q: %v", tailer.Filename, err)
```
Same for the case below.

**Review by srebhan — COMMENTED** [review]
Thanks for the update @skartikey! Looks good to me, just some style comments...

**Review by srebhan — APPROVED** [review]
Thanks @skartikey!
