### PR TITLE
fix(parsers.json_v2): Properly handle optional fields

### LINKED ISSUE #13990: Duplicate lines emitted from `json_v2` when mixing Object and Tag/Field configurations
### Relevant telegraf.conf

```toml
[agent]
omit_hostname = true
flush_interval = "1s"

[[inputs.file]]

  files = ["nested_objects_single.json", "nested_objects_nest.json"]

  data_format = "json_v2"
  
  [[inputs.file.json_v2]]
    timestamp_path = 'timestamp'
    timestamp_format = 'unix_ms'

    [[inputs.file.json_v2.tag]]
      path = 'name'
      optional = true
    [[inputs.file.json_v2.tag]]
      path = 'source'
      optional = true
    [[inputs.file.json_v2.tag]]
      path = 'datatype'
      optional = true
    [[inputs.file.json_v2.field]]
      path = 'value'
      rename = 'value_f'
      optional = true

    [[inputs.file.json_v2.object]]
      path = 'metrics.#(datatype=="float")#'
      optional = true
      tags = ['datatype','source']
      excluded_keys = ['quality']
      [inputs.file.json_v2.object.renames]
        value = 'value_f'
      [inputs.file.json_v2.object.fields]
        value = 'float'
    
    [[inputs.file.json_v2.object]]
      path = 'metrics.#(datatype=="string")#'
      optional = true
      tags = ['datatype','source']
      excluded_keys = ['quality']
      [inputs.file.json_v2.object.renames]
        value = 'value_s'
      [inputs.file.json_v2.object.fields]
        value = 'string'

    [[inputs.file.json_v2.object]]
      path = 'metrics.#(datatype=="int")#'
      optional = true
      tags = ['datatype','source']
      excluded_keys = ['quality']
      [inputs.file.json_v2.object.renames]
        value = 'value_i'
      [inputs.file.json_v2.object.fields]
        value = 'int'

    [[inputs.file.json_v2.object]]
      path = 'metrics.#(datatype=="bool")#'
      optional = true
      tags = ['datatype','source']
      excluded_keys = ['quality']
      [inputs.file.json_v2.object.renames]
        value = 'value_b'
      [inputs.file.json_v2.object.fields]
        value = 'bool'

[[outputs.file]]
  files = ["stdout", "nested_objects_result.txt"]
  data_format = "influx"
```

### Logs from Telegraf

```text
telegraf.exe --debug --config "nested_objects.conf"
2023-09-25T22:17:48Z I! Loading config: .\nested_objects.conf
2023-09-25T22:17:48Z I! Starting Telegraf 1.29.0-080f5a2e brought to you by InfluxData the makers of InfluxDB
2023-09-25T22:17:48Z I! Available plugins: 240 inputs, 9 aggregators, 29 processors, 24 parsers, 59 outputs, 5 secret-stores
2023-09-25T22:17:48Z I! Loaded inputs: file
2023-09-25T22:17:48Z I! Loaded aggregators: 
2023-09-25T22:17:48Z I! Loaded processors: 
2023-09-25T22:17:48Z I! Loaded secretstores: 
2023-09-25T22:17:48Z I! Loaded outputs: file
2023-09-25T22:17:48Z I! Tags enabled: 
2023-09-25T22:17:48Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"", Flush Interval:1s
2023-09-25T22:17:48Z D! [agent] Initializing plugins
2023-09-25T22:17:48Z D! [agent] Connecting outputs
2023-09-25T22:17:48Z D! [agent] Attempting connection to [outputs.file]
2023-09-25T22:17:48Z D! [agent] Successfully connected to outputs.file
2023-09-25T22:17:48Z D! [agent] Starting service inputs
2023-09-25T22:17:49Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-09-25T22:17:50Z D! [parsers.json_v2::file] the path source doesn't exist
2023-09-25T22:17:50Z D! [parsers.json_v2::file] the path metrics.#(datatype=="float")# doesn't exist
2023-09-25T22:17:50Z D! [parsers.json_v2::file] the path metrics.#(datatype=="string")# doesn't exist
2023-09-25T22:17:50Z D! [parsers.json_v2::file] the path metrics.#(datatype=="int")# doesn't exist
2023-09-25T22:17:50Z D! [parsers.json_v2::file] the path metrics.#(datatype=="bool")# doesn't exist
2023-09-25T22:17:50Z D! [parsers.json_v2::file] the path value doesn't exist
2023-09-25T22:17:50Z D! [parsers.json_v2::file] the path name doesn't exist
2023-09-25T22:17:50Z D! [parsers.json_v2::file] the path source doesn't exist
2023-09-25T22:17:50Z D! [parsers.json_v2::file] the path datatype doesn't exist
file,datatype=float,name=inlet-1/temperature value_f=0.20791169081775931 1695679023000000000
file,datatype=float,name=inlet-1/temperature value_f=0.20791169081775931 1695679023000000000
file,datatype=float,name=inlet-1/temperature value_f=0.20791169081775931 1695679023000000000
file,datatype=float,name=inlet-1/temperature value_f=0.20791169081775931 1695679023000000000
file,datatype=float value_f=-0.3090169943749477,name="inlet-1/temperature" 1695679077000000000
file,datatype=string value_s="-0.3090169943749477",name="inlet-3/flow" 1695679077000000000
file,datatype=int value_i=95i,name="inlet-2/temperature" 1695679077000000000
file,datatype=bool value_b=true,name="inlet-2/flow" 1695679077000000000
2023-09-25T22:17:50Z D! [outputs.file] Wrote batch of 8 metrics in 1.6287ms
2023-09-25T22:17:50Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-09-25T22:17:51Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-09-25T22:17:52Z D! [agent] Stopping service inputs
2023-09-25T22:17:52Z D! [agent] Input channel closed
2023-09-25T22:17:52Z I! [agent] Hang on, flushing any cached metrics before shutdown
2023-09-25T22:17:52Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-09-25T22:17:52Z I! [agent] Stopping running outputs
2023-09-25T22:17:52Z D! [agent] Stopped Successfully
```

### System info

Telegraf 1.29.0, Docker and Windows

### Docker

image: telegraf:1.27.4

### Steps to reproduce

1. Create file `nested_objects_single.json`:
```
{
    "timestamp": 1695679022882.0,
    "value": 0.20791169081775931,
    "name": "inlet-1/temperature",
    "datatype": "float"
}
```
2. Create file `nested_objects_nest.json`:
```
{
    "timestamp": 1695679077118.0,
    "metrics": [
        {
            "value": -0.3090169943749477,
            "name": "inlet-1/temperature",
            "datatype": "float"
        },
        {
            "value": 95,
            "name": "inlet-2/temperature",
            "datatype": "int"
        },
        {
            "value": true,
            "name": "inlet-2/flow",
            "datatype": "bool"
        },
        {
            "value": "-0.3090169943749477",
            "name": "inlet-3/flow",
            "datatype": "string"
        }
    ]
}
``` 
4. Run ``telegraf.exe --debug --config "nested_objects.conf"``

### Expected behavior

``json_v2`` processing of the flat JSON structure without an array in ``metrics`` yields a single line:

```
file,datatype=float,name=inlet-1/temperature value_f=0.20791169081775931 1695679023000000000
file,datatype=float value_f=-0.3090169943749477,name="inlet-1/temperature" 1695679077000000000
file,datatype=string value_s="-0.3090169943749477",name="inlet-3/flow" 1695679077000000000
file,datatype=int value_i=95i,name="inlet-2/temperature" 1695679077000000000
file,datatype=bool value_b=true,name="inlet-2/flow" 1695679077000000000
```

### Actual behavior

``json_v2`` processing of the flat JSON structure without an array in ``metrics`` yields four identical lines (equal to the number of ``json_v2.object`` configurations):

```
file,datatype=float,name=inlet-1/temperature value_f=0.20791169081775931 1695679023000000000
file,datatype=float,name=inlet-1/temperature value_f=0.20791169081775931 1695679023000000000
file,datatype=float,name=inlet-1/temperature value_f=0.20791169081775931 1695679023000000000
file,datatype=float,name=inlet-1/temperature value_f=0.20791169081775931 1695679023000000000
file,datatype=float value_f=-0.3090169943749477,name="inlet-1/temperature" 1695679077000000000
file,datatype=string value_s="-0.3090169943749477",name="inlet-3/flow" 1695679077000000000
file,datatype=int value_i=95i,name="inlet-2/temperature" 1695679077000000000
file,datatype=bool value_b=true,name="inlet-2/flow" 1695679077000000000
```

### Additional info

Going through debugging it appears the error is introduced in ``parser.go`` at:

```
if len(objects) != 0 && len(metrics) != 0 {
	metrics = cartesianProduct(objects, metrics)
} else {
	metrics = append(metrics, objects...)
}
```

``objects, err := p.processObjects(input, c.JSONObjects, timestamp)`` returns 4 objects that have no Tag or Field records (only a timestamp), so this product duplicates the correctly Tag/Field parsed JSON.

### PR DESCRIPTION
**Pull request by caallinson**
# Required for all PRs

- [ ] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #13990

Correct `checkResult()` to return error when result does not exist, even if it is optional (other return value already denotes optional for calling logic).

### CODE REVIEW

**Review by powersj — APPROVED** [review]
Thanks for the issue, debug, and PR! It is great to get fixes directly from users.

I will say I am always slightly concerned to make changes to the parsers, given their wide usage, and how users can end up depending on incorrect behavior. However, in this case I do think this new behavior is more correct. I await to see if there is any further fallout.

File: plugins/parsers/json_v2/parser.go [hunk 1]
```diff
@@ -703,9 +703,8 @@ func (p *Parser) convertType(input gjson.Result, desiredType string, name string
 func (p *Parser) checkResult(result gjson.Result, path string, optional bool) (bool, error) {
 	if !result.Exists() {
 		if optional {
-			// If path is marked as optional don't error if path doesn't return a result
 			p.Log.Debugf("the path %q doesn't exist", path)
-			return true, nil
+			return true, fmt.Errorf("the path %q doesn't exist", path)
```
Comment (srebhan) [inline plugins/parsers/json_v2/parser.go:707]: Can we please add a comment here saying that the error is required in order for the `skip` to take effect!? Otherwise someone will change this (because honestly speaking this should not be an error) and will break the code...

**Review by srebhan — COMMENTED** [review]
@caallinson just one request to add a comment... Otherwise the code looks good.

File: plugins/parsers/json_v2/parser.go (hunk 1 above)
Comment (caallinson) [reply plugins/parsers/json_v2/parser.go:707]: Is it cleaner to re-write this function as:

```
// Check if gjson result exists and if a non-existing gjson result can be skipped over
func (p *Parser) checkResult(result gjson.Result, path string, optional bool) (bool, error) {
	if !result.Exists() {
		p.Log.Debugf("the path %q doesn't exist", path)
		return optional, fmt.Errorf("the path %q doesn't exist", path)
	}
	
	return false, nil
}
```

This makes the relationship between the boolean return value and ``optional`` more explicit.

Comment (srebhan) [reply plugins/parsers/json_v2/parser.go:707]: I really love this!

**Comment by caallinson** [comment]
@powersj @srebhan Updated PR from discussion in comments

File: plugins/parsers/json_v2/parser.go [hunk 2]
```diff
@@ -700,15 +700,11 @@ func (p *Parser) convertType(input gjson.Result, desiredType string, name string
 	return input.Value(), nil
 }
 
+// Check if gjson result exists and if a non-existing gjson result can be skipped over
```
Comment (srebhan) [inline plugins/parsers/json_v2/parser.go:703]:
```suggestion
// Check if gjson result exists and if a non-existing gjson result can be skipped over.
// We need to return an error even for optional entities to allow the upstream code
// to take the skipping return value into account.
```

**Review by srebhan — COMMENTED** [review]
@caallinson thanks for improving this code! Suggestion for extending the code to prevent others to change the error back to `nil` for optional entries... What do you think?

File: plugins/parsers/json_v2/parser.go (hunk 2 above)
Comment (caallinson) [reply plugins/parsers/json_v2/parser.go:703]: That makes sense!

Another option is to change ``checkResult()`` into a single error return on ``result.Exists()``. Currently, the other arguments are used either in a log message or just passed back in the return - not a ton of checking done. This could leave ``checkResult()`` to be expanded with other types of error messages in the future, but leave evaluating what to do about an error (skip, error out) to the calling logic.

Calls could be changed to something like:

```
if err := p.checkResult(result, c.Path); err != nil {
	if c.Optional {
		continue
	}
	return nil, err
}
(...)
func (p *Parser) checkResult(result gjson.Result, path string) (error) {
	if !result.Exists() {
		return fmt.Errorf("the path %q doesn't exist", path)
	}

}
```

Adding comment or code change both sound good to me.

Comment (srebhan) [reply plugins/parsers/json_v2/parser.go:703]: Yeah that would be the better option or even condense your code to
```golang
if !result.Exists() {
	if c.Optional {
		continue
	}
	return nil, fmt.Errorf("the path %q doesn't exist", c.Path)
}
```

Comment (caallinson) [reply plugins/parsers/json_v2/parser.go]: Just 4 spots, moved the ``optional`` arg to replace ``skip`` and flattened ``checkResult()``

**Comment by caallinson** [comment]
@srebhan for review

**Review by powersj — APPROVED** [review]
Thanks for working through this!

**Review by srebhan — APPROVED** [review]
Thanks for the amazing work @caallinson!
