### PR TITLE
fix(inputs.diskio): Handle counter wrapping in io fields

### LINKED ISSUE #17408: diskio: new io_* metrics not checking for wraparound
### Relevant telegraf.conf

```toml
[[inputs.diskio]]
```

### Logs from Telegraf

```text
N/A
```

### System info

N/A

### Docker

_No response_

### Steps to reproduce

1. Collect new io_util, io_svctm or io_await metrics via diskio
2. Observe occasionally vast results in the trillions

### Expected behavior

Decimal values under 10

### Actual behavior

Image

### Additional info

This appears to be a counter wraparound issue, and potentially getting extra confused from casting operations,  around about here - https://github.com/influxdata/telegraf/blob/df0b229cf6384022124ff653428ff15df619a4ff/plugins/inputs/diskio/diskio.go#L132

### PR DESCRIPTION
**Pull request by skartikey**
## Summary

Fixes counter wraparound issue in diskio plugin that was causing io_util, io_svctm, and io_await metrics to occasionally produce massive values in the trillions instead of expected decimal values.

**Root cause**: Lines calculating deltas like `deltaIOTime := float64(io.IoTime - lastValue.IoTime)` don't account for counter wraparound scenarios.

### Example
**Before (with bug)**
```
diskio,name=sda reads=1234,writes=5678,read_bytes=987654,io_time=12345,io_util=2847391847382.3,io_await=9847382947.2,io_svctm=8472947.1 
```

**After (during wraparound detection):**
```
diskio,name=sda reads=1234,writes=5678,read_bytes=987654,io_time=12345,io_util=0.0,io_await=0.0,io_svctm=0.0
# Zero values provided instead of trillion-scale incorrect values
```

**After (normal operation resumes):**
```
diskio,name=sda reads=1234,writes=5678,read_bytes=987654,io_time=12345,io_util=15.2,io_await=2.3,io_svctm=1.1
```

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #17408

### CODE REVIEW

File: plugins/inputs/diskio/diskio.go [hunk 1]
```diff
@@ -127,16 +127,32 @@ func (d *DiskIO) Gather(acc telegraf.Accumulator) error {
...
+				if deltaRWCount > 0 {
+					fields["io_await"] = deltaRWTime / deltaRWCount
+					fields["io_svctm"] = deltaIOTime / deltaRWCount
+				}
+
+				itv := float64(collectTime.Sub(d.lastCollectTime).Milliseconds())
+				if itv > 0 {
+					fields["io_util"] = 100 * deltaIOTime / itv
+				}
 			}
```
Comment (srebhan) [inline plugins/inputs/diskio/diskio.go]: @skartikey reading the previous code again it seems that the problem is that the `float64` conversion is done _after_ computation instead of converting the individual values first. So how about

```suggestion
			// Check for wrap around
			wrap := io.ReadCount < lastValue.ReadCount || io.WriteCount < lastValue.WriteCount
			wrap = wrap || io.ReadTime <  lastValue.ReadTime || io.WriteTime < lastValue.WriteTime
			wrap = wrap || io.IoTime < lastValue.IoTime
			if ! wrap {
				deltaRWCount := float64(io.ReadCount - lastValue.ReadCount) + float64(io.WriteCount  - lastValue.WriteCount)
				deltaRWTime := float64(io.ReadTime - lastValue.ReadTime) + float64(io.WriteTime - lastValue.WriteTime)
				deltaIOTime := float64(io.IoTime - lastValue.IoTime)
				fields["io_await"] = deltaRWTime / deltaRWCount
				fields["io_svctm"] = deltaIOTime / deltaRWCount
			}
			itv := float64(collectTime.Sub(d.lastCollectTime).Milliseconds())
			if itv > 0 {
				fields["io_util"] = 100 * deltaIOTime / itv
			}
```

**Review by srebhan — COMMENTED** [review]
Thanks for approaching this @skartikey! A suggestion for a less invasive change...

File: plugins/inputs/diskio/diskio.go (hunk 1 above)
Comment (skartikey) [reply plugins/inputs/diskio/diskio.go]: @srebhan Thanks for the review, I like your approach since it’s simpler, easier to maintain, and follows the proven pattern most monitoring tools use. The direct comparison makes the wrap detection very clear and avoids over-complicating things.

That said, I’m still leaning toward keeping the 0.0 assignment instead of omitting fields, so that we don’t end up with sparse metrics during wrap events.
