### PR TITLE
fix(inputs.systemd_units): Revert to only gather loaded units by default

### LINKED ISSUE #15093: inputs.systemd_units "Error in plugin: listing unit files failed" in v1.30.0 and v1.30.1
### Relevant telegraf.conf

```toml
[[inputs.systemd_units]]
  timeout = "3s"
  unittype = "service"
  interval = "20s"
  [inputs.systemd_units.tags]
    interval_type = "r0"
```

### Logs from Telegraf

```text
2024-04-02T17:15:00Z E! [inputs.systemd_units] Error in plugin: listing unit files failed: Rejected send message, 2 matched rules; type="method_call", sender=":1.584082" (uid=1003 pid=387836 comm="/usr/bin/telegraf -config /etc/telegraf/telegraf.c") interface="org.freedesktop.systemd1.Manager" member="ListUnitFilesByPatterns" error name="(unset)" requested_reply="0" destination="org.freedesktop.systemd1" (uid=0 pid=1 comm="/usr/lib/systemd/systemd --switched-root --system ")
```

### System info

OS: Centos 7, running systemd 219

### Docker

(OS details)
```
$ systemctl --version
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN

$ ps -ef  |grep dbus
dbus        1537       1  0 Mar26 ?        00:09:36 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
```

### Steps to reproduce

1. Configure telegraf with above input on Centos 7 host
2. Launch telegraf
3. Note logged errors
...

### Expected behavior

Expect no error for `inputs.systemd_units` plugin. :) 

### Actual behavior

Telegraf runs with other configured inputs normally, but fails to collect/send `inputs.systemd_units` data.

### Additional info

This bug follows https://github.com/influxdata/telegraf/issues/14980.

### LINKED ISSUE #15104: [inputs.systemd_units] cpu usage goes through the roof!
### Relevant telegraf.conf

```toml
[[inputs.systemd_units]]
```

### Logs from Telegraf

```text
-
```

### System info

Ubuntu 22.04

### Docker

_No response_

### Steps to reproduce

Start telegraf with [inputs.systemd_units] used.

### Expected behavior

Same cpu usage as before.

### Actual behavior

With the new implementation of systemd_units, every time telegraf runs (which is every 10s), a systemd process eats a lot of cpu.

Attached 2 picture of grafana graphs, I think you can guess when I upgraded to 1.30.1. I've just reverted it back again to 1.29.5-1.

Screenshot from 2024-04-04 16-35-19

Screenshot from 2024-04-04 16-35-41

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by srebhan**
## Summary

With PR #14814 we also produce metrics for unloaded units. However, for unspecific filters (like `*` being the default) this touches a lot of files and forces systemd to lookup those unit-files which is expensive.

Therefore, this PR reverts the behavior to pre-v1.30.0 versions and only collects units already loaded by systemd. To allow collecting disabled/unloaded units you can use the new `collect_disabled_units`.

Additionally to this change, the PR also optimizes the interaction with systemd for cases where non-detailed metrics are requested.

This leads to the following improvements when gathering _all_ units (`pattern = "*"`) in non-detailed mode
```
goos: linux
goarch: amd64
pkg: github.com/influxdata/telegraf/plugins/inputs/systemd_units
cpu: AMD Ryzen 7 3700X 8-Core Processor 
```
|version|performance|improvement|
|---|---:|---:|
| v1.30.0 reference | 2,021,195,198 ns/op | 1.0x |
| all units including non-loaded |  700,185,759 ns/op | 2.9x |
| only loaded units (default) | 5,754,030  ns/op | **351.3x**|

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #15104 
resolves #15093

### CODE REVIEW

**Review by powersj — COMMENTED** [review]
Thanks for jumping on this. As a PR this looks fine, but I'm still concerned that the usage is still higher than it used to be. Do we need to have this new method be opt-in?

**Comment by srebhan** [comment]
@1tft FYI: This PR disables collection of non-loaded/disabled units by default, so in case you need them please use the new `collect_disabled_units` option! Would be cool if you can test this in your environment...

File: plugins/inputs/systemd_units/systemd_units_linux.go [hunk 1]
```diff
@@ -362,17 +329,43 @@ func (s *SystemdUnits) Gather(acc telegraf.Accumulator) error {
...
-			fields["mem_peak"] = u.properties["MemoryPeak"]
-			fields["swap_current"] = u.properties["MemorySwapCurrent"]
-			fields["swap_peak"] = u.properties["MemorySwapPeak"]
-			fields["mem_avail"] = u.properties["MemoryAvailable"]
+			properties, err := s.client.GetUnitTypePropertiesContext(ctx, state.Name, s.unitTypeDBus)
+			if err != nil {
+				// Skip units returning "Unknown interface" errors as those indicate
+				// that the unit is of the wrong type.
+				if strings.Contains(err.Error(), "Unknown interface") {
+					fmt.Println("mismatch in", state.Name)
```
Comment (powersj) [inline plugins/inputs/systemd_units/systemd_units_linux.go:337]: Println? not an error, warning, or debug?

**Review by powersj — COMMENTED** [review]
Thank you - one question about a println statement?

**Comment by 1tft** [comment]
@srebhan Thank you so much for keeping that feature alive. With this build and `collect_disabled_units = true` we can collect metrics for unloaded units.
Only one remark for Readme: Maybe you should also mention that `collect_disabled_units = true` activates metrics for systemd_units with _state=disabled_ **AND** with _state=static_.

**Review by powersj — APPROVED** [review]
Thank you!

**Review by DStrand1 — APPROVED** [review]
