### PR TITLE
[output dynatrace] Initialize loggedMetrics map

### LINKED ISSUE #9437: Dynatrace > loggedMetrics map is never initialized.
Since d. loggedMetrics is never initialized, the following line causes a runtime panic.
https://github.com/influxdata/telegraf/blob/ed412d7f9cd4fd45693d77604140aa286adb3581/plugins/outputs/dynatrace/dynatrace.go#L132

Stacktrace:
`   2021-06-25T10:30:00.68+0530 [APP/PROC/WEB/0] ERR panic: assignment to entry in nil map
   2021-06-25T10:30:00.68+0530 [APP/PROC/WEB/0] ERR goroutine 505 [running]:
   2021-06-25T10:30:00.68+0530 [APP/PROC/WEB/0] ERR github.com/influxdata/telegraf/plugins/outputs/dynatrace.(*Dynatrace).Write(0xc00061a000, 0xc00de1e000, 0x3e8, 0x3e8, 0xc00de1e000, 0xc00b828700)
   2021-06-25T10:30:00.68+0530 [APP/PROC/WEB/0] ERR 	/go/src/github.com/influxdata/telegraf/plugins/outputs/dynatrace/dynatrace.go:132 +0xc9c
   2021-06-25T10:30:00.68+0530 [APP/PROC/WEB/0] ERR github.com/influxdata/telegraf/models.(*RunningOutput).write(0xc000206080, 0xc00de1e000, 0x3e8, 0x3e8, 0x3e8, 0x100010000)
   2021-06-25T10:30:00.68+0530 [APP/PROC/WEB/0] ERR 	/go/src/github.com/influxdata/telegraf/models/running_output.go:244 +0x99
   2021-06-25T10:30:00.68+0530 [APP/PROC/WEB/0] ERR github.com/influxdata/telegraf/models.(*RunningOutput).WriteBatch(0xc000206080, 0xc0006ca140, 0xc00ce34360)
   2021-06-25T10:30:00.68+0530 [APP/PROC/WEB/0] ERR 	/go/src/github.com/influxdata/telegraf/models/running_output.go:218 +0x85
   2021-06-25T10:30:00.68+0530 [APP/PROC/WEB/0] ERR github.com/influxdata/telegraf/agent.(*Agent).flushOnce.func1(0xc00b116900, 0xc00b110490)
   2021-06-25T10:30:00.68+0530 [APP/PROC/WEB/0] ERR 	/go/src/github.com/influxdata/telegraf/agent/agent.go:825 +0x27
   2021-06-25T10:30:00.68+0530 [APP/PROC/WEB/0] ERR created by github.com/influxdata/telegraf/agent.(*Agent).flushOnce
   2021-06-25T10:30:00.68+0530 [APP/PROC/WEB/0] ERR 	/go/src/github.com/influxdata/telegraf/agent/agent.go:824 +0x7a`

### PR DESCRIPTION
**Pull request by dyladan**
Fixes #9437

~~- [ ] Updated associated README.md.~~ n/a
- [x] Wrote appropriate unit tests.

### CODE REVIEW

File: plugins/outputs/dynatrace/dynatrace_test.go [hunk 1]
```diff
@@ -515,3 +515,36 @@ func TestSendCounterMetricWithoutTags(t *testing.T) {
...
+		map[string]interface{}{"unsupported": "type"},
+		time.Date(2010, time.November, 10, 23, 0, 0, 0, time.UTC),
+	)
+
+	metrics := []telegraf.Metric{m1}
+
+	err = d.Write(metrics)
+	require.NoError(t, err)
+
+	require.Equal(t, true, d.loggedMetrics["mymeasurement.unsupported"])
```
Comment (arminru) [inline plugins/outputs/dynatrace/dynatrace_test.go:549]: This shows that the key ends up in the map but doesn't prove it's actually used anywhere. Ideally try exporting the same metric once again and check that we only create one log message to avoid log spam.

**Review by arminru — APPROVED** [review]

File: plugins/outputs/dynatrace/dynatrace_test.go (hunk 1 above)
Comment (dyladan) [reply plugins/outputs/dynatrace/dynatrace_test.go]: Updated the test

File: plugins/outputs/dynatrace/dynatrace_test.go [hunk 2]
```diff
@@ -515,3 +515,52 @@ func TestSendCounterMetricWithoutTags(t *testing.T) {
...
+
+	metrics := []telegraf.Metric{m1}
+
+	err = d.Write(metrics)
+	require.NoError(t, err)
+	require.Equal(t, 1, warnfCalledTimes)
+
+	err = d.Write(metrics)
+	require.NoError(t, err)
+	require.Equal(t, 1, warnfCalledTimes)
```
Comment (arminru) [inline plugins/outputs/dynatrace/dynatrace_test.go:565]:
```suggestion
	require.Equal(t, 1, warnfCalledTimes) // each metric name is logged only once
```
To make it more obvious.

**Review by arminru — APPROVED** [review]

File: plugins/outputs/dynatrace/dynatrace_test.go [hunk 3]
```diff
@@ -515,3 +515,73 @@ func TestSendCounterMetricWithoutTags(t *testing.T) {
...
+	require.NoError(t, err)
+	err = d.Connect()
+	require.NoError(t, err)
+
+	// Init metrics
+
+	m1 := metric.New(
+		"mymeasurement",
+		map[string]string{},
+		map[string]interface{}{"1": "unsupported_type"},
```
Comment (arminru) [inline plugins/outputs/dynatrace/dynatrace_test.go:553]:
```suggestion
		map[string]interface{}{"metric1": "unsupported_type"},
```
Otherwise it looks at first like "mymeasurement" was the metric name and "1" the stringified value.

File: plugins/outputs/dynatrace/dynatrace_test.go [hunk 4]
```diff
@@ -515,3 +515,73 @@ func TestSendCounterMetricWithoutTags(t *testing.T) {
...
+
+	err = d.Write(metrics)
+	require.NoError(t, err)
+	// Warnf skipped for more invalid exports with the same name
+	require.Equal(t, 1, warnfCalledTimes)
+
+	m2 := metric.New(
+		"mymeasurement",
+		map[string]string{},
+		map[string]interface{}{"2": "unsupported_type"},
```
Comment (arminru) [inline plugins/outputs/dynatrace/dynatrace_test.go:572]:
```suggestion
		map[string]interface{}{"metric2": "unsupported_type"},
```

**Review by arminru — APPROVED** [review]

**Review by SathishKumarRamasamy — APPROVED** [review]

**Comment by dyladan** [comment]
Hello. This fixes a crashing bug so I would appreciate if it can be reviewed and merged asap. Thanks!

**Comment by dyladan** [comment]
Any update here?

**Review by helenosheaa — APPROVED** [review]

**Review by MyaLongmire — APPROVED** [review]
