### PR TITLE
Close running outputs when reloading

### LINKED ISSUE #8185: Reload configuration with `kill -HUP` fail to reload prometheus output
Note: I can't reproduce this with `1.14.5` but it's start show up in `1.15.1` (couldn't try with 1.15.0 as there is no docker image for it).

Config file:

```
[agent]
  omit_hostname = true
  logtarget = "stderr"

[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2

[[inputs.internal]]
  collect_memstats = true
```

I start `telegraf --pidfile=/var/run/telegraf.pid --config=/etc/telegraf/telegraf.conf`

```
2020-09-28T06:20:44Z I! Starting Telegraf 1.15.3
2020-09-28T06:20:44Z I! Loaded inputs: internal
2020-09-28T06:20:44Z I! Loaded aggregators: 
2020-09-28T06:20:44Z I! Loaded processors: 
2020-09-28T06:20:44Z I! Loaded outputs: prometheus_client
2020-09-28T06:20:44Z I! Tags enabled: 
2020-09-28T06:20:44Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"", Flush Interval:10s
2020-09-28T06:20:44Z I! [outputs.prometheus_client] Listening on http://[::]:9273/metrics
2020-09-28T06:23:14Z I! Reloading Telegraf config
2020-09-28T06:23:14Z I! [agent] Hang on, flushing any cached metrics before shutdown
2020-09-28T06:23:14Z I! Starting Telegraf 1.15.3
2020-09-28T06:23:14Z I! Loaded inputs: internal
2020-09-28T06:23:14Z I! Loaded aggregators: 
2020-09-28T06:23:14Z I! Loaded processors: 
2020-09-28T06:23:14Z I! Loaded outputs: prometheus_client
2020-09-28T06:23:14Z I! Tags enabled: 
2020-09-28T06:23:14Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"", Flush Interval:10s
```

Later I restart with: `kill -HUP "$(cat /var/run/telegraf.pid)"`

```
2020-09-28T06:23:14Z E! [agent] Failed to connect to [outputs.prometheus_client], retrying in 15s, error was 'listen tcp :9273: bind: address already in use'
2020-09-28T06:23:29Z E! [telegraf] Error running agent: connecting output outputs.prometheus_client: Error connecting to output "outputs.prometheus_client": listen tcp :9273: bind: address already in use
```

and process exit

### LINKED ISSUE #8726: SIGHUP config reload broken for prometheus_client
cant reload the configuration via sighup on anything newer than 1.14.5 with prometheus_client enabled.

```
2021-01-21T00:43:13Z I! Reloading Telegraf config
2021-01-21T00:43:13Z I! [agent] Hang on, flushing any cached metrics before shutdown
2021-01-21T00:43:13Z I! Starting Telegraf 1.16.3
2021-01-21T00:43:13Z I! Loaded inputs: dns_query (2x)
2021-01-21T00:43:13Z I! Loaded aggregators:
2021-01-21T00:43:13Z I! Loaded processors:
2021-01-21T00:43:13Z I! Loaded outputs: prometheus_client
2021-01-21T00:43:13Z I! Tags enabled: host=${NODE_NAME}
2021-01-21T00:43:13Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"${NODE_NAME}", Flush Interval:10s
2021-01-21T00:43:13Z E! [agent] Failed to connect to [outputs.prometheus_client], retrying in 15s, error was 'listen tcp :9273: bind: address already in use'
2021-01-21T00:43:28Z E! [telegraf] Error running agent: connecting output outputs.prometheus_client: Error connecting to output "outputs.prometheus_client": listen tcp :9273: bind: address already in use
```

```
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = "${NODE_NAME}"
  omit_hostname = false

[[outputs.prometheus_client]]
  listen = ":9273"
  path = "/metrics"
  metric_version = 2

  # expiration_interval = "60s"
  collectors_exclude = ["gocollector", "process"]
  export_timestamp = false
```

### PR DESCRIPTION
**Pull request by viperstars**
closes #8726, closes #8185

As we know, telegraf will reload when getting a SIGHUP signal. If we go deeper into the reload loop, we can see "runAgent" is called without closing running outputs.

This will cause some issues like reload failure and connection leaking.

- Reload failure

1. Add prometheus configuration
```
[[outputs.prometheus_client]]
  listen = ":9273"
  path = "/metrics"
  metric_version = 2
```

2. Send a SIGHUP to the process

3. We will get the "address already in use" error:
```
2021-01-28T08:47:59Z I! Starting Telegraf 
2021-01-28T08:47:59Z I! Loaded inputs: x509_cert
2021-01-28T08:47:59Z I! Loaded aggregators: 
2021-01-28T08:47:59Z I! Loaded processors: 
2021-01-28T08:47:59Z I! Loaded outputs: prometheus_client
2021-01-28T08:47:59Z I! Tags enabled: host=Zachary-MBP.local
2021-01-28T08:47:59Z I! [agent] Config: Interval:20s, Quiet:false, Hostname:"Zachary-MBP.local", Flush Interval:20s
2021-01-28T08:47:59Z I! [outputs.prometheus_client] Listening on http://[::]:9273/metrics
2021-01-28T08:48:12Z I! Reloading Telegraf config
2021-01-28T08:48:12Z I! [agent] Hang on, flushing any cached metrics before shutdown
2021-01-28T08:48:12Z I! Starting Telegraf 
2021-01-28T08:48:12Z I! Loaded inputs: x509_cert
2021-01-28T08:48:12Z I! Loaded aggregators: 
2021-01-28T08:48:12Z I! Loaded processors: 
2021-01-28T08:48:12Z I! Loaded outputs: prometheus_client
2021-01-28T08:48:12Z I! Tags enabled: host=Zachary-MBP.local
2021-01-28T08:48:12Z I! [agent] Config: Interval:20s, Quiet:false, Hostname:"Zachary-MBP.local", Flush Interval:20s
2021-01-28T08:48:12Z E! [agent] Failed to connect to [outputs.prometheus_client], retrying in 15s, error was 'listen tcp :9273: bind: address already in use'
2021-01-28T08:48:27Z E! [telegraf] Error running agent: connecting output outputs.prometheus_client: Error connecting to output "outputs.prometheus_client": listen tcp :9273: bind: address already in use
```

- Connection leaking 

1. Add influxdb output 
```
[[outputs.influxdb_v2]]
urls = ["http://127.0.0.1:8086"]
```

2. Sent SIGHUP several times.

3. We can find more than one tcp connection to influxdb server:
```
Zachary-MBP:telegraf zachary$ lsof -p 34680
COMMAND    PID    USER   FD     TYPE             DEVICE  SIZE/OFF                NODE NAME
telegraf 34680 zachary  cwd      DIR                1,4      1408            26952554 /Users/zachary/Projects/golang/telegraf
telegraf 34680 zachary  txt      REG                1,4 117061680            27081706 /Users/zachary/Projects/golang/telegraf/telegraf
telegraf 34680 zachary  txt      REG                1,4     34032            24991620 /Library/Preferences/Logging/.plist-cache.eRVHsOgp
telegraf 34680 zachary  txt      REG                1,4     62747            26934247 /private/var/db/analyticsd/events.whitelist
telegraf 34680 zachary  txt      REG                1,4   2528384 1152921500312783762 /usr/lib/dyld
telegraf 34680 zachary  txt      REG                1,4  30148944 1152921500312795328 /usr/share/icu/icudt66l.dat
telegraf 34680 zachary    0u     CHR               16,1   0t14589                1483 /dev/ttys001
telegraf 34680 zachary    1u     CHR               16,1   0t14589                1483 /dev/ttys001
telegraf 34680 zachary    2u     CHR               16,1   0t14589                1483 /dev/ttys001
telegraf 34680 zachary    3     PIPE 0xdbb151f6d2284bc1     16384                     ->0x500c3504a5abf149
telegraf 34680 zachary    4     PIPE 0x500c3504a5abf149     16384                     ->0xdbb151f6d2284bc1
telegraf 34680 zachary    5u  KQUEUE                                                  count=0, state=0xa
telegraf 34680 zachary    6     PIPE 0x7060bc4282b87de5     16384                     ->0x58c782c11bf250d
telegraf 34680 zachary    7     PIPE  0x58c782c11bf250d     16384                     ->0x7060bc4282b87de5
telegraf 34680 zachary    8u    unix 0xba652578907083cf       0t0                     ->0xba6525787cd608e7
telegraf 34680 zachary    9r     CHR               17,1    0t4096                 593 /dev/urandom
telegraf 34680 zachary   10u    IPv4 0xba6525789e21f5d7       0t0                 TCP localhost:64693->localhost:8086 (ESTABLISHED)
telegraf 34680 zachary   11u    IPv4 0xba65257897816267       0t0                 TCP localhost:64841->localhost:8086 (ESTABLISHED)
telegraf 34680 zachary   12u    IPv4 0xba65257888979267       0t0                 TCP localhost:64847->localhost:8086 (ESTABLISHED)
telegraf 34680 zachary   13u    IPv4 0xba6525789ad5b267       0t0                 TCP localhost:64853->localhost:8086 (ESTABLISHED)
telegraf 34680 zachary   14u    IPv4 0xba65257898eb0fef       0t0                 TCP localhost:64859->localhost:8086 (ESTABLISHED)
telegraf 34680 zachary   15u    IPv4 0xba6525789e129697       0t0                 TCP localhost:64865->localhost:8086 (ESTABLISHED)
telegraf 34680 zachary   16u    IPv4 0xba6525789ad5d0af       0t0                 TCP localhost:64870->localhost:8086 (ESTABLISHED)
telegraf 34680 zachary   17u    IPv4 0xba6525788bc6f267       0t0                 TCP localhost:64876->localhost:8086 (ESTABLISHED)
telegraf 34680 zachary   18u    IPv4 0xba6525789e13fc7f       0t0                 TCP localhost:64884->localhost:8086 (ESTABLISHED)
```
4. This issue was mentioned before. "client.Close()" was add in the influxdb output, but "(i *InfluxDB) Close()" method is never called during the reload.

I add some code to fix this.

### Required for all PRs:

- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

File: cmd/telegraf/telegraf.go [hunk 1]
```diff
@@ -106,8 +107,16 @@ func reloadLoop(
 				cancel()
 			}
 		}()
-
-		err := runAgent(ctx, inputFilters, outputFilters)
+		if ag != nil {
```
Comment (Jagularr) [inline cmd/telegraf/telegraf.go:110]: these two ifs can be combined with an &&

File: cmd/telegraf/telegraf.go [hunk 2]
```diff
@@ -106,8 +107,16 @@ func reloadLoop(
...
+			if ag.Config != nil {
+				for idx := range ag.Config.Outputs {
+					log.Printf("I! Closing running input: %s", ag.Config.Outputs[idx].LogName())
```
Comment (Jagularr) [inline cmd/telegraf/telegraf.go:113]: did you mean "output" ?

Comment (viperstars) [reply cmd/telegraf/telegraf.go]: Yes, it should be "output", my fault🤣

File: cmd/telegraf/telegraf.go [hunk 3]
```diff
@@ -117,44 +124,46 @@ func reloadLoop(
 func runAgent(ctx context.Context,
 	inputFilters []string,
 	outputFilters []string,
-) error {
+) (*agent.Agent, error) {
+	var ag *agent.Agent
+	var err error
```
Comment (srebhan) [inline cmd/telegraf/telegraf.go:129]: I think you can initialize error as before.

File: cmd/telegraf/telegraf.go [hunk 4]
```diff
@@ -117,44 +124,46 @@ func reloadLoop(
 func runAgent(ctx context.Context,
 	inputFilters []string,
 	outputFilters []string,
-) error {
+) (*agent.Agent, error) {
+	var ag *agent.Agent
```
Comment (srebhan) [inline cmd/telegraf/telegraf.go:128]: This line will shadow the global variable. In general I don't see the point of returning the agent only to afterwards set a global variable to this return value. You can cook down the whole patch quite a bit if you set the global variable in here directly.

File: cmd/telegraf/telegraf.go [hunk 5]
```diff
@@ -76,6 +76,7 @@ var (
 )
 
 var stop chan struct{}
+var ag *agent.Agent
```
Comment (srebhan) [inline cmd/telegraf/telegraf.go:79]: Not sure I like a two-letter abbreviation for a global variable. :-/

**Review by srebhan — COMMENTED** [review]
Please set the global agent variable directly from within`runAgent()` and please also think about a better name for the global variable. How about `runningAgent` or something.

**Comment by viperstars** [comment]
> Please set the global agent variable directly from within`runAgent()` and please also think about a better name for the global variable. How about `runningAgent` or something.

I initalize a global variable named "runningAgent".  Move closing outputs into the `runAgent()` before call `agent.NewAgent(c)`

File: cmd/telegraf/telegraf.go [hunk 6]
```diff
@@ -152,32 +152,39 @@ func runAgent(ctx context.Context,
...
 
-	ag, err := agent.NewAgent(c)
+	if runningAgent != nil && runningAgent.Config != nil {
+		for idx := range runningAgent.Config.Outputs {
+			log.Printf("I! Closing running output: %s", runningAgent.Config.Outputs[idx].LogName())
+			runningAgent.Config.Outputs[idx].Close()
+		}
+	}
+
+	runningAgent, err = agent.NewAgent(c)
```
Comment (srebhan) [inline cmd/telegraf/telegraf.go:162]: Please also set `runningAgent = nil` in case of an error. Otherwise we might run into trouble if the agent address is a leftover from a previous run...

**Review by srebhan — COMMENTED** [review]
This looks very good already. Just one more minor request, please set the agent to a defined state in case of `agent.NewAgent()` fails. I know this call cannot fail currently, but it might fail in the future and I don't want to introduce later hard-to-find issues by assuming the above function to return something sensible in case of error.

**Review by srebhan — APPROVED** [review]
Looks good to me.

**Comment by viperstars** [comment]
related issue: #8726 #8185

**Comment by srebhan** [comment]
@viperstars can you please add `closes #8726, #8185` to your PR description to allow automatic closing of the tickets!?

**Review by srebhan — APPROVED** [review]
Fine with me.

**Review by ssoroka — CHANGES_REQUESTED** [review]
This is not the right approach. The change has to be internal to the agent after the output has finished processing its writes.

**Comment by viperstars** [comment]
> This is not the right approach. The change has to be internal to the agent after the output has finished processing its writes.

After I go through the code, I think the outputs will be flushed when get the SIGHUP signal.

1. reloadLoop will cancel the context when get SIGHUP signal
```go
func reloadLoop(
	inputFilters []string,
	outputFilters []string,
	aggregatorFilters []string,
	processorFilters []string,
) {
	reload := make(chan bool, 1)
	reload <- true
	for <-reload {
		reload <- false

		ctx, cancel := context.WithCancel(context.Background())

		signals := make(chan os.Signal, 1)
		signal.Notify(signals, os.Interrupt, syscall.SIGHUP,
			syscall.SIGTERM, syscall.SIGINT)
		go func() {
			select {
			case sig := <-signals:
				if sig == syscall.SIGHUP {
					log.Printf("I! Reloading Telegraf config")
					<-reload
					reload <- true
				}
				cancel() // cancel the context
			case <-stop:
				cancel()
			}
		}()
		err := runAgent(ctx, inputFilters, outputFilters)
		if err != nil && err != context.Canceled {
			log.Fatalf("E! [telegraf] Error running agent: %v", err)
		}
	}
}
```

2. gatherLoop will be stopped and input channel will be closed
```
func (a *Agent) runInputs(
	ctx context.Context,
	startTime time.Time,
	unit *inputUnit,
) error {
	var wg sync.WaitGroup
	for _, input := range unit.inputs {
		// Overwrite agent interval if this plugin has its own.
		interval := a.Config.Agent.Interval.Duration
		if input.Config.Interval != 0 {
			interval = input.Config.Interval
		}

		// Overwrite agent precision if this plugin has its own.
		precision := a.Config.Agent.Precision.Duration
		if input.Config.Precision != 0 {
			precision = input.Config.Precision
		}

		// Overwrite agent collection_jitter if this plugin has its own.
		jitter := a.Config.Agent.CollectionJitter.Duration
		if input.Config.CollectionJitter != 0 {
			jitter = input.Config.CollectionJitter
		}

		var ticker Ticker
		if a.Config.Agent.RoundInterval {
			ticker = NewAlignedTicker(startTime, interval, jitter)
		} else {
			ticker = NewUnalignedTicker(interval, jitter)
		}
		defer ticker.Stop()

		acc := NewAccumulator(input, unit.dst)
		acc.SetPrecision(getPrecision(precision, interval))

		wg.Add(1)
		go func(input *models.RunningInput) {
			defer wg.Done()
			a.gatherLoop(ctx, acc, input, ticker, interval) // all gatherLoop will be stopped
		}(input)
	}

	wg.Wait()

	log.Printf("D! [agent] Stopping service inputs")
	stopServiceInputs(unit.inputs)

	close(unit.dst)  // input channel will be closed
	log.Printf("D! [agent] Input channel closed")

	return nil
}
```

3. input channel closed will cause the context canceled
```
func (a *Agent) runOutputs(
	unit *outputUnit,
) error {
	var wg sync.WaitGroup

	// Start flush loop
	interval := a.Config.Agent.FlushInterval.Duration
	jitter := a.Config.Agent.FlushJitter.Duration

	ctx, cancel := context.WithCancel(context.Background())

	for _, output := range unit.outputs {
		interval := interval
		// Overwrite agent flush_interval if this plugin has its own.
		if output.Config.FlushInterval != 0 {
			interval = output.Config.FlushInterval
		}

		jitter := jitter
		// Overwrite agent flush_jitter if this plugin has its own.
		if output.Config.FlushJitter != 0 {
			jitter = output.Config.FlushJitter
		}

		wg.Add(1)
		go func(output *models.RunningOutput) {
			defer wg.Done()

			ticker := NewRollingTicker(interval, jitter)
			defer ticker.Stop()

			a.flushLoop(ctx, output, ticker) // all flushLoop will flush before return
		}(output)
	}

	for metric := range unit.src { // input channel closed
		for i, output := range unit.outputs {
			if i == len(a.Config.Outputs)-1 {
				output.AddMetric(metric)
			} else {
				output.AddMetric(metric.Copy())
			}
		}
	}

	log.Println("I! [agent] Hang on, flushing any cached metrics before shutdown")
	cancel() // context cancel
	wg.Wait()

	return nil
}
```

4. all flushLoop will flush before return
```
func (a *Agent) flushLoop(
	ctx context.Context,
	output *models.RunningOutput,
	ticker Ticker,
) {
	logError := func(err error) {
		if err != nil {
			log.Printf("E! [agent] Error writing to %s: %v", output.LogName(), err)
		}
	}

	// watch for flush requests
	flushRequested := make(chan os.Signal, 1)
	watchForFlushSignal(flushRequested)
	defer stopListeningForFlushSignal(flushRequested)

	for {
		// Favor shutdown over other methods.
		select {
		case <-ctx.Done(): 
			logError(a.flushOnce(output, ticker, output.Write)) // context is canceled, each output will be flushed 
			return
		default:
		}

		select {
		case <-ctx.Done():
			logError(a.flushOnce(output, ticker, output.Write))
			return
		case <-ticker.Elapsed():
			logError(a.flushOnce(output, ticker, output.Write))
		case <-flushRequested:
			logError(a.flushOnce(output, ticker, output.Write))
		case <-output.BatchReady:
			// Favor the ticker over batch ready
			select {
			case <-ticker.Elapsed():
				logError(a.flushOnce(output, ticker, output.Write))
			default:
				logError(a.flushOnce(output, ticker, output.WriteBatch))
			}
		}
	}
}
```

So I think it is not necessary to flush the output before closing, it is already done.

File: agent/agent.go [hunk 7]
```diff
@@ -447,6 +447,17 @@ func stopServiceInputs(inputs []*models.RunningInput) {
 	}
 }
 
+// stopRunningOutputs stops all running outputs.
+func stopRunningOutputs(outputs []*models.RunningOutput) {
+	for _, output := range outputs {
```
Comment (srebhan) [inline agent/agent.go:452]: You might want to close the outputs in parallel!?

File: agent/agent.go [hunk 8]
```diff
@@ -785,6 +796,9 @@ func (a *Agent) runOutputs(
 	cancel()
 	wg.Wait()
 
+	log.Printf("I [agent] Stopping running outputs")
+	stopRunningOutputs(unit.outputs)
```
Comment (srebhan) [inline agent/agent.go:800]: Can't you close the outputs in `a.flushLoop()` in the loop above?

Comment (ssoroka) [reply agent/agent.go:800]: I'd rather close it here.

File: agent/agent.go (hunk 7 above)
Comment (ssoroka) [reply agent/agent.go:452]: I don't think that's necessary.

File: agent/agent.go [hunk 9]
```diff
@@ -447,6 +447,17 @@ func stopServiceInputs(inputs []*models.RunningInput) {
 	}
 }
 
+// stopRunningOutputs stops all running outputs.
+func stopRunningOutputs(outputs []*models.RunningOutput) {
+	for _, output := range outputs {
+		log.Printf("I! [agent] stop running output: %s", output.LogName())
```
Comment (ssoroka) [inline agent/agent.go:453]:
```suggestion
```

**Review by ssoroka — APPROVED** [review]
much better, thank you!

**Review by srebhan — COMMENTED** [review]
Fine with me if you remove the extra log-message as @ssoroka requested/suggested.

File: agent/agent.go (hunk 9 above)
Comment (viperstars) [reply agent/agent.go]: I have removed this log message and I think is better to call "output.Close()" instead of "output.Output.Close()"

**Review by srebhan — COMMENTED** [review]
Sorry for one more request, but can you move the body of `stopRunningOutputs()` to the location of the function call. That is dissolve  `stopRunningOutputs()`  and fold into the `gatherLoop()` function. It's only a `for` loop that survived, wrapping it in a function is not worth it.

**Comment by viperstars** [comment]
> Sorry for one more request, but can you move the body of `stopRunningOutputs()` to the location of the function call. That is dissolve `stopRunningOutputs()` and fold into the `gatherLoop()` function. It's only a `for` loop that survived, wrapping it in a function is not worth it.

I think we should keep it. I add "stopRunningOutputs" based on the existing function "stopServiceInputs". These two functions work in the same way, so the definition and call should be same.

**Review by srebhan — APPROVED** [review]
Agreed. Looks good to me. @ssoroka any comments?
