### PR TITLE
fix(inputs.mongodb): Fix connection leak

### LINKED ISSUE #12336: connections leak triggered by auto reload config mechanism
### Relevant telegraf.conf

```toml
[agent]
interval = "30s"
round_interval = false
metric_batch_size = 1000
metric_buffer_limit = 10000
collection_jitter = "0s"
flush_interval = "10s"
flush_jitter = "0s"
precision = "s"
debug = false
quiet = true
logtarget = ""
logfile = ""logfile_rotation_max_archives = 5
hostname = ""
omit_hostname = false

[global_tags]
point_id = "600a95a2db699236fd60a192"

[[inputs.mongodb]]
servers = ["mongodb://xxx:xxx@127.0.0.1:27017"]
gather_cluster_status = true
gather_perdb_stats = true
gather_col_stats = false

[inputs.mongodb.tags]
task_id = "638ded70b4e458e6bb962ebe"
task_name = "test"
```

### Logs from Telegraf

```text
much mongo connections from telegraf
```

### System info

telegraf master centos8

### Docker

_No response_

### Steps to reproduce

1.  ./telegraf --config=./telegraf.conf --watch-config=notify
2. loop change config file: echo "" >> ./telegraf.conf 

### Expected behavior

every time file changed, release previous mongo connections

### Actual behavior

every time file changed, lead to connections leak

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by zhiyuan-mojie**
# Required for all PRs

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format]

resolves #12336
Fixed an mongo connections leak triggered by auto reload config mechanism.

### CODE REVIEW

**Comment by powersj** [comment]
Thanks for the PR! Can you fix the lint issue?

File: plugins/inputs/mongodb/mongodb.go [hunk 1]
```diff
@@ -144,7 +144,17 @@ func (m *MongoDB) Start(telegraf.Accumulator) error {
...
-func (m *MongoDB) Stop() {}
+// Stop disconnect mongo connections when stop or reload
+func (m *MongoDB) Stop() {
+	for _, server := range m.clients {
+		// prefer not to defer inside loops
+		func() {
+			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
+			defer cancel()
+			_ = server.client.Disconnect(ctx)
+		}()
```
Comment (powersj) [inline plugins/inputs/mongodb/mongodb.go:155]: Hi - any reason we cannot just do the following?

```suggestion
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		_ = server.client.Disconnect(ctx)
		cancel()
```

Comment (zhiyuan-mojie) [reply plugins/inputs/mongodb/mongodb.go:155]: > Hi - any reason we cannot just do the following?

using defer can ensure that the cancel method can been executed even if the following code raise panic.

Comment (powersj) [reply plugins/inputs/mongodb/mongodb.go:155]: Yeah, if we panic we've already lost :)

Comment (zhiyuan-mojie) [reply plugins/inputs/mongodb/mongodb.go]: got it

**Review by powersj — APPROVED** [review]
Thank you for taking the time to put up a PR!

File: plugins/inputs/mongodb/mongodb.go [hunk 2]
```diff
@@ -144,7 +144,14 @@ func (m *MongoDB) Start(telegraf.Accumulator) error {
 	return nil
 }
 
-func (m *MongoDB) Stop() {}
+// Stop disconnect mongo connections when stop or reload
+func (m *MongoDB) Stop() {
+	for _, server := range m.clients {
+		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
+		_ = server.client.Disconnect(ctx)
```
Comment (srebhan) [inline plugins/inputs/mongodb/mongodb.go:151]: Should we maybe at least log an error if it occurs?
```suggestion
		if err := server.client.Disconnect(ctx); err != nil {
			m.Log.Errorf("disconnecting from %q failed: %w", server, err)
		}
```

**Review by srebhan — COMMENTED** [review]
Thanks @zhiyuan-mojie for contributing this nice fix! I do have one suggestion to log errors though... What do you think?

File: plugins/inputs/mongodb/mongodb.go (hunk 2 above)
Comment (zhiyuan-mojie) [reply plugins/inputs/mongodb/mongodb.go]: Thank you for correcting

**Review by powersj — APPROVED** [review]

**Review by srebhan — APPROVED** [review]
Thank you for the fix @zhiyuan-mojie!
