### PR TITLE
test: add unit test to check correct tags for each plugin registered

### LINKED ISSUE #13018: Add unit test for build tags for plugins to ensure correctness
While building a custom telegraf binary, I noticed that the netflow input plugin was incorrectly registered via build tag. It was fixed in #13006 
I advocate for unit tests for all plugins to ensure that the plugin name matches the build tag. Hoping its not an overkill.

Let me know if that sounds good.

### PR DESCRIPTION
**Pull request by neelayu**
# Required for all PRs

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #13018

### CODE REVIEW

**Comment by powersj** [comment]
I think this is another nice addition. Two linter issues and then I can look over it in more detail:

```s
  plugins/inputs/all/all_test.go:17:18  errcheck  Error return value of `filepath.WalkDir` is not checked
  plugins/inputs/all/all_test.go:25:33  revive    empty-lines: extra empty line at the end of a block
```

Thanks again!

File: plugins/all_test.go
Comment (Hipska) [inline plugins/all_test.go:1]: Should this maybe be placed in `plugins/inputs/all/all_test.go` and similar?

I think you can then also use all the imports in there?

Comment (Hipska) [reply plugins/all_test.go:1]: I just saw it was like that initially 😆 Not sure what to think of it..

Comment (neelayu) [reply plugins/all_test.go:1]: If I put it in individual directories, I believe there will be lot of code duplication. Hence moved to `plugins` directory.

Comment (Hipska) [reply plugins/all_test.go:1]: That's a fair point. But I think we should do something with the includes in `all` to only check plugins actually included? Not sure if that is possible in some way though...

Comment (Hipska) [reply plugins/all_test.go:1]: Nevermind, just saw you did that as well 🤦

Comment (neelayu) [reply plugins/all_test.go:1]: Yeah. I have covered that case as well. Just need some opinion on the code correctness. Since one of the parsers 
`plugins/parsers/all/influx.go` imports 2 pkgs- influx and influx_upstream, but the file tag contains only one- `parsers.influx`. So in a way I cannot build a telegraf dist with just `influx_upstream` parser. I am not aware of this parser and I am assuming that influx_upstream is independent of influx parser!

Comment (Hipska) [reply plugins/all_test.go:1]: This is from the docs:
```toml
  ## Influx line protocol parser
  ## 'internal' is the default. 'upstream' is a newer parser that is faster
  ## and more memory efficient.
  ## influx_parser_type = "internal"
```
It is an option for the influx parser.. But you can close this conversation.

File: plugins/all_test.go [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+							result[i] = strings.TrimPrefix(transFormFunc(t), "//go:build ")
+						}
+						return result
+					}(tags, strings.TrimSpace)
+
+					assert.Len(t, tags, 3)
+					assert.Contains(t, tags, "!custom")
+					assert.Contains(t, tags, pluginCategory)
+					plugin := getPlugin(tags, pluginCategory)
+					assert.Greater(t, len(plugin), 0)
```
Comment (Hipska) [inline plugins/all_test.go:68]: Why using assert instead of require?
```suggestion
					require.Len(t, tags, 3)
					require.Contains(t, tags, "!custom")
					require.Contains(t, tags, pluginCategory)
					plugin := getPlugin(tags, pluginCategory)
					require.NotEmpty(t, plugin)
```

(same for the rest of the test..)

File: plugins/all_test.go [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+
+					// check if present in exceptionMap
+					exception, ok := exceptionMap[importPath]
+					if ok {
+						assert.Equal(t, plugin, exception)
+						return
+					}
+					check := strings.TrimSuffix(importPath, plugin)
+					// validate if check changed(Success), else fail
+					assert.NotEqual(t, importPath, check, fmt.Sprintf("build tag is invalid for %v", d.Name()))
```
Comment (Hipska) [inline plugins/all_test.go:83]: I'm not sure what is happening here. Could you explain?

File: plugins/all_test.go [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+				}
+				testName := fmt.Sprintf("%v-%v", pluginCategory, strings.TrimSuffix(d.Name(), ".go"))
+				t.Run(testName, func(t *testing.T) {
+					tags := strings.Split(comm.Text, "||")
+					// tags might contain spaces and hence trim
+					tags = func(elems []string, transFormFunc func(string) string) []string {
+						result := make([]string, len(elems))
+						for i, t := range elems {
+							result[i] = strings.TrimPrefix(transFormFunc(t), "//go:build ")
+						}
```
Comment (Hipska) [inline plugins/all_test.go:60]: `t` is a confusing name when inside tests.

**Review by Hipska — CHANGES_REQUESTED** [review]
On overall good idea, but I would split out some part into a specific function that clearly states that it is testing the tags, as later on there might be other tests that test different stuff..

File: plugins/all_test.go (hunk 3 above)
Comment (neelayu) [reply plugins/all_test.go]: Agreed. Renamed

File: plugins/all_test.go (hunk 1 above)
Comment (neelayu) [reply plugins/all_test.go]: I follow the following convention-
use require when you want to test the behaviour of components not directly related to the code. Acts as a prerequisite. So if that itself fails, code shouldn't execute further.

use assert when you want to test the actual code.

Although now that I see, telegraf uses require almost everywhere.
Thanks for the tip 👍

File: plugins/all_test.go [hunk 4]
```diff
@@ -0,0 +1,114 @@
...
+	// tags might contain spaces and hence trim
+	tags = stringMap(tags, strings.TrimSpace)
+
+	require.Len(t, tags, 3)
+	require.Contains(t, tags, "!custom")
+	require.Contains(t, tags, pluginCategory)
+
+	actual := getPluginBuildTag(tags, pluginCategory)
+	expected := fmt.Sprintf("%v.%v", pluginCategory, plugin)
+	require.Equal(t, expected, actual, fmt.Sprintf("build tag is invalid for %v", plugin))
```
Comment (Hipska) [inline plugins/all_test.go:93]:
```suggestion
	actual := getPluginBuildTag(tags, pluginCategory)
	expected := fmt.Sprintf("%s.%s", pluginCategory, plugin)
	require.Equal(t, expected, actual, "invalid build tag")
```
(plugin name is already covered in the name of the test)

File: plugins/all_test.go [hunk 5]
```diff
@@ -0,0 +1,114 @@
...
+}
+
+// getPluginBuildTag takes a slice of tags and returns the build tag corresponding to this plugin type.
+//
+// For ex ["!custom", "inputs", "inputs.docker"] returns "inputs.docker"
+func getPluginBuildTag(tags []string, pluginCategory string) string {
+	for _, tag := range tags {
+		if strings.HasPrefix(tag, fmt.Sprintf("%v.", pluginCategory)) {
```
Comment (Hipska) [inline plugins/all_test.go:101]:
```suggestion
		if strings.HasPrefix(tag, fmt.Sprintf("%s.", pluginCategory)) {
```
Or 
```suggestion
		if strings.HasPrefix(tag, pluginCategory+".") {
```

File: plugins/all_test.go [hunk 6]
```diff
@@ -0,0 +1,114 @@
...
+}
+
+func testBuildTags(t *testing.T, buildComment string, pluginCategory string, plugin string) {
+	tags := strings.Split(buildComment, "||")
+	// tags might contain spaces and hence trim
+	tags = stringMap(tags, strings.TrimSpace)
+
+	require.Len(t, tags, 3)
+	require.Contains(t, tags, "!custom")
+	require.Contains(t, tags, pluginCategory)
```
Comment (Hipska) [inline plugins/all_test.go:89]: Is it clear in the message that this is about the build tags when they fail?

**Review by Hipska — CHANGES_REQUESTED** [review]

File: plugins/all_test.go (hunk 6 above)
Comment (neelayu) [reply plugins/all_test.go:89]: Example message we get-
```
[]string{"not-custom", "inputs", "inputs.mysql"} does not contain "!custom"
```
I think that is acceptable. Any suggestions?

File: plugins/all_test.go [hunk 7]
```diff
@@ -0,0 +1,114 @@
...
+	node, err := parser.ParseFile(fset, goPluginFile, nil, parser.ParseComments)
+	require.NoError(t, err)
+
+	for _, cg := range node.Comments {
+		for _, comm := range cg.List {
+			if !strings.HasPrefix(comm.Text, "//go:build") {
+				continue
+			}
+			file := filepath.Base(goPluginFile)
+			testName := fmt.Sprintf("%v-%v", pluginCategory, strings.TrimSuffix(file, ".go"))
```
[the remark this answers is not in the document]
Comment (neelayu) [reply plugins/all_test.go]: Yeah that works! Done

File: plugins/all_test.go [hunk 8]
```diff
@@ -0,0 +1,114 @@
...
+				plugin := resolvePluginFromImports(t, node.Imports)
+				testBuildTags(t, comm.Text, pluginCategory, plugin)
+			})
+		}
+	}
+}
+
+func resolvePluginFromImports(t *testing.T, imports []*ast.ImportSpec) string {
+	// should contain one or more import statements
+	require.GreaterOrEqual(t, len(imports), 1)
```
[the remark this answers is not in the document]
Comment (Hipska) [reply plugins/all_test.go]: Why resolved? You don't agree with my suggestion?

File: plugins/all_test.go (hunk 6 above)
Comment (Hipska) [reply plugins/all_test.go:87]: Well the other test says "invalid build tag", but yeah, it might be ok when the test name is also the filename..

File: plugins/all_test.go [hunk 9]
```diff
@@ -0,0 +1,112 @@
...
+}
+
+func testPluginDirectory(t *testing.T, directory string) {
+	allDir := filepath.Join(directory, "all")
+	err := filepath.WalkDir(allDir, func(goPluginFile string, d fs.DirEntry, walkErr error) error {
+		require.NoError(t, walkErr)
+		if d.IsDir() || strings.HasSuffix(d.Name(), "_test.go") {
+			return nil
+		}
+		parseSourceFile(t, goPluginFile, directory)
```
Comment (Hipska) [inline plugins/all_test.go:41]: What do you think of moving the Run to here?
```suggestion
		t.Run(goPluginFile, func(t *testing.T) {
			parseSourceFile(t, goPluginFile, directory)
		}
```

Then it will become easier to add other tests for this file in the future.

**Review by Hipska — APPROVED** [review]

File: plugins/all_test.go [hunk 10]
```diff
@@ -0,0 +1,112 @@
...
+func parseSourceFile(t *testing.T, goPluginFile string, pluginCategory string) {
+	fset := token.NewFileSet()
+	node, err := parser.ParseFile(fset, goPluginFile, nil, parser.ParseComments)
+	require.NoError(t, err)
+
+	for _, cg := range node.Comments {
+		for _, comm := range cg.List {
+			if !strings.HasPrefix(comm.Text, "//go:build") {
+				continue
+			}
```
Comment (srebhan) [inline plugins/all_test.go:58]: Isn't this also an error? We expect plugins to contain build-tags otherwise they will be always included...

**Review by srebhan — COMMENTED** [review]
Looks good to me. Just one question @neelayu...

File: plugins/all_test.go (hunk 10 above)
Comment (neelayu) [reply plugins/all_test.go:59]: Good point. This check is only to filter out comments which do not start with go:build as there can be other package level comments as well.
Having said that, I have now added a check to ensure go:build is present. Thanks!

**Review by srebhan — COMMENTED** [review]
And a last one...

File: plugins/all_test.go [hunk 11]
```diff
@@ -0,0 +1,117 @@
...
+			foundGoBuild = true
+			plugin := resolvePluginFromImports(t, node.Imports)
+			testBuildTags(t, comm.Text, pluginCategory, plugin)
+		}
+	}
+	if !foundGoBuild {
+		require.Fail(t, fmt.Sprintf("%s does not contain go:build. Ensure that there no whitespaces between %q %q", goPluginFile, "//", "go:build"))
+	}
```
[the remark this answers is not in the document]
Comment (neelayu) [reply plugins/all_test.go]: Noted.

**Review by srebhan — APPROVED** [review]
Looks good to me. Thanks for this cool test @neelayu!
