### PR TITLE
Skip bad entries on interrupt input

### LINKED ISSUE #4470: Parsing error in interrupt input plugin
### Relevant telegraf.conf:
```
[[inputs.interrupts]]
    # no further configuration
```
### System info:
```
$ uname -a
Linux undisclosed 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux
$ telegraf version
Telegraf v1.7.1 (git: release-1.7 4be18c1e)
```

### Steps to reproduce:
1. install telegraf
2. enable `interrupts` input plugin

### Expected behavior:
I expect Telegraf to gather interrupt metrics as described in the plugin readme.

### Actual behavior:
Telegraf throws an error while gathering.
```
E! Error in plugin [inputs.interrupts]: Parsing /proc/interrupts: Unable to parse "usb_fiq" from "FIQ:              usb_fiq": strconv.ParseInt: parsing "usb_fiq": invalid syntax
```

### Additional info:
Please notice that this machine is ARM-based.
```
$ cat /proc/interrupts
           CPU0       CPU1       CPU2       CPU3
 16:          0          0          0          0  bcm2836-timer   0 Edge      arch_timer
 17:  127224250  118424219  127224437  117885416  bcm2836-timer   1 Edge      arch_timer
 21:          0          0          0          0  bcm2836-pmu   9 Edge      arm-pmu
 23:    1549514          0          0          0  ARMCTRL-level   1 Edge      3f00b880.mailbox
 24:          2          0          0          0  ARMCTRL-level   2 Edge      VCHIQ doorbell
 46:          0          0          0          0  ARMCTRL-level  48 Edge      bcm2708_fb dma
 48:          0          0          0          0  ARMCTRL-level  50 Edge      DMA IRQ
 50:          0          0          0          0  ARMCTRL-level  52 Edge      DMA IRQ
 51:        208          0          0          0  ARMCTRL-level  53 Edge      DMA IRQ
 54:     883002          0          0          0  ARMCTRL-level  56 Edge      DMA IRQ
 59:          0          0          0          0  ARMCTRL-level  61 Edge      bcm2835-auxirq
 62:  521451447          0          0          0  ARMCTRL-level  64 Edge      dwc_otg, dwc_otg_pcd, dwc_otg_hcd:usb1
 86:     857597          0          0          0  ARMCTRL-level  88 Edge      mmc0
 87:       4938          0          0          0  ARMCTRL-level  89 Edge      uart-pl011
 92:       5669          0          0          0  ARMCTRL-level  94 Edge      mmc1
FIQ:              usb_fiq
IPI0:          0          0          0          0  CPU wakeup interrupts
IPI1:          0          0          0          0  Timer broadcast interrupts
IPI2:   23564958   23464876   23531165   23040826  Rescheduling interrupts
IPI3:     148438     639704     644266     588150  Function call interrupts
IPI4:          0          0          0          0  CPU stop interrupts
IPI5:    4348149    1843985    3819457    1822877  IRQ work interrupts
IPI6:          0          0          0          0  completion interrupts
```

### PR DESCRIPTION
**Pull request by glinton**
Resolves #4470

### CODE REVIEW

File: plugins/inputs/interrupts/interrupts.go [hunk 1]
```diff
@@ -50,11 +51,15 @@ func parseInterrupts(r io.Reader) ([]IRQ, error) {
 		}
 		cpucount = len(cpus)
 	}
+
 	for scanner.Scan() {
 		fields := strings.Fields(scanner.Text())
 		if !strings.HasSuffix(fields[0], ":") {
 			continue
 		}
+		if cpucount > len(fields) {
```
Comment (danielnelson) [inline plugins/inputs/interrupts/interrupts.go]: I was going to say we need to compare this against `irqvals` since `fields` includes the name of the irq, but then I noticed this line from the existing tests:
```
 MIS:          0
```

So it is possible to have fewer fields than cpucount.  Maybe we just continue with no error if the ParseInt call fails?
