### PR TITLE
fix(inputs.zfs): Gathering poolMetrics failed on zfs 2.2.0

### LINKED ISSUE #14279: [inputs.zfs] no zfs_pool on linux with poolMetrics=true and zfs=2.2.0
### Relevant telegraf.conf

```toml
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = "truenas"
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["https://****"]
  token = "****"
  organization = "*****"
  bucket = "servers"

#[[outputs.file]]
#  files = [ "/mnt/safe/telegraf.data" ]

[[inputs.zfs]]
  poolMetrics = true
  # datasetMetrics = false
```

### Logs from Telegraf

```text
root@truenas:~# /usr/bin/telegraf --config /mnt/safe/apps/telegraf/telegraf.conf --debug --test
2023-11-10T09:50:25Z I! Loading config: /mnt/safe/apps/telegraf/telegraf.conf
2023-11-10T09:50:25Z I! Starting Telegraf 1.28.3 brought to you by InfluxData the makers of InfluxDB
2023-11-10T09:50:25Z I! Available plugins: 240 inputs, 9 aggregators, 29 processors, 24 parsers, 59 outputs, 5 secret-stores
2023-11-10T09:50:25Z I! Loaded inputs: zfs
2023-11-10T09:50:25Z I! Loaded aggregators: 
2023-11-10T09:50:25Z I! Loaded processors: 
2023-11-10T09:50:25Z I! Loaded secretstores: 
2023-11-10T09:50:25Z W! Outputs are not used in testing mode!
2023-11-10T09:50:25Z I! Tags enabled: host=truenas
2023-11-10T09:50:25Z D! [agent] Initializing plugins
2023-11-10T09:50:25Z D! [agent] Starting service inputs
2023-11-10T09:50:26Z D! [agent] Stopping service inputs
2023-11-10T09:50:26Z D! [agent] Input channel closed
2023-11-10T09:50:26Z D! [agent] Stopped Successfully
> zfs,host=truenas,pools=boot-pool::main::registry::safe abdstats_linear_cnt=11381i,abdstats_linear_data_size=8297984i,abdstats_scatter_chunk_waste=14147072i,abdstats_scatter_cnt=67553i,abdstats_scatter_data_size=2784842240i,abdstats_scatter_order_0=40930i,abdstats_scatter_order_1=20008i,abdstats_scatter_order_10=0i,abdstats_scatter_order_11=0i,abdstats_scatter_order_12=0i,abdstats_scatter_order_13=0i,abdstats_scatter_order_2=14016i,abdstats_scatter_order_3=8624i,abdstats_scatter_order_4=9790i,abdstats_scatter_order_5=10022i,abdstats_scatter_order_6=0i,abdstats_scatter_order_7=0i,abdstats_scatter_order_8=0i,abdstats_scatter_order_9=0i,abdstats_scatter_page_alloc_retry=0i,abdstats_scatter_page_multi_chunk=24501i,abdstats_scatter_page_multi_zone=0i,abdstats_scatter_sg_table_retry=0i,abdstats_struct_size=8209136i,arcstats_abd_chunk_waste_size=14147072i,arcstats_access_skip=8i,arcstats_anon_data=9043968i,arcstats_anon_evictable_data=0i,arcstats_anon_evictable_metadata=0i,arcstats_anon_metadata=270848i,arcstats_anon_size=9314816i,arcstats_arc_dnode_limit=835900211i,arcstats_arc_loaned_bytes=0i,arcstats_arc_meta_used=423909664i,arcstats_arc_need_free=0i,arcstats_arc_no_grow=0i,arcstats_arc_prune=0i,arcstats_arc_raw_size=0i,arcstats_arc_sys_free=646546432i,arcstats_arc_tempreserve=0i,arcstats_async_upgrade_sync=466i,arcstats_bonus_size=19775680i,arcstats_c=3257517056i,arcstats_c_max=8359002112i,arcstats_c_min=522437632i,arcstats_cached_only_in_progress=0i,arcstats_compressed_size=2793136128i,arcstats_data_size=2770252800i,arcstats_dbuf_size=28865312i,arcstats_deleted=73i,arcstats_demand_data_hits=5181447i,arcstats_demand_data_iohits=372i,arcstats_demand_data_misses=40088i,arcstats_demand_hit_predictive_prefetch=12350i,arcstats_demand_hit_prescient_prefetch=74i,arcstats_demand_iohit_predictive_prefetch=919i,arcstats_demand_iohit_prescient_prefetch=45i,arcstats_demand_metadata_hits=25208757i,arcstats_demand_metadata_iohits=1998i,arcstats_demand_metadata_misses=16554i,arcstats_dnode_size=65623944i,arcstats_evict_l2_cached=0i,arcstats_evict_l2_eligible=1040896i,arcstats_evict_l2_eligible_mfu=278528i,arcstats_evict_l2_eligible_mru=762368i,arcstats_evict_l2_ineligible=16384i,arcstats_evict_l2_skip=0i,arcstats_evict_not_enough=0i,arcstats_evict_skip=20876i,arcstats_hash_chain_max=3i,arcstats_hash_chains=1368i,arcstats_hash_collisions=47798i,arcstats_hash_elements=78873i,arcstats_hash_elements_max=78932i,arcstats_hdr_size=21224376i,arcstats_hits=30416760i,arcstats_iohits=11668i,arcstats_l2_abort_lowmem=0i,arcstats_l2_asize=0i,arcstats_l2_bufc_data_asize=0i,arcstats_l2_bufc_metadata_asize=0i,arcstats_l2_cksum_bad=0i,arcstats_l2_data_to_meta_ratio=0i,arcstats_l2_evict_l1cached=0i,arcstats_l2_evict_lock_retry=0i,arcstats_l2_evict_reading=0i,arcstats_l2_feeds=0i,arcstats_l2_free_on_write=0i,arcstats_l2_hdr_size=0i,arcstats_l2_hits=0i,arcstats_l2_io_error=0i,arcstats_l2_log_blk_asize=0i,arcstats_l2_log_blk_avg_asize=0i,arcstats_l2_log_blk_count=0i,arcstats_l2_log_blk_writes=0i,arcstats_l2_mfu_asize=0i,arcstats_l2_misses=0i,arcstats_l2_mru_asize=0i,arcstats_l2_prefetch_asize=0i,arcstats_l2_read_bytes=0i,arcstats_l2_rebuild_asize=0i,arcstats_l2_rebuild_bufs=0i,arcstats_l2_rebuild_bufs_precached=0i,arcstats_l2_rebuild_cksum_lb_errors=0i,arcstats_l2_rebuild_dh_errors=0i,arcstats_l2_rebuild_io_errors=0i,arcstats_l2_rebuild_log_blks=0i,arcstats_l2_rebuild_lowmem=0i,arcstats_l2_rebuild_size=0i,arcstats_l2_rebuild_success=0i,arcstats_l2_rebuild_unsupported=0i,arcstats_l2_rw_clash=0i,arcstats_l2_size=0i,arcstats_l2_write_bytes=0i,arcstats_l2_writes_done=0i,arcstats_l2_writes_error=0i,arcstats_l2_writes_lock_retry=0i,arcstats_l2_writes_sent=0i,arcstats_memory_all_bytes=16718004224i,arcstats_memory_available_bytes=6186945536i,arcstats_memory_direct_count=0i,arcstats_memory_free_bytes=6833491968i,arcstats_memory_indirect_count=0i,arcstats_memory_throttle_count=0i,arcstats_meta=1073741824i,arcstats_metadata_size=288420352i,arcstats_mfu_data=2000919040i,arcstats_mfu_evictable_data=1887841792i,arcstats_mfu_evictable_metadata=55416832i,arcstats_mfu_ghost_data=0i,arcstats_mfu_ghost_evictable_data=0i,arcstats_mfu_ghost_evictable_metadata=0i,arcstats_mfu_ghost_hits=0i,arcstats_mfu_ghost_metadata=0i,arcstats_mfu_ghost_size=0i,arcstats_mfu_hits=28595077i,arcstats_mfu_metadata=169408000i,arcstats_mfu_size=2170327040i,arcstats_misses=65641i,arcstats_mru_data=760289792i,arcstats_mru_evictable_data=751781376i,arcstats_mru_evictable_metadata=21857280i,arcstats_mru_ghost_data=0i,arcstats_mru_ghost_evictable_data=0i,arcstats_mru_ghost_evictable_metadata=0i,arcstats_mru_ghost_hits=0i,arcstats_mru_ghost_metadata=0i,arcstats_mru_ghost_size=0i,arcstats_mru_hits=1821683i,arcstats_mru_metadata=118741504i,arcstats_mru_size=879031296i,arcstats_mutex_miss=0i,arcstats_overhead_size=265537024i,arcstats_pd=2147483648i,arcstats_pm=2147483648i,arcstats_predictive_prefetch=44734i,arcstats_prefetch_data_hits=683i,arcstats_prefetch_data_iohits=35i,arcstats_prefetch_data_misses=4277i,arcstats_prefetch_metadata_hits=25873i,arcstats_prefetch_metadata_iohits=9263i,arcstats_prefetch_metadata_misses=4722i,arcstats_prescient_prefetch=119i,arcstats_size=3208309536i,arcstats_uncached_data=0i,arcstats_uncached_evictable_data=0i,arcstats_uncached_evictable_metadata=0i,arcstats_uncached_hits=0i,arcstats_uncached_metadata=0i,arcstats_uncached_size=0i,arcstats_uncompressed_size=5357437952i,dmu_tx_assigned=6440352i,dmu_tx_delay=0i,dmu_tx_dirty_delay=0i,dmu_tx_dirty_frees_delay=0i,dmu_tx_dirty_over_max=0i,dmu_tx_dirty_throttle=0i,dmu_tx_error=0i,dmu_tx_group=0i,dmu_tx_memory_reclaim=0i,dmu_tx_memory_reserve=0i,dmu_tx_quota=0i,dmu_tx_suspended=0i,dmu_tx_wrlog_delay=0i,dnode_alloc_next_block=0i,dnode_alloc_next_chunk=471i,dnode_alloc_race=0i,dnode_allocate=42676i,dnode_buf_evict=15058i,dnode_free_interior_lock_retry=0i,dnode_hold_alloc_hits=16555196i,dnode_hold_alloc_interior=0i,dnode_hold_alloc_lock_misses=0i,dnode_hold_alloc_lock_retry=0i,dnode_hold_alloc_misses=0i,dnode_hold_alloc_type_none=48i,dnode_hold_dbuf_hold=0i,dnode_hold_dbuf_read=0i,dnode_hold_free_hits=42676i,dnode_hold_free_lock_misses=0i,dnode_hold_free_lock_retry=0i,dnode_hold_free_misses=5650i,dnode_hold_free_overflow=0i,dnode_hold_free_refcount=0i,dnode_move_active=0i,dnode_move_handle=0i,dnode_move_invalid=0i,dnode_move_recheck1=0i,dnode_move_recheck2=0i,dnode_move_rwlock=0i,dnode_move_special=0i,dnode_reallocate=0i,fm_erpt-dropped=0i,fm_erpt-duplicates=0i,fm_erpt-set-failed=0i,fm_fmri-set-failed=0i,fm_payload-set-failed=0i,vdev_mirror_stats_non_rotating_linear=0i,vdev_mirror_stats_non_rotating_seek=0i,vdev_mirror_stats_preferred_found=75311i,vdev_mirror_stats_preferred_not_found=33835i,vdev_mirror_stats_rotating_linear=1833i,vdev_mirror_stats_rotating_offset=4812i,vdev_mirror_stats_rotating_seek=80393i,zfetchstats_hits=77672i,zfetchstats_io_active=0i,zfetchstats_io_issued=5505i,zfetchstats_max_streams=1199635i,zfetchstats_misses=1499391i,zil_commit_count=31659i,zil_commit_writer_count=31587i,zil_itx_copied_bytes=0i,zil_itx_copied_count=0i,zil_itx_count=334359i,zil_itx_indirect_bytes=205725696i,zil_itx_indirect_count=6257i,zil_itx_metaslab_normal_alloc=2762297344i,zil_itx_metaslab_normal_bytes=971531248i,zil_itx_metaslab_normal_count=29435i,zil_itx_metaslab_normal_write=1051631616i,zil_itx_metaslab_slog_alloc=0i,zil_itx_metaslab_slog_bytes=0i,zil_itx_metaslab_slog_count=0i,zil_itx_metaslab_slog_write=0i,zil_itx_needcopy_bytes=903975256i,zil_itx_needcopy_count=304073i 1699609826000000000
```

### System info

Telegraf 1.28.3; Truenas scale 23.10.0.1(Debian 12); OpenZFS 2.2.0

### Docker

_No response_

### Steps to reproduce

1. run metrics
2. open influxdb oss dashboard and there is not measurement named zfs_pool

### Expected behavior

gather the right zfs_pool measurements

### Actual behavior

there is not measurement named zfs_pool

### Additional info

the `zfs/*/object-*` in zfs 2.2.0 adds some `zil_*` fields:
```shell
root@truenas:~# cat /proc/spl/kstat/zfs/safe/objset-0xf1bb
65 1 0x01 24 6784 71306408925 262976147663960
name                            type data
dataset_name                    7    safe/ix-applications/releases/traefik/charts
writes                          4    0
nwritten                        4    0
reads                           4    1
nread                           4    24271
nunlinks                        4    0
nunlinked                       4    0
zil_commit_count                4    0
zil_commit_writer_count         4    0
zil_itx_count                   4    0
zil_itx_indirect_count          4    0
zil_itx_indirect_bytes          4    0
zil_itx_copied_count            4    0
zil_itx_copied_bytes            4    0
zil_itx_needcopy_count          4    0
zil_itx_needcopy_bytes          4    0
zil_itx_metaslab_normal_count   4    0
zil_itx_metaslab_normal_bytes   4    0
zil_itx_metaslab_normal_write   4    0
zil_itx_metaslab_normal_alloc   4    0
zil_itx_metaslab_slog_count     4    0
zil_itx_metaslab_slog_bytes     4    0
zil_itx_metaslab_slog_write     4    0
zil_itx_metaslab_slog_alloc     4    0
```

### PR DESCRIPTION
**Pull request by delichik**
- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #14279

### CODE REVIEW

**Comment by delichik** [comment]
!signed-cla

**Comment by delichik** [comment]
!signed-cla

File: plugins/inputs/zfs/zfs_linux.go [hunk 1]
```diff
@@ -83,9 +83,9 @@ func getTags(pools []poolInfo) map[string]string {
 	return map[string]string{"pools": poolNames}
 }
 
-func gather(lines []string, fileLines int) ([]string, []string, error) {
-	if len(lines) != fileLines {
-		return nil, nil, errors.New("expected lines in kstat does not match")
+func gather(lines []string, minimalFileLines int) ([]string, []string, error) {
+	if len(lines) < minimalFileLines {
+		return nil, nil, errors.New("lines in kstat is not enough")
```
Comment (srebhan) [inline plugins/inputs/zfs/zfs_linux.go:88]: Can you please minimize the changes here by keeping the parameter-name `fileLines` instead of renaming it!?! The same holds true for the error message.

File: plugins/inputs/zfs/README.md [hunk 2]
```diff
@@ -223,6 +223,33 @@ For ZFS >= 2.1.x the format has changed significantly:
...
+  - zil_itx_needcopy_bytes (integer, bytes)
+  - zil_itx_metaslab_normal_count (integer, count)
+  - zil_itx_metaslab_normal_bytes (integer, bytes)
+  - zil_itx_metaslab_normal_write (integer, bytes)
+  - zil_itx_metaslab_normal_alloc (integer, bytes)
+  - zil_itx_metaslab_slog_count (integer, count)
+  - zil_itx_metaslab_slog_bytes (integer, bytes)
+  - zil_itx_metaslab_slog_write (integer, bytes)
+  - zil_itx_metaslab_slog_alloc (integer, bytes)
+
```
Comment (srebhan) [inline plugins/inputs/zfs/README.md:252]: Maybe
```suggestion
For ZFS >= 2.2.x the following additional fields are available:

- additional fields for ZFS > 2.2.x
  - zil_commit_count (integer, count)
  - zil_commit_writer_count (integer, count)
  - zil_itx_count (integer, count)
  - zil_itx_indirect_count (integer, count)
  - zil_itx_indirect_bytes (integer, bytes)
  - zil_itx_copied_count (integer, count)
  - zil_itx_copied_bytes (integer, bytes)
  - zil_itx_needcopy_count (integer, count)
  - zil_itx_needcopy_bytes (integer, bytes)
  - zil_itx_metaslab_normal_count (integer, count)
  - zil_itx_metaslab_normal_bytes (integer, bytes)
  - zil_itx_metaslab_normal_write (integer, bytes)
  - zil_itx_metaslab_normal_alloc (integer, bytes)
  - zil_itx_metaslab_slog_count (integer, count)
  - zil_itx_metaslab_slog_bytes (integer, bytes)
  - zil_itx_metaslab_slog_write (integer, bytes)
  - zil_itx_metaslab_slog_alloc (integer, bytes)

```

**Review by srebhan — COMMENTED** [review]
Thank you very much @delichik for your fix! Much appreciated. Two minor comments from my side... Can you please have a look!?

**Comment by delichik** [comment]
> Thank you very much @delichik for your fix! Much appreciated. Two minor comments from my side... Can you please have a look!?

you are right. thanks a lot

**Review by srebhan — APPROVED** [review]
Thanks @delichik for the quick response!

File: plugins/inputs/zfs/README.md [hunk 3]
```diff
@@ -391,6 +412,7 @@ memory is too low)
 
 ### ZIL (Linux Only)
 
-note: ZIL measurements are system-wide, neither per-pool nor per-dataset
+note: `zil` measurements in `kstatMetrics` are system-wide, in `poolMetrics`
+are pool-wide
```
Comment (powersj) [inline plugins/inputs/zfs/README.md:416]:
```suggestion
they are pool-wide
```

**Review by powersj — APPROVED** [review]
