### PR TITLE
Validate tag names for consul input

### LINKED ISSUE #5522: Consul plugin doesn't work since 1.6.4 with prometheus
### System info:
RHEL OS 3.10.0-862.11.6.el7.x86_64

#### Bug: 
Telegraf 1.6.4 works well, any telegraf with greater version(1.7.0+) breaks the scrapping from telegraf with prometheus.
#### My case overview:
A custom proceses register in consul with their uniq tags.(`Tags: noc, 0193068a-3ddb-44e7-81c1-0528d28419e0`)
default

### Steps to reproduce:
On 1.6.4 it looks normal and don't break prometheus :
```
consul_health_checks,check_id=service:0193068a-3ddb-44e7-81c1-0528d28419e0,host=sstage-db,node=sstage-db,service_name=discovery-default check_name="Service 'discovery-default' check",service_id="0193068a-3ddb-44e7-81c1-0528d28419e0",status="passing",passing=1i,critical=0i,warning=0i 1551639934000000000
```
On 1.9.5 like:
```
> consul_health_checks,0193068a-3ddb-44e7-81c1-0528d28419e0=0193068a-3ddb-44e7-81c1-0528d28419e0,check_id=service:0193068a-3ddb-44e7-81c1-0528d28419e0,host=sstage-db,noc=noc,node=sstage-db,service_name=discovery-default check_name="Service 'discovery-default' check",critical=0i,passing=1i,service_id="0193068a-3ddb-44e7-81c1-0528d28419e0",status="passing",warning=0i 1551640092000000000
```
With Prometheus error:
```
msg="append failed" err="expected label name, got \"EQUAL\""
```
So i have additional info like 
```
0193068a-3ddb-44e7-81c1-0528d28419e0=0193068a-3ddb-44e7-81c1-0528d28419e0
noc=noc
```

### Additional info:
Also i have found this discussion: 
https://github.com/influxdata/telegraf/pull/4155#discussion_r245284507

### PR DESCRIPTION
**Pull request by glinton**
Valid prometheus labels must match the regex `^[a-zA-Z_][a-zA-Z0-9_]*`
https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels

Resolves #5522

### CODE REVIEW

File: plugins/inputs/consul/consul.go [hunk 1]
```diff
@@ -141,6 +146,14 @@ func (c *Consul) GatherHealthCheck(acc telegraf.Accumulator, checks []*api.Healt
 	}
 }
 
+func isValidTagName(tag string) bool {
+	matched, err := regexp.MatchString(`^[a-zA-Z_][a-zA-Z0-9_]*`, tag)
```
Comment (danielnelson) [inline plugins/inputs/consul/consul.go]: Compile the regex, either at package scope or once at plugin startup.  Otherwise this will compile the regex on every item.
