### PR TITLE
fix: Remove verbose logging from disk input plugin

### LINKED ISSUE #10514: Trim down debug messages in disk
The `inputs.disk` plugin outputs extensive debug information which disrupts observation of e.g. buffer-fullness as reported by @voiprodrigo (see #10318).

Please remove the debug output in disk to make debug usable for those use-cases.

### PR DESCRIPTION
**Pull request by reimda**
fixes #10514

### CODE REVIEW

File: plugins/inputs/system/ps.go [hunk 1]
```diff
@@ -131,29 +137,22 @@ func (s *SystemPS) DiskUsage(
...
 			}
 		}
-		if s.Log != nil {
-			s.Log.Debugf("[SystemPS] -> using mountpoint %q...", mountpoint)
-		}
 
 		du, err := s.PSDiskUsage(mountpoint)
 		if err != nil {
 			if s.Log != nil {
-				s.Log.Debugf("[SystemPS] => dropped by disk usage (%q): %v", mountpoint, err)
```
Comment (reimda) [inline plugins/inputs/system/ps.go:148]: I changed the message text to emphasize that there was an error

File: plugins/inputs/system/ps.go [hunk 2]
```diff
@@ -64,6 +64,27 @@ func (s *SystemPS) CPUTimes(perCPU, totalCPU bool) ([]cpu.TimesStat, error) {
...
+	return ok
+}
+
+func newSet() *set {
+	s := &set{
+		m: make(map[string]struct{}),
+	}
+	return s
+}
+
```
Comment (srebhan) [inline plugins/inputs/system/ps.go:87]: Can we have this as an internal type as we often see `set` operations... We can add `intersection` and `union` later on-demand as I think we have it in the code in multiple locations...

File: plugins/inputs/system/ps.go [hunk 3]
```diff
@@ -73,53 +94,38 @@ func (s *SystemPS) DiskUsage(
...
 
 		// If the mount point is a member of the exclude set,
 		// don't gather info on it.
-		if _, ok := fstypeExcludeSet[p.Fstype]; ok {
-			if s.Log != nil {
-				s.Log.Debug("[SystemPS] => dropped by filesystem-type filter")
-			}
+		if fstypeExcludeSet.has(p.Fstype) {
 			continue
 		}
```
Comment (srebhan) [inline plugins/inputs/system/ps.go:130]: How about we remove the mount-point from the set as it is likely never changing the FS-type?

File: plugins/inputs/system/ps.go (hunk 1 above)
Comment (srebhan) [reply plugins/inputs/system/ps.go:148]: Maybe we should use `s.Log.Errorf`?

**Review by srebhan — COMMENTED** [review]
Hey @reimda thanks for looking into this!
I would love to see `set` becoming an `internal` package as it is helpful in many places/plugins. Furthermore, we maybe should limit the error messages to be printed only once? We can use the `set` again or remove the erroneous mountpoints from the set of processed ones...
What do you think?

File: plugins/inputs/system/ps.go (hunk 2 above)
Comment (reimda) [reply plugins/inputs/system/ps.go:87]: I don't mind if we move it to internal and extend it. Next time you (or anyone) needs it, feel free to move it around.

File: plugins/inputs/system/ps.go (hunk 3 above)
Comment (reimda) [reply plugins/inputs/system/ps.go:130]: In this PR I only addressed the verbose logging and didn't want to change behavior so I didn't think through any improvements (other than adding the set type).

I'm not sure I follow you about removing the mount point. Each gather we get disk usage from gopsutil. It returns usage by filesystem/partition/mountpoint. In this func we skip the filesystem if it's a blacklisted fs type. If we remove it, it will be back in the next gather because gopsutil returns it every time we get disk usage.

File: plugins/inputs/system/ps.go (hunk 1 above)
Comment (reimda) [reply plugins/inputs/system/ps.go:148]: Probably so. It is a real error. Hiding it in a debug message is less useful to anyone who hits it.

File: plugins/inputs/system/ps.go (hunk 3 above)
Comment (srebhan) [reply plugins/inputs/system/ps.go:130]: Understood and I agree here.

File: plugins/inputs/system/ps.go (hunk 1 above)
Comment (reimda) [reply plugins/inputs/system/ps.go:148]: done in 4c3ed8d

**Comment by srebhan** [comment]
@reimda any chance you take a look at the tests?

**Comment by reimda** [comment]
I'm struggling to find how this change causes the failures. I can reproduce them locally but I haven't gotten to the bottom of them yet. Still working on it!

File: plugins/inputs/system/ps.go [hunk 4]
```diff
@@ -73,53 +94,38 @@ func (s *SystemPS) DiskUsage(
...
-					s.Log.Debug("[SystemPS] => dropped by mount-point filter")
-				}
-				continue
-			}
+	for _, p := range parts {
+		// If the mount point is not a member of the filter set,
+		// don't gather info on it.
+		if !mountPointFilterSet.has(p.Mountpoint) {
+			continue
 		}
```
Comment (srebhan) [inline plugins/inputs/system/ps.go:124]: @reimda I think the error (detected by tests) happens here. The old code disabled filtering if there was no entry in the filter, however, your code will filter out _all_ mount-points if no `mountPointFilter` was given...

Comment (reimda) [reply plugins/inputs/system/ps.go]: Thanks! I hadn't noticed this

**Review by srebhan — APPROVED** [review]
Looks good to me. Thanks @reimda!

**Review by powersj — APPROVED** [review]
