### PR TITLE
fix: Update GroundWork SDK and improve logging

### LINKED ISSUE #10278: Groundwork doesn't handle string metrics and payload without NextCheckTime and StartTime
### Relevent telegraf.conf

```toml
# Send telegraf metrics to GroundWork Monitor
[[outputs.groundwork]]
  ## URL of your groundwork instance.
  url = "http://groundwork:8080"
  ## Agent uuid for GroundWork API Server.
  agent_id = "a0eeddb0-ed82-4d62-8320-0882579b6260"
  ## Username and password to access GroundWork API.
  username = "SECRET"
  password = "SECRET"
  
  ## Default display name for the host with services(metrics).
  # default_host = "telegraf"
  ## Default service state.
  # default_service_state = "SERVICE_OK"
  ## The name of the tag that contains the hostname.
  resource_tag = "resource"
```

### System info

Telegraf 1.20.4, Ubuntu 20.04, Docker 20.10.7, Groundwork 8.2.1

### Docker

_No response_

### Steps to reproduce

1. Connect the 'groundwork' output plugin with any Groundwork instance
2. Open the Groundwork -> Status -> Dashboard page on your Groundwork instance UI

### Expected behavior

Resource and services from telegraf plugin must be displayed

### Actual behavior

Resources and services from telegraf plugin not displayed

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by VladislavSenkevich**
### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #10278

### CODE REVIEW

**Comment by powersj** [comment]
Hi,

Is there a bug report to go along with this PR to explain the fix? I would want to understand why a temporary workaround is necessary versus a real fix.

Thanks!

File: plugins/outputs/groundwork/groundwork.go [hunk 1]
```diff
@@ -222,6 +227,7 @@ func (g *Groundwork) parseMetric(metric telegraf.Metric) (string, *transit.Dynam
 		},
 		Status:           transit.MonitorStatus(status),
 		LastCheckTime:    lastCheckTime,
+		NextCheckTime:    nextCheckTime,
```
Comment (Hipska) [inline plugins/outputs/groundwork/groundwork.go:230]: Would this also be accepted by the server?
```suggestion
		NextCheckTime:    lastCheckTime,
```

File: plugins/outputs/groundwork/groundwork.go [hunk 2]
```diff
@@ -254,12 +260,18 @@ func (g *Groundwork) parseMetric(metric telegraf.Metric) (string, *transit.Dynam
...
+			continue
+		}
 
 		serviceObject.Metrics = append(serviceObject.Metrics, transit.TimeSeries{
 			MetricName: value.Key,
 			SampleType: transit.Value,
 			Interval: &transit.TimeInterval{
 				EndTime: lastCheckTime,
+				// Temporary work around to avoid error from the server.
+				StartTime: transit.NewTimestamp(),
```
Comment (Hipska) [inline plugins/outputs/groundwork/groundwork.go:274]: Same here, would this be accepted?
```suggestion
				StartTime: lastCheckTime,
```

File: plugins/outputs/groundwork/groundwork.go [hunk 3]
```diff
@@ -254,12 +260,18 @@ func (g *Groundwork) parseMetric(metric telegraf.Metric) (string, *transit.Dynam
 		if err != nil {
 			return "", nil, err
 		}
+		if typedValue.ValueType == transit.StringType {
+			g.Log.Warn("string values are not supported, skipping")
+			continue
+		}
```
Comment (Hipska) [inline plugins/outputs/groundwork/groundwork.go:266]: Not sure if this is the preferred way to go for telegraf, will discuss that internally.

Comment (Hipska) [reply plugins/outputs/groundwork/groundwork.go:266]: I would definitely mention this in the README.

File: plugins/outputs/groundwork/groundwork.go (hunk 1 above)
Comment (VladislavSenkevich) [reply plugins/outputs/groundwork/groundwork.go:230]: Yes, but we have such a field on the UI side, which can be confusing as it coincides with the LastCheckTime.

File: plugins/outputs/groundwork/groundwork.go (hunk 3 above)
Comment (VladislavSenkevich) [reply plugins/outputs/groundwork/groundwork.go:266]: I asked Thomas Stocking about this, but he said that all we can do at the moment is avoid metrics that we cannot handle on the server side.

File: plugins/outputs/groundwork/groundwork.go (hunk 1 above)
Comment (Hipska) [reply plugins/outputs/groundwork/groundwork.go:230]: Then at least it is visible to not count too much on it. Now it is just making up values..

Comment (VladislavSenkevich) [reply plugins/outputs/groundwork/groundwork.go:230]: Ok, let's leave it the same as LastCheckTime.

File: plugins/outputs/groundwork/groundwork.go (hunk 2 above)
Comment (VladislavSenkevich) [reply plugins/outputs/groundwork/groundwork.go]: Fixed

File: plugins/outputs/groundwork/groundwork.go (hunk 3 above)
Comment (Hipska) [reply plugins/outputs/groundwork/groundwork.go:262]: I was just talking about if telegraf maintainers would accept if an output just 'silently' ignores a field instead of erroring-out. Will ask them about that.

**Comment by VladislavSenkevich** [comment]
> Hi,
> 
> Is there a bug report to go along with this PR to explain the fix? I would want to understand why a temporary workaround is necessary versus a real fix.
> 
> Thanks!

This is a server side bug. The problem is that NextCheckTime and StartTime cannot be empty or absent at all. Some internal logic depends on these fields and cannot be quickly fixed. So I added this  workaround to make the plugin work with the current server implementation.

File: plugins/outputs/groundwork/groundwork.go [hunk 4]
```diff
@@ -5,11 +5,10 @@ import (
 	"encoding/json"
 	"errors"
 	"fmt"
-	"strconv"
-
 	"github.com/gwos/tcg/sdk/clients"
 	"github.com/gwos/tcg/sdk/transit"
 	"github.com/hashicorp/go-uuid"
+	"strconv"
```
Comment (Hipska) [inline plugins/outputs/groundwork/groundwork.go:11]: I think internal libraries should be kept together.

File: plugins/outputs/groundwork/groundwork.go (hunk 3 above)
Comment (VladislavSenkevich) [reply plugins/outputs/groundwork/groundwork.go:262]: In case of erroring-out we are losing another metrics from the batch. We can add information to the logs(with warn level) to notify users about skipping string metrics.

File: plugins/outputs/groundwork/groundwork.go [hunk 5]
```diff
@@ -220,8 +220,10 @@ func (g *Groundwork) parseMetric(metric telegraf.Metric) (string, *transit.Dynam
 			Type:  transit.Service,
 			Owner: resource,
 		},
-		Status:           transit.MonitorStatus(status),
-		LastCheckTime:    lastCheckTime,
+		Status:        transit.MonitorStatus(status),
+		LastCheckTime: lastCheckTime,
+		// Temporary work around to avoid error from the server.
+		NextCheckTime:    lastCheckTime,
 		LastPlugInOutput: message,
```
[the remark this answers is not in the document]
Comment (VladislavSenkevich) [reply plugins/outputs/groundwork/groundwork.go]: Fixed ✅

File: plugins/outputs/groundwork/groundwork.go (hunk 4 above)
Comment (VladislavSenkevich) [reply plugins/outputs/groundwork/groundwork.go]: Fixed ✅

File: plugins/outputs/groundwork/groundwork.go (hunk 3 above)
Comment (Hipska) [reply plugins/outputs/groundwork/groundwork.go:262]: Yeah, I know. That's why I can't make a decision on that by myself.

Comment (VladislavSenkevich) [reply plugins/outputs/groundwork/groundwork.go:262]: Ok, let me know about the results of the conversation.
Thanks!

Comment (Hipska) [reply plugins/outputs/groundwork/groundwork.go:280]: They agree with this 😉

**Comment by Hipska** [comment]
Keep in mind, there still needs a [bug issue to be created](https://github.com/influxdata/telegraf/issues/new?assignees=&labels=bug&template=BUG_REPORT.yml) to be linked to this PR:

> Hi,
> 
> Is there a bug report to go along with this PR to explain the fix? I would want to understand why a temporary workaround is necessary versus a real fix.
> 
> Thanks!

File: plugins/outputs/groundwork/groundwork.go [hunk 6]
```diff
@@ -254,12 +274,17 @@ func (g *Groundwork) parseMetric(metric telegraf.Metric) (string, *transit.Dynam
 		if err != nil {
 			return "", nil, err
```
Comment (Hipska) [inline plugins/outputs/groundwork/groundwork.go:275]:
```suggestion
			return "", nil, fmt.Errorf("Could not convert %s: %w", value.Key, err)
```

**Review by Hipska — CHANGES_REQUESTED** [review]
In order for easier debugging, I request a little bit more descriptive error messages.

File: plugins/outputs/groundwork/groundwork.go [hunk 7]
```diff
@@ -254,12 +274,17 @@ func (g *Groundwork) parseMetric(metric telegraf.Metric) (string, *transit.Dynam
...
 		}
+		if typedValue.ValueType == transit.StringType {
+			g.Log.Warn("string values are not supported, skipping")
```
Comment (Hipska) [inline plugins/outputs/groundwork/groundwork.go:278]:
```suggestion
			g.Log.Warnf("string values are not supported, skipping field %s", value.key)
```

**Review by Hipska — CHANGES_REQUESTED** [review]

**Review by Hipska — APPROVED** [review]

**Comment by powersj** [comment]
> This is a server side bug. The problem is that NextCheckTime and StartTime cannot be empty or absent at all. Some internal logic depends on these fields and cannot be quickly fixed. So I added this workaround to make the plugin work with the current server implementation.

Is the intention to fix this server-side and then revert this PR?

**Comment by ymkins** [comment]
> Is the intention to fix this server-side and then revert this PR

For today we updated client SDK to prevent stepping on server-side limitations.
So, it's not more `temporary work around`.

**Review by Hipska — APPROVED** [review]

File: plugins/outputs/groundwork/groundwork.go [hunk 8]
```diff
@@ -244,15 +266,18 @@ func (g *Groundwork) parseMetric(metric telegraf.Metric) (string, *transit.Dynam
...
-		err := typedValue.FromInterface(value.Value)
-		if err != nil {
-			return "", nil, err
+		typedValue := transit.NewTypedValue(value.Value)
+		if typedValue == nil {
+			return "", nil, fmt.Errorf("could not convert value %s: %v", value.Key, value.Value)
+		}
+		if typedValue.ValueType == transit.StringType {
+			g.Log.Warnf("string values are not supported, skipping field %s", value.Key)
+			continue
```
Comment (Hipska) [inline plugins/outputs/groundwork/groundwork.go:280]: Is this still needed with new SDK version?

Also, why just ignore string values and error out on other unsupported values?

Comment (ymkins) [reply plugins/outputs/groundwork/groundwork.go:280]: We assume that TypedValue is created here, so, returning an error if it is not.
And we still need to skip StringType as backend doesn't support it.

Comment (Hipska) [reply plugins/outputs/groundwork/groundwork.go:280]: Okay, but why just logging Warning if type is string and returning error on different unsupported type? I don't get why there's a difference.

For me it should be ignoring in both cases or returning error in both cases..

File: plugins/outputs/groundwork/groundwork.go [hunk 9]
```diff
@@ -244,15 +266,19 @@ func (g *Groundwork) parseMetric(metric telegraf.Metric) (string, *transit.Dynam
...
 			})
 		}
 
-		typedValue := new(transit.TypedValue)
-		err := typedValue.FromInterface(value.Value)
-		if err != nil {
-			return "", nil, err
+		typedValue := transit.NewTypedValue(value.Value)
+		if typedValue == nil {
+			g.Log.Warnf("could not convert value, skipping field %s: %v", value.Key, value.Value)
```
Comment (Hipska) [inline plugins/outputs/groundwork/groundwork.go:276]: I think there was a version that also logged what the value type was?

I also think the support is lacking for `uint` types.

**Review by ymkins — APPROVED** [review]

**Comment by powersj** [comment]
@VladislavSenkevich can you update this MP to not conflict? Thanks!

**Comment by ymkins** [comment]
> @VladislavSenkevich can you update this MP to not conflict? Thanks!

done

File: go.mod [hunk 10]
```diff
@@ -68,7 +68,10 @@ require (
 	github.com/gorilla/websocket v1.4.2
 	github.com/gosnmp/gosnmp v1.33.0
 	github.com/grid-x/modbus v0.0.0-20210224155242-c4a3d042e99b
-	github.com/gwos/tcg/sdk v0.0.0-20211130162655-32ad77586ccf
+	github.com/grid-x/serial v0.0.0-20191104121038-e24bc9bf6f08 // indirect
```
Comment (sspaink) [inline go.mod:71]: Can you run `go mod tidy`? These indirect dependencies should be moved to the second require block, not sure why it isn't being enforced by Go yet.

File: plugins/outputs/groundwork/README.md [hunk 11]
```diff
@@ -36,3 +36,7 @@ This plugin writes to a [GroundWork Monitor][1] instance. Plugin only supports G
 * unitType - to use in monitoring contexts(subset of The Unified Code for Units of Measure standard). Supported types: "1", "%cpu", "KB", "GB", "MB".
 * warning  - to define warning threshold value.
 * critical - to define critical threshold value.
+
+## NOTE
+
+The current version of the plugin does not support metrics whose values are strings. Such metrics will be skipped and will not be added to the final payload.
```
Comment (sspaink) [inline plugins/outputs/groundwork/README.md:42]:
```suggestion
The current version of Groundworks does not support metrics whose values are strings. Such metrics will be skipped and will not be added to the final payload. You can find more context in this pull request: [#10255]( https://github.com/influxdata/telegraf/pull/10255)
```

Comment (sspaink) [reply plugins/outputs/groundwork/README.md:42]: nitpick, but in case a future user stumbles on this then they will know to look at Groundworks for this feature.

**Review by sspaink — CHANGES_REQUESTED** [review]

File: go.mod (hunk 10 above)
Comment (ymkins) [reply go.mod]: done

File: plugins/outputs/groundwork/README.md (hunk 11 above)
Comment (ymkins) [reply plugins/outputs/groundwork/README.md]: done

**Review by sspaink — APPROVED** [review]
lgtm! there are some linter issues that need to be resolved before this can be merged.

File: plugins/outputs/groundwork/README.md [hunk 12]
```diff
@@ -32,7 +32,18 @@ This plugin writes to a [GroundWork Monitor][1] instance. Plugin only supports G
 
 * service  - to define the name of the service you want to monitor.
 * status   - to define the status of the service.
+   * Valid Values are:
+   * Ok = "SERVICE_OK"
+   * Unscheduled Warning = "SERVICE_UNSCHEDULED_WARNING"
+   * Unscheduled Critical = "SERVICE_UNSCHEDULED_CRITICAL"
+   * Pending = "SERVICE_PENDING"
+   * Scheduled Critical = "SERVICE_SCHEDULED_CRITICAL"
+   * Unknown = "SERVICE_UNKNOWN"
```
Comment (sspaink) [inline plugins/outputs/groundwork/README.md:41]: Linter is complaining about `Unordered list indentation [Expected: 2; Actual: 3]`

```suggestion
  * Valid Values are:
  * Ok = "SERVICE_OK"
  * Unscheduled Warning = "SERVICE_UNSCHEDULED_WARNING"
  * Unscheduled Critical = "SERVICE_UNSCHEDULED_CRITICAL"
  * Pending = "SERVICE_PENDING"
  * Scheduled Critical = "SERVICE_SCHEDULED_CRITICAL"
  * Unknown = "SERVICE_UNKNOWN"
```

File: plugins/outputs/groundwork/README.md [hunk 13]
```diff
@@ -31,8 +31,12 @@ This plugin writes to a [GroundWork Monitor][1] instance. Plugin only supports G
...
-* status   - to define the status of the service.
+* status   - to define the status of the service. Supported statuses: "SERVICE_OK", "SERVICE_WARNING", "SERVICE_UNSCHEDULED_CRITICAL", "SERVICE_PENDING", "SERVICE_SCHEDULED_CRITICAL", "SERVICE_UNKNOWN".
 * message  - to provide any message you want.
 * unitType - to use in monitoring contexts(subset of The Unified Code for Units of Measure standard). Supported types: "1", "%cpu", "KB", "GB", "MB".
 * warning  - to define warning threshold value.
 * critical - to define critical threshold value.
+
+## NOTE
+
+The current version of Groundworks does not support metrics whose values are strings. Such metrics will be skipped and will not be added to the final payload. You can find more context in this pull request: [#10255]( https://github.com/influxdata/telegraf/pull/10255)
```
Comment (Hipska) [inline plugins/outputs/groundwork/README.md:42]: The name of the product is GroundWork Monitor, see https://www.gwos.com/product/groundwork-monitor/
```suggestion
The current version of GroundWork Monitor does not support metrics whose values are strings. Such metrics will be skipped and will not be added to the final payload. You can find more context in this pull request: [#10255]( https://github.com/influxdata/telegraf/pull/10255)
```

**Review by Hipska — CHANGES_REQUESTED** [review]
I'm getting log outputs like these:
```log
I! [outputs.groundwork] Authenticate password status:200 method:"PUT" url:"http://groundwork:8080/api/users/authenticatePassword"
I! [outputs.groundwork] Send request method:"POST" url:"http://groundwork:8080/api/monitoring?dynamic=true" status:200
```
Those should be debugging output and not INFO.
They are also not consistent, but I think that depends on external library? Order I would expect the fields: url, method, status

File: plugins/outputs/groundwork/README.md (hunk 13 above)
Comment (VladislavSenkevich) [reply plugins/outputs/groundwork/README.md]: Fixed

**Comment by VladislavSenkevich** [comment]
> I'm getting log outputs like these:
> 
> ```
> I! [outputs.groundwork] Authenticate password status:200 method:"PUT" url:"http://groundwork:8080/api/users/authenticatePassword"
> I! [outputs.groundwork] Send request method:"POST" url:"http://groundwork:8080/api/monitoring?dynamic=true" status:200
> ```
> 
> Those should be debugging output and not INFO. They are also not consistent, but I think that depends on external library? Order I would expect the fields: url, method, status

@ymkins fixed that in the last commit

**Review by Hipska — APPROVED** [review]
Whoa, it is now showing a lot more, but I think that's okay since it is debug mode.

Seems good to me!

**Review by powersj — APPROVED** [review]
