### PR TITLE
Fix gzip support in socket_listener with tcp sockets

### LINKED ISSUE #7377: `socket_listener` unable to decode compressed TCP payloads
### Relevant telegraf.conf:

```toml
[[inputs.socket_listener]]
  service_address = "tcp://:8096"
  data_format = "influx"
  content_encoding = "gzip"
```

### System info:
Telegraf: Telegraf 1.14.0 (git: HEAD fefd7ff1)
OS: Windows Server 2016 Standard - Version 1607 build 14393.3630

Telegraf installed as a Windows Service by `telegraf.exe`

### Steps to reproduce:

1. Start a Telegraf instance listening with `socket_listener` with the provided configuration to listen for TCP connections with `gzip` compressed payloads
2. Write compressed line protocol messages to the TCP socket that Telegraf is listening on
    1. This can be done with the build artifact from [abandoned PR 7355](https://github.com/influxdata/telegraf/pull/7355)

### Expected behavior:

Telegraf can decode and consume line protocol messages compressed with gzip on a TCP socket

### Actual behavior:

Telegraf unable to decode and consume line protocol messages compressed with gzip on a TCP socket

### Additional info:

Log file messages:
```
2020-04-20T20:13:46Z I! [inputs.socket_listener] Listening on tcp://[::]:8096
2020-04-20T20:14:50Z E! [inputs.socket_listener] Unable to decode incoming line: unexpected EOF
2020-04-20T20:14:50Z E! [inputs.socket_listener] Unable to decode incoming line: gzip: invalid header
...
```
[Telegraf_CompressedTCP.pcapng.zip](https://github.com/influxdata/telegraf/files/4505991/Telegraf_CompressedTCP.pcapng.zip)

### PR DESCRIPTION
**Pull request by danielnelson**
closes #7377

### Required for all PRs:

- [ ] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

File: internal/content_coding.go [hunk 1]
```diff
@@ -1,18 +1,115 @@
...
+	"bufio"
 	"bytes"
 	"compress/gzip"
 	"errors"
 	"io"
 )
 
+// NewStreamContentEncoder returns a writer that will encode the stream
+// according to the encoding type.
+func NewStreamContentEncoder(encoding string, w io.Writer) (io.Writer, error) {
```
Comment (reimda) [inline internal/content_coding.go:13]: This isn't used outside of tests.  Are you planning to use it later?

File: internal/content_coding.go [hunk 2]
```diff
@@ -1,18 +1,115 @@
...
+	w io.Writer
+	z *gzip.Writer
+}
+
+func NewGzipWriter(w io.Writer) (io.Writer, error) {
+	return &GzipWriter{w: w, z: new(gzip.Writer)}, nil
+}
+
+func (w *GzipWriter) Write(p []byte) (int, error) {
+	w.z.Reset(w.w)
```
Comment (reimda) [inline internal/content_coding.go:50]: I'm not sure why we start a new gzip stream for each write.  Doesn't this prevent the gzip algorithm from getting enough state to compress well?

File: plugins/inputs/socket_listener/socket_listener.go [hunk 3]
```diff
@@ -111,7 +111,12 @@ func (ssl *streamSocketListener) read(c net.Conn) {
 	defer ssl.removeConnection(c)
 	defer c.Close()
 
-	scnr := bufio.NewScanner(c)
+	decoder, err := internal.NewStreamContentDecoder(ssl.ContentEncoding, c)
+	if err != nil {
+		ssl.Log.Error("Read error: %v", err)
+	}
+
+	scnr := bufio.NewScanner(decoder)
```
Comment (reimda) [inline plugins/inputs/socket_listener/socket_listener.go:119]: We always wrap with decoder here.  Wrapping makes sense to me for gzip, but not for identity.  If identity, why not pass in c and not wrap at all?

File: internal/content_coding.go (hunk 1 above)
Comment (danielnelson) [reply internal/content_coding.go:13]: I'll remove it for now, originally was planning to use it in the socket_writer but ended up leaving it with the batching version.  Potentially we could use something like this to reduce memory usage.

File: internal/content_coding.go (hunk 2 above)
Comment (danielnelson) [reply internal/content_coding.go:50]: It would if the write is small, my idea here was that it would be nice to be able to read each batch.  I'm going to remove the Writer completely for now since it isn't used and we can sort this out later.

File: plugins/inputs/socket_listener/socket_listener.go (hunk 3 above)
Comment (danielnelson) [reply plugins/inputs/socket_listener/socket_listener.go:119]: In the 'identity' case, internal.NewStreamContentDecoder is just returning the reader unwrapped.  I thought it would be a bit nicer to push the switch logic into this factory function.

**Comment by danielnelson** [comment]
I removed the GzipWriter related code, didn't end up using it for now so we can revive and complete it when we have the need.

**Comment by m4ce** [comment]
@danielnelson - I tested this PR and I am seeing issues. I see random TCP disconnects when sending data.
