### PR TITLE
Fix #1827 - multi instances in win_perf_counters

### LINKED ISSUE #1827: Telegraf issues with Windows multi instance processes
## Bug report

I noticed in Grafana that some Windows process % Processor Time was incorrect on one server for one process. The process is called UserMonitor showed as using 100 % CPU for almost all the time. 

image

Doublechecking the perfmon on the Windows Server showed that this process was actually only using +- 8 % CPU.

image

The config in Grafana:

image

And a query qhowing the UserMonitor process data coming in as 100%:

image
### Relevant telegraf.conf:

```
  [[inputs.win_perf_counters.object]]
    ObjectName = "Process"
    Counters = ["% Processor Time","Pool Nonpaged Bytes","Pool Paged Bytes","Working Set - Private"]
    Instances = ["*"]
    Measurement = "win_processes"
    IncludeTotal=true
```
### System info:

Telegraf 1.0.0
Windows Server 2012 R2

### PR DESCRIPTION
**Pull request by bullshit**
### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [ ] README.md updated (if adding a new plugin)

This PR fixes #1827. If you are using multiple instances identifier like "w3wp#1" the phd.dll returns only 2 characters in the SzName var. To be sure it is an error from the dll it self, i try to use phd.dll with c++
[c++ source](https://gist.github.com/bullshit/a75f9c57bb03f9863a4cee66375c3f1e#file-phdtest-cpp)

### Screenshot
| Instance=chrome#4        | Instance=chrome | 
| ------------- |:-------------:| 
|single instance|multi instance

As a fix i look if the configured instance name contains a "#". If this is true i look if the  instance name starts with returned instance name.

### CODE REVIEW

**Comment by bullshit** [comment]
Is there anything i can do, to support the contributors to merge this PR?

File: plugins/inputs/win_perf_counters/win_perf_counters.go [hunk 1]
```diff
@@ -265,6 +265,11 @@ func (m *Win_PerfCounters) Gather(acc telegraf.Accumulator) error {
 					} else if metric.instance == s {
 						// Catch if we set it to total or some form of it
 						add = true
+					} else if strings.Contains(metric.instance, "#") && strings.HasPrefix(metric.instance, s) {
```
Comment (danielnelson) [inline plugins/inputs/win_perf_counters/win_perf_counters.go]: Is this function iterating over all processes on the system?  If so and if metric.instance = "chrome#4", what about processes named, for instance, `cha`?  Would it be misnamed by this?

File: plugins/inputs/win_perf_counters/win_perf_counters.go [hunk 2]
```diff
@@ -265,6 +265,11 @@ func (m *Win_PerfCounters) Gather(acc telegraf.Accumulator) error {
...
+						// FIX: #1827
```
Comment (danielnelson) [inline plugins/inputs/win_perf_counters/win_perf_counters.go]: Remove this line

File: plugins/inputs/win_perf_counters/win_perf_counters.go [hunk 3]
```diff
@@ -265,6 +265,11 @@ func (m *Win_PerfCounters) Gather(acc telegraf.Accumulator) error {
...
+						// phd.dll only returns first 2 characters of the instance name
```
Comment (danielnelson) [inline plugins/inputs/win_perf_counters/win_perf_counters.go]: Please expand on this a bit, when does it only return 2 characters of the instance name?

**Comment by danielnelson** [comment]
If anyone running windows can test and report back it would be very helpful.

File: plugins/inputs/win_perf_counters/win_perf_counters.go (hunk 3 above)
Comment (bullshit) [inline plugins/inputs/win_perf_counters/win_perf_counters.go]: Did you read the pull request description?
> If you are using multiple instances identifier like "w3wp#1" the phd.dll returns only 2 characters in the SzName var. To be sure it is an error from the dll it self, i try to use phd.dll with c++

File: plugins/inputs/win_perf_counters/win_perf_counters.go (hunk 2 above)
Comment (bullshit) [inline plugins/inputs/win_perf_counters/win_perf_counters.go]: Ok

File: plugins/inputs/win_perf_counters/win_perf_counters.go (hunk 1 above)
Comment (bullshit) [inline plugins/inputs/win_perf_counters/win_perf_counters.go]: No this funktion is iterating over all process that are retrieved for the specific counter instances

**Comment by bullshit** [comment]
Currently, i'm running my changes in a production environment since january on 14 servers without any troubles

File: plugins/inputs/win_perf_counters/win_perf_counters.go (hunk 3 above)
Comment (danielnelson) [inline plugins/inputs/win_perf_counters/win_perf_counters.go]: Okay, so change the comment to: "If you are using a multiple instance identifier such as "w3wp#1" phd.dll returns only the first 2 characters of the identifier."

File: plugins/inputs/win_perf_counters/win_perf_counters.go (hunk 1 above)
Comment (danielnelson) [inline plugins/inputs/win_perf_counters/win_perf_counters.go]: What about the possibility of a process prefix collision, can it happen if matching all instances?  Should we test that s is length 2?

Comment (bullshit) [inline plugins/inputs/win_perf_counters/win_perf_counters.go]: In my opinion it is impossible, because telegraf creates for every configured instance and WPC combination a unique [query](https://github.com/bullshit/telegraf/blob/fix-1827-win_perf_counters/plugins/inputs/win_perf_counters/win_perf_counters.go#L165) and [handle](https://github.com/bullshit/telegraf/blob/fix-1827-win_perf_counters/plugins/inputs/win_perf_counters/win_perf_counters.go#L125) to [fetch](https://github.com/bullshit/telegraf/blob/fix-1827-win_perf_counters/plugins/inputs/win_perf_counters/win_perf_counters.go#L251]) the counter data.

for example:
```
[[inputs.win_perf_counters.object]]
  ObjectName = "Process"
  Counters = ["% Processor Time"]
  Instances = ["chrome","chrome#4"]
  Measurement = "win_chrome_cpu"
```

```
Valid: \Process(chrome)\% Processor Time
Valid: \Process(chrome#4)\% Processor Time
win_chrome_cpu,instance=chrome,objectname=Process,host=winston-pc Percent_Processor_Time=0.16016027331352234 1490095720000000000
win_chrome_cpu,instance=chrome#4,objectname=Process,host=winston-pc Percent_Processor_Time=0 1490095720000000000
```

for the instance "chrome" there are no problems, but because phd returns for the query `\Process(chrome#4)\% Processor Time` only `ch` as instance name the if statment at [win_perf_counters.go#L265](https://github.com/bullshit/telegraf/blob/fix-1827-win_perf_counters/plugins/inputs/win_perf_counters/win_perf_counters.go#L265) isn't working. Thats the reason why i check if the configured instance name contains an hash and, just to be sure, the returned name from phd starts like the configured name. If phd.dll will be fixed in the future my changes won't be executed because of the previous else if statment on line [win_perf_counters.go#L265](https://github.com/bullshit/telegraf/blob/fix-1827-win_perf_counters/plugins/inputs/win_perf_counters/win_perf_counters.go#L265). I don't see any reason why there should be a process prefix collision.

**Comment by danielnelson** [comment]
Can you update the CHANGELOG.md before I merge?

**Comment by discoduck2x** [comment]
@danielnelson @bullshit is this now included on the telegraf download page for win? or do i have to wait for next proper version release (our build myself) ?

**Comment by danielnelson** [comment]
It will be in the upcoming 1.3.0 release.  We have nightly builds available though, this link should always have the latest build: https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly_windows_amd64.zip

**Comment by dudusakharovich** [comment]
@danielnelson - I have the same issue, where telegraf can't retrieve data from all "w3wp" instances.
This is my configuration:

[[inputs.win_perf_counters.object]]
    ObjectName = "Process"
    Counters = ["% Processor Time","Handle Count","Private Bytes","Thread Count","Virtual Bytes","Working Set"]
    Instances = ["*"]
    Measurement = "win_proc"
    IncludeTotal=true 

I can only see data retrieved for one "w3wp" instance instead of 3 (w3wp, w3wp#1 & w3wp#2).
What is wrong with my configuration ?
