### PR TITLE
fix(inputs.ntpq): Fix ntpq field misalignment parsing errors

### LINKED ISSUE #17147: ntpq input plugin cannot parse "-" value in "when" field when a ntp pool is configured
### Relevant telegraf.conf

```toml
[[inputs.ntpq]]
  options = "-pn"
```

### Logs from Telegraf

```text
E! [inputs.ntpq] Error in plugin: parsing "when" (when) as duration failed: strconv.ParseInt: parsing "when": invalid syntax
```

### System info

Telegraf 1.34.4 (git: HEAD@e7ce1e1e), ntpq ntpsec-1.2.2 (debian 12.11)

### Docker

_No response_

### Steps to reproduce

Configure a pool for the ntp server:
```
pool -4 0.gr.pool.ntp.org maxpoll 7 iburst
pool -4 1.gr.pool.ntp.org maxpoll 7 iburst
pool -4 2.gr.pool.ntp.org maxpoll 7 iburst
pool -4 3.gr.pool.ntp.org maxpoll 7 iburst
```
then `ntpq -pn` will produce:
```
     remote                                   refid      st t when poll reach   delay   offset   jitter
=======================================================================================================
 0.gr.pool.ntp.org                       .POOL.          16 p    -   64    0   0.0000   0.0000   0.0001
 1.gr.pool.ntp.org                       .POOL.          16 p    -   64    0   0.0000   0.0000   0.0001
 2.gr.pool.ntp.org                       .POOL.          16 p    -   64    0   0.0000   0.0000   0.0001
 3.gr.pool.ntp.org                       .POOL.          16 p    -   64    0   0.0000   0.0000   0.0001
```

### Expected behavior

parse ntpq output without errors

### Actual behavior

Parsing errors, starting with:
`E! [inputs.ntpq] Error in plugin: parsing "when" (when) as duration failed: strconv.ParseInt: parsing "when": invalid syntax`

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skartikey**
## Summary

The ntpq input plugin was failing to parse output when NTP pool configurations were used, resulting in cryptic parsing errors like:

```
E! [inputs.ntpq] Error in plugin: parsing "when" (when) as duration failed: strconv.ParseInt: parsing "when": invalid syntax
```

This occurred when `ntpq -pn` output contained pool entries that caused field misalignment, where column header names appeared as data values instead of actual field values.

### Root Cause

The issue was caused by **field misalignment** in ntpq output where:
1. The parser correctly detected column headers: `["remote", "refid", "st", "t", "when", "poll", "reach", "delay", "offset", "jitter"]`
2. But malformed data lines contained literal column names as values: `["remote", "refid", "st", "t", "when", "poll", "reach", "delay", "offset", "jitter"]`
3. The parser attempted to parse the string "when" as a duration value, causing `strconv.ParseInt` to fail

This commonly happened with:
- NTP pool configurations
- Corrupted ntpq output
- Lines where field alignment was disrupted

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #17147

### CODE REVIEW

File: plugins/inputs/ntpq/ntpq.go [hunk 1]
```diff
@@ -219,66 +219,86 @@ func (n *NTPQ) gatherServer(acc telegraf.Accumulator, server string) {
 				continue
 			case tag:
 				tags[col.name] = raw
-			case fieldFloat:
```
Comment (srebhan) [inline plugins/inputs/ntpq/ntpq.go:222]: How about replacing this whole `switch` block with

```golang
			// Handle tags, empty or invalid entries
			switch col.etype {
			case none:
				continue
			case tag:
				tags[col.name] = raw
				continue
			default:
				// Common validation for all field types to detect misalignment
				if raw == col.name {
					// Field misalignment detected - skip this field
					acc.AddError(fmt.Errorf("%sfield misalignment detected: got column name %q instead of value", msgPrefix, raw))
					continue
				}
			}

			// Handle empty or whitespace-only values
			if strings.TrimSpace(raw) == "" {
				continue
			}

			// Do the actual parsing
			switch col.etype {
			case fieldFloat:
				value, err := strconv.ParseFloat(raw, 64)
				if err != nil {
					msg := fmt.Sprintf("%sparsing %q (%v) as float failed", msgPrefix, col.name, raw)
					acc.AddError(fmt.Errorf("%s: %w", msg, err))
					continue
				}
				fields[col.name] = value
			case fieldDuration:
				// Ignore fields only containing a minus
				if raw == "-" {
					continue
				}
				factor := int64(1)
				suffix := raw[len(raw)-1:]
				switch suffix {
				case "d":
					factor = 24 * 3600
				case "h":
					factor = 3600
				case "m":
					factor = 60
				default:
					suffix = ""
				}
				value, err := strconv.ParseInt(strings.TrimSuffix(raw, suffix), 10, 64)
				if err != nil {
					msg := fmt.Sprintf("%sparsing %q (%v) as duration failed", msgPrefix, col.name, raw)
					acc.AddError(fmt.Errorf("%s: %w", msg, err))
					continue
				}
				fields[col.name] = value * factor
			case fieldIntDecimal:
				value, err := strconv.ParseInt(raw, 10, 64)
				if err != nil {
					msg := fmt.Sprintf("%sparsing %q (%v) as int failed", msgPrefix, col.name, raw)
					acc.AddError(fmt.Errorf("%s: %w", msg, err))
					continue
				}
				fields[col.name] = value
			case fieldIntOctal:
				value, err := strconv.ParseInt(raw, 8, 64)
				if err != nil {
					msg := fmt.Sprintf("%sparsing %q (%v) as int failed", msgPrefix, col.name, raw)
					acc.AddError(fmt.Errorf("%s: %w", msg, err))
					continue
				}
				fields[col.name] = value
			case fieldIntBits:
				value, err := strconv.ParseUint(raw, 8, 64)
				if err != nil {
					msg := fmt.Sprintf("%sparsing %q (%v) as int failed", msgPrefix, col.name, raw)
					acc.AddError(fmt.Errorf("%s: %w", msg, err))
					continue
				}
				fields[col.name] = bits.OnesCount64(value)
			case fieldIntRatio8:
				value, err := strconv.ParseUint(raw, 8, 64)
				if err != nil {
					msg := fmt.Sprintf("%sparsing %q (%v) as int failed", msgPrefix, col.name, raw)
					acc.AddError(fmt.Errorf("%s: %w", msg, err))
					continue
				}
				fields[col.name] = float64(bits.OnesCount64(value)) / float64(8)
			}
```

**Review by srebhan — COMMENTED** [review]
@skartikey looks good. Just one suggestion to split the `switch` block for more readability and less indentation.

File: plugins/inputs/ntpq/ntpq.go (hunk 1 above)
Comment (skartikey) [reply plugins/inputs/ntpq/ntpq.go:222]: @srebhan Thanks! I've made the changes.

**Review by mstrandboge — APPROVED** [review]
