### PR TITLE
fix(parsers.csv): Remove direct checks for the parser type

### LINKED ISSUE #11820: Inputs don't know that parsers are wrapped in runningparser
#11811 happens because the exec plugin has a special case when using the nagios parser. Since the parser plugin refactor the parser passed to the plugin is wrapped in a runningparser. This causes the exec plugin's special case to fail.

To fix this, either the plugin must not be wrapped or each input with special case will need to expect the runningparser wrapper

There are other plugins with this problem:
* https://github.com/influxdata/telegraf/blob/21a7d6fcbe8cfdee18fe62518575bd4b0446d223/plugins/inputs/exec/exec.go#L137
* https://github.com/influxdata/telegraf/blob/21a7d6fcbe8cfdee18fe62518575bd4b0446d223/plugins/inputs/execd/execd.go#L76
* https://github.com/influxdata/telegraf/blob/21a7d6fcbe8cfdee18fe62518575bd4b0446d223/plugins/inputs/directory_monitor/directory_monitor.go#L296
* https://github.com/influxdata/telegraf/blob/21a7d6fcbe8cfdee18fe62518575bd4b0446d223/plugins/inputs/tail/tail.go#L237

Since 1.24.0 is the first release with the parser plugin refactor, and it was only released this week, we should fix this and include it in a bugfix release quickly.

### PR DESCRIPTION
**Pull request by srebhan**
- [ ] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format]

partially resolves #11820 

This PR introduces a new error (`ErrNotEnoughData`) for parsers that need to consume more data to output metrics. This is the case for CSV when fed linewise with skipping rows, metadata or other headers involved.

As a consequence, we can remove the direct check for the CSV parser in `inputs.tail` and `inputs.directory_monitor` and open the possibility for other parsers to also use this error.

### CODE REVIEW

**Review by MyaLongmire — APPROVED** [review]

File: plugins/parsers/csv/parser.go [hunk 1]
```diff
@@ -197,23 +198,30 @@ func (p *Parser) Parse(buf []byte) ([]telegraf.Metric, error) {
 	}
 
 	r := bytes.NewReader(buf)
-	return parseCSV(p, r)
+	metrics, err := parseCSV(p, r)
+	if err != nil && errors.Is(err, io.EOF) {
+		return nil, parsers.ErrNotEnoughData
```
Comment (reimda) [inline plugins/parsers/csv/parser.go:203]: I'm not sure I understand the new parsers.ErrNotEnoughData error. Doesn't io.EOF conceptually also mean there isn't enough data? Is the difference that the new error is returned when the parser expects more data eventually and EOF is final with no chance of more data?

Comment (srebhan) [reply plugins/parsers/csv/parser.go:203]: The idea was to not reuse the existing error to minimize side-effects for non-CSV parsers that also might return `io.EOF`. By using a new error and only apply it to CSV we can be sure that the previous `if` condition is still there...

**Review by reimda — APPROVED** [review]

**Comment by reimda** [comment]
This fixes the bug caused by the last two wrapped parsers listed in #11820. It's a fix for the regression in 1.24.0 and should be included in 1.24.1.

When we have more time, we should revisit the approach of using a parser specific error (originally parsers.ErrNotEnoughData in this PR but now named parsers.ErrEOF). If the input plugin is always going to ignore the error, it would be simpler if the parser didn't return an error to begin with. Maybe parsers whose Parse methods calls their own ParseLine method need it?

If we do decide parsers.ErrEOF is needed, we should check the other parsers besides csv and update them to use it. For example, xml could return it if it hasn't received data including a closing tag, and influx could use it when it has received part of a line but not the end of line character.
