### PR TITLE
fix(inputs.kinesis_consumer): Ignore expired parent shards

### LINKED ISSUE #17871: [[inputs.kinesis_consumer]] Kinesis Consumer does not consume messages since v1.34.0
### Relevant telegraf.conf

```toml
[agent]
  debug = true
  quiet = false
  metric_batch_size = 5000
  metric_buffer_limit = 50000

[[inputs.kinesis_consumer]]
  region = "${AWS_REGION}"
  streamname = "${KINESIS_STREAM_NAME}"
  role_arn = "${KINESIS_ROLE_ARN}"
  data_format = "value"
  data_type = "string"

  [inputs.kinesis_consumer.checkpoint_dynamodb]
    app_name = "${KINESIS_CHECKPOINT_DYNAMODB_APP_NAME}"
    table_name = "${KINESIS_CHECKPOINT_DYNAMODB_TABLE_NAME}"
```

### Logs from Telegraf

```text
I! Loading config: /etc/telegraf/telegraf.conf
I! Starting Telegraf 1.34.0 brought to you by InfluxData the makers of InfluxDB
I! Available plugins: 239 inputs, 9 aggregators, 33 processors, 26 parsers, 63 outputs, 6 secret-stores
I! Loaded inputs: kinesis_consumer
I! Loaded aggregators:
I! Loaded processors: starlark
I! Loaded secretstores:
I! Loaded outputs: file
I! Tags enabled: host=0df117d65da4
I! [agent] Config: Interval:10s, Quiet:false, Hostname:"0df117d65da4", Flush Interval:10s
W! [agent] The default value of 'skip_processors_after_aggregators' will change to 'true' with Telegraf v1.40.0! If you need the current default behavior, please explicitly set the option to 'false'!
D! [agent] Initializing plugins
D! [agent] Connecting outputs
D! [agent] Attempting connection to [outputs.file]
D! [agent] Successfully connected to outputs.file
D! [agent] Starting service inputs
D! [outputs.file] Buffer fullness: 0 / 50000 metrics
D! [outputs.file] Buffer fullness: 0 / 50000 metrics
D! [outputs.file] Buffer fullness: 0 / 50000 metrics
```

### System info

Telegraf 1.34.0, Docker on MacOS and/or ECS Fargate

### Docker

The following PR appears to have broken the Kinesis Consumer: [influxdata/telegraf#16332](https://github.com/influxdata/telegraf/pull/16332)

In our environment, we are using a Kinesis Data Stream configured in On-Demand mode. Starting from Telegraf v1.34.0, the Kinesis Consumer does not consume messages from streams that have approximately 20 shards. No errors are reported, even with debug logging enabled.

The consumer appears to work correctly with streams containing fewer than 5 shards.

When downgrading to v1.33.3 - everything works as expected.

### Steps to reproduce

1. Create a Kinesis Data Stream in On-Demand mode.
2. Increase the number of shards (e.g., ~20).
3. Configure Telegraf with the Kinesis Consumer plugin.
4. Start Telegraf and monitor the logs.

### Expected behavior

Messages should be consumed from a stream

### Actual behavior

Messages are not consumed from a stream

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by srebhan**
## Summary

When consuming Kinesis shards the code tries to begin as early as possible which, when resharding occured, means to start at the parent shards. However, in some cases the parent shards are already expired and therefore not accessible anymore (see [documentation](https://docs.aws.amazon.com/streams/latest/dev/kinesis-using-sdk-java-after-resharding.html#kinesis-using-sdk-java-resharding-data-routing)).

In the current code, this case is not handled and we rely on the parent shard being among the listed available shards. This assumption does not hold true for expired parent shards and thus the complete shard subgraph is not consumed.

This PR checks for expired parent shards and start consuming the present child shard in those cases.

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #17871

### CODE REVIEW

File: plugins/inputs/kinesis_consumer/consumer.go [hunk 1]
```diff
@@ -268,16 +270,31 @@ func (c *consumer) updateShardConsumers(ctx context.Context) error {
...
+			// The parent shard might be expired and thus not available anymore.
+			// In those cases, we need to start consuming the child shard
+			// instead. Data in the parent shard is lost.
+			if availableShardIDs[pid] {
+				if !c.shardsConsumed[pid] {
+					c.log.Tracef("shard %s has parent %s which is not fully consumed yet...", id, pid)
+					continue
+				}
+			} else {
+				c.log.Tracef("shard %s has parent %s which is is expired...", id, pid)
```
Comment (skartikey) [inline plugins/inputs/kinesis_consumer/consumer.go]:
```suggestion
				c.log.Tracef("shard %s has parent %s which is expired...", id, pid)
```

File: plugins/inputs/kinesis_consumer/consumer.go [hunk 2]
```diff
@@ -268,16 +270,31 @@ func (c *consumer) updateShardConsumers(ctx context.Context) error {
...
+			// The parent shard might be expired and thus not available anymore.
+			// In those cases, we need to start consuming the child shard
+			// instead. Data in the parent shard is lost.
+			if availableShardIDs[pid] {
+				if !c.shardsConsumed[pid] {
+					c.log.Tracef("shard %s has adjacent parent %s which is not fully consumed yet...", id, pid)
+					continue
+				}
+			} else {
+				c.log.Tracef("shard %s has adjacent parent %s which is is expired...", id, pid)
```
Comment (skartikey) [inline plugins/inputs/kinesis_consumer/consumer.go]:
```suggestion
				c.log.Tracef("shard %s has adjacent parent %s which is expired...", id, pid)
```

File: plugins/inputs/kinesis_consumer/consumer.go [hunk 3]
```diff
@@ -268,16 +270,31 @@ func (c *consumer) updateShardConsumers(ctx context.Context) error {
...
+				if !c.shardsConsumed[pid] {
+					c.log.Tracef("shard %s has parent %s which is not fully consumed yet...", id, pid)
+					continue
+				}
+			} else {
+				c.log.Tracef("shard %s has parent %s which is is expired...", id, pid)
 			}
 		}
-		if shard.AdjacentParentShardId != nil && *shard.AdjacentParentShardId != "" {
+		if shard.AdjacentParentShardId != nil && *shard.AdjacentParentShardId != "" && availableShardIDs[*shard.AdjacentParentShardId] {
```
Comment (skartikey) [inline plugins/inputs/kinesis_consumer/consumer.go]: The outer if adds && availableShardIDs[*shard.AdjacentParentShardId] which makes the inner if availableShardIDs[pid] always true. The else branch logging the expired adjacent parent is unreachable (dead code). When an adjacent parent is expired, the code doesn't log it (though it does handle it correctly by skipping the block and proceeding to consume the child)

So, how about removing `&& availableShardIDs[*shard]?AdjacentParentShardId]` from the outer if condition to match the ParentShardId logic:
```suggestion
		if shard.AdjacentParentShardId != nil && *shard.AdjacentParentShardId != "" {
```

Comment (srebhan) [reply plugins/inputs/kinesis_consumer/consumer.go]: Good catch!
