### PR TITLE
fix(outputs.graylog): Reconnect transparently when TCP peer closes connection

### LINKED ISSUE #18737: [[outputs.graylog]] Seems not to recognize closed connections correctly
### Relevant telegraf.conf

```toml
n/a
```

### Logs from Telegraf

```text
Error writing to outputs.graylog::aliasname: error writing message
write tcp IP:PORT->IP:PORT: write: broken pipe
```

### System info

Telegraf v1.38.2

### Docker

_No response_

### Steps to reproduce

Use Graylog Ouput plugin to send data to endpoint.
Close connection on endpoint gracefully.
When Telegraf want to send new data to log endpoint, Telegraf logs error message.

### Expected behavior

We think its a normal behavior that an endpoint can close its (idle) connection gracefully.
So Telegraf should not log an error message about a closed connection.
Telegraf should only write an error message, when it can not establish a new connection or connection has been closed by endpoint not gracefully.

output.graylog depends on a static connection. So a closed connection should be recognized immediately (and reopen connection immediately and maybe produce a warning) and not just on the next data send attempt.

### Actual behavior

Telegraf does not recognize a closed connection. Only on the next attempt to send, closed connection is recognized and produces immediately an error message.
For clarification: The logs aren't lost; they're resent (but with an error message by telegraf)

### Additional info

Why ist it a problem: We monitor telegraf.log for **errors**. So everytime a (idle) connection is closed by our logging endpoint or loadbalancer, we get an alarm.

### PR DESCRIPTION
**Pull request by skartikey**
## Summary

Retry the write once on failure after reconnecting so a graceful server close no longer surfaces a 'broken pipe' error on every flush. Also rename graylog_test_linux.go to graylog_linux_test.go so the TCP/UDP tests are actually discovered by 'go test' (Go requires the _test.go suffix), and fix two dormant test bugs this uncovers.

## Checklist

- [x] No AI generated code was used in this PR
- [ ] AI generated code used in this PR follows the [InfluxData Policy on AI-Generated Code Contributions][policy]

[policy]: https://www.influxdata.com/ai-generated-code-contributions-policy

## Related issues

resolves #18737

### CODE REVIEW

File: plugins/outputs/graylog/graylog.go [hunk 1]
```diff
@@ -292,25 +292,36 @@ func (g *gelfTCP) Connect() error {
...
+	if err := g.writeFrame(b); err == nil {
+		return nil
+	}
+
+	// The peer may have closed the connection without us noticing because we
+	// only ever write to it. Reconnect and retry the write once before
+	// reporting the error to avoid noisy logs on every graceful close.
+	if err := g.Connect(); err != nil {
+		return err
+	}
```
Comment (srebhan) [inline plugins/outputs/graylog/graylog.go:310]: If the connection fails we should set `g.conn` to `nil` in order to directly trying to reconnect on the next write.

File: plugins/outputs/graylog/graylog_linux_test.go [hunk 2]
```diff
@@ -310,6 +312,11 @@ func TCPServer(t *testing.T, wg *sync.WaitGroup, tlsConfig *tls.Config, errs cha
 		}
 		defer conn.Close()
 
+		fmt.Println("server: receiving packet 3")
+		err = recv(conn)
+		if err != nil {
+			fmt.Println(err)
+		}
```
Comment (srebhan) [inline plugins/outputs/graylog/graylog_linux_test.go:319]: Are these debug leftovers?

**Review by srebhan — COMMENTED** [review]
Thanks @skartikey! I asked the issue reporter to test this PR. Furthermore, I do have two small comments...

File: plugins/outputs/graylog/graylog_linux_test.go (hunk 2 above)
Comment (skartikey) [reply plugins/outputs/graylog/graylog_linux_test.go:319]: Good catch. These are 2016-era debug leftovers from the original helper. Beyond the six `"server: ..."` progress prints, the six `if err != nil { fmt.Println(err) }` blocks actively swallow errors the test should fail on. I'll clean up the whole `TCPServer` helper in a follow-up PR to keep this one focused on the reconnect fix. Happy to fold it in here instead if you'd prefer.

**Review by srebhan — APPROVED** [review]
Thanks you very much @skartikey!
