### PR TITLE
Remove outputs blocking inputs when output is slow

### LINKED ISSUE #2919: Outputs block inputs when batch size is reached
## Bug report
If one of the output plugins become slow it can cause back pressure all the way up through the input plugins and start to block the input plugins from running. 

The reason for this is the channels between the input and output plugins only have a buffer of 100. This should be ok since most of the operations are in memory. The problem ends up being [here](https://github.com/influxdata/telegraf/blob/f93615672b02a41d9bc867bd92bf31c1d777989b/internal/models/running_output.go#L113) where the buffer gets written if the batch size is full. This ends up happening on the same thread that reads from the `outMetricC` channel in the [agent](https://github.com/influxdata/telegraf/blob/f93615672b02a41d9bc867bd92bf31c1d777989b/agent/agent.go#L281)
### Relevant telegraf.conf:
```
# Configuration for telegraf agent
[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 250000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "5s"
  precision = ""
  debug = true
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

## Configuration for influxdb server to send metrics to
[[outputs.influxdb]]
  urls = ["http://localhost:8086"] # required
  database = "telegraf" # required
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"


## Configuration for influxdb server to send metrics to
[[outputs.influxdb]]
  urls = ["http://localhost:8080"] # required
  database = "telegraf" # required
  retention_policy = ""
  write_consistency = "any"
  timeout = "10s"



###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################

# Read metrics about cpu usage
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false

# Read metrics about disk usage by mount point
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs"]

# Read metrics about disk IO by device
[[inputs.diskio]]

# Get kernel statistics from /proc/stat
[[inputs.kernel]]

# Read metrics about memory usage
[[inputs.mem]]

# Read metrics about system load & uptime
[[inputs.system]]

[[inputs.internal]]


###############################################################################
#                            SERVICE INPUT PLUGINS                            #
###############################################################################

 # Influx HTTP write listener
 [[inputs.http_listener]]
   service_address = ":8186"
   read_timeout = "10s"
   write_timeout = "10s"
   max_body_size = 0
   max_line_size = 0
```
### System info:
Telegraf version 1.3.1

### Steps to reproduce:

1. Start simple python httpServer shown below
2. Start telegraf with the provided config
1. Start producing metrics to the http listener, the number of metrics produced should be more than the metricBatchSize
1. start to see log output that looks like
  ```
2017-06-13T22:08:30Z D! Output [influxdb] wrote batch of 1000 metrics in 6.552099ms
2017-06-13T22:08:38Z D! Output [influxdb] wrote batch of 1000 metrics in 8.001152082s
2017-06-13T22:08:38Z D! Output [influxdb] wrote batch of 1000 metrics in 6.412968ms
2017-06-13T22:08:45Z E! Error in plugin [inputs.cpu]: took longer to collect than collection interval (5s)
2017-06-13T22:08:45Z E! Error in plugin [inputs.diskio]: took longer to collect than collection interval (5s)
2017-06-13T22:08:45Z E! Error in plugin [inputs.system]: took longer to collect than collection interval (5s)
2017-06-13T22:08:45Z E! Error in plugin [inputs.internal]: took longer to collect than collection interval (5s)
2017-06-13T22:08:45Z E! Error in plugin [inputs.mem]: took longer to collect than collection interval (5s)
2017-06-13T22:08:45Z E! Error in plugin [inputs.disk]: took longer to collect than collection interval (5s)
2017-06-13T22:08:46Z D! Output [influxdb] wrote batch of 1000 metrics in 8.004440807s
2017-06-13T22:08:46Z D! Output [influxdb] wrote batch of 1000 metrics in 6.244551ms
2017-06-13T22:08:50Z D! Output [influxdb] buffer fullness: 0 / 250000 metrics. 
2017-06-13T22:08:50Z D! Output [influxdb] buffer fullness: 0 / 250000 metrics. 
2017-06-13T22:08:51Z E! Error in plugin [inputs.diskio]: took longer to collect than collection interval (5s)
2017-06-13T22:08:51Z E! Error in plugin [inputs.system]: took longer to collect than collection interval (5s)
2017-06-13T22:08:54Z D! Output [influxdb] wrote batch of 1000 metrics in 8.004885924s
2017-06-13T22:08:54Z D! Output [influxdb] wrote batch of 1000 metrics in 6.013943ms
2017-06-13T22:08:58Z D! Output [influxdb] buffer fullness: 0 / 250000 metrics. 
2017-06-13T22:08:58Z D! Output [influxdb] buffer fullness: 0 / 250000 metrics. 
2017-06-13T22:08:59Z E! Error in plugin [inputs.system]: took longer to collect than collection interval (5s)
2017-06-13T22:09:00Z E! Error in plugin [inputs.disk]: took longer to collect than collection interval (5s)
2017-06-13T22:09:00Z E! Error in plugin [inputs.diskio]: took longer to collect than collection interval (5s)
2017-06-13T22:09:00Z E! Error in plugin [inputs.internal]: took longer to collect than collection interval (5s)
2017-06-13T22:09:00Z E! Error in plugin [inputs.mem]: took longer to collect than collection interval (5s)
2017-06-13T22:09:00Z E! Error in plugin [inputs.cpu]: took longer to collect than collection interval (5s)
```

### Expected behavior:
The expected behavior is for the outputs and the inputs to be independent of each other, meaning all the inputs should write to a buffer and the outputs read from that buffer. This way the outputs can't block the inputs. 
### Actual behavior:
Most of the time the expected behavior happens, except for when the batch size is reached. When the batch size is reached the output happens on that thread which ends up blocking all the inputs. This causes the inputs to take a long time to collect as they get blocked waiting on the metricC channel

### Additional info:
I believe this is the code path that causes the blocking.

* an input calls gather and writes to the accumulator [here](https://github.com/influxdata/telegraf/blob/f93615672b02a41d9bc867bd92bf31c1d777989b/plugins/inputs/system/cpu.go#L105)
* this results in a write channel [here](https://github.com/influxdata/telegraf/blob/f93615672b02a41d9bc867bd92bf31c1d777989b/agent/accumulator.go#L64)
*  which is the channel created [here](https://github.com/influxdata/telegraf/blob/f93615672b02a41d9bc867bd92bf31c1d777989b/agent/agent.go#L341)
* and is the same channel passed to the flusher [here](https://github.com/influxdata/telegraf/blob/f93615672b02a41d9bc867bd92bf31c1d777989b/agent/agent.go#L370)
* The flusher reads from that channel and adds to the outMetricC channel [here](https://github.com/influxdata/telegraf/blob/f93615672b02a41d9bc867bd92bf31c1d777989b/agent/agent.go#L325)
* The outputMetricC channel is read from and then added to the runningOutput [here](https://github.com/influxdata/telegraf/blob/f93615672b02a41d9bc867bd92bf31c1d777989b/agent/agent.go#L286)
* If the buffer is the same as batch size, the output ends up getting invoked [here](https://github.com/influxdata/telegraf/blob/f93615672b02a41d9bc867bd92bf31c1d777989b/internal/models/running_output.go#L115)
* if the output takes a while to execute all the channels can back up since no more reads are happening off of them and ultimately lead to the inputs getting blocked, waiting to be able to write to the accumulator

It seems that the flusher should just write to the buffer and trigger the go routine here to write instead of doing the write inline. This way the flow can still continue and metrics just get buffered

#### Sample python server
This is the sample python http server used for testing that does a sleep. This simulates an output taking too long.

```python
#!/usr/bin/env python

from BaseHTTPServer import HTTPServer, BaseHTTPRequestHandler
from SocketServer import ThreadingMixIn
from optparse import OptionParser
import time

class RequestHandler(BaseHTTPRequestHandler):        
    def do_POST(self):
        stime = 8
        print "sleeping for: " + str(stime)
        time.sleep(stime)       
        self.send_response(204)
        self.end_headers()
        self.wfile.write(" ")
        self.wfile.close()

class ThreadedHTTPServer(ThreadingMixIn, HTTPServer):
    """Handle requests in a separate thread."""

def main():
    port = 8080
    print('Listening on localhost:%s' % port)
    server = ThreadedHTTPServer(('', port), RequestHandler)
    server.serve_forever()

        
if __name__ == "__main__":    
    main()
```

### LINKED ISSUE #3968: How to make input plugin collect data on each  :00:00, :05:00, :10:00, ... ?
### System info:

telegraf-1.5
influxdb-1.5
ubuntu16.04

### Steps to reproduce:

[agent]
  interval = "60s"
  round_interval = true

[[outputs.influxdb]]
  urls = ["http://127.0.0.1:8086"] # required
  database = "test" # required
  precision = "s"

 [[inputs.rabbitmq]]
    interval = "5m"
    url = "http://localhost:15672"
    username = "username"
    password = "password"

### Expected behavior:

time                 consumers messages messages_publish queue
----                 --------- -------- ---------------- -----
2018-04-04T05:**40**:00Z 0         0        0                report_queue

### Actual behavior:

time                 consumers messages messages_publish queue
----                 --------- -------- ---------------- -----
2018-04-04T05:**38**:00Z 0         0        0                report_queue

### Additional info:

How to make telegraf collect data on :05:00, :10:00, :15:00, ...

### LINKED ISSUE #3984: Queue messages are acknowledged immediately when they first should be successfully emitted
## Bug report

This is a known problem but I don't think we have an issue opened explicitly for it.

Telegraf immediately acks incoming queue messages in the various queue consumers.  It does this because there is no mechanism to learn when the metrics has been successfully outputted.

Metrics can be copied, modified, and can cause new metrics to be produced.  A received metric should not be treated as being emitted successfully until all produced metrics are emitted, or there should be some options for configuring this behavior.  The most routine time this occurs is when you have multiple outputs.

When this issue is resolved, it will be possible to use any queue and fully gain the durability properties of the queue.  For example you can run a queue, potentially even locally, with Telegraf writing new metrics to the queue and reading from the queue and sending items read from the queue to the final output.

Example config:
```toml
[[inputs.cpu]]

[[outputs.nats]]
  [inputs.nats.tagdrop]
    telegraf_output = ["influxdb"]

[[inputs.nats_consumer]]
  [inputs.nats.tags]
    telegraf_output = "influxdb"

[[outputs.influxdb]]
  tagexclude = ["telegraf_output"]
  [inputs.nats.tagpass]
    telegraf_output = ["influxdb"]
```

This has been discussed in:
- https://github.com/influxdata/telegraf/issues/2919
- https://github.com/influxdata/telegraf/issues/2905

### System info:

<= Telegraf 1.6.0

### Steps to reproduce:

1. Enable a queue consumer plugin
2. Start Telegraf
3. kill -9 Telegraf

### Expected behavior:

No unemitted metrics are acknowledged

### Actual behavior:

Unemitted metrics are acknowledged

### LINKED ISSUE #4283: Telegraf with Kafka output dies if the TCP connection is terminated
### Relevant telegraf.conf:

[[outputs.kafka]]
  brokers = [ "serverA.localdomain:9093", "serverB.localdomain:9093" ]
  topic = "telegraf"
  routing_tag = ""
  compression_codec = 1
  required_acks = 1
  max_retry = 3
  ssl_ca   = "/etc/ssl/certs/ca-bundle.crt"
  ssl_cert = ""
  ssl_key  = ""
  insecure_skip_verify = false
  sasl_username = ""
  sasl_password = ""
  data_format = "influx"

### System info:

Telegraf 1.6.0 on RHEL6.9 for this particular system. It happened on 10+ systems connected to the same Kafka cluster in the same time frame.

### Steps to reproduce:

Not attempted.

### Expected behavior:

Reconnect to the Kafka cluster without failure after the TCP connection is re-establoished

### Actual behavior:

Panic, had to be started up again.

### Additional info:

There was a network reconfiguration ongoing at the time where the panic happened. This reconfiguration killed ongoing TCP connections.

```
2018-06-13T14:00:11Z I! Reloading Telegraf config
2018-06-13T14:00:11Z I! Hang on, flushing any cached metrics before shutdown
panic: send on closed channel

goroutine 1148670 [running]:
github.com/Shopify/sarama.(*syncProducer).SendMessage(0xc420874120, 0xc4201161b0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/Shopify/sarama/sync_producer.go:100 +0xf5
github.com/influxdata/telegraf/plugins/outputs/kafka.(*Kafka).Write(0xc4203b8dc0, 0xc4203c4630, 0x3, 0x3, 0xc4203c0101, 0xc420b0be68)
        /go/src/github.com/influxdata/telegraf/plugins/outputs/kafka/kafka.go:266 +0x254
github.com/influxdata/telegraf/internal/models.(*RunningOutput).write(0xc42016c640, 0xc4203c4630, 0x3, 0x3, 0x0, 0x0)
        /go/src/github.com/influxdata/telegraf/internal/models/running_output.go:179 +0x104
github.com/influxdata/telegraf/internal/models.(*RunningOutput).Write(0xc42016c640, 0x16248a0, 0xc4202561d0)
        /go/src/github.com/influxdata/telegraf/internal/models/running_output.go:161 +0x476
github.com/influxdata/telegraf/agent.(*Agent).flush.func1(0xc4202561d0, 0xc42016c640)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:238 +0x59
created by github.com/influxdata/telegraf/agent.(*Agent).flush
        /go/src/github.com/influxdata/telegraf/agent/agent.go:236 +0xa2
```

### LINKED ISSUE #4457: Memory leakage in SNMP input
### Relevant telegraf.conf:
```
# grep -R snmp /etc/telegraf/* | grep -Po "inputs\.snmp.+" | grep -Po "[\w\.]+" | sort | uniq -c | sort -h
      1 inputs.snmp.host.table
      1 inputs.snmp_legacy
      2 inputs.snmp.bulk
      3 inputs.snmp.get
      3 inputs.snmp.host
    382 inputs.snmp.tagpass
    940 inputs.snmp.tags
    942 inputs.snmp
   1094 inputs.snmp.table
   1759 inputs.snmp.field
  15220 inputs.snmp.table.field
```
Sample config: https://pastebin.com/x1qWYsYk

### System info:
Telegraf v1.6.0 (git: release-1.6 9253f6fe)
Red Hat Enterprise Linux Server release 7.5 (Maipo)

### Steps to reproduce:

1. Run Telegraf with the SNMP input for longer durations of time
2. Check that the memory usage is increasing over time
3. Eventually the process will consume all the memory on the host and get killed by OOM

### Expected behavior:
That the memory usage were consistent and not increasing over time. 

### Actual behavior:
Telegraf's memory usage seems to increase over time. 

### Additional info:
Graph showing increasing memory usage until the process restarts. 
image

Newly started process
```
(pprof) top10
Showing nodes accounting for 84.14MB, 96.46% of 87.22MB total
Showing top 10 nodes out of 89
      flat  flat%   sum%        cum   cum%
   59.57MB 68.30% 68.30%    64.09MB 73.48%  github.com/soniah/gosnmp.(*GoSNMP).Connect
    7.50MB  8.60% 76.90%     8.57MB  9.82%  github.com/influxdata/telegraf/plugins/inputs/snmp.Table.Build
    4.02MB  4.61% 81.51%     4.02MB  4.61%  math/rand.NewSource
       3MB  3.44% 84.95%        3MB  3.44%  runtime.malg
    2.50MB  2.87% 87.83%     2.50MB  2.87%  reflect.unsafe_NewArray
       2MB  2.29% 90.12%        2MB  2.29%  github.com/influxdata/telegraf/internal/config.buildInput
       2MB  2.29% 92.41%        2MB  2.29%  github.com/influxdata/telegraf/metric.New
    1.76MB  2.02% 94.43%     1.76MB  2.02%  compress/flate.NewWriter
       1MB  1.15% 95.58%        1MB  1.15%  crypto/x509/pkix.(*Name).FillFromRDNSequence
    0.77MB  0.88% 96.46%     0.77MB  0.88%  github.com/zensqlmonitor/go-mssqldb.init
```

After running for several days
```
(pprof) top10
Showing nodes accounting for 784.13MB, 96.14% of 815.64MB total
Dropped 67 nodes (cum <= 4.08MB)
Showing top 10 nodes out of 60
      flat  flat%   sum%        cum   cum%
  465.43MB 57.06% 57.06%   546.85MB 67.05%  github.com/influxdata/telegraf/plugins/inputs/snmp.Table.Build
  188.82MB 23.15% 80.21%   205.40MB 25.18%  github.com/soniah/gosnmp.(*GoSNMP).Connect
   26.50MB  3.25% 83.46%    26.50MB  3.25%  github.com/influxdata/telegraf/plugins/inputs/snmp.fieldConvert
   23.50MB  2.88% 86.34%    23.50MB  2.88%  strconv.formatBits
      23MB  2.82% 89.16%       23MB  2.82%  github.com/soniah/gosnmp.(*GoSNMP).decodeValue
   20.27MB  2.49% 91.65%    23.48MB  2.88%  compress/flate.NewWriter
   15.58MB  1.91% 93.56%    15.58MB  1.91%  math/rand.NewSource
       8MB  0.98% 94.54%    10.50MB  1.29%  github.com/influxdata/telegraf/metric.(*metric).AddField
    6.52MB   0.8% 95.34%     6.52MB   0.8%  reflect.unsafe_NewArray
    6.50MB   0.8% 96.14%     6.50MB   0.8%  runtime.malg
```

pprof png generated from `http://localhost:6060/debug/pprof/heap?debug=1`
profile003

### LINKED ISSUE #4610: 'systemctl restart telegraf' failing (related to logparser ?)
### Relevant telegraf.conf:
Agent runs some basic system metric plus one logparser that parses a preprocessed (sorted) nginx acces.log. The preprocessing script runs every 10 minutes and extracts 10 minutes (in the past, to make sure nginx buffer is flushed) of logdata to a sorted file for ingestion into telegraf logparser (every run about 10.000 lines)

Logparser config (one file in /etc/telegraf/telegraf.d):
  
```
[[inputs.logparser]]
    tagexclude = ["path"]
   files = ["/var/log/nginx/access.log.sorted.10min"]
   from_beginning = true
   watch_method = "inotify"
   [inputs.logparser.grok]
        patterns = ['''
%{CLIENT:client_ip:drop} %{NOTSPACE:ident:drop} %{NOTSPACE:auth:drop} \[%{HTTPDATE:ts:ts-httpd}\] \"%{WORD:http_method:drop} %{PATHLEVEL1:pathlevel1:tag}(\/|\?)?.* HTTP\/%{NUMBER:http_version:drop}\" %{RESPONSE_CODE} (?:%{NUMBER:resp_bytes:int}|-) \"%{DATA:referer:drop}\" \"%{DATA:user_agent:drop}\" +(?:%{NUMBER:request_time:float}|-) %{LOAD_BALANCING_TIMES:lb_times:drop}(?:%{NUMBER:upstream_time:float}|-) %{GREEDYDATA:pipe:drop}+ \"%{GREEDYDATA:gzip_ratio:drop}\" \"(www.)?%{DOMAIN_MATCH:domain:tag}~%{DATA:mobile:tag} %{DATA:bot:tag} %{DATA:cache_status:tag}\"
        ''']
        custom_patterns = '''
        DOMAIN_MATCH (exampe1.com|example2.com|example3.com)
        PATHLEVEL1 \/([^ "/?]+)?
        LOAD_BALANCING_TIMES (((\d+\.\d+),\s)+)?
        '''
     measurement = "proxy_access_log"
```

### System info:

telegraf 1.7.3 on Ubuntu 18.04 server

### Steps to reproduce:
1.  systemctl restart telegraf

### Expected behavior:
Restart succeeds
### Actual behavior:
sometimes (not always) the restart doesn't finish and the process gets killed by systemd

### Additional info:
Journal:
```
Aug 28 18:10:01 us-proxy1 CRON[30491]: (root) CMD (/usr/local/bin/ws/prep_telegraf_access_previous_10min.sh)
Aug 28 18:20:01 us-proxy1 CRON[31065]: (root) CMD (/usr/local/bin/ws/prep_telegraf_access_previous_10min.sh)
Aug 28 18:21:32 us-proxy1 systemd[1]: telegraf.service: State 'stop-sigterm' timed out. Killing.
Aug 28 18:21:32 us-proxy1 systemd[1]: telegraf.service: Killing process 30512 (telegraf) with signal SIGKILL.
Aug 28 18:21:32 us-proxy1 systemd[1]: telegraf.service: Killing process 30524 (telegraf) with signal SIGKILL.
Aug 28 18:21:32 us-proxy1 systemd[1]: telegraf.service: Main process exited, code=killed, status=9/KILL
Aug 28 18:21:32 us-proxy1 systemd[1]: telegraf.service: Failed with result 'timeout'.
Aug 28 18:21:32 us-proxy1 systemd[1]: telegraf.service: Triggering OnFailure= dependencies.
Aug 28 18:21:32 us-proxy1 systemd-unit-status-mail.sh[31089]: Status mail sent to: root for unit: telegraf.service

```
In the Log below one can see that telegraf restart is triggered 18:20:02 (from the script in CRON above) and then logparser tries to parse a line even before it flushes the cashed metrics. Also the Log-entry doesn't exist in that way and is somehow cut off. This is always seen when this problem occurs, so seems to be related to logparser.
After flushing the old metrics it takes the Systemd TimeoutSec before it gets killed and restarted (successfully).

telegraf.log:
```
2018-08-28T18:19:51Z D! Output [influxdb] wrote batch of 65 metrics in 271.871656ms
2018-08-28T18:20:02Z D! Output [influxdb] buffer fullness: 77 / 10000 metrics. 
2018-08-28T18:20:02Z D! Grok no match found for: " \"GET /some-url/file_mobile.png HTTP/2.0\" 200 10786 \"https://www.example.com/some-URL\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36\" +0.000 - .+ \"-\" \"www.example.com~0 0 HIT\""
2018-08-28T18:20:02Z I! Hang on, flushing any cached metrics before shutdown
2018-08-28T18:20:02Z D! Output [influxdb] buffer fullness: 5 / 10000 metrics. 
2018-08-28T18:20:02Z D! Output [influxdb] wrote batch of 77 metrics in 266.754045ms
2018-08-28T18:20:02Z D! Output [influxdb] wrote batch of 5 metrics in 133.367373ms
2018-08-28T18:21:32Z D! Attempting connection to output: influxdb
2018-08-28T18:21:32Z D! Successfully connected to output: influxdb
2018-08-28T18:21:32Z I! Starting Telegraf v1.7.3
2018-08-28T18:21:32Z I! Loaded inputs: inputs.cpu inputs.disk inputs.diskio inputs.mem inputs.processes inputs.system inputs.internal inputs.nginx inputs.kernel inputs.swap inputs.net inputs.netstat inputs.procstat inputs.logparser
2018-08-28T18:21:32Z I! Loaded aggregators: 
2018-08-28T18:21:32Z I! Loaded processors: 
2018-08-28T18:21:32Z I! Loaded outputs: influxdb
2018-08-28T18:21:32Z I! Tags enabled: dc=us-vultr host=us-proxy1
2018-08-28T18:21:32Z I! Agent Config: Interval:10s, Quiet:false, Hostname:"us-proxy1", Flush Interval:10s

```

### LINKED ISSUE #4717: Multiple output plugins with different time intervals
Allow user to configure multiple output plugins for a Telegraf agent to send data at different time intervals. Essentially, the data will be flowing to 2 different outputs at different intervals. 

Example:

`outputs.influxdb` is set to send data every `30s`
`outputs.http_listener` is configured to send data every `60s`

### PR DESCRIPTION
**Pull request by danielnelson**
This pull request remove blocking during flushes and writes immediately to the metric buffer.  This should improve throughput especially when outputs are slow, and degrade better when overloaded.
closes #2919 

To avoid over consumption in queue consumers it introduces a way to track metrics and be notified when they are delivered, allowing for durable handling in the consumer inputs.  This is done by reference counting the metrics as they move through Telegraf which does add some additional implementation requirements to processors and consumer inputs.
closes #3984

The agent was refactored to fix issues restarting and shutting down when under load:
closes #4283 
closes #4457 
closes #4610

As part of the agent refactor, the timing alignment is fixed:
closes #3968

Add per output `flush_interval`, `metric_buffer_limit` and `metric_batch_size`.
closes #4717

### What still needs done:

- [x] Update contributing documentation WRT tracking data.
- [x] Add tracking support to mqtt_consumer
- [x] Add tracking support to nats_consumer
- [x] Add tracking support to nsq_consumer

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

File: output.go [hunk 1]
```diff
@@ -35,21 +26,3 @@ type AggregatingOutput interface {
...
-	Close() error
-	// Description returns a one-sentence description on the Output
-	Description() string
-	// SampleConfig returns the default configuration of the Output
-	SampleConfig() string
-	// Write takes in group of points to be written to the Output
-	Write(metrics []Metric) error
-
-	// Start the "service" that will provide an Output
-	Start() error
```
Comment (glinton) [inline output.go]: Do service plugins replace `Start` and `Stop` implementations with `Connect` and `Close`?
