### PR TITLE
Use Systemd for Amazon Linux 2

### LINKED ISSUE #5117: Telegraf install logic does not support new Amazon Linux 2 operating system
### System info:

Telegraf agent 1.8.2
amzn2-ami-hvm-2.0.20181114-x86_64-gp2 (ami-009d6802948d06e52)
us-east-1 region of AWS

### Steps to reproduce:

On Amazon Linux 2 OS:

$ yum -y localinstall /tmp/telegraf-agent.rpm
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Examining /tmp/telegraf-agent.rpm: telegraf-1.8.2-1.x86_64
Marking /tmp/telegraf-agent.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package telegraf.x86_64 0:1.8.2-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===========================================================================================================================
 Package                     Arch                      Version                    Repository                          Size
===========================================================================================================================
Installing:
 telegraf                    x86_64                    1.8.2-1                    /telegraf-agent                     46 M

Transaction Summary
===========================================================================================================================
Install  1 Package

Total size: 46 M
Installed size: 46 M
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : telegraf-1.8.2-1.x86_64                                                                                 1/1 
  Verifying  : telegraf-1.8.2-1.x86_64                                                                                 1/1 

Installed:
  telegraf.x86_64 0:1.8.2-1                                                                                                

Complete!

...
Populate files such as 
  /etc/default/telegraf
  /etc/telegraf/telegraf.conf
...

$ telegraf --version
Telegraf 1.8.2 (git: HEAD 996a91f2)
$ service telegraf status
telegraf Process is running [ OK ]
$ ps -ef | grep telegraf
telegraf   821     1  0 19:46 ?        00:00:00 /usr/bin/telegraf -pidfile /var/run/telegraf/telegraf.pid -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
root       924   646  0 19:47 pts/0    00:00:00 grep --color=auto telegraf
$ systemctl status telegraf
● telegraf.service - LSB: Start telegraf at boot time
   Loaded: loaded (/etc/rc.d/init.d/telegraf; bad; vendor preset: disabled)
   Active: inactive (dead)
     Docs: man:systemd-sysv-generator(8)
$ systemctl restart telegraf
$ systemctl status telegraf
● telegraf.service - LSB: Start telegraf at boot time
   Loaded: loaded (/etc/rc.d/init.d/telegraf; bad; vendor preset: disabled)
   Active: active (exited) since Wed 2018-12-05 19:47:50 UTC; 5s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 966 ExecStart=/etc/rc.d/init.d/telegraf start (code=exited, status=0/SUCCESS)

Dec 05 19:47:50 i-0b8de5454928d.awsdev.inforcloud.local systemd[1]: Starting LSB: Start telegraf at boot time...
Dec 05 19:47:50 i-0b8de5454928d.awsdev.inforcloud.local telegraf[966]: telegraf process is running [ FAILED ]
Dec 05 19:47:50 i-0b8de5454928d.awsdev.inforcloud.local systemd[1]: Started LSB: Start telegraf at boot time.
$ service telegraf status
telegraf Process is running [ OK ]

### Expected behavior:

Expected systemctl to be able to recognize that the service is running.

### Actual behavior:

systemctl thinks service is not active and the agent must be restarted via systemctl.

### Additional info:

This file may need to be updated to handle Amazon Linux 2:
https://github.com/influxdata/telegraf/blob/master/scripts/post-install.sh#L89

### PR DESCRIPTION
**Pull request by gunnaraasen**
Amazon Linux 2 uses systemd. This PR adds support for Amazon Linux 2 in the Telegraf `post-install.sh` and `post-remove.sh` scripts.

closes #5117

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).

### CODE REVIEW

File: scripts/post-install.sh [hunk 1]
```diff
@@ -90,12 +90,17 @@ elif [[ -f /etc/os-release ]]; then
     source /etc/os-release
     if [[ $ID = "amzn" ]]; then
         # Amazon Linux logic
-        install_init
-        # Run update-rc.d or fallback to chkconfig if not available
-        if which update-rc.d &>/dev/null; then
-            install_update_rcd
+        if [[ $VERSION_ID = "2" ]]; then
```
Comment (danielnelson) [inline scripts/post-install.sh]: I expect that when VERSION_ID=3 is released it will still be using systemd, so maybe we can have the systemd path be default and only do the other methods for VERSION_ID=1 (if there is such a variable)

Comment (gunnaraasen) [reply scripts/post-install.sh]: Good point, I'll switch this around.

**Comment by gunnaraasen** [comment]
Unfortunately, `VERSION_ID` follows an `xxxx.xx` (e.g. `2018.03`) format in Amazon Linux 1. Checking whether the name is "Amazon Linux AMI" instead of "Amazon Linux" appears to be the only non-complicated way to distinguish between Amazon Linux version 1 and later.

**Comment by gunnaraasen** [comment]
I cleaned up the logic a bit. This is ready to merge.

File: scripts/post-install.sh [hunk 2]
```diff
@@ -88,7 +88,10 @@ elif [[ -f /etc/debian_version ]]; then
     fi
 elif [[ -f /etc/os-release ]]; then
     source /etc/os-release
-    if [[ $ID = "amzn" ]]; then
+    if [[ $NAME = "Amazon Linux" ]]; then
```
Comment (danielnelson) [inline scripts/post-install.sh]: Quote `"$NAME"`
