### PR TITLE
Make prometheus serializer update timestamps and expiration time as new data arrives

### LINKED ISSUE #8170: outputs.prometheus_client (metric_version=2) removes(still existing) histograms every expiration_interval
I'm gathering metrics with Google mtail (https://github.com/google/mtail) (inputs.prometheus). Problem is that histograms are removed every expiration_interval (and reappear on next interval) (Counters from mtail are not removed on expiration_interval).

(Setting expiration_interval=0 is not viable because telegraf also gathers other metrics and there are metrics I want to alert on if they're absent). (Testing with (both input/output) metric_version=1  and histograms don't disappear every expiration_interval).

### Relevant telegraf.conf:

```toml
# This is minimal example for reproducing the behaviour. 
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "3s"
  flush_interval = "10s"
  flush_jitter = "4s"
  precision = ""
  debug = false
  hostname = ""
  omit_hostname = true

[[outputs.prometheus_client]]
  ## Address to listen on
  listen = ":9273"
  metric_version = 2
  path = "/metrics"
  # short expiration for debugging
  expiration_interval = "30s"
  collectors_exclude = ["gocollector", "process"]
  # string_as_label = true

  ## Export metric collection time.
  export_timestamp = false

[[inputs.prometheus]]
  urls = ["http://localhost:8000/metrics"]
  response_timeout = "8s"

  metric_version = 2

  namedrop = [ "go_*", "process_*" ]
  tagexclude = [ "host", "url" ]

  interval = "10s"

```

### System info:

Telegraf 1.15.3 (git: HEAD fac81815) (also happens with at least 1.15.1, 1.14.0)
linux(amd64) (fedora32, centos8, centos7) 

### Steps to reproduce:

1. Serve this file as /metrics (for example with `python3 -m http.server 8000`
```
# HELP postfix_qmgr_messages_inserted_recipients defined at postfix.mtail:81:13-53
# TYPE postfix_qmgr_messages_inserted_recipients histogram
postfix_qmgr_messages_inserted_recipients_bucket{prog="postfix.mtail",le="1"} 2
postfix_qmgr_messages_inserted_recipients_bucket{prog="postfix.mtail",le="2"} 2
postfix_qmgr_messages_inserted_recipients_bucket{prog="postfix.mtail",le="+Inf"} 2
postfix_qmgr_messages_inserted_recipients_sum{prog="postfix.mtail"} 2
postfix_qmgr_messages_inserted_recipients_count{prog="postfix.mtail"} 2
# HELP postfix_qmgr_messages_removed_total defined at postfix.mtail:89:11-45
# TYPE postfix_qmgr_messages_removed_total counter
postfix_qmgr_messages_removed_total{prog="postfix.mtail"} 2
```
2. Start telegraf with the example config: `telegraf --config telegraf.conf` and in a loop scrape telegraf: `while true; do curl -s http://localhost:9273/metrics | grep -c ^postfix_ ; sleep 2; done` and see that about every expiration_interval the `postfix_qmgr_messages_inserted_recipients_*` metrics disappear (and reappear after next input interval). **Note**: `postfix_qmgr_messages_removed_total` (counter) doesn't disappear.

### Expected behavior:

curl -s http://localhost:9273/metrics output should have `postfix_qmgr_messages_inserted_recipients_*` metrics as long as they appear in input.

### Actual behavior:

Histogram metrics are incorrectly removed every expiration_interval.

### Additional info:
While this is fairly minimal test config, the problem also appears with actual data + mtail (here the histogram data is updated more frequently than expiration_interval).

Also with this test setup and file output:
```toml
[[outputs.file]]
  files = ["stdout"]
  data_format = "prometheus"
```
produces weird duplicate histogram values:
```
# HELP postfix_qmgr_messages_inserted_recipients Telegraf collected metric
# TYPE postfix_qmgr_messages_inserted_recipients histogram
postfix_qmgr_messages_inserted_recipients_bucket{prog="postfix.mtail",le="+Inf"} 2
postfix_qmgr_messages_inserted_recipients_sum{prog="postfix.mtail"} 2
postfix_qmgr_messages_inserted_recipients_count{prog="postfix.mtail"} 2
# HELP postfix_qmgr_messages_inserted_recipients Telegraf collected metric
# TYPE postfix_qmgr_messages_inserted_recipients histogram
postfix_qmgr_messages_inserted_recipients_bucket{prog="postfix.mtail",le="1"} 2
postfix_qmgr_messages_inserted_recipients_bucket{prog="postfix.mtail",le="+Inf"} 0
postfix_qmgr_messages_inserted_recipients_sum{prog="postfix.mtail"} 0
postfix_qmgr_messages_inserted_recipients_count{prog="postfix.mtail"} 0
# HELP postfix_qmgr_messages_inserted_recipients Telegraf collected metric
# TYPE postfix_qmgr_messages_inserted_recipients histogram
postfix_qmgr_messages_inserted_recipients_bucket{prog="postfix.mtail",le="2"} 2
postfix_qmgr_messages_inserted_recipients_bucket{prog="postfix.mtail",le="+Inf"} 0
postfix_qmgr_messages_inserted_recipients_sum{prog="postfix.mtail"} 0
postfix_qmgr_messages_inserted_recipients_count{prog="postfix.mtail"} 0
# HELP postfix_qmgr_messages_inserted_recipients Telegraf collected metric
# TYPE postfix_qmgr_messages_inserted_recipients histogram
postfix_qmgr_messages_inserted_recipients_bucket{prog="postfix.mtail",le="+Inf"} 2
postfix_qmgr_messages_inserted_recipients_sum{prog="postfix.mtail"} 0
postfix_qmgr_messages_inserted_recipients_count{prog="postfix.mtail"} 0
# HELP postfix_qmgr_messages_removed_total Telegraf collected metric
# TYPE postfix_qmgr_messages_removed_total counter
postfix_qmgr_messages_removed_total{prog="postfix.mtail"} 2
```

### PR DESCRIPTION
**Pull request by jakemcc**
- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.

resolves #8170 

Replaces #8257

#8257 partially implements a fix for #8170 but this PR expands it to also resolve the expiration issue to the Summary type.

It also updates both the Histogram and Summary `timestampMs` field when new data arrives for a particular Histogram or Summary. I talk about this problem in [this](https://github.com/influxdata/telegraf/issues/8170#issuecomment-816261054) comment on #8170. Below expands on it.

If you have configured `[[outputs.prometheus_client]]` to `export_timestamps = true` then without the updating of `timestampMs` on new data coming in you end up in a situation like below.

Say you are pushing prometheus data to telegraf. The first batch might look something like below with a timestamp of `1617722541063`

```
metric_name{application="the-application",quantile="0.5"} 1 1617722540000
metric_name{application="the-application",quantile="0.75"} 2 1617722540000
metric_name{application="the-application",quantile="0.95"} 3 1617722540000
metric_name{application="the-application",quantile="0.98"} 3.3 1617722540000
metric_name{application="the-application",quantile="0.99"} 3.4 1617722540000
metric_name{application="the-application",quantile="0.999"} 10 1617722540000
metric_name_sum{application="the-application"} 207.501625198 1617722540000
metric_name_count{application="the-application"} 18000 1617722540000

```

About 10 seconds later, you publish an update to telegraf.

```
metric_name{application="the-application",quantile="0.5"} 0.9  1617722550000
metric_name{application="the-application",quantile="0.75"} 1.5 1617722550000
metric_name{application="the-application",quantile="0.95"} 2 1617722550000
metric_name{application="the-application",quantile="0.98"} 3 1617722550000
metric_name{application="the-application",quantile="0.99"} 3.5 1617722550000
metric_name{application="the-application",quantile="0.999"} 10 1617722550000
metric_name_sum{application="the-application"} 310 1617722550000
metric_name_count{application="the-application"} 18281 1617722550000
```

If telegraf is then scrapped by prometheus and `export_timestamp = true`, the initial first received timestamp is exported instead of the correct second timestamp. Updating `timestampMs` as new data comes in resolves this issue.

### CODE REVIEW

**Review by Jagularr — APPROVED** [review]
Makes sense to me

File: plugins/serializers/prometheus/collection_test.go [hunk 1]
```diff
@@ -425,3 +636,209 @@ func TestCollectionExpire(t *testing.T) {
...
+			input: []Input{
+				{
+					metric: testutil.MustMetric(
+						"prometheus",
+						map[string]string{},
+						map[string]interface{}{
+							"http_request_duration_seconds_sum":   10.0,
+							"http_request_duration_seconds_count": 2,
+						},
+						time.Unix(15, 0),
```
Comment (reimda) [inline plugins/serializers/prometheus/collection_test.go:661]: Now is set to 0 seconds but the metric timestamps are in the future at 15 and 20 seconds. Shouldn't now be greater than or equal the latest timestamp? Maybe it doesn't matter since this isn't testing expiration but it seems odd.

Same thing happens in the other table test (line 754).

**Review by reimda — CHANGES_REQUESTED** [review]
It makes sense to me for expiration to be relative to to the last time a histogram or summary is gathered instead of the first time. Thanks @jakemcc for adding comprehensive tests for this.

**Comment by reimda** [comment]
Hey @ssoroka, you commented on #8170 a few months ago, would you like to review this fix?

File: plugins/serializers/prometheus/collection_test.go (hunk 1 above)
Comment (jakemcc) [reply plugins/serializers/prometheus/collection_test.go]: Not sure how I missed this question but finally noticed it.

It doesn't matter for this test as the interaction for expiration is between `now` and `addtime` and these tests are confirming that a metrics timestamp is exported. I believe theoretically you could have a service report metrics with timestamps to telegraf and have those reported timestamps be in the future if telegraf and the source of metrics disagreed on the answer to "what time is it?"

Regardless, I updated the tests to have both `now` and `addtime` be moved to be timestamps that are **after** the metric timestamps. I made `now` and `addtime` distinct from the metric timestamps so it continues to be clear where the exported timestamp is coming from (the metric timestamp and not `now` or `addtime`).

See commit https://github.com/influxdata/telegraf/pull/9139/commits/b29e41a4a7159c516219b974b7078757624a3c0f

Comment (jakemcc) [reply plugins/serializers/prometheus/collection_test.go]: @reimda Thanks for taking the time to review and think about the test data!

**Comment by jakemcc** [comment]
We've been running with a fork that includes these changes since a little before I submitted this PR. It has been working well for us and, as expected, has resolved the gaps mentioned in the referenced issues.

**Comment by jjh74** [comment]
@reimda / @ssoroka Any updates on this ?
I've been running a fork with subset/previous version of fix(#8257) for nearly a year. Without this PR prometheus histograms are not useful.

**Review by reimda — APPROVED** [review]
