### PR TITLE
fix(outputs.quix): Allow empty certificate for new cloud managed instances

### LINKED ISSUE #16856: Quix output plugin fails with new Quix Cloud product
### Relevant telegraf.conf

```toml
# Global Agent Configuration
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.mem]]
  ## Collect memory usage metrics

[[inputs.disk]]
  ## Collect disk usage metrics
  ignore_fs = ["tmpfs", "devtmpfs"]

[[outputs.quix]]
  workspace = "${Quix__Workspace__Id}"
  token = "${Quix__Sdk__Token}"
  url = "${Quix__Portal__Api}"
  topic = "${output}"
  data_format = "json"
```

### Logs from Telegraf

```text
403
```

### System info

Telegraf in Quix

### Docker

_No response_

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

Sends data to Quix broker

### Actual behavior

It fails on start

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by tomas-quix**
## Summary
New Quix Cloud managed broker don't require certificate and current Quix plugin implementation will fail in such a scenario.

## Checklist
- [x] No AI generated code was used in this PR

## Related issues

resolves #16856

### CODE REVIEW

File: plugins/outputs/quix/quix.go [hunk 1]
```diff
@@ -109,13 +109,18 @@ func (q *Quix) Connect() error {
...
-		certPool := x509.NewCertPool()
-		if !certPool.AppendCertsFromPEM(quixConfig.cert) {
-			return errors.New("appending CA cert to pool failed")
+		// Certificate (optional)
+		if len(quixConfig.cert) > 0 {
+			certPool := x509.NewCertPool()
+			if !certPool.AppendCertsFromPEM(quixConfig.cert) {
+				return errors.New("appending CA cert to pool failed")
+			}
+			cfg.Net.TLS.Enable = true
```
Comment (srebhan) [inline plugins/outputs/quix/quix.go:118]: TLS should be enabled unconditionally, shouldn't it?

File: plugins/outputs/quix/quix.go [hunk 2]
```diff
@@ -109,13 +109,18 @@ func (q *Quix) Connect() error {
...
+			cfg.Net.TLS.Config = &tls.Config{RootCAs: certPool}
+		} else {
+			cfg.Net.TLS.Enable = true
+			cfg.Net.TLS.Config = &tls.Config{InsecureSkipVerify: true}
```
Comment (srebhan) [inline plugins/outputs/quix/quix.go:122]: No, we cannot simply enforce unsecure settings on our users. If you need to allow insecure settings, make this explicit by adding a setting! Why would we need to set this at all?

**Review by srebhan — COMMENTED** [review]
Thanks for the fix @tomas-quix! Two comments from my side. Furthermore, I would love to see a comment in both branches when those things occur like
```
// A certificate is delivered for old Quix cloud manager instances
```
and
```
// New cloud manager instances do not require an explicit certificate to be added to the trust chain
```
or similar.

File: plugins/outputs/quix/quix.go (hunk 1 above)
Comment (tomas-quix) [reply plugins/outputs/quix/quix.go]: You are right.

File: plugins/outputs/quix/quix.go (hunk 2 above)
Comment (tomas-quix) [reply plugins/outputs/quix/quix.go]: You are right. It is not needed.

File: plugins/outputs/quix/quix.go [hunk 3]
```diff
@@ -109,13 +109,16 @@ func (q *Quix) Connect() error {
...
 
-		// Certificate
-		certPool := x509.NewCertPool()
-		if !certPool.AppendCertsFromPEM(quixConfig.cert) {
-			return errors.New("appending CA cert to pool failed")
-		}
 		cfg.Net.TLS.Enable = true
-		cfg.Net.TLS.Config = &tls.Config{RootCAs: certPool}
+		
+        	// Certificate (optional)
```
Comment (srebhan) [inline plugins/outputs/quix/quix.go:114]: How about
```suggestion
        	// Add the CA certificate sent by the server if there is any. Newer cloud
        	// instances do not need this and we can go with the system certificates.
```

**Review by srebhan — COMMENTED** [review]
@tomas-quix just one more suggestion and a request to run `make fmt` to please the linters...

**Review by mstrandboge — APPROVED** [review]
