### PR TITLE
fix(inputs.docker): Emit status metrics for non-running containers

### LINKED ISSUE #18451: [inputs.docker] Only running containers are logged regardless of container_state_include/exclude options
### Relevant telegraf.conf

```toml
[[inputs.docker]]
endpoint = "unix:///var/run/docker.sock"
gather_services = false
container_state_include = ["exited"]
timeout = "5s"
```

### Logs from Telegraf

```text
2026-03-03T05:23:40Z I! Loading config: /etc/telegraf/telegraf.conf
2026-03-03T05:23:40Z I! Starting Telegraf 1.37.3 brought to you by InfluxData the makers of InfluxDB
2026-03-03T05:23:40Z I! Available plugins: 243 inputs, 9 aggregators, 35 processors, 26 parsers, 67 outputs, 8 secret-stores
2026-03-03T05:23:40Z I! Loaded inputs: docker
2026-03-03T05:23:40Z I! Loaded aggregators:
2026-03-03T05:23:40Z I! Loaded processors:
2026-03-03T05:23:40Z I! Loaded secretstores:
2026-03-03T05:23:40Z I! Loaded outputs: file
2026-03-03T05:23:40Z I! Tags enabled: host=3b4eee8596de
2026-03-03T05:23:40Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"3b4eee8596de", Flush Interval:10s
2026-03-03T05:23:40Z W! [agent] The default value of 'skip_processors_after_aggregators' will change to 'true' with Telegraf v1.40.0! If you need the current default behavior, please explicitly set the option to 'false'!

docker,engine_host=docker,host=3b4eee8596de,server_version=29.2.1 n_images=27i,n_listener_events=0i,n_containers=26i,n_containers_stopped=1i,n_containers_paused=0i,n_goroutines=207i,n_cpus=16i,n_used_file_descriptors=222i,n_containers_running=25i 1772515430000000000
docker,engine_host=docker,host=3b4eee8596de,server_version=29.2.1 memory_total=17028141056i 1772515430000000000
docker,engine_host=docker,host=3b4eee8596de,server_version=29.2.1 n_used_file_descriptors=222i,n_containers_running=25i,n_containers_stopped=1i,n_containers_paused=0i,n_listener_events=0i,n_cpus=16i,n_containers=26i,n_images=27i,n_goroutines=207i 1772515440000000000
docker,engine_host=docker,host=3b4eee8596de,server_version=29.2.1 memory_total=17028141056i 1772515440000000000
```

### System info

Debain 13 (Linux 6.12.73) Using telegraf:latest docker image

### Docker

**docker-compose.yml:**
```
services:
  telegraf:
    image: telegraf:latest
    container_name: Telegraf
    restart: unless-stopped
    user: telegraf:1000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Data/telegraf.conf:/etc/telegraf/telegraf.conf
```

**docker ps -a:**
`c254ae7808fb   openspeedtest/latest                           "/docker-entrypoint.…"   5 days ago     Exited (137) 42 minutes ago`

**curl --unix-socket /var/run/docker.sock http://localhost/containers/c254ae7808fb/stats:**
```{"id":"c254ae7808fbbbd0f9fbe11cdd0138774b1695a0903fc38f1c46af381fac13e3","name":"/OpenSpeedTest","os_type":"linux","read":"0001-01-01T00:00:00Z","cpu_stats":{"cpu_usage":{"total_usage":0,"usage_in_kernelmode":0,"usage_in_usermode":0},"throttling_data":{"periods":0,"throttled_periods":0,"throttled_time":0}},"memory_stats":{},"pids_stats":{},"blkio_stats":{"io_service_bytes_recursive":null,"io_serviced_recursive":null,"io_queue_recursive":null,"io_service_time_recursive":null,"io_wait_time_recursive":null,"io_merged_recursive":null,"io_time_recursive":null,"sectors_recursive":null},"num_procs":0,"storage_stats":{},"preread":"0001-01-01T00:00:00Z","precpu_stats":{"cpu_usage":{"total_usage":0,"usage_in_kernelmode":0,"usage_in_usermode":0},"throttling_data":{"periods":0,"throttled_periods":0,"throttled_time":0}}}```

### Steps to reproduce

1. Modify example config for inputs.docker to change the container_state_include/exclude to include not just running containers
2. Start telegraf

### Expected behavior

Changing container_state_include config option to include exited/stopped containers should log info for exited/stopped containers.

### Actual behavior

Non-running containers are not logged even if the state is included via the config

### Additional info

Tried various configurations including adding all the states to include, changing the container_name_include to only include the stopped container, nothing is returned for any containers that are not running.

### PR DESCRIPTION
**Pull request by skartikey**
## Summary

When container_state_include was configured to include non-running states (e.g. exited), the plugin silently dropped all metrics because Docker's stats API returns an empty body (EOF) for stopped containers. The EOF handler returned early, skipping the inspect call that emits docker_container_status and docker_container_health metrics.

Continue past EOF so inspect metrics (exitcode, finished_at, uptime_ns, etc.) are still collected. Add a nil guard in parseContainerStats since runtime stats are unavailable for non-running containers.

## Checklist

- [x] No AI generated code was used in this PR
- [ ] AI generated code used in this PR follows the [InfluxData Policy on AI-Generated Code Contributions][policy]

[policy]: https://www.influxdata.com/ai-generated-code-contributions-policy

## Related issues

resolves #18451

### CODE REVIEW

File: plugins/inputs/docker/docker_test.go [hunk 1]
```diff
@@ -1245,6 +1245,64 @@ func TestContainerStateFilter(t *testing.T) {
...
+	require.Equal(t, "exited", acc.TagValue("docker_container_status", "container_status"))
+	exitcode, ok := acc.IntField("docker_container_status", "exitcode")
+	require.True(t, ok)
+	require.Equal(t, 137, exitcode)
+
+	// Runtime stats (cpu, mem, net, blkio) should NOT be emitted
+	acc.AssertDoesNotContainMeasurement(t, "docker_container_cpu")
+	acc.AssertDoesNotContainMeasurement(t, "docker_container_mem")
+	acc.AssertDoesNotContainMeasurement(t, "docker_container_net")
+	acc.AssertDoesNotContainMeasurement(t, "docker_container_blkio")
```
Comment (srebhan) [inline plugins/inputs/docker/docker_test.go]: Wouldn't it be easier to define a set of `expected` metrics and check those using `testutil.RequireMetricsEqual`?

File: plugins/inputs/docker/docker_test.go [hunk 2]
```diff
@@ -1278,6 +1278,13 @@ func TestNonRunningContainerEmitsStatusMetrics(t *testing.T) {
 		return &client, nil
 	}
 
+	now = func() time.Time {
+		return time.Date(2024, 1, 2, 0, 0, 0, 0, time.UTC)
+	}
+	defer func() {
+		now = time.Now
+	}()
```
Comment (srebhan) [inline plugins/inputs/docker/docker_test.go]: Why is this required? If it is for comparing the metrics, I would instead use the [`testutil.IgnoreTime()` compare option](https://github.com/influxdata/telegraf/blob/2768d1426a0eb55caffe1a59f3545938806f13be/testutil/metric.go#L160)!

File: plugins/inputs/docker/docker_test.go [hunk 3]
```diff
@@ -1289,12 +1296,35 @@ func TestNonRunningContainerEmitsStatusMetrics(t *testing.T) {
...
 	require.NoError(t, d.Gather(&acc))
 
-	// Status metrics should be emitted even for non-running containers
-	require.True(t, acc.HasMeasurement("docker_container_status"))
-	require.Equal(t, "exited", acc.TagValue("docker_container_status", "container_status"))
-	exitcode, ok := acc.IntField("docker_container_status", "exitcode")
-	require.True(t, ok)
-	require.Equal(t, 137, exitcode)
+	expected := []telegraf.Metric{
+		testutil.MustMetric(
```
Comment (srebhan) [inline plugins/inputs/docker/docker_test.go]: Please use `metric.New` instead. We really need to kill `testutil.MustMetric`!

File: plugins/inputs/docker/docker_test.go [hunk 4]
```diff
@@ -1289,12 +1296,35 @@ func TestNonRunningContainerEmitsStatusMetrics(t *testing.T) {
...
+				"finished_at":   time.Date(2024, 1, 1, 1, 0, 0, 0, time.UTC).UnixNano(),
+				"uptime_ns":     int64(time.Hour),
+			},
+			time.Date(2024, 1, 2, 0, 0, 0, 0, time.UTC),
+		),
+	}
+
+	actual := filterMetrics(acc.GetTelegrafMetrics(), func(m telegraf.Metric) bool {
+		return m.Name() == "docker_container_status"
+	})
```
Comment (srebhan) [inline plugins/inputs/docker/docker_test.go:1320]: Why are you filtering here? Wouldn't it be better to just define all metrics as expected as you then can also get rid of the `acc.AssertDoesNotContainMeasurement(t, "docker_container_cpu")` cruft below...

**Comment by astudnev** [comment]
I have telegraf 1.38.2-1 where this issue have to be fixed, but looks it is not.
I have config 
```
### MANAGED BY telegraf ANSIBLE ROLE ###

[[inputs.docker]]
    endpoint = "unix:///run/docker.sock"
    gather_services = false
    source_tag = false
    container_state_include = ["created", "restarting", "running", "removing", "paused", "exited", "dead"]
    container_name_include = []
    container_name_exclude = []
    timeout = "5s"
    docker_label_include = []
    docker_label_exclude = [ "_*" ]
~
```

and test fails

```
root@hel415 ~ # docker run --name test-fail-container alpine sh -c "exit 2"
root@hel415 ~ # docker ps -a
CONTAINER ID   IMAGE                                                           COMMAND                    CREATED         STATUS                     PORTS                       NAMES
bf0b00561346   alpine                                                          "sh -c 'exit 2'"           4 seconds ago   Exited (2) 3 seconds ago                               test-fail-container
8709652eb203   nexus.bitq.dev/repository/nodes_exporter:v1.0.50                "/opt/nodes_exporter"      46 hours ago    Up 45 hours                172.18.3.1:7072->9228/tcp   eth-node-3-lighthouse-exporter-1
d9bd30200c04   sigp/lighthouse:v8.0.1                                          "lighthouse beacon_n…"     46 hours ago    Up 45 hours                172.18.3.1:5051->5051/tcp   eth-node-3-lighthouse-1
41000bc23440   nexus.bitq.dev/repository/nodes_exporter:v1.0.50                "/opt/nodes_exporter"      46 hours ago    Up 45 hours                172.18.3.1:7070->9228/tcp   eth-node-3-exporter-1
6db569c7165e   nexus.bitq.dev/repository/go-ethereum-streaming:v1.17.2-2.5.7   "./entrypoint.sh get…"     46 hours ago    Exited (2) 41 hours ago                                eth-node-3-geth-1
a782e6a32c2d   nexus.bitq.dev/repository/go-ethereum-streaming:v1.17.2-2.5.7   "./entrypoint.sh /ap…"     46 hours ago    Exited (0) 45 hours ago                                eth-node-3-init-genesis-1
8c99c7de0828   python:3.9-alpine                                               "/app/scripts/create…"     46 hours ago    Exited (0) 45 hours ago                                eth-node-3-create-topics-1
537ff1122414   nginx:1.22-alpine                                               "/docker-entrypoint.…"     46 hours ago    Up 45 hours                0.0.0.0:8081->80/tcp        eth-node-3-nginx-1
73d5fe916e07   nexus.bitq.dev/repository/snapshots-processor:v1.2.33           "restore-snapshot"         46 hours ago    Exited (0) 45 hours ago                                eth-node-3-geth-snapshot-1
99affbea2332   alpine                                                          "/bin/sh -c '. /app/…"     46 hours ago    Exited (0) 45 hours ago                                eth-node-3-runtime-config-1
c1a347a189f9   nexus.bitq.dev/repository/storage-utils:v1.2.16                 "sh -c '\n  trap \"ech…"   46 hours ago    Up 45 hours                                            eth-node-3-sync-job-1
d302b9e02667   alpine                                                          "sh -c '\n  chown -R …"    46 hours ago    Exited (0) 45 hours ago                                eth-node-3-allow-volumes-1
root@hel415 ~ # curl -s http://172.18.3.1:9126/metrics | grep test-fail-container

```

**Comment by skartikey** [comment]
@astudnev Thanks for reporting this. I have put up a PR for it https://github.com/influxdata/telegraf/pull/18719. Could you please run your test with the binary present in the PR?
