### PR TITLE
fix(inputs.chrony): Support local (reference) sources

### LINKED ISSUE #15550: [chrony] `sourcestats` metrics don't work on stratum-1 servers
### Relevant telegraf.conf

```toml
[[inputs.chrony]]
    metrics = ["sourcestats"]
```

### Logs from Telegraf

```text
2024-06-21T20:59:22Z E! [inputs.chrony] Error in plugin: querying name of source 0 failed: got status NOSUCHSOURCE (4)
2024-06-21T20:59:22Z E! [inputs.chrony] Error in plugin: querying name of source 0 failed: got status NOSUCHSOURCE (4)
```

### System info

1.13

### Docker

_No response_

### Steps to reproduce

1. Launch telegraf on a stratum-1 server (with local sources)
2. See it fail

### Expected behavior

It should get the sourcestats

### Actual behavior

It crashes with the error above

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Frankkkkk**
## Summary

Local sources are directly connected to the server (PPS inputs from oscillators, GPS, etc..). They can be seen as stratum-0 sources.

The standard way of getting their name doesn't work as it is stored into their RefID instead.

This fixes that

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #15550

### CODE REVIEW

**Comment by Frankkkkk** [comment]
!signed-cla

File: plugins/inputs/chrony/chrony.go [hunk 1]
```diff
@@ -316,22 +317,32 @@ func (c *Chrony) gatherSources(acc telegraf.Accumulator) error {
...
-
-		// Cut the string at null termination
 		var peer string
-		if termidx := bytes.Index(sourceName.Name[:], []byte{0}); termidx >= 0 {
-			peer = string(sourceName.Name[:termidx])
+
+		if sourceData.Mode == fbchrony.SourceModeRef && sourceData.IPAddr.To4() != nil {
+			// If source is a reference (PPS, etc..), and if the IP is an IPv4 address,
+			// then the name is encoded in its IP (32 bits). Yes
+			//https://gitlab.com/chrony/chrony/-/blob/05bd4898a9a64fe1e5432a78939c4b4b82619c2f/client.c?page=3#L2046
```
Comment (srebhan) [inline plugins/inputs/chrony/chrony.go:325]: Maybe
```suggestion
			// References of local sources (PPS, etc..) are encoded in the bits of the IPv4 address,
			// instead of the RefId. Extract the correct name for those sources.
```

**Review by srebhan — COMMENTED** [review]
Thanks @Frankkkkk! Just a small comment regarding the comment. ;-) Maybe we could also move the peer-extraction to a function to avoid having to comment the special cases in two places?

File: plugins/inputs/chrony/chrony.go (hunk 1 above)
Comment (Frankkkkk) [reply plugins/inputs/chrony/chrony.go]: Hi @srebhan  thanks for your feedback!  Done; please tell me what you think :-)

File: plugins/inputs/chrony/chrony.go [hunk 2]
```diff
@@ -316,22 +335,20 @@ func (c *Chrony) gatherSources(acc telegraf.Accumulator) error {
...
-			return fmt.Errorf("got unexpected response type %T while waiting for source name", sourceNameRaw)
-		}
-
-		// Cut the string at null termination
 		var peer string
-		if termidx := bytes.Index(sourceName.Name[:], []byte{0}); termidx >= 0 {
-			peer = string(sourceName.Name[:termidx])
+
+		if sourceData.Mode == fbchrony.SourceModeRef && sourceData.IPAddr.To4() != nil {
+			//https://gitlab.com/chrony/chrony/-/blob/05bd4898a9a64fe1e5432a78939c4b4b82619c2f/client.c?page=3#L2046
```
Comment (srebhan) [inline plugins/inputs/chrony/chrony.go:341]: I don't think we should add the link here. If you want to, please put it into the PR description...

Furthermore, I would also move the branching into the `getSourceName` function to have it here nice and clean, including the source-stats case below. This way, we do have the "extraction" logic in one place and not distributed across the code.

File: plugins/inputs/chrony/chrony.go [hunk 3]
```diff
@@ -388,22 +405,19 @@ func (c *Chrony) gatherSourceStats(acc telegraf.Accumulator) error {
...
-		// Cut the string at null termination
 		var peer string
-		if termidx := bytes.Index(sourceName.Name[:], []byte{0}); termidx >= 0 {
-			peer = string(sourceName.Name[:termidx])
+
+		if sourceStats.IPAddr.String() == "::" {
+			// `::` IPs mean a local source directly connected to the server.
+			// For example a PPS source or a local GPS receiver.
+			// Then the name of the source is encoded in its RefID
+			// https://gitlab.com/chrony/chrony/-/blob/05bd4898a9a64fe1e5432a78939c4b4b82619c2f/client.c?page=3#L2152
```
Comment (srebhan) [inline plugins/inputs/chrony/chrony.go:414]: See above, remove the link to the source code and include the branching in `getSourceName`.

**Review by srebhan — COMMENTED** [review]
Thanks for the quick update! Please move all source-name logic into the now function as this makes the code in gather more readable.

**Comment by Frankkkkk** [comment]
I don't understand what you mean by "source-name logic into the now function" as they are different:
- `gatherSources` asks for a `SourceData` in which the name is encoded into the IPv4
- `gatherSourcesStats` asks for a `SourceStats`, in which the name is encoded into the RefID
The logic for decoding is different (IP == "::" vs mode = sourceModeRef)

Cheers

**Comment by srebhan** [comment]
@Frankkkkk I see, didn't notice that the type is different. So keep the code locations but remove the link to the other repository!

**Comment by Frankkkkk** [comment]
@srebhan done

**Review by srebhan — APPROVED** [review]
Thanks for your contribution @Frankkkkk!

**Review by powersj — APPROVED** [review]
