### PR TITLE
fix: Print loaded plugins and deprecations for once and test

### LINKED ISSUE #10080: Improve or replace --test
## Problem

The telegraf command line option `--test` is often misunderstood especially in that it does **not** send any data to the outputs but only to stdout. Therefore new users wonder why they don't see any data in their configured database(s) as they meant to use `--once`.

### Proposal:

To improve the awareness for the user about the actual behavior when using `--test` I see the following options

1. Keep `--test` and add a (maybe red) output saying: _"NOTE: Telegraf running in **test mode**, no data will be sent to the outputs!"_ or similar.
2. Add a `--dry-run` option disabling the output plugins. Used together with `--once` it resembles the present `--test` option. We can then remove `--test`. Additionally, the new option allows to run multiple gather cycles or listen for inputs with outputs disabled.
3. Like 2 with the additional warning of 1.

What is your opinion on this?

### PR DESCRIPTION
**Pull request by srebhan**
- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #10080

In the current state loaded plugin-names will only be shown when running in production mode but **not** when running with `--test` or `--once`. The same holds for the newly added deprecation information.

This PR changes the behavior to _always_ show the loaded plugins as well as the deprecation information even when running in testing mode. Furthermore, it clarifies `--test` behavior and fixes `--test-wait` documentation.

### CODE REVIEW

**Review by Hipska — APPROVED** [review]

File: cmd/telegraf/telegraf.go [hunk 1]
```diff
@@ -256,16 +256,6 @@ func runAgent(ctx context.Context,
...
-		wait := time.Duration(*fTestWait) * time.Second
-		return ag.Once(ctx, wait)
-	}
-
-	if *fTest || *fTestWait != 0 {
-		wait := time.Duration(*fTestWait) * time.Second
-		return ag.Test(ctx, wait)
-	}
-
 	log.Printf("I! Loaded inputs: %s", strings.Join(c.InputNames(), " "))
```
Comment (powersj) [inline cmd/telegraf/telegraf.go:259]: This will also, unfortunately, print out the "loaded outputs", which may lead to even more confusion about why outputs are not run doing `--test` or `--once`. What if we only printed the inputs?

Comment (Hipska) [reply cmd/telegraf/telegraf.go:259]: Outputs are definitely run with `--once`, but question is, are they loaded?

Comment (Hipska) [reply cmd/telegraf/telegraf.go:259]: Based on https://github.com/influxdata/telegraf/blob/52c422af3b32ab4185f82ce3f7789255934ab4b8/cmd/telegraf/telegraf.go#L224-L226 I would say no.

Comment (powersj) [reply cmd/telegraf/telegraf.go:259]: So I stand corrected on `--once`, but they do show up and they should *not* with `--test` with this PR.

Comment (Hipska) [reply cmd/telegraf/telegraf.go:259]: That's just what I'm saying. I don't believe there are any outputs loaded in that case.

Comment (srebhan) [reply cmd/telegraf/telegraf.go:259]: I can guard the output with an if, but this would make it harder to read...

Comment (srebhan) [reply cmd/telegraf/telegraf.go:259]: Any preference?

Comment (Hipska) [reply cmd/telegraf/telegraf.go:259]: It seems they are loaded, in that case i would not print that log message for outputs for `--test`.

Comment (powersj) [reply cmd/telegraf/telegraf.go:259]: What about doing the following:

- Only move the ag.Once block down, since we do want to see everything that is loaded
- Leave ag.Test up above all the log/prints, and add a log printf statement that shows what inputs were loaded

Comment (Hipska) [reply cmd/telegraf/telegraf.go:259]: Test also does processors (and aggregators?) But I agree on moving only the once block.

Comment (srebhan) [reply cmd/telegraf/telegraf.go:261]: I've added a proposal. We only print the loaded outputs in 'non-testing' mode. Otherwise we show a big red warning that outputs are not used in testing mode (see #10080). How does that sound to you?

**Review by powersj — APPROVED** [review]

**Comment by srebhan** [comment]
Tried to make this more useful by solving #10080 which is very close.

File: docs/COMMANDS_AND_FLAGS.md [hunk 2]
```diff
@@ -36,8 +36,8 @@ telegraf [flags]
 |`--section-filter`               |filter config sections to output, separator is `:`.  Valid values are `agent`, `global_tags`, `outputs`, `processors`, `aggregators` and `inputs`|
 |`--sample-config`                |print out full sample configuration|
 |`--once`                         |enable once mode: gather metrics once, write them, and exit|
-|`--test`                         |enable test mode: gather metrics once and print them|
-|`--test-wait`                    |wait up to this many seconds for service inputs to complete in test or once mode|
+|`--test`                         |enable test mode: gather metrics once and print them.<br>**No outputs are written!**|
```
Comment (powersj) [inline docs/COMMANDS_AND_FLAGS.md:39]: Instead of written, can we use "executed" or "used"

linter should complain that there should not be HTML in markdown. It can be on the same line as the bold should be enough.

File: docs/COMMANDS_AND_FLAGS.md [hunk 3]
```diff
@@ -36,8 +36,8 @@ telegraf [flags]
...
+|`--test-wait`                    |wait up to this many seconds for service inputs to complete in test or once mode. <br> **Implies `--test` if not used with `--once`**|
```
Comment (powersj) [inline docs/COMMANDS_AND_FLAGS.md:40]: same about the linter here

File: internal/usage.go [hunk 4]
```diff
@@ -38,9 +38,10 @@ The commands & flags are:
                                  'processors', 'aggregators' and 'inputs'
   --sample-config                print out full sample configuration
   --once                         enable once mode: gather metrics once, write them, and exit
-  --test                         enable test mode: gather metrics once and print them
-  --test-wait                    wait up to this many seconds for service
-                                 inputs to complete in test or once mode
+  --test                         enable test mode: gather metrics once and print them.
+                                 NO OUTPUTS ARE WRITTEN!
```
Comment (powersj) [inline internal/usage.go:42]: Same as above "executed" or "used", and I don't think we need to caps it all

File: internal/usage.go [hunk 5]
```diff
@@ -38,9 +38,10 @@ The commands & flags are:
...
+  --test-wait                    wait up to this many seconds for service inputs to complete
+                                 in test or once mode. IMPLIES --test if not used with --once.
```
Comment (powersj) [inline internal/usage.go:44]: no need to all caps IMPLIES

File: docs/COMMANDS_AND_FLAGS.md (hunk 2 above)
Comment (srebhan) [reply docs/COMMANDS_AND_FLAGS.md:39]: Yeah but it looks ugly and I allowed `<br>` for the markdown linter by injecting it in the deprecation PR. ;-P Do you insist on removing the newline?

File: internal/usage.go (hunk 4 above)
Comment (srebhan) [reply internal/usage.go:42]: Tried to make it "bold". Will switch to "executed", even though I think "written" is more clear.

File: docs/COMMANDS_AND_FLAGS.md (hunk 2 above)
Comment (powersj) [reply docs/COMMANDS_AND_FLAGS.md:39]: doh, sneaky you... I really don't like the inline HTML and we pretty much removed it everywhere last week when we did all our listing clean ups :)

File: internal/usage.go (hunk 4 above)
Comment (powersj) [reply internal/usage.go:42]: I thought saying outputs were not executed is more explicit. Saying outputs are not written, could lead someone to think outputs are still run.

**Review by Hipska — APPROVED** [review]

File: docs/COMMANDS_AND_FLAGS.md (hunk 2 above)
Comment (srebhan) [reply docs/COMMANDS_AND_FLAGS.md:39]: For e.g. tables that's sometimes the only way to get sensible formatting... Will remove the linebreak here...

**Review by Hipska — APPROVED** [review]

**Review by powersj — APPROVED** [review]

**Review by reimda — APPROVED** [review]

**Comment by Hipska** [comment]
@srebhan don't know what happened, but this is what I get as output when running `--test`:

> 2021-12-22T10:43:36Z I! **W! Outputs are not used in testing mode!**
