### PR TITLE
fix(inputs.mongodb): add an option to bypass connection errors on start

### LINKED ISSUE #10078: [inputs.mongodb] Telegraf crash on init if conn to MongoDB fails
### Relevent telegraf.conf

`/etc/telegraf/telegraf.d/mongo.conf`

```toml
[[inputs.mongodb]]
  servers = ["mongodb://127.0.0.1:27017/?connect=direct"]
  gather_perdb_stats = false

  fieldpass = ["deletes_per_sec", "flushes_per_sec", "getmores_per_sec", "inserts_per_sec", "updates_per_sec", "queries_per_sec", "open_connections", "net_in_bytes", "net_out_bytes", "repl_lag", "state"]
```

### System info

Telegraf 1.20.2 (git: HEAD f721f53d), Debian 10.11

### Docker

_No response_

### Steps to reproduce

1. Add a dedicated conf for MongoDB like the one above (to simulate a failed conn, just change the port number, for example)
2. Restart Telegraf

### Expected behavior

At least a log message to STDERR, on init, about a failing conn to a MongoDB server (with no retry mechanism)

### Actual behavior

Telegraf crashes :

```
Nov 08 17:32:09 test-mongo-telegraf telegraf[3423]: 2021-11-08T16:32:09Z E! [telegraf] Error running agent: could not initialize input inputs.mongodb: unable to connect to MongoDB: server selection error: context deadline exceeded, current topology: { Type: Single,
Nov 08 17:32:09 test-mongo-telegraf systemd[1]: telegraf.service: Main process exited, code=exited, status=1/FAILURE
```

### Additional info

My hypothesis is that we need to rethink some logic in the Init function in the [mongodb input code](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/mongodb/mongodb.go#L138-L146)

### PR DESCRIPTION
**Pull request by papey**
# Required for all PRs

- [X] Updated associated README.md.
- [X] Wrote appropriate unit tests.
- [X] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #10078

This PR replaces https://github.com/influxdata/telegraf/pull/10086.

Summary of changes : 

* Added an option `ignore_unreachable_hosts` to not return an error on init if a ping fails

### CODE REVIEW

**Review by Hipska — CHANGES_REQUESTED** [review]
My comments about moving the connect to mongo from the `Init` to the `Start` method still counts.

**Comment by papey** [comment]
> My comments about moving the connect to mongo from the `Init` to the `Start` method still counts.

Oh yes, sorry. Will fix.

**Comment by papey** [comment]
Here is a refactor, I did not find an example of the `Start` function, so not sure if correct. If not correct, can you provide some example ? Thanks.

**Comment by Hipska** [comment]
This is the interface: [input.go](https://github.com/influxdata/telegraf/blob/master/input.go)

And these are some sample implementations:
https://github.com/influxdata/telegraf/blob/b07e94b66207b7f5c0a627b8f917939b1b7c20f9/plugins/inputs/sql/sql.go#L354-L392
https://github.com/influxdata/telegraf/blob/b07e94b66207b7f5c0a627b8f917939b1b7c20f9/plugins/inputs/mqtt_consumer/mqtt_consumer.go#L151-L166

File: plugins/inputs/mongodb/mongodb.go [hunk 1]
```diff
@@ -26,14 +26,16 @@ import (
...
+	Servers                []string
+	Ssl                    Ssl
+	GatherClusterStatus    bool
+	GatherPerdbStats       bool
+	GatherColStats         bool
+	GatherTopStat          bool
+	IgnoreUnreachableHosts bool
+	ColStatsDbs            []string
 	tlsint.ClientConfig
+	tlsConfig *tls.Config
```
Comment (Hipska) [inline plugins/inputs/mongodb/mongodb.go:38]: Keep the internal var with the other internal vars (`clients`).

File: plugins/inputs/mongodb/mongodb.go [hunk 2]
```diff
@@ -110,7 +116,11 @@ func (m *MongoDB) Init() error {
 
 		err = client.Ping(ctx, opts.ReadPreference)
 		if err != nil {
-			return fmt.Errorf("unable to connect to MongoDB: %s", err)
+			if !m.IgnoreUnreachableHosts {
+				return fmt.Errorf("unable to connect to MongoDB: %s", err)
```
Comment (Hipska) [inline plugins/inputs/mongodb/mongodb.go:120]: Errors should be printed with `%w`
```suggestion
				return fmt.Errorf("unable to connect to MongoDB: %w", err)
```

File: plugins/inputs/mongodb/mongodb.go [hunk 3]
```diff
@@ -110,7 +116,11 @@ func (m *MongoDB) Init() error {
...
+			}
+
+			m.Log.Infof("unable to connect do MongoDB: %s", err)
```
Comment (Hipska) [inline plugins/inputs/mongodb/mongodb.go:123]: I think severity `Info` is too low, I would pick `Warn` or `Error` here.

File: plugins/inputs/mongodb/mongodb_server_test.go [hunk 4]
```diff
@@ -82,3 +82,14 @@ func TestPoolStatsVersionCompatibility(t *testing.T) {
...
+
+func TestIgnoreUnreachableHosts(t *testing.T) {
+	m := &MongoDB{
+		Log:     testutil.Logger{},
+		Servers: []string{"mongodb://user:pass@127.0.0.1:27017/nop"},
+	}
+
+	m.IgnoreUnreachableHosts = true
+	err := m.Init()
+	require.NoError(t, err)
```
Comment (Hipska) [inline plugins/inputs/mongodb/mongodb_server_test.go:94]: I think the test should also test for no errors on `Start`?

File: plugins/inputs/mongodb/README.md [hunk 5]
```diff
@@ -43,6 +43,10 @@ All MongoDB server versions from 2.6 and higher are supported.
   # tls_key = "/etc/telegraf/key.pem"
   ## Use TLS but skip chain & host verification
   # insecure_skip_verify = false
+
+  ## When true, telegraf will not return an error on init if one of
+  ## the mongodb targets is unreachable
+  # ignore_unreachable_hosts = false
```
Comment (Hipska) [inline plugins/inputs/mongodb/README.md:49]:
```suggestion
  ## When true, telegraf will not return an error on start if one of
  ## the mongodb targets is unreachable
  # ignore_unreachable_hosts = false
```

**Review by Hipska — CHANGES_REQUESTED** [review]
Looks good overall, but shouldn't the ping then also be done at the start of the gathering for the server? Maybe it can be done only there?

**Comment by papey** [comment]
> Looks good overall, but shouldn't the ping then also be done at the start of the gathering for the server, it will reduce the amount of errors every gather interval?

Sounds good to me but how do we want that ?

In the current implementation on master if one of the Mongo servers becomes unreachable after init/start errors will be written in the logs.

IMO, it's ok to attach the behavior you describe to the new option, WDYT ?

**Comment by Hipska** [comment]
Yeah, so I was thinking, if this is enabled, then first ping the device and then only try to gather all the metrics if it does respond ok? Does that sounds reasonable?

**Comment by papey** [comment]
LGTM, i will implement it asap !

File: plugins/inputs/mongodb/mongodb.go [hunk 6]
```diff
@@ -89,28 +96,32 @@ func (m *MongoDB) Init() error {
...
 		}
 
 		err = client.Ping(ctx, opts.ReadPreference)
 		if err != nil {
-			return fmt.Errorf("unable to connect to MongoDB: %s", err)
+			if !m.IgnoreUnreachableHosts {
+				return fmt.Errorf("unable to connect to MongoDB: %w", err)
+			}
+
+			m.Log.Errorf("unable to connect do MongoDB: %s", err)
```
Comment (Hipska) [inline plugins/inputs/mongodb/mongodb.go:124]:
```suggestion
			m.Log.Errorf("unable to connect to MongoDB: %w", err)
```

File: plugins/inputs/mongodb/mongodb.go [hunk 7]
```diff
@@ -22,22 +22,25 @@ import (
 )
 
 // DO NOT REMOVE THE NEXT TWO LINES! This is required to embed the sampleConfig data.
+//
 //go:embed sample.conf
```
Comment (Hipska) [inline plugins/inputs/mongodb/mongodb.go:26]:
```suggestion
// DO NOT REMOVE THE NEXT TWO LINES! This is required to embed the sampleConfig data.
//go:embed sample.conf
```

**Review by Hipska — CHANGES_REQUESTED** [review]
Looks good, only minor typo's

**Comment by papey** [comment]
Damn sorry ! Thanks a lot for the feedback :+1:

**Review by Hipska — APPROVED** [review]

File: plugins/inputs/mongodb/mongodb_server.go [hunk 8]
```diff
@@ -37,6 +37,13 @@ func IsAuthorization(err error) bool {
 	return strings.Contains(err.Error(), "not authorized")
 }
 
+func (s *Server) ping() error {
+	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
```
Comment (reimda) [inline plugins/inputs/mongodb/mongodb_server.go:41]: This hard coded 10 seconds might need to be changed. For example, if someone uses this plugin with a 2 second gather and the server is down, ping timeouts will pile up.

File: plugins/inputs/mongodb/mongodb.go [hunk 9]
```diff
@@ -132,6 +142,12 @@ func (m *MongoDB) Gather(acc telegraf.Accumulator) error {
 		wg.Add(1)
 		go func(srv *Server) {
 			defer wg.Done()
+			if m.IgnoreUnreachableHosts {
+				if err := srv.ping(); err != nil {
```
Comment (reimda) [inline plugins/inputs/mongodb/mongodb.go:146]: Does pinging attempt to reconnect? In other words, if a server goes down, can it ever come back up or is it going to fail ping each gather from then on?

File: plugins/inputs/mongodb/sample.conf [hunk 10]
```diff
@@ -36,3 +36,9 @@
   # tls_key = "/etc/telegraf/key.pem"
   ## Use TLS but skip chain & host verification
   # insecure_skip_verify = false
+
+  ## When true, telegraf will not return an error on start if one of
+  ## the mongodb targets is unreachable
+  ## Note that while running, telegraf will also avoid data gathering for
+  ## unreachable mongo endpoints
+  # ignore_unreachable_hosts = false
```
Comment (reimda) [inline plugins/inputs/mongodb/sample.conf:44]: Could we change the name and the type of the config setting? It sounds like this fix only ignores server errors temporarily, but this name implies to me that it will ignore servers completely. I think from reading the code that it retries connecting to the server each gather and just ignores connection errors.

Earlier in the config we call the hosts "servers". It would be more clear to users if we continued using the same term here.

Also, using a boolean setting doesn't give any room to add other ways to handle the problem to be added in the future. If we use a string setting, we could add any number of future approaches.

```toml
disconnected_servers = "retry"
```

Then if someone wanted to do something else when a server disconnects (like log or remove from the list or whatever) there will already be a way to configure it.

**Review by reimda — CHANGES_REQUESTED** [review]

File: plugins/inputs/mongodb/mongodb_server.go (hunk 8 above)
Comment (papey) [reply plugins/inputs/mongodb/mongodb_server.go:41]: Do I have a way to get the current configured gather interval ?

File: plugins/inputs/mongodb/sample.conf (hunk 10 above)
Comment (papey) [reply plugins/inputs/mongodb/sample.conf:44]: Will do it for the naming hamonization.

On the "behavior" proposal, I was thinking about this at first but wasn't sure on the way to implement it : 

- What kind of strictness do we want, what happens if the option is not one of the accepted values ?
- Where the validation code should be place ? I didn't find something similar in the code base, do I have to make the check logic inside the plugin ?

File: plugins/inputs/mongodb/mongodb.go (hunk 9 above)
Comment (papey) [reply plugins/inputs/mongodb/mongodb.go:146]: `mongodb` go client spawns one go routine per conn and use it to monitor the connexion. Transient errors should be recoverable from the client it self.

File: plugins/inputs/mongodb/sample.conf (hunk 10 above)
Comment (Hipska) [reply plugins/inputs/mongodb/sample.conf:44]: The init function does the validation of the config, there is the internal `choice.Check` method.

File: plugins/inputs/mongodb/sample.conf [hunk 11]
```diff
@@ -36,3 +36,9 @@
   # tls_key = "/etc/telegraf/key.pem"
   ## Use TLS but skip chain & host verification
   # insecure_skip_verify = false
+
+  ## Specifies plugin behavior regarding disconnected servers
+  ## Available choices :
+  ##   - default: telegraf will return an error on startup if one the servers is unreachable
+  ##   - retry: telegraf will start anyway and retry connexions to unreachable servers
+  # disconnected_servers_behavior = default
```
Comment (Hipska) [inline plugins/inputs/mongodb/sample.conf:44]: I would name it "error" to indicate what telegraf will do (just like "retry"). Also strings needs quotes.
```suggestion
  ##   - error: telegraf will return an error on startup if one the servers is unreachable
  ##   - retry: telegraf will start anyway and retry connexions to unreachable servers
  # disconnected_servers_behavior = "error"
```

File: plugins/inputs/mongodb/mongodb.go [hunk 12]
```diff
@@ -50,10 +55,18 @@ func (*MongoDB) SampleConfig() string {
...
 func (m *MongoDB) Init() error {
-	var tlsConfig *tls.Config
+	if m.DisconnectedServersBehavior == "" {
+		m.DisconnectedServersBehavior = "default"
+	}
+
+	err := choice.Check(m.DisconnectedServersBehavior, DisconnectedServersBehaviors)
+	if err != nil {
+		return err
+	}
```
Comment (Hipska) [inline plugins/inputs/mongodb/mongodb.go:65]: Make the returned error a bit more descriptive
```suggestion
	err := choice.Check(m.DisconnectedServersBehavior, DisconnectedServersBehaviors)
	if err != nil {
		return fmt.Errorf("disconnected_servers_behavior: %w", err)
	}
```

File: plugins/inputs/mongodb/mongodb.go [hunk 13]
```diff
@@ -89,28 +107,32 @@ func (m *MongoDB) Init() error {
...
 
 		err = client.Ping(ctx, opts.ReadPreference)
 		if err != nil {
-			return fmt.Errorf("unable to connect to MongoDB: %s", err)
+			if m.DisconnectedServersBehavior == "default" {
+				return fmt.Errorf("unable to connect to MongoDB: %w", err)
+			}
+
+			m.Log.Errorf("unable to connect to MongoDB: %w", err)
 		}
```
Comment (Hipska) [inline plugins/inputs/mongodb/mongodb.go:136]: Maybe these errors should say unable to ping?

**Review by Hipska — CHANGES_REQUESTED** [review]

**Comment by papey** [comment]
There is just one behavior left we may want to discuss : 

When `Gather` is called on an unreachable server it waits a very looong time before returning back an error. This is the current behavior and this PR do not change anything about it. We may want to change it in another PR. WDYT ?

_Sorry for the the review requests mess, my internet was lagging and Github just goes crazy for no reason_

File: plugins/inputs/mongodb/mongodb.go [hunk 14]
```diff
@@ -50,10 +55,18 @@ func (*MongoDB) SampleConfig() string {
 }
 
 func (m *MongoDB) Init() error {
-	var tlsConfig *tls.Config
+	if m.DisconnectedServersBehavior == "" {
+		m.DisconnectedServersBehavior = "error"
+	}
+
+	err := choice.Check(m.DisconnectedServersBehavior, DisconnectedServersBehaviors)
+	if err != nil {
```
Comment (Hipska) [inline plugins/inputs/mongodb/mongodb.go:63]: Maybe single liner?
```suggestion
	if err := choice.Check(m.DisconnectedServersBehavior, DisconnectedServersBehaviors); err != nil {
```

**Review by Hipska — COMMENTED** [review]
Do you mean this is the current default behaviour? I think that's good, they can change to retry when they don't want that. But when thinking about that, "retry" might give wrong impression. I would expect telegraf to retry in the same poll interval. Maybe the value for this option should be "skip"?

Also, I don't get the new logic in Gather when behaviour is "retry". So seems like it returns and skips collection for the server if there is no error? That sounds a bit strange.

File: plugins/inputs/mongodb/mongodb_server.go (hunk 8 above)
Comment (reimda) [reply plugins/inputs/mongodb/mongodb_server.go]: There's no way for a plugin to get the gather interval.

After seeing this again, I don't think it's a big deal. In my example with 2 second gather interval, there could only be 5 concurrent pings.

I see that you reduced the timeout to 1s which helps too

**Comment by reimda** [comment]
> When `Gather` is called on an unreachable server it waits a very looong time before returning back an error. This is the current implementation and this PR do not change anything about it. We may want to change it in another PR. WDYT ?

Sounds good to me to work on that in a future PR.

**Review by reimda — APPROVED** [review]

File: plugins/inputs/mongodb/README.md [hunk 15]
```diff
@@ -43,6 +43,12 @@ All MongoDB server versions from 2.6 and higher are supported.
   # tls_key = "/etc/telegraf/key.pem"
   ## Use TLS but skip chain & host verification
   # insecure_skip_verify = false
+
+  ## Specifies plugin behavior regarding disconnected servers
+  ## Available choices :
+  ##   - error: telegraf will return an error on startup if one the servers is unreachable
+  ##   - retry: telegraf will start anyway and retry connexions to unreachable servers
```
Comment (reimda) [inline plugins/inputs/mongodb/README.md:50]: I missed a small misspelling

```suggestion
  ##   - retry: telegraf will start anyway and retry connections to unreachable servers
```

**Comment by papey** [comment]
@Hipska I changed the wording from "retry" to "skip", I also find it more clear. Thanks.

**Comment by papey** [comment]
> Do you mean this is the current default behaviour? I think that's good, they can change to retry when they don't want that. But when thinking about that, "retry" might give wrong impression. I would expect telegraf to retry in the same poll interval. Maybe the value for this option should be "skip"?
> 
> Also, I don't get the new logic in Gather when behaviour is "retry". So seems like it returns and skips collection for the server if there is no error? That sounds a bit strange.

Sorry I didn't get your point, if behavior is skip, we ping, if ping fails, we drop fetch from the current server :

```go
			if m.DisconnectedServersBehavior == "skip" {
				if err := srv.ping(); err != nil {
					return
				}
			}
```

**Review by Hipska — APPROVED** [review]

**Comment by Hipska** [comment]
> Sorry I didn't get your point, if behavior is skip, we ping, if ping fails, we drop fetch from the current server :

Nevermind, I was indeed looking wrong. Maybe we could add a debug log message with the content of the error before we return?
