### PR TITLE
Fix opcua integration test

### LINKED ISSUE #8737: Skipped integration tests due to failures
### Expected behavior:
make test-integration passes

### Actual behavior:
currently we are skipping these tests at all times as they are in a broken state: 

- [ ] Inputs: Openldap

```
FAIL: TestOpenldapReverseMetrics (0.01s)
openldap_test.go:170:
Error Trace:	openldap_test.go:170
Error:	Should be true
Test:	TestOpenldapReverseMetrics
Messages:	Has an integer field called connections_total
```

acc is getting this:

`[unable to read LDAP response packet: unexpected EOF]`

docker container shows:

` ldap_bind: Invalid DN syntax (34)`

- [ ] Inputs: Pgbouncer   

```
FAIL: TestPgBouncerGeneratesMetrics (0.02s)
pgbouncer_test.go:30:
Error Trace:	pgbouncer_test.go:30
Error:	Received unexpected error:
ERROR: not allowed (SQLSTATE 08P01)
Test:	TestPgBouncerGeneratesMetrics
```

docker container shows: 

`Pooler Error: not allowed after failed login`

- [x] Inputs: Opcua #9107

`Error: dial tcp 195.254.227.245:4840: connect: connection refused
`

- [ ] Outputs: Cratedb / Postgres 

```
-- FAIL: TestConnectAndWrite (0.38s)
cratedb_test.go:35:
Error Trace:	cratedb_test.go:35
Error:	Received unexpected error:
FATAL: trust authentication failed for user "username" (SQLSTATE 28000)
Test:	TestConnectAndWrite
```

### PR DESCRIPTION
**Pull request by R290**
### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.

Related to #8737

Changed remote `opcua.rocks` domain to docker container on `localhost`. The docker image is the same as the original server on opcua.rocks uses: `open62541/open62541`. See https://opcua.rocks/open62541-online-test-server/ for additional info.

### CODE REVIEW

**Review by Jagularr — APPROVED** [review]

File: plugins/inputs/opcua/opcua_client_test.go [hunk 1]
```diff
@@ -20,7 +20,6 @@ type OPCTags struct {
 }
 
 func TestClient1Integration(t *testing.T) {
-	t.Skip("Skipping due to dial tcp 195.254.227.245:4840: connect: connection refused")
```
Comment (helenosheaa) [inline plugins/inputs/opcua/opcua_client_test.go:23]: Could you add in --> 	

```
if testing.Short() {
		t.Skip("Skipping integration test in short mode")
	}
```

Otherwise it will fail on circleci as it's trying to run it and we don't currently have our build process setup to run integration tests with the docker file

**Review by helenosheaa — CHANGES_REQUESTED** [review]
Thanks for the PR! Could you add in the skip for the test in short mode, as we currently don't have the setup to run docker dependent integration tests on circleci. Also could you remove the resolves keyword as it will close the issue when we merge this PR and there are the other items on the issue.

File: plugins/inputs/opcua/opcua_client_test.go (hunk 1 above)
Comment (R290) [reply plugins/inputs/opcua/opcua_client_test.go:23]: Removed the keyword and added the short test exemption.

**Review by helenosheaa — APPROVED** [review]
Great, thanks
