### PR TITLE
fix(outputs.sql): Add timestamp to derived datatypes

### LINKED ISSUE #17309: outputs.sql - Unknown datatype time.Time with table updates enabled.
### Relevant telegraf.conf

```toml
table_update_template = "ALTER TABLE {TABLE} ADD COLUMN {COLUMN}"
```

### Logs from Telegraf

```text
2025-07-09T14:55:33Z E! [outputs.sql] Unknown datatype: 'time.Time' 2025-07-09 14:40:00 +0000 UTC
2025-07-09T14:55:33Z E! [outputs.sql] Unknown datatype: 'time.Time' 2025-07-09 14:40:00 +0000 UTC
2025-07-09T14:55:33Z E! [outputs.sql] Unknown datatype: 'time.Time' 2025-07-09 14:45:00 +0000 UTC
2025-07-09T14:55:33Z E! [outputs.sql] Unknown datatype: 'time.Time' 2025-07-09 14:50:00 +0000 UTC
2025-07-09T14:55:33Z E! [outputs.sql] Unknown datatype: 'time.Time' 2025-07-09 14:55:00 +0000 UTC
2025-07-09T14:55:33Z E! [outputs.sql] Unknown datatype: 'time.Time' 2025-07-09 14:40:00 +0000 UTC
2025-07-09T14:55:33Z E! [outputs.sql] Unknown datatype: 'time.Time' 2025-07-09 14:45:00 +0000 UTC
2025-07-09T14:55:33Z E! [outputs.sql] Unknown datatype: 'time.Time' 2025-07-09 14:50:00 +0000 UTC
2025-07-09T14:55:33Z E! [outputs.sql] Unknown datatype: 'time.Time' 2025-07-09 14:55:00 +0000 UTC
2025-07-09T14:55:33Z E! [outputs.sql] Unknown datatype: 'time.Time' 2025-07-09 14:45:00 +0000 UTC
2025-07-09T14:55:33Z E! [outputs.sql] Unknown datatype: 'time.Time' 2025-07-09 14:50:00 +0000 UTC
2025-07-09T14:55:33Z E! [outputs.sql] Unknown datatype: 'time.Time' 2025-07-09 14:55:00 +0000 UTC
2025-07-09T14:55:33Z E! [outputs.sql] Unknown datatype: 'time.Time' 2025-07-09 14:40:00 +0000 UTC
2025-07-09T14:55:33Z E! [outputs.sql] Unknown datatype: 'time.Time' 2025-07-09 14:45:00 +0000 UTC
2025-07-09T14:55:33Z E! [outputs.sql] Unknown datatype: 'time.Time' 2025-07-09 14:50:00 +0000 UTC
2025-07-09T14:55:33Z E! [outputs.sql] Unknown datatype: 'time.Time' 2025-07-09 14:55:00 +0000 UTC
2025-07-09T14:55:33Z E! [outputs.sql] Unknown datatype: 'time.Time' 2025-07-09 14:40:00 +0000 UTC
2025-07-09T14:55:33Z E! [outputs.sql] Unknown datatype: 'time.Time' 2025-07-09 14:45:00 +0000 UTC
2025-07-09T14:55:33Z E! [outputs.sql] Unknown datatype: 'time.Time' 2025-07-09 14:50:00 +0000 UTC
```

### System info

Telegraf 1.36.0-542dce70 - Ubuntu 22.04

### Docker

_No response_

### Steps to reproduce

Enable the update template, run your config.

### Expected behavior

Don't get errors.

### Actual behavior

Get unknown datatype error.

### Additional info

The deriveDataType method doesn't have a conversion for time.Time datatypes. If the metric is a time value, and the type is derived, it will fail. There are two places where types are derived, generateCreateTable and Write. 

generateCreateTable only calls deriveDataType on fields. If there is a metric with a time value in a field, this will fail.

Write only calls deriveDataType when there is an update table template. This includes the timestamp field, so you will get the Unknown datatype error.

Adding a case for time.Time into deriveDataType fixes this.

### PR DESCRIPTION
**Pull request by Soldrym**
## Summary

outputs.sql derived datatypes does not account for time.Time values causing errors.

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #17309

### CODE REVIEW

**Review by srebhan — COMMENTED** [review]
Thanks @Soldrym! The code looks good. Could you please add a unit-test to avoid future regressions!?

**Comment by Soldrym** [comment]
I added a unit test. Ran into issues where adding the field would just send through a nil and had to add a time.Time conversion to metric.convertField.

That was the most time I've ever spent adding 9 lines of code.

**Comment by Soldrym** [comment]
So I don't know what to do about this failing check. 

It's in plugins/inputs/ecs. They unmarshal the a json source file into a struct called ecsTask with a slice of ecsContainer structs in it. The ecsContainer struct has the CreatedAt and StartedAt fields, so that all makes sense. The final output function (metastats) creates a map with keys created_at and started_at with the values of CreatedAt and StartedAt, but the expected data does not have those fields. 

Before changing the metric convert field function, the ecs metastats function didn't output the created_at and started_at keys, so the expected matched the output. I just don't know if that's actually supposed to be like that. It looks like a bug in the ecs test but I don't know much about ECS.

File: metric/metric.go [hunk 1]
```diff
@@ -380,6 +380,8 @@ func convertField(v interface{}) interface{} {
 		if v != nil {
 			return float64(*v)
 		}
+	case time.Time:
+		return v
```
Comment (srebhan) [inline metric/metric.go]: Ummm no! Metrics can only hold basic types! `time.Time` is a complex time and should be handled by the plugin to convert to something handle-able by a metric field... Why do you need to introduce this?

Comment (Soldrym) [reply metric/metric.go]: I guess I don't need to. I didn't know that metrics should only contain basic types and anything such as a time value should just get nil'd out, which is current behavior. I'll just have to rewrite my test to assume no time can come in unless it's the single timestamp.

Comment (Soldrym) [reply metric/metric.go]: This has been reverted.

**Review by srebhan — APPROVED** [review]
Awesome! Thanks a lot @Soldrym!

**Review by skartikey — APPROVED** [review]
@Soldrym Thanks!
