### PR TITLE
fix(agent): Allow overriding collection_jitter with 0s on a per-input basis

### LINKED ISSUE #18517: collection_jitter = "0s" per plugin doesn't disable jitter
### Relevant telegraf.conf

```toml
[agent]
interval = "60s"
precision = "60s"
collection_jitter = "10s"
flush_interval = "10s"

[[inputs.internal]]
collect_memstats = false
collection_jitter = "0s"
```

### Logs from Telegraf

```text
-
```

### System info

Telegraf 1.38.0

### Docker

_No response_

### Steps to reproduce

1. have `collection_jitter = "10s"` in  the `[agent]` section
2. try to disable jitter per-input using `collection_jitter = "0s"`
3. observer that said input still runs with global jitter
...

### Expected behavior

have a way to disable jitter

### Actual behavior

I have to set `collection_jitter = "1ms"` to effectively disable it. I suspect truly 0 value is treated as unset somewhere.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by WZH8898**
Summary

Fix per-input `collection_jitter = "0s"` not overriding the agent-level jitter.

The input configuration parsing currently discards whether `collection_jitter` was explicitly set. As a result, both an unset value and an explicit `0s` are represented as the zero-value duration, and the agent logic treats both cases as "use the global collection_jitter".

This change preserves whether `collection_jitter` was explicitly configured on the input and updates the agent-side selection logic so that:
- an explicitly configured per-input value overrides the agent setting
- `collection_jitter = "0s"` disables jitter for that input
- an unset per-input value still falls back to the agent setting

Tests were added to verify:
- explicit `0s` is preserved during config parsing
- explicit `0s` overrides the agent-level jitter
- unset values still inherit the agent-level jitter

## Checklist

- [x] No AI generated code was used in this PR

## Related Issues

resolves #18517

### CODE REVIEW

File: agent/agent.go [hunk 1]
```diff
@@ -417,10 +417,7 @@ func (a *Agent) runInputs(ctx context.Context, startTime time.Time, unit *inputU
 		}
 
 		// Overwrite agent collection_jitter if this plugin has its own.
-		jitter := time.Duration(a.Config.Agent.CollectionJitter)
-		if input.Config.CollectionJitter != 0 {
-			jitter = input.Config.CollectionJitter
-		}
+		jitter := getCollectionJitter(time.Duration(a.Config.Agent.CollectionJitter), input.Config)
```
Comment (srebhan) [inline agent/agent.go]: Please don't move this to a function as it makes code harder to read as we need to follow all the nested redirections! Furthermore, the minimal change would be

```golang
		jitter := time.Duration(a.Config.Agent.CollectionJitter)
		if input.Config.CollectionJitterSet {
			jitter = input.Config.CollectionJitter
		}
```

which is also much more readable!

File: agent/agent_test.go [hunk 2]
```diff
@@ -177,6 +177,53 @@ func TestWindow(t *testing.T) {
 	}
 }
 
+func TestGetCollectionJitter(t *testing.T) {
+	t.Parallel()
```
Comment (srebhan) [inline agent/agent_test.go]: Why?

File: agent/agent_test.go [hunk 3]
```diff
@@ -177,6 +177,53 @@ func TestWindow(t *testing.T) {
...
+
+	agentJitter := 10 * time.Second
+	tests := []struct {
+		name   string
+		config *models.InputConfig
+		want   time.Duration
```
Comment (srebhan) [inline agent/agent_test.go]: Please call this `expected` as we do in other places.

File: agent/agent_test.go [hunk 4]
```diff
@@ -177,6 +177,53 @@ func TestWindow(t *testing.T) {
...
+				CollectionJitter:    0,
+				CollectionJitterSet: true,
+			},
+			want: 0,
+		},
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			t.Parallel()
```
Comment (srebhan) [inline agent/agent_test.go]: Why do you need this?

File: agent/agent_test.go [hunk 5]
```diff
@@ -177,6 +177,53 @@ func TestWindow(t *testing.T) {
...
+			got := getCollectionJitter(agentJitter, tt.config)
```
Comment (srebhan) [inline agent/agent_test.go]: No. Either really test the whole processing path, i.e. set the agent config, then initialize a model and check the jitter _or_ skip the test altogether. This tests really doesn't gain anything as-is.

File: agent/agent_test.go (hunk 2 above)
Comment (WZH8898) [reply agent/agent_test.go]: No strong reason beyond a table-driven helper test pattern. I removed this test to avoid low-value indirection.

File: agent/agent_test.go (hunk 4 above)
Comment (WZH8898) [reply agent/agent_test.go]: You are right, it wasn't needed here. Removed together with that helper test.

**Comment by WZH8898** [comment]
Hi @srebhan , I addressed the review comments in commit 0245d69.

Changes made:

kept the agent-side jitter selection inline, per your suggestion
removed the helper-style test
simplified the test changes to avoid low-value indirection

This PR is intended to fix #18517  by allowing an explicitly set per-input collection_jitter = "0s" to override the agent-level jitter.

This PR seems to have been auto-closed due to inactivity. Could you please reopen it for another look? Thanks!
