### PR TITLE
fix: Couchbase insecure certificate validation

### LINKED ISSUE #9454: Couchbase plugin stop working due to certificate verification of an self-signed certificate
### Relevant telegraf.conf:

```toml
[[inputs.couchbase]]
  servers = ["https://user:password@example.org:18091"]
```

### System info:
Telegraf version 1.19.0
Debian 9
Couchbase 6.5.1

### Steps to reproduce:

We upgraded our Telegraf package from version 1.17.x to 1.19.0.
After this upgrade we are getting error messages regarding certificate verification. See the logs in the additional info.

### Expected behavior:

Couchbase input plugin should still work or at least have an option to skip the verification step of an self-signed certificate.

### Actual behavior:

Couchbase metrics are not gather, however telegraf is still working for the other plugins.

### Additional info:

Error log from the systemd journal. 
```bash
Jun 30 09:59:40 someNode telegraf[11607]: 2021-06-30T09:59:40Z E! [inputs.couchbase] Error in plugin: Get "https://telegraf:***@localhost:18091/pools/default/buckets/someBucket/stats?": x509: certificate is not valid for any names, but wanted to match localhost
```

### PR DESCRIPTION
**Pull request by akrantz01**
### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.

resolves #9454 

Fixes a bug where the `couchbase` plugin would fail to retrieve bucket stats due to a self-signed certificate. Prior, only the bucket stats would fail because the couchbase library skips certificate verification by default unless a keypair and optional root certificate are provided.

### CODE REVIEW

**Comment by srebhan** [comment]
Hey @akrantz01 thanks for looking into this!

TBH, I'm not sure this is the right approach, as it uses an "insecure by default" approach without allowing the user to enforce strict security rules. So I think you should either replicate the client behavior (only insecure if no certificate is provided) _OR_ (and this is my preference) you allow the user to set `insecure_skip_verify` as an option.

File: plugins/inputs/couchbase/couchbase.go [hunk 1]
```diff
@@ -379,13 +391,39 @@ func (cb *Couchbase) Init() error {
...
+
 	return nil
 }
 
 func init() {
 	inputs.Add("couchbase", func() telegraf.Input {
 		return &Couchbase{
 			BucketStatsIncluded: []string{"quota_percent_used", "ops_per_sec", "disk_fetches", "item_count", "disk_used", "data_used", "mem_used"},
+			ClientConfig: tls.ClientConfig{
+				InsecureSkipVerify: true,
```
Comment (reimda) [inline plugins/inputs/couchbase/couchbase.go:425]: We can't skip tls verification by default. I'd prefer to default to false and then provide a helpful error message at runtime that gives the user the two options: 1. provide cert and key or 2. skip tls verification by setting insecure_skip_verify true. That way the user has to choose the insecure option and not us.

**Review by reimda — CHANGES_REQUESTED** [review]

File: plugins/inputs/couchbase/couchbase.go (hunk 1 above)
Comment (akrantz01) [reply plugins/inputs/couchbase/couchbase.go:425]: I agree it would be best to default to false. However, couchbase defaults to skipping TLS verification, so I was trying to keep it backward compatible.

Comment (reimda) [reply plugins/inputs/couchbase/couchbase.go:425]: So we use go-couchbase for everything but queryDetailedBucketStats, and go-couchbase skips verification by default? I looked through go-couchbase and see the same thing. They don't even provide a way to check what their default is. I would prefer to get our default from them so if they change in the future we won't be left defaulting to skipping, but that's not possible.

Comment (srebhan) [reply plugins/inputs/couchbase/couchbase.go:425]: If we **have to** reproduce their default it's also ok for me to have an `insecure_skip_verify` option defaulting to `true` with a big fat warning! I just want to make sure the user _can_ choose to be secure. :-)

Comment (ssoroka) [reply plugins/inputs/couchbase/couchbase.go:425]: skipping verification is a bad default, and if go-couchbase is doing it, we don't want to copy that. This should be:
```suggestion
				InsecureSkipVerify: false,
```
here and in the documentation.

File: plugins/inputs/couchbase/couchbase.go [hunk 2]
```diff
@@ -379,13 +391,39 @@ func (cb *Couchbase) Init() error {
...
+		Transport: &http.Transport{
+			MaxIdleConnsPerHost: couchbaseClient.MaxIdleConnsPerHost,
+			TLSClientConfig:     tlsConfig,
+		},
+	}
+
+	// Couchbase requires that a TLS cert and key be provided when insecure skip verify is disabled
+	if !cb.ClientConfig.InsecureSkipVerify && (cb.ClientConfig.TLSCert == "" || cb.ClientConfig.TLSKey == "") {
+		return fmt.Errorf("tls_cert and tls_key are required when insecure_skip_verify = false")
+	}
```
Comment (ssoroka) [inline plugins/inputs/couchbase/couchbase.go:410]: can you provide a reference to this? I don't understand this requirement. It seems like if there's no key or cert then TLS configuration should not be enabled.

**Review by ssoroka — CHANGES_REQUESTED** [review]
would like to see insecure_skip_verify default to false (we don't want to help users be insecure), and I think this doesn't work for connecting to couchbase without TLS.

File: plugins/inputs/couchbase/couchbase.go (hunk 2 above)
Comment (akrantz01) [reply plugins/inputs/couchbase/couchbase.go:410]: I misread some of the code in go-couchbase, the current implementation is incorrect.

**Review by sspaink — APPROVED** [review]

File: plugins/inputs/couchbase/couchbase.go (hunk 1 above)
Comment (srebhan) [reply plugins/inputs/couchbase/couchbase.go]: This would also be my preferred setting. :-)

**Review by srebhan — APPROVED** [review]
Looks good to me and also matches @ssoroka 's requests I think.

File: plugins/inputs/couchbase/couchbase.go [hunk 3]
```diff
@@ -36,10 +40,17 @@ var sampleConfig = `
 
   ## Filter bucket fields to include only here.
   # bucket_stats_included = ["quota_percent_used", "ops_per_sec", "disk_fetches", "item_count", "disk_used", "data_used", "mem_used"]
+
+  ## Optional TLS Config
+  # tls_ca = "/etc/telegraf/ca.pem"
+  # tls_cert = "/etc/telegraf/cert.pem"
+  # tls_key = "/etc/telegraf/key.pem"
+  ## Use TLS but skip chain & host verification (defaults to true)
```
Comment (reimda) [inline plugins/inputs/couchbase/couchbase.go:48]: With this latest change, insecure_skip_verify defaults to false, right?
```suggestion
  ## Use TLS but skip chain & host verification (defaults to false)
```

Comment (akrantz01) [reply plugins/inputs/couchbase/couchbase.go:48]: Yes, good catch

**Review by srebhan — APPROVED** [review]
Looks perfect to me. Thanks @akrantz01 for this nice PR!

**Review by reimda — APPROVED** [review]
Seems like the right thing to do to set the library's TLS settings based on ours.

**Comment by reimda** [comment]
Hey @akrantz01 could you resolve the conflicts and I'll merge this? Thanks again!

**Review by srebhan — APPROVED** [review]
Still looks good.

**Comment by powersj** [comment]
I want to click merge, but lint is failing in couchbase_test.go. Tried editing it in GitHub, but it doesn't show as an issue. Pulling down the MP does show the issue, so typing `make fmt` and pushing a final commit should do it!

**Comment by powersj** [comment]
@akrantz01 thank you for bringing this one home!
