### PR TITLE
fix(inputs.jenkins): Report all concurrent builds

### LINKED ISSUE #6966: Jenkins plugin doesn't collect all builds for a job
The plugin only collects the metrics of builds that have finished. That's fine, but it also only collects the metrics of the last build to run within a job. So if there is a new build that starts before the previous has finished, the metrics of the previous build will not be collected.

### System info:
telegraf 1.13.2 Docker image

### Steps to reproduce:
1. Configure Jenkins plugin
2. Run two concurrent builds in Jenkins

### Expected behavior:
Both builds will be recorded. Even better, I want all builds within the `max_build_age` setting of the conf file to be recorded.

### Actual behavior:
Only the last build to finish will be recorded.

### LINKED ISSUE #18345: inputs.jenkins: Only lastBuild is reported, missing concurrent and queued builds
### Relevant telegraf.conf

```toml
[[inputs.jenkins]]
  url = "${JENKINS_URL}"
  ## No authentication — setup wizard is disabled
  # username = ""
  # password = ""

  ## Collect all job and node metrics
  max_build_age = "1h"
  max_connections = 5
  response_timeout = "10s"
```

### Logs from Telegraf

```text
# (The Telegraf logs do not have any errors or entries related to this bug.)

podman compose logs telegraf
telegraf  | 2026-02-13T01:31:27Z W! Strict environment variable handling will be the new default starting with v1.38.0! If your configuration works with strict handling or you don't use environment variables it is safe to ignore this warning. Otherwise please explicitly add the --non-strict-env-handling flag!
telegraf  | 2026-02-13T01:31:27Z I! Loading config: /etc/telegraf/telegraf.conf
telegraf  | 2026-02-13T01:31:27Z I! Starting Telegraf 1.37.1 brought to you by InfluxData the makers of InfluxDB
telegraf  | 2026-02-13T01:31:27Z I! Available plugins: 243 inputs, 9 aggregators, 35 processors, 26 parsers, 67 outputs, 8 secret-stores
telegraf  | 2026-02-13T01:31:27Z I! Loaded inputs: jenkins
telegraf  | 2026-02-13T01:31:27Z I! Loaded aggregators:
telegraf  | 2026-02-13T01:31:27Z I! Loaded processors:
telegraf  | 2026-02-13T01:31:27Z I! Loaded secretstores:
telegraf  | 2026-02-13T01:31:27Z I! Loaded outputs: influxdb_v2
telegraf  | 2026-02-13T01:31:27Z I! Tags enabled: host=39c273fc6f2c
telegraf  | 2026-02-13T01:31:27Z I! [agent] Config: Interval:30s, Quiet:false, Hostname:"39c273fc6f2c", Flush Interval:10s
telegraf  | 2026-02-13T01:31:27Z W! [agent] The default value of 'skip_processors_after_aggregators' will change to 'true' with Telegraf v1.40.0! If you need the current default behavior, please explicitly set the option to 'false'!
```

### System info

Telegraf 1.37.1 (git: HEAD@3352c0d5), Debian GNU/Linux 12 (bookworm), Podman Engine 5.7.1

### Docker

See https://github.com/jeffhoek/tig-stack for Telegraf-InfluxDB-Grafana (TIG) + Jenkins stack for testing and validation.

### Steps to reproduce

1. Configure a Jenkins job that allows concurrent builds (or triggers builds faster than they complete so one queues behind another). For example, create a Freestyle job that sleeps for 10 seconds.
2. Trigger two builds in quick succession
3. Observe that jenkins_job metrics are missing for one of the builds

Image

Image

### Expected behavior

All completed builds within max_build_age should be reported as jenkins_job metrics.

### Actual behavior

Only lastBuild is checked. If that build is still running, the plugin skips the entire job and reports nothing — even if other builds have already completed. This leads to two failure modes:

1. Running + completed builds: If lastBuild is still building, the plugin returns early. Any older builds that already finished are never reported.
2. Multiple completed builds: If two or more builds complete between gather cycles, only the  latest (lastBuild) is reported. The others are lost.

### Additional info

This issue is similar to https://github.com/influxdata/telegraf/issues/6966, but the report is more comprehensive and forthcoming fix much more concise.

The Jenkins input plugin only inspects the lastBuild field from the Jenkins API when collecting build metrics. This means only a single build per job is ever evaluated per gather cycle. When a job has multiple builds — whether running concurrently or queued — completed builds are silently dropped.

Root cause:
In getJobDetail(), the plugin reads only js.LastBuild.Number and fetches that single build. The Jenkins API also returns a builds array containing all recent builds, but this field was not being used.

Affected versions:  All current versions of the plugin.

### PR DESCRIPTION
**Pull request by jeffhoek**
## Summary
Report all concurrent builds, not just lastBuild. The plugin
previously only checked lastBuild for each job, missing builds
that completed alongside it. Now iterates over the builds array
from the Jenkins API, falling back to lastBuild when the array
is empty for backwards compatibility.

Bound build fetching by adding a tree query parameter to the
getJobs API call, limiting the builds array to 20 entries
server-side. This prevents unbounded HTTP requests for jobs
with thousands of historical builds.

Improve error resilience in the build fetch loop by replacing
return err with acc.AddError + continue. A single getBuild
failure no longer aborts the entire job; remaining builds are
still processed.

Replace break with continue for the MaxBuildAge check so an
out-of-order old build no longer stops iteration and silently
drops subsequent newer builds.

## Checklist
- [ ] No AI generated code was used in this PR
- [x] AI generated code used in this PR follows the [InfluxData Policy on AI-Generated Code Contributions][policy]

[policy]: https://www.influxdata.com/ai-generated-code-contributions-policy

## Related issues
resolves #6966
resolves #18345

### CODE REVIEW

File: plugins/inputs/jenkins/jenkins.go [hunk 1]
```diff
@@ -290,31 +290,37 @@ func (j *Jenkins) getJobDetail(jr jobRequest, acc telegraf.Accumulator) error {
...
-		return nil
-	}
+	for _, jb := range builds {
+		if jb.Number < 1 {
+			continue
+		}
+
+		build, err := j.client.getBuild(context.Background(), jr, jb.Number)
+		if err != nil {
+			return err
```
Comment (mstrandboge) [inline plugins/inputs/jenkins/jenkins.go]: Does it make sense to error here, or is there a case where we may still want to see the other builds? Since returning the error here will result in all of the builds of this "batch" not being gathered

Comment (jeffhoek) [reply plugins/inputs/jenkins/jenkins.go]: Good catch. Yeah I think instead we should accumulate the errors `accAddError(err)` and use a continue here similar to line 281.

I re-reviewed this PR myself and actually think a bigger concern is the unbounded loop. I'll add a separate comment for discussion on that issue.

File: plugins/inputs/jenkins/jenkins.go [hunk 2]
```diff
@@ -290,31 +290,37 @@ func (j *Jenkins) getJobDetail(jr jobRequest, acc telegraf.Accumulator) error {
...
 
-	// stop if build is too old
-	// Higher up in gatherJobs
 	cutoff := time.Now().Add(-1 * time.Duration(j.MaxBuildAge))
 
-	// Here we just test
-	if build.getTimestamp().Before(cutoff) {
-		return nil
-	}
+	for _, jb := range builds {
```
Comment (jeffhoek) [inline plugins/inputs/jenkins/jenkins.go:306]: *Performance concern:* unbounded build fetching

The new loop iterates over js.Builds and makes a getBuild() HTTP call for each entry. Jenkins returns all historical builds in the builds array by default, so for a job with hundreds or thousands of builds, this will fire an HTTP request per build until it hits one older than MaxBuildAge and breaks out of the loop.

*Proposed fix:* Use Jenkins' tree query parameter on the getJobs call to limit the builds array server-side (e.g. tree=builds[number]{0,20}). This caps the number of build stubs returned — and therefore the number of getBuild() HTTP calls — without needing a new config option. MaxBuildAge remains the user-facing control for which builds get reported; the tree limit just prevents fetching an unbounded number of build stubs before the age filter can be applied. A hardcoded cap of ~20 should be generous enough to cover any realistic number of concurrent builds within a MaxBuildAge window.

Alternatively, the cap could be exposed as a config option (e.g. max_builds_per_job) for users who need to tune it for unusually active jobs, but a sensible hardcoded default is likely sufficient for most environments.

File: plugins/inputs/jenkins/jenkins_test.go [hunk 3]
```diff
@@ -719,6 +719,168 @@ func TestGatherLabels(t *testing.T) {
 	testutil.RequireMetricsEqual(t, expected, actual, options...)
 }
 
+func TestGatherJobsMultipleBuilds(t *testing.T) {
```
Comment (jeffhoek) [inline plugins/inputs/jenkins/jenkins_test.go]: Test only covers the happy path. 

Consider adding cases for:
  - A build that's still running (should be skipped)
  - A build older than MaxBuildAge (should be skipped, and subsequent builds too per the break logic)
  - The fallback path where Builds is empty and LastBuild is used
  - An empty Builds array with LastBuild.Number < 1 (no builds at all)

  These would help verify the edge cases and the backwards-compatibility fallback.

File: plugins/inputs/jenkins/jenkins.go [hunk 4]
```diff
@@ -290,31 +290,37 @@ func (j *Jenkins) getJobDetail(jr jobRequest, acc telegraf.Accumulator) error {
...
+		}
 
-	j.gatherJobBuild(jr, build, acc)
+		if build.Building {
+			j.Log.Debugf("Ignore running build on %s, build %v", jr.name, jb.Number)
+			continue
+		}
+
+		if build.getTimestamp().Before(cutoff) {
+			break // builds are newest-first, so all remaining are older
```
Comment (jeffhoek) [inline plugins/inputs/jenkins/jenkins.go]: The comment says builds are newest-first, which is the Jenkins default. However, this is an assumption about the Jenkins API response ordering — if a Jenkins instance or plugin returns them differently, metrics would be silently dropped. A continue instead of break would be safer (at the cost of iterating more builds), or we could sort the builds slice by number descending before iterating to guarantee the invariant.

**Review by jeffhoek — COMMENTED** [review]
I can't request changes on my own PR, but do feel strongly some of these should be implemented. Thank you for your feedback.

File: plugins/inputs/jenkins/jenkins.go (hunk 1 above)
Comment (skartikey) [reply plugins/inputs/jenkins/jenkins.go]: Agree with both of you. Using acc.AddError(err) + continue is the right approach here, it matches the existing pattern in gatherNodesData() and ensures a transient failure on one build doesn't silently drop metrics for all other builds in the job.

File: plugins/inputs/jenkins/jenkins.go (hunk 2 above)
Comment (skartikey) [reply plugins/inputs/jenkins/jenkins.go:306]: Good call on the unbounded iteration. The tree parameter approach is the right fix, it limits the response at the source rather than adding client-side caps.

  A few thoughts:
  - A hardcoded cap (e.g., 20) should be sufficient. Exposing it as a config option adds complexity for a knob most users will never need to tune. If someone does need more, it can always be added later.
  - The tree parameter would go on the getJobs call in client.go, the job detail URL would become something like /job/{name}/api/json?tree=builds[number],lastBuild[number],jobs[name,url,color],name. This keeps
  the existing fields and just bounds builds.
  - Make sure the lastBuild field is still requested for the fallback path.

File: plugins/inputs/jenkins/jenkins_test.go (hunk 3 above)
Comment (skartikey) [reply plugins/inputs/jenkins/jenkins_test.go]: Good self-review. All of these cases are important. The "running + completed builds" case is especially critical since that's the primary failure mode described in issue #18345 it should be the first test case added.

Since these would add multiple entries, the table-driven structure will be justified.

File: plugins/inputs/jenkins/jenkins.go (hunk 4 above)
Comment (skartikey) [reply plugins/inputs/jenkins/jenkins.go]: I'd recommend continue instead of break here. The performance difference is negligible in practice (bounded by the tree parameter cap if that's implemented), and it eliminates the ordering assumption entirely.
Sorting adds code and an allocation for a problem that continue solves more simply.

  If the tree parameter is added to cap the builds array at ~20, iterating all 20 with continue is trivially cheap.

**Comment by jeffhoek** [comment]
I noticed the `TestMysqlEmptyTimestampColumnIntegration` failure in `test-integration` logs, which looks unrelated (I see several other PRs hitting this error).

```
Version: '12.2.2-MariaDB-ubu2404'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
--- Container Logs End ---
--- FAIL: TestMysqlEmptyTimestampColumnIntegration (19.46s)
...
Exited with code exit status 2
```

File: plugins/inputs/jenkins/jenkins_test.go [hunk 5]
```diff
@@ -719,6 +720,681 @@ func TestGatherLabels(t *testing.T) {
...
+		ResponseTimeout: config.Duration(time.Second),
+		Log:             testutil.Logger{},
+	}
+
+	var acc testutil.Accumulator
+	require.NoError(t, plugin.Gather(&acc))
+
+	// Should have recorded an error for the failed build fetch
+	require.Len(t, acc.Errors, 1)
+	require.Contains(t, acc.Errors[0].Error(), "404")
```
Comment (skartikey) [inline plugins/inputs/jenkins/jenkins_test.go]: Per Telegraf guidelines, this should be:
```suggestion
	require.ErrorContains(t, acc.Errors[0], "404")
```

File: plugins/inputs/jenkins/jenkins_test.go [hunk 6]
```diff
@@ -719,6 +720,681 @@ func TestGatherLabels(t *testing.T) {
...
+			Timestamp: (time.Now().Unix() - int64(time.Minute.Seconds())) * 1000,
+		},
+		"/job/pipeline/2/api/json": &buildResponse{
+			Building:  false,
+			Result:    "SUCCESS",
+			Duration:  20000,
+			Number:    2,
+			Timestamp: (time.Now().Unix() - int64((2 * time.Hour).Seconds())) * 1000,
+		},
+		// Build 1 should never be fetched because build 2 is already too old
```
Comment (skartikey) [inline plugins/inputs/jenkins/jenkins_test.go]: The test name says "StopsIteration" and the comment says

```
// Build 1 should never be fetched because build 2 is already too old.
```

However, the code uses `continue` (not `break`), so build 1 IS fetched, it's just filtered out after the HTTP request because it's also old. The test passes regardless because it only checks emitted metrics, not whether HTTP requests were made.

Either:

* Rename to `TestGatherMaxBuildAgeFiltersOldBuilds` and fix the comment to say "Build 1 is also too old, so no metric is emitted for it"
* Or, if the intent is to actually stop fetching old builds (optimization), use `break` in the code and verify build 1 is not fetched (e.g., with a request counter as in `TestGatherBuildsCappedAt20`)

This conflicts with `TestGatherOldBuildAmongNewBuilds` which correctly validates that `continue` allows newer builds to be processed after old ones. Both behaviors can't be true simultaneously for the same code.

File: plugins/inputs/jenkins/client.go [hunk 7]
```diff
@@ -132,7 +132,7 @@ func (c *client) getJobs(ctx context.Context, jr *jobRequest) (js *jobResponse,
 	js = new(jobResponse)
 	url := jobPath
 	if jr != nil {
-		url = jr.url()
+		url = jr.url() + "?tree=builds[number,url]{0,20},lastBuild[number,url],jobs[name,url,color],name"
```
Comment (skartikey) [inline plugins/inputs/jenkins/client.go]: The build limit {0,20} is hardcoded in the tree query string. This should be a constant:
  `const maxBuildsPerJob = 20`
  And the query string should use fmt.Sprintf to incorporate it. This makes the limit self-documenting and easier to find/change.

File: plugins/inputs/jenkins/jenkins_test.go [hunk 8]
```diff
@@ -719,6 +720,681 @@ func TestGatherLabels(t *testing.T) {
...
+	now := time.Now()
+
+	// Build the job response with 25 builds (newest-first)
+	builds := make([]jobBuild, totalBuilds)
+	for i := 0; i < totalBuilds; i++ {
+		builds[i] = jobBuild{Number: int64(totalBuilds - i)}
+	}
+
+	// Track how many build-detail requests are made
+	var buildFetchCount int
```
Comment (skartikey) [inline plugins/inputs/jenkins/jenkins_test.go]: The buildFetchCount variable is incremented in the HTTP handler goroutine and read in the test goroutine after Gather returns. While the HTTP request/response cycle provides implicit synchronization, using
  atomic.Int32 would be more robust and pass the race detector cleanly:
  `var buildFetchCount atomic.Int32`
  // In handler:
`  buildFetchCount.Add(1)`
  // In assertion:
  `require.LessOrEqual(t, int(buildFetchCount.Load()), maxExpectedFetches, ...)`

File: plugins/inputs/jenkins/jenkins_test.go [hunk 9]
```diff
@@ -719,6 +720,681 @@ func TestGatherLabels(t *testing.T) {
...
+			resp = &jobResponse{
+				Jobs: []innerJob{{Name: "pipeline"}},
+			}
+		case "/computer/api/json":
+			resp = &nodeResponse{}
+		case "/job/pipeline/api/json":
+			// Simulate Jenkins honoring the tree parameter:
+			// when the request includes tree=...{0,20}, return only 20 builds.
+			buildsToReturn := builds
+			if strings.Contains(r.URL.RawQuery, "tree=") && len(buildsToReturn) > maxExpectedFetches {
```
Comment (skartikey) [inline plugins/inputs/jenkins/jenkins_test.go]: The test manually truncates the builds list if strings.Contains(r.URL.RawQuery, "tree=") in the mock handler, then asserts the fetch count is <= 20. This only verifies that if the server honors the tree parameter, fewer fetches occur. It doesn't verify that the client sends the correct tree parameter. Consider also asserting that the query string contains the expected tree parameter:
  `require.Contains(t, r.URL.RawQuery, "tree=")`

File: plugins/inputs/jenkins/jenkins.go [hunk 10]
```diff
@@ -290,31 +290,38 @@ func (j *Jenkins) getJobDetail(jr jobRequest, acc telegraf.Accumulator) error {
...
-	}
-	build, err := j.client.getBuild(context.Background(), jr, number)
-	if err != nil {
-		return err
-	}
-
-	if build.Building {
-		j.Log.Debugf("Ignore running build on %s, build %v", jr.name, number)
-		return nil
+	builds := js.Builds
```
Comment (skartikey) [inline plugins/inputs/jenkins/jenkins.go:293]: Build limit is only enforced server-side
The {0,20} tree parameter is a hint to the Jenkins server. If a Jenkins instance doesn't honor it (older version, different plugin), the builds array could contain any number of entries. The Go code has no client-side enforcement. Consider adding:
```
  if len(builds) > maxBuildsPerJob {
      builds = builds[:maxBuildsPerJob]
  }
```

**Review by skartikey — COMMENTED** [review]
@jeffhoek Thanks for submitting the PR! I’ve left a few comments for you to review.

File: plugins/inputs/jenkins/jenkins.go (hunk 10 above)
Comment (jeffhoek) [reply plugins/inputs/jenkins/jenkins.go:293]: addressed with change on lines 300-301 below

**Comment by jeffhoek** [comment]
@skartikey Thank you for your feedback. I've implemented your suggestions and resolved each comment. Please LMK if you have any additional questions or concerns.

File: plugins/inputs/jenkins/jenkins_test.go [hunk 11]
```diff
@@ -719,6 +721,686 @@ func TestGatherLabels(t *testing.T) {
...
+
+	// Build the job response with 25 builds (newest-first)
+	builds := make([]jobBuild, totalBuilds)
+	for i := 0; i < totalBuilds; i++ {
+		builds[i] = jobBuild{Number: int64(totalBuilds - i)}
+	}
+
+	// Track how many build-detail requests are made and whether the tree parameter was sent
+	var buildFetchCount atomic.Int32
+	var treeParameterSeen bool
```
Comment (skartikey) [inline plugins/inputs/jenkins/jenkins_test.go]: treeParameterSeen is a plain bool written in the HTTP handler goroutine and read in the test goroutine. While buildFetchCount correctly uses atomic.Int32, this variable has the same concurrency issue. The race detector will likely flag this.

  // Current:
  var treeParameterSeen bool

  // Should be:
  var treeParameterSeen atomic.Bool

  // In handler:
  treeParameterSeen.Store(true)

  // In assertion:
  require.True(t, treeParameterSeen.Load(), "expected the job request to include a tree query parameter")

File: plugins/inputs/jenkins/jenkins_test.go [hunk 12]
```diff
@@ -719,6 +721,686 @@ func TestGatherLabels(t *testing.T) {
...
+		testutil.IgnoreTime(),
+		testutil.SortMetrics(),
+		testutil.IgnoreTags("port"),
+	}
+
+	actual := acc.GetTelegrafMetrics()
+	testutil.RequireMetricsEqual(t, expected, actual, options...)
+}
+
+func TestGatherJobsMultipleBuilds(t *testing.T) {
```
Comment (skartikey) [inline plugins/inputs/jenkins/jenkins_test.go]: Six separate test functions should be one table-driven test 

These 6 tests all share identical structure (response map + expected metrics -> call gatherJobBuildsHelper):
  - TestGatherJobsMultipleBuilds
  - TestGatherRunningBuildSkipped
  - TestGatherMaxBuildAgeFiltersOldBuilds
  - TestGatherLastBuildFallback
  - TestGatherNoBuildWhenLastBuildInvalid
  - TestGatherOldBuildAmongNewBuilds

  They should be a single `TestGatherJobBuilds` with table cases. The `gatherJobBuildsHelper` body becomes the test loop body, and the helper is eliminated.

  `TestGatherBuildFetchErrorPartial` and `TestGatherBuildsCappedAt20` have unique logic and are fine as standalone functions.

File: plugins/inputs/jenkins/jenkins_test.go [hunk 13]
```diff
@@ -719,6 +721,686 @@ func TestGatherLabels(t *testing.T) {
...
+				Timestamp: (now.Unix() - int64(time.Minute.Seconds())) * 1000,
+			}
+		}
+
+		buf, err := json.Marshal(resp)
+		if err != nil {
+			w.WriteHeader(http.StatusInternalServerError)
+			return
+		}
+		w.Write(buf) //nolint:errcheck // test server response write
```
Comment (skartikey) [inline plugins/inputs/jenkins/jenkins_test.go]: w.Write(buf) //nolint:errcheck inconsistency:
All other handlers (including the gatherJobBuildsHelper handler and existing tests) properly check the error:
```
  if _, err := w.Write(buf); err != nil {
      t.Logf("writing failed: %v", err)
      t.Fail()
  }
```

  Should be consistent.

File: plugins/inputs/jenkins/jenkins_test.go [hunk 14]
```diff
@@ -719,6 +721,686 @@ func TestGatherLabels(t *testing.T) {
...
+func TestGatherLastBuildFallback(t *testing.T) {
+	response := map[string]interface{}{
+		"/api/json": &jobResponse{
+			Jobs: []innerJob{
+				{Name: "pipeline"},
+			},
+		},
+		"/computer/api/json": nodeResponse{},
+		"/job/pipeline/api/json": &jobResponse{
+			Builds:    make([]jobBuild, 0),
```
Comment (skartikey) [inline plugins/inputs/jenkins/jenkins_test.go]: Since the code checks len(builds) == 0 which handles both nil and empty slices, nil is simpler and avoids the allocation.
```suggestion
			Builds:    nil,
```

File: plugins/inputs/jenkins/jenkins_test.go [hunk 15]
```diff
@@ -719,6 +721,686 @@ func TestGatherLabels(t *testing.T) {
...
+func TestGatherNoBuildWhenLastBuildInvalid(t *testing.T) {
+	response := map[string]interface{}{
+		"/api/json": &jobResponse{
+			Jobs: []innerJob{
+				{Name: "pipeline"},
+			},
+		},
+		"/computer/api/json": nodeResponse{},
+		"/job/pipeline/api/json": &jobResponse{
+			Builds:    make([]jobBuild, 0),
```
Comment (skartikey) [inline plugins/inputs/jenkins/jenkins_test.go]: Since the code checks len(builds) == 0 which handles both nil and empty slices, nil is simpler and avoids the allocation.
```suggestion
			Builds:    nil,
```

File: plugins/inputs/jenkins/client.go [hunk 16]
```diff
@@ -132,7 +134,7 @@ func (c *client) getJobs(ctx context.Context, jr *jobRequest) (js *jobResponse,
 	js = new(jobResponse)
 	url := jobPath
 	if jr != nil {
-		url = jr.url()
+		url = jr.url() + fmt.Sprintf("?tree=builds[number,url]{0,%d},lastBuild[number,url],jobs[name,url,color],name", maxBuildsPerJob)
```
Comment (skartikey) [inline plugins/inputs/jenkins/client.go]: Since maxBuildsPerJob is a constant, this fmt.Sprintf call allocates on every getJobs invocation. Could be a package-level var:
`  var jobTreeParam = fmt.Sprintf("?tree=builds[number,url]{0,%d},lastBuild[number,url],jobs[name,url,color],name", maxBuildsPerJob)`

  This is very minor and more of a readability/DRY improvement than a performance concern.

File: plugins/inputs/jenkins/client.go [hunk 17]
```diff
@@ -8,6 +8,10 @@ import (
 	"strings"
 )
 
+const maxBuildsPerJob = 20
+
+var jobTreeParam = fmt.Sprintf("?tree=builds[number,url]{0,%d},lastBuild[number,url],jobs[name,url,color],name", maxBuildsPerJob)
```
Comment (srebhan) [inline plugins/inputs/jenkins/client.go]: Please don't declare this as a variable as it is
1. a constant string that you could simply expand
2. only used in one spot

My suggestion is to move the `fmt.Sprintf` to the calling site (line 139) and construct the whole URL in the format statement.

Comment (jeffhoek) [reply plugins/inputs/jenkins/client.go]: Unless I'm misunderstanding your comment I had it that way initially, but changed it in response @skartikey comment: https://github.com/influxdata/telegraf/pull/18347#discussion_r2818826103. I am fine with either implementation, and happy to switch it back.

**Comment by jeffhoek** [comment]
@srebhan I'd like to respectfully push back on the `feat` classification (I did change the PR title, but would prefer`fix`). The plugin's stated purpose  is to collect Jenkins build metrics. When concurrent builds exist, the existing code  silently drops all but the last one — users have no idea their data is missing. That's a defect in correctness, not an absence of a feature. Issue #18345 is labeled bug by  maintainers. I agree #6966 has a feat label, but its description ("only collects the metrics of the last build to run within a job") describes broken behavior, not missing functionality. Happy to defer to maintainer consensus, but wanted to make the case for fix.

**Comment by srebhan** [comment]
@jeffhoek thanks for your detailed information above and sorry for the forth-and-back.

 I was thinking about

```golang
url = fmt.Sprintf("%s?tree=builds[number,url]{0,%d},lastBuild[number,url],jobs[name,url,color],name", jr.url(), maxBuildsPerJob)
```

The comment by @skartikey is correct in general but here we have to constructing the string in each iteration anyway... So I prefer to switch to the code above.

For the fix vs feature I agree with your explanation! Thanks for bringing this up. I switched the title back...
