### PR TITLE
fix: directory monitor input plugin when data format is CSV and csv_skip_rows>0 and csv_header_row_count>=1

### LINKED ISSUE #5338: csv-data omitting csv_comment with input.tail
### Relevant telegraf.conf:
Slightly modified from #5334 by adding csv_comment="#" and changing test input with starting line "#version=13.0". Your #5336 has the example code to produce.

### System info:
telegraf --version

Telegraf unknown (git: master efbc83c)
- was cloned and compiled yesterday so not yet having fix #5336 if that is merged to master branch

### Steps to reproduce:

I experimented more with input.tail and tried csv_comment:
- added configuration to existing
csv_comment = "#"

- changed input file
#version=13.0
date,instance,Incoming Requests,Outgoing Requests,Incoming Answers 2xxx,Outgoing Answers 2xxx,Incoming Answers UTD,Outgoing Answers UTD,Incoming Answers Redirect,Outgoing Answers Redirec...

### Expected behavior:
First line to be skipped because it is CSV comment, 2nd line used as headers and from 3rd line onwards all data

### Actual behavior:
2019-01-24T07:25:35Z D! [agent] Starting service inputs
2019-01-24T07:25:35Z D! [inputs.tail] tail added for file: testlog
2019-01-24T07:25:35Z E! [inputs.tail]: Error in plugin: E! Malformed log line in testlog: [#version=13.0], Error: EOF
2019-01-24T07:25:35Z E! [inputs.tail]: Error in plugin: E! Malformed log line in testlog: [date,instance,In coming Requests,Outgoing Requests,Incoming Answers 2xxx,Outgoing Answers 2xxx,Incoming Answers UTD,Outgoing Answers UTD,Incoming Answers Redirect,Outgoing Answers Redirect,Incoming Answers Other,Outgoing Answers Other,Retransmit Requests,Rejected Requests Filtering,Rejected Requests In-gress Filtering,Rejected Requests Other,Timeout Requests,Discarded Answers], Error: [parsers.csv] data columns must be specified

### Additional info:

I converted **input.tail** to **input.file** and ..

    csv_comment works as expected - outputs CSV data starting from line 3
    csv_skip_rows works different (ref #5336), not more parsing error on headers but...

2019-01-24T07:33:35Z D! [agent] Starting service inputs
2019-01-24T07:33:40Z E! [inputs.file]: Error in plugin: timestamp column: date could not be found
2019-01-24T07:33:50Z E! [inputs.file]: Error in plugin: timestamp column: date could not be found

### LINKED ISSUE #9898: csv_skip_rows>0 and csv_header_row_count>=1 results in error while reading file
When using ```inputs.directory_monitor``` with the CSV data format. CSV files that start with metadata or have multi-row headers would result in an error while reading the file. 

### Relevant telegraf.conf:
```toml
[[inputs.directory_monitor]]
  directory = "/path/to/unprocessed"
  finished_directory = "/path/to/processed"
  error_directory = "/path/to/error"
  files_to_monitor = ["^.*\.csv"]
  file_tag = "filename"
  data_format = "csv"
  csv_header_row_count = 1
  csv_column_names = []
  csv_column_types = []
  csv_skip_rows = 2
  csv_skip_columns = 0
  csv_delimiter = ","
  csv_comment = ""
  csv_trim_space = false
  csv_tag_columns = []
  csv_measurement_column = ""
  csv_timestamp_column = ""
  csv_timestamp_format = ""
  csv_timezone = ""
  csv_skip_values = []
```

### System info:

Telegraf 1.20.0

### Steps to reproduce:
1. Create a ```metrics.csv``` file with the following information in the ```/path/to/``` folder.
```
version=1.0
file created: 2021-10-08T12:34:18+10:00
timestamp,type,name,status
2020-11-23T08:19:27+10:00,Reader,R002,1
2020-11-04T13:23:04+10:00,Reader,R031,0
2020-11-04T13:29:47+10:00,Coordinator,C001,1
```

### Expected behaviour:

The expected behaviour would be that the parser would skip the first two lines and parse the rest of the file as normal.

### Actual behaviour:

The first two metadata lines are not ignored and it results in an error while reading the file.

### LINKED ISSUE #9903: inputs.tail does not support csv_skip_rows>0 and csv_header_row_count>=1
I have noticed that the ```inputs.tail``` does not allow support for ```csv_skip_rows>0``` and ```csv_header_row_count>=1```.
This is an issue that was [raised ](https://github.com/influxdata/telegraf/issues/9898) and [fixed](https://github.com/influxdata/telegraf/pull/9865) for ```inputs.directory_monitor```.

At this stage, I could like help from the community to indicate if it would be helpful to have the same fix apply for ```inputs.tail```.
My reservation not to make this change is that we have other input types like ```inputs.file``` that could be used as an alternative. Also, the ```inputs.tail``` is commonly designed for tailing log files. In the case of telling a CSV file, the headers should already be provided.

### Relevant telegraf.conf:
```toml
[[inputs.tail]]
  files = ["/path/to/metrics.csv"]
  from_beginning = true
  file_tag = "filename"
  data_format = "csv"
  csv_header_row_count = 1
  csv_column_names = []
  csv_column_types = []
  csv_skip_rows = 2
  csv_skip_columns = 0
  csv_delimiter = ","
  csv_comment = ""
  csv_trim_space = false
  csv_tag_columns = []
  csv_measurement_column = ""
  csv_timestamp_column = ""
  csv_timestamp_format = ""
  csv_timezone = ""
  csv_skip_values = []
```

### System info:

Telegraf 1.20.0

1. Create a ```metrics.csv``` file with the following information in the ```/path/to/``` folder.
```
version=1.0
file created: 2021-10-08T12:34:18+10:00
timestamp,type,name,status
2020-11-23T08:19:27+10:00,Reader,R002,1
2020-11-04T13:23:04+10:00,Reader,R031,0
2020-11-04T13:29:47+10:00,Coordinator,C001,1
```
### Expected behaviour:

The expected behaviour would be that the parser would skip the first two lines and parse the rest of the file as normal.

### Actual behaviour:

The first two metadata lines are not ignored and it results in an error while reading the file.

### PR DESCRIPTION
**Pull request by etycomputer**
### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #9898
resolves #9903
resolves #5338

🐛 Fixed an issue with directory monitor input plugin when data format is CSV and csv_skip_rows>0 and csv_header_row_count>=1
✅ Added new test cases that cover these scenarios

### CODE REVIEW

**Comment by etycomputer** [comment]
!signed-cla

**Comment by etycomputer** [comment]
!signed-cla

**Comment by etycomputer** [comment]
For this PR, did I have to create an issue first?

**Comment by powersj** [comment]
It would be good to create an issue describing a bit more of what you are fixing, expected vs actual results, etc :) Then you can update the PR to reference that issue #.

Also, note that the lint tests failed, so you will want to clean those up.

Thanks!

**Comment by etycomputer** [comment]
Hi @srebhan, can you please, let me know if you still think I need to make any changes.
Thank

**Comment by etycomputer** [comment]
@srebhan, @powersj, and @Hipska

Hi,

I have made the requested changes to the CSV Parser.
The change is merging all the functionality between CSV.Parse() and CSV.ParseLine so that you can call both functions and they will perform the same action while keeping the state of the CSV parse updated between calls.
This allows the input plugins to call either of the functions and pass the while file or one row at a time.

Hope the fix is as expected.

Kind regards,
Ehsan

**Comment by etycomputer** [comment]
Hi Joshua @powersj,
Could you have another look at this PR, please.
Cheers,
Ehsan

**Comment by etycomputer** [comment]
> Yeah, it would need to be fixed in the parser, otherwise every plugin using this approach would need to be adapted.

Hi Thomas @Hipska,

I have made the requested changes in the csv parse and added tests to parser and both inputs.

Could you have a look and let me know if you have happy with the changes.

Thanks

**Comment by etycomputer** [comment]
> Hey @etycomputer, thanks for the PR! I don't think this is the right place to fix this. Instead you should change the `CSV` parser's [expectation of getting all rows at once](https://github.com/influxdata/telegraf/blob/4c417976a34b25a17ce2b69e140fa5c5d8046621/plugins/parsers/csv/parser.go#L101) by decrementing the `SkipRows` by the rows you already skipped and check if there are remaining ones... This will then also fix `tail`.

Hi Sven @srebhan,

As requested I have made the changes to the csv parser and decremented the SkipRows and SkipHeaderCount to meet the requirements. I have also added multiple tests to cover the scenarios in the csv parser and both input plug-ins.

Hope the changes meet your requirements. Let me know if there is any other changes you need.

Kind regards,
Ehsan

File: plugins/parsers/csv/parser_test.go [hunk 1]
```diff
@@ -332,17 +332,40 @@ func TestSkipRows(t *testing.T) {
 			TimeFunc:          DefaultTime,
 		},
 	)
-	testCSV := `garbage nonsense
+	testCSV1 := `garbage nonsense
```
Comment (srebhan) [inline plugins/parsers/csv/parser_test.go:335]: Why is this necessary?

File: plugins/parsers/csv/parser_test.go [hunk 2]
```diff
@@ -332,17 +332,40 @@ func TestSkipRows(t *testing.T) {
...
 	expectedFields := map[string]interface{}{
 		"line2": int64(80),
 	}
-	metrics, err := p.Parse([]byte(testCSV))
-	require.NoError(t, err)
-	require.Equal(t, "test_name2", metrics[0].Name())
-	require.Equal(t, expectedFields, metrics[0].Fields())
+	metrics0, err1 := p1.Parse([]byte(testCSV1))
+	require.NoError(t, err1)
+	require.Equal(t, "test_name2", metrics0[0].Name())
```
Comment (srebhan) [inline plugins/parsers/csv/parser_test.go:344]: Please don't add random suffices. Keep tests as they are and add new ones. This way we can be sure that the code is still working as before.

File: plugins/parsers/csv/parser_test.go [hunk 3]
```diff
@@ -375,15 +398,52 @@ func TestSkipColumnsWithHeader(t *testing.T) {
 	)
 	require.NoError(t, err)
 	testCSV := `col,col,col
-	1,2,3
-	trash,80,test_name`
+1,2,3
+trash,80,test_name`
```
Comment (srebhan) [inline plugins/parsers/csv/parser_test.go:402]: Why is this necessary?

**Comment by etycomputer** [comment]
Hi @srebhan,

I am getting `typecheck  undeclared name: xxxx`.
I tried rebasing with Master, but that did not make a difference can you advise on this?

Kind regards,
Ehsan

**Comment by etycomputer** [comment]
Hi @sspaink,

can you look at this job?
Made more changes and rebased with Master after your "chore: only check new issues with Go linter (#10054)" change.
This fixed one of the Lint checks now It is failing on another one.

Kind regards,
Ehsan

**Comment by sspaink** [comment]
@etycomputer sorry for the problems with the linter, looks like this time it did find an error: https://github.com/influxdata/telegraf/pull/9865/files#diff-d6a8a85e74d13d871ed75dec8bd88f874b3e370f1b7df0262309c7eca5c237b7R74 the error returned by `NewParser` isn't being checked.

**Comment by etycomputer** [comment]
> @etycomputer sorry for the problems with the linter, looks like this time it did find an error: https://github.com/influxdata/telegraf/pull/9865/files#diff-d6a8a85e74d13d871ed75dec8bd88f874b3e370f1b7df0262309c7eca5c237b7R74 the error returned by `NewParser` isn't being checked.

Thanks for pointing that out @sspaink. I clicked on the Details and could not figure out what the error was. I should have looked at the diff too. 

Cheers,
Ehsan

**Comment by etycomputer** [comment]
Hey @sspaink, 

Sorry to bother you one more time, I am getting another failing test for a part of the code that I have not changed and it is only failing for Go 1.17.
Can you advise in this regard?

Thanks.

**Comment by sspaink** [comment]
@etycomputer no worries, looks like it was a flaky test! I re-triggered the job and it passed, we will look into getting this test fixed.

File: plugins/inputs/directory_monitor/directory_monitor.go [hunk 4]
```diff
@@ -285,24 +282,17 @@ func (monitor *DirectoryMonitor) parseFile(parser parsers.Parser, reader io.Read
...
-			return parser.Parse(line)
+		m, err := parser.Parse(line)
+		if err == io.EOF {
+			return []telegraf.Metric{}, nil
 		}
-
-		m, err := parser.ParseLine(string(line))
 		if err != nil {
 			return nil, err
 		}
```
Comment (srebhan) [inline plugins/inputs/directory_monitor/directory_monitor.go:294]: Please fuse the error checks and use `errors.Is` to also handle wrapped errors.
```golang
		if err != nil {
			if errors.Is(err, io.EOF) {
				return []telegraf.Metric{}, nil
			}
			return nil, err
		}
```
Same for tail.

File: plugins/inputs/tail/tail.go [hunk 5]
```diff
@@ -378,13 +368,12 @@ func (t *Tail) receiver(parser parsers.Parser, tailer *tail.Tail) {
 			continue
 		}
 
-		metrics, err := parseLine(parser, text, firstLine)
+		metrics, err := parseLine(parser, text)
```
Comment (srebhan) [inline plugins/inputs/tail/tail.go:371]: You should also check for `EOF` here, shouldn't you?

File: plugins/parsers/csv/parser.go [hunk 6]
```diff
@@ -96,22 +96,38 @@ func (p *Parser) compile(r io.Reader) *csv.Reader {
...
+// ParseLine does not use any information in header and assumes DataColumns is set
+// it will also not skip any rows
+func (p *Parser) ParseLine(line string) (telegraf.Metric, error) {
+	r := bytes.NewReader([]byte(line))
+	metrics, err := parseCSV(p, r)
+	if len(metrics) > 0 {
+		// only return the first metric as there should be only one
+		return metrics[0], err
+	}
+	return nil, err
```
Comment (srebhan) [inline plugins/parsers/csv/parser.go:111]: Can you please change that to check there is only _exactly_ one metric?
```suggestion
	if err != nil {
		return nil, err
	}
	if len(metrics) != 1 {
		return nil, fmt.Errorf("expected 1 metric found %d", len(metrics))
	}
	return metrics[0], nil
```

File: plugins/parsers/csv/parser.go [hunk 7]
```diff
@@ -96,24 +96,43 @@ func (p *Parser) compile(r io.Reader) *csv.Reader {
...
-	// if there is a header and we did not get DataColumns
+	// if there is a header, and we did not get DataColumns
 	// set DataColumns to names extracted from the header
 	// we always reread the header to avoid side effects
 	// in cases where multiple files with different
 	// headers are read
 	if !p.gotColumnNames {
-		headerNames := make([]string, 0)
-		for i := 0; i < p.HeaderRowCount; i++ {
+		for p.HeaderRowCount > 0 {
```
[the remark this answers is not in the document]
Comment (srebhan) [reply plugins/parsers/csv/parser.go:130]: Any reason you don't fuse the `if` and `else` path as suggested above?

File: plugins/parsers/csv/parser_test.go (hunk 3 above)
Comment (srebhan) [reply plugins/parsers/csv/parser_test.go:429]: Can you please comment on why the reformatting is necessary?

**Review by srebhan — COMMENTED** [review]
Very nice update @etycomputer! I have some more comments and two comments left from the last review. The first one is the formatting of the test case. I try to understand if this is a necessary change. The second being folding the `else` case when there are column-names into the `if`. I think this will make the code more maintain and understandable. Is there a reason not to do it?

**Comment by etycomputer** [comment]
Hi @srebhan, 

Thanks for looking at my code on such short notice.
I have applied the requested changes and added more explanation and my reasoning.

Regarding the last test format change (removed the spaces), I think the programmer that created the test initially did not really have the intention of adding the spaces. I think they thought it would look better and since it did not affect the result of the test it got missed. 
I think the spaces should be removed. 

Kind regards,
Ehsan

File: plugins/inputs/directory_monitor/directory_monitor.go [hunk 8]
```diff
@@ -285,24 +282,17 @@ func (monitor *DirectoryMonitor) parseFile(parser parsers.Parser, reader io.Read
...
-		// The CSV parser parses headers in Parse and skips them in ParseLine.
-		if firstLine {
-			return parser.Parse(line)
-		}
-
-		m, err := parser.ParseLine(string(line))
+		m, err := parser.Parse(line)
 		if err != nil {
+			if errors.Is(err, io.EOF) {
+				return []telegraf.Metric{}, nil
```
Comment (srebhan) [inline plugins/inputs/directory_monitor/directory_monitor.go:291]: Maybe doing this would be even better
```suggestion
				return nil, nil
```

File: plugins/parsers/csv/parser.go [hunk 9]
```diff
@@ -96,49 +96,68 @@ func (p *Parser) compile(r io.Reader) *csv.Reader {
...
+// it will also not skip any rows
+func (p *Parser) ParseLine(line string) (telegraf.Metric, error) {
+	r := bytes.NewReader([]byte(line))
+	metrics, err := parseCSV(p, r)
+	if err != nil {
+		return nil, err
+	}
+	if len(metrics) == 1 {
+		return metrics[0], nil
+	} else if len(metrics) > 1 {
```
Comment (srebhan) [inline plugins/parsers/csv/parser.go:112]: Sorry my bad, the linter will probably complain on this, just do
```suggestion
	}
	if len(metrics) > 1 {
```

File: plugins/parsers/csv/parser_test.go (hunk 3 above)
Comment (srebhan) [reply plugins/parsers/csv/parser_test.go:429]: I'm ok with removing them but they might be used to test the trim-space feature... If you don't mind I would feel better to keep them...

**Review by srebhan — COMMENTED** [review]
Nice, only some very minor things left. Please keep the spaces in the test-case as they also test for the 'trim-space' path I think.

**Comment by etycomputer** [comment]
Hi @srebhan,

I have applied the minor changes.
Also, added a new test for the multi-metric error that we introduced.
Regarding the space removal, I strongly think that this should be removed. To make sure that the trim space functionality is still working as is as expected for multi header scenarios, I have added a new test. 

Hope that is acceptable to you. If you still think that adding the spaces is needed I am happy to add them back in.
I don't think the extra space is going to be a game-changer, and I really like my changes to get into master as soon as possible.
I would like to next work on a new feature related to the CVS parser.

Kind regards,
Ehsan

**Review by Hipska — APPROVED** [review]

**Comment by etycomputer** [comment]
How can we close issue #5338 
https://github.com/influxdata/telegraf/issues/5338
And issue #8989 
https://github.com/influxdata/telegraf/issues/9898
And issue #9903 
https://github.com/influxdata/telegraf/issues/9903
With this PR?

**Comment by Hipska** [comment]
Add them in your description as you did for #9898. One per line.

More info: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by etycomputer** [comment]
Hey @Hipska,

How are you going?
Thanks, I will add them and try and see if I can find any other ones.

So, do you think this is ready to be merged or do we need to get feedback from anyone else like @srebhan?

Also, do I need to update the CHANGElOG or you is it done automatically?

Cheers,
Ehsan

**Review by srebhan — APPROVED** [review]
LGTM. That's an amazing PR @etycomputer. I like the test solution adding another test. Thank you very much for your work!

**Comment by srebhan** [comment]
> So, do you think this is ready to be merged or do we need to get feedback from anyone else like @srebhan?

After my approval (which you just got) I set the "ready for final review" tag. With this someone from the InfluxData telegraf team will give the PR another review and, if he/she does not have any comment, merge it.

> Also, do I need to update the CHANGELOG or you is it done automatically?

You don't have to care for this, it's done (semi)automatically IIRC.

**Comment by etycomputer** [comment]
Thank you very much @srebhan you were also have me good comments and pointed out excellent alternative solution. I really enjoyed working with you on this PR.

Kind regarding,
Ehsan

**Comment by etycomputer** [comment]
Hey @powersj, 

Are you able to do the final review and push my changes into master, please?

Cheers,
Ehsan

**Review by srebhan — APPROVED** [review]

**Comment by srebhan** [comment]
@etycomputer please be patient waiting for the final review. Rest assured that your PR is on the list and will not be forgotten. As the change is touching a tricky part of telegraf, it might be possible your PR will only be included in the next version (1.21).

**Comment by etycomputer** [comment]
Hey @srebhan,

Sorry, the reason I wanted this change to go in was because my metadata feature that I wanted to add depends on these changes.

I have already based my new PR #10083 off this branch. So most probably they will all go in at the same time.

Is there a timeline when you are expecting to go to the next version?

It would be awesome if you could also have a look at #10083 and let me know what you think.

I have just started programming in Go and I really like it so far.

I would be happy to work on some of the smaller jobs if you come across any please let me know.

Kind regards,
Ehsan

File: plugins/parsers/csv/parser_test.go (hunk 3 above)
Comment (reimda) [reply plugins/parsers/csv/parser_test.go:445]: Let's not remove the space. I don't see a reason to remove it.

File: plugins/parsers/csv/parser_test.go [hunk 10]
```diff
@@ -343,6 +385,30 @@ hello,80,test_name2`
...
+	require.Error(t, io.EOF, err)
+	require.Error(t, err)
+	require.Nil(t, metrics)
+	m, err := p.ParseLine(testCSVRows[1])
+	require.NoError(t, err)
+	require.Nil(t, m)
+	m, err = p.ParseLine(testCSVRows[2])
+	require.NoError(t, err)
+	require.Equal(t, "test_name2", m.Name())
+	require.Equal(t, expectedFields, m.Fields())
```
Comment (reimda) [inline plugins/parsers/csv/parser_test.go:411]: We need to check that the tag "line1=hello" is in the metric.

File: plugins/parsers/csv/parser_test.go [hunk 11]
```diff
@@ -59,9 +60,33 @@ func TestHeaderOverride(t *testing.T) {
...
+	p, err = NewParser(
+		&Config{
+			HeaderRowCount:    1,
+			ColumnNames:       []string{"first", "second", "third"},
+			MeasurementColumn: "third",
+			TimeFunc:          DefaultTime,
+		},
+	)
+	require.NoError(t, err)
+	metrics, err = p.Parse([]byte(testCSVRows[0]))
```
Comment (reimda) [inline plugins/parsers/csv/parser_test.go:83]: Do you mean to call ParseLine instead of Parse here?

**Comment by etycomputer** [comment]
Hey @reimda,

Thanks for reviewing my work.
I have added the extra test you requested.

Regarding your other comment, I have chosen to use the combination to cover scenarios that someone may use the parse.Parse() for its first line and the parse.ParseLine() for any line after that. This was the approach that is currently is being used on the master branch but going forward I have removed the need to differentiate between the initial line (header column) and other lines (records).

Let me know if you like to change the p.parse() to p.ParseLine().

Kind regards,
Ehsan

**Comment by srebhan** [comment]
> I would be happy to work on some of the smaller jobs if you come across any please let me know.

@etycomputer, you might want to go through [`help wanted` PRs](https://github.com/influxdata/telegraf/pulls?q=is%3Aopen+is%3Apr+label%3A%22help+wanted%22) or check the issues (best would be [bug reports](https://github.com/influxdata/telegraf/issues?q=is%3Aopen+is%3Aissue+label%3Abug)) if you can find anything you like. Furthermore, you might want to join our Slack channel #telegraf-dev and/or #telegraf. Happy to see you there. :-)

**Review by reimda — APPROVED** [review]

**Comment by etycomputer** [comment]
Thank you All for helping me with this PR.

**Comment by srebhan** [comment]
@etycomputer thank you for fixing this!
