### PR TITLE
Fixed #3162 fix parsing of SHM remotes

### LINKED ISSUE #3162: NTP plugin incorrectly parses shared memory remotes
### Relevant telegraf.conf:

```
[[inputs.ntpq]]
   dns_lookup = false
```

### System info:

- Telegraf >= 1.3.5;
- Linux (version not relevant);
- latest [NTPsec](https://www.ntpsec.org/).

### Steps to reproduce:

1. use NTPsec instead of NTP as time daemon;
2. use the shared memory driver to use a local GPS+PPS reference;
3. observe that the output of `ntpq` is using aliases like `SHM(0)` & `SHM(1)` for the GPS/PPS remotes.

### Expected behaviour:

The measurements of both the `SHM(0)` and `SHM(1)` remotes to appear in Influx for my host.

### Actual behaviour:

Only the measurements of a (non-existing) remote `SHM` appears for my host. 

### Additional info:

The issue was introduced with the fix for #2386.

The output of ntpq:

```
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*SHM(1)          .PPS.            0 l    8   16  377    0.000    0.001   0.000
xSHM(0)          .GPS.            0 l    2    2  377    0.000  -116.97   1.414
```

### PR DESCRIPTION
**Pull request by jawi**
- added test cases for SHM remotes;
- slightly changed the fix for #2386 to improve and fix the parsing of SHM remotes.

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/);
- [ ] Associated README.md updated;
- [x] Has appropriate unit tests.

### CODE REVIEW

File: plugins/inputs/ntpq/ntpq_test.go [hunk 1]
```diff
@@ -229,22 +229,6 @@ func TestBadWhenNTPQ(t *testing.T) {
...
-		"jitter": float64(17.462),
-	}
-	tags := map[string]string{
-		"remote":       "uschi5-ntp-002.",
-		"state_prefix": "*",
-		"refid":        "10.177.80.46",
-		"stratum":      "2",
-		"type":         "u",
-	}
-	acc.AssertContainsTaggedFields(t, "ntpq", fields, tags)
```
Comment (danielnelson) [inline plugins/inputs/ntpq/ntpq_test.go]: Why is this code removed?

Comment (jawi) [reply plugins/inputs/ntpq/ntpq_test.go]: A combination of fat fingers and a lack of caffeine. Should not be removed at all. I've reverted that change...
