### PR TITLE
fix(inputs.snmp): snmp UseUnconnectedUDPSocket when using udp

### LINKED ISSUE #9286: Timeout with inputs.snmp polling squid-cache
### Relevant telegraf.conf:

```toml
[[inputs.snmp]]
  interval = "30s"
  agents = [ "udp://192.168.3.1:161" ]
  version = 2
  community = "public"
  name = "squid"

  [[inputs.snmp.field]]
    name = "cacheSoftware"
    oid = "1.3.6.1.4.1.3495.1.2.2.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "cacheVersionId"
    oid = "1.3.6.1.4.1.3495.1.2.3.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "cacheProtoClientHttpRequests"
    oid = "1.3.6.1.4.1.3495.1.3.2.1.1.0"
```

### System info:

Running Ubuntu in telegraf:latest docker image:

> I have no name!@TelegrafHost:/$ telegraf --version
Telegraf 1.18.2 (git: HEAD a6143722)

### Docker

```yaml
version : "3"

services:
  telegraf:
    image: telegraf
    hostname: TelegrafHost
    user: 201:201
    command: --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d
    ports:
      - 6514:6514/udp
      - 162:6162/udp
    volumes:
      - /home/docker/etc/telegraf:/etc/telegraf:ro
      - /proc:/host/proc:ro
      - /home/docker/.snmp/mibs:/usr/share/snmp/mibs:ro
    networks:
       influxdatanet:
```
### Steps to reproduce:

1. configure telegraf docker image to pull snmp statistics from squid-cache

### Expected behavior:

From the CLI inside the docker container snmpget works as expected.

> I have no name!@TelegrafHost:/$ snmpget -v2c -c public 192.168.3.1 1.3.6.1.4.1.3495.1.2.2.0
iso.3.6.1.4.1.3495.1.2.2.0 = STRING: "squid"

### Actual behavior:

docker logs show timeout errors on this specific agent
> 2021-05-20T14:28:10Z E! [inputs.snmp] Error in plugin: agent udp://192.168.3.1:161: performing get on field cacheSoftware: request timeout (after 3 retries)

(lot's of these)

### Additional info:
Other input.snmp agents work, just this specific one time's out.

a tcpdump gives this when telegraf polls:

> 16:31:35.005000 IP 172.18.0.5.35773 > 192.168.3.1.161:  GetRequest(31)  .1.3.6.1.4.1.3495.1.2.2.0
16:31:35.005274 IP 172.18.0.1.161 > 172.18.0.5.35773:  GetResponse(40)  .1.3.6.1.4.1.3495.1.2.2.0="squid"
16:31:35.005313 IP 172.18.0.5 > 172.18.0.1: ICMP 172.18.0.5 udp port 35773 unreachable, length 95 

but an snmpget from the CLI does not give the ICMP error. (telegraf stops listening at the port before the answer is received?) 

test run output:

> I have no name!@TelegrafHost:/$ telegraf --test --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d
<...>
2021-05-20T14:09:28Z E! [inputs.snmp] Error in plugin: agent udp://192.168.3.1:161: performing get on field cacheSoftware: request timeout (after 3 retries)
I have no name!@TelegrafHost:/$

### PR DESCRIPTION
**Pull request by MyaLongmire**
### Required for all PRs:

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #9286 maybe #10554

When using udp in snmp  set gosnmp's UseUnconnectedUDPSocket to true

### CODE REVIEW

File: plugins/inputs/snmp_trap/snmp_trap.go [hunk 1]
```diff
@@ -116,6 +117,9 @@ func (s *SnmpTrap) Start(acc telegraf.Accumulator) error {
 	s.listener = gosnmp.NewTrapListener()
 	s.listener.OnNewTrap = makeTrapHandler(s)
 	s.listener.Params = gosnmp.Default
+	s.udp = &gosnmp.GoSNMP{
```
Comment (Hipska) [inline plugins/inputs/snmp_trap/snmp_trap.go:120]: s.udp is not used somewhere?

File: plugins/inputs/snmp/snmp.go [hunk 2]
```diff
@@ -620,6 +620,9 @@ func (s *Snmp) getConnection(idx int) (snmpConnection, error) {
 	var err error
 	var gs snmp.GosnmpWrapper
 	gs, err = snmp.NewWrapper(s.ClientConfig)
+	if strings.ContainsAny(agent, "udp") {
+		gs.UseUnconnectedUDPSocket = true
+	}
```
Comment (Hipska) [inline plugins/inputs/snmp/snmp.go:625]: Is this `if` needed? Couldn't we set the value anyway?

Comment (MyaLongmire) [reply plugins/inputs/snmp/snmp.go:625]: I would rather be explicit about setting this option so it is only set when using udp to decrease confusion for possibly affecting TCP down the road. Without sending the agent to the NewWrapper there is no way to check if the user is using udp or TCP.

File: plugins/inputs/snmp_trap/snmp_trap.go (hunk 1 above)
Comment (MyaLongmire) [reply plugins/inputs/snmp_trap/snmp_trap.go:120]: This section is setting GoSNMP options.

Comment (Hipska) [reply plugins/inputs/snmp_trap/snmp_trap.go:120]: Are you sure? It seems like its never reverenced anymore in the code..

Comment (MyaLongmire) [reply plugins/inputs/snmp_trap/snmp_trap.go:120]: since snmp_trap is an event-based input plugin, start is called by telegraf during initialization and never called again.

File: plugins/inputs/snmp/snmp.go (hunk 2 above)
Comment (Hipska) [reply plugins/inputs/snmp/snmp.go:625]: I think we had such a discussion already earlier. But I still can't see how a UDP setting might ever affect anything that has to do with TCP? If that option would have named something like `UseUnconnectedSocket`, then I would agree and leave it like it is, but now it specifically mentions in the name it is only relevant for UDP..

Comment (MyaLongmire) [reply plugins/inputs/snmp/snmp.go:625]: We have had this discussion. I want to be explicit when setting this option for easier maintenance down the road.

File: plugins/inputs/snmp_trap/snmp_trap.go (hunk 1 above)
Comment (MyaLongmire) [reply plugins/inputs/snmp_trap/snmp_trap.go:120]: In telegraf no, but in GoSNMP yes.

Comment (Hipska) [reply plugins/inputs/snmp_trap/snmp_trap.go]: So did you actually check if the setting was set?

Actually, I don't think it even makes sense with snmp traps, because you are not receiving a packet that came as response to any request..

File: plugins/inputs/snmp/snmp.go (hunk 2 above)
Comment (Hipska) [reply plugins/inputs/snmp/snmp.go:625]: Ok, I agree. But I would place this inside the `GosnmpWrapper` after this:
https://github.com/influxdata/telegraf/blob/2ca5cfed94cef0b987ce487600c631e8583aa05e/internal/snmp/wrapper.go#L145-L156

Comment (Hipska) [reply plugins/inputs/snmp/snmp.go:625]: What do you think Mya?

Comment (MyaLongmire) [reply plugins/inputs/snmp/snmp.go]: moved

**Comment by OliverTUBAF** [comment]
Did this change make it into 1.22 release?

It seem like "no" to me, just want to make sure ...

**Comment by Hipska** [comment]
No, since it hasn't been merged yet..

**Comment by svestenik** [comment]
Hm, tried to download the file, but getting ERROR 404: Not found...

**Comment by Hipska** [comment]
!retry-checks

File: plugins/inputs/snmp_trap/snmp_trap.go (hunk 1 above)
Comment (Hipska) [reply plugins/inputs/snmp_trap/snmp_trap.go]: @MyaLongmire ?

**Comment by Hipska** [comment]
!retry-checks

**Comment by svestenik** [comment]
Installed the branch build from rpm.
Didn't go too well... My system load after starting Telegraf went to 56.07 :)
And nothing gets written into InfluxDB. Centos8 Stream, InfluxDB version 1.8.10.

When I check telegraf log file, I see it doing nothing:

tail /var/log/telegraf/telegraf.log
2022-04-26T09:48:27Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"", Flush Interval:10s
2022-04-26T09:48:27Z D! [agent] Initializing plugins
2022-04-26T09:51:41Z I! Starting Telegraf 1.22.0-a1db1d8d
2022-04-26T09:51:41Z I! Loaded inputs: cpu disk diskio exec (2x) kernel mem ping (2x) processes snmp (27x) sqlserver swap system x509_cert
2022-04-26T09:51:41Z I! Loaded aggregators:
2022-04-26T09:51:41Z I! Loaded processors: converter (15x) regex (11x) rename (7x) starlark strings (12x)
2022-04-26T09:51:41Z I! Loaded outputs: influxdb
2022-04-26T09:51:41Z I! Tags enabled:
2022-04-26T09:51:41Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"", Flush Interval:10s
2022-04-26T09:51:41Z D! [agent] Initializing plugins
and just hangs there instead of progressing to input processing.

**Review by srebhan — APPROVED** [review]
Looks good to me. Thanks @MyaLongmire!

**Comment by srebhan** [comment]
Hey @MyaLongmire, can you please wrap this change with an option which keeps the old way by default?

**Comment by MyaLongmire** [comment]
@srebhan Like a config option?

**Comment by srebhan** [comment]
@MyaLongmire exactly.

File: plugins/inputs/snmp_trap/snmp_trap.go (hunk 1 above)
Comment (Hipska) [reply plugins/inputs/snmp_trap/snmp_trap.go]: @MyaLongmire ?

Comment (MyaLongmire) [reply plugins/inputs/snmp_trap/snmp_trap.go]: The setting is set and since traps use udp i bet it also needs the setting

Comment (Hipska) [reply plugins/inputs/snmp_trap/snmp_trap.go]: Please enlighten me how it would have any effect in traps?

Comment (MyaLongmire) [reply plugins/inputs/snmp_trap/snmp_trap.go]: I'm sorry @Hipska, I misinterpreted this [comment](https://github.com/influxdata/telegraf/issues/11278#issuecomment-1178203096). I have since removed the option for traps. Thank you for your continued patience as I learn snmp

**Review by Hipska — APPROVED** [review]

File: plugins/inputs/snmp/snmp.go [hunk 3]
```diff
@@ -761,12 +761,13 @@ func init() {
...
 			Name: "snmp",
 			ClientConfig: snmp.ClientConfig{
-				Retries:        3,
-				MaxRepetitions: 10,
-				Timeout:        config.Duration(5 * time.Second),
-				Version:        2,
-				Path:           []string{"/usr/share/snmp/mibs"},
-				Community:      "public",
+				Retries:                 3,
+				UseUnconnectedUDPSocket: false,
```
Comment (Hipska) [inline plugins/inputs/snmp/snmp.go:765]: I don't think this is needed if false is the default value anyway.

Comment (MyaLongmire) [reply plugins/inputs/snmp/snmp.go]: removed

File: plugins/inputs/snmp/README.md [hunk 4]
```diff
@@ -30,6 +30,12 @@ path onto the global path variable
   ## SNMP version; can be 1, 2, or 3.
   # version = 2
 
+  ## If set to true changes to be an unconnected UDP socket
+  ## This is used when network gear isn't smart enough to send SNMP
+  ## reponses from the address it recieved the request on. 
+  ## This opens a unconnected UDP socket and use sendto/recvfrom
```
Comment (reimda) [inline plugins/inputs/snmp/README.md:36]:
```suggestion
  ## Unconnected UDP socket
  ## When true, SNMP reponses are accepted from any address not just
  ## the requested address. This can be useful when gathering from
  ## redundant/failover systems.
```

File: internal/snmp/config.go [hunk 5]
```diff
@@ -9,7 +9,8 @@ type ClientConfig struct {
 	Timeout config.Duration `toml:"timeout"`
 	Retries int             `toml:"retries"`
 	// Values: 1, 2, 3
-	Version uint8 `toml:"version"`
+	Version                 uint8 `toml:"version"`
+	UseUnconnectedUDPSocket bool  `toml:"use_unconnected_udp_socket"`
```
Comment (reimda) [inline internal/snmp/config.go:13]: What do you think about leaving off the "use"? It makes the name longer but doesn't add anything. The other settings are nouns, so it doesn't fit to have this one be a verb phrase. The "use" came from gosnmp which doesn't have the same settings naming style.

```suggestion
	UnconnectedUDPSocket bool  `toml:"unconnected_udp_socket"`
```

File: plugins/inputs/snmp/README.md [hunk 6]
```diff
@@ -349,6 +355,10 @@ needed:
 sudo tcpdump -s 0 -i eth0 -w telegraf-snmp.pcap host 127.0.0.1 and port 161
 ```
 
+## Metrics
+
+The field and tags will depend on the table and fields configured
```
Comment (reimda) [inline plugins/inputs/snmp/README.md:360]:
```suggestion
The field and tags will depend on the table and fields configured.
```

**Review by reimda — CHANGES_REQUESTED** [review]

File: internal/snmp/config.go (hunk 5 above)
Comment (MyaLongmire) [reply internal/snmp/config.go:13]: I like the idea. I was just following goSNMP. I will implement it

**Review by reimda — APPROVED** [review]
Thanks! Looks good
