### PR TITLE
fix(outputs.sql): populate column cache for existing tables

### LINKED ISSUE #18192: SQL output plugin attempts to add existing columns when table_update_template is set
### Relevant telegraf.conf
```toml
[[outputs.sql]]
  driver = "clickhouse"
  data_source_name = "clickhouse://..."
  table_update_template = "ALTER TABLE {TABLE} ADD COLUMN {COLUMN}"
  
  [outputs.sql.convert]
    conversion_style = "literal"
    integer = "Int64"
    text = "String"
    timestamp = "DateTime"
```

### System info
Telegraf version: master branch
Database: ClickHouse (also affects other databases)

### Steps to reproduce
1. Configure SQL output plugin with `table_update_template` set
2. Ensure tables already exist in the database with columns
3. Start Telegraf and write metrics to existing tables
4. Observe error: "column already exists" when plugin tries to add existing columns

### Expected behavior
Plugin should detect existing columns and only add new columns that don't exist.

### Actual behavior
Plugin attempts to add ALL columns (including existing ones) to the table, causing errors like:
```
creating column failed: code: 15, message: Cannot add column \`timestamp\`: column with this name already exists
```

### Additional info
The issue occurs because when \`tableExists()\` discovers an existing table, it creates an empty column cache but never populates it with actual columns from the database. This causes \`createColumn()\` to think no columns exist and attempts to add them all.

### PR DESCRIPTION
**Pull request by ishaankalra**
## Summary
  Fixes an issue where the SQL output plugin attempts to add existing columns to tables when `table_update_template` is configured.

  **Problem:** When an existing table is discovered, the column cache (`p.tables[tablename]`) was initialized as an empty map for performance optimization but never
  populated with actual column names. This caused the plugin to believe the table had zero columns and attempt to add ALL columns when writing metrics, resulting in
  "column already exists" errors.

  **Solution:** Populate the column cache immediately when `tableExists()` discovers an existing table and `table_update_template` is set. This ensures the plugin
  knows which columns exist before attempting schema updates.

  **Impact:**
  - Maintains existing performance optimization (cache populated only once)
  - Enables automatic schema updates to work correctly with pre-existing tables
  - Affects ClickHouse and all other database drivers

  ## Checklist

  - [x] AI generated code used in this PR follows the [InfluxData Policy on AI-Generated Code Contributions][policy]

  [policy]: https://www.influxdata.com/ai-generated-code-contributions-policy

  ## Related issues

  resolves #18192

### CODE REVIEW

**Comment by ishaankalra** [comment]
!signed-cla

**Comment by skartikey** [comment]
@ishaankalra Thanks for the fix! The logic looks correct and follows the existing pattern used in `createTable()`.

  One suggestion: could you add an integration test that specifically covers the bug scenario? The existing `Test*UpdateSchemeIntegration` tests create tables via Telegraf, but this bug only manifests when the table pre-exists in the database before Telegraf connects.

  A test could:
  1. Pre-create a table with columns in the init script (e.g., add `metric_one` with `timestamp` and `tag_one` columns)
  2. Configure the plugin with `table_update_template`
  3. Write metrics to that pre-existing table
  4. Verify new columns are added without errors

  Example addition to testdata/clickhouse/initdb/init.sql:
```
  CREATE TABLE metric_one (
      timestamp DateTime,
      tag_one String
  ) ENGINE=MergeTree ORDER BY (timestamp);
```

  This would validate the fix and prevent regression.

**Comment by ishaankalra** [comment]
> @ishaankalra Thanks for the fix! The logic looks correct and follows the existing pattern used in `createTable()`.
> 
> One suggestion: could you add an integration test that specifically covers the bug scenario? The existing `Test*UpdateSchemeIntegration` tests create tables via Telegraf, but this bug only manifests when the table pre-exists in the database before Telegraf connects.
> 
> A test could:
> 
> 1. Pre-create a table with columns in the init script (e.g., add `metric_one` with `timestamp` and `tag_one` columns)
> 2. Configure the plugin with `table_update_template`
> 3. Write metrics to that pre-existing table
> 4. Verify new columns are added without errors
> 
> Example addition to testdata/clickhouse/initdb/init.sql:
> 
> ```
>   CREATE TABLE metric_one (
>       timestamp DateTime,
>       tag_one String
>   ) ENGINE=MergeTree ORDER BY (timestamp);
> ```
> 
> This would validate the fix and prevent regression.

Hi @skartikey, thanks for the review! I've added the integration test as requested.

The test (TestClickHousePreExistingTableIntegration) now:
1. ✅ Pre-creates a table with timestamp and tag_one columns in the init script
2. ✅ Configures table_update_template to enable automatic schema updates
3. ✅ Writes metrics with only existing columns first (validates no "already exists" errors)
4. ✅ Writes metrics with both existing and new columns (tag_two, int64_one, bool_one)
5. ✅ Verifies all columns exist using DESCRIBE TABLE

The test passes locally and validates that the column cache is properly populated for pre-existing tables, preventing duplicate column creation attempts.

File: plugins/outputs/sql/sql.go [hunk 1]
```diff
@@ -317,6 +317,13 @@ func (p *SQL) tableExists(tableName string) bool {
 	exists := err == nil
 	if _, found := p.tables[tableName]; exists && !found {
 		p.tables[tableName] = make(map[string]bool)
+		// If table_update_template is set, populate the column cache now
+		// so we know which columns already exist before trying to add new ones
+		if p.TableUpdateTemplate != "" {
+			if err := p.updateTableCache(tableName); err != nil {
+				p.Log.Errorf("Failed to populate column cache for existing table %s: %v", tableName, err)
```
Comment (skartikey) [inline plugins/outputs/sql/sql.go]: While log messages can use capitals, comparing with other Log.Errorf calls in this file, lowercase is more common. 

```suggestion
				p.Log.Errorf("failed to populate column cache for existing table %s: %v", tableName, err)
```

**Comment by ishaankalra** [comment]
> Just one minor comment.

@skartikey I have committed your suggestion.
