### PR TITLE
snmp ip/mac addr conversion & oid index suffix support

### LINKED ISSUE #1729: SNMP plugin mapping
I have started using the new Telegraf SNMP plugin, and so far working really well but I have hit an issue that I am trying to either work around or see if could get a fix for?

I am using the mib cbgpPeer2Table to get BGP session information from a Cisco router.  Most of the stats are collected fine, but the number of prefixes for each peer is kept in a seleparate table with a suffix on the mapping.

For example if I snmpwalk cbgpPeer2RemoteIdentifier I see:

```
SNMPv2-SMI::enterprises.9.9.187.1.2.5.1.12.1.4.192.168.0.1 = IpAddress: 119.168.0.1
SNMPv2-SMI::enterprises.9.9.187.1.2.5.1.12.1.4.192.168.0.2 = IpAddress: 119.168.0.2
SNMPv2-SMI::enterprises.9.9.187.1.2.5.1.12.1.4.192.168.0.4 = IpAddress: 119.168.0.4
```

If I then fetch cbgpPeer2State I get:

```
SNMPv2-SMI::enterprises.9.9.187.1.2.5.1.3.1.4.192.168.0.1 = INTEGER: 6
SNMPv2-SMI::enterprises.9.9.187.1.2.5.1.3.1.4.192.168.0.2 = INTEGER: 6
SNMPv2-SMI::enterprises.9.9.187.1.2.5.1.3.1.4.192.168.0.4 = INTEGER: 6
```

To collect this I use the following telegraf config works and it works as expected:

```toml
[[inputs.snmp.table]]
 name = "BGP"
 inherit_tags = [ "hostname" ]
   [[inputs.snmp.table.field]]
     name = "remoteAS"
     oid = ".1.3.6.1.4.1.9.9.187.1.2.5.1.11"
     is_tag = true

   [[inputs.snmp.table.field]]
     name = "remoteID"
     oid = ".1.3.6.1.4.1.9.9.187.1.2.5.1.12"
     is_tag = true

   [[inputs.snmp.table.field]]
     name = "state"
     oid = ".1.3.6.1.4.1.9.9.187.1.2.5.1.3"
```

My problem occurs when I try to include data from cbgpPeer2AcceptedPrefixes. The results from an snmpwalk looks like:

```
SNMPv2-SMI::enterprises.9.9.187.1.2.8.1.1.1.4.192.168.0.1.1.1 = Counter32: 0
SNMPv2-SMI::enterprises.9.9.187.1.2.8.1.1.1.4.192.168.0.2.1.1 = Counter32: 15464
SNMPv2-SMI::enterprises.9.9.187.1.2.8.1.1.1.4.192.168.0.4.1.1 = Counter32: 11
```

As you can see there is a suffix of ".1.1" on these results, so telegraf is just ignoring the entries as they don't match any tag.

Is there some way to work around this, maybe applying either a "map" or somehow specify a suffix?

### LINKED ISSUE #1755: SNMP plugin IF-MIB::ifTable physical interface problem
## Bug report

Utilizing the new (and old) SNMP plugin for IF-MIB::ifTable there is an issue where the physaddress is being returned via SNMP correctly but Telegraf is turning it into characters before outputting it. 

### Relevant telegraf.conf:

```toml
[[inputs.snmp]]
  agents = [ "172.16.1.13" ]
  version = 2
  community = "public"
  interval = "10s"
  timeout = "10s"

  name = "pts_stats"
  [[inputs.snmp.field]]
    name = "hostname"
    oid = ".1.3.6.1.2.1.1.5.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "ifTable"
    oid = "IF-MIB::ifPhysAddress.1"
```

### System info:
ubuntu 16.04 desktop with Telegraf 1.0 and the new SNMP plugin

### telegraf output
interface_stats,agent_host=172.16.1.13,host=Dell210,hostname=unnamed ifTable="�>" 1473690400000000000

### tcpdump of SNMP response
10:33:00.000413 IP 172.16.3.13.50536 > 172.16.1.13.161:  GetRequest(28)  .1.3.6.1.2.1.1.5.0
10:33:00.043629 IP 172.16.1.13.161 > 172.16.3.13.50536:  GetResponse(51)  .1.3.6.1.2.1.1.5.0="development-server"
10:33:00.043877 IP 172.16.3.13.50536 > 172.16.1.13.161:  GetRequest(30)  .1.3.6.1.2.1.2.2.1.6.1
10:33:00.082439 IP 172.16.1.13.161 > 172.16.3.13.50536:  GetResponse(36)  .1.3.6.1.2.1.2.2.1.6.1=fa_16_3e_ee_85_8c

### PR DESCRIPTION
**Pull request by phemmer**
This adds 2 new features to the SNMP plugin:
1. Support for MAC address & IP address conversion. Both types of addresses, when returned as packed bytes, can be converted to human readable addresses.
2. Support for OID index suffixes. When joining multiple tables, sometimes the joined table has a slightly longer index as the table has a multiple records for each of the records in the origin table. The new `oid_index_suffix` allows stripping off the trailing part of the OID on the joined table so that the index will match.

closes #1755 
closes #1729 

### Required for all PRs:

- [X] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: plugins/inputs/snmp/snmp_mocks_generate.go [hunk 1]
```diff
@@ -0,0 +1,97 @@
+// +build generate
```
Comment (phemmer) [inline plugins/inputs/snmp/snmp_mocks_generate.go]: I built this generator to make management of the mocked commands easier. Having to manually add the command & output to the test file was becoming a PITA.

File: plugins/inputs/snmp/snmp_mocks_test.go [hunk 2]
```diff
@@ -0,0 +1,82 @@
+package snmp
```
Comment (phemmer) [inline plugins/inputs/snmp/snmp_mocks_test.go]: I split all the command mocking stuff out of `test_snmp.go` to keep the tests clean.

**Comment by phemmer** [comment]
@mattbakerau This should solve your use case (#1729). If you want to take a look at it, and/or try it out, any feedback would be great.

@mnctech This should also solve your use case (#1755). If you have any feedback, it would also be appreciated.

**Comment by phemmer** [comment]
Rebased
