### PR TITLE
Limit wait time for writes in mqtt output

### LINKED ISSUE #3697: Telegraf fails stop sending metrics - took longer to collect than collection interval
## Bug report
Telegraf seems to be choking after certain amount of time. I'm not using aggregators. Seems like there other issues resported on the same lines - https://github.com/influxdata/telegraf/issues/3629
### Relevant telegraf.conf:
[telegraf.txt](https://github.com/influxdata/telegraf/files/1643878/telegraf.txt)

### System info:
Telegraf v1.6.0~6e240567 (git: master 6e240567)
Using it on Centos 7

### Steps to reproduce:

1. service start telegraf
2. wait for some time (varies from system to system) for it reproduce.

### Expected behavior:
Telegraf publishing metrics to mqtt.
### Actual behavior:
Telegraf stops publishing metrics seemingly randomly, all input plugins start to fail with:
2018-01-18T16:10:00Z E! Error in plugin [inputs.mem]: took longer to collect than collection interval (10s)
2018-01-18T16:10:00Z E! Error in plugin [inputs.mysql]: took longer to collect than collection interval (10s)
2018-01-18T16:10:00Z E! Error in plugin [inputs.cpu]: took longer to collect than collection interval (10s)
2018-01-18T16:10:10Z E! Error in plugin [inputs.mysql]: took longer to collect than collection interval (10s)
2018-01-18T16:10:10Z E! Error in plugin [inputs.cpu]: took longer to collect than collection interval (10s)
2018-01-18T16:10:10Z E! Error in plugin [inputs.mem]: took longer to collect than collection interval (10s)
2018-01-18T16:10:20Z E! Error in plugin [inputs.mysql]: took longer to collect than collection interval (10s)
2018-01-18T16:10:20Z E! Error in plugin [inputs.cpu]: took longer to collect than collection interval (10s)
2018-01-18T16:10:20Z E! Error in plugin [inputs.mem]: took longer to collect than collection interval (10s)
2018-01-18T16:10:30Z E! Error in plugin [inputs.mysql]: took longer to collect than collection interval (10s)
2018-01-18T16:10:30Z E! Error in plugin [inputs.cpu]: took longer to collect than collection interval (10s)
2018-01-18T16:10:30Z E! Error in plugin [inputs.mem]: took longer to collect than collection interval (10s)
2018-01-18T16:10:40Z E! Error in plugin [inputs.mysql]: took longer to collect than collection interval (10s)
2018-01-18T16:10:40Z E! Error in plugin [inputs.cpu]: took longer to collect than collection interval (10s)
2018-01-18T16:10:40Z E! Error in plugin [inputs.mem]: took longer to collect than collection interval 

### Additional info:
[telegraf-dump.txt](https://github.com/influxdata/telegraf/files/1643888/telegraf-dump.txt)

### PR DESCRIPTION
**Pull request by danielnelson**
By limiting the amount of time we will wait for message to be sent, we avoid deadlock in the mqtt output.

closes #3697 

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

File: plugins/outputs/mqtt/mqtt.go [hunk 1]
```diff
@@ -25,6 +26,9 @@ var sampleConfig = `
   # username = "telegraf"
   # password = "metricsmetricsmetricsmetrics"
 
+  ## Timeout for write operations. default: 5s
+  # timeout = "5s"
```
Comment (danielnelson) [inline plugins/outputs/mqtt/mqtt.go]: This option already existed but was undocumented and unused.

**Comment by adityask2** [comment]
@danielnelson  Can we have this code checked in v1.5.2?
