### PR TITLE
fix(serializers.prometheus): Use legacy validation for metric name

### LINKED ISSUE #16550: Telegraf 1.33.2 unable to send windows metrics to Amazon Managed Prometheus
### Relevant telegraf.conf

```toml
[[inputs.mem]]
  fieldpass = ["used_percent"]

[[inputs.win_perf_counters]]
  UseWildcardsExpansion = true

  [[inputs.win_perf_counters.object]]
    ObjectName = "Processor"
    Instances = ["_Total"]
    Counters = ["% Idle Time", "% Interrupt Time", "% Privileged Time", "% Processor Time", "% User Time", "Interrupts/sec"]
    Measurement = "win.cpu"
    IncludeTotal = true

[[inputs.win_perf_counters.object]]
    ObjectName = "Network Interface"
    Counters = ["Bytes Received/sec", "Bytes Sent/sec", "Packets Outbound Discarded",
                "Packets Outbound Errors", "Packets Received Discarded", "Packets Received Errors",
                "Packets Received/sec", "Packets Sent/sec"]
    Instances = ["*"]
    Measurement = "win.net"
    IncludeTotal = true

[[outputs.http]]
  url = "<amp_url>"
  ## Data format to output.
  data_format = "prometheusremotewrite"
  ## AWS Configuration
  region = "<aws_region>"
  aws_service = "<aws_service>"
  access_key = "<aws_access_key>"
  secret_key = "<aws_secret_key>"

  [outputs.http.headers]
     Content-Type = "application/x-protobuf"
     Content-Encoding = "snappy"
     X-Prometheus-Remote-Write-Version = "0.1.0"
```

### Logs from Telegraf

```text
2025-02-24T20:06:34Z E! [agent] Error writing to outputs.http: when writing to [https://<amp_workspace>/api/v1/remote_write] received status code: 400. body: sample invalid metric name: "win.net_Bytes_Sent_persec"
2025-02-24T20:06:59Z E! [agent] Error writing to outputs.http: when writing to [https://<amp_workspace>/api/v1/remote_write] received status code: 400. body: sample invalid metric name: "win.net_Packets_Sent_persec"
```

### System info

1.33.2

### Docker

_No response_

### Steps to reproduce

1.Deploy telegraf 1.33.2 on windows node to collect windows host metrics and use http output plugin to send to amazon managed prometheus.
2. Notice AMP doesn't accept the incoming metrics.
3. Revert back to 1.33.1 and observe everything works as expected.
...

### Expected behavior

AMP should accept the incoming metrics. 

### Actual behavior

AMP doesn't accept the incoming metrics

### Additional info

Revert back to 1.33.1 and observe everything works as expected.

### PR DESCRIPTION
**Pull request by srebhan**
## Summary

With PR #16453  we bumped the prometheus package which in turn changed the validation scheme for metric-names and labels to only being UTF-8 conform. However, while changing the label validation scheme back to "legacy" the metric name validation was not. This PR fixes the metric name validation and reverts the check to "legacy". This PR is also relevant for the `prometheusremotewrite` serializer as it reuses the sanitization code.

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #16550

### CODE REVIEW

File: plugins/serializers/prometheusremotewrite/prometheusremotewrite.go [hunk 1]
```diff
@@ -46,10 +46,12 @@ func (s *Serializer) SerializeBatch(metrics []telegraf.Metric) ([]byte, error) {
 		var metrickey MetricKey
 		var promts prompb.TimeSeries
 		for _, field := range metric.FieldList() {
-			metricName := prometheus.MetricName(metric.Name(), field.Key, metric.Type())
-			metricName, ok := prometheus.SanitizeMetricName(metricName)
+			rawName := prometheus.MetricName(metric.Name(), field.Key, metric.Type())
+			fmt.Println("raw:", rawName)
+			metricName, ok := prometheus.SanitizeMetricName(rawName)
+			fmt.Println("sanitized:", metricName)
```
Comment (DStrand1) [inline plugins/serializers/prometheusremotewrite/prometheusremotewrite.go:52]: Could you remove these printlns?

**Review by DStrand1 — APPROVED** [review]
