### PR TITLE
fix: Rename KNXListener to knx_listener

### LINKED ISSUE #9709: Rename KNX listener plugin in config
KNX listener in [config](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/knx_listener#configuration) is currently `inputs.KNXListener` should be `inputs.knx_listener`. Our plugin names are written in snake case.

Should be changed for backwards capability.

### PR DESCRIPTION
**Pull request by srebhan**
### Required for all PRs:

- [X] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [X] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary) (e.g. feat: or fix:)

resolves #9709 

Rename `KNXListener` input plugin to `knx_listener` to follow the convention.

### CODE REVIEW

**Review by sjwang90 — APPROVED** [review]

File: plugins/inputs/knx_listener/knx_listener.go [hunk 1]
```diff
@@ -195,5 +195,5 @@ func (kl *KNXListener) listen() {
 }
 
 func init() {
-	inputs.Add("KNXListener", func() telegraf.Input { return &KNXListener{ServiceType: "tunnel"} })
```
Comment (reimda) [inline plugins/inputs/knx_listener/knx_listener.go:198]: knx_listener is the right name to use, but since we released this in 1.19 with KNXListener, we should register both names here for backward compatibility.

**Review by reimda — CHANGES_REQUESTED** [review]

**Review by reimda — APPROVED** [review]
