### PR TITLE
fix(elasticsearch-input): Issue-732701

### LINKED ISSUE #7327: Elasticsearch Input Plugin - Doesn't report correct field values for shards.
### Relevant telegraf.conf:

```[[inputs.elasticsearch]]

  interval                       = "30s"
  servers                        = ["https://localhost:9200"]
  http_timeout                   = "29s"

  indices_include                = ["my_index"]
  indices_level                  = "shards"

  namepass                      = [ "elasticsearch_indices_stats_shards"]
  fieldpass                      = ["store_size_in_bytes"]
```

### System info:

telegraf-1.14.0
elasticsearch-7.1.1

### Docker

N/A

### Steps to reproduce:

1. Download telegraf-1.14.0-alpine docker container and use elasticsearch input above pointing to an ES cluster.
2. Create an index called my_index with 2 primary shards and 1 replica.
3.  Run telegraf with the config in test mode, pointed at ES cluster and see the output.

### Expected behavior:

my_index is an Elasticsearch 7.1.1 index with 2 primary shards and 1 replica, so there should be a total of 4 active shards. The cluster has 6 data nodes, and when looking at the cluster itself, the shards are spread across the nodes. The primary and replica shards are not co-located on the same node as expected.

``` elasticsearch_indices_stats_shards,host=d69568f9ee31,index_name=my_index,node_id=0Yiewdb5T4WdCW_sBw4cSA,shard_name=1,type=replica store_size_in_bytes=6232080892 1586826940000000000 elasticsearch_indices_stats_shards,host=d69568f9ee31,index_name=my_index,node_id=lNMQORcqQQGwO4QH6SDKow,shard_name=1,type=primary store_size_in_bytes=6209098781 1586826940000000000 elasticsearch_indices_stats_shards,host=d69568f9ee31,index_name=my_index,node_id=0Yiewdb5T4WdCW_sBw4cSA,shard_name=0,type=primary store_size_in_bytes=6211660107 1586826940000000000 elasticsearch_indices_stats_shards,host=d69568f9ee31,index_name=my_index,node_id=6TmdVpLTTcmy6yhTUvnMhg,shard_name=0,type=replica store_size_in_bytes=6103655903 1586826940000000000```

This is output from a patched telegraf. PR will be coming shortly.

### Actual behavior:

Code https://github.com/influxdata/telegraf/blob/master/plugins/inputs/elasticsearch/elasticsearch.go#L552 only grabs the first entry in the array, which could be the primary or replica information for the shard. It does not iterate over the list and report information on each shard.

```
elasticsearch_indices_stats_shards,host=d69568f9ee31,index_name=my_index,node_id=0Yiewdb5T4WdCW_sBw4cSA,shard_name=1,type=replica store_size_in_bytes=6232080892 1586831319000000000

elasticsearch_indices_stats_shards,host=d69568f9ee31,index_name=my_index,node_id=0Yiewdb5T4WdCW_sBw4cSA,shard_name=0,type=primary store_size_in_bytes=6211660107 1586831319000000000
```

### PR DESCRIPTION
**Pull request by lrsmith**
closes #7327

### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [N/A] Associated README.md updated.
- [X] Has appropriate unit tests.

### CODE REVIEW

**Comment by lrsmith** [comment]
@danielnelson Can this be included in the 1.14.2 milestone or will it be part of a later release?

File: plugins/inputs/elasticsearch/elasticsearch.go [hunk 1]
```diff
@@ -546,10 +546,10 @@ func (e *Elasticsearch) gatherIndicesStats(url string, acc telegraf.Accumulator)
 
 		if e.IndicesLevel == "shards" {
 			for shardNumber, shard := range index.Shards {
-				if len(shard) > 0 {
+				for i := 0; i < len(shard); i++ {
 					// Get Shard Stats
 					flattened := jsonparser.JSONFlattener{}
-					err := flattened.FullFlattenJSON("", shard[0], true, true)
+					err := flattened.FullFlattenJSON("", shard[i], true, true)
```
Comment (danielnelson) [inline plugins/inputs/elasticsearch/elasticsearch.go:552]: Could you switch to this equivalent form:
```
for shardNumber, shards := range index.Shards {
    for _, shard := range shards {
```

**Comment by lrsmith** [comment]
@danielnelson Should be all set.
