### PR TITLE
Fix parsing multiple metrics on the first line of tailed file

### LINKED ISSUE #6138: json_query not parsing through all entries in the JSON array
Hi, I think there is a bug in how JSON array entries are being parsed by JSONQuery. Would really appreciate guidance on whether I've made a configuration error or this is indeed reproducible by other folks.

### Relevant telegraf.conf:

```
[[inputs.tail]]
  files = ["/test.log"]
  watch_method = "poll"
  data_format = "json"
  name_override = "test-key"
  tag_keys = ["first"]
  json_query = "friends"
```

### System info:

Telegraf v 1.11.2
OS: Debian 9

### Steps to reproduce:

1. Follow the example for JSON Query - 
https://github.com/influxdata/telegraf/tree/master/plugins/parsers/json#query
So a sample entry in the file would be - 
```
{"friends": [{"first": "Dale", "last": "Murphy", "age": 44},{"first": "Roger", "last": "Craig", "age": 68},{"first": "Jane", "last": "Murphy", "age": 47}]}
```

### Expected behavior:
All entries in the array are parsed (very similar to the posted example)
```
{"fields":{"age":44},"name":"test-key","tags":{"first":"Dale","host":"test-us1-instance","path":"/test.log"},"timestamp":1563466236}
{"fields":{"age":68},"name":"test-key","tags":{"first":"Roger","host":"test-us1-instance","path":"/test.log"},"timestamp":1563466236}
{"fields":{"age":47},"name":"test-key","tags":{"first":"Jane","host":"test-us1-instance","path":"/test.log"},"timestamp":1563466236}
```

### Actual behavior:
Only the first array entry is being parsed.
```{"fields":{"age":44},"name":"test-key","tags":{"first":"Dale","host":"test-us1-instance","path":"/test.log"},"timestamp":1563466236}```

### PR DESCRIPTION
**Pull request by danielnelson**
This is a quick fix for parsing multiple metrics on the first line of a file without breaking the special csv behavior.  #6160 will fix this in a better way, but needs changes around performance and reporting errors during construction first.

closes #6138

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

File: plugins/inputs/tail/tail.go [hunk 1]
```diff
@@ -172,55 +172,66 @@ func (t *Tail) tailNewFiles(fromBeginning bool) error {
...
+			return parser.Parse([]byte(line))
+		} else {
+			metrics := []telegraf.Metric{}
+			m, err := parser.ParseLine(line)
+			if err != nil {
+				return nil, err
+			}
+
+			if m != nil {
+				metrics = append(metrics, m)
```
Comment (glinton) [inline plugins/inputs/tail/tail.go]: Nit: use `metrics = []telegraf.Metric{m}`
