### PR TITLE
Fix ping skips remaining hosts after dns lookup error

### LINKED ISSUE #6690: inputs.ping - When one target url not responding it stops and dont ping the rest
### Relevant telegraf.conf:

```toml
[[inputs.ping]]
   urls = [
       "target1",
       "target2",
       "target3",
       "target4",
       "target5",
       "target6",
       "target7",
   ]
   method = "exec"
   count = 2
```

### System info:

```bash
# uname -a
Linux telegraf 4.14.138-rancher #1 SMP Sat Aug 10 11:25:46 UTC 2019 x86_64 GNU/Linux

# telegraf --version
Telegraf 1.12.5 (git: HEAD f09d4023)
```

### Steps to reproduce:

Have a long list of targets (url) target 1 to 7.
Now pull target3 down and NS record, and telegraf ping will only update target1 and 2 in influxdb.
The rest will shown as down.

> I have tested both with "method" set to native and exec.

### Expected behavior:

Target 1 to 2 - up and metrics
Target 3 - down
Target 4 to 7 - up and metrics

### Actual behavior:

Target 1 to 2 - up and metrics
Target 3 - down
Target 4 to 7 - down

### Additional info:

Also it's irritating that when a host is not responding that we don't set package loss to 100%.
Just a side note :)

### PR DESCRIPTION
**Pull request by danielnelson**
Continue after error.  Also fix tag name regression `url` -> `ip`. 
Compare against 1.11:

https://github.com/influxdata/telegraf/blob/747b136466cfe31084ef0ec5fc24ffb2aabba8c9/plugins/inputs/ping/ping.go#L111-L120

closes #6690

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

File: plugins/inputs/ping/ping.go [hunk 1]
```diff
@@ -122,27 +122,25 @@ func (p *Ping) Gather(acc telegraf.Accumulator) error {
 		p.listenAddr = getAddr(p.Interface)
 	}
 
-	for _, ip := range p.Urls {
-		_, err := net.LookupHost(ip)
+	for _, host := range p.Urls {
+		_, err := net.LookupHost(host)
 		if err != nil {
-			acc.AddFields("ping", map[string]interface{}{"result_code": 1}, map[string]string{"ip": ip})
+			acc.AddFields("ping", map[string]interface{}{"result_code": 1}, map[string]string{"url": host})
```
Comment (reimda) [inline plugins/inputs/ping/ping.go]: Changing the tag from ip to url is a user-facing change.  The readme says url is the only tag so maybe ip was incorrect in the first place?

Then again why are we calling it url when it's a host or ip?  For example, url can be scheme://host/path but ping doesn't use scheme or path.

Comment (reimda) [reply plugins/inputs/ping/ping.go]: Now I see your comment about ip being a regression

**Comment by oijkn** [comment]
Hello, I'm having the same problem as https://github.com/influxdata/telegraf/issues/6690. Looks like when a host is unreachable the whole ping bug afterwards.

At first I applied the recommendations and used the `method = "native"` but as soon as a host doesn't respond I get the following error messages : 

```
2020-04-20T14:25:00Z E! [inputs.ping] Error in plugin: lookup 10.2.10.125 on 10.188.28.132:53: no such host
2020-04-20T15:09:05Z E! [inputs.ping] Error in plugin: lookup google.com on 10.1.80.155:53: read udp 10.0.2.15:37935->10.1.80.155:53: i/o timeout
2020-04-20T16:08:22Z E! [inputs.ping] Error in plugin: lookup facebook.com on 10.1.80.155:53: read udp 10.0.2.15:35200->10.1.80.155:53: i/o timeout
.....
```

On the other hand when I change `method = "exec"` and a host doesn't answer, well the pings continue to run and no lookup error appears except the host who is not reachable .

### System info:
```
# uname -a
Linux localhost.localdomain 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# telegraf --version
Telegraf 1.14.1 (git: HEAD 33dd867d)
```

### Relevant telegraf.conf:
```
[[inputs.ping]]
  interval = '300s'
  urls = ['host_001']
  count = 5
  ping_interval = 1.0
  timeout = 2.0
  method = 'native'
  [inputs.ping.tags]
     plaque = '01'
     equipement = 'bng'

.........
.........

[[inputs.ping]]
  interval = '300s'
  urls = ['host_500']
  count = 5
  ping_interval = 1.0
  timeout = 2.0
  method = 'native'
  [inputs.ping.tags]
     plaque = '02'
     equipement = 'edg'
```

**Comment by danielnelson** [comment]
@oijkn How many ping plugins are running total and are they all a single host per plugin?

**Comment by oijkn** [comment]
@danielnelson In my conf file there are 500 hosts (for the moment) running in single host per plugin, as like my previous message. Because I need to tag each of them.

**Comment by danielnelson** [comment]
I think the error could be because we are trying to lookup so many hosts at the same time.  Does the i/o timeout error still occur if you only have 3 plugins with a single `no host error`?

**Comment by oijkn** [comment]
### telegraf.d/test.conf:
```
[[inputs.ping]]
  interval = '30s'
  urls = ['host1']
  count = 5
  ping_interval = 1.0
  timeout = 2.0
  method = 'native'
  [inputs.ping.tags]
     plaque = '01'
     equipement = 'bng'

[[inputs.ping]]
  interval = '30s'
  urls = ['host2']
  count = 5
  ping_interval = 1.0
  timeout = 2.0
  method = 'native'
  [inputs.ping.tags]
     plaque = '02'
     equipement = 'edg'

[[inputs.ping]]
  interval = '30s'
  urls = ['host3']
  count = 5
  ping_interval = 1.0
  timeout = 2.0
  method = 'native'
  [inputs.ping.tags]
     plaque = '03'
     equipement = 'lsr'
```

### telegraf.log:
```
2020-04-20T21:23:28Z I! Loaded inputs: ping ping ping ping
2020-04-20T21:23:28Z I! Loaded aggregators:
2020-04-20T21:23:28Z I! Loaded processors:
2020-04-20T21:23:28Z I! Loaded outputs: influxdb
2020-04-20T21:23:28Z I! Tags enabled: host=CentOS
2020-04-20T21:23:28Z I! [agent] Config: Interval:1m0s, Quiet:false, Hostname:"CentOS", Flush Interval:10s
2020-04-20T21:23:30Z E! [inputs.ping] Error in plugin: lookup host1 on xxx.xxx.xxx.xxx:53: no such host
2020-04-20T21:24:00Z E! [inputs.ping] Error in plugin: lookup host1 on xxx.xxx.xxx.xxx:53: no such host
2020-04-20T21:24:30Z E! [inputs.ping] Error in plugin: lookup host1 on xxx.xxx.xxx.xxx:53: no such host
2020-04-20T21:25:00Z E! [inputs.ping] Error in plugin: lookup host1 on xxx.xxx.xxx.xxx:53: no such host
2020-04-20T21:25:30Z E! [inputs.ping] Error in plugin: lookup host1 on xxx.xxx.xxx.xxx:53: no such host
```
It looks like if I drastically reduce the list of hosts per plugin, it continues to process the other hosts without any apparent error.

If you need more tests, let me know.

**Comment by danielnelson** [comment]
That seems to support my theory, could you open this up as a new issue?

**Comment by oijkn** [comment]
@danielnelson Before opening issue I will do some more investigations. If the problem persist I will open it and if it's solved I will post my troubleshooting :)

**Comment by danielnelson** [comment]
Okay, possible workaround is to use a `collection_jitter` to spread out when the inputs run a bit.

**Comment by oijkn** [comment]
@danielnelson Well after a lot of tests I can't manage it alone so I opened this issuehttps://github.com/influxdata/telegraf/issues/7386. Thank you in advance for your help.
