### PR TITLE
fix(config): Make labels and selectors conform to specification

### LINKED ISSUE #18105: Plugin label cannot contain capitals
### Relevant telegraf.conf

```toml
[[inputs.ping]]
  [inputs.ping.labels]
    key = "FOObar"
```

### Logs from Telegraf

```text
2025-12-09T11:42:24Z E! loading config file telegraf.conf failed: error parsing ping, invalid label in plugin inputs.ping: invalid value "FOObar"
```

### System info

Telegraf 1.37.0

### Docker

_No response_

### Steps to reproduce

1. Run `telegraf config check`

### Expected behavior

According to [TSD-010](https://github.com/influxdata/telegraf/blob/master/docs/specs/tsd-010-labels-and-selectors.md), the labels and their value could contain capital letters.

### Actual behavior

Telegraf errors out when using capital letters in key or value for a label.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by neelayu**
## Summary
Adds support for uppercase characters and `_` as defined in the original spec.

Added many unit tests for the same.

## Checklist

- [x] No AI generated code was used in this PR
- [ ] AI generated code used in this PR follows the [InfluxData Policy on AI-Generated Code Contributions][policy]

[policy]: https://www.influxdata.com/ai-generated-code-contributions-policy

## Related issues
resolves #18105

### CODE REVIEW

**Review by mstrandboge — APPROVED** [review]

File: config/plugin_selector.go [hunk 1]
```diff
@@ -14,19 +14,33 @@ const (
...
 	}
-	if !reValue.MatchString(v) {
+	if !selectorValueRegex.MatchString(v) {
+		return fmt.Errorf("invalid value %q", v)
+	}
+	return nil
+}
+
+// CheckLabelKeyValuePairs checks the key and value of a label.
+func CheckLabelKeyValuePairs(k, v string) error {
```
Comment (Hipska) [inline config/plugin_selector.go:39]: Where is this new function being used in the code?

File: config/plugin_selector_test.go [hunk 2]
```diff
@@ -75,6 +90,133 @@ func TestSetPluginLabelSelections(t *testing.T) {
...
+		{name: "colon", input: "abc:def", wantErr: true},
+		{name: "comma", input: "abc,def", wantErr: true},
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			err := CheckSelectionKeyValuePairs(tt.input, "value")
+			if tt.wantErr {
+				require.Error(t, err)
+			}
```
Comment (Hipska) [inline config/plugin_selector_test.go:128]: Also need to check false positives..
```suggestion
			if tt.wantErr {
				require.Error(t, err)
			} else {
				require.NoError(t, err)
			}

File: config/plugin_selector_test.go [hunk 3]
```diff
@@ -75,6 +90,133 @@ func TestSetPluginLabelSelections(t *testing.T) {
...
+		{name: "pipe", input: "abc|def", wantErr: true},
+		{name: "caret", input: "abc^def", wantErr: true},
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			err := CheckSelectionKeyValuePairs("key", tt.input)
+			if tt.wantErr {
+				require.Error(t, err)
+			}
```
Comment (Hipska) [inline config/plugin_selector_test.go:172]: Also need to check false positives..
```suggestion
			if tt.wantErr {
				require.Error(t, err)
			} else {
				require.NoError(t, err)
			}

File: config/plugin_selector_test.go [hunk 4]
```diff
@@ -75,6 +90,133 @@ func TestSetPluginLabelSelections(t *testing.T) {
...
+		{name: "caret", input: "abc^def", wantErr: true},
+		{name: "pipe", input: "abc|def", wantErr: true},
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			err := CheckLabelKeyValuePairs("key", tt.input)
+			if tt.wantErr {
+				require.Error(t, err)
+			}
```
Comment (Hipska) [inline config/plugin_selector_test.go:215]: Also need to check false positives..
```suggestion
			if tt.wantErr {
				require.Error(t, err)
			} else {
				require.NoError(t, err)
			}
