### PR TITLE
fix(inputs.tail): Retry opening file after permission denied

### LINKED ISSUE #13154: Permission denied in a middle of logrotate process
### Relevant telegraf.conf

```toml
[[inputs.tail]]
  files = ["/var/log/nginx/access.log"]
  data_format = "grok"
  grok_patterns = ["%{COMBINED_LOG_FORMAT}"]
```

### Logs from Telegraf

```text
2023-04-27T00:00:02+03:00 E! [inputs.tail] Tailing "/var/log/nginx/access.log": Unable to open file /var/log/nginx/access.log: open /var/log/nginx/access.log: permission denied
```

### System info

Telegraf 1.26.1 (git: HEAD@8f421f25), Docker 20.10.21, Ubuntu 22.04.2 LTS

### Docker

Releant part of `docker-compose.yml` config. Group 4 is `adm` with read access to the log files.
```
services:
    telegraf:
        image: telegraf
        volumes:
            - /var/log/nginx:/var/log/nginx:ro
        group_add:
            - "4"
```

### Steps to reproduce

1. Start Telegraf with `tail` on log file;
2. Daily rotate log file using `logrotate` utility;
3. Enentually tail will stop with permission denied error. In my case it stopped after 9 days with daily log rotation.

### Expected behavior

Retry tailing the file after failure.

### Actual behavior

Tail stops after the error.

### Additional info

The bug is **not related** to the file permissions, I'm able to start the Telegraf and obtain the logs as expected.
```
  File: /var/log/nginx/access.log
  Size: 285582    	Blocks: 568        IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 524853      Links: 1
Access: (0640/-rw-r-----)  Uid: (   33/www-data)   Gid: (    4/     adm)
Access: 2023-04-27 09:07:29.001913262 +0300
Modify: 2023-04-27 12:32:01.672785512 +0300
Change: 2023-04-27 12:32:01.672785512 +0300
 Birth: 2023-04-27 00:00:02.631913631 +0300

```

But due to (un-)lucky circumstances `tail` plugin was trying to read the file exactly at the same time `logrotate` did its job.
```
Apr 27 00:00:01 docker-host systemd[1]: Starting Rotate log files...
Apr 27 00:00:03 docker-host systemd[1]: logrotate.service: Deactivated successfully.
Apr 27 00:00:03 docker-host systemd[1]: Finished Rotate log files.
Apr 27 00:00:03 docker-host systemd[1]: logrotate.service: Consumed 1.022s CPU time.
```

As far as I understand internal workings of the `logrotate`, it first creates the new log file, and then applies `chmod` and `chown`. And seems `tail` plugin failed in a middle of this process and stopped sending the logs. Restarting the Telegraf at the morning did resolved the problem. 

But it would be nice to have built-in retry mechanism for such cases. 
Actually `tail` does retry, but only when file does not exist, rather then when file exists but (temporarly) is not accessible. 
https://github.com/influxdata/tail/blob/master/tail.go#L194

### PR DESCRIPTION
**Pull request by ericmiller-wpengine**
# Required for all PRs

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [ ] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #13154

Gather() calls tailNewFiles() and creates a tailer for any that are not in the map of tailers already. Deleting the old one from the map on "permission denied" was sufficient to get the plugin to reopen the file.

a lightly redacted section of logs. in another terminal i forced a logrotate that left the log file with the wrong permissions (0600) and then immediately chmod'ed to 0644, easier to catch than the race condition.
```
2023-11-27T21:58:37Z I! Loaded inputs: conntrack disk filestat http (3x) http_listener_v2 httpjson memcached mysql net_response (5x) nginx (2x) prometheus tail (3x)
2023-11-27T21:58:37Z I! Loaded aggregators:
2023-11-27T21:58:37Z I! Loaded processors: regex rename (2x)
2023-11-27T21:58:37Z I! Loaded secretstores:
2023-11-27T21:58:37Z I! Loaded outputs: file
2023-11-27T21:58:37Z I! Tags enabled: <some tags were here>
2023-11-27T21:58:37Z W! Deprecated inputs: 1 and 0 options
2023-11-27T21:58:37Z I! [agent] Config: Interval:30s, Quiet:false, Hostname:"fake", Flush Interval:1m0s
2023-11-27T21:58:37Z I! [inputs.prometheus] Using the label selector:  and field selector:
2023-11-27T21:58:37Z I! [inputs.http_listener_v2] Listening on [::]:8185
{"fields":{"account_name":"foobar",<more fields omitted>},"name":"nginxlog","tags":{"datacenter":"self-contained",<more tags omitted>},"timestamp":1701122545}
2023-11-27T22:03:31Z E! [inputs.tail] Tailing "/.../access.json": Unable to open file /.../access.json: open /.../access.json: permission denied
2023-11-27T22:03:31Z E! [inputs.tail] Deleting tailer for "/.../access.json"
{"fields":{"account_name":"foobar",<more fields omitted>},"name":"nginxlog","tags":{"datacenter":"self-contained",<more tags omitted>},"timestamp":1701122692}
```

### CODE REVIEW

**Comment by ericmiller-wpengine** [comment]
!signed-cla

**Comment by Hipska** [comment]
What happens in the scenario the file becomes inaccessible, then few lines added, then accessible again?

**Review by Hipska — APPROVED** [review]

File: plugins/inputs/tail/tail.go [hunk 1]
```diff
@@ -236,6 +236,10 @@ func (t *Tail) tailNewFiles(fromBeginning bool) error {
 
 				if err := tailer.Err(); err != nil {
 					t.Log.Errorf("Tailing %q: %s", tailer.Filename, err.Error())
+					if strings.HasSuffix(err.Error(), "permission denied") {
```
Comment (srebhan) [inline plugins/inputs/tail/tail.go:239]: Have you tried to use `errors.Is(err, os.ErrPermission)` here? It might nor work as the `tail` package might not wrap the errors correctly...

File: plugins/inputs/tail/tail.go [hunk 2]
```diff
@@ -236,6 +236,10 @@ func (t *Tail) tailNewFiles(fromBeginning bool) error {
...
+						t.Log.Errorf("Deleting tailer for %q", tailer.Filename)
```
Comment (srebhan) [inline plugins/inputs/tail/tail.go:240]: How about adding some details like
```suggestion
						t.Log.Errorf("Deleting tailer for %q: %v", tailer.Filename, err)
```

**Review by srebhan — COMMENTED** [review]
Thanks for the PR @ericmiller-wpengine! One question and one suggestion from my side...

File: plugins/inputs/tail/tail.go (hunk 2 above)
Comment (ericmiller-wpengine) [reply plugins/inputs/tail/tail.go]: I moved the previous log message into an else at the same time, hopefully this is adequately idiomatic.

**Review by powersj — APPROVED** [review]
Thanks for coming up with this!
