### PR TITLE
use AddError everywhere

### LINKED ISSUE #1446: telegraf needs better support for partial failure/success
### Proposal:

The telgraf code needs a better way of supporting plugins with partial success/failure.
### Current behavior:

Currently partial success/failure is handled, or not handled, in numerous ways. Many of which are very buggy. I started going through the plugins looking for issues (see #1440, #1441, #1442, #1443, #1444, #1445), but stopped because of how prevalent they are.

There seems to be 4 general categories which plugins fall into when they have the possibility of partial success/failure.
1. The plugin captures the first error, returns it, and discards all the rest.
2. The plugin gathers all errors and concatenates them together.
3. The plugin attempts to capture one error, but fails to do so properly (#1440, #1442, #1444, #1445)
4. The plugin returns on the first error it encounters, skipping any further meaasurements which might actually succeed (#1439, #1441, #1443).
### Desired behavior:

We instead need some simplified way for plugins to report multiple errors back to telegraf core.
I think the simplest way might be to just add a `AddError()` method to [`telegraf.Accumulator`](https://godoc.org/github.com/influxdata/telegraf#Accumulator).

The other option might be to expose a general purpose logger on the accumulator. This might be better as then plugins could log things at different log levels (error, warning, info, debug, etc), and when a user wants to troubleshoot an issue, they can just bump up the log level.
### Use case: [Why is this important (helps with prioritizing requests)]

Make it easier (and more consistent) for plugin developers to handle errors, and less likely for them to introduce buggy code.

### PR DESCRIPTION
**Pull request by phemmer**
### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Closes #1446 

Also addressed some of the issues described in https://github.com/influxdata/telegraf/issues/2326#issuecomment-277542420 by cleaning up some of the `fmt.Printf()` and `log.Print()` statements to use `acc.AddError()`.

### CODE REVIEW

File: testutil/accumulator.go [hunk 1]
```diff
@@ -161,6 +161,17 @@ func (a *Accumulator) Get(measurement string) (*Metric, bool) {
...
+// Calls the given Gather function and returns the first error found.
+func (a *Accumulator) GatherError(gf func(telegraf.Accumulator) error) error {
+	if err := gf(a); err != nil {
+		return err
+	}
+	if len(a.Errors) > 0 {
+		return a.Errors[0]
+	}
+	return nil
+}
```
Comment (phemmer) [inline testutil/accumulator.go]: I'm open to feedback on this method. I just wrote it as it made adjusting the tests a lot easier by not having to check the return value of `Gather()` and any errors added by `AddError()`.

Comment (phemmer) [inline testutil/accumulator.go]: I think I would prefer to accept a [`telegraf.Input`](https://godoc.org/github.com/influxdata/telegraf#Input) interface, and then call the `Gather()` method on that interface instead of accepting the `Gather` function signature.

File: plugins/inputs/cassandra/cassandra.go [hunk 2]
```diff
@@ -274,25 +273,26 @@ func (c *Cassandra) Gather(acc telegraf.Accumulator) error {
...
+				continue
 			}
 			if serverTokens["user"] != "" && serverTokens["passwd"] != "" {
 				requestUrl.User = url.UserPassword(serverTokens["user"],
 					serverTokens["passwd"])
 			}
 
 			out, err := c.getAttr(requestUrl)
-			if out["status"] != 200.0 {
-				fmt.Printf("URL returned with status %v\n", out["status"])
```
Comment (phemmer) [inline plugins/inputs/cassandra/cassandra.go]: This change I'm not completely certain about as I'm not familiar with Cassandra. The code I removed appears like it would never evaluate as non-200 responses are handled up on [line 211](https://github.com/influxdata/telegraf/blob/c8cc01ba6a27a68a5d161152d9323d3e801edfbd/plugins/inputs/cassandra/cassandra.go#L211).
However if cassandra will respond with an http-200, but a non-200 in the body, then that would trigger the code. However the tests do not mock out a `status` field in the body.

File: plugins/inputs/jolokia/jolokia_test.go [hunk 3]
```diff
@@ -175,7 +175,7 @@ func TestHttpJsonOn404(t *testing.T) {
 
 	var acc testutil.Accumulator
 	acc.SetDebug(true)
-	err := jolokia.Gather(&acc)
+	err := acc.GatherError(jolokia.Gather)
 
 	assert.Nil(t, err)
```
Comment (phemmer) [inline plugins/inputs/jolokia/jolokia_test.go]: This test is failing because of a similar situation to the cassandra one. The code was previously printing an error, but is now being passed to `AddError()`. The problem here is that this test doesn't make much sense. It generates a stub that returns valid JSON, but with a http 404 status code. Jolokia will not do this, thus the test seems bogus.

Given that the cassandra code seems to be based off the jolokia code, I'm betting the cassandra test that I previously commented on is bogus too.

File: plugins/inputs/cassandra/cassandra_test.go [hunk 4]
```diff
@@ -197,24 +197,25 @@ func TestHttpJsonJavaMultiType(t *testing.T) {
 }
 
 // Test that the proper values are ignored or collected
-func TestHttpJsonOn404(t *testing.T) {
+func TestHttp404(t *testing.T) {
```
Comment (phemmer) [inline plugins/inputs/cassandra/cassandra_test.go]: As a resolution to [the earlier comment on this test](https://github.com/influxdata/telegraf/pull/2372#discussion_r99757820), I'm changing the test to look for the error that is now passed via AddError(). Previous behavior of the plugin was that it was ignoring http-404 errors, and instead printing (not returning) an error when it failed to parse the response body. New behavior calls `AddError()` on both non-http-200 responses, as well as parse errors.

The cassandra plugin test was modified for the same reason.

**Comment by phemmer** [comment]
CircleCI test is failing due to #2382 . Just keep running it. Eventually it'll pass.

File: testutil/accumulator.go (hunk 1 above)
Comment (danielnelson) [inline testutil/accumulator.go]: Agreed, but it's not critical, we can improve this latter

**Comment by phemmer** [comment]
> I'm going to push most of the remaining 1.3 features out and try to get the next release ready soon, but I'd like to merge this. Do you have time to rebase?

Yeah, I doubt it'll be hard. When do you need it by? Hopefully I'll take care of it tonight.

**Comment by danielnelson** [comment]
That will be good, probably try to branch for the release sometime early next week.

**Comment by phemmer** [comment]
Rebased. Tests passing.

File: testutil/accumulator.go (hunk 1 above)
Comment (phemmer) [inline testutil/accumulator.go]: Another improvement might be to add an `acc.AddErrorf()`. The vast majority of the usage is nesting an `fmt.Errorf()` inside `acc.AddError()`. Would just be a convenience.

Comment (danielnelson) [inline testutil/accumulator.go]: Long term I think we need to allow access to log level as well, probably using a good logging library that allows control at a per logger basis (and one logger per plugin).

Comment (phemmer) [inline testutil/accumulator.go]: I proposed this a few times, but was always declined by your predecessor. Not sure what the reasons were though.
https://github.com/influxdata/telegraf/issues/1446#issuecomment-233371520
https://github.com/influxdata/telegraf/issues/2326#issuecomment-277557824
