### PR TITLE
fix: check index before assignment

### LINKED ISSUE #10298: Telegraf 1.21.0 - go panic with SNMP plugin
### Relevent telegraf.conf

```toml
Dec 17 16:38:04 hostname systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
Dec 17 16:38:04 hostname telegraf[306402]: 2021-12-17T15:38:04Z I! Starting Telegraf 1.21.1
Dec 17 16:38:04 hostname telegraf[306402]: 2021-12-17T15:38:04Z I! Loaded inputs: cpu disk internal mem net ping snmp (352x) swap
Dec 17 16:38:04 hostname telegraf[306402]: 2021-12-17T15:38:04Z I! Loaded aggregators:
Dec 17 16:38:04 hostname telegraf[306402]: 2021-12-17T15:38:04Z I! Loaded processors: converter
Dec 17 16:38:04 hostname telegraf[306402]: 2021-12-17T15:38:04Z I! Loaded outputs: influxdb_v2 (2x)
Dec 17 16:38:04 hostname telegraf[306402]: 2021-12-17T15:38:04Z I! Tags enabled: host=s
Dec 17 16:38:04 hostname telegraf[306402]: 2021-12-17T15:38:04Z I! [agent] Config: Interval:2m0s, Quiet:false, Hostname:"", Flush Interval:10s
Dec 17 16:38:06 hostname telegraf[306402]: panic: runtime error: index out of range [1] with length 1
Dec 17 16:38:06 hostname telegraf[306402]: goroutine 1 [running]:
Dec 17 16:38:06 hostname telegraf[306402]: github.com/influxdata/telegraf/internal/snmp.SnmpTranslateCall({0xc00158ca81, 0x27})
Dec 17 16:38:06 hostname telegraf[306402]:         /go/src/github.com/influxdata/telegraf/internal/snmp/translate.go:153 +0xbfd
Dec 17 16:38:06 hostname telegraf[306402]: github.com/influxdata/telegraf/plugins/inputs/snmp.SnmpTranslate({0xc00158ca81, 0x27})
Dec 17 16:38:06 hostname telegraf[306402]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/snmp/snmp.go:877 +0x170
Dec 17 16:38:06 hostname telegraf[306402]: github.com/influxdata/telegraf/plugins/inputs/snmp.(*Field).init(0xc000766708)
Dec 17 16:38:06 hostname telegraf[306402]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/snmp/snmp.go:263 +0x73
Dec 17 16:38:06 hostname telegraf[306402]: github.com/influxdata/telegraf/plugins/inputs/snmp.(*Table).Init(0xc0016ede00)
Dec 17 16:38:06 hostname telegraf[306402]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/snmp/snmp.go:169 +0xd8
Dec 17 16:38:06 hostname telegraf[306402]: github.com/influxdata/telegraf/plugins/inputs/snmp.(*Snmp).Init(0xc0009f7340)
Dec 17 16:38:06 hostname telegraf[306402]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/snmp/snmp.go:110 +0x127
Dec 17 16:38:06 hostname telegraf[306402]: github.com/influxdata/telegraf/models.(*RunningInput).Init(0xc000e4b758)
Dec 17 16:38:06 hostname telegraf[306402]:         /go/src/github.com/influxdata/telegraf/models/running_input.go:82 +0x35
Dec 17 16:38:06 hostname telegraf[306402]: github.com/influxdata/telegraf/agent.(*Agent).initPlugins(0xc000184ba8)
Dec 17 16:38:06 hostname telegraf[306402]:         /go/src/github.com/influxdata/telegraf/agent/agent.go:189 +0x96
Dec 17 16:38:06 hostname telegraf[306402]: github.com/influxdata/telegraf/agent.(*Agent).Run(0xc000184ba8, {0x57e5688, 0xc000acc380})
Dec 17 16:38:06 hostname telegraf[306402]:         /go/src/github.com/influxdata/telegraf/agent/agent.go:105 +0x185
Dec 17 16:38:06 hostname telegraf[306402]: main.runAgent({0x57e5688, 0xc000acc380}, {0x837a278, 0x0, 0x0}, {0x837a278, 0x0, 0x0})
Dec 17 16:38:06 hostname telegraf[306402]:         /go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:312 +0xc57
Dec 17 16:38:06 hostname telegraf[306402]: main.reloadLoop({0x837a278, 0x0, 0x0}, {0x837a278, 0x0, 0x0})
Dec 17 16:38:06 hostname telegraf[306402]:         /go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:147 +0x28a
Dec 17 16:38:06 hostname telegraf[306402]: main.run(...)
Dec 17 16:38:06 hostname telegraf[306402]:         /go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf_posix.go:8
Dec 17 16:38:06 hostname telegraf[306402]: main.main()
Dec 17 16:38:06 hostname telegraf[306402]:         /go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:485 +0xa9a
Dec 17 16:38:06 hostname systemd[1]: telegraf.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 17 16:38:06 hostname systemd[1]: telegraf.service: Failed with result 'exit-code'.
Dec 17 16:38:07 hostname systemd[1]: telegraf.service: Service RestartSec=100ms expired, scheduling restart.
Dec 17 16:38:07 hostname systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 26.
Dec 17 16:38:07 hostname systemd[1]: Stopped The plugin-driven server agent for reporting metrics into InfluxDB.
```

### System info

Telegraf 1.21.1

### Docker

_No response_

### Steps to reproduce

1.
After the agent restarted it restarts every 100ms because of the error "panic: runtime error: index out of range [1] with length 1"
2.
rollback to 1.21.0 does not fix the issue
rollback to 1.20.4 fixes the issue
3.
...

### Expected behavior

to work like 1.20.4

### Actual behavior

crashes

### Additional info

Not sure if I have a specific snmp MIB file that causes this, I cannot see any reference in the trace what causes it besides snmptranslate

### PR DESCRIPTION
**Pull request by MyaLongmire**
### Required for all PRs:

- [ ] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #10298 

Check the index before looking it up in case there is a floating :: eg. `RFC1213-MIB::` instead of `RFC1213-MIB::sysUpTime`, also added unit test. This will now error instead of panic

### CODE REVIEW

File: internal/snmp/translate.go [hunk 1]
```diff
@@ -150,20 +150,24 @@ func SnmpTranslateCall(oid string) (mibName string, oidNum string, oidText strin
...
+			out, err = gosmi.GetNode(node)
+			if err != nil {
+				return oid, oid, oid, oid, err
+			}
 
-		oidNum = "." + out.RenderNumeric() + end
+			oidNum = "." + out.RenderNumeric() + end
+		} else {
+			return "", oid, oid, oid, fmt.Errorf("can not parse %v\n", oid)
+		}
```
Comment (srebhan) [inline internal/snmp/translate.go:170]: Please invert the logic to save some indention...
```golang
		s := strings.Split(oid, "::")
		// node becomes sysUpTime.0
		if s[1] == "" {
			return "", oid, oid, oid, fmt.Errorf("cannot parse %v\n", oid)
		}
		node := s[1]
		if strings.ContainsAny(node, ".") {
			s = strings.Split(node, ".")
			// node becomes sysUpTime
			node = s[0]
			end = "." + s[1]
		}

		out, err = gosmi.GetNode(node)
		if err != nil {
			return oid, oid, oid, oid, err
		}

		oidNum = "." + out.RenderNumeric() + end
```

Another thing is that you split unconditionally, that is, if there are multiple (`::` or `.`) separators, you will only process the first and the second element and ignore all others. Maybe it would be better to explicitly use [`strings.SplitN(..., 2)`](https://pkg.go.dev/strings#SplitN) as I think you intent to split into two parts, aren't you?

**Review by srebhan — COMMENTED** [review]
Hey @MyaLongmire, thanks for looking into this! One small comment and a question regarding using `SplitN` instead of `Split`...

File: internal/snmp/translate.go (hunk 1 above)
Comment (Hipska) [reply internal/snmp/translate.go:170]: I would also already assign `node` before first `if`. 

While we're here, maybe better also change `s := strings.SplitN(oid, "::", 2)`.

Comment (MyaLongmire) [reply internal/snmp/translate.go]: Flipped the logic and changed both to `string.SplitN()`. I didn't know about splitN but it is super useful. Thank you for the suggestion!

**Review by srebhan — APPROVED** [review]
Looks perfect to me. Thanks @MyaLongmire!!!

File: internal/snmp/translate.go [hunk 2]
```diff
@@ -148,11 +148,14 @@ func SnmpTranslateCall(oid string) (mibName string, oidNum string, oidText strin
 	if strings.ContainsAny(oid, "::") {
 		// split given oid
 		// for example RFC1213-MIB::sysUpTime.0
-		s := strings.Split(oid, "::")
+		s := strings.SplitN(oid, "::", 2)
 		// node becomes sysUpTime.0
+		if s[1] == "" {
+			return "", oid, oid, oid, fmt.Errorf("cannot parse %v\n", oid)
+		}
 		node := s[1]
```
Comment (Hipska) [inline internal/snmp/translate.go:156]:
```suggestion
		// node becomes sysUpTime.0
		node := s[1]
		if node == "" {
			return "", oid, oid, oid, fmt.Errorf("cannot parse %v\n", oid)
		}
```

**Review by Hipska — CHANGES_REQUESTED** [review]

**Review by powersj — APPROVED** [review]

File: internal/snmp/translate.go (hunk 2 above)
Comment (MyaLongmire) [reply internal/snmp/translate.go:156]: I like checking s[1] before assigning as there is no point assigning node just to error out.
