### PR TITLE
fix: CrateDB replace dots in tag keys with underscores

### LINKED ISSUE #7026: CrateDB Output to replace dots in tags with custom separator
### Proposal:

When using the CrateDB output plugin with the Docker plugin enabled, some measurements fail to get inserted into CrateDB because they have a dot in their tag name.

### Current behavior:

Feb 14 03:50:21 agent-1 telegraf[1345]: 2020-02-14T03:50:21Z E! [agent] Error writing to output [cratedb]: ERROR: "io.k8s.description" contains a dot (SQLSTATE XX000)
Feb 14 03:50:31 agent-1 telegraf[1345]: 2020-02-14T03:50:31Z E! [agent] Error writing to output [cratedb]: ERROR: "dockerImage.teamcity.buildNumber" contains a dot (SQLSTATE XX000)

### Desired behavior:

The measurements should have the dots replaced with something valid for CrateDB such as underscores or be able to be configurable.

### Use case: 

Currently finding it difficult for Telegraf to send all metrics into CrateDB

### PR DESCRIPTION
**Pull request by akrantz01**
### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.

resolves #7026 

Fixes a bug in the `cratedb` output where records would fail to insert if any tags contained keys separated by dots by replacing all dots with underscores in the key. Also made insertion errors more explicit since CrateDB does not cause the entire insert command to fail when the one record fails in a batch.

### CODE REVIEW

File: plugins/outputs/cratedb/cratedb.go [hunk 1]
```diff
@@ -171,12 +187,15 @@ func escapeObject(m map[string]interface{}) (string, error) {
 	// Now we build our key = val pairs
 	pairs := make([]string, 0, len(m))
 	for _, k := range keys {
-		// escape the value of our key k (potentially recursive)
+		key := strings.ReplaceAll(escapeString(k, `"`), ".", "_")
```
Comment (srebhan) [inline plugins/outputs/cratedb/cratedb.go:190]: Can we please make the "replacement character" configurable? Or is underscore the only valid replacement?

File: plugins/outputs/cratedb/cratedb_test.go [hunk 2]
```diff
@@ -93,66 +92,69 @@ VALUES
 	}
 }
 
+var escapeValueTests = []struct {
```
Comment (srebhan) [inline plugins/outputs/cratedb/cratedb_test.go:95]: Please do this as a function, returning a fresh new instance of the patterns for every tests. We should do this to be _absolutely_ sure there are no side-effects between the tests by (accidentally) altering those patterns.

**Review by srebhan — APPROVED** [review]
Thanks @akrantz01 for looking into this! Just two minor comments. The one is regarding the replacement character, which should be configurable (maybe out of a set of valid characters) by the user.
The second point is regarding the tests. Please do not share the same _instance_ of test-patterns between tests, as one test might accidentally modify the pattern making the other test fail or pass (in the worst case).

**Review by srebhan — COMMENTED** [review]
Meant to have comments. ;-)

File: plugins/outputs/cratedb/cratedb.go [hunk 3]
```diff
@@ -171,12 +190,15 @@ func escapeObject(m map[string]interface{}) (string, error) {
 	// Now we build our key = val pairs
 	pairs := make([]string, 0, len(m))
 	for _, k := range keys {
-		// escape the value of our key k (potentially recursive)
-		val, err := escapeValue(m[k])
+		key := strings.ReplaceAll(escapeString(k, `"`), ".", keyReplacement)
```
Comment (srebhan) [inline plugins/outputs/cratedb/cratedb.go:193]: Should we maybe _first_ replace and _then_ escape the resulting string? Otherwise it might be possible to craft the replacement to circumvent escaping?

**Review by srebhan — COMMENTED** [review]
Looks good, only one comment regarding escaping order of the string.

File: plugins/outputs/cratedb/cratedb.go (hunk 3 above)
Comment (akrantz01) [reply plugins/outputs/cratedb/cratedb.go:193]: Oh, good catch

File: plugins/outputs/cratedb/cratedb.go [hunk 4]
```diff
@@ -68,15 +71,31 @@ CREATE TABLE IF NOT EXISTS ` + c.Table + ` (
...
 	}
+
+	if affected, err := result.RowsAffected(); err != nil {
+		return err
+	} else if affected != int64(len(metrics)) {
+		// Unfortunately this is the most we can do to ensure everything was written. CrateDB
+		// does not return an error for a single row when doing bulk inserts, instead it just
+		// decrements the number of affected rows.
+		// https://crate.io/docs/crate/reference/en/latest/general/dml.html#inserting-data
+		return fmt.Errorf("failed to insert %d rows", int64(len(metrics))-affected)
```
Comment (ssoroka) [inline plugins/outputs/cratedb/cratedb.go:92]: only return an error if you want these writes to be retried until they succeed. If there are valid reasons for some rows not to be written to the db (eg they already exist there) then this will fail unnecessarily.

Comment (akrantz01) [reply plugins/outputs/cratedb/cratedb.go:92]: What do you suggest we do then, just keep it as it was or something else?

Comment (ssoroka) [reply plugins/outputs/cratedb/cratedb.go:92]: probably shouldn't check RowsAffected; error isn't necessary

File: plugins/outputs/cratedb/cratedb.go [hunk 5]
```diff
@@ -68,15 +71,31 @@ CREATE TABLE IF NOT EXISTS ` + c.Table + ` (
...
+	}
```
Comment (ssoroka) [inline plugins/outputs/cratedb/cratedb.go:93]:
```suggestion
	}
```

File: plugins/outputs/cratedb/cratedb.go [hunk 6]
```diff
@@ -68,15 +71,31 @@ CREATE TABLE IF NOT EXISTS ` + c.Table + ` (
...
+
```
Comment (ssoroka) [inline plugins/outputs/cratedb/cratedb.go:94]:
```suggestion
```

File: plugins/outputs/cratedb/cratedb.go [hunk 7]
```diff
@@ -68,15 +71,21 @@ CREATE TABLE IF NOT EXISTS ` + c.Table + ` (
...
 	defer cancel()
-	if sql, err := insertSQL(c.Table, metrics); err != nil {
+
+	generatedSQL, err := insertSQL(c.Table, c.KeySeparator, metrics)
+	if err != nil {
 		return err
-	} else if _, err := c.DB.ExecContext(ctx, sql); err != nil {
+	}
+
+	result, err := c.DB.ExecContext(ctx, generatedSQL)
```
Comment (ssoroka) [inline plugins/outputs/cratedb/cratedb.go:80]:
```suggestion
	_, err := c.DB.ExecContext(ctx, generatedSQL)
```
