### PR TITLE
fix(parsers.json_v2): Reset parser before parsing (#13805)

### LINKED ISSUE #13805: Weird behavior of json_v2 parser with multiple input lines and lots of decimal places
### Relevant telegraf.conf

```toml
[[inputs.tail]]
  files = ["./test-input.txt"]
  from_beginning = true
  data_format = "json_v2"

  [[inputs.tail.json_v2]]
    [[inputs.tail.json_v2.object]]
      path = "{fields}"

    [[inputs.tail.json_v2.object.field]]
      path = "fields.kwh_import"
      rename = "o1"

    [[inputs.tail.json_v2.object.field]]
      path = "fields.kwh_export"
      rename = "o2"

    [[inputs.tail.json_v2.object.field]]
      path = "fields.freq"
      rename = "o3"


[[outputs.file]]
  files = ["./test-output.txt"]
```

### Logs from Telegraf

```text
$ telegraf --debug --config test-config.conf
2023-08-21T16:47:49Z I! Loading config: test-config.conf
2023-08-21T16:47:49Z I! Starting Telegraf 1.27.3
2023-08-21T16:47:49Z I! Available plugins: 237 inputs, 9 aggregators, 28 processors, 23 parsers, 59 outputs, 4 secret-stores
2023-08-21T16:47:49Z I! Loaded inputs: tail
2023-08-21T16:47:49Z I! Loaded aggregators:
2023-08-21T16:47:49Z I! Loaded processors:
2023-08-21T16:47:49Z I! Loaded secretstores:
2023-08-21T16:47:49Z I! Loaded outputs: file
2023-08-21T16:47:49Z I! Tags enabled: host=ai-2
2023-08-21T16:47:49Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"ai-2", Flush Interval:10s
2023-08-21T16:47:49Z D! [agent] Initializing plugins
2023-08-21T16:47:49Z D! [agent] Connecting outputs
2023-08-21T16:47:49Z D! [agent] Attempting connection to [outputs.file]
2023-08-21T16:47:49Z D! [agent] Successfully connected to outputs.file
2023-08-21T16:47:49Z D! [agent] Starting service inputs
2023-08-21T16:47:49Z D! [inputs.tail] Tail added for "test-input.txt"
2023-08-21T16:47:59Z D! [outputs.file] Wrote batch of 3 metrics in 89.699µs
2023-08-21T16:47:59Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-08-21T16:48:05Z D! [agent] Stopping service inputs
2023-08-21T16:48:05Z D! [inputs.tail] Tail removed for "test-input.txt"
2023-08-21T16:48:05Z D! [agent] Input channel closed
2023-08-21T16:48:05Z I! [agent] Hang on, flushing any cached metrics before shutdown
2023-08-21T16:48:05Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-08-21T16:48:05Z I! [agent] Stopping running outputs
2023-08-21T16:48:05Z D! [agent] Stopped Successfully
```

### System info

Telegraf 1.27.3, Debian 12

### Docker

_No response_

### Steps to reproduce

1. Prepare input file `./test-input.txt` as follows:
```
{"fields":{"freq":50.02000045776367,"kwh_export":0,"kwh_import":568.5}}
{"fields":{"freq":50.0099983215332,"kwh_export":0,"kwh_import":568.5}}
{"fields":{"freq":50,"kwh_export":0,"kwh_import":568.5}}
```
2. Run `telegraf --debug --config test-config.conf`
3. Observe `./test-output.txt`

### Expected behavior

Each line of output should contain fields o1, o2, o3:
```
tail,host=ai-2,path=test-input.txt o3=50.02000045776367,o2=0,o1=568.5 1692636469843257713
tail,host=ai-2,path=test-input.txt o3=50.0099983215332,o2=0,o1=568.5 1692636469843312200
tail,host=ai-2,path=test-input.txt o3=50,o2=0,o1=568.5 1692636469843327461
```

### Actual behavior

Last line of output is missing field `o1`:
```
tail,host=ai-2,path=test-input.txt o3=50.02000045776367,o2=0,o1=568.5 1692636469843257713
tail,host=ai-2,path=test-input.txt o3=50.0099983215332,o2=0,o1=568.5 1692636469843312200
tail,host=ai-2,path=test-input.txt o3=50,o2=0 1692636469843327461
```

### Additional info

Number of decimals in freq field seems to have significance. If input is changed to:
```
{"fields":{"freq":50.02,"kwh_export":0,"kwh_import":568.5}}
{"fields":{"freq":50.01,"kwh_export":0,"kwh_import":568.5}}
{"fields":{"freq":50,"kwh_export":0,"kwh_import":568.5}}
```
The output is as expected.

Also, there need to be multiple lines before "freq":50 for the anomaly to occur. 

Another workaround is to increase decimals for the last freq:
```
{"fields":{"freq":50.02000045776367,"kwh_export":0,"kwh_import":568.5}}
{"fields":{"freq":50.0099983215332,"kwh_export":0,"kwh_import":568.5}}
{"fields":{"freq":50.00,"kwh_export":0,"kwh_import":568.5}}
```
..producing:
```
tail,host=ai-2,path=test-input.txt o3=50.02000045776367,o2=0,o1=568.5 1692638034737406013
tail,host=ai-2,path=test-input.txt o3=50.0099983215332,o2=0,o1=568.5 1692638034737459133
tail,host=ai-2,path=test-input.txt o3=50,o2=0,o1=568.5 1692638034737474051
```

The anomaly was first observed with AMQP, but it seems to be reproducible with the tail input plugin.

### PR DESCRIPTION
**Pull request by agiilit-admin**
# Required for all PRs

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [ ] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #13805

Running json_v2 parser leaves `p.subPathResults` dirty, affecting subsequent runs. This is a problem for input plugins reusing json_v2 parser instance instead of creating a new one.

Following the pattern of `csv` parser, added a `Reset()` method, which clears `subPathResults`. It is called in `Init()` and when starting `Parse()`.

### CODE REVIEW

**Comment by agiilit-admin** [comment]
!signed-cla

File: plugins/parsers/json_v2/parser.go [hunk 1]
```diff
@@ -113,6 +117,8 @@ func (p *Parser) Init() error {
 			p.Configs[i].Location = loc
 		}
 	}
+	p.Reset()
+
```
Comment (Hipska) [inline plugins/parsers/json_v2/parser.go:121]: Doesn't seem necessary in Init?

**Comment by srebhan** [comment]
@agiilit-admin how do you plan to use it? IMO the subpaths should be cleaned out on every call to `Parse` as we will _always_ get a new document in that call!?!?

File: plugins/parsers/json_v2/parser.go (hunk 1 above)
Comment (agiilit-admin) [reply plugins/parsers/json_v2/parser.go:121]: No, not strictly necessary, but one can think of Reset() as implementing ensure pattern, so it is logical to place it as the last operation in `Init()`.

**Comment by agiilit-admin** [comment]
> @agiilit-admin how do you plan to use it? IMO the subpaths should be cleaned out on every call to `Parse` as we will _always_ get a new document in that call!?!?

In CSV parser there is a separate `ResetMode`, and a conditional inside `Parse()`:
```
// Reset the parser according to the specified mode
        if p.ResetMode == "always" {
                p.Reset()
        }
```
but since here I could not think of a use case where `Reset()` should _not_ be called in `Parse()` (because, as you said, `Parse()` is always called with a new document), I left out the `if` and always call `p.Reset()` in `Parse()`.

**Comment by srebhan** [comment]
I think my comment was a bit misleading, sorry for that! What I mean is, why implement an exported `Reset` method if you can put the `p.subPathResults = nil` statement directly as a first line in `Parse()`? Maybe add a small comment that this is required to reset the state of the parser or something...

**Comment by srebhan** [comment]
Oh and @agiilit-admin you need to sign the CLA as otherwise we cannot take your PR...

**Comment by agiilit-admin** [comment]
> Oh and @agiilit-admin you need to sign the CLA as otherwise we cannot take your PR...

I thought I did and posted the `!signed-cla` comment here as requested. Is there still something I should do?

**Comment by agiilit-admin** [comment]
> I think my comment was a bit misleading, sorry for that! What I mean is, why implement an exported `Reset` method if you can put the `p.subPathResults = nil` statement directly as a first line in `Parse()`? Maybe add a small comment that this is required to reset the state of the parser or something...

Probably it is just a learned predisposition: I don't think `Parse()` internal variables such as `p.subPathResults` should be visible via instance variables at all if `Parse()` is meant to be reused, but if they are, then there should be an instance method to revert the parser back to the state it was just after coming out of the constructor.

Anyway, comments added.

**Comment by srebhan** [comment]
While I do agree with your thinking, in the current state this is useless to export `Reset()` as no plugin can use it without type-asserting the parser. Furthermore, it is fundamentally wrong to require the _user_ of the parser to know about the internal workings! You _always_ need to reset this state after parsing, there is no use-case to _not_ reset `subPathResults` (contrary to CSV), so just do it and do not require others to care.

Therefore, please do not export the `Reset()` function! And in turn this then is a one-function-call wrapping function which should go away.

**Review by powersj — APPROVED** [review]
