### PR TITLE
fix(inputs.mqtt_consumer): Rely on paho auto-reconnect to restore message flow after network disruption

### LINKED ISSUE #16035: Telegraf stops producing data after a network disconnect and reconnect.
### Relevant telegraf.conf

```toml
[agent]
  omit_hostname = true
  debug = true

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "$KTS_TELEMETRY_INFLUXDB_TOKEN"
  organization = "$KTS_TELEMETRY_INFLUXDB_ORG"
  bucket = "$KTS_TELEMETRY_INFLUXDB_BUCKET"


[[inputs.mqtt_consumer]]
  data_format = "json_v2"
  client_trace = true
  servers = ["tcp://10.0.200.10:1883"]
  topics = [
    "/sample/#", "/request/#", "/event/#"
  ]
  [[inputs.mqtt_consumer.json_v2]]
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "@this"
      excluded_keys = []
```

### Logs from Telegraf

```text
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [client]  internalConnLost called
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [client]  stopCommsWorkers called
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [net]     incoming complete
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: ibound complete
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [net]     startIncomingComms goroutine complete
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [router]  matchAndDispatch exiting
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [net]     outgoing waiting for an outbound message
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [net]     outgoing waiting for an outbound message
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [net]     outgoing waiting for an outbound message
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [net]     outgoing comms stopping
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [net]     startComms closing outError
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [client]  incoming comms goroutine done
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [client]  internalConnLost waiting on workers
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [client]  startCommsWorkers output redirector finished
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [client]  stopCommsWorkers waiting for workers
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [client]  stopCommsWorkers waiting for comms
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [client]  stopCommsWorkers done
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [client]  internalConnLost workers stopped
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [client]  BUG BUG BUG reconnection function is nil<nil>
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [msgids]  cleaned up
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [client]  internalConnLost complete
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] [client]  status is already disconnected
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z E! [inputs.mqtt_consumer] Error in plugin: connection lost: pingresp not received, disconnecting
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:30Z D! [inputs.mqtt_consumer] Disconnected [tcp://10.0.200.10:1883]
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:40Z D! [inputs.mqtt_consumer] Connecting [tcp://10.0.200.10:1883]
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:40Z D! [inputs.mqtt_consumer] [client]  Connect()
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:40Z D! [inputs.mqtt_consumer] [store]   memorystore initialized
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:40Z D! [inputs.mqtt_consumer] [client]  about to write new connect msg
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:50Z D! [inputs.mqtt_consumer] Previous collection has not completed; scheduled collection skipped
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:50Z W! [inputs.mqtt_consumer] Collection took longer than expected; not complete after interval of 10s
telemetry-mqtt_telegraf-1  | 2024-10-16T08:11:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telemetry-mqtt_telegraf-1  | 2024-10-16T08:12:00Z W! [inputs.mqtt_consumer] Collection took longer than expected; not complete after interval of 10s
telemetry-mqtt_telegraf-1  | 2024-10-16T08:12:00Z D! [inputs.mqtt_consumer] Previous collection has not completed; scheduled collection skipped
telemetry-mqtt_telegraf-1  | 2024-10-16T08:12:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telemetry-mqtt_telegraf-1  | 2024-10-16T08:12:10Z W! [inputs.mqtt_consumer] Collection took longer than expected; not complete after interval of 10s
telemetry-mqtt_telegraf-1  | 2024-10-16T08:12:10Z D! [inputs.mqtt_consumer] Previous collection has not completed; scheduled collection skipped
telemetry-mqtt_telegraf-1  | 2024-10-16T08:12:10Z D! [inputs.mqtt_consumer] [client]  dial tcp 10.0.200.10:1883: i/o timeout
telemetry-mqtt_telegraf-1  | 2024-10-16T08:12:10Z D! [inputs.mqtt_consumer] [client]  failed to connect to broker, trying next
telemetry-mqtt_telegraf-1  | 2024-10-16T08:12:10Z D! [inputs.mqtt_consumer] [client]  Failed to connect to a broker
telemetry-mqtt_telegraf-1  | 2024-10-16T08:12:10Z D! [inputs.mqtt_consumer] [store]   memorystore closed
telemetry-mqtt_telegraf-1  | 2024-10-16T08:12:10Z E! [inputs.mqtt_consumer] Error in plugin: network Error : dial tcp 10.0.200.10:1883: i/o timeout
```

### System info

Telegraf-1.32.1 Ubuntu-20.04.3 LTS

### Docker

version: "3"
services:
  influxdb:
    image: influxdb:2.7.10 # influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=$KTS_TELEMETRY_INFLUXDB_USERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD=$KTS_TELEMETRY_INFLUXDB_PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG=$KTS_TELEMETRY_INFLUXDB_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET=$KTS_TELEMETRY_INFLUXDB_BUCKET
      - DOCKER_INFLUXDB_INIT_RETENTION=$KTS_TELEMETRY_INFLUXDB_RETENTION
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$KTS_TELEMETRY_INFLUXDB_TOKEN

  grafana:
    image: grafana/grafana:11.2.0 # grafana/grafana:latest
    environment:
      - GF_SERVER_ROOT_URL=http://192.168.1.97:3000/
      - GF_PLUGINS_ENABLE_ALPHA=true
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
    restart: always
    depends_on:
      - influxdb

  mqtt_telegraf:
    image: telegraf:1.32.1
    environment:
      - KTS_TELEMETRY_INFLUXDB_TOKEN=$KTS_TELEMETRY_INFLUXDB_TOKEN
      - KTS_TELEMETRY_INFLUXDB_ORG=$KTS_TELEMETRY_INFLUXDB_ORG
      - KTS_TELEMETRY_INFLUXDB_BUCKET=$KTS_TELEMETRY_INFLUXDB_BUCKET
      - KTS_INFLUXDB_HOST=influxdb:8086
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: always
    depends_on:
      - influxdb

volumes:
  influxdb-storage:
  grafana-storage:

### Steps to reproduce

1. Run the given docker-compose.
2. Run an MQTT server on another device on the network
3. Publish to /event/#, any message
4.  Disconnect the network.
5. Reboot the network connection

### Expected behavior

The telegraf instance should reconnect to the MQTT broker upon having network connectivity again and then begin producing data to insert into InfluxDB as normal.

### Actual behavior

Upon reconnection, a bunch of cached data is dumped to InfluxDB and shortly there after, no new data is ingested. If telegraf is rebooted, it reconnects normally and produces data. A reboot to telegraf should not be required. It does not notice that it's broken so a manual effort is require to realize data is not being ingested to InfluxDB and a manual forced restart needs to be triggered.

### Additional info

A more full version of the logs which did not fit here is located on gitst.
https://gist.github.com/mmachenry/59139541bbb628abff0c648d37eb41fb

### LINKED ISSUE #16293: MQTT consumer plugin disconnects frequently and can not reconnect successfully
### Relevant telegraf.conf

```toml
[[inputs.mqtt_consumer]]
topics = [
    "myTenant/#",
  ]
  data_format= "value"
  data_type= "string"

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "+/devices/+/+"
    measurement = "measurement/_/_/_"
    tags = "tenant/_/device/field"

[[processors.pivot]]
  order = 1
  tag_key = "field"
  value_key = "value"

[[processors.converter]]
  order = 2
  tagpass = { topic = ["myTenant*"] }
  [processors.converter.fields]
    float = ["temperature", "humidity"]
    integer = ["pressure", "rssi"]
```

### Logs from Telegraf

```text
2024-12-08T22:49:30Z D! [inputs.mqtt_consumer] [pinger]  ping check60.000303436
2024-12-08T22:49:30Z D! [inputs.mqtt_consumer] [pinger]  keepalive sending ping
2024-12-08T22:49:34Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
2024-12-08T22:49:35Z D! [inputs.mqtt_consumer] [pinger]  ping check4.9995263
2024-12-08T22:49:40Z D! [inputs.mqtt_consumer] [pinger]  ping check10.00021076
2024-12-08T22:49:40Z D! [inputs.mqtt_consumer] [pinger]  pingresp not received, disconnecting
2024-12-08T22:49:40Z D! [inputs.mqtt_consumer] [client]  internalConnLost called
2024-12-08T22:49:40Z D! [inputs.mqtt_consumer] [client]  stopCommsWorkers called
2024-12-08T22:49:40Z D! [inputs.mqtt_consumer] [client]  internalConnLost waiting on workers
2024-12-08T22:49:40Z D! [inputs.mqtt_consumer] [client]  stopCommsWorkers waiting for workers
2024-12-08T22:49:44Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] Connecting [tcp://127.0.0.1:1883]
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [client]  Connect()
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [store]   memorystore initialized
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [client]  about to write new connect msg
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [client]  socket connected to broker
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [client]  Using MQTT 3.1.1 protocol
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     connect started
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     received connack
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [client]  startCommsWorkers called
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [client]  client is connected/reconnected
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     incoming started
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     startIncomingComms started
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     outgoing started
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     startComms started
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [client]  startCommsWorkers done
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [store]   memorystore wiped
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [client]  exit startClient
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [pinger]  keepalive starting
2024-12-08T22:49:50Z I! [inputs.mqtt_consumer] Connected [tcp://127.0.0.1:1883]
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     outgoing waiting for an outbound message
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     logic waiting for msg on ibound
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: inboundFromStore complete
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     logic waiting for msg on ibound
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [client]  enter SubscribeMultiple
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [client]  sending subscribe message, topics:[topic1/# topic2/#]
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [client]  exit SubscribeMultiple
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     obound priority msg to write, type*packets.SubscribePacket
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     outgoing waiting for an outbound message
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     startIncoming Received Message
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: got msg on ibound
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [store]   memorystore del: message1not found
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: received suback, id:1
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: granted qoss[0 0]
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     logic waiting for msg on ibound
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     startIncoming Received Message
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     startIncoming Received Message
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: got msg on ibound
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: received publish, msgId:0
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     logic waiting for msg on ibound
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: got msg on ibound
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: received publish, msgId:0
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     startIncoming Received Message
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     logic waiting for msg on ibound
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: got msg on ibound
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: received publish, msgId:0
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     logic waiting for msg on ibound
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     startIncoming Received Message
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     startIncoming Received Message
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: got msg on ibound
2024-12-08T22:49:50Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: received publish, msgId:0
2024-12-08T22:49:54Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
2024-12-08T22:49:55Z D! [inputs.mqtt_consumer] [pinger]  ping check5.000816128
2024-12-08T22:50:00Z D! [inputs.mqtt_consumer] [pinger]  ping check10.000605322
2024-12-08T22:50:04Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
```
etc (goes on forever like this)

### System info

Telegraf 1.32.3 (git: HEAD@2fd5bf4f) on Debian 12 (bookworm)
* Bug introduced with Telegraf [v1.32.0](https://github.com/influxdata/telegraf/releases/tag/v1.32.0)
* Bug still present in Telegraf [v1.33.0](https://github.com/influxdata/telegraf/releases/tag/v1.33.0)

### Docker

not using docker

### Steps to reproduce

1. start mosquitto, influxdb and telegraf
2. publish some data

### Expected behavior

1. Data is read and transformed by telegraf and stored in influxdb
2. if connection to mosquitto is lost, telegraf reconnects and continues to process data

### Actual behavior

1. Data is read and transformed by telegraf and stored in influxdb
2. if connection to mosquitto is lost, telegraf reconnects successfully but fails to receive any data (including ping resp)

### LINKED ISSUE #17555: MQTT stops working after few minutes
### Relevant telegraf.conf

```toml
[[inputs.mqtt_consumer]]

  servers = ["${MQTT_BROKER}"]

  ## Topics that will be subscribed to.
  topics = [
    "ZGW16-IP/#",
  ]

  topic_tag = "topic"

  username = "${MQTT_USER}"
  password = "${MQTT_PASSWORD}"

  data_format = "xpath_json"

  [inputs.mqtt_consumer.tags]
   bucket = "MQTT"

    [[inputs.mqtt_consumer.topic_parsing]]
      topic = "ZGW16-IP/devices/+/+"
      measurement = "_/_/_/measurement"
      tags = "_/_/device/_"
 

    [[inputs.mqtt_consumer.xpath]]
      timestamp = "timestamp"
      timestamp_format = "2006-01-02T15:04:05Z0700"

      [inputs.mqtt_consumer.xpath.tags]
       unit = "unit"

      [inputs.mqtt_consumer.xpath.fields]
       value = "number(value)"
```

### Logs from Telegraf

```text
n/a
```

### System info

Proxmox, mqtt container

### Docker

_No response_

### Steps to reproduce

1. Disconnect the ethernet connection for an hour or so
2. Reconnect
3. MQTT is writing data but stops after a few seconds

If you disconnect ethernet for a short period of time, lets say, 1 or 2 Minutes the problem does not occur.
But longer disconnection time leads to problems.

### Expected behavior

n/a

### Actual behavior

n/a

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skartikey**
## Summary

Since v1.32.0, the MQTT consumer plugin failed to process messages after a network disconnection and reconnection. Three interrelated bugs caused this:

1. When Gather() called connect() on a network error, the context cancellation killed the delivery tracking goroutine permanently, preventing any further metric delivery.

2. The onConnectionLost() callback called Disconnect() on the client, which could race with a new client being created in Gather(), disconnecting the fresh connection.

3. Manual reconnection via Gather() conflicted with paho's built-in AutoReconnect, leading to duplicate clients and subscription issues.

The fix delegates all reconnection handling to paho's AutoReconnect mechanism and uses OnConnectHandler to re-subscribe after each reconnection. This eliminates the context cancellation bug, the race condition, and the manual reconnection complexity.

## Checklist

- [x] No AI generated code was used in this PR
- [ ] AI generated code used in this PR follows the [InfluxData Policy on AI-Generated Code Contributions][policy]

[policy]: https://www.influxdata.com/ai-generated-code-contributions-policy

## Related issues

resolves #16035
resolves #16293
resolves #17555

### CODE REVIEW

File: plugins/inputs/mqtt_consumer/mqtt_consumer.go [hunk 1]
```diff
@@ -147,79 +147,73 @@ func (m *MQTTConsumer) Start(acc telegraf.Accumulator) error {
 		}
 	}()
 
-	return m.connect()
+	if err := m.connect(); err != nil {
+		m.cancel()
+		m.cancel = nil
+		m.wg.Wait()
+		return err
+	}
```
Comment (srebhan) [inline plugins/inputs/mqtt_consumer/mqtt_consumer.go:153]: Shouldn't this call `m.Stop()`?

File: plugins/inputs/mqtt_consumer/mqtt_consumer.go [hunk 2]
```diff
@@ -147,79 +147,73 @@ func (m *MQTTConsumer) Start(acc telegraf.Accumulator) error {
...
-	// Persistent sessions should skip subscription if a session is present, as
-	// the subscriptions are stored by the server.
-	type sessionPresent interface {
-		SessionPresent() bool
-	}
-	if t, ok := token.(sessionPresent); ok && t.SessionPresent() {
-		m.Log.Debugf("Session found %v", m.Servers)
-		return nil
-	}
+func (m *MQTTConsumer) subscribe() {
```
Comment (srebhan) [inline plugins/inputs/mqtt_consumer/mqtt_consumer.go]: Can we please merge this into `onConnect`?

File: plugins/inputs/mqtt_consumer/mqtt_consumer.go [hunk 3]
```diff
@@ -147,79 +147,73 @@ func (m *MQTTConsumer) Start(acc telegraf.Accumulator) error {
...
 
-	// Persistent sessions should skip subscription if a session is present, as
-	// the subscriptions are stored by the server.
-	type sessionPresent interface {
-		SessionPresent() bool
-	}
-	if t, ok := token.(sessionPresent); ok && t.SessionPresent() {
-		m.Log.Debugf("Session found %v", m.Servers)
-		return nil
-	}
```
Comment (srebhan) [inline plugins/inputs/mqtt_consumer/mqtt_consumer.go:207]: Why is this deleted? Doesn't this break persisted sessions?

**Review by srebhan — COMMENTED** [review]
Thanks @skartikey! I have some comments...

Please also ask issue reporters to test this PR thoroughly!

File: plugins/inputs/mqtt_consumer/mqtt_consumer.go (hunk 3 above)
Comment (skartikey) [reply plugins/inputs/mqtt_consumer/mqtt_consumer.go:207]: It doesn't break persistent sessions. `SubscribeMultiple` is idempotent; the broker acknowledges the existing subscriptions without side effects.

The reason for removing the check is that the `OnConnect` callback signature is `func(mqtt.Client)`, it doesn't receive the connect token, so there's no way to check `SessionPresent()` inside `onConnect`. And we need `onConnect` to handle resubscription after auto-reconnect too.

With auto-reconnect, `onConnect` fires on every reconnection. For non-persistent (clean) sessions, the broker discards subscriptions on disconnect, so we must resubscribe. For persistent sessions, the broker
retains them, so resubscribing is redundant but harmless (one extra SUBSCRIBE packet round-trip).

The alternative would be to store the `SessionPresent` flag during the initial connection and conditionally skip the first subscribe, but that adds complexity for no real benefit since the call is idempotent.

Comment (srebhan) [reply plugins/inputs/mqtt_consumer/mqtt_consumer.go:207]: I fully agree. Thanks for your explanation!

File: plugins/inputs/mqtt_consumer/mqtt_consumer.go [hunk 4]
```diff
@@ -147,79 +147,67 @@ func (m *MQTTConsumer) Start(acc telegraf.Accumulator) error {
...
+	}
+	return nil
 }
 
-func (m *MQTTConsumer) Gather(_ telegraf.Accumulator) error {
-	if !m.client.IsConnected() {
-		m.Log.Debugf("Connecting %v", m.Servers)
-		return m.connect()
-	}
+func (*MQTTConsumer) Gather(_ telegraf.Accumulator) error {
```
Comment (srebhan) [inline plugins/inputs/mqtt_consumer/mqtt_consumer.go]:
```suggestion
func (*MQTTConsumer) Gather(telegraf.Accumulator) error {
```

File: plugins/inputs/mqtt_consumer/mqtt_consumer.go [hunk 5]
```diff
@@ -147,79 +147,67 @@ func (m *MQTTConsumer) Start(acc telegraf.Accumulator) error {
...
 	return nil
 }
 
 func (m *MQTTConsumer) Stop() {
-	if m.client.IsConnected() {
+	if m.client != nil {
```
Comment (srebhan) [inline plugins/inputs/mqtt_consumer/mqtt_consumer.go:162]: Are you sure you can call disconnect on an already disconnected client? If so, please add a small comment here stating that we can simply call disconnect as it does the right thing... Just want to be extra-sure! :-)

Comment (skartikey) [reply plugins/inputs/mqtt_consumer/mqtt_consumer.go:162]: That's correct, I have added the comment in the code.

**Comment by srebhan** [comment]
@skartikey it seems like there is a failing integration test for the MQTT consumer!

**Comment by skartikey** [comment]
@srebhan Found the issue in the integration test, `TestReconnectIntegration` polls `plugin.client.IsConnected()` to detect the connection loss after pausing the container. But with `SetAutoReconnect(true)` (the whole point of this PR), paho immediately tries to reconnect when it detects a disconnect. The `IsConnected()` flag flips back to `true` so fast that the 100ms polling interval never catches it in the `false` state, causing the 5-second `require.Eventually` to time out.

So, instead of polling `IsConnected()`, detect the disconnect by waiting for `onConnectionLost` to fire, which adds an error to the accumulator. This is a stable, one-shot event that doesn't get undone by auto-reconnect. Also increased the timeout from 5s to 10s to match the reconnect `Eventually` below, giving more headroom in slow CI environments.

**Comment by SofieF2005** [comment]
First try:
 1:

Telegraf: 1.30.1
Influxdb: 2.7.5

=> without any problems on reconnect.

2:

Telegraf: 1.37.2
Influxdb: 2.8.0

=> after long disconnect data will be written but only for a short period of time and then stops

3:

Telegraf: 1.38.0
Influxdb: 2.8.0

=> after short disconnect no problems like in "2". After long disconnect no data will be written after reconnect. Reboot is necessary to fix this.

will try again later.

**Comment by SofieF2005** [comment]
```
Mar 06 17:58:46 influxdbclone telegraf[158]: 2026-03-06T16:58:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 17:58:56 influxdbclone telegraf[158]: 2026-03-06T16:58:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 17:59:06 influxdbclone telegraf[158]: 2026-03-06T16:59:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 17:59:16 influxdbclone telegraf[158]: 2026-03-06T16:59:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 17:59:26 influxdbclone telegraf[158]: 2026-03-06T16:59:26Z E! [inputs.mqtt_consumer] Error in plugin: connection lost: pingresp not received, disconnecting
Mar 06 17:59:26 influxdbclone telegraf[158]: 2026-03-06T16:59:26Z D! [inputs.mqtt_consumer] Disconnected [tcp://192.168.1.12:1883]
Mar 06 17:59:26 influxdbclone telegraf[158]: 2026-03-06T16:59:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 17:59:36 influxdbclone telegraf[158]: 2026-03-06T16:59:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 17:59:46 influxdbclone telegraf[158]: 2026-03-06T16:59:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 17:59:56 influxdbclone telegraf[158]: 2026-03-06T16:59:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:00:06 influxdbclone telegraf[158]: 2026-03-06T17:00:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:00:16 influxdbclone telegraf[158]: 2026-03-06T17:00:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:00:26 influxdbclone telegraf[158]: 2026-03-06T17:00:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:00:36 influxdbclone telegraf[158]: 2026-03-06T17:00:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:00:46 influxdbclone telegraf[158]: 2026-03-06T17:00:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:00:56 influxdbclone telegraf[158]: 2026-03-06T17:00:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:01:06 influxdbclone telegraf[158]: 2026-03-06T17:01:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:01:16 influxdbclone telegraf[158]: 2026-03-06T17:01:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:01:26 influxdbclone telegraf[158]: 2026-03-06T17:01:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:01:36 influxdbclone telegraf[158]: 2026-03-06T17:01:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:01:46 influxdbclone telegraf[158]: 2026-03-06T17:01:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:01:56 influxdbclone telegraf[158]: 2026-03-06T17:01:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:02:06 influxdbclone telegraf[158]: 2026-03-06T17:02:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:02:16 influxdbclone telegraf[158]: 2026-03-06T17:02:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:02:26 influxdbclone telegraf[158]: 2026-03-06T17:02:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:02:36 influxdbclone telegraf[158]: 2026-03-06T17:02:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:02:46 influxdbclone telegraf[158]: 2026-03-06T17:02:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:02:56 influxdbclone telegraf[158]: 2026-03-06T17:02:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:03:06 influxdbclone telegraf[158]: 2026-03-06T17:03:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:03:16 influxdbclone telegraf[158]: 2026-03-06T17:03:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:03:26 influxdbclone telegraf[158]: 2026-03-06T17:03:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:03:36 influxdbclone telegraf[158]: 2026-03-06T17:03:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:03:46 influxdbclone telegraf[158]: 2026-03-06T17:03:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:03:56 influxdbclone telegraf[158]: 2026-03-06T17:03:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:04:06 influxdbclone telegraf[158]: 2026-03-06T17:04:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:04:16 influxdbclone telegraf[158]: 2026-03-06T17:04:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:04:26 influxdbclone telegraf[158]: 2026-03-06T17:04:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:04:36 influxdbclone telegraf[158]: 2026-03-06T17:04:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:04:46 influxdbclone telegraf[158]: 2026-03-06T17:04:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:04:56 influxdbclone telegraf[158]: 2026-03-06T17:04:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:05:06 influxdbclone telegraf[158]: 2026-03-06T17:05:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:05:16 influxdbclone telegraf[158]: 2026-03-06T17:05:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:05:26 influxdbclone telegraf[158]: 2026-03-06T17:05:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:05:36 influxdbclone telegraf[158]: 2026-03-06T17:05:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:05:46 influxdbclone telegraf[158]: 2026-03-06T17:05:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:05:56 influxdbclone telegraf[158]: 2026-03-06T17:05:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:06:06 influxdbclone telegraf[158]: 2026-03-06T17:06:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:06:16 influxdbclone telegraf[158]: 2026-03-06T17:06:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:06:26 influxdbclone telegraf[158]: 2026-03-06T17:06:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:06:36 influxdbclone telegraf[158]: 2026-03-06T17:06:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:06:46 influxdbclone telegraf[158]: 2026-03-06T17:06:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:06:56 influxdbclone telegraf[158]: 2026-03-06T17:06:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:07:06 influxdbclone telegraf[158]: 2026-03-06T17:07:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:07:16 influxdbclone telegraf[158]: 2026-03-06T17:07:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:07:26 influxdbclone telegraf[158]: 2026-03-06T17:07:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:07:36 influxdbclone telegraf[158]: 2026-03-06T17:07:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:07:46 influxdbclone telegraf[158]: 2026-03-06T17:07:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:07:56 influxdbclone telegraf[158]: 2026-03-06T17:07:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:08:06 influxdbclone telegraf[158]: 2026-03-06T17:08:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:08:16 influxdbclone telegraf[158]: 2026-03-06T17:08:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:08:26 influxdbclone telegraf[158]: 2026-03-06T17:08:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:08:36 influxdbclone telegraf[158]: 2026-03-06T17:08:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:08:46 influxdbclone telegraf[158]: 2026-03-06T17:08:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:08:56 influxdbclone telegraf[158]: 2026-03-06T17:08:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:09:06 influxdbclone telegraf[158]: 2026-03-06T17:09:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:09:16 influxdbclone telegraf[158]: 2026-03-06T17:09:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:09:26 influxdbclone telegraf[158]: 2026-03-06T17:09:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:09:36 influxdbclone telegraf[158]: 2026-03-06T17:09:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:09:46 influxdbclone telegraf[158]: 2026-03-06T17:09:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:09:56 influxdbclone telegraf[158]: 2026-03-06T17:09:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:10:06 influxdbclone telegraf[158]: 2026-03-06T17:10:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:10:16 influxdbclone telegraf[158]: 2026-03-06T17:10:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:10:26 influxdbclone telegraf[158]: 2026-03-06T17:10:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:10:36 influxdbclone telegraf[158]: 2026-03-06T17:10:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:10:46 influxdbclone telegraf[158]: 2026-03-06T17:10:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:10:56 influxdbclone telegraf[158]: 2026-03-06T17:10:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:11:06 influxdbclone telegraf[158]: 2026-03-06T17:11:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:11:16 influxdbclone telegraf[158]: 2026-03-06T17:11:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:11:26 influxdbclone telegraf[158]: 2026-03-06T17:11:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:11:36 influxdbclone telegraf[158]: 2026-03-06T17:11:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:11:46 influxdbclone telegraf[158]: 2026-03-06T17:11:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:11:56 influxdbclone telegraf[158]: 2026-03-06T17:11:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:12:06 influxdbclone telegraf[158]: 2026-03-06T17:12:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:12:16 influxdbclone telegraf[158]: 2026-03-06T17:12:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:12:26 influxdbclone telegraf[158]: 2026-03-06T17:12:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:12:36 influxdbclone telegraf[158]: 2026-03-06T17:12:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:12:46 influxdbclone telegraf[158]: 2026-03-06T17:12:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:12:56 influxdbclone telegraf[158]: 2026-03-06T17:12:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:13:06 influxdbclone telegraf[158]: 2026-03-06T17:13:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:13:16 influxdbclone telegraf[158]: 2026-03-06T17:13:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:13:26 influxdbclone telegraf[158]: 2026-03-06T17:13:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:13:36 influxdbclone telegraf[158]: 2026-03-06T17:13:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:13:46 influxdbclone telegraf[158]: 2026-03-06T17:13:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:13:56 influxdbclone telegraf[158]: 2026-03-06T17:13:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:14:06 influxdbclone telegraf[158]: 2026-03-06T17:14:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:14:16 influxdbclone telegraf[158]: 2026-03-06T17:14:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:14:26 influxdbclone telegraf[158]: 2026-03-06T17:14:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:14:36 influxdbclone telegraf[158]: 2026-03-06T17:14:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:14:46 influxdbclone telegraf[158]: 2026-03-06T17:14:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:14:56 influxdbclone telegraf[158]: 2026-03-06T17:14:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:15:06 influxdbclone telegraf[158]: 2026-03-06T17:15:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:15:16 influxdbclone telegraf[158]: 2026-03-06T17:15:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:15:26 influxdbclone telegraf[158]: 2026-03-06T17:15:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:15:36 influxdbclone telegraf[158]: 2026-03-06T17:15:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:15:46 influxdbclone telegraf[158]: 2026-03-06T17:15:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:15:56 influxdbclone telegraf[158]: 2026-03-06T17:15:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:16:06 influxdbclone telegraf[158]: 2026-03-06T17:16:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:16:16 influxdbclone telegraf[158]: 2026-03-06T17:16:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:16:26 influxdbclone telegraf[158]: 2026-03-06T17:16:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:16:36 influxdbclone telegraf[158]: 2026-03-06T17:16:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:16:46 influxdbclone telegraf[158]: 2026-03-06T17:16:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:16:56 influxdbclone telegraf[158]: 2026-03-06T17:16:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:17:06 influxdbclone telegraf[158]: 2026-03-06T17:17:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:17:16 influxdbclone telegraf[158]: 2026-03-06T17:17:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:17:26 influxdbclone telegraf[158]: 2026-03-06T17:17:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:17:36 influxdbclone telegraf[158]: 2026-03-06T17:17:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:17:46 influxdbclone telegraf[158]: 2026-03-06T17:17:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:17:56 influxdbclone telegraf[158]: 2026-03-06T17:17:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:18:06 influxdbclone telegraf[158]: 2026-03-06T17:18:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:18:16 influxdbclone telegraf[158]: 2026-03-06T17:18:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:18:26 influxdbclone telegraf[158]: 2026-03-06T17:18:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:18:36 influxdbclone telegraf[158]: 2026-03-06T17:18:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:18:46 influxdbclone telegraf[158]: 2026-03-06T17:18:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:18:56 influxdbclone telegraf[158]: 2026-03-06T17:18:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:19:06 influxdbclone telegraf[158]: 2026-03-06T17:19:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:19:16 influxdbclone telegraf[158]: 2026-03-06T17:19:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:19:26 influxdbclone telegraf[158]: 2026-03-06T17:19:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:19:36 influxdbclone telegraf[158]: 2026-03-06T17:19:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:19:46 influxdbclone telegraf[158]: 2026-03-06T17:19:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:19:56 influxdbclone telegraf[158]: 2026-03-06T17:19:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:20:06 influxdbclone telegraf[158]: 2026-03-06T17:20:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:20:16 influxdbclone telegraf[158]: 2026-03-06T17:20:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:20:26 influxdbclone telegraf[158]: 2026-03-06T17:20:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:20:36 influxdbclone telegraf[158]: 2026-03-06T17:20:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:20:46 influxdbclone telegraf[158]: 2026-03-06T17:20:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:20:56 influxdbclone telegraf[158]: 2026-03-06T17:20:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:21:06 influxdbclone telegraf[158]: 2026-03-06T17:21:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:21:16 influxdbclone telegraf[158]: 2026-03-06T17:21:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:21:26 influxdbclone telegraf[158]: 2026-03-06T17:21:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:21:36 influxdbclone telegraf[158]: 2026-03-06T17:21:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:21:46 influxdbclone telegraf[158]: 2026-03-06T17:21:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:21:56 influxdbclone telegraf[158]: 2026-03-06T17:21:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:22:06 influxdbclone telegraf[158]: 2026-03-06T17:22:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:22:16 influxdbclone telegraf[158]: 2026-03-06T17:22:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:22:26 influxdbclone telegraf[158]: 2026-03-06T17:22:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:22:36 influxdbclone telegraf[158]: 2026-03-06T17:22:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:22:46 influxdbclone telegraf[158]: 2026-03-06T17:22:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:22:56 influxdbclone telegraf[158]: 2026-03-06T17:22:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:23:06 influxdbclone telegraf[158]: 2026-03-06T17:23:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:23:16 influxdbclone telegraf[158]: 2026-03-06T17:23:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:23:26 influxdbclone telegraf[158]: 2026-03-06T17:23:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:23:36 influxdbclone telegraf[158]: 2026-03-06T17:23:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:23:46 influxdbclone telegraf[158]: 2026-03-06T17:23:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:23:56 influxdbclone telegraf[158]: 2026-03-06T17:23:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:24:06 influxdbclone telegraf[158]: 2026-03-06T17:24:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:24:16 influxdbclone telegraf[158]: 2026-03-06T17:24:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:24:26 influxdbclone telegraf[158]: 2026-03-06T17:24:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:24:36 influxdbclone telegraf[158]: 2026-03-06T17:24:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:24:46 influxdbclone telegraf[158]: 2026-03-06T17:24:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:24:56 influxdbclone telegraf[158]: 2026-03-06T17:24:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:25:06 influxdbclone telegraf[158]: 2026-03-06T17:25:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:25:16 influxdbclone telegraf[158]: 2026-03-06T17:25:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:25:26 influxdbclone telegraf[158]: 2026-03-06T17:25:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:25:36 influxdbclone telegraf[158]: 2026-03-06T17:25:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:25:46 influxdbclone telegraf[158]: 2026-03-06T17:25:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:25:56 influxdbclone telegraf[158]: 2026-03-06T17:25:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:26:06 influxdbclone telegraf[158]: 2026-03-06T17:26:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:26:16 influxdbclone telegraf[158]: 2026-03-06T17:26:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:26:26 influxdbclone telegraf[158]: 2026-03-06T17:26:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:26:36 influxdbclone telegraf[158]: 2026-03-06T17:26:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:26:46 influxdbclone telegraf[158]: 2026-03-06T17:26:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:26:56 influxdbclone telegraf[158]: 2026-03-06T17:26:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:27:06 influxdbclone telegraf[158]: 2026-03-06T17:27:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:27:16 influxdbclone telegraf[158]: 2026-03-06T17:27:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:27:26 influxdbclone telegraf[158]: 2026-03-06T17:27:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:27:36 influxdbclone telegraf[158]: 2026-03-06T17:27:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:27:46 influxdbclone telegraf[158]: 2026-03-06T17:27:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:27:56 influxdbclone telegraf[158]: 2026-03-06T17:27:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:28:06 influxdbclone telegraf[158]: 2026-03-06T17:28:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:28:16 influxdbclone telegraf[158]: 2026-03-06T17:28:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:28:26 influxdbclone telegraf[158]: 2026-03-06T17:28:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:28:36 influxdbclone telegraf[158]: 2026-03-06T17:28:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:28:46 influxdbclone telegraf[158]: 2026-03-06T17:28:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:28:56 influxdbclone telegraf[158]: 2026-03-06T17:28:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:29:06 influxdbclone telegraf[158]: 2026-03-06T17:29:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:29:16 influxdbclone telegraf[158]: 2026-03-06T17:29:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:29:26 influxdbclone telegraf[158]: 2026-03-06T17:29:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:29:36 influxdbclone telegraf[158]: 2026-03-06T17:29:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:29:46 influxdbclone telegraf[158]: 2026-03-06T17:29:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:29:56 influxdbclone telegraf[158]: 2026-03-06T17:29:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:30:06 influxdbclone telegraf[158]: 2026-03-06T17:30:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:30:16 influxdbclone telegraf[158]: 2026-03-06T17:30:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:30:26 influxdbclone telegraf[158]: 2026-03-06T17:30:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:30:36 influxdbclone telegraf[158]: 2026-03-06T17:30:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:30:46 influxdbclone telegraf[158]: 2026-03-06T17:30:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:30:56 influxdbclone telegraf[158]: 2026-03-06T17:30:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:31:06 influxdbclone telegraf[158]: 2026-03-06T17:31:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:31:16 influxdbclone telegraf[158]: 2026-03-06T17:31:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:31:26 influxdbclone telegraf[158]: 2026-03-06T17:31:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:31:36 influxdbclone telegraf[158]: 2026-03-06T17:31:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:31:46 influxdbclone telegraf[158]: 2026-03-06T17:31:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:31:56 influxdbclone telegraf[158]: 2026-03-06T17:31:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:32:06 influxdbclone telegraf[158]: 2026-03-06T17:32:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:32:16 influxdbclone telegraf[158]: 2026-03-06T17:32:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:32:26 influxdbclone telegraf[158]: 2026-03-06T17:32:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:32:36 influxdbclone telegraf[158]: 2026-03-06T17:32:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:32:46 influxdbclone telegraf[158]: 2026-03-06T17:32:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:32:56 influxdbclone telegraf[158]: 2026-03-06T17:32:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:33:06 influxdbclone telegraf[158]: 2026-03-06T17:33:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:33:16 influxdbclone telegraf[158]: 2026-03-06T17:33:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:33:26 influxdbclone telegraf[158]: 2026-03-06T17:33:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:33:36 influxdbclone telegraf[158]: 2026-03-06T17:33:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:33:46 influxdbclone telegraf[158]: 2026-03-06T17:33:46Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:33:56 influxdbclone telegraf[158]: 2026-03-06T17:33:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:34:06 influxdbclone telegraf[158]: 2026-03-06T17:34:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:34:16 influxdbclone telegraf[158]: 2026-03-06T17:34:16Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:34:26 influxdbclone telegraf[158]: 2026-03-06T17:34:26Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 06 18:34:36 influxdbclone telegraf[158]: 2026-03-06T17:34:36Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
```

Reconnect at 18:32. 

Maybe has something to do with the error at 17:59

**Comment by SofieF2005** [comment]
```
Mar 06 18:36:55 influxdbclone telegraf[158]: 2026-03-06T17:36:55Z I! [inputs.mqtt_consumer] Connected [tcp://192.168.1.12:1883]
Mar 06 18:36:55 influxdbclone telegraf[158]: 2026-03-06T17:36:55Z E! [inputs.mqtt_consumer] Error in plugin: invalid character 'o' looking for beginning of value
Mar 06 18:36:55 influxdbclone telegraf[158]: 2026-03-06T17:36:55Z D! [parsers.xpath_json::mqtt_consumer] Number of configs: 1
Mar 06 18:36:55 influxdbclone telegraf[158]: 2026-03-06T17:36:55Z D! [parsers.xpath_json::mqtt_consumer] Number of selected metric nodes: 1
Mar 06 18:36:55 influxdbclone telegraf[158]: 2026-03-06T17:36:55Z D! [parsers.xpath_json::mqtt_consumer] Number of configs: 1
Mar 06 18:36:55 influxdbclone telegraf[158]: 2026-03-06T17:36:55Z D! [parsers.xpath_json::mqtt_consumer] Number of selected metric nodes: 1
Mar 06 18:36:55 influxdbclone telegraf[158]: 2026-03-06T17:36:55Z D! [parsers.xpath_json::mqtt_consumer] Number of configs: 1
Mar 06 18:36:55 influxdbclone telegraf[158]: 2026-03-06T17:36:55Z D! [parsers.xpath_json::mqtt_consumer] Number of selected metric nodes: 1
Mar 06 18:36:55 influxdbclone telegraf[158]: 2026-03-06T17:36:55Z D! [parsers.xpath_json::mqtt_consumer] Number of configs: 1
Mar 06 18:36:55 influxdbclone telegraf[158]: 2026-03-06T17:36:55Z D! [parsers.xpath_json::mqtt_consumer] Number of selected metric nodes: 1
Mar 06 18:36:55 influxdbclone telegraf[158]: 2026-03-06T17:36:55Z D! [parsers.xpath_json::mqtt_consumer] Number of configs: 1
Mar 06 18:36:55 influxdbclone telegraf[158]: 2026-03-06T17:36:55Z D! [parsers.xpath_json::mqtt_consumer] Number of selected metric nodes: 1
Mar 06 18:36:55 influxdbclone telegraf[158]: 2026-03-06T17:36:55Z D! [parsers.xpath_json::mqtt_consumer] Number of configs: 1
Mar 06 18:36:55 influxdbclone telegraf[158]: 2026-03-06T17:36:55Z D! [parsers.xpath_json::mqtt_consumer] Number of selected metric nodes: 1
```

Well this is strange.

at 18:36, 4 minutes after Reconnect, there is again data beeing written to influxdb.

But in the first attempt I was waiting for 1-2h after reconnect and nothing happen..

**Comment by skartikey** [comment]
@SofieF2005 Thank you so much for testing this with the PR build and sharing those detailed logs, this is incredibly helpful!                                                                                   
                                                                                                                                                                                                                   
  From the logs, it looks like paho's auto-reconnect never successfully re-establishes the connection after a long disconnect (we never see a "Connected" log after the disconnect at 17:59:26). To understand what's happening internally during the reconnection attempts, could you enable `client_trace` in your mqtt_consumer config and reproduce the issue?                                                                
                  
```
  [[inputs.mqtt_consumer]]                                                                                                                                                                                         
    client_trace = true                                                                                                                                                                                            
    # ... rest of your config      
```                                                                                                                                                                                
                                                                                                                                                                                                                   
  This will enable paho's internal debug logging so we can see the reconnection attempts, backoff timing, and where exactly it gets stuck. Could you share the full log output (from before the disconnect through to when it should have reconnected) with this enabled?

**Comment by SofieF2005** [comment]
Disconnect at ~01:47:25

```
Mar 07 01:47:25 influxdbclone telegraf[154]: 2026-03-07T00:47:25Z D! [inputs.mqtt_consumer] [net]     startIncoming Received Message
Mar 07 01:47:25 influxdbclone telegraf[154]: 2026-03-07T00:47:25Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: got msg on ibound
Mar 07 01:47:25 influxdbclone telegraf[154]: 2026-03-07T00:47:25Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: received publish, msgId:0
Mar 07 01:47:25 influxdbclone telegraf[154]: 2026-03-07T00:47:25Z D! [inputs.mqtt_consumer] [net]     logic waiting for msg on ibound
Mar 07 01:47:25 influxdbclone telegraf[154]: 2026-03-07T00:47:25Z D! [parsers.xpath_json::mqtt_consumer] Number of configs: 1
Mar 07 01:47:25 influxdbclone telegraf[154]: 2026-03-07T00:47:25Z D! [parsers.xpath_json::mqtt_consumer] Number of selected metric nodes: 1
Mar 07 01:47:25 influxdbclone telegraf[154]: 2026-03-07T00:47:25Z D! [inputs.mqtt_consumer] [net]     startIncoming Received Message
Mar 07 01:47:25 influxdbclone telegraf[154]: 2026-03-07T00:47:25Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: got msg on ibound
Mar 07 01:47:25 influxdbclone telegraf[154]: 2026-03-07T00:47:25Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: received publish, msgId:0
Mar 07 01:47:25 influxdbclone telegraf[154]: 2026-03-07T00:47:25Z D! [inputs.mqtt_consumer] [net]     logic waiting for msg on ibound
Mar 07 01:47:25 influxdbclone telegraf[154]: 2026-03-07T00:47:25Z D! [parsers.xpath_json::mqtt_consumer] Number of configs: 1
Mar 07 01:47:25 influxdbclone telegraf[154]: 2026-03-07T00:47:25Z D! [parsers.xpath_json::mqtt_consumer] Number of selected metric nodes: 1
Mar 07 01:47:25 influxdbclone telegraf[154]: 2026-03-07T00:47:25Z D! [inputs.mqtt_consumer] [net]     startIncoming Received Message
Mar 07 01:47:25 influxdbclone telegraf[154]: 2026-03-07T00:47:25Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: got msg on ibound
Mar 07 01:47:25 influxdbclone telegraf[154]: 2026-03-07T00:47:25Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: received publish, msgId:0
Mar 07 01:47:25 influxdbclone telegraf[154]: 2026-03-07T00:47:25Z D! [inputs.mqtt_consumer] [net]     logic waiting for msg on ibound
Mar 07 01:47:25 influxdbclone telegraf[154]: 2026-03-07T00:47:25Z D! [parsers.xpath_json::mqtt_consumer] Number of configs: 1
Mar 07 01:47:25 influxdbclone telegraf[154]: 2026-03-07T00:47:25Z D! [parsers.xpath_json::mqtt_consumer] Number of selected metric nodes: 1
Mar 07 01:47:26 influxdbclone telegraf[154]: 2026-03-07T00:47:26Z D! [inputs.mqtt_consumer] [pinger]  ping check34.996614699
Mar 07 01:47:31 influxdbclone telegraf[154]: 2026-03-07T00:47:31Z D! [inputs.mqtt_consumer] [pinger]  ping check39.997002763
Mar 07 01:47:31 influxdbclone telegraf[154]: 2026-03-07T00:47:31Z D! [outputs.influxdb_v2] Wrote batch of 19 metrics in 4.150677ms
Mar 07 01:47:31 influxdbclone telegraf[154]: 2026-03-07T00:47:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:47:36 influxdbclone telegraf[154]: 2026-03-07T00:47:36Z D! [inputs.mqtt_consumer] [pinger]  ping check44.997431687
Mar 07 01:47:41 influxdbclone telegraf[154]: 2026-03-07T00:47:41Z D! [inputs.mqtt_consumer] [pinger]  ping check49.997078161
Mar 07 01:47:41 influxdbclone telegraf[154]: 2026-03-07T00:47:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:47:46 influxdbclone telegraf[154]: 2026-03-07T00:47:46Z D! [inputs.mqtt_consumer] [pinger]  ping check54.997000351
Mar 07 01:47:51 influxdbclone telegraf[154]: 2026-03-07T00:47:51Z D! [inputs.mqtt_consumer] [pinger]  ping check59.996998026
Mar 07 01:47:51 influxdbclone telegraf[154]: 2026-03-07T00:47:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:47:56 influxdbclone telegraf[154]: 2026-03-07T00:47:56Z D! [inputs.mqtt_consumer] [pinger]  ping check64.997078647
Mar 07 01:47:56 influxdbclone telegraf[154]: 2026-03-07T00:47:56Z D! [inputs.mqtt_consumer] [pinger]  keepalive sending ping
Mar 07 01:48:01 influxdbclone telegraf[154]: 2026-03-07T00:48:01Z D! [inputs.mqtt_consumer] [pinger]  ping check4.999849034
Mar 07 01:48:01 influxdbclone telegraf[154]: 2026-03-07T00:48:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:48:06 influxdbclone telegraf[154]: 2026-03-07T00:48:06Z D! [inputs.mqtt_consumer] [pinger]  ping check9.999683167
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [pinger]  ping check15.000312471
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [pinger]  pingresp not received, disconnecting
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [client]  internalConnLost called
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [client]  stopCommsWorkers called
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [net]     incoming complete
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: ibound complete
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [net]     startIncomingComms goroutine complete
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [router]  matchAndDispatch exiting
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [client]  startCommsWorkers output redirector finished
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [client]  internalConnLost waiting on workers
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [net]     outgoing waiting for an outbound message
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [net]     outgoing waiting for an outbound message
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [net]     outgoing waiting for an outbound message
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [net]     outgoing comms stopping
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [net]     startComms closing outError
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [client]  incoming comms goroutine done
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [client]  stopCommsWorkers waiting for workers
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [client]  stopCommsWorkers waiting for comms
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [client]  stopCommsWorkers done
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [client]  internalConnLost workers stopped
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [msgids]  cleaned up subs
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [client]  internalConnLost complete
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z E! [inputs.mqtt_consumer] Error in plugin: connection lost: pingresp not received, disconnecting
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] Disconnected [tcp://192.168.1.12:1883]
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [client]  enter reconnect
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [inputs.mqtt_consumer] [client]  about to write new connect msg
Mar 07 01:48:11 influxdbclone telegraf[154]: 2026-03-07T00:48:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:48:13 influxdbclone telegraf[154]: 2026-03-07T00:48:13Z D! [inputs.mqtt_consumer] [client]  dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 01:48:13 influxdbclone telegraf[154]: 2026-03-07T00:48:13Z D! [inputs.mqtt_consumer] [client]  failed to connect to broker, trying next
Mar 07 01:48:14 influxdbclone telegraf[154]: 2026-03-07T00:48:14Z D! [inputs.mqtt_consumer] [client]  Reconnect failed, slept for1seconds:network Error : dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 01:48:14 influxdbclone telegraf[154]: 2026-03-07T00:48:14Z D! [inputs.mqtt_consumer] [client]  about to write new connect msg
Mar 07 01:48:17 influxdbclone telegraf[154]: 2026-03-07T00:48:17Z D! [inputs.mqtt_consumer] [client]  dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 01:48:17 influxdbclone telegraf[154]: 2026-03-07T00:48:17Z D! [inputs.mqtt_consumer] [client]  failed to connect to broker, trying next
Mar 07 01:48:19 influxdbclone telegraf[154]: 2026-03-07T00:48:19Z D! [inputs.mqtt_consumer] [client]  Reconnect failed, slept for2seconds:network Error : dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 01:48:19 influxdbclone telegraf[154]: 2026-03-07T00:48:19Z D! [inputs.mqtt_consumer] [client]  about to write new connect msg
Mar 07 01:48:20 influxdbclone telegraf[154]: 2026-03-07T00:48:20Z D! [inputs.mqtt_consumer] [client]  dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 01:48:20 influxdbclone telegraf[154]: 2026-03-07T00:48:20Z D! [inputs.mqtt_consumer] [client]  failed to connect to broker, trying next
Mar 07 01:48:21 influxdbclone telegraf[154]: 2026-03-07T00:48:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:48:24 influxdbclone telegraf[154]: 2026-03-07T00:48:24Z D! [inputs.mqtt_consumer] [client]  Reconnect failed, slept for4seconds:network Error : dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 01:48:24 influxdbclone telegraf[154]: 2026-03-07T00:48:24Z D! [inputs.mqtt_consumer] [client]  about to write new connect msg
Mar 07 01:48:26 influxdbclone telegraf[154]: 2026-03-07T00:48:26Z D! [inputs.mqtt_consumer] [client]  dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 01:48:26 influxdbclone telegraf[154]: 2026-03-07T00:48:26Z D! [inputs.mqtt_consumer] [client]  failed to connect to broker, trying next
Mar 07 01:48:31 influxdbclone telegraf[154]: 2026-03-07T00:48:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:48:34 influxdbclone telegraf[154]: 2026-03-07T00:48:34Z D! [inputs.mqtt_consumer] [client]  Reconnect failed, slept for8seconds:network Error : dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 01:48:34 influxdbclone telegraf[154]: 2026-03-07T00:48:34Z D! [inputs.mqtt_consumer] [client]  about to write new connect msg
Mar 07 01:48:35 influxdbclone telegraf[154]: 2026-03-07T00:48:35Z D! [inputs.mqtt_consumer] [client]  dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 01:48:35 influxdbclone telegraf[154]: 2026-03-07T00:48:35Z D! [inputs.mqtt_consumer] [client]  failed to connect to broker, trying next
Mar 07 01:48:41 influxdbclone telegraf[154]: 2026-03-07T00:48:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:48:51 influxdbclone telegraf[154]: 2026-03-07T00:48:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:48:51 influxdbclone telegraf[154]: 2026-03-07T00:48:51Z D! [inputs.mqtt_consumer] [client]  Reconnect failed, slept for16seconds:network Error : dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 01:48:51 influxdbclone telegraf[154]: 2026-03-07T00:48:51Z D! [inputs.mqtt_consumer] [client]  about to write new connect msg
Mar 07 01:48:53 influxdbclone telegraf[154]: 2026-03-07T00:48:53Z D! [inputs.mqtt_consumer] [client]  dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 01:48:53 influxdbclone telegraf[154]: 2026-03-07T00:48:53Z D! [inputs.mqtt_consumer] [client]  failed to connect to broker, trying next
Mar 07 01:49:01 influxdbclone telegraf[154]: 2026-03-07T00:49:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:49:11 influxdbclone telegraf[154]: 2026-03-07T00:49:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:49:21 influxdbclone telegraf[154]: 2026-03-07T00:49:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:49:25 influxdbclone telegraf[154]: 2026-03-07T00:49:25Z D! [inputs.mqtt_consumer] [client]  Reconnect failed, slept for32seconds:network Error : dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 01:49:25 influxdbclone telegraf[154]: 2026-03-07T00:49:25Z D! [inputs.mqtt_consumer] [client]  about to write new connect msg
Mar 07 01:49:27 influxdbclone telegraf[154]: 2026-03-07T00:49:27Z D! [inputs.mqtt_consumer] [client]  dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 01:49:27 influxdbclone telegraf[154]: 2026-03-07T00:49:27Z D! [inputs.mqtt_consumer] [client]  failed to connect to broker, trying next
Mar 07 01:49:31 influxdbclone telegraf[154]: 2026-03-07T00:49:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:49:41 influxdbclone telegraf[154]: 2026-03-07T00:49:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:49:51 influxdbclone telegraf[154]: 2026-03-07T00:49:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:50:01 influxdbclone telegraf[154]: 2026-03-07T00:50:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:50:11 influxdbclone telegraf[154]: 2026-03-07T00:50:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:50:21 influxdbclone telegraf[154]: 2026-03-07T00:50:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:50:31 influxdbclone telegraf[154]: 2026-03-07T00:50:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:50:31 influxdbclone telegraf[154]: 2026-03-07T00:50:31Z D! [inputs.mqtt_consumer] [client]  Reconnect failed, slept for64seconds:network Error : dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 01:50:31 influxdbclone telegraf[154]: 2026-03-07T00:50:31Z D! [inputs.mqtt_consumer] [client]  about to write new connect msg
Mar 07 01:50:34 influxdbclone telegraf[154]: 2026-03-07T00:50:34Z D! [inputs.mqtt_consumer] [client]  dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 01:50:34 influxdbclone telegraf[154]: 2026-03-07T00:50:34Z D! [inputs.mqtt_consumer] [client]  failed to connect to broker, trying next
Mar 07 01:50:41 influxdbclone telegraf[154]: 2026-03-07T00:50:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:50:51 influxdbclone telegraf[154]: 2026-03-07T00:50:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:51:01 influxdbclone telegraf[154]: 2026-03-07T00:51:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:51:11 influxdbclone telegraf[154]: 2026-03-07T00:51:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:51:21 influxdbclone telegraf[154]: 2026-03-07T00:51:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:51:31 influxdbclone telegraf[154]: 2026-03-07T00:51:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:51:41 influxdbclone telegraf[154]: 2026-03-07T00:51:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:51:51 influxdbclone telegraf[154]: 2026-03-07T00:51:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:52:01 influxdbclone telegraf[154]: 2026-03-07T00:52:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:52:11 influxdbclone telegraf[154]: 2026-03-07T00:52:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:52:21 influxdbclone telegraf[154]: 2026-03-07T00:52:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:52:31 influxdbclone telegraf[154]: 2026-03-07T00:52:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:52:41 influxdbclone telegraf[154]: 2026-03-07T00:52:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:52:42 influxdbclone telegraf[154]: 2026-03-07T00:52:42Z D! [inputs.mqtt_consumer] [client]  Reconnect failed, slept for128seconds:network Error : dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 01:52:42 influxdbclone telegraf[154]: 2026-03-07T00:52:42Z D! [inputs.mqtt_consumer] [client]  about to write new connect msg
Mar 07 01:52:45 influxdbclone telegraf[154]: 2026-03-07T00:52:45Z D! [inputs.mqtt_consumer] [client]  dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 01:52:45 influxdbclone telegraf[154]: 2026-03-07T00:52:45Z D! [inputs.mqtt_consumer] [client]  failed to connect to broker, trying next
Mar 07 01:52:51 influxdbclone telegraf[154]: 2026-03-07T00:52:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:53:01 influxdbclone telegraf[154]: 2026-03-07T00:53:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:53:11 influxdbclone telegraf[154]: 2026-03-07T00:53:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:53:21 influxdbclone telegraf[154]: 2026-03-07T00:53:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:53:31 influxdbclone telegraf[154]: 2026-03-07T00:53:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:53:41 influxdbclone telegraf[154]: 2026-03-07T00:53:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:53:51 influxdbclone telegraf[154]: 2026-03-07T00:53:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:54:01 influxdbclone telegraf[154]: 2026-03-07T00:54:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:54:11 influxdbclone telegraf[154]: 2026-03-07T00:54:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:54:21 influxdbclone telegraf[154]: 2026-03-07T00:54:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:54:31 influxdbclone telegraf[154]: 2026-03-07T00:54:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:54:41 influxdbclone telegraf[154]: 2026-03-07T00:54:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:54:51 influxdbclone telegraf[154]: 2026-03-07T00:54:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:55:01 influxdbclone telegraf[154]: 2026-03-07T00:55:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:55:11 influxdbclone telegraf[154]: 2026-03-07T00:55:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:55:21 influxdbclone telegraf[154]: 2026-03-07T00:55:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:55:31 influxdbclone telegraf[154]: 2026-03-07T00:55:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:55:41 influxdbclone telegraf[154]: 2026-03-07T00:55:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:55:51 influxdbclone telegraf[154]: 2026-03-07T00:55:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:56:01 influxdbclone telegraf[154]: 2026-03-07T00:56:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:56:11 influxdbclone telegraf[154]: 2026-03-07T00:56:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:56:21 influxdbclone telegraf[154]: 2026-03-07T00:56:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:56:31 influxdbclone telegraf[154]: 2026-03-07T00:56:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:56:41 influxdbclone telegraf[154]: 2026-03-07T00:56:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:56:51 influxdbclone telegraf[154]: 2026-03-07T00:56:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:57:01 influxdbclone telegraf[154]: 2026-03-07T00:57:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:57:01 influxdbclone telegraf[154]: 2026-03-07T00:57:01Z D! [inputs.mqtt_consumer] [client]  Reconnect failed, slept for256seconds:network Error : dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 01:57:01 influxdbclone telegraf[154]: 2026-03-07T00:57:01Z D! [inputs.mqtt_consumer] [client]  about to write new connect msg
Mar 07 01:57:04 influxdbclone telegraf[154]: 2026-03-07T00:57:04Z D! [inputs.mqtt_consumer] [client]  dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 01:57:04 influxdbclone telegraf[154]: 2026-03-07T00:57:04Z D! [inputs.mqtt_consumer] [client]  failed to connect to broker, trying next
Mar 07 01:57:11 influxdbclone telegraf[154]: 2026-03-07T00:57:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:57:21 influxdbclone telegraf[154]: 2026-03-07T00:57:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:57:31 influxdbclone telegraf[154]: 2026-03-07T00:57:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:57:41 influxdbclone telegraf[154]: 2026-03-07T00:57:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:57:51 influxdbclone telegraf[154]: 2026-03-07T00:57:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:58:01 influxdbclone telegraf[154]: 2026-03-07T00:58:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:58:11 influxdbclone telegraf[154]: 2026-03-07T00:58:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:58:21 influxdbclone telegraf[154]: 2026-03-07T00:58:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:58:31 influxdbclone telegraf[154]: 2026-03-07T00:58:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:58:41 influxdbclone telegraf[154]: 2026-03-07T00:58:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:58:51 influxdbclone telegraf[154]: 2026-03-07T00:58:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:59:01 influxdbclone telegraf[154]: 2026-03-07T00:59:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:59:11 influxdbclone telegraf[154]: 2026-03-07T00:59:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:59:21 influxdbclone telegraf[154]: 2026-03-07T00:59:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:59:31 influxdbclone telegraf[154]: 2026-03-07T00:59:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:59:41 influxdbclone telegraf[154]: 2026-03-07T00:59:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 01:59:51 influxdbclone telegraf[154]: 2026-03-07T00:59:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:00:01 influxdbclone telegraf[154]: 2026-03-07T01:00:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:00:11 influxdbclone telegraf[154]: 2026-03-07T01:00:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:00:21 influxdbclone telegraf[154]: 2026-03-07T01:00:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:00:31 influxdbclone telegraf[154]: 2026-03-07T01:00:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:00:41 influxdbclone telegraf[154]: 2026-03-07T01:00:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:00:51 influxdbclone telegraf[154]: 2026-03-07T01:00:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:01:01 influxdbclone telegraf[154]: 2026-03-07T01:01:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:01:11 influxdbclone telegraf[154]: 2026-03-07T01:01:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:01:21 influxdbclone telegraf[154]: 2026-03-07T01:01:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:01:31 influxdbclone telegraf[154]: 2026-03-07T01:01:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:01:41 influxdbclone telegraf[154]: 2026-03-07T01:01:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:01:51 influxdbclone telegraf[154]: 2026-03-07T01:01:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:02:01 influxdbclone telegraf[154]: 2026-03-07T01:02:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:02:11 influxdbclone telegraf[154]: 2026-03-07T01:02:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:02:21 influxdbclone telegraf[154]: 2026-03-07T01:02:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:02:31 influxdbclone telegraf[154]: 2026-03-07T01:02:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:02:41 influxdbclone telegraf[154]: 2026-03-07T01:02:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:02:51 influxdbclone telegraf[154]: 2026-03-07T01:02:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:03:01 influxdbclone telegraf[154]: 2026-03-07T01:03:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:03:11 influxdbclone telegraf[154]: 2026-03-07T01:03:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:03:21 influxdbclone telegraf[154]: 2026-03-07T01:03:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:03:31 influxdbclone telegraf[154]: 2026-03-07T01:03:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:03:41 influxdbclone telegraf[154]: 2026-03-07T01:03:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:03:51 influxdbclone telegraf[154]: 2026-03-07T01:03:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:04:01 influxdbclone telegraf[154]: 2026-03-07T01:04:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:04:11 influxdbclone telegraf[154]: 2026-03-07T01:04:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:04:21 influxdbclone telegraf[154]: 2026-03-07T01:04:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:04:31 influxdbclone telegraf[154]: 2026-03-07T01:04:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:04:41 influxdbclone telegraf[154]: 2026-03-07T01:04:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:04:51 influxdbclone telegraf[154]: 2026-03-07T01:04:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:05:01 influxdbclone telegraf[154]: 2026-03-07T01:05:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:05:11 influxdbclone telegraf[154]: 2026-03-07T01:05:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:05:21 influxdbclone telegraf[154]: 2026-03-07T01:05:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:05:31 influxdbclone telegraf[154]: 2026-03-07T01:05:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:05:36 influxdbclone telegraf[154]: 2026-03-07T01:05:36Z D! [inputs.mqtt_consumer] [client]  Reconnect failed, slept for512seconds:network Error : dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 02:05:36 influxdbclone telegraf[154]: 2026-03-07T01:05:36Z D! [inputs.mqtt_consumer] [client]  about to write new connect msg
Mar 07 02:05:39 influxdbclone telegraf[154]: 2026-03-07T01:05:39Z D! [inputs.mqtt_consumer] [client]  dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 02:05:39 influxdbclone telegraf[154]: 2026-03-07T01:05:39Z D! [inputs.mqtt_consumer] [client]  failed to connect to broker, trying next
Mar 07 02:05:41 influxdbclone telegraf[154]: 2026-03-07T01:05:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:05:51 influxdbclone telegraf[154]: 2026-03-07T01:05:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:06:01 influxdbclone telegraf[154]: 2026-03-07T01:06:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:06:11 influxdbclone telegraf[154]: 2026-03-07T01:06:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:06:21 influxdbclone telegraf[154]: 2026-03-07T01:06:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:06:31 influxdbclone telegraf[154]: 2026-03-07T01:06:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:06:41 influxdbclone telegraf[154]: 2026-03-07T01:06:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:06:51 influxdbclone telegraf[154]: 2026-03-07T01:06:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:07:01 influxdbclone telegraf[154]: 2026-03-07T01:07:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:07:11 influxdbclone telegraf[154]: 2026-03-07T01:07:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:07:21 influxdbclone telegraf[154]: 2026-03-07T01:07:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:07:31 influxdbclone telegraf[154]: 2026-03-07T01:07:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:07:41 influxdbclone telegraf[154]: 2026-03-07T01:07:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:07:51 influxdbclone telegraf[154]: 2026-03-07T01:07:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:08:01 influxdbclone telegraf[154]: 2026-03-07T01:08:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:08:11 influxdbclone telegraf[154]: 2026-03-07T01:08:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:08:21 influxdbclone telegraf[154]: 2026-03-07T01:08:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:08:31 influxdbclone telegraf[154]: 2026-03-07T01:08:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:08:41 influxdbclone telegraf[154]: 2026-03-07T01:08:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:08:51 influxdbclone telegraf[154]: 2026-03-07T01:08:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:09:01 influxdbclone telegraf[154]: 2026-03-07T01:09:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:09:11 influxdbclone telegraf[154]: 2026-03-07T01:09:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:09:21 influxdbclone telegraf[154]: 2026-03-07T01:09:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:09:31 influxdbclone telegraf[154]: 2026-03-07T01:09:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:09:41 influxdbclone telegraf[154]: 2026-03-07T01:09:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:09:51 influxdbclone telegraf[154]: 2026-03-07T01:09:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:10:01 influxdbclone telegraf[154]: 2026-03-07T01:10:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:10:11 influxdbclone telegraf[154]: 2026-03-07T01:10:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:10:21 influxdbclone telegraf[154]: 2026-03-07T01:10:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:10:31 influxdbclone telegraf[154]: 2026-03-07T01:10:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:10:41 influxdbclone telegraf[154]: 2026-03-07T01:10:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:10:51 influxdbclone telegraf[154]: 2026-03-07T01:10:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:11:01 influxdbclone telegraf[154]: 2026-03-07T01:11:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:11:11 influxdbclone telegraf[154]: 2026-03-07T01:11:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:11:21 influxdbclone telegraf[154]: 2026-03-07T01:11:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:11:31 influxdbclone telegraf[154]: 2026-03-07T01:11:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:11:41 influxdbclone telegraf[154]: 2026-03-07T01:11:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:11:51 influxdbclone telegraf[154]: 2026-03-07T01:11:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:12:01 influxdbclone telegraf[154]: 2026-03-07T01:12:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:12:11 influxdbclone telegraf[154]: 2026-03-07T01:12:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:12:21 influxdbclone telegraf[154]: 2026-03-07T01:12:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:12:31 influxdbclone telegraf[154]: 2026-03-07T01:12:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:12:41 influxdbclone telegraf[154]: 2026-03-07T01:12:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:12:51 influxdbclone telegraf[154]: 2026-03-07T01:12:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:13:01 influxdbclone telegraf[154]: 2026-03-07T01:13:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:13:11 influxdbclone telegraf[154]: 2026-03-07T01:13:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:13:21 influxdbclone telegraf[154]: 2026-03-07T01:13:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:13:31 influxdbclone telegraf[154]: 2026-03-07T01:13:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:13:41 influxdbclone telegraf[154]: 2026-03-07T01:13:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:13:51 influxdbclone telegraf[154]: 2026-03-07T01:13:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:14:01 influxdbclone telegraf[154]: 2026-03-07T01:14:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:14:11 influxdbclone telegraf[154]: 2026-03-07T01:14:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:14:21 influxdbclone telegraf[154]: 2026-03-07T01:14:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:14:31 influxdbclone telegraf[154]: 2026-03-07T01:14:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:14:41 influxdbclone telegraf[154]: 2026-03-07T01:14:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:14:51 influxdbclone telegraf[154]: 2026-03-07T01:14:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:15:01 influxdbclone telegraf[154]: 2026-03-07T01:15:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:15:11 influxdbclone telegraf[154]: 2026-03-07T01:15:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:15:21 influxdbclone telegraf[154]: 2026-03-07T01:15:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:15:31 influxdbclone telegraf[154]: 2026-03-07T01:15:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:15:39 influxdbclone telegraf[154]: 2026-03-07T01:15:39Z D! [inputs.mqtt_consumer] [client]  Reconnect failed, slept for600seconds:network Error : dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 02:15:39 influxdbclone telegraf[154]: 2026-03-07T01:15:39Z D! [inputs.mqtt_consumer] [client]  about to write new connect msg
Mar 07 02:15:41 influxdbclone telegraf[154]: 2026-03-07T01:15:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:15:43 influxdbclone telegraf[154]: 2026-03-07T01:15:43Z D! [inputs.mqtt_consumer] [client]  dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 02:15:43 influxdbclone telegraf[154]: 2026-03-07T01:15:43Z D! [inputs.mqtt_consumer] [client]  failed to connect to broker, trying next
Mar 07 02:15:51 influxdbclone telegraf[154]: 2026-03-07T01:15:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:16:01 influxdbclone telegraf[154]: 2026-03-07T01:16:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:16:11 influxdbclone telegraf[154]: 2026-03-07T01:16:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:16:21 influxdbclone telegraf[154]: 2026-03-07T01:16:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:16:31 influxdbclone telegraf[154]: 2026-03-07T01:16:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:16:41 influxdbclone telegraf[154]: 2026-03-07T01:16:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:16:51 influxdbclone telegraf[154]: 2026-03-07T01:16:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:17:01 influxdbclone telegraf[154]: 2026-03-07T01:17:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:17:11 influxdbclone telegraf[154]: 2026-03-07T01:17:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:17:21 influxdbclone telegraf[154]: 2026-03-07T01:17:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:17:31 influxdbclone telegraf[154]: 2026-03-07T01:17:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:17:41 influxdbclone telegraf[154]: 2026-03-07T01:17:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:17:51 influxdbclone telegraf[154]: 2026-03-07T01:17:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:18:01 influxdbclone telegraf[154]: 2026-03-07T01:18:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:18:11 influxdbclone telegraf[154]: 2026-03-07T01:18:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:18:21 influxdbclone telegraf[154]: 2026-03-07T01:18:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:18:31 influxdbclone telegraf[154]: 2026-03-07T01:18:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:18:41 influxdbclone telegraf[154]: 2026-03-07T01:18:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:18:51 influxdbclone telegraf[154]: 2026-03-07T01:18:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:19:01 influxdbclone telegraf[154]: 2026-03-07T01:19:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:19:11 influxdbclone telegraf[154]: 2026-03-07T01:19:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:19:21 influxdbclone telegraf[154]: 2026-03-07T01:19:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:19:31 influxdbclone telegraf[154]: 2026-03-07T01:19:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:19:41 influxdbclone telegraf[154]: 2026-03-07T01:19:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:19:51 influxdbclone telegraf[154]: 2026-03-07T01:19:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:20:01 influxdbclone telegraf[154]: 2026-03-07T01:20:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:20:11 influxdbclone telegraf[154]: 2026-03-07T01:20:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:20:21 influxdbclone telegraf[154]: 2026-03-07T01:20:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:20:31 influxdbclone telegraf[154]: 2026-03-07T01:20:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:20:41 influxdbclone telegraf[154]: 2026-03-07T01:20:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:20:51 influxdbclone telegraf[154]: 2026-03-07T01:20:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:21:01 influxdbclone telegraf[154]: 2026-03-07T01:21:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:21:11 influxdbclone telegraf[154]: 2026-03-07T01:21:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:21:21 influxdbclone telegraf[154]: 2026-03-07T01:21:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:21:31 influxdbclone telegraf[154]: 2026-03-07T01:21:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:21:41 influxdbclone telegraf[154]: 2026-03-07T01:21:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:21:51 influxdbclone telegraf[154]: 2026-03-07T01:21:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:22:01 influxdbclone telegraf[154]: 2026-03-07T01:22:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:22:11 influxdbclone telegraf[154]: 2026-03-07T01:22:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:22:21 influxdbclone telegraf[154]: 2026-03-07T01:22:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:22:31 influxdbclone telegraf[154]: 2026-03-07T01:22:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:22:41 influxdbclone telegraf[154]: 2026-03-07T01:22:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:22:51 influxdbclone telegraf[154]: 2026-03-07T01:22:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:23:01 influxdbclone telegraf[154]: 2026-03-07T01:23:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:23:11 influxdbclone telegraf[154]: 2026-03-07T01:23:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:23:21 influxdbclone telegraf[154]: 2026-03-07T01:23:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:23:31 influxdbclone telegraf[154]: 2026-03-07T01:23:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:23:41 influxdbclone telegraf[154]: 2026-03-07T01:23:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:23:51 influxdbclone telegraf[154]: 2026-03-07T01:23:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:24:01 influxdbclone telegraf[154]: 2026-03-07T01:24:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:24:11 influxdbclone telegraf[154]: 2026-03-07T01:24:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:24:21 influxdbclone telegraf[154]: 2026-03-07T01:24:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:24:31 influxdbclone telegraf[154]: 2026-03-07T01:24:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:24:41 influxdbclone telegraf[154]: 2026-03-07T01:24:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:24:51 influxdbclone telegraf[154]: 2026-03-07T01:24:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:25:01 influxdbclone telegraf[154]: 2026-03-07T01:25:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:25:11 influxdbclone telegraf[154]: 2026-03-07T01:25:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:25:21 influxdbclone telegraf[154]: 2026-03-07T01:25:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:25:31 influxdbclone telegraf[154]: 2026-03-07T01:25:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:25:41 influxdbclone telegraf[154]: 2026-03-07T01:25:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:25:43 influxdbclone telegraf[154]: 2026-03-07T01:25:43Z D! [inputs.mqtt_consumer] [client]  Reconnect failed, slept for600seconds:network Error : dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 02:25:43 influxdbclone telegraf[154]: 2026-03-07T01:25:43Z D! [inputs.mqtt_consumer] [client]  about to write new connect msg
Mar 07 02:25:46 influxdbclone telegraf[154]: 2026-03-07T01:25:46Z D! [inputs.mqtt_consumer] [client]  dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 02:25:46 influxdbclone telegraf[154]: 2026-03-07T01:25:46Z D! [inputs.mqtt_consumer] [client]  failed to connect to broker, trying next
Mar 07 02:25:51 influxdbclone telegraf[154]: 2026-03-07T01:25:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:26:01 influxdbclone telegraf[154]: 2026-03-07T01:26:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:26:11 influxdbclone telegraf[154]: 2026-03-07T01:26:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:26:21 influxdbclone telegraf[154]: 2026-03-07T01:26:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:26:31 influxdbclone telegraf[154]: 2026-03-07T01:26:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:26:41 influxdbclone telegraf[154]: 2026-03-07T01:26:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:26:51 influxdbclone telegraf[154]: 2026-03-07T01:26:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:27:01 influxdbclone telegraf[154]: 2026-03-07T01:27:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:27:11 influxdbclone telegraf[154]: 2026-03-07T01:27:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:27:21 influxdbclone telegraf[154]: 2026-03-07T01:27:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:27:31 influxdbclone telegraf[154]: 2026-03-07T01:27:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:27:41 influxdbclone telegraf[154]: 2026-03-07T01:27:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:27:51 influxdbclone telegraf[154]: 2026-03-07T01:27:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:28:01 influxdbclone telegraf[154]: 2026-03-07T01:28:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:28:11 influxdbclone telegraf[154]: 2026-03-07T01:28:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:28:21 influxdbclone telegraf[154]: 2026-03-07T01:28:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:28:31 influxdbclone telegraf[154]: 2026-03-07T01:28:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:28:41 influxdbclone telegraf[154]: 2026-03-07T01:28:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:28:51 influxdbclone telegraf[154]: 2026-03-07T01:28:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:29:01 influxdbclone telegraf[154]: 2026-03-07T01:29:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:29:11 influxdbclone telegraf[154]: 2026-03-07T01:29:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:29:21 influxdbclone telegraf[154]: 2026-03-07T01:29:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:29:31 influxdbclone telegraf[154]: 2026-03-07T01:29:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:29:41 influxdbclone telegraf[154]: 2026-03-07T01:29:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:29:51 influxdbclone telegraf[154]: 2026-03-07T01:29:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:30:01 influxdbclone telegraf[154]: 2026-03-07T01:30:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:30:11 influxdbclone telegraf[154]: 2026-03-07T01:30:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:30:21 influxdbclone telegraf[154]: 2026-03-07T01:30:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:30:31 influxdbclone telegraf[154]: 2026-03-07T01:30:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:30:41 influxdbclone telegraf[154]: 2026-03-07T01:30:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:30:51 influxdbclone telegraf[154]: 2026-03-07T01:30:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:31:01 influxdbclone telegraf[154]: 2026-03-07T01:31:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:31:11 influxdbclone telegraf[154]: 2026-03-07T01:31:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:31:21 influxdbclone telegraf[154]: 2026-03-07T01:31:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:31:31 influxdbclone telegraf[154]: 2026-03-07T01:31:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:31:41 influxdbclone telegraf[154]: 2026-03-07T01:31:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:31:51 influxdbclone telegraf[154]: 2026-03-07T01:31:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:32:01 influxdbclone telegraf[154]: 2026-03-07T01:32:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:32:11 influxdbclone telegraf[154]: 2026-03-07T01:32:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:32:21 influxdbclone telegraf[154]: 2026-03-07T01:32:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:32:31 influxdbclone telegraf[154]: 2026-03-07T01:32:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:32:41 influxdbclone telegraf[154]: 2026-03-07T01:32:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:32:51 influxdbclone telegraf[154]: 2026-03-07T01:32:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:33:01 influxdbclone telegraf[154]: 2026-03-07T01:33:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:33:11 influxdbclone telegraf[154]: 2026-03-07T01:33:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:33:21 influxdbclone telegraf[154]: 2026-03-07T01:33:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:33:31 influxdbclone telegraf[154]: 2026-03-07T01:33:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
```

**Comment by SofieF2005** [comment]
Reconnect at ~2:38:00
```
Mar 07 02:35:21 influxdbclone telegraf[154]: 2026-03-07T01:35:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:35:31 influxdbclone telegraf[154]: 2026-03-07T01:35:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:35:41 influxdbclone telegraf[154]: 2026-03-07T01:35:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:35:46 influxdbclone telegraf[154]: 2026-03-07T01:35:46Z D! [inputs.mqtt_consumer] [client]  Reconnect failed, slept for600seconds:network Error : dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 02:35:46 influxdbclone telegraf[154]: 2026-03-07T01:35:46Z D! [inputs.mqtt_consumer] [client]  about to write new connect msg
Mar 07 02:35:49 influxdbclone telegraf[154]: 2026-03-07T01:35:49Z D! [inputs.mqtt_consumer] [client]  dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 02:35:49 influxdbclone telegraf[154]: 2026-03-07T01:35:49Z D! [inputs.mqtt_consumer] [client]  failed to connect to broker, trying next
Mar 07 02:35:51 influxdbclone telegraf[154]: 2026-03-07T01:35:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:36:01 influxdbclone telegraf[154]: 2026-03-07T01:36:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:36:11 influxdbclone telegraf[154]: 2026-03-07T01:36:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:36:21 influxdbclone telegraf[154]: 2026-03-07T01:36:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:36:31 influxdbclone telegraf[154]: 2026-03-07T01:36:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:36:41 influxdbclone telegraf[154]: 2026-03-07T01:36:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:36:51 influxdbclone telegraf[154]: 2026-03-07T01:36:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:37:01 influxdbclone telegraf[154]: 2026-03-07T01:37:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:37:11 influxdbclone telegraf[154]: 2026-03-07T01:37:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:37:21 influxdbclone telegraf[154]: 2026-03-07T01:37:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:37:31 influxdbclone telegraf[154]: 2026-03-07T01:37:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:37:41 influxdbclone telegraf[154]: 2026-03-07T01:37:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:37:51 influxdbclone telegraf[154]: 2026-03-07T01:37:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:38:01 influxdbclone telegraf[154]: 2026-03-07T01:38:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:38:11 influxdbclone telegraf[154]: 2026-03-07T01:38:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:38:21 influxdbclone telegraf[154]: 2026-03-07T01:38:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:38:31 influxdbclone telegraf[154]: 2026-03-07T01:38:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:38:41 influxdbclone telegraf[154]: 2026-03-07T01:38:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:38:51 influxdbclone telegraf[154]: 2026-03-07T01:38:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:39:01 influxdbclone telegraf[154]: 2026-03-07T01:39:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:39:11 influxdbclone telegraf[154]: 2026-03-07T01:39:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:39:21 influxdbclone telegraf[154]: 2026-03-07T01:39:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:39:31 influxdbclone telegraf[154]: 2026-03-07T01:39:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:39:41 influxdbclone telegraf[154]: 2026-03-07T01:39:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:39:51 influxdbclone telegraf[154]: 2026-03-07T01:39:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:40:01 influxdbclone telegraf[154]: 2026-03-07T01:40:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:40:11 influxdbclone telegraf[154]: 2026-03-07T01:40:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:40:21 influxdbclone telegraf[154]: 2026-03-07T01:40:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:40:31 influxdbclone telegraf[154]: 2026-03-07T01:40:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:40:41 influxdbclone telegraf[154]: 2026-03-07T01:40:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:40:51 influxdbclone telegraf[154]: 2026-03-07T01:40:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:41:01 influxdbclone telegraf[154]: 2026-03-07T01:41:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:41:11 influxdbclone telegraf[154]: 2026-03-07T01:41:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:41:21 influxdbclone telegraf[154]: 2026-03-07T01:41:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:41:31 influxdbclone telegraf[154]: 2026-03-07T01:41:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:41:41 influxdbclone telegraf[154]: 2026-03-07T01:41:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:41:51 influxdbclone telegraf[154]: 2026-03-07T01:41:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:42:01 influxdbclone telegraf[154]: 2026-03-07T01:42:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:42:11 influxdbclone telegraf[154]: 2026-03-07T01:42:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:42:21 influxdbclone telegraf[154]: 2026-03-07T01:42:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:42:31 influxdbclone telegraf[154]: 2026-03-07T01:42:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:42:41 influxdbclone telegraf[154]: 2026-03-07T01:42:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:42:51 influxdbclone telegraf[154]: 2026-03-07T01:42:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:43:01 influxdbclone telegraf[154]: 2026-03-07T01:43:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:43:11 influxdbclone telegraf[154]: 2026-03-07T01:43:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:43:21 influxdbclone telegraf[154]: 2026-03-07T01:43:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:43:31 influxdbclone telegraf[154]: 2026-03-07T01:43:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:43:41 influxdbclone telegraf[154]: 2026-03-07T01:43:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:43:51 influxdbclone telegraf[154]: 2026-03-07T01:43:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:44:01 influxdbclone telegraf[154]: 2026-03-07T01:44:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:44:11 influxdbclone telegraf[154]: 2026-03-07T01:44:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:44:21 influxdbclone telegraf[154]: 2026-03-07T01:44:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:44:31 influxdbclone telegraf[154]: 2026-03-07T01:44:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:44:41 influxdbclone telegraf[154]: 2026-03-07T01:44:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:44:51 influxdbclone telegraf[154]: 2026-03-07T01:44:51Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:45:01 influxdbclone telegraf[154]: 2026-03-07T01:45:01Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:45:11 influxdbclone telegraf[154]: 2026-03-07T01:45:11Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:45:21 influxdbclone telegraf[154]: 2026-03-07T01:45:21Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:45:31 influxdbclone telegraf[154]: 2026-03-07T01:45:31Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:45:41 influxdbclone telegraf[154]: 2026-03-07T01:45:41Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [client]  Reconnect failed, slept for600seconds:network Error : dial tcp 192.168.1.12:1883: connect: no route to host
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [client]  about to write new connect msg
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [client]  socket connected to broker
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [client]  Using MQTT 3.1.1 protocol
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     connect started
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     received connack
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [client]  startCommsWorkers called
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [client]  client is connected/reconnected
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     incoming started
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms started
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     outgoing started
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startComms started
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [client]  startCommsWorkers done
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [store]   enter Resume
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [store]   exit resume
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [pinger]  keepalive starting
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z I! [inputs.mqtt_consumer] Connected [tcp://192.168.1.12:1883]
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [client]  enter SubscribeMultiple
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [client]  sending subscribe message, topics:[ZGW16-IP/#]
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [client]  exit SubscribeMultiple
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     logic waiting for msg on ibound
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: inboundFromStore complete
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     logic waiting for msg on ibound
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     outgoing waiting for an outbound message
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     obound priority msg to write, type*packets.SubscribePacket
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     outgoing waiting for an outbound message
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncoming Received Message
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: got msg on ibound
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [store]   memorystore del: message2not found
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: received suback, id:2
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: granted qoss[0]
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     logic waiting for msg on ibound
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncoming Received Message
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncoming Received Message
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: got msg on ibound
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: received publish, msgId:0
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     logic waiting for msg on ibound
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: got msg on ibound
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: received publish, msgId:0
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncoming Received Message
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     logic waiting for msg on ibound
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: got msg on ibound
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: received publish, msgId:0
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncoming Received Message
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     logic waiting for msg on ibound
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: got msg on ibound
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: received publish, msgId:0
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncoming Received Message
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z E! [inputs.mqtt_consumer] Error in plugin: invalid character 'o' looking for beginning of value
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [parsers.xpath_json::mqtt_consumer] Number of configs: 1
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [parsers.xpath_json::mqtt_consumer] Number of selected metric nodes: 1
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [parsers.xpath_json::mqtt_consumer] Number of configs: 1
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [parsers.xpath_json::mqtt_consumer] Number of selected metric nodes: 1
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [parsers.xpath_json::mqtt_consumer] Number of configs: 1
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [parsers.xpath_json::mqtt_consumer] Number of selected metric nodes: 1
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     logic waiting for msg on ibound
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: got msg on ibound
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: received publish, msgId:0
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     logic waiting for msg on ibound
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [parsers.xpath_json::mqtt_consumer] Number of configs: 1
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [parsers.xpath_json::mqtt_consumer] Number of selected metric nodes: 1
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncoming Received Message
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncoming Received Message
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: got msg on ibound
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: received publish, msgId:0
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     logic waiting for msg on ibound
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: got msg on ibound
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: received publish, msgId:0
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncoming Received Message
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     logic waiting for msg on ibound
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: got msg on ibound
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncomingComms: received publish, msgId:0
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     startIncoming Received Message
Mar 07 02:45:49 influxdbclone telegraf[154]: 2026-03-07T01:45:49Z D! [inputs.mqtt_consumer] [net]     logic waiting for msg on ibound
```

**Comment by SofieF2005** [comment]
It will work but you have to wait up to 10mins after reconnect until you get some data
Don't know why my first try failed. Can't reproduce at the moment.

Another problem:
If you boot the machine with disconnected ethernet this will happen:


```
Last login: Sat Mar  7 01:46:51 CET 2026 on tty1
root@influxdbclone:~# journalctl -u telegraf -f
Mar 07 02:51:47 influxdbclone telegraf[368]: 2026-03-07T01:51:47Z D! [inputs.mqtt_consumer] Disconnected [tcp://192.168.1.12:1883]
Mar 07 02:51:47 influxdbclone telegraf[368]: 2026-03-07T01:51:47Z E! [telegraf] Error running agent: starting input inputs.mqtt_consumer: network Error : dial tcp 192.168.1.12:1883: connect: network is unreachable
Mar 07 02:51:47 influxdbclone systemd[1]: Started telegraf.service - Telegraf.
Mar 07 02:51:47 influxdbclone systemd[1]: telegraf.service: Main process exited, code=exited, status=1/FAILURE
Mar 07 02:51:47 influxdbclone systemd[1]: telegraf.service: Failed with result 'exit-code'.
Mar 07 02:51:47 influxdbclone systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 5.
Mar 07 02:51:47 influxdbclone systemd[1]: Stopped telegraf.service - Telegraf.
Mar 07 02:51:47 influxdbclone systemd[1]: telegraf.service: Start request repeated too quickly.
Mar 07 02:51:47 influxdbclone systemd[1]: telegraf.service: Failed with result 'exit-code'.
Mar 07 02:51:47 influxdbclone systemd[1]: Failed to start telegraf.service - Telegraf.
```


When  you (re)connect ethernet nothing will happen. You have to reboot the machine again with ethernet connected (or restart telegraf)

**Comment by skartikey** [comment]
@SofieF2005 Thank you so much for the thorough testing and for enabling `client_trace`, your logs were invaluable in pinpointing the issue!

### What we found

The `client_trace` logs revealed the root cause:

```
Reconnect failed, slept for600seconds:network Error : dial tcp 192.168.1.12:1883: connect: no route to host
```

Paho's default `MaxReconnectInterval` is 10 minutes (600 seconds). After a long network outage, the exponential backoff maxes out, so once the broker comes back, paho can take up to 10 minutes before it even attempts to reconnect. This explains the long delay you observed.

### Fix

I've opened a follow-up PR to address this: #18466. It caps the max reconnect interval at the `connection_timeout` value (default 30s), so reconnection attempts happen much more frequently after an outage.

Could you download the build artifact from #18466 once the CI builds are ready and test the long disconnect scenario again? The reconnection should now happen within ~30 seconds instead of ~10 minutes.

Regarding the second issue you reported (Telegraf crashing on boot with no network), that is a pre-existing behavior not specific to this PR. You can work around it by adding `startup_error_behavior = "retry"` to your `[[inputs.mqtt_consumer]]` config, which will make Telegraf keep retrying instead of exiting.

Thanks again for your help. This kind of real-world testing makes a huge difference!
