### PR TITLE
fix(inputs.snmp_trap): Remove timeout deprecation

### LINKED ISSUE #16137: DeprecationWarning: Option “timeout” of plugin inputs.snmp_trap
### Relevant telegraf.conf

```toml
[[inputs.snmp_trap]]
path = [ “/usr/share/snmp/mibs” ]
service_address = “udp://:162”
version = “2c”
```

### Logs from Telegraf

```text
"DeprecationWarning: Option “timeout” of plugin “inputs.snmp_trap” deprecated since version 1.20.0 and will be removed in 2.0.0: unused option"
```

### System info

1.27.3

### Docker

_No response_

### Steps to reproduce

1. Restarting the Telegraf service after adding new community strings for the V2 Input

### Expected behavior

There shouldn't be this warning because “timeout” of plugin “inputs.snmp_trap” is not used in the confing file

### Actual behavior

Getting this deprecation warning

### Additional info

Operating System: Red Hat Enterprise Linux 8.10 (Ootpa)
CPE OS Name: cpe:/o:redhat:enterprise_linux:8::baseos
Kernel: Linux 4.18.0-553.22.1.el8_10.x86_64
Architecture: x86-64

NAME="Red Hat Enterprise Linux"
VERSION="8.10 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"

### PR DESCRIPTION
**Pull request by DStrand1**
## Summary
Removes the "unused" deprecation from the timeout field as it is still used

## Checklist
- [X] No AI generated code was used in this PR

## Related issues
resolves #16137

### CODE REVIEW

File: plugins/inputs/snmp_trap/snmp_trap.go [hunk 1]
```diff
@@ -104,6 +103,9 @@ func (s *SnmpTrap) Init() error {
 			return err
 		}
 	case "netsnmp":
+		if s.Timeout == 0 {
+			s.Timeout = defaultTimeout
+		}
```
Comment (Hipska) [inline plugins/inputs/snmp_trap/snmp_trap.go:108]: Why setting it if it's an unused option?

Comment (srebhan) [reply plugins/inputs/snmp_trap/snmp_trap.go:108]: I agree. However, I'm not sure anymore the parameter is actually unused... It is used with the netsnmp translator isn't it?

Comment (Hipska) [reply plugins/inputs/snmp_trap/snmp_trap.go:108]: How/where?

Comment (srebhan) [reply plugins/inputs/snmp_trap/snmp_trap.go:108]: @Hipska the timeout is [passed to the netsnmp translator](https://github.com/influxdata/telegraf/blob/d075815f29d73a7fb880c11d24a1b3a4901cc520/plugins/inputs/snmp_trap/snmp_trap.go#L107) which in turn uses it for the [command execution](https://github.com/influxdata/telegraf/blob/d075815f29d73a7fb880c11d24a1b3a4901cc520/plugins/inputs/snmp_trap/netsnmp.go#L62).

Comment (srebhan) [inline plugins/inputs/snmp_trap/snmp_trap.go:108]: @DStrand1 I think you need to remove this section as the default should be already set in `init`, isn't it?

**Review by srebhan — COMMENTED** [review]
@DStrand1 one comment. Furthemore, it might be good to add a comment to the setting in the `sample.conf` that this timeout is only used with the netsnmp translator.

File: plugins/inputs/snmp_trap/snmp_trap.go (hunk 1 above)
Comment (DStrand1) [reply plugins/inputs/snmp_trap/snmp_trap.go:108]: I thought it would be better to leave it this way in case we decide later to deprecate this flag

**Comment by Hipska** [comment]
Looks like I deprecated it (partially) with #10339, but then it got re-added with #11534.

To me, it looks like the timeout should be removed completely, or set it fixed at 5s (a `snmptranslate` call should never take that long) I think it was added as a fail-save, since the call is run during runtime instead of with inputs.snmp it is only called on initialisation.

File: plugins/inputs/snmp_trap/snmp_trap.go (hunk 1 above)
Comment (srebhan) [reply plugins/inputs/snmp_trap/snmp_trap.go:108]: No, please remove this as it now does not allow the user to enforce an infinite timeout.

File: plugins/inputs/snmp_trap/sample.conf [hunk 2]
```diff
@@ -14,8 +14,8 @@
   ## To add paths when translating with netsnmp, use the MIBDIRS environment variable
   # path = ["/usr/share/snmp/mibs"]
   ##
-  ## Deprecated in 1.20.0; no longer running snmptranslate
   ## Timeout running snmptranslate command
+  ## Used by the netsnmp translator
```
Comment (srebhan) [inline plugins/inputs/snmp_trap/sample.conf:18]:
```suggestion
  ## Used by the netsnmp translator only
```

File: plugins/inputs/snmp_trap/README.md [hunk 3]
```diff
@@ -62,8 +62,8 @@ details.
   ## To add paths when translating with netsnmp, use the MIBDIRS environment variable
   # path = ["/usr/share/snmp/mibs"]
   ##
-  ## Deprecated in 1.20.0; no longer running snmptranslate
   ## Timeout running snmptranslate command
+  ## Used by the netsnmp translator
```
Comment (srebhan) [inline plugins/inputs/snmp_trap/README.md:66]:
```suggestion
  ## Used by the netsnmp translator only
```

**Review by Hipska — APPROVED** [review]

**Review by srebhan — APPROVED** [review]
