### PR TITLE
Handle variations in the user_statistics collecting

### LINKED ISSUE #2910: MariaDB user statistics are different from Percona version
### System info:

Telegraf 1.3.1, MariaDB 10.1.24

### Steps to reproduce:

1. Configure Telegraf with MySQL input plugin
2. Turn on gather_user_statistics in Telegraf and userstat in MariaDB

### Expected behavior:
Information should be collected.

### Actual behavior:
Error in logs:
Jun 12 14:43:10 db1 telegraf[14838]: 2017-06-12T13:43:10Z E! MySQL Error gathering user stats: Error 1054: Unknown column 'rows_fetched' in 'field list'
Jun 12 14:43:10 db1 telegraf[14838]: 2017-06-12T13:43:10Z E! Error in plugin [inputs.mysql]: sql: expected 26 destination arguments in Scan, not 23

### Additional info:
                USER: stats
          TOTAL_CONNECTIONS: 83
     CONCURRENT_CONNECTIONS: 0
             CONNECTED_TIME: 55
                  BUSY_TIME: 1.2070639999999992
                   CPU_TIME: 1.1825710000000003
             BYTES_RECEIVED: 82791
                 BYTES_SENT: 1655069
       BINLOG_BYTES_WRITTEN: 0
                  ROWS_READ: 0
                  ROWS_SENT: 2264
               ROWS_DELETED: 0
              ROWS_INSERTED: 0
               ROWS_UPDATED: 0
            SELECT_COMMANDS: 443
            UPDATE_COMMANDS: 0
             OTHER_COMMANDS: 0
        COMMIT_TRANSACTIONS: 0
      ROLLBACK_TRANSACTIONS: 0
         DENIED_CONNECTIONS: 27
           LOST_CONNECTIONS: 0
              ACCESS_DENIED: 6
              EMPTY_QUERIES: 117
      TOTAL_SSL_CONNECTIONS: 0
       MAX_STATEMENT_TIME_EXCEEDED: 0

### PR DESCRIPTION
**Pull request by glinton**
There are differences in the `user_statistics` table (if it exists) between MariaDB, Percona, and MySQL. This should allow the stats to be collected properly.

MariaDB has two different table definitions:
 - https://mariadb.com/kb/en/library/information-schema-user_statistics-table/

Percona has it's own:
 - https://www.percona.com/doc/percona-server/LATEST/diagnostics/user_stats.html#USER_STATISTICS

MySQL doesn't have the table, but there may be a patch:
 - https://www.byte.nl/blog/enhancing-mysql-with-user-statistics

Resolves #2910
Closes #3382

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

File: plugins/inputs/mysql/mysql.go [hunk 1]
```diff
@@ -920,74 +861,210 @@ func (m *Mysql) GatherUserStatisticsStatuses(db *sql.DB, serv string, acc telegr
...
+				return fmt.Errorf("Unknown column type - %T", v)
+			}
 		}
 		acc.AddFields("mysql_user_stats", fields, tags)
 	}
 	return nil
 }
 
+// convertColumns converts selected column names to lowercase.
+func convertColumns(s []string, e error) ([]string, error) {
```
Comment (danielnelson) [inline plugins/inputs/mysql/mysql.go]: Maybe rename `columnsToLower` or `lowerColumns`?

File: plugins/inputs/mysql/mysql.go [hunk 2]
```diff
@@ -920,74 +861,210 @@ func (m *Mysql) GatherUserStatisticsStatuses(db *sql.DB, serv string, acc telegr
...
-		rollback_transactions  int64
-		denied_connections     int64
-		lost_connections       int64
-		access_denied          int64
-		empty_queries          int64
-		total_ssl_connections  int64
-		count                  uint32
-	)
+
+	cols, err := convertColumns(rows.Columns())
```
Comment (danielnelson) [inline plugins/inputs/mysql/mysql.go]: This is just an observation.  I never knew you could pass multiple arguments like this, interesting.  I'm not sure I like how it becomes the outer functions job to deal with an upstream error, but I like how it can compress the error handling needed in this function.

File: plugins/inputs/mysql/mysql.go [hunk 3]
```diff
@@ -920,74 +861,210 @@ func (m *Mysql) GatherUserStatisticsStatuses(db *sql.DB, serv string, acc telegr
...
-			"commit_transactions":    commit_transactions,
-			"rollback_transactions":  rollback_transactions,
-			"denied_connections":     denied_connections,
-			"lost_connections":       lost_connections,
-			"access_denied":          access_denied,
-			"empty_queries":          empty_queries,
-			"total_ssl_connections":  total_ssl_connections,
+		for i := range cols {
+			if i == 0 {
+				continue // skip "user"
```
Comment (danielnelson) [inline plugins/inputs/mysql/mysql.go]: Percona index 0 comment applies here.

File: plugins/inputs/mysql/mysql.go [hunk 4]
```diff
@@ -920,74 +861,210 @@ func (m *Mysql) GatherUserStatisticsStatuses(db *sql.DB, serv string, acc telegr
...
-			"update_commands":        update_commands,
-			"other_commands":         other_commands,
-			"commit_transactions":    commit_transactions,
-			"rollback_transactions":  rollback_transactions,
-			"denied_connections":     denied_connections,
-			"lost_connections":       lost_connections,
-			"access_denied":          access_denied,
-			"empty_queries":          empty_queries,
-			"total_ssl_connections":  total_ssl_connections,
+		for i := range cols {
```
Comment (danielnelson) [inline plugins/inputs/mysql/mysql.go]: I would use `for _, column := range cols {` and avoid using the index directly.  I know in some situations it can be slightly slower to iterate in this manner, but I think it almost always is more readable and less error prone.

File: plugins/inputs/mysql/mysql.go [hunk 5]
```diff
@@ -920,74 +861,210 @@ func (m *Mysql) GatherUserStatisticsStatuses(db *sql.DB, serv string, acc telegr
...
+			if i == 0 {
+				continue // skip "user"
+			}
+			switch v := read[i].(type) {
+			case *bool:
```
Comment (danielnelson) [inline plugins/inputs/mysql/mysql.go]: Only include expected types and the default case can handle anything else.

File: plugins/inputs/mysql/mysql.go [hunk 6]
```diff
@@ -920,74 +861,210 @@ func (m *Mysql) GatherUserStatisticsStatuses(db *sql.DB, serv string, acc telegr
...
-			&empty_queries, &total_ssl_connections, &count,
-		)
+		err = rows.Scan(read...)
 		if err != nil {
 			return err
 		}
 
-		tags := map[string]string{"server": servtag, "user": user}
-		fields := map[string]interface{}{
+		tags := map[string]string{"server": servtag, "user": *read[0].(*string)}
```
Comment (danielnelson) [inline plugins/inputs/mysql/mysql.go]: User is not always index 0 (percona)

File: plugins/inputs/mysql/mysql.go [hunk 7]
```diff
@@ -920,74 +861,210 @@ func (m *Mysql) GatherUserStatisticsStatuses(db *sql.DB, serv string, acc telegr
...
+	if err != nil {
+		return err
+	}
+
+	read, err := getColSlice(len(cols))
+	if err != nil {
+		return err
+	}
+
+	if len(read) != len(cols) {
```
Comment (danielnelson) [inline plugins/inputs/mysql/mysql.go]: I would probably remove this check, since in theory it is impossible unless there is a programming error and it should. be picked up by the rows.Scan(

File: plugins/inputs/mysql/mysql.go (hunk 5 above)
Comment (glinton) [reply plugins/inputs/mysql/mysql.go]: Good call. Is it stylistically ok to leave out the default case since it is immediately followed by the function's return?

File: plugins/inputs/mysql/mysql.go (hunk 7 above)
Comment (glinton) [reply plugins/inputs/mysql/mysql.go]: :+1:

File: plugins/inputs/mysql/mysql.go (hunk 6 above)
Comment (glinton) [reply plugins/inputs/mysql/mysql.go]: I'll make it more robust, but in all the [docs](https://www.percona.com/doc/percona-server/LATEST/diagnostics/user_stats.html#USER_STATISTICS) I checked it would be index 0.

File: plugins/inputs/mysql/mysql.go (hunk 4 above)
Comment (glinton) [reply plugins/inputs/mysql/mysql.go]: In this case, I think leaving it is best. I'll still need the iterator for the `read` slice and it's pretty clear where `cols[i]` is only used in the switch block.

File: plugins/inputs/mysql/mysql.go (hunk 5 above)
Comment (danielnelson) [reply plugins/inputs/mysql/mysql.go]: I usually leave the default in to catch any programming mistakes.

File: plugins/inputs/mysql/mysql.go (hunk 6 above)
Comment (danielnelson) [reply plugins/inputs/mysql/mysql.go]: What about in this list of columns?

https://github.com/influxdata/telegraf/pull/4306/files#diff-d267f290fd16dce7d39997e69d775747R1041

File: plugins/inputs/mysql/mysql.go [hunk 8]
```diff
@@ -790,72 +790,13 @@ func (m *Mysql) gatherGlobalStatuses(db *sql.DB, serv string, acc telegraf.Accum
 
 	// gather connection metrics from user_statistics for each user
 	if m.GatherUserStatistics {
-		conn_rows, err := db.Query("select user, total_connections, concurrent_connections, connected_time, busy_time, cpu_time, bytes_received, bytes_sent, binlog_bytes_written, rows_fetched, rows_updated, table_rows_read, select_commands, update_commands, other_commands, commit_transactions, rollback_transactions, denied_connections, lost_connections, access_denied, empty_queries, total_ssl_connections FROM INFORMATION_SCHEMA.USER_STATISTICS GROUP BY user")
+		err = m.GatherUserStatisticsStatuses(db, serv, acc)
```
[the remark this answers is not in the document]
Comment (danielnelson) [reply plugins/inputs/mysql/mysql.go]: What about L455 though?

File: plugins/inputs/mysql/mysql.go [hunk 9]
```diff
@@ -790,72 +790,13 @@ func (m *Mysql) gatherGlobalStatuses(db *sql.DB, serv string, acc telegraf.Accum
...
-					"denied_connections":     denied_connections,
-					"lost_connections":       lost_connections,
-					"access_denied":          access_denied,
-					"empty_queries":          empty_queries,
-					"total_ssl_connections":  total_ssl_connections,
-				}
-
-				acc.AddFields("mysql_user_stats", fields, tags)
+			// disable collecting if table is not found (suppresses repeat errors)
+			if strings.Contains(err.Error(), "nknown table 'user_statistics'") {
```
[the remark this answers is not in the document]
Comment (danielnelson) [reply plugins/inputs/mysql/mysql.go]: Okay, personally I would probably just ToLower it, but ideally this type of error matching will be uncommon.

I did find an interesting link off of http://go-database-sql.org/errors.html#identifying-specific-database-errors to a [package of error codes for mysql](https://github.com/VividCortex/mysqlerr), this might be helpful, though I'm unsure if these work on all mysql flavors.

File: plugins/inputs/mysql/mysql.go (hunk 6 above)
Comment (glinton) [reply plugins/inputs/mysql/mysql.go]: alias for user iirc

Comment (glinton) [reply plugins/inputs/mysql/mysql.go]: AH! I was referencing `client_statistics` table instead of `user_statistics` table

**Comment by glinton** [comment]
Closes #1645
