### PR TITLE
fix(internal.ethtool): internal name conflict with aws

### LINKED ISSUE #10869: inputs.ethtool expects boolean for interface_up metrics, however they're counters within ethtool.
### Relevant telegraf.conf

```toml
cat /etc/telegraf/telegraf.d/input-ethtool.conf
[[inputs.ethtool]]
```

### Logs from Telegraf

Mar 22 15:52:15 influxdb telegraf[244872]: 2022-03-22T15:52:15Z E! [outputs.influxdb] E! [outputs.influxdb] Failed to write metric (will be dropped: 400 Bad Request): partial write: field type conflict: input field "interface_up" on measurem
ent "ethtool" is type integer, already exists as type boolean dropped=1

### System info

1.21.4-1, Ubuntu 20.04, Ubuntu 18.04

### Docker

_No response_

### Steps to reproduce

Spin up AWS instance using enhanced networking, restart interfaces.
```
interface_up: N
The number of times that the ENA interface was brought up.

interface_down: N
The number of times that the ENA interface was brought down.

```

### Expected behavior

interface_up are counters not booleans, metrics should not be sent as boolean. this breaks all ethtool stats which are critical for us to track aws bandwidth allowance.

### Actual behavior

interface_up metrics with telegraf are not sent as booleans

### Additional info

https://github.com/influxdata/telegraf/pull/8590

### PR DESCRIPTION
**Pull request by MyaLongmire**
# Required for all PRs

- [ ] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #10869

### CODE REVIEW

File: plugins/inputs/ethtool/ethtool_test.go [hunk 1]
```diff
@@ -305,6 +305,15 @@ func toStringMapInterface(in map[string]uint64) map[string]interface{} {
 	return m
 }
 
+func toStringMapUint(in map[string]interface{}) map[string]uint64 {
+	var m = map[string]uint64{}
+	for k, v := range in {
+		t := v.(uint64)
+		m[k] = t
```
Comment (srebhan) [inline plugins/inputs/ethtool/ethtool_test.go:312]: This will panic if something is not an uint.... Are we _really_ sure this doesn't fire back at us?

**Review by srebhan — COMMENTED** [review]
Thanks @MyaLongmire for the fix. Are we really sure the type assertion will _always_ hold? I'd feel a bit better if we check and log on error...

File: plugins/inputs/ethtool/ethtool_test.go (hunk 1 above)
Comment (MyaLongmire) [reply plugins/inputs/ethtool/ethtool_test.go]: I added an error. It is only used in the test case `TestNormalizedKeys` since it is no longer a unit64 as it needs to contain a boolean. But `InterfaceMock` requires `stats` to be unit. If you have other ideas to avoid this I am open to hearing them :)

File: plugins/inputs/ethtool/ethtool_test.go [hunk 2]
```diff
@@ -305,6 +305,18 @@ func toStringMapInterface(in map[string]uint64) map[string]interface{} {
...
 }
 
+func toStringMapUint(in map[string]interface{}) map[string]uint64 {
+	var m = map[string]uint64{}
+	for k, v := range in {
+		t, ok := v.(uint64)
+		if !ok {
+			errors.New("something in the interface is not a unit")
+		}
+		m[k] = t
```
Comment (srebhan) [inline plugins/inputs/ethtool/ethtool_test.go:315]: I think we have to do something with the error here. ;-) I see three possibilities

1. Make the function a member of the `ethtool` struct and use the logger to log the error message.
2. Make the function return an error.
3. Silently ignore the value.

I think 2 is not so nice at it will throw away all values. TBH I would prefer option 1, but I don't know if that's easily doable... What do you think?

Comment (MyaLongmire) [reply plugins/inputs/ethtool/ethtool_test.go:315]: > I think we have to do something with the error here

Haha my mistake!

>  TBH I would prefer option 1, but I don't know if that's easily doable... 

I will give 1 a shot and I'll bug you if I get stuck :)

**Comment by MyaLongmire** [comment]
@srebhan I am not convinced this is the correct way to implement the logger but I gave it a go. If you would please take another look :)

**Comment by srebhan** [comment]
Oh damn I feel so dumb... I didn't notice that the function is in the **test**. :-( Sorry for all the noise!!! Please revert to before adding the logger as it is not worth to do this for tests!

**Comment by MyaLongmire** [comment]
@srebhan no worries :) I have now removed the logger if you wouldn't mind giving it yet another look.

**Review by srebhan — COMMENTED** [review]
Code looks good except for the included `custom_builder`binary. ;-D

**Comment by MyaLongmire** [comment]
So weird! I have no idea where that came from. I look into removing it

**Review by srebhan — APPROVED** [review]
Looks good to me. Thanks for the fix @MyaLongmire!

**Review by powersj — APPROVED** [review]
Thank you!
