### PR TITLE
Use add time for prometheus expiration calculation

### LINKED ISSUE #6926: Cloudwatch input plugin doesn't work with prometheus output metric_version 2
Since the introduction of the `metric_version = 2 ` configuration the cloudwatch input plugin doesn't produce any metric.

### Relevant telegraf.conf:

```toml
#
# OUTPUTS:
#
[[outputs.prometheus_client]]
listen = ":9273"
#
# INPUTS:
#
[[inputs.cloudwatch]]
delay = "5m"
interval = "1m"
namespace = "AWS/ApplicationELB"
period = "1m"
region = "eu-central-1"
[[inputs.cloudwatch.metrics]]
names = ["HealthyHostCount", "UnHealthyHostCount"]
statistic_include = ["average"]
[[inputs.cloudwatch.metrics.dimensions]]
name = "LoadBalancer"
value = "*"
[[inputs.cloudwatch.metrics.dimensions]]
name = "TargetGroup"
value = "*"
[[inputs.cloudwatch.metrics]]
names = ["TargetResponseTime"]
statistic_include = ["average"]
[[inputs.cloudwatch.metrics.dimensions]]
name = "LoadBalancer"
value = "*"
[[inputs.cloudwatch.metrics]]
names = ["RequestCount", "HTTPCode_Target_2XX_Count", "HTTPCode_Target_4XX_Count", "HTTPCode_Target_5XX_Count", "HTTPCode_ELB_4XX_Count", "HTTPCode_ELB_5XX_Count"]
statistic_include = ["sum"]
[[inputs.cloudwatch.metrics.dimensions]]
name = "LoadBalancer"
value = "*"
[[inputs.cloudwatch.metrics]]
names = ["RequestCountPerTarget"]
statistic_include = ["sum"]
[[inputs.cloudwatch.metrics.dimensions]]
name = "TargetGroup"
value = "*"
[[inputs.cloudwatch]]
delay = "5m"
interval = "1m"
namespace = "AWS/AutoScaling"
period = "1m"
region = "eu-central-1"
[[inputs.cloudwatch.metrics]]
names = ["GroupDesiredCapacity", "GroupInServiceInstances", "GroupTerminatingInstances", "GroupPendingInstances", "GroupStandbyInstances", "GroupTotalInstances", "GroupMaxSize"]
statistic_include = ["average"]
[[inputs.cloudwatch.metrics.dimensions]]
name = "AutoScalingGroupName"
value = "*"
```

### System info:

```
# telegraf --version
Telegraf 1.13.1 (git: HEAD 0c175724)

# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### Steps to reproduce:

1. Add the configuration `metric_version = 2` in the prometheus output section as recommended since the latest telegraf version

### Expected behavior:

The telegraf prometheus output should be the same as with the `metric_version = 1` configuration.

### Actual behavior:

The telegraf output is entirely missing the cloudwatch input plugin metrics.

### Additional info:

No message of any sort is logged by telegraf.

### PR DESCRIPTION
**Pull request by danielnelson**
closes #6926

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

File: plugins/serializers/prometheus/collection_test.go [hunk 1]
```diff
@@ -124,39 +143,47 @@ func TestCollectionExpire(t *testing.T) {
...
-				),
+			input: []Input{
+				{
+					metric: testutil.MustMetric(
+						"cpu",
+						map[string]string{},
+						map[string]interface{}{
+							"time_idle": 42.0,
+						},
+						time.Unix(0, 0),
```
Comment (reimda) [inline plugins/serializers/prometheus/collection_test.go]: The test probably ought to have different time and addtime to show that addtime is what's used during expiration

Comment (danielnelson) [reply plugins/serializers/prometheus/collection_test.go]: Added
