### PR TITLE
fix(inputs.execd): read from stdout using ReadLine instead of scanner.Scan to overcome 64kb buffer limit

### LINKED ISSUE #12934: inputs.execd: collection stops when the stdout reader fails
### Relevant telegraf.conf

```toml
# any execd would do
# I'm using this config to parse a JSON object on lines longer than 64kb
# When the scanner tries to scan for the next newline character, it fails
[[inputs.execd]]
   command = ['c:\\temp\\telegraf\\bug-execd\\test_execd_err.bat']
   signal = "none"
   data_format = "json"
   #buffer_size = 1024
   json_name_key = "OutputMeasurement"

   json_time_key = "collection_time_iso"
   json_time_format = "2006-01-02T15:04:05.999999999Z07:00"

   tag_keys = [
      "server_instance_name",
      "name", 
      "client_app_name", 
      "server_principal_name", 
      "client_hostname", 
      "database_name",
      "severity",
      "error_number"
   ]

   json_string_fields = [
      "message",
      "sql_text",
      "query_hash",
      "xml_report",
      "lock_mode",
      "resource_owner_type",
      "transaction_id"
   ]

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
```

### Logs from Telegraf

```text
2023-03-25T14:09:58Z I! Starting Telegraf 1.2.15-ed90c8dc (customized)
2023-03-25T14:09:58Z I! Available plugins: 12 inputs, 0 aggregators, 3 processors, 7 parsers, 6 outputs
2023-03-25T14:09:58Z I! Loaded inputs: execd
2023-03-25T14:09:58Z I! Loaded aggregators:
2023-03-25T14:09:58Z I! Loaded processors:
2023-03-25T14:09:58Z I! Loaded outputs: file
2023-03-25T14:09:58Z I! Tags enabled: host=QDWS01
2023-03-25T14:09:58Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"QDWS01", Flush Interval:10s
2023-03-25T14:09:58Z D! [agent] Initializing plugins
2023-03-25T14:09:58Z D! [agent] Connecting outputs
2023-03-25T14:09:58Z D! [agent] Attempting connection to [outputs.file]
2023-03-25T14:09:58Z D! [agent] Successfully connected to outputs.file
2023-03-25T14:09:58Z D! [agent] Starting service inputs
2023-03-25T14:09:58Z I! [inputs.execd] Starting process: c:\\temp\\telegraf\\bug-execd\\test_execd_err.bat []
2023-03-25T14:09:58Z E! [inputs.execd] Error in plugin: error reading stdout: bufio.Scanner: token too long
2023-03-25T14:10:08Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-03-25T14:10:14Z D! [agent] Stopping service inputs
2023-03-25T14:10:14Z E! [inputs.execd] stderr: "^CThe process tried to write to a nonexistent pipe."
2023-03-25T14:10:18Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-03-25T14:10:19Z I! [inputs.execd] Process c:\\temp\\telegraf\\bug-execd\\test_execd_err.bat shut down
2023-03-25T14:10:19Z D! [agent] Input channel closed
2023-03-25T14:10:19Z I! [agent] Hang on, flushing any cached metrics before shutdown
2023-03-25T14:10:19Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-03-25T14:10:19Z I! [agent] Stopping running outputs
2023-03-25T14:10:19Z D! [agent] Stopped Successfully
```

### System info

Telegraf 1.26.0 on Windows 11

### Docker

_No response_

### Steps to reproduce

Run telegraf using the config file included
Please use the JSON and BAT files attached. Repro files are for windows.
Change paths according to your environment

[test_execd.zip](https://github.com/influxdata/telegraf/files/11069101/test_execd.zip)

### Expected behavior

Execd should continue reading stdout from the command, even if one or more rows cannot be read or parsed correctly

### Actual behavior

Execd stops as soon as a read error is encountered. The underlying command keeps running, but no output is captured.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by spaghettidba**
- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [X] Pull request title or commits are in [conventional commit format]

Resolves #12934

- Fixed code for reading stdout from the underlying command. See #12934 for details.
- Introduced additional parameter to control the buffer size (in kb) used to read the stream. Not strictly required, but handy.

### CODE REVIEW

File: plugins/inputs/execd/execd.go [hunk 1]
```diff
@@ -28,6 +29,7 @@ type Execd struct {
 	Signal       string          `toml:"signal"`
 	RestartDelay config.Duration `toml:"restart_delay"`
 	Log          telegraf.Logger `toml:"-"`
+	BufferSize   int             `toml:"buffer_size"`
```
[the remark this answers is not in the document]
Comment (spaghettidba) [reply plugins/inputs/execd/execd.go]: Thanks for the input and the super fast review! Should be ok now.

File: plugins/inputs/execd/execd.go [hunk 2]
```diff
@@ -96,9 +106,6 @@ func (e *Execd) cmdReadOut(out io.Reader) {
 		}
 	}
```
Comment (powersj) [inline plugins/inputs/execd/execd.go:108]:
```suggestion
```

Comment (spaghettidba) [reply plugins/inputs/execd/execd.go]: Ah, thanks! I'm having a hard time understanding all the messages from the linter, I must have missed this one

**Review by powersj — APPROVED** [review]
Thanks!

FYI I pushed one change to fix the linter so I could approve

File: plugins/inputs/execd/sample.conf [hunk 3]
```diff
@@ -23,6 +23,10 @@
   ## Delay before the process is restarted after an unexpected termination
   restart_delay = "10s"
 
+  ## Buffer size used to read from the command output stream
+  ## Optional parameter. Default is 64 Kib, minimum is 16 bytes
+  buffer_size = "64Kib"
```
Comment (srebhan) [inline plugins/inputs/execd/sample.conf:28]: As this is a sensible default and also set in `init()` I think you should comment that option
```suggestion
  # buffer_size = "64Kib"
```

**Review by srebhan — COMMENTED** [review]
Just one small comment @spaghettidba.

File: plugins/inputs/execd/sample.conf (hunk 3 above)
Comment (spaghettidba) [reply plugins/inputs/execd/sample.conf:28]: Thanks for the suggestion!
I'm not sure I understand correctly: should I remove the option completely or just remove it from sample.conf?

Comment (powersj) [reply plugins/inputs/execd/sample.conf:28]: all you need to do is accept Sven's suggestion. 

Essentially, default values should be commented out in the config. We still want it in the config so the user sees it, but commented out to indicate it is not actually required or a user can un-comment it and set their own value.

File: plugins/inputs/execd/README.md [hunk 4]
```diff
@@ -50,6 +50,10 @@ See the [CONFIGURATION.md][CONFIGURATION.md] for more details.
   ## Delay before the process is restarted after an unexpected termination
   restart_delay = "10s"
 
+  ## Buffer size used to read from the command output stream
+  ## Optional parameter. Default is 64 Kib, minimum is 16 bytes
+  buffer_size = "64Kib"
```
Comment (powersj) [inline plugins/inputs/execd/README.md:55]:
```suggestion
  # buffer_size = "64Kib"
```

**Review by srebhan — APPROVED** [review]
Thanks @spaghettidba for this nice fix!

File: plugins/inputs/execd/README.md [hunk 5]
```diff
@@ -50,6 +50,10 @@ See the [CONFIGURATION.md][CONFIGURATION.md] for more details.
   ## Delay before the process is restarted after an unexpected termination
   restart_delay = "10s"
 
+  ## Buffer size used to read from the command output stream
+  ## Optional parameter. Default is 64 Kib, minimum is 16 bytes
+  # buffer_size = "64Kib"
```
Comment (adaszko) [inline plugins/inputs/execd/README.md:55]:
```
2023-06-20T10:40:29Z I! Loading config: /etc/telegraf/telegraf.conf
2023-06-20T10:40:29Z E! error loading config file /etc/telegraf/telegraf.conf: error parsing execd, line 218: (execd.Execd.BufferSize) units: unknown unit Kib in 128Kib
```

Getting these errors with `Kib`.  Shouldn’t the unit say `KiB`?

**Comment by adaszko** [comment]
I’m also still getting `2023-06-20T10:45:00Z E! [inputs.execd] Error in plugin: error reading stderr: bufio.Scanner: token too long` errors, even though I’m at telegraf v1.27.0 and have set `buffer_size = "256KiB"`
