### PR TITLE
fix(parsers/nagios): metrics will always return a supported status co…

### LINKED ISSUE #11061: Nagios parser returns not supported return codes and not enough information
### Relevant telegraf.conf

```toml
[[inputs.exec]]
commands = ['/opt/checks/nagios_check.pl']
interval = '30s'
timeout = '15s'
name_suffix = '__nagios_check'
data_format = 'nagios'
```

### Logs from Telegraf

```text
2022-05-03T11:55:04Z E! [inputs.exec] Failed to add nagios state: exec: get exit code: exit status 127
```

### System info

Telegraf 1.22.3, Oracle Linux Server 8.5

### Docker

_No response_

### Steps to reproduce

1. Remove dependencies a nagios check needs to be executes (depends on check)
2. Let telegraf execute the check

### Expected behavior

Metric 1: => nagios_state__tcp,host=home1 service_output="/some/path/telegraf/commands/check_tcp: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory",state=3i 1651661042000000000

Metric 2: => nagios_state__tcp,host=home1 service_output="fork/exec /some/path/telegraf/commands/check_tcp: permission denied",state=3i 1651665933000000000

### Actual behavior

Metric 1: => nagios_state__tcp,host=home1 service_output="",state=127i 1651661431000000000
Metric 2: => nagios_state__tcp,host=home1 service_output="" 1651665481000000000

#### 1. Return of not supported status codes:
As seen in the 'actual behavior' the status code '127' is returned. This is a not supported status code and should be converted into a '3' unknown status. (https://nagios-plugins.org/doc/guidelines.html , Plugin Return Codes )

#### 2. Missing error information:
The error message from this check execution is nowhere to be found. Not in the error.log file nor in service_output field from the metric. The message gets thrown away in the parsing process if it is not from type [ExitError](https://github.com/influxdata/telegraf/blob/6dc2b99549b3fc4684295ebcd2975cee96a1fa28/plugins/parsers/nagios/parser.go#L26).

#### 3. Error can only be found in error.log
The error can only be found in the telegraf error log when it occures. It should be shown in the service_output response itself.

### Solution
The Solution would be to return a 'unknown' state in case of an error and to put the error message into the service output field. No errors needs to be logged into the telegraf error.log because a unknown state with proper information is a valid checkresult.

### PR DESCRIPTION
**Pull request by Sakerdotes**
…de, error is now in service_output if needed #11061

### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #11061

 
- The nagios parser will now only return supported status codes. (https://nagios-plugins.org/doc/guidelines.html, Plugin Return Codes)
- All status codes other than 0,1,2,3 will automatically changed to 3 (unknown)
- More errors like the examples in the linked issue will be correct handled now.
- The Human readable error messages will now be added to the 'service_output' metric field. These errors wont be logged to the telegraf error.log anymore because they are useable metrics now and no real errors.

### CODE REVIEW

**Review by powersj — APPROVED** [review]
Thanks for this. This makes the nagios messages more clear and follows the spec. Thanks!

File: plugins/parsers/nagios/parser.go [hunk 1]
```diff
@@ -25,10 +24,7 @@ func getExitCode(err error) (int, error) {
 
 	ee, ok := err.(*exec.ExitError)
 	if !ok {
-		// If it is not an *exec.ExitError, then it must be
-		// an io error, but docs do not say anything about the
-		// exit code in this case.
-		return 0, err
+		return 3, err
```
Comment (reimda) [inline plugins/parsers/nagios/parser.go:27]: Could we declare a constant 'unknownExit=3' or something and use it instead of the bare 3s here and later in parser.go? I understand from the guidelines doc you linked in the PR description that it's a special value for nagios but that will not be clear to people who read this code in the future.

**Review by reimda — CHANGES_REQUESTED** [review]

File: plugins/parsers/nagios/parser.go (hunk 1 above)
Comment (Sakerdotes) [reply plugins/parsers/nagios/parser.go]: That is a good point. The bare value 3 is refactored into a const.

**Review by powersj — APPROVED** [review]
Thanks for the quick change!

**Review by sspaink — APPROVED** [review]
