### PR TITLE
fix(inputs.win_perf_counters): Ignore PdhCstatusNoInstance as well

### LINKED ISSUE #14557: [inputs.win_perf_counters] skip PdhCstatusNoInstance error
### Use Case

I plan to collect processes metrics on Windows host using configuration like below.
```
[agent]
  round_interval = true
  precision = "5s"
  interval = "5s"

[[inputs.win_perf_counters]]
  UseWildcardsExpansion = true

[[inputs.win_perf_counters.object]]
  UseRawValues = true
  ObjectName = "Process"
  Instances = ["OUTLOOK*", "python*"]
  Counters = [
    "ID Process",
    "% Processor Time",
]    

[[outputs.file]]
  files = ["stdout"]
  data_format = "csv"
  csv_timestamp_format = "2006-01-02T15:04:05Z07:00"
```

I tested this configuration with the following steps.
1. Start outlook and run `python -c "while True: i=1"`.
2. Then start telegraf with above configuration.
3. Wait until telegraf outputs records for 1st interval.
4. Then Quit outlook.

### Expected behavior

Telegraf continues to output records of running processes (matching "python*" in this case).

### Actual behavior

Telegraf outputs error logs shown below and stops to output records until counters are refreshed.
```
E! [inputs.win_perf_counters] Error in plugin: error during collecting data on host "localhost": error while getting value for counter "\\\\{my computer name}\\Process(OUTLOOK)\\ID Process": The specified instance of the performance object was not found.
```

### Additional info

I temporarily modified `isKnownCounterDataError` function to return true when errorcode is `PdhCstatusNoInstance` and ran same senario. In the case telegraf outputs warn logs shown below but continues to output records of python instance which has consistent value.
```
W! [inputs.win_perf_counters] Error while getting value for counter "\\\\{my computer name}\\Process(OUTLOOK)\\ID Process", instance: OUTLOOK, will skip metric: The specified instance of the performance object was not found.
```

Actually I have to set `Instances = ["*"]` in real case. In that case there are more chances to see `PdhCstatusNoInstance` error.

This is derived from https://github.com/influxdata/telegraf/issues/14486

### PR DESCRIPTION
**Pull request by powersj**
## Summary

Ignore the `PdhCstatusNoInstance` error so we do not stop collecting data for other counters. This PR builds on top of the change from #14526.

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #14557

### CODE REVIEW

File: plugins/inputs/win_perf_counters/win_perf_counters.go [hunk 1]
```diff
@@ -576,6 +576,7 @@ func isKnownCounterDataError(err error) bool {
 		pdhErr.ErrorCode == PdhCalcNegativeDenominator ||
 		pdhErr.ErrorCode == PdhCalcNegativeValue ||
 		pdhErr.ErrorCode == PdhCstatusInvalidData ||
+		pdhErr.ErrorCode == PdhCstatusNoInstance ||
 		pdhErr.ErrorCode == PdhNoData) {
 		return true
 	}
```
Comment (srebhan) [inline plugins/inputs/win_perf_counters/win_perf_counters.go:582]: This really should be converted to a switch statement one day.... But maybe not today. ;-)

**Review by srebhan — APPROVED** [review]
Thanks for the fix @powersj!
