### PR TITLE
fix: openweathermap add feels_like field

### LINKED ISSUE #10695: Add Feels_Like temperature
I would like to request that "Feels_Like" temperature is added to this plug-in.  I know it is available from OWM, I just do not see it in the plug-in data.

Thank you!

### PR DESCRIPTION
**Pull request by popey**
### Required for all PRs:

- [X] Updated associated README.md.
- [X] Wrote appropriate unit tests.
- [X] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #10695 

Added the necessary float data structure to hold the feels_like temperature data. 
Updated the test case to include the data during tests.
Ran locally and updated the README.md to include the actual data from the API.

### CODE REVIEW

**Comment by powersj** [comment]
Run `make check` and `make lint-branch` localy and resolve those issues and you should be good to go.

File: plugins/inputs/openweathermap/openweathermap_test.go [hunk 1]
```diff
@@ -671,6 +687,7 @@ func TestRainMetrics(t *testing.T) {
 				"humidity":              int64(87),
 				"pressure":              1007.0,
 				"temperature":           9.25,
+				"feels_like":            8.25
```
Comment (MyaLongmire) [inline plugins/inputs/openweathermap/openweathermap_test.go:690]:
```suggestion
				"feels_like":            8.25,
```

**Comment by popey** [comment]
Thanks for the feedback. All good I think?

```
alan@robot:~/Source/influxdata/telegraf-issue-10695/telegraf$ make check
go vet $(go list ./... | grep -v ./plugins/parsers/influx)
alan@robot:~/Source/influxdata/telegraf-issue-10695/telegraf$ PATH=$PATH:/usr/local/bin:/home/alan/go/bin make lint-branch
golangci-lint run --new-from-rev master
alan@robot:~/Source/influxdata/telegraf-issue-10695/telegraf$ 
```

**Review by powersj — APPROVED** [review]

**Review by MyaLongmire — APPROVED** [review]
