### PR TITLE
fix(inputs.smart): Include NVMe SMART data in smart_device measurement

### LINKED ISSUE #18180: Smart data not included for NVME devices
### Relevant telegraf.conf

```toml
[[inputs.smart]]
  use_sudo = true
```

### Logs from Telegraf

```text
2026-01-04T13:32:49Z W! Strict environment variable handling will be the new default starting with v1.38.0! If your configuration works with strict handling or you don't use environment variables it is safe to ignore this warning. Otherwise please explicitly add the --non-strict-env-handling flag!
2026-01-04T13:32:49Z I! Loading config: /etc/telegraf/telegraf.conf
2026-01-04T13:32:49Z I! Starting Telegraf 1.37.0 brought to you by InfluxData the makers of InfluxDB
2026-01-04T13:32:49Z I! Available plugins: 243 inputs, 9 aggregators, 35 processors, 26 parsers, 67 outputs, 8 secret-stores
2026-01-04T13:32:49Z I! Loaded inputs: cpu disk diskio kernel mem processes smart swap system
2026-01-04T13:32:49Z I! Loaded aggregators:
2026-01-04T13:32:49Z I! Loaded processors:
2026-01-04T13:32:49Z I! Loaded secretstores:
2026-01-04T13:32:49Z W! Outputs are not used in testing mode!
2026-01-04T13:32:49Z I! Tags enabled: host=topgw
2026-01-04T13:32:49Z W! [agent] The default value of 'skip_processors_after_aggregators' will change to 'true' with Telegraf v1.40.0! If you need the current default behavior, please explicitly set the option to 'false'!
2026-01-04T13:32:49Z D! [agent] Initializing plugins
2026-01-04T13:32:49Z D! [agent] Starting service inputs
> mem,host=topgw active=5781626880u,available=13408743424u,available_percent=80.75301452983399,buffered=823296u,cached=10665558016u,commit_limit=25499099136u,committed_as=4133441536u,dirty=1236992u,free=3095687168u,high_free=0u,high_total=0u,huge_page_size=2097152u,huge_pages_free=0u,huge_pages_total=0u,inactive=6921281536u,low_free=0u,low_total=0u,mapped=841416704u,page_tables=18698240u,shared=3403776u,slab=645513216u,sreclaimable=498339840u,sunreclaim=147173376u,swap_cached=53248u,swap_free=17193897984u,swap_total=17196781568u,total=16604635136u,used=3195891712u,used_percent=19.24698547016601,vmalloc_chunk=0u,vmalloc_total=35184372087808u,vmalloc_used=39251968u,write_back=0u,write_back_tmp=0u 1767533569000000000
> swap,host=topgw free=17193897984u,total=17196781568u,used=2883584u,used_percent=0.01676816088288178 1767533569000000000
> swap,host=topgw in=110592u,out=2150400u 1767533569000000000
> kernel,host=topgw boot_time=1767436648i,context_switches=316660341i,entropy_avail=256i,interrupts=203683756i,processes_forked=288601i 1767533569000000000
> diskio,host=topgw,name=sda io_time=120u,iops_in_progress=0u,merged_reads=0u,merged_writes=0u,read_bytes=8026112u,read_time=167u,reads=422u,weighted_io_time=167u,write_bytes=0u,write_time=0u,writes=0u 1767533569000000000
> diskio,host=topgw,name=sda1 io_time=40u,iops_in_progress=0u,merged_reads=0u,merged_writes=0u,read_bytes=2783232u,read_time=57u,reads=117u,weighted_io_time=57u,write_bytes=0u,write_time=0u,writes=0u 1767533569000000000
> diskio,host=topgw,name=nvme0n1p2 io_time=1961260u,iops_in_progress=0u,merged_reads=755u,merged_writes=6518u,read_bytes=45631270912u,read_time=2293618u,reads=896890u,weighted_io_time=8139129u,write_bytes=53058097152u,write_time=5820732u,writes=2881492u 1767533569000000000
> diskio,host=topgw,name=sdb1 io_time=87u,iops_in_progress=0u,merged_reads=0u,merged_writes=0u,read_bytes=2719744u,read_time=103u,reads=109u,weighted_io_time=103u,write_bytes=0u,write_time=0u,writes=0u 1767533569000000000
> diskio,host=topgw,name=sdb2 io_time=104u,iops_in_progress=0u,merged_reads=0u,merged_writes=0u,read_bytes=2719744u,read_time=110u,reads=113u,weighted_io_time=110u,write_bytes=0u,write_time=0u,writes=0u 1767533569000000000
> diskio,host=topgw,name=sda2 io_time=70u,iops_in_progress=0u,merged_reads=0u,merged_writes=0u,read_bytes=3600384u,read_time=84u,reads=178u,weighted_io_time=84u,write_bytes=0u,write_time=0u,writes=0u 1767533569000000000
> system,host=topgw load1=0.36,load15=0.2,load5=0.18,n_cpus=4i,n_physical_cpus=4i,n_unique_users=1i,n_users=1i 1767533569000000000
> system,host=topgw uptime=96921u 1767533569000000000
> system,host=topgw uptime_format="1 day,  2:55" 1767533569000000000
> diskio,host=topgw,name=nvme0n1,wwid=eui.0025385131406607 io_time=1772934u,iops_in_progress=0u,merged_reads=2792u,merged_writes=7308u,read_bytes=45660551680u,read_time=2293753u,reads=898067u,weighted_io_time=8390243u,write_bytes=53136948736u,write_time=5821740u,writes=2882015u 1767533569000000000
> diskio,host=topgw,name=nvme0n1p1 io_time=84u,iops_in_progress=0u,merged_reads=2020u,merged_writes=295u,read_bytes=7981568u,read_time=33u,reads=227u,weighted_io_time=780u,write_bytes=76701184u,write_time=747u,writes=484u 1767533569000000000
> diskio,host=topgw,name=nvme0n1p3 io_time=267u,iops_in_progress=0u,merged_reads=17u,merged_writes=495u,read_bytes=2961408u,read_time=12u,reads=120u,weighted_io_time=265u,write_bytes=2150400u,write_time=252u,writes=30u 1767533569000000000
> diskio,host=topgw,name=sdb io_time=274u,iops_in_progress=0u,merged_reads=0u,merged_writes=0u,read_bytes=8261632u,read_time=364u,reads=396u,weighted_io_time=364u,write_bytes=0u,write_time=0u,writes=0u 1767533569000000000
> diskio,host=topgw,name=loop0 io_time=44u,iops_in_progress=0u,merged_reads=0u,merged_writes=8u,read_bytes=5464064u,read_time=15u,reads=346u,weighted_io_time=88u,write_bytes=49152u,write_time=36u,writes=10u 1767533569000000000
> disk,device=efivarfs,fstype=efivarfs,host=topgw,mode=rw,path=/sys/firmware/efi/efivars free=150828u,inodes_free=0u,inodes_total=0u,inodes_used=0u,inodes_used_percent=0,total=196608u,used=40660u,used_percent=21.23370655080214 1767533569000000000
> disk,device=nvme0n1p2,fstype=btrfs,host=topgw,mode=rw,path=/ free=1093348511744u,inodes_free=0u,inodes_total=0u,inodes_used=0u,inodes_used_percent=0,total=1982126358528u,used=888324272128u,used_percent=44.82699057875231 1767533569000000000
> disk,device=nvme0n1p2,fstype=btrfs,host=topgw,mode=rw,path=/home free=1093348511744u,inodes_free=0u,inodes_total=0u,inodes_used=0u,inodes_used_percent=0,total=1982126358528u,used=888324272128u,used_percent=44.82699057875231 1767533569000000000
> disk,device=nvme0n1p2,fstype=btrfs,host=topgw,mode=rw,path=/mnt/topgw free=1093348511744u,inodes_free=0u,inodes_total=0u,inodes_used=0u,inodes_used_percent=0,total=1982126358528u,used=888324272128u,used_percent=44.82699057875231 1767533569000000000
> disk,device=nvme0n1p2,fstype=btrfs,host=topgw,mode=rw,path=/srv/http free=1093348511744u,inodes_free=0u,inodes_total=0u,inodes_used=0u,inodes_used_percent=0,total=1982126358528u,used=888324272128u,used_percent=44.82699057875231 1767533569000000000
> disk,device=nvme0n1p1,fstype=vfat,host=topgw,mode=rw,path=/boot free=1008590848u,inodes_free=0u,inodes_total=0u,inodes_used=0u,inodes_used_percent=0,total=1071628288u,used=63037440u,used_percent=5.882397908480744 1767533569000000000
> disk,device=nvme0n1p1,fstype=vfat,host=topgw,mode=rw,path=/efi free=1008590848u,inodes_free=0u,inodes_total=0u,inodes_used=0u,inodes_used_percent=0,total=1071628288u,used=63037440u,used_percent=5.882397908480744 1767533569000000000
> disk,device=nvme0n1p2,fstype=btrfs,host=topgw,mode=rw,path=/srv/minio free=1093348511744u,inodes_free=0u,inodes_total=0u,inodes_used=0u,inodes_used_percent=0,total=1982126358528u,used=888324272128u,used_percent=44.82699057875231 1767533569000000000
> disk,device=nvme0n1p2,fstype=btrfs,host=topgw,mode=rw,path=/var/lib/machines free=1093348511744u,inodes_free=0u,inodes_total=0u,inodes_used=0u,inodes_used_percent=0,total=1982126358528u,used=888324272128u,used_percent=44.82699057875231 1767533569000000000
> disk,device=nvme0n1p2,fstype=btrfs,host=topgw,mode=rw,path=/var/lib/virt/images free=1093348511744u,inodes_free=0u,inodes_total=0u,inodes_used=0u,inodes_used_percent=0,total=1982126358528u,used=888324272128u,used_percent=44.82699057875231 1767533569000000000
> disk,device=sda2,fstype=btrfs,host=topgw,mode=rw,path=/mnt/archive free=354298519552u,inodes_free=0u,inodes_total=0u,inodes_used=0u,inodes_used_percent=0,total=479834476544u,used=123783651328u,used_percent=25.891710435499604 1767533569000000000
> processes,host=topgw blocked=0i,dead=0i,idle=94i,paging=0i,running=0i,sleeping=128i,stopped=0i,total=222i,total_threads=351i,unknown=0i,zombies=0i 1767533569000000000
> smart_device,device=nvme0,host=topgw,model=Samsung\ SSD\ 970\ EVO\ Plus\ 2TB,serial_no=S6P1NS0W104313N exit_status=0i,health_ok=true,temp_c=45i 1767533569000000000
> smart_device,capacity=480103981056,device=sda,enabled=Enabled,host=topgw,model=KINGSTON\ SA400S37480G,power=ACTIVE,serial_no=50026B778436F93D,wwn=50026b778436f93d exit_status=0i,health_ok=true,power_cycle_count=272i,power_on_hours=16924i,read_error_rate=100i,realloc_event_count=0i,temp_c=20i,udma_crc_errors=0i,uncorrectable_errors=0i 1767533569000000000
2026-01-04T13:32:49Z D! [agent] Stopping service inputs
2026-01-04T13:32:49Z D! [agent] Input channel closed
2026-01-04T13:32:49Z D! [agent] Stopped Successfully
> cpu,cpu=cpu0,host=topgw usage_guest=0,usage_guest_nice=0,usage_idle=83.67346938708842,usage_iowait=2.040816326567545,usage_irq=0,usage_nice=0,usage_softirq=0,usage_steal=0,usage_system=6.122448979725837,usage_user=8.16326530627018 1767533570000000000
> cpu,cpu=cpu1,host=topgw usage_guest=0,usage_guest_nice=0,usage_idle=78.43137254929934,usage_iowait=3.9215686273758013,usage_irq=0,usage_nice=0,usage_softirq=1.9607843136879006,usage_steal=0,usage_system=1.9607843136879006,usage_user=13.725490195770721 1767533570000000000
> cpu,cpu=cpu2,host=topgw usage_guest=0,usage_guest_nice=0,usage_idle=88.00000000046566,usage_iowait=0,usage_irq=0,usage_nice=0,usage_softirq=2.0000000000038654,usage_steal=0,usage_system=5.999999999994543,usage_user=3.999999999996362 1767533570000000000
> cpu,cpu=cpu3,host=topgw usage_guest=0,usage_guest_nice=0,usage_idle=94.00000000023283,usage_iowait=0,usage_irq=0,usage_nice=0,usage_softirq=0,usage_steal=0,usage_system=3.999999999996362,usage_user=1.9999999999527063 1767533570000000000
> cpu,cpu=cpu-total,host=topgw usage_guest=0,usage_guest_nice=0,usage_idle=85.92964824266119,usage_iowait=1.5075376884478953,usage_irq=0.5025125628159651,usage_nice=0,usage_softirq=0.5025125628159651,usage_steal=0,usage_system=4.522613065355111,usage_user=7.03517587940066 1767533570000000000
```

### System info

Telegraf 1.37.0 (git: HEAD@f80cc596), Arch Linux

### Docker

_No response_

### Steps to reproduce

1. Run telegraf on system with NVME device.

### Expected behavior

Smart data should be included for NVME devices.

### Actual behavior

Measurement for NVME device includes only fields `exit_status`, `health_ok` and `temp_c`.

```
smart_device,device=nvme0,host=topgw,model=Samsung\ SSD\ 970\ EVO\ Plus\ 2TB,serial_no=S6P1NS0W104313N exit_status=0i,health_ok=true,temp_c=45i 1767533569000000000
```

### Additional info

Both `smartctl` and `nvme` report SMART data for the device, including power_on_hours, power cycle count, and additional relevant information. Unfortunately not structure exactly the same as SATA devices.

`telegraf` does not attempt to execute `nvme` for the device (checked with strace), but runs ` /usr/bin/smartctl --info --health --attributes -n standby --format=brief /dev/nvme0`. I note that the output of smartctl is different for SATA and NVME devices.

(Also, why not use JSON output?)

I realize that these are available with `attributes = true`, but it was a surprise to not get them in `smart_device`.

Output available from smartctl/nvme:

#### smartctl info from NVME device:

```
% /usr/bin/smartctl --info --health --attributes -n standby --format=brief /dev/nvme0
smartctl 7.5 2025-04-30 r5714 [x86_64-linux-6.12.62-1-lts] (local build)
Copyright (C) 2002-25, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       Samsung SSD 970 EVO Plus 2TB
Serial Number:                      S6P1NS0W104313N
Firmware Version:                   4B2QEXM7
PCI Vendor/Subsystem ID:            0x144d
IEEE OUI Identifier:                0x002538
Total NVM Capacity:                 2,000,398,934,016 [2.00 TB]
Unallocated NVM Capacity:           0
Controller ID:                      6
NVMe Version:                       1.3
Number of Namespaces:               1
Namespace 1 Size/Capacity:          2,000,398,934,016 [2.00 TB]
Namespace 1 Utilization:            898,037,108,736 [898 GB]
Namespace 1 Formatted LBA Size:     512
Namespace 1 IEEE EUI-64:            002538 5131406607
Local Time is:                      Sun Jan  4 14:55:29 2026 CET

=== START OF SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

SMART/Health Information (NVMe Log 0x02, NSID 0xffffffff)
Critical Warning:                   0x00
Temperature:                        45 Celsius
Available Spare:                    100%
Available Spare Threshold:          10%
Percentage Used:                    1%
Data Units Read:                    29,359,186 [15.0 TB]
Data Units Written:                 34,126,857 [17.4 TB]
Host Read Commands:                 94,502,164
Host Write Commands:                998,942,830
Controller Busy Time:               6,770
Power Cycles:                       160
Power On Hours:                     1,060
Unsafe Shutdowns:                   147
Media and Data Integrity Errors:    0
Error Information Log Entries:      0
Warning  Comp. Temperature Time:    0
Critical Comp. Temperature Time:    0
Temperature Sensor 1:               45 Celsius
Temperature Sensor 2:               50 Celsius
Thermal Temp. 1 Transition Count:   3
Thermal Temp. 2 Transition Count:   1
Thermal Temp. 1 Total Time:         3646
Thermal Temp. 2 Total Time:         15

```

#### smartctl info from SATA device:

```
% /usr/bin/smartctl --info --health --attributes -n standby --format=brief /dev/sda 
smartctl 7.5 2025-04-30 r5714 [x86_64-linux-6.12.62-1-lts] (local build)
Copyright (C) 2002-25, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Phison Driven SSDs
Device Model:     KINGSTON SA400S37480G
Serial Number:    50026B778436F93D
LU WWN Device Id: 5 0026b7 78436f93d
Firmware Version: S3B00101
User Capacity:    480,103,981,056 bytes [480 GB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    Solid State Device
TRIM Command:     Available
Device is:        In smartctl database 7.5/5706
ATA Version is:   ACS-3 T13/2161-D revision 4
SATA Version is:  SATA 3.2, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Sun Jan  4 14:54:28 2026 CET
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
Power mode is:    ACTIVE or IDLE

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

SMART Attributes Data Structure revision number: 1
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAGS    VALUE WORST THRESH FAIL RAW_VALUE
  1 Raw_Read_Error_Rate     -O--CK   100   100   000    -    100
  9 Power_On_Hours          -O--CK   100   100   000    -    16924
 12 Power_Cycle_Count       -O--CK   100   100   000    -    272
148 Unknown_Attribute       ------   100   100   000    -    0
149 Unknown_Attribute       ------   100   100   000    -    0
167 Write_Protect_Mode      ------   100   100   000    -    0
168 SATA_Phy_Error_Count    -O--C-   100   100   000    -    0
169 Bad_Block_Rate          ------   100   100   000    -    0
170 Bad_Blk_Ct_Lat/Erl      ------   100   100   010    -    0/0
172 Erase_Fail_Count        -O--CK   100   100   000    -    0
173 MaxAvgErase_Ct          ------   100   100   000    -    0
181 Program_Fail_Count      -O--CK   100   100   000    -    0
182 Erase_Fail_Count        ------   100   100   000    -    0
187 Reported_Uncorrect      -O--CK   100   100   000    -    0
192 Unsafe_Shutdown_Count   -O--C-   100   100   000    -    260
194 Temperature_Celsius     -O---K   019   061   000    -    19 (Min/Max 14/61)
196 Reallocated_Event_Count -O--CK   100   100   000    -    0
199 SATA_CRC_Error_Count    -O--CK   100   100   000    -    0
218 CRC_Error_Count         -O--CK   100   100   000    -    0
231 SSD_Life_Left           ------   100   100   000    -    100
233 Flash_Writes_GiB        -O--CK   100   100   000    -    468
241 Lifetime_Writes_GiB     -O--CK   100   100   000    -    550
242 Lifetime_Reads_GiB      -O--CK   100   100   000    -    468
244 Average_Erase_Count     ------   100   100   000    -    5
245 Max_Erase_Count         ------   100   100   000    -    17
246 Total_Erase_Count       ------   100   100   000    -    2795
                            ||||||_ K auto-keep
                            |||||__ C event count
                            ||||___ R error rate
                            |||____ S speed/performance
                            ||_____ O updated online
                            |______ P prefailure warning

```

#### smartctl info from NVME, JSON format:

```
% smartctl -A -j /dev/nvme0
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      5
    ],
    "pre_release": false,
    "svn_revision": "5714",
    "platform_info": "x86_64-linux-6.12.62-1-lts",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-A",
      "-j",
      "/dev/nvme0"
    ],
    "exit_status": 0
  },
  "local_time": {
    "time_t": 1767533686,
    "asctime": "Sun Jan  4 14:34:46 2026 CET"
  },
  "device": {
    "name": "/dev/nvme0",
    "info_name": "/dev/nvme0",
    "type": "nvme",
    "protocol": "NVMe"
  },
  "nvme_smart_health_information_log": {
    "nsid": -1,
    "critical_warning": 0,
    "temperature": 45,
    "available_spare": 100,
    "available_spare_threshold": 10,
    "percentage_used": 1,
    "data_units_read": 29358994,
    "data_units_written": 34125838,
    "host_reads": 94496638,
    "host_writes": 998903304,
    "controller_busy_time": 6770,
    "power_cycles": 160,
    "power_on_hours": 1060,
    "unsafe_shutdowns": 147,
    "media_errors": 0,
    "num_err_log_entries": 0,
    "warning_temp_time": 0,
    "critical_comp_time": 0,
    "temperature_sensors": [
      45,
      49
    ]
  },
  "temperature": {
    "current": 45
  },
  "spare_available": {
    "current_percent": 100,
    "threshold_percent": 10
  },
  "endurance_used": {
    "current_percent": 1
  },
  "power_cycle_count": 160,
  "power_on_time": {
    "hours": 1060
  }
}
```

#### smart-log retrieved using nvme-cli for same device:

```
% nvme smart-log -o json /dev/nvme0
{
  "critical_warning":0,
  "temperature":318,
  "avail_spare":100,
  "spare_thresh":10,
  "percent_used":1,
  "endurance_grp_critical_warning_summary":0,
  "data_units_read":29358997,
  "data_units_written":34125865,
  "host_read_commands":94496705,
  "host_write_commands":998904543,
  "controller_busy_time":6770,
  "power_cycles":160,
  "power_on_hours":1060,
  "unsafe_shutdowns":147,
  "media_errors":0,
  "num_err_log_entries":0,
  "warning_temp_time":0,
  "critical_comp_time":0,
  "temperature_sensor_1":318,
  "temperature_sensor_2":322,
  "thm_temp1_trans_count":3,
  "thm_temp2_trans_count":1,
  "thm_temp1_total_time":3646,
  "thm_temp2_total_time":15
}
```

### PR DESCRIPTION
**Pull request by skartikey**
## Summary

NVMe devices only emitted 3 fields (exit_status, health_ok, temp_c) in the smart_device measurement while SATA devices emitted ~15 fields. The NVMe/SAS parse functions ignored the deviceFields parameter, so data like power_on_hours and power_cycle_count only appeared in smart_attribute metrics.

Add an nvmeDeviceFields mapping and populate deviceFields after parsing NVMe attributes, promoting 11 key fields to the smart_device measurement.

## Checklist

- [x] No AI generated code was used in this PR
- [ ] AI generated code used in this PR follows the [InfluxData Policy on AI-Generated Code Contributions][policy]

[policy]: https://www.influxdata.com/ai-generated-code-contributions-policy

## Related issues

resolves #18180

### CODE REVIEW

File: plugins/inputs/smart/smart.go [hunk 1]
```diff
@@ -886,6 +902,11 @@ func (m *Smart) gatherDisk(acc telegraf.Accumulator, device string, wg *sync.Wai
 					if err := parse(fields, deviceFields, matches[2]); err != nil {
 						continue
 					}
+					if field, ok := nvmeDeviceFields[attr.Name]; ok {
+						if rawValue, ok := fields["raw_value"]; ok {
+							deviceFields[field] = rawValue
+						}
+					}
```
Comment (srebhan) [inline plugins/inputs/smart/smart.go]: Please use `found` here to indicate a map-lookup as `ok` is usually used for type-assertions...


```suggestion
					if name, found := nvmeDeviceFields[attr.Name]; found {
						if v, found := fields["raw_value"]; found {
							deviceFields[name] = v
						}
					}
```

**Review by srebhan — COMMENTED** [review]
Thanks @skartikey! Just one small comment...
