### PR TITLE
fix(inputs.docker): Fix incorrect CPU usage_percent for Podman containers

### LINKED ISSUE #17379: [[inputs.docker]] incorrect usage_percent when using podman
### Relevant telegraf.conf

```toml
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = "xxx"
  omit_hostname = false
[[outputs.influxdb]]
   urls = ["http://influxdb:8086"]  # the name of the host with influxdb
   database = "telegraf"
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.docker]]
   endpoint = "unix:///run/podman/podman.sock"
```

### Logs from Telegraf

```text
Jul 24 08:28:44 xxx systemd[1]: Starting Telegraf...
Jul 24 08:28:44 xxx telegraf[1345004]: 2025-07-24T08:28:44Z I! Loading config: /etc/telegraf/telegraf.conf
Jul 24 08:28:44 xxx telegraf[1345004]: 2025-07-24T08:28:44Z I! Starting Telegraf 1.35.2 brought to you by InfluxData the makers of InfluxDB
Jul 24 08:28:44 xxx telegraf[1345004]: 2025-07-24T08:28:44Z I! Available plugins: 238 inputs, 9 aggregators, 34 processors, 26 parsers, 65 outputs, 6 secret-stores
Jul 24 08:28:44 xxx telegraf[1345004]: 2025-07-24T08:28:44Z I! Loaded inputs: cpu disk diskio docker kernel mem processes swap system
Jul 24 08:28:44 xxx telegraf[1345004]: 2025-07-24T08:28:44Z I! Loaded aggregators:
Jul 24 08:28:44 xxx telegraf[1345004]: 2025-07-24T08:28:44Z I! Loaded processors:
Jul 24 08:28:44 xxx telegraf[1345004]: 2025-07-24T08:28:44Z I! Loaded secretstores:
Jul 24 08:28:44 xxx telegraf[1345004]: 2025-07-24T08:28:44Z I! Loaded outputs: influxdb
Jul 24 08:28:44 xxx telegraf[1345004]: 2025-07-24T08:28:44Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"xxx", Flush Interval:10s
Jul 24 08:28:44 xxx telegraf[1345004]: 2025-07-24T08:28:44Z W! [agent] The default value of 'skip_processors_after_aggregators' will change to 'true' with Telegraf v1.40.0! If >
Jul 24 08:28:44 xxx systemd[1]: Started Telegraf.
```

### System info

Telegraf 1.35.2, RHEL8.10, podman 4.9.4

### Docker

When using `podman` the value recorded in `usage_percent` does not appear to be the actual %CPU but rather the average %CPU since the container was started.

### Steps to reproduce

1. Create a new container and put it under load for several minutes, then let it idle.
2. Plot the container %CPU
```
SELECT "usage_percent" FROM "docker_container_cpu" WHERE ("host" = 'xxx') AND $timeFilter
```
3. Plot the system %CPU
``` 
SELECT "usage_system" FROM "cpu" WHERE ("host" = 'xxx' AND "cpu" = 'cpu-total') AND $timeFilter
```

### Expected behavior

The container %CPU should peak during a load test and then drop immediately when the test is over, closely matching the system %CPU

### Actual behavior

The container %CPU remains high after the test, even when the container is idle.

### Additional info

I actually think this might be a bug in `podman-stats` since you get the same behaviour in the 1st sample when streaming. But it does mean that the data reported by Telegraf is -also- wrong.

E.g. this is the output on a test system where I first noticed the data shown in Grafana didn't make much sense.

```
# podman stats --all --interval 1 --format "table {{.ID}}\t{{.CPU }}\t{{.AvgCPU}}\t{{.MemUsageBytes}}" --no-reset
ID            CPU                  AVG CPU             MEM USAGE / LIMIT
1aa772a0c85c  159.3999657351224    159.3999657351224   39.88GiB / 82GiB
ID            CPU                  AVG CPU             MEM USAGE / LIMIT
1aa772a0c85c  0.5486888953293112   159.39698221220848  39.88GiB / 82GiB
ID            CPU                  AVG CPU             MEM USAGE / LIMIT
1aa772a0c85c  0.2593970819529336   159.39399526163533  39.88GiB / 82GiB
ID            CPU                  AVG CPU             MEM USAGE / LIMIT
1aa772a0c85c  0.24709045580450345  159.39101059737825  39.88GiB / 82GiB
ID            CPU                  AVG CPU             MEM USAGE / LIMIT
1aa772a0c85c  0.23393135232549853  159.38802545420887  39.88GiB / 82GiB
ID            CPU                  AVG CPU             MEM USAGE / LIMIT
1aa772a0c85c  0.2443277612159435   159.38503951503566  39.88GiB / 82GiB
```

### PR DESCRIPTION
**Pull request by skartikey**
## Summary

Fixes incorrect CPU `usage_percent` metrics when using the Docker input plugin with Podman containers. The plugin now automatically detects Podman and implements an efficient caching mechanism to calculate accurate CPU percentages.

**Issue:**
Podman's Docker-compatible API behaves differently from Docker's native API:
  - **Docker**: Returns `PreCPUStats` from the previous collection interval (~1 second ago)
  - **Podman**: Returns `PreCPUStats` from when the container started

This caused Telegraf to report the average CPU usage since container start rather than current CPU usage, making the metrics essentially useless for monitoring actual container load.
Related to Podman issue: containers/podman#25709

**Solution:**
This PR implements an intelligent caching mechanism that:
  1. Automatically detects Podman using multiple heuristics (version strings, endpoint patterns, runtime indicators)
  2. Caches previous stats readings to calculate accurate interval-based CPU percentages
  3. Zero impact on Docker users - cache is only allocated when Podman is detected

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #17379

### CODE REVIEW

File: plugins/inputs/docker/docker.go [hunk 1]
```diff
@@ -124,6 +139,12 @@ func (d *Docker) Init() error {
 		}
 	}
 
+	// Set sensible defaults for Podman support
+	if d.PodmanCacheTTL == 0 {
+		d.PodmanCacheTTL = config.Duration(60 * time.Second)
+	}
```
Comment (srebhan) [inline plugins/inputs/docker/docker.go]: Can you please set this in `init` (lowercase) to allow the user to override this setting with _zero_ for indicating "keep the entries forever"?

Furthermore, I guess the user wants to set this to a value much higher than the collection `interval`, shouldn't he? Maybe that should be written somewhere either in the `sample.conf` documentation of the option or in the `README.md` file...

File: plugins/inputs/docker/docker.go [hunk 2]
```diff
@@ -333,6 +359,17 @@ func (d *Docker) gatherInfo(acc telegraf.Accumulator) error {
...
+	// Detect if we're connected to Podman
+	d.isPodman = d.detectPodman(&info)
+
+	if d.isPodman {
+		// Initialize stats cache only for Podman to save memory for Docker users
+		if d.statsCache == nil {
+			d.statsCache = make(map[string]*cachedContainerStats)
+		}
+		d.Log.Infof("Detected Podman engine (version: %s, name: %s), using stats caching for accurate CPU measurements", info.ServerVersion, info.Name)
+	}
```
Comment (srebhan) [inline plugins/inputs/docker/docker.go]: Can we please do this in `Start` to only handle this once?!? 

I would even do this unconditionally as the potential waste of memory is low, but I'm also fine with doing it only for Podman.

File: plugins/inputs/docker/docker.go [hunk 3]
```diff
@@ -87,11 +91,22 @@ type Docker struct {
...
+	isPodman        bool
 	filtersCreated  bool
 	labelFilter     filter.Filter
 	containerFilter filter.Filter
 	stateFilter     filter.Filter
 	objectTypes     []types.DiskUsageObject
+
+	// Stats cache for Podman CPU calculation
+	statsCache      map[string]*cachedContainerStats
+	statsCacheMutex sync.RWMutex
```
Comment (srebhan) [inline plugins/inputs/docker/docker.go]: You are not using this as RW-Mutex but only as a "normal" mutex, so please reflect this by using `sync.Mutex` as type.

File: plugins/inputs/docker/docker.go [hunk 4]
```diff
@@ -222,6 +243,11 @@ func (d *Docker) Gather(acc telegraf.Accumulator) error {
 	}
 	wg.Wait()
 
+	// Clean up stale cache entries for Podman
+	if d.isPodman {
+		d.cleanupStaleCache()
+	}
```
Comment (srebhan) [inline plugins/inputs/docker/docker.go]: I would make this the last item in `Gather` to not split the collection functions...

File: plugins/inputs/docker/docker.go [hunk 5]
```diff
@@ -1042,6 +1085,102 @@ func (d *Docker) getNewClient() (dockerClient, error) {
...
+// cleanupStaleCache removes expired entries from the stats cache
+func (d *Docker) cleanupStaleCache() {
+	if len(d.statsCache) == 0 {
+		return // Early exit if cache is empty
+	}
+
+	d.statsCacheMutex.Lock()
+	defer d.statsCacheMutex.Unlock()
+
+	cutoff := time.Now().Add(-time.Duration(d.PodmanCacheTTL) * 2) // 2x TTL for safety
```
Comment (srebhan) [inline plugins/inputs/docker/docker.go]: Why two times the TTL? This is kind of unexpected to the user isn't it? What you could do is to get the start time of `Gather` and pass it to this function but otherwise, it should be what the user sets...

File: plugins/inputs/docker/docker.go [hunk 6]
```diff
@@ -1042,6 +1085,102 @@ func (d *Docker) getNewClient() (dockerClient, error) {
...
+	for id, cached := range d.statsCache {
+		if cached.timestamp.Before(cutoff) {
+			delete(d.statsCache, id)
+			expiredCount++
+		}
+	}
+
+	if expiredCount > 0 {
+		d.Log.Debugf("Cleaned up %d expired entries from Podman stats cache", expiredCount)
+	}
```
Comment (srebhan) [inline plugins/inputs/docker/docker.go]: Please make this a "trace" message as people enable "debug" to see the buffer fullness in the logs... Futhermore, I would print this unconditionally to be able to follow what has been done... Maybe

```suggestion
	d.Log.Tracef("Cleaned up %d expired entries from Podman stats cache", expiredCount)
```

File: plugins/inputs/docker/docker.go (hunk 1 above)
Comment (skartikey) [reply plugins/inputs/docker/docker.go]: Good idea, changes made

File: plugins/inputs/docker/docker.go [hunk 7]
```diff
@@ -127,6 +142,38 @@ func (d *Docker) Init() error {
 	return nil
 }
 
+func (d *Docker) Start(_ telegraf.Accumulator) error {
```
Comment (srebhan) [inline plugins/inputs/docker/docker.go]:
```suggestion
func (d *Docker) Start(telegraf.Accumulator) error {
```

Comment (srebhan) [inline plugins/inputs/docker/docker.go]: You also need to implement the `Stop` function to fulfill the interface! Otherwise the start function will never be called!

File: plugins/inputs/docker/docker.go
Comment (srebhan) [inline plugins/inputs/docker/docker.go]: Do we really need to construct a new client in every cycle? I feel like this should be in `Start` and `Stop` shouldn't it?

File: plugins/inputs/docker/docker.go [hunk 8]
```diff
@@ -1042,13 +1100,108 @@ func (d *Docker) getNewClient() (dockerClient, error) {
...
+
+	// 5. Default to Docker for safety
+	return false
+}
+
+// fixPodmanCPUStats fixes Podman's CPU stats using cached previous stats
+func (d *Docker) fixPodmanCPUStats(containerID string, current *container.StatsResponse) {
+	if current == nil || d.statsCache == nil {
+		return // Safety check
+	}
```
Comment (srebhan) [inline plugins/inputs/docker/docker.go]: This should never happen right?

File: plugins/inputs/docker/README.md [hunk 9]
```diff
@@ -99,6 +105,27 @@ relevant if the telegraf configuration can be changed by untrusted users.
...
 
+### Podman Compatibility
+
+This plugin is compatible with Podman through its Docker-compatible API. When connected to Podman:
+
+- The plugin automatically detects Podman by examining the server version and endpoint
+- Uses an intelligent caching mechanism to calculate accurate CPU percentages
+- Configure Podman socket endpoint, for example: `endpoint = "unix:///run/podman/podman.sock"`
+
+**How it works**: Podman's stats API returns cumulative CPU values since container start. To calculate accurate current CPU usage, this plugin caches previous stats readings and calculates the difference between consecutive measurements.
```
Comment (srebhan) [inline plugins/inputs/docker/README.md]: Please wrap at 80 columns! Should you make this a [`NOTE` alert](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts)?

File: plugins/inputs/docker/README.md [hunk 10]
```diff
@@ -99,6 +105,27 @@ relevant if the telegraf configuration can be changed by untrusted users.
...
+**Configuration options**:
+```toml
+## Cache TTL for accurate CPU percentage calculation (default: 60s)
+## Stats caching is automatically enabled when Podman is detected
+## Set higher than your collection interval for accurate measurements
+## Set to 0 to keep cache entries forever (not recommended for dynamic environments)
+# podman_cache_ttl = "60s"
+```
+
+**Performance**: The caching approach scales efficiently to hundreds of containers without adding delays, unlike streaming approaches that would add latency per container.
```
Comment (srebhan) [inline plugins/inputs/docker/README.md]: I would remove this section as it does not add any information but sounds more like an "over-specific dementi". ;-)

**Comment by skartikey** [comment]
@srebhan I've incorporated the review comments, please have another look.

File: plugins/inputs/docker/docker.go [hunk 11]
```diff
@@ -127,31 +142,77 @@ func (d *Docker) Init() error {
...
+	d.engineHost = info.Name
+	d.serverVersion = info.ServerVersion
+
+	// Detect if we're connected to Podman
+	d.isPodman = d.detectPodman(&info)
+
+	if d.isPodman {
+		// Initialize stats cache only for Podman to save memory for Docker users
+		d.statsCache = make(map[string]*cachedContainerStats)
+		d.Log.Infof("Detected Podman engine (version: %s, name: %s), using stats caching for accurate CPU measurements", info.ServerVersion, info.Name)
```
Comment (srebhan) [inline plugins/inputs/docker/docker.go]: Should we make this a debug message?

```suggestion
		d.Log.Debugf("Detected Podman engine (version: %s, name: %s), using stats caching for accurate CPU measurements", info.ServerVersion, info.Name)
```

File: plugins/inputs/docker/docker.go [hunk 12]
```diff
@@ -127,31 +142,77 @@ func (d *Docker) Init() error {
...
+		d.client.Close()
+		d.client = nil
+	}
+
+	// Clear stats cache
+	if d.statsCache != nil {
+		d.statsCacheMutex.Lock()
+		d.statsCache = nil
+		d.statsCacheMutex.Unlock()
+	}
```
Comment (srebhan) [inline plugins/inputs/docker/docker.go]: I don't think we need this as the cache is reset on the next start isn't it? However, we can keep it if you insist. :-)

File: plugins/inputs/docker/docker.go [hunk 13]
```diff
@@ -127,31 +142,77 @@ func (d *Docker) Init() error {
...
+}
+
 func (d *Docker) Gather(acc telegraf.Accumulator) error {
+	// Ensure client is initialized (backward compatibility with tests)
```
Comment (srebhan) [inline plugins/inputs/docker/docker.go]: No! Tests should call `Start` instead! Please do not hamper readability of _actual_ plugin code to accommodate tests if possible!

File: plugins/inputs/docker/README.md [hunk 14]
```diff
@@ -99,6 +105,33 @@ relevant if the telegraf configuration can be changed by untrusted users.
...
+When connected to Podman:
+
+- The plugin automatically detects Podman by examining the server version and
+  endpoint
+- Uses an intelligent caching mechanism to calculate accurate CPU percentages
+- Configure Podman socket endpoint, for example:
+  `endpoint = "unix:///run/podman/podman.sock"`
+
+> [!NOTE]
+> **How it works**: Podman's stats API returns cumulative CPU values since
```
Comment (srebhan) [inline plugins/inputs/docker/README.md]: Please try to avoid visually catching elements if not absolutely necessary as this will reduce attention to actually important stuff so how about

```suggestion
> Podman's stats API returns cumulative CPU values since
```

or removing the alert altogether and just put some normal text. We could even remove the whole section starting from the `NOTE` as this describes an implementation detail not relevant to the normal user. Please remember, this is a _user_-facing document.

File: plugins/inputs/docker/README.md [hunk 15]
```diff
@@ -99,6 +105,33 @@ relevant if the telegraf configuration can be changed by untrusted users.
...
+
+**Configuration options**:
+
+```toml
+## Cache TTL for accurate CPU percentage calculation (default: 60s)
+## Stats caching is automatically enabled when Podman is detected
+## Set higher than your collection interval for accurate measurements
+## Set to 0 to keep cache entries forever (not recommended)
+# podman_cache_ttl = "60s"
+```
```
Comment (srebhan) [inline plugins/inputs/docker/README.md]: Please remove this as it is redundant and won't be updated if someone changes the option (e.g. the default or description).

File: plugins/inputs/docker/docker_test.go [hunk 16]
```diff
@@ -1596,3 +1597,167 @@ func TestDockerGatherDiskUsage(t *testing.T) {
...
+						ClientVersionF: func() string {
+							return "1.24.0"
+						},
+						CloseF: func() error {
+							return nil
+						},
+					}, nil
+				},
+				ContainerInclude: nil,
+				ContainerExclude: nil,
```
Comment (srebhan) [inline plugins/inputs/docker/docker_test.go]: Please remove as this is the default for Golang.

```suggestion
```

**Review by srebhan — COMMENTED** [review]
Thanks @skartikey! Some more small comments...
