### PR TITLE
fix: collapsed fields by calling more indepth function

### LINKED ISSUE #9470: some fields are collapsed in input.snmp_trap
Good day!

I have the following Telegraf topology: 
```
input.snmp_trap -> output.http
```

I have upgraded Telegraf agent within the version of 1.19.0. For the same SNMP and Telegraf configuration I have different SNMP trap messages.

For an old version of Telegraf (installed from apt repositories):
```
admin@st2-prod:~$ telegraf --version
Telegraf 1.19.0 (git: HEAD ed412d7f)

# SNMP trap message coming from output.http
{
  "metrics": [
    {
      "fields": {
        "enterprises.232.165.1.1.1": 0,
        "enterprises.232.165.1.1.2": "Test Trap",
        "enterprises.232.165.1.1.3": "http://172.17.17.7",
        "enterprises.232.165.1.1.4": "SN: 3C89411919       PN: 326528-002       MN: R5500 XR",
        "enterprises.232.165.1.1.5": "HP UPS Management Module",
        "sysName.0": "hpe_battery",
        "sysUpTimeInstance": 593913227
      },
      "name": "snmp_trap",
      "tags": {
        "agent_address": "172.17.17.7",
        "community": "public",
        "host": "matvey-pc",
        "mib": "SNMPv2-SMI",
        "name": "enterprises.232.165.0.3",
        "oid": ".1.3.6.1.4.1.232.165.0.3",
        "source": "172.17.17.7",
        "version": "1"
      },
      "timestamp": 1625566614
    }
  ]
}
```

For a new version of [nightly-telegraf](https://dl.influxdata.com/telegraf/nightlies/telegraf_nightly_amd64.deb):
```
admin@st2-prod:~$ telegraf --version
Telegraf unknown (git: master 17e86ab4)

# SNMP trap message coming from output.http
{
  "metrics": [
    {
      "fields": {
        "enterprises": "http://172.17.17.7",
        "sysName": "hpe_battery",
        "sysUpTimeInstance": 593979402
      },
      "name": "snmp_trap",
      "tags": {
        "agent_address": "172.17.17.7",
        "community": "public",
        "host": "matvey-pc",
        "mib": "SNMPv2-SMI",
        "name": "enterprises",
        "oid": ".1.3.6.1.4.1.232.165.0.3",
        "source": "172.17.17.7",
        "version": "1"
      },
      "timestamp": 1625567276
    }
  ]
}
``` 

Seems like the fields of `enterprises` are collapsed into the one in the new version of Telegraf. What do you think about?

### PR DESCRIPTION
**Pull request by MyaLongmire**
### Required for all PRs:

- [ ] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #9470 

Changes calling `node.RenderQualified` to calling `smi.RenderOid` as a suggestion of @Hipska

### CODE REVIEW

**Review by Hipska — COMMENTED** [review]
Hmm, no test changes and all tests succeed, so no change in behaviour? Do you have before and after output please?

**Comment by MyaLongmire** [comment]
I did not test against the user's mib. Just implemented the idea you were adamant about.

**Comment by Hipska** [comment]
Adamant? Sorry, if you have another or better solution, please be my guest and implement as You want. I just want to make sure the previous behaviour is restored..

File: internal/snmp/translate.go [hunk 1]
```diff
@@ -119,6 +119,13 @@ func TrapLookup(oid string) (e MibEntry, err error) {
 		return e, err
 	}
 
+	givenOid := strings.Split(oid, ".")
+	if givenOid[0] == "" {
+		givenOid = givenOid[1:]
+	}
+
+	foundOid := strings.Split(node.Oid.String(), ".")
```
Comment (Hipska) [inline internal/snmp/translate.go:127]: Oid is already an array, no need to concat and split again,
```suggestion
	givenOid := types.OidMustFromString(oid)
	foundOid := node.Oid
```

I think defining `foundOid` isn't needed in this case and `node.Oid` can be used directly later in that loop.

Also, `types.OidFromString` should be used, as the other one might panic.

File: internal/snmp/translate.go [hunk 2]
```diff
@@ -127,6 +134,20 @@ func TrapLookup(oid string) (e MibEntry, err error) {
...
+		for i := range foundOid {
+			if foundOid[i] == givenOid[i] {
+				s = s + 1
+			}
+		}
+	}
+
+	givenOid = givenOid[s:]
+
+	e.OidText = e.OidText + "." + strings.Join(givenOid, ".")
```
Comment (Hipska) [inline internal/snmp/translate.go:149]:
```suggestion
	e.OidText = e.OidText + "." + givenOid
```

Also wouldn't this resulting in `e.OidText` to always end with `.`?

File: plugins/inputs/snmp_trap/snmp_trap_test.go [hunk 3]
```diff
@@ -1357,14 +1357,14 @@ func TestGosmiSingleMib(t *testing.T) {
 			"snmp_trap", // name
 			map[string]string{ // tags
 				"oid":       ".1.3.6.1.6.3.1.1.5.1",
-				"name":      "coldStart",
+				"name":      "coldStart.1.1.5.1",
```
Comment (Hipska) [inline plugins/inputs/snmp_trap/snmp_trap_test.go:1360]: This doesn't make much sense. OID `.1.3.6.1.6.3.1.1.5.1` resolves to either `snmpModules.1.1.5.1` or `coldStart`.

File: plugins/inputs/snmp_trap/snmp_trap_test.go [hunk 4]
```diff
@@ -1357,14 +1357,14 @@ func TestGosmiSingleMib(t *testing.T) {
...
 				"mib":       "SNMPv2-MIB",
 				"version":   "2c",
 				"source":    "127.0.0.1",
 				"community": "public",
 			},
 			map[string]interface{}{ // fields
-				"sysUpTimeInstance": now,
+				"sysUpTimeInstance.1.3.0": now,
```
Comment (Hipska) [inline plugins/inputs/snmp_trap/snmp_trap_test.go:1367]: Similar remark here.

**Review by Hipska — CHANGES_REQUESTED** [review]
Good that you found a way without using `smi.RenderOid`, but I think there are still some mistakes.

**Comment by MyaLongmire** [comment]
I  don't think this is the right way to do either. I am going to mark this as a draft and try a different idea.

**Comment by Hipska** [comment]
The latest build even hangs when trying to start up..

**Comment by sspaink** [comment]
@reimda and I took a look at the failing tests and noticed that the test2 mibs file hadn't setup sysUpTimeInstance and coldstart correctly therefore it was adding the trailing numbers. The new code for `TrapLookup` looks good but we also need to add a test case for partially resolved names like the issue has (e.g. `enterprises.232.165.1.1.1`).

**Comment by Hipska** [comment]
Yes I know it needs to have a test. I asked @MyaLongmire to help with that.

File: internal/snmp/translate.go [hunk 5]
```diff
@@ -111,22 +111,30 @@ type MibEntry struct {
 }
 
 func TrapLookup(oid string) (e MibEntry, err error) {
-	var node gosmi.SmiNode
-	node, err = gosmi.GetNodeByOID(types.OidMustFromString(oid))
+	var givenOid types.Oid
+	if givenOid, err = types.OidFromString(oid); err != nil {
+		return e, fmt.Errorf("Could not convert OID %s: %w", oid, err)
```
Comment (srebhan) [inline internal/snmp/translate.go:116]: Error strings should start with a lowercase letter. ;-) Same for the other instances.

**Review by srebhan — COMMENTED** [review]
Hey @MyaLongmire, please make the error messages starting lowercase... :-)

**Review by Hipska — APPROVED** [review]

File: plugins/inputs/snmp_trap/snmp_trap_test.go [hunk 6]
```diff
@@ -1405,3 +1405,54 @@ func TestGosmiSingleMib(t *testing.T) {
...
+// 	given_oid = given_oid[s:]
+
+// 	OidText = OidText + "." + strings.Join(given_oid, ".")
+
+// 	fmt.Printf("s: %v\n", OidText)
+
+// 	println(MibName)
+
+// 	require.Error(t, err)
+// }
```
Comment (Hipska) [inline plugins/inputs/snmp_trap/snmp_trap_test.go:1458]: Remove this commented block?

File: internal/snmp/translate.go [hunk 7]
```diff
@@ -111,22 +111,29 @@ type MibEntry struct {
 }
 
 func TrapLookup(oid string) (e MibEntry, err error) {
```
Comment (Hipska) [inline internal/snmp/translate.go:113]: Wouldn't it be nicer if we just passed an `Oid` type instead of string?
```suggestion
func TrapLookup(givenOid types.Oid) (e MibEntry, err error) {
```

File: plugins/inputs/snmp_trap/snmp_trap_test.go (hunk 6 above)
Comment (srebhan) [reply plugins/inputs/snmp_trap/snmp_trap_test.go:1458]: Yes this should be removed.

**Review by srebhan — COMMENTED** [review]
The code looks good to me. I don't have any preference regarding @Hipska's comment on passing an OID struct instead of a string. However, the commented code section should be removed.

File: internal/snmp/translate.go (hunk 7 above)
Comment (reimda) [reply internal/snmp/translate.go:113]: The oid arrives from the trap throught gosnmp as a string. If we make TrapLookup take gosmi's types.Oid, we would have to convert from string to types.Oid everywhere TrapLookup (aka lookupFunc) is called. Makes sense to me to leave the argument a string.

File: internal/snmp/testdata/mibs/SNMPv2.mib [hunk 8]
```diff
@@ -0,0 +1,864 @@
...
+--
+-- March 2006,  Wen Xu
+--
+-- Copyright (c) 2006 by cisco Systems, Inc.
+-- All rights reserved.
+-- *****************************************************************
+--
+-- This mib was extracted from RFC 3418
+
+
```
Comment (reimda) [inline internal/snmp/testdata/mibs/SNMPv2.mib:13]: We can't accept files into the project that are copyright someone else.

I understand MIB files published as RFCs (like this) are copyright the Internet Society. They allow the MIB files to be extracted and used under certain legal conditions. To meet the conditions Linux distributions often don't include the MIB files. Instead, they have tools that download the RFCs and extract the MIBs (see debian package snmp-mibs-downloader). If we wanted to use MIBs from RFCs in our unit tests, I think we may need to do something similar.

We don't need the real MIBs for these tests. If we don't use the real MIBs we avoid copyright questions. That's why we wrote custom simple test mibs to use in unit tests (test2 and test.mib in plugins/inputs/snmp_trap).

**Review by reimda — APPROVED** [review]

File: internal/snmp/testdata/mibs/SNMPv2.mib (hunk 8 above)
Comment (Hipska) [reply internal/snmp/testdata/mibs/SNMPv2.mib]: Indeed, I agree!

File: internal/snmp/translate_test.go [hunk 9]
```diff
@@ -18,23 +18,23 @@ func TestTrapLookup(t *testing.T) {
...
 			},
 		},
 		{
 			name: "Known trap value OID",
 			oid:  ".1.3.6.1.2.1.1.3.0",
 			expected: MibEntry{
-				MibName: "SNMPv2-MIB",
-				OidText: "sysUpTime.0",
+				MibName: "TGTEST-MIB",
+				OidText: "sysUpTimeInstance",
```
Comment (Hipska) [inline internal/snmp/translate_test.go:30]: @reimda This test was specifically crafted to have a test with an `OidText` having 1 additional part (`.0`). The next test with enterprise tests if it also works with multiple additional parts. The previous test already tests an fully translatable OID.

File: internal/snmp/testdata/mibs/testmib [hunk 10]
```diff
@@ -0,0 +1,22 @@
+TGTEST-MIB DEFINITIONS ::= BEGIN
```
Comment (Hipska) [inline internal/snmp/testdata/mibs/testmib:1]: Thanks for a clear and working MIB!

Do you agree to change the name (and filename) to something like TELEGRAF-TEST-MIB. IMHO that looks a bit more comprehensive. (Could then also be used for inputs/snmp tests?)

File: internal/snmp/translate_test.go (hunk 9 above)
Comment (reimda) [reply internal/snmp/translate_test.go:30]: I understand that oids ending with .0 often or usually refer to an instance of a scalar object. Most of the time there is no name defined in the mib for the instance, but in this case, the SNMPv2 authors did include a name "sysUpTimeInstance".

I think it's a good idea to include a test for an instance of a scalar object that doesn't have a name in the mib. In that case we will need to choose a different oid than sysUpTime, and one that doesn't have a name (like xyzInstance) in the mib.

One way to do this would be to remove sysUpTimeInstance from the mib and use SysUpTime.0 like you had, but I think this would be confusing to people who are familiar with these common oids. Let's add a new oid scalar object that has a clearly fake name like "scalarObject" and use it in the test.

Does this sound good to you? Could you open a new PR to do this?

File: internal/snmp/testdata/mibs/testmib (hunk 10 above)
Comment (reimda) [reply internal/snmp/testdata/mibs/testmib:1]: The name doesn't matter to me.

I hope we can use it in the other tests too. We could refer to it in the other tests or make copies with changes needed for other tests.

I do want to keep the test files simple so people can quickly understand them. If we extend a single mib to cover all tests, it will need to be complex. I would rather different tests use different mibs if that means we can keep the mibs simple.

File: internal/snmp/translate_test.go (hunk 9 above)
Comment (Hipska) [reply internal/snmp/translate_test.go:30]: I would have preferred `sysUptime.0` but I understand your reasoning and agree to add a new object for that.
