### PR TITLE
fix(inputs.nftables): Handle named counter references in JSON output

### LINKED ISSUE #18135: [input.nftables] Fails to parse nft output including named counters
### Relevant telegraf.conf

```toml
[[inputs.nftables]]
  binary = "./nft-example.sh"
  tables = ["inet example"]

[[outputs.file]]
  files = ["stdout"]
```

### Logs from Telegraf

```text
2025-12-16T10:38:15Z D! [agent] Starting service inputs
2025-12-16T10:38:20Z E! [inputs.nftables] Error in plugin: parsing command output failed: unable to parse rule: json: cannot unmarshal string into Go struct field expr.expr.counter of type nftables.counter
```

### System info

Telegraf 1.38.0-1980bf81 (git: master@1980bf81)

### Docker

_No response_

### Steps to reproduce

To reproduce with mocked output:

`nft-example.sh`:

```
cat inet-example.json
```

`inet-example.json`:

```json
{
    "nftables": [
        {
            "metainfo": {
                "version": "1.1.6",
                "release_name": "Commodore Bullmoose #7",
                "json_schema_version": 1
            }
        },
        {
            "table": {
                "family": "inet",
                "name": "example",
                "handle": 7
            }
        },
        {
            "chain": {
                "family": "inet",
                "table": "example",
                "name": "input",
                "handle": 1,
                "type": "filter",
                "hook": "input",
                "prio": 0,
                "policy": "drop"
            }
        },
        {
            "counter": {
                "family": "inet",
                "name": "named_counter",
                "table": "example",
                "handle": 2,
                "comment": "named counter comment",
                "packets": 45470,
                "bytes": 55119375
            }
        },
        {
            "rule": {
                "family": "inet",
                "table": "example",
                "chain": "input",
                "handle": 3,
                "expr": [
                    {
                        "counter": "named_counter"
                    },
                    {
                        "accept": null
                    }
                ]
            }
        }
    ]
}
```

This is the output of `nft --json list table inet example` after it was created from this `nftables.conf`:

```
table inet example {
  counter named_counter {
    comment "named counter comment"
  }
  chain input {
    type filter hook input priority filter
    policy drop

    counter name named_counter accept
  }
}
```

### Expected behavior

Plugin finds no relevant counters (because as documented it looks for anonymous counters with comments).

Even better: Plugin finds the named counter and includes it in the output. Maybe the plugin should even exclusively look for named counters, rather than using comments to identify anonymous counters.

### Actual behavior

Plugin errors. Any additional supported statistics would not be reported.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skartikey**
## Summary

The nftables plugin failed to parse JSON output containing named counter references. In nftables, counters can be either:
  - Anonymous (inline objects): {"counter": {"packets": 100, "bytes": 5000}}
  - Named references (strings): {"counter": "my_counter_name"}

The plugin only handled anonymous counters, causing a parse error: "json: cannot unmarshal string into Go struct field"

Add custom UnmarshalJSON to the expr struct that detects and gracefully skips named counter references, since they don't contain inline statistics. Anonymous counters continue to be parsed and reported as before.

## Checklist

- [x] No AI generated code was used in this PR
- [ ] AI generated code used in this PR follows the [InfluxData Policy on AI-Generated Code Contributions][policy]

[policy]: https://www.influxdata.com/ai-generated-code-contributions-policy

## Related issues

resolves #18135

### CODE REVIEW

File: plugins/inputs/nftables/types.go [hunk 1]
```diff
@@ -58,6 +58,37 @@ type expr struct {
...
+		var c counter
+		if err := json.Unmarshal(raw.Counter, &c); err != nil {
+			return err
+		}
+		e.Cntr = &c
+	}
+
+	return nil
+}
+
```
Comment (srebhan) [inline plugins/inputs/nftables/types.go]: Shouldn't this be a function of the type `counter`?

**Review by srebhan — COMMENTED** [review]
Thanks @skartikey! One question...

File: plugins/inputs/nftables/types.go (hunk 1 above)
Comment (skartikey) [reply plugins/inputs/nftables/types.go]: @srebhan   You're right, that would be a cleaner design, having counter handle its own JSON polymorphism.                                                                                                         
                                                                                                                                                                                                          
  I'll add an `IsNamedRef bool` field (with `json:"-"`) to the `counter` struct. The flag is necessary because when Go unmarshals `"counter": "my_named_counter"` into `*counter`, it allocates the struct before calling `UnmarshalJSON`, so we can't use nil to distinguish named references from anonymous counters with zero stats. The flag makes this distinction explicit.                                          
 I'll update the PR.

File: plugins/inputs/nftables/types.go [hunk 2]
```diff
@@ -59,6 +59,21 @@ type expr struct {
 }
 
 type counter struct {
-	Packets int64 `json:"packets"`
-	Bytes   int64 `json:"bytes"`
+	Packets    int64 `json:"packets"`
+	Bytes      int64 `json:"bytes"`
+	IsNamedRef bool  `json:"-"`
```
Comment (srebhan) [inline plugins/inputs/nftables/types.go]: How about unexporting this struct member, which would make the `json` tag superfluous and marks this as an internal thing...

File: plugins/inputs/nftables/types.go [hunk 3]
```diff
@@ -59,6 +59,21 @@ type expr struct {
...
+// IsNamedRef flag since they don't contain inline statistics.
+func (c *counter) UnmarshalJSON(b []byte) error {
+	if len(b) > 0 && b[0] == '"' {
+		// Named counter reference - mark it and return
+		c.IsNamedRef = true
+		return nil
+	}
+	// Anonymous counter - parse the object
+	type counterAlias counter
+	return json.Unmarshal(b, (*counterAlias)(c))
```
Comment (srebhan) [inline plugins/inputs/nftables/types.go:80]: Why is the aliasing necessary? Is it to avoid an infinite unmarshalling loop? If so, please add a comment!

**Review by srebhan — COMMENTED** [review]
Two more comments...

File: plugins/inputs/nftables/types.go (hunk 3 above)
Comment (skartikey) [reply plugins/inputs/nftables/types.go:80]: yes that's correct, added the comment.
