### PR TITLE
Fix null value crash in postgresql_extensible input

### LINKED ISSUE #4688: postgresql_extensible crash on null value
### Relevant telegraf.conf:
```
[[outputs.influxdb]]
  urls = ["http://localhost:8086"]

  [[inputs.postgresql_extensible.query]]
    sqlquery='''
      SELECT *
      FROM pg_catalog.pg_stat_activity
    '''
    version=100
    withdbname=false
```

### System info:

```
Linux 4.4.0-1061-aws #70-Ubuntu SMP Fri May 25 21:47:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

telegraf --version
Telegraf v1.7.4 (git: release-1.7 578db7ef)
```

### Steps to reproduce:

drop target measurement on influxdb side and

select have to capture at least one column with null value, can be simplified:
```
    sqlquery='''
      SELECT
        null as datname
      FROM pg_catalog.pg_stat_activity
'''
```

### Expected behavior:
Insert null and did not crash
### Actual behavior:

```
# /usr/bin/telegraf -config /etc/telegraf/fr_usd_dev-5432.conf
panic: interface conversion: interface {} is nil, not string

goroutine 16 [running]:
github.com/influxdata/telegraf/plugins/inputs/postgresql_extensible.(*Postgresql).accRow(0xc42019e120, 0xc420304cc1, 0x10, 0x17ac460, 0xc4201c8780, 0x17c9f20, 0xc42048dce0, 0xc4203b8c00, 0x2, 0x2, ...)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/postgresql_extensible/postgresql_extensible.go:226 +0xe5e
github.com/influxdata/telegraf/plugins/inputs/postgresql_extensible.(*Postgresql).Gather(0xc42019e120, 0x17c9f20, 0xc42048dce0, 0x0, 0x0)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/postgresql_extensible/postgresql_extensible.go:184 +0x40e
github.com/influxdata/telegraf/agent.gatherWithTimeout.func1(0xc42017c540, 0xc42040cf00, 0x17c9f20, 0xc42048dce0)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:153 +0x47
created by github.com/influxdata/telegraf/agent.gatherWithTimeout
        /go/src/github.com/influxdata/telegraf/agent/agent.go:152 +0xd4

```
### Additional info:
crash is not written to logfile.

### PR DESCRIPTION
**Pull request by glinton**
Resolves #4688

### CODE REVIEW

File: plugins/inputs/postgresql_extensible/postgresql_extensible.go [hunk 1]
```diff
@@ -221,7 +221,7 @@ func (p *Postgresql) accRow(meas_name string, row scanner, acc telegraf.Accumula
 		return err
 	}
 
-	if columnMap["datname"] != nil {
+	if *columnMap["datname"] != nil {
```
Comment (danielnelson) [inline plugins/inputs/postgresql_extensible/postgresql_extensible.go]: I think this will crash if "datname" is not set, let's try to add a unit test for this function.

**Comment by danielnelson** [comment]
Can you add a test for if the datname column exists but isn't a string?

File: plugins/inputs/postgresql_extensible/postgresql_extensible.go [hunk 2]
```diff
@@ -221,9 +213,14 @@ func (p *Postgresql) accRow(meas_name string, row scanner, acc telegraf.Accumula
 		return err
 	}
 
-	if columnMap["datname"] != nil {
+	if c, ok := columnMap["datname"]; ok && *c != nil {
 		// extract the database name from the column map
-		dbname.WriteString((*columnMap["datname"]).(string))
+		switch (*c).(type) {
```
Comment (danielnelson) [inline plugins/inputs/postgresql_extensible/postgresql_extensible.go]: Use a variable `switch datname := (*c).(type) {` so you don't need to redo the conversion in the case.
