### PR TITLE
fix(inputs.postgresql): Default database definition

### LINKED ISSUE #9735: postgresql_extensible reports wrong database name
### Relevant telegraf.conf:

```toml
[[inputs.postgresql_extensible]]
address = "database=foo"
databases = ["foo"]
[[inputs.postgresql_extensible.query]]
sqlquery = "select 1"
```

### System info:

ba1484c

### Steps to reproduce:

1. Run the above configuration

### Expected behavior:

A metric should be emitted with the tag `db=foo`

### Actual behavior:

The metric is emitted with the tag `db=postgres`

### Additional info:

Apparently `postgres` is a hard-coded value when the statement you are executing does not return a `datname` field.  
This is wrong by all accounts as neither the db in the connection string, nor the db in the database list is `postgres`. In addition, this behavior (of relying on the `datname` column) is completely undocumented, and I had to go digging through the source to find out what was going on.

https://github.com/influxdata/telegraf/blob/ba1484c/plugins/inputs/postgresql_extensible/postgresql_extensible.go#L267-L283

### PR DESCRIPTION
**Pull request by aleksvagachev**
- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #9735 

- Fixing the default DB in the absence of the "datname" field. Now the default DB definition is taken from the connection string.
- Fixing the default database for pgbouncer. System database pgbouncer -> pgbouncer (https://www.pgbouncer.org/usage.html)

### CODE REVIEW

File: plugins/inputs/postgresql/postgresql.go [hunk 1]
```diff
@@ -139,15 +144,13 @@ func (p *Postgresql) accRow(row scanner, acc telegraf.Accumulator, columns []str
 			}
 		}
 	} else {
-		if _, err := dbname.WriteString("postgres"); err != nil {
+		database, err := p.GetConnectDatabase(tagAddress)
+		if err != nil {
+			return err
+		}
```
Comment (srebhan) [inline plugins/inputs/postgresql/postgresql.go:150]: Instead of doing the connection string parsing yourself I suggest to use the [`ParseConfig` function](https://pkg.go.dev/github.com/jackc/pgx/v5#ParseConfig) of the `pgx` library.

**Review by srebhan — COMMENTED** [review]
Thanks for your contribution @aleksvagachev! I have one suggestion regarding the database extraction...

**Comment by aleksvagachev** [comment]
@srebhan Thanks for the advice. Fixed getting the database through the ParseConfig function.

**Review by srebhan — APPROVED** [review]
Beautiful. Thanks for the fix @aleksvagachev!

**Review by powersj — APPROVED** [review]
