### PR TITLE
fix(inputs.modbus): Handle field-measurement definitions correctly on duplicate field check

### LINKED ISSUE #12091: inputs.modbus falsely reports duplicate field
### Relevant telegraf.conf

```toml
## Define a request sent to the device	  
  [[inputs.modbus.request]]
    slave_id = 9
    byte_order = "ABCD"
    register = "holding"
    fields = [
      { address=32000, measurement="Bitfield", name="State1", type="UINT16" },
      { address=32002, measurement="Bitfield", name="State2", type="UINT16" },
      { address=32003, measurement="Bitfield", name="State3", type="UINT32" },
      { address=32008, measurement="Bitfield", name="Alarm1", type="UINT16" },
      { address=32009, measurement="Bitfield", name="Alarm2", type="UINT16" },
      { address=32010, measurement="Bitfield", name="Alarm3", type="UINT16" },
      { address=32016, measurement="Voltage", name="PV1", type="INT16", scale=0.1, output="FLOAT64" },
      { address=32017, measurement="Current", name="PV1", type="INT16", scale=0.01, output="FLOAT64" },
      { address=32018, measurement="Voltage", name="PV2", type="INT16", scale=0.1, output="FLOAT64" },
      { address=32019, measurement="Current", name="PV2", type="INT16", scale=0.01, output="FLOAT64" },
      { address=32020, measurement="Voltage", name="PV3", type="INT16", scale=0.1, output="FLOAT64" },
      { address=32021, measurement="Current", name="PV3", type="INT16", scale=0.01, output="FLOAT64" },
      { address=32022, measurement="Voltage", name="PV4", type="INT16", scale=0.1, output="FLOAT64" },
      { address=32023, measurement="Current", name="PV4", type="INT16", scale=0.01, output="FLOAT64" },
      { address=32064, measurement="Power", name="DC", type="INT32", output="FLOAT64" },
      { address=32080, measurement="Power", name="AC", type="INT32", output="FLOAT64" },
      { address=32086, measurement="Power", name="Efficiency", type="UINT16", scale=0.01, output="FLOAT64" },
      { address=32087, measurement="Temp", name="Internal", type="INT16", scale=0.1, output="FLOAT64" },
      { address=32088, measurement="Resistance", name="Insulation", type="UINT16", scale=0.001, output="FLOAT64" },
      { address=32089, measurement="Status", name="Device", type="UINT16" },
    ]
    [inputs.modbus.request.tags]
      resource = "30KTL"
```

### Logs from Telegraf

```text
2022-10-24T15:50:16+02:00 E! [telegraf] Error running agent: could not initialize input inputs.modbus: configuraton invalid: field "PV1" duplicated in measurement "Current" (slave 9/"holding")
```

### System info

Telegraf 1.24.2, Debian 11

### Docker

_No response_

### Steps to reproduce

1. try to start telegraf with the shown inputs.modbus config

### Expected behavior

Telegraf should start with no error as the field PV1 is not duplicate in measurement Current

### Actual behavior

Error thrown (see log)

### Additional info

I triple checked the config and I'm 99.9% sure the config is correct and PV1 is not multiple

### PR DESCRIPTION
**Pull request by srebhan**
- [ ] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #12091 

This PR fixes an issue where measurements are defined for individual registers and handles those cases correctly. Before, only the global (plugin-instance/request-instance wide) measurement name was considered when checking for duplicate fields. Now also the field-individual measurement name is considered.

### CODE REVIEW

File: plugins/inputs/modbus/configuration_request.go [hunk 1]
```diff
@@ -269,13 +269,13 @@ func (c *ConfigurationPerRequest) fieldID(seed maphash.Seed, def requestDefiniti
 	if err := mh.WriteByte(0); err != nil {
 		return 0, err
 	}
-	if _, err := mh.WriteString(def.Measurement); err != nil {
+	if _, err := mh.WriteString(field.Measurement); err != nil {
```
Comment (sspaink) [inline plugins/inputs/modbus/configuration_request.go:272]: Not using the global measurement name shouldn't cause any backward compatibility issues?

Comment (srebhan) [reply plugins/inputs/modbus/configuration_request.go:272]: In the caller function, the field measurement is set to `def.Measurement` [by default](https://github.com/influxdata/telegraf/blob/a4956057b3d3c9414f2d23339b09e2baf7c3c07f/plugins/inputs/modbus/configuration_request.go#L107). So if the field _does not_ overwrite the measurement, the code is equivalent.
