### PR TITLE
fix(common.socket): Switch to context to simplify closing

### LINKED ISSUE #15509: memory leak
### Relevant telegraf.conf

```toml
[[inputs.socket_listener]]
service_address = "tcp://1.2.3.4:8085"
tls_cert = "/etc/ssl/host/cert.crt"
tls_key = "/etc/ssl/host/cert.key"
tls_allowed_cacerts = ["/usr/local/share/ca-certificates/edge-ca.crt"]
content_encoding = "gzip"
keep_alive_period = "2m"

[[inputs.socket_listener]]
service_address = "tcp://:8185"
tls_cert = "/etc/ssl/host/cert.crt"
tls_key = "/etc/ssl/host/cert.key"
tls_allowed_cacerts = ["/usr/local/share/ca-certificates/edge-ca.crt"]
content_encoding = "gzip"
keep_alive_period = "2m"
```

### Logs from Telegraf

```text
.
```

### System info

telegraf 1.30.2

### Docker

_No response_

### Steps to reproduce

1. run the above config for a while
2.
3.
...

### Expected behavior

no infinite memory growth

### Actual behavior

infinite memory growth

### Additional info

So a few days ago we encountered an OOM on one of our hosts, which was due to telegraf. On another host we also noticed elevated memory usage from telegraf, as it was consuming approximately 41GB. After enabling pprof, heap profiles were captured a few days apart (where telegraf had gone up to a few GB memory). It's clear from the profiles that there are several memory leaks going on.

heap

We did not start experiencing this issue until upgrading to version 1.30.2 from 1.26.0

### PR DESCRIPTION
**Pull request by srebhan**
## Summary

Switching the socket-close implementation to context cancellation avoids the complexity to keep track of all open connection. As side effects, this PR avoids the memory leak described in #15509 and avoids race conditions when closing the socket while new connections arrive.

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #15509

### CODE REVIEW

**Review by DStrand1 — APPROVED** [review]

File: plugins/common/socket/stream.go [hunk 1]
```diff
@@ -172,27 +173,33 @@ func (l *streamListener) setupConnection(conn net.Conn) error {
...
 
 func (l *streamListener) address() net.Addr {
 	return l.listener.Addr()
 }
 
 func (l *streamListener) close() error {
-	if err := l.listener.Close(); err != nil {
-		return err
+	if l.listener != nil {
+		l.listener.Close()
```
Comment (powersj) [inline plugins/common/socket/stream.go:196]: This will fail the linter if you rebase on master since you aren't checking the error right?

**Review by powersj — COMMENTED** [review]
Ran my reproducer for the issue with this branch for over 40k metrics and confirmed that the new pprof captures look better than before.

One inline comment about checking an error, otherwise I would like to land and get this in for our bug fix release next Monday.

Thanks!

**Review by powersj — APPROVED** [review]
