### PR TITLE
fix(inputs.tail): Handle missing read permissions for directory globbing

### LINKED ISSUE #9129: tail input fails silently when trying to read files inside directories with only execute permissions
The `tail` input (and I think that `logparser` does this too) fails silently when attempting to read a file inside a directory which has execute but not read permissions for the `telegraf` user.

I'm providing a Dockerfile to reproduce the issues below.

Below you can see the file permissions schema and proof that the user can read the file:

```bash
bash-4.2$ whoami
telegraf

bash-4.2$ namei -mo /var/log/apache2/error_log 
f: /var/log/apache2/error_log
 drwxr-xr-x root root /
 drwxr-xr-x root root var
 drwxr-xr-x root root log
 drwx--x--x root root apache2
 -rw-r--r-- root root error_log

bash-4.2$ tail /var/log/apache2/error_log 
example,result=ok value=1i
example,result=ok value=2i
example,result=ok value=3i
example,result=error value=3i
```
Below you can see that telegraf fails silently when running under the `telegraf` user:

```shell
bash-4.2$ /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d --debug --test-wait 15 
2021-04-14T10:15:01Z I! Starting Telegraf 1.18.1
2021-04-14T10:15:01Z D! [agent] Initializing plugins
2021-04-14T10:15:01Z D! [agent] Starting service inputs
2021-04-14T10:15:16Z D! [agent] Stopping service inputs
2021-04-14T10:15:16Z D! [agent] Input channel closed
2021-04-14T10:15:16Z D! [agent] Stopped Successfully
```

It works as expected with a `root` user or with a `/var/log/apache2` directory with read and execute permissions:

```shell
[root@400fb31a3249 /]# /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d --debug --test-wait 15 
2021-04-14T10:17:07Z I! Starting Telegraf 1.18.1
2021-04-14T10:17:07Z D! [agent] Initializing plugins
2021-04-14T10:17:07Z D! [agent] Starting service inputs
2021-04-14T10:17:07Z D! [inputs.tail] Tail added for "/var/log/apache2/error_log"
> example,host=400fb31a3249,path=/var/log/apache2/error_log,result=ok value=1i 1618395427510170897
> example,host=400fb31a3249,path=/var/log/apache2/error_log,result=ok value=2i 1618395427510177215
> example,host=400fb31a3249,path=/var/log/apache2/error_log,result=ok value=3i 1618395427510181769
> example,host=400fb31a3249,path=/var/log/apache2/error_log,result=error value=3i 1618395427510183472
2021-04-14T10:17:22Z D! [agent] Stopping service inputs
2021-04-14T10:17:22Z D! [inputs.tail] Tail removed for "/var/log/apache2/error_log"
2021-04-14T10:17:22Z D! [agent] Input channel closed
2021-04-14T10:17:22Z D! [agent] Stopped Successfully

```

### Relevant telegraf.conf:

```toml
[global_tags]

[agent]
  interval = "1s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false

[[outputs.file]]
  files = ["stdout"]

[[inputs.tail]]
  files = ["/var/log/apache2/error_log"]
  from_beginning = true
  watch_method = "poll"
  data_format = "influx"

```

### System info:

* CentOS 7
* Telegraf 1.18.1 (git: HEAD d3ac9a3f) 

### Steps to reproduce:

I've provided a Dockerfile that reproduces the error:

https://github.com/hluaces/telegraf-bug-9129

If you run the container (`docker run --rm local/bug-telegraf`) you'll see that no data is gathered after a 15s wait time.

If you run with as root inside the container (`docker run --rm -u root local/bug-telegraf`) you'll see that data is gathered.

You can move inside the container by using  `docker run --rm -it --entrypoint bash local/bug-telegraf`.

### Expected behavior:

* Data should be properly read by the `tail` input.
* A warning or error should be displayed in the case it cannot.

### Actual behavior:

* Data is not read.
* A warning is not shown in the file.

### LINKED ISSUE #16188: Tail input silently ignores files in unreadable directories
### Relevant telegraf.conf

```toml
[global_tags]

[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  flush_interval = "1s"
  precision = "1ms"

[[inputs.tail]]
  files = [ "/home/myuser/root_only/myfile" ]
  data_format = "influx"
```

### Logs from Telegraf

```text
$ telegraf --config telegraf-basic.conf  --debug --test
2024-11-13T11:36:48Z I! Loading config: telegraf-basic.conf
2024-11-13T11:36:48Z I! Starting Telegraf 1.32.2 brought to you by InfluxData the makers of InfluxDB
2024-11-13T11:36:48Z I! Available plugins: 235 inputs, 9 aggregators, 32 processors, 26 parsers, 62 outputs, 6 secret-stores
2024-11-13T11:36:48Z I! Loaded inputs: tail
2024-11-13T11:36:48Z I! Loaded aggregators:
2024-11-13T11:36:48Z I! Loaded processors:
2024-11-13T11:36:48Z I! Loaded secretstores:
2024-11-13T11:36:48Z W! Outputs are not used in testing mode!
2024-11-13T11:36:48Z I! Tags enabled: host=thinkpad
2024-11-13T11:36:48Z D! [agent] Initializing plugins
2024-11-13T11:36:48Z D! [agent] Starting service inputs
2024-11-13T11:36:48Z D! [agent] Stopping service inputs
2024-11-13T11:36:48Z D! [agent] Input channel closed
2024-11-13T11:36:48Z D! [agent] Stopped Successfully
```

### System info

Fedora 44, Telegraf 1.32.2

### Docker

_No response_

### Steps to reproduce

1. Run telegraf with a tail input that references a file in a directory to which there are no access permissions for the executing user

### Expected behavior

If a file can not be reached because of directory permissions then an error should be reported.

### Actual behavior

No error is reported, telegraf ignores the input

### Additional info

I couldn't work out in the code at what point the path access is evaluated, it seems to be quite early on as when the code is adding the tail, there are unaviodable error messages there that would be printed had it failed inside the Tail module.

This works fine for actual file permissions, but not for directories.

### PR DESCRIPTION
**Pull request by srebhan**
## Summary

Currently, the underlying doublestar library requires read permissions on directories either containing the given file or
on directories followed by globbing expressions like asterix (see https://github.com/bmatcuk/doublestar/issues/103).

This PR adds a workaround for cases where a file is specified directly without wildcards and adds a warning for all other
cases no producing any matching elements. The warning is only printed once as tailing an (initially) empty directory is a valid use-case.

## Checklist

- [x] No AI generated code was used in this PR
- [ ] AI generated code used in this PR follows the [InfluxData Policy on AI-Generated Code Contributions][policy]

[policy]: https://www.influxdata.com/ai-generated-code-contributions-policy

## Related issues

resolves #9129
resolves #16188

### CODE REVIEW

**Review by mstrandboge — APPROVED** [review]

File: plugins/inputs/tail/tail.go [hunk 1]
```diff
@@ -260,7 +267,22 @@ func (t *Tail) tailNewFiles() error {
...
+		// https://github.com/bmatcuk/doublestar/issues/103).
+		// However, if the given file does not require globbing we can try to
+		// keep the file directly.
+		matches := g.Match()
+		if len(matches) == 0 {
+			if _, err := os.Lstat(filepath); err == nil {
+				matches = append(matches, filepath)
+			} else if !t.nomatch[filepath] {
+				t.Log.Warnf("No file(s) matching pattern %q! Make sure Telegraf has read permissions on directories followed by wildcards!", filepath)
+				t.nomatch[filepath] = true
```
Comment (skartikey) [inline plugins/inputs/tail/tail.go:300]: tailNewFiles() is called from `Start()` - during initialization and `Gather()` - periodically by the agent (every collection interval)

This creates a race condition with concurrent map writes.

How about adding a mutex to protect the nomatch map, similar to tailersMutex:
```go
  nomatch      map[string]bool
  nomatchMutex sync.Mutex
```

File: plugins/inputs/tail/tail.go [hunk 2]
```diff
@@ -260,7 +267,22 @@ func (t *Tail) tailNewFiles() error {
...
+		// permissions on the directory to glob files (see
+		// https://github.com/bmatcuk/doublestar/issues/103).
+		// However, if the given file does not require globbing we can try to
+		// keep the file directly.
+		matches := g.Match()
+		if len(matches) == 0 {
+			if _, err := os.Lstat(filepath); err == nil {
+				matches = append(matches, filepath)
+			} else if !t.nomatch[filepath] {
+				t.Log.Warnf("No file(s) matching pattern %q! Make sure Telegraf has read permissions on directories followed by wildcards!", filepath)
```
Comment (skartikey) [inline plugins/inputs/tail/tail.go]: This warning appears even when the file doesn’t exist (not a permission issue) and no wildcards are used. The message should be more general or check for wildcards before suggesting permission issues.

```suggestion
				t.Log.Warnf("No file(s) matching pattern %q: %v", filepath, err)
```

File: plugins/inputs/tail/tail.go (hunk 1 above)
Comment (srebhan) [reply plugins/inputs/tail/tail.go:300]: @skartikey we could add the mutex but Telegraf plugin lifecycle will _always_ call `Start` before `Gather`, they should never run concurrently...

**Comment by srebhan** [comment]
@skartikey I reworked the error checking to actually check the directories before wildcards...

**Review by skartikey — APPROVED** [review]
