### PR TITLE
fix(inputs.chrony): Prevent race condition in concurrent gather calls

### LINKED ISSUE #17757: Panic in chrony input plugin
### Relevant telegraf.conf

```toml
[[inputs.chrony]]
  server = "unixgram:///var/run/chrony/chronyd.sock"
  dns_lookup = true
  metrics = ["activity", "tracking", "serverstats", "sources", "sourcestats"]
  socket_group = "wheel"
  socket_perms = "0660"
```

### Logs from Telegraf

```text
2025-10-03T04:00:30Z E! FATAL: [inputs.chrony] panicked: runtime error: index out of range [256] with length 256, Stack:
goroutine 236818 [running]:
github.com/influxdata/telegraf/agent.panicRecover(0x1400151c900)
	github.com/influxdata/telegraf/agent/agent.go:1202 +0x60
panic({0x10e9e5660?, 0x14001d2e090?})
	runtime/panic.go:783 +0x120
encoding/binary.(*encoder).uint8(...)
	encoding/binary/binary.go:792
encoding/binary.(*encoder).value(0x14002ab1d50, {0x10d8a3240?, 0x14000861620?, 0x10d43a6ae?})
	encoding/binary/binary.go:953 +0x89c
encoding/binary.(*encoder).value(0x14002ab1d50, {0x10da17980?, 0x14000861534?, 0x114a092a8?})
	encoding/binary/binary.go:919 +0x804
encoding/binary.(*encoder).value(0x14002ab1d50, {0x10e406d20?, 0x14000861520?, 0x10476e21c?})
	encoding/binary/binary.go:928 +0x714
encoding/binary.Write({0x10f133580, 0x14000b60480}, {0x10f218880, 0x114f0fa00}, {0x10ded1d20, 0x14000861520})
	encoding/binary/binary.go:431 +0x254
github.com/facebook/time/ntp/chrony.(*Client).Communicate(0x14000a49050, {0x10f16fc38, 0x14000861520})
	github.com/facebook/time@v0.0.0-20250903103710-a5911c32cdb9/ntp/chrony/client.go:38 +0x84
github.com/influxdata/telegraf/plugins/inputs/chrony.(*Chrony).gatherServerStats(0x14001380a00, {0x10f2319a0, 0x14000624220})
	github.com/influxdata/telegraf/plugins/inputs/chrony/chrony.go:298 +0x64
github.com/influxdata/telegraf/plugins/inputs/chrony.(*Chrony).Gather(0x14001380a00, {0x10f2319a0, 0x14000624220})
	github.com/influxdata/telegraf/plugins/inputs/chrony/chrony.go:156 +0x174
github.com/influxdata/telegraf/models.(*RunningInput).Gather(0x1400151c900, {0x10f2319a0, 0x14000624220})
	github.com/influxdata/telegraf/models/running_input.go:263 +0x210
github.com/influxdata/telegraf/agent.(*Agent).gatherOnce.func1()
	github.com/influxdata/telegraf/agent/agent.go:590 +0x50
created by github.com/influxdata/telegraf/agent.(*Agent).gatherOnce in goroutine 93
	github.com/influxdata/telegraf/agent/agent.go:588 +0xb4

goroutine 1 [sync.WaitGroup.Wait, 561 minutes]:
sync.runtime_SemacquireWaitGroup(0x1047458f0?, 0x80?)
	runtime/sema.go:114 +0x38
sync.(*WaitGroup).Wait(0x14001517150)
	sync/waitgroup.go:206 +0xa8
2025-10-03T04:00:30Z E! PLEASE REPORT THIS PANIC ON GITHUB with stack trace, configuration, and OS information: https://github.com/influxdata/telegraf/issues/new/choose
2025-10-03T04:00:30Z W! Telegraf is not permitted to read /opt/homebrew/etc/telegraf.d
2025-10-03T04:00:30Z I! Loading config: /opt/homebrew/etc/telegraf.conf
2025-10-03T04:00:30Z I! Starting Telegraf 1.36.2 brought to you by InfluxData the makers of InfluxDB
2025-10-03T04:00:30Z I! Available plugins: 238 inputs, 9 aggregators, 35 processors, 26 parsers, 65 outputs, 5 secret-stores
2025-10-03T04:00:30Z I! Loaded inputs: chrony cpu disk diskio dns_query http (4x) http_response internal mem net netstat ping processes swap system temp
2025-10-03T04:00:30Z I! Loaded aggregators:
2025-10-03T04:00:30Z I! Loaded processors:
2025-10-03T04:00:30Z I! Loaded secretstores:
2025-10-03T04:00:30Z I! Loaded outputs: influxdb_v2
2025-10-03T04:00:30Z I! Tags enabled: host=homelab.localdomain
2025-10-03T04:00:30Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"homelab.localdomain", Flush Interval:10s
runtime: g31113: frame.sp=0x14002389970 top=0x14002389fd0
	stack=[0x14002386000-0x1400238a000
fatal error: traceback did not unwind completely

runtime stack:
runtime.throw({0x10b526ee0?, 0x10465c960?})
	runtime/panic.go:1094 +0x34 fp=0x174a3ec00 sp=0x174a3ebd0 pc=0x104678af4
runtime.(*unwinder).finishInternal(0x174a3ecc8?)
	runtime/traceback.go:566 +0x10c fp=0x174a3ec40 sp=0x174a3ec00 pc=0x104667bdc
runtime.(*unwinder).next(0x174a3ed18?)
	runtime/traceback.go:447 +0x284 fp=0x174a3ecd0 sp=0x174a3ec40 pc=0x104667a34
runtime.copystack(0x14000a83500, 0x4000)
	runtime/stack.go:975 +0x2b8 fp=0x174a3edd0 sp=0x174a3ecd0 pc=0x10465d038
runtime.newstack()
	runtime/stack.go:1168 +0x35c fp=0x174a3ef00 sp=0x174a3edd0 pc=0x10465d4cc
runtime.morestack()
	runtime/asm_arm64.s:392 +0x70 fp=0x174a3ef00 sp=0x174a3ef00 pc=0x10467f470

goroutine 31113 gp=0x14000a83500 m=19 mp=0x14001d60808 [copystack]:
github.com/shirou/gopsutil/v4/internal/common.NewLibrary({0x105853d00, 0x0})
	github.com/shirou/gopsutil/v4@v4.25.8/internal/common/common_darwin.go:85 +0xcc fp=0x14002389960 sp=0x14002389960 pc=0x105853d0c
github.com/shirou/gopsutil/v4/internal/common.(*Library).Close(...)
	github.com/shirou/gopsutil/v4@v4.25.8/internal/common/common_darwin.go:113
github.com/shirou/gopsutil/v4/sensors.TemperaturesWithContext.deferwrap1()
	github.com/shirou/gopsutil/v4@v4.25.8/sensors/sensors_darwin_arm64.go:23 +0x30 fp=0x14002389970 sp=0x14002389960 pc=0x108960d80
github.com/shirou/gopsutil/v4/sensors.TemperaturesWithContext({0x14000f40e58?, 0x10460d53c?})
	github.com/shirou/gopsutil/v4@v4.25.8/sensors/sensors_darwin_arm64.go:54 +0x6b4 fp=0x14002389e10 sp=0x14002389970 pc=0x108960bc4
created by github.com/influxdata/telegraf/agent.(*Agent).gatherOnce in goroutine 89
	github.com/influxdata/telegraf/agent/agent.go:588 +0xb4

goroutine 1 gp=0x140000021c0 m=nil [sync.WaitGroup.Wait, 72 minutes]:
runtime.gopark(0x1148d2020?, 0x140015facc0?, 0x80?, 0xe4?, 0x14000658e80?)
	runtime/proc.go:460 +0xc0 fp=0x1400238cbe0 sp=0x1400238cbc0 pc=0x104678c00
runtime.goparkunlock(...)
	runtime/proc.go:466
runtime.semacquire1(0x140015ffcb8, 0x0, 0x1, 0x0, 0x19)
	runtime/sema.go:192 +0x204 fp=0x1400238cc30 sp=0x1400238cbe0 pc=0x1046578f4
sync.runtime_SemacquireWaitGroup(0x10464d8f0?, 0xc0?)
	runtime/sema.go:114 +0x38 fp=0x1400238cc70 sp=0x1400238cc30 pc=0x10467a848
sync.(*WaitGroup).Wait(0x140015ffcb0)
	sync/waitgroup.go:206 +0xa8 fp=0x1400238cca0 sp=0x1400238cc70 pc=0x10469be28
github.com/influxdata/telegraf/agent.(*Agent).Run(0x1400105df78, {0x10f0ecff0, 0x14001499220})
	github.com/influxdata/telegraf/agent/agent.go:208 +0x7d0 fp=0x1400238ce60 sp=0x1400238cca0 pc=0x104e43ad0
main.(*Telegraf).runAgent(0x140010c9080, {0x10f0ecff0, 0x14001499220}, 0x0?)
	github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:565 +0x1184 fp=0x1400238d230 sp=0x1400238ce60 pc=0x10b388824
main.(*Telegraf).reloadLoop(0x140010c9080)
	github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:207 +0x1b8 fp=0x1400238d410 sp=0x1400238d230 pc=0x10b385288
main.(*Telegraf).Run(0x140010c9080)
	github.com/influxdata/telegraf/cmd/telegraf/telegraf_posix.go:20 +0xb0 fp=0x1400238d460 sp=0x1400238d410 pc=0x10b3892b0
main.runApp.func1(0x1400143cf40)
	github.com/influxdata/telegraf/cmd/telegraf/main.go:261 +0x9dc fp=0x1400238da10 sp=0x1400238d460 pc=0x10b380e2c
github.com/urfave/cli/v2.(*Command).Run(0x1400149ec60, 0x1400143cf40, {0x140001ce050, 0x5, 0x5})
	github.com/urfave/cli/v2@v2.27.7/command.go:276 +0x580 fp=0x1400238dc70 sp=0x1400238da10 pc=0x1047c2190
github.com/urfave/cli/v2.(*App).RunContext(0x14000ca5600, {0x10f0ecd00, 0x114e17a00}, {0x140001ce050, 0x5, 0x5})
	github.com/urfave/cli/v2@v2.27.7/app.go:333 +0x4c8 fp=0x1400238dcd0 sp=0x1400238dc70 pc=0x1047bf318
github.com/urfave/cli/v2.(*App).Run(...)
	github.com/urfave/cli/v2@v2.27.7/app.go:307
main.runApp({0x140001ce050, 0x5, 0x5}, {0x10f03b1e8, 0x1400019c068}, {0x10f075d38, 0x1400105dce0}, {0x10f075d60, 0x140012e6900}, {0x10f0ecbb0, ...})
	github.com/influxdata/telegraf/cmd/telegraf/main.go:419 +0xd44 fp=0x1400238dec0 sp=0x1400238dcd0 pc=0x10b380244
main.main()
	github.com/influxdata/telegraf/cmd/telegraf/main.go:433 +0xec fp=0x1400238df40 sp=0x1400238dec0 pc=0x10b38174c
runtime.main()
	runtime/proc.go:285 +0x278 fp=0x1400238dfd0 sp=0x1400238df40 pc=0x104642d88
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x1400238dfd0 sp=0x1400238dfd0 pc=0x104681834

goroutine 2 gp=0x14000002c40 m=nil [force gc (idle), 11 minutes]:
runtime.gopark(0x22406b427fa19?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:460 +0xc0 fp=0x140000f0f90 sp=0x140000f0f70 pc=0x104678c00
runtime.goparkunlock(...)
	runtime/proc.go:466
runtime.forcegchelper()
	runtime/proc.go:373 +0xb4 fp=0x140000f0fd0 sp=0x140000f0f90 pc=0x1046430d4
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x140000f0fd0 sp=0x140000f0fd0 pc=0x104681834
created by runtime.init.7 in goroutine 1
	runtime/proc.go:361 +0x24

goroutine 3 gp=0x14000003180 m=nil [GC sweep wait]:
runtime.gopark(0x114892c01?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:460 +0xc0 fp=0x140000f1760 sp=0x140000f1740 pc=0x104678c00
runtime.goparkunlock(...)
	runtime/proc.go:466
runtime.bgsweep(0x1400011c000)
	runtime/mgcsweep.go:323 +0x104 fp=0x140000f17b0 sp=0x140000f1760 pc=0x10462b2c4
runtime.gcenable.gowrap1()
	runtime/mgc.go:212 +0x28 fp=0x140000f17d0 sp=0x140000f17b0 pc=0x10461ed88
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x140000f17d0 sp=0x140000f17d0 pc=0x104681834
created by runtime.gcenable in goroutine 1
	runtime/mgc.go:212 +0x6c

goroutine 4 gp=0x14000003340 m=nil [GC scavenge wait]:
runtime.gopark(0x14f0ad?, 0xbb50e?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:460 +0xc0 fp=0x140000f1f60 sp=0x140000f1f40 pc=0x104678c00
runtime.goparkunlock(...)
	runtime/proc.go:466
runtime.(*scavengerState).park(0x1148a35e0)
	runtime/mgcscavenge.go:425 +0x5c fp=0x140000f1f90 sp=0x140000f1f60 pc=0x104628ddc
runtime.bgscavenge(0x1400011c000)
	runtime/mgcscavenge.go:658 +0xac fp=0x140000f1fb0 sp=0x140000f1f90 pc=0x10462937c
runtime.gcenable.gowrap2()
	runtime/mgc.go:213 +0x28 fp=0x140000f1fd0 sp=0x140000f1fb0 pc=0x10461ed28
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x140000f1fd0 sp=0x140000f1fd0 pc=0x104681834
created by runtime.gcenable in goroutine 1
	runtime/mgc.go:213 +0xac

goroutine 18 gp=0x14000182380 m=nil [GOMAXPROCS updater (idle), 73 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:460 +0xc0 fp=0x140000ec770 sp=0x140000ec750 pc=0x104678c00
runtime.goparkunlock(...)
	runtime/proc.go:466
runtime.updateMaxProcsGoroutine()
	runtime/proc.go:6706 +0xf4 fp=0x140000ec7d0 sp=0x140000ec770 pc=0x104651ba4
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x140000ec7d0 sp=0x140000ec7d0 pc=0x104681834
created by runtime.defaultGOMAXPROCSUpdateEnable in goroutine 1
	runtime/proc.go:6694 +0x48

goroutine 19 gp=0x140001828c0 m=nil [finalizer wait, 73 minutes]:
runtime.gopark(0x140000f05b8?, 0x108cf067c?, 0x0?, 0x64?, 0xa?)
	runtime/proc.go:460 +0xc0 fp=0x140000f0580 sp=0x140000f0560 pc=0x104678c00
runtime.runFinalizers()
	runtime/mfinal.go:210 +0x104 fp=0x140000f07d0 sp=0x140000f0580 pc=0x10461dd74
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x140000f07d0 sp=0x140000f07d0 pc=0x104681834
created by runtime.createfing in goroutine 1
	runtime/mfinal.go:172 +0x78

goroutine 34 gp=0x14000884000 m=nil [GC worker (idle)]:
runtime.gopark(0x114e23320?, 0x1?, 0x62?, 0x2f?, 0x0?)
	runtime/proc.go:460 +0xc0 fp=0x1400195df10 sp=0x1400195def0 pc=0x104678c00
runtime.gcBgMarkWorker(0x14000882000)
	runtime/mgc.go:1463 +0xe0 fp=0x1400195dfb0 sp=0x1400195df10 pc=0x104621400
runtime.gcBgMarkStartWorkers.gowrap1()
	runtime/mgc.go:1373 +0x28 fp=0x1400195dfd0 sp=0x1400195dfb0 pc=0x1046212e8
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x1400195dfd0 sp=0x1400195dfd0 pc=0x104681834
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1373 +0x140

goroutine 5 gp=0x14000003c00 m=nil [GC worker (idle)]:
runtime.gopark(0x114e23320?, 0x1?, 0x72?, 0xee?, 0x0?)
	runtime/proc.go:460 +0xc0 fp=0x14003018f10 sp=0x14003018ef0 pc=0x104678c00
runtime.gcBgMarkWorker(0x14000882000)
	runtime/mgc.go:1463 +0xe0 fp=0x14003018fb0 sp=0x14003018f10 pc=0x104621400
runtime.gcBgMarkStartWorkers.gowrap1()
	runtime/mgc.go:1373 +0x28 fp=0x14003018fd0 sp=0x14003018fb0 pc=0x1046212e8
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14003018fd0 sp=0x14003018fd0 pc=0x104681834
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1373 +0x140

goroutine 20 gp=0x14000183340 m=nil [GC worker (idle)]:
runtime.gopark(0x22486c07fa177?, 0x3?, 0xea?, 0x5d?, 0x0?)
	runtime/proc.go:460 +0xc0 fp=0x1400301ef10 sp=0x1400301eef0 pc=0x104678c00
runtime.gcBgMarkWorker(0x14000882000)
	runtime/mgc.go:1463 +0xe0 fp=0x1400301efb0 sp=0x1400301ef10 pc=0x104621400
runtime.gcBgMarkStartWorkers.gowrap1()
	runtime/mgc.go:1373 +0x28 fp=0x1400301efd0 sp=0x1400301efb0 pc=0x1046212e8
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x1400301efd0 sp=0x1400301efd0 pc=0x104681834
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1373 +0x140

goroutine 35 gp=0x140008841c0 m=nil [GC worker (idle)]:
runtime.gopark(0x22486c07b6a0a?, 0x1?, 0x27?, 0x31?, 0x0?)
	runtime/proc.go:460 +0xc0 fp=0x1400297ff10 sp=0x1400297fef0 pc=0x104678c00
runtime.gcBgMarkWorker(0x14000882000)
	runtime/mgc.go:1463 +0xe0 fp=0x1400297ffb0 sp=0x1400297ff10 pc=0x104621400
runtime.gcBgMarkStartWorkers.gowrap1()
	runtime/mgc.go:1373 +0x28 fp=0x1400297ffd0 sp=0x1400297ffb0 pc=0x1046212e8
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x1400297ffd0 sp=0x1400297ffd0 pc=0x104681834
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1373 +0x140

goroutine 21 gp=0x14000183500 m=nil [GC worker (idle), 7 minutes]:
runtime.gopark(0x224379d1fc4b8?, 0x1?, 0x90?, 0x44?, 0x0?)
	runtime/proc.go:460 +0xc0 fp=0x14001958f10 sp=0x14001958ef0 pc=0x104678c00
runtime.gcBgMarkWorker(0x14000882000)
	runtime/mgc.go:1463 +0xe0 fp=0x14001958fb0 sp=0x14001958f10 pc=0x104621400
runtime.gcBgMarkStartWorkers.gowrap1()
	runtime/mgc.go:1373 +0x28 fp=0x14001958fd0 sp=0x14001958fb0 pc=0x1046212e8
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001958fd0 sp=0x14001958fd0 pc=0x104681834
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1373 +0x140

goroutine 6 gp=0x14000003dc0 m=nil [GC worker (idle), 2 minutes]:
runtime.gopark(0x2246ad2bdea8d?, 0x1?, 0x93?, 0x20?, 0x0?)
	runtime/proc.go:460 +0xc0 fp=0x140022f9f10 sp=0x140022f9ef0 pc=0x104678c00
runtime.gcBgMarkWorker(0x14000882000)
	runtime/mgc.go:1463 +0xe0 fp=0x140022f9fb0 sp=0x140022f9f10 pc=0x104621400
runtime.gcBgMarkStartWorkers.gowrap1()
	runtime/mgc.go:1373 +0x28 fp=0x140022f9fd0 sp=0x140022f9fb0 pc=0x1046212e8
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x140022f9fd0 sp=0x140022f9fd0 pc=0x104681834
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1373 +0x140

goroutine 36 gp=0x14000884380 m=nil [GC worker (idle)]:
runtime.gopark(0x22486c07f9542?, 0x3?, 0x46?, 0xa?, 0x0?)
	runtime/proc.go:460 +0xc0 fp=0x14002cb9f10 sp=0x14002cb9ef0 pc=0x104678c00
runtime.gcBgMarkWorker(0x14000882000)
	runtime/mgc.go:1463 +0xe0 fp=0x14002cb9fb0 sp=0x14002cb9f10 pc=0x104621400
runtime.gcBgMarkStartWorkers.gowrap1()
	runtime/mgc.go:1373 +0x28 fp=0x14002cb9fd0 sp=0x14002cb9fb0 pc=0x1046212e8
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14002cb9fd0 sp=0x14002cb9fd0 pc=0x104681834
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1373 +0x140

goroutine 37 gp=0x14000884540 m=nil [GC worker (idle)]:
runtime.gopark(0x22486c07be499?, 0x1?, 0x25?, 0x69?, 0x0?)
	runtime/proc.go:460 +0xc0 fp=0x1400088bf10 sp=0x1400088bef0 pc=0x104678c00
runtime.gcBgMarkWorker(0x14000882000)
	runtime/mgc.go:1463 +0xe0 fp=0x1400088bfb0 sp=0x1400088bf10 pc=0x104621400
runtime.gcBgMarkStartWorkers.gowrap1()
	runtime/mgc.go:1373 +0x28 fp=0x1400088bfd0 sp=0x1400088bfb0 pc=0x1046212e8
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x1400088bfd0 sp=0x1400088bfd0 pc=0x104681834
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1373 +0x140

goroutine 22 gp=0x140001836c0 m=nil [GC worker (idle)]:
runtime.gopark(0x22486c07adbf3?, 0x3?, 0x34?, 0x21?, 0x0?)
	runtime/proc.go:460 +0xc0 fp=0x14001781f10 sp=0x14001781ef0 pc=0x104678c00
runtime.gcBgMarkWorker(0x14000882000)
	runtime/mgc.go:1463 +0xe0 fp=0x14001781fb0 sp=0x14001781f10 pc=0x104621400
runtime.gcBgMarkStartWorkers.gowrap1()
	runtime/mgc.go:1373 +0x28 fp=0x14001781fd0 sp=0x14001781fb0 pc=0x1046212e8
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001781fd0 sp=0x14001781fd0 pc=0x104681834
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1373 +0x140

goroutine 23 gp=0x14000183880 m=nil [GC worker (idle)]:
runtime.gopark(0x22486c07b67ec?, 0x3?, 0x17?, 0x3?, 0x0?)
	runtime/proc.go:460 +0xc0 fp=0x14000107f10 sp=0x14000107ef0 pc=0x104678c00
runtime.gcBgMarkWorker(0x14000882000)
	runtime/mgc.go:1463 +0xe0 fp=0x14000107fb0 sp=0x14000107f10 pc=0x104621400
runtime.gcBgMarkStartWorkers.gowrap1()
	runtime/mgc.go:1373 +0x28 fp=0x14000107fd0 sp=0x14000107fb0 pc=0x1046212e8
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14000107fd0 sp=0x14000107fd0 pc=0x104681834
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1373 +0x140

goroutine 7 gp=0x14000138000 m=nil [GC worker (idle)]:
runtime.gopark(0x22486c07adee1?, 0x1?, 0x84?, 0xca?, 0x0?)
	runtime/proc.go:460 +0xc0 fp=0x14002cbff10 sp=0x14002cbfef0 pc=0x104678c00
runtime.gcBgMarkWorker(0x14000882000)
	runtime/mgc.go:1463 +0xe0 fp=0x14002cbffb0 sp=0x14002cbff10 pc=0x104621400
runtime.gcBgMarkStartWorkers.gowrap1()
	runtime/mgc.go:1373 +0x28 fp=0x14002cbffd0 sp=0x14002cbffb0 pc=0x1046212e8
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14002cbffd0 sp=0x14002cbffd0 pc=0x104681834
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1373 +0x140

goroutine 38 gp=0x14000884700 m=nil [GC worker (idle)]:
runtime.gopark(0x22486c08034c4?, 0x3?, 0x24?, 0xf4?, 0x0?)
	runtime/proc.go:460 +0xc0 fp=0x14001996f10 sp=0x14001996ef0 pc=0x104678c00
runtime.gcBgMarkWorker(0x14000882000)
	runtime/mgc.go:1463 +0xe0 fp=0x14001996fb0 sp=0x14001996f10 pc=0x104621400
runtime.gcBgMarkStartWorkers.gowrap1()
	runtime/mgc.go:1373 +0x28 fp=0x14001996fd0 sp=0x14001996fb0 pc=0x1046212e8
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001996fd0 sp=0x14001996fd0 pc=0x104681834
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1373 +0x140

goroutine 24 gp=0x14000183a40 m=nil [GC worker (idle)]:
runtime.gopark(0x22486c07f8c4f?, 0x3?, 0xbf?, 0x60?, 0x0?)
	runtime/proc.go:460 +0xc0 fp=0x140000eef10 sp=0x140000eeef0 pc=0x104678c00
runtime.gcBgMarkWorker(0x14000882000)
	runtime/mgc.go:1463 +0xe0 fp=0x140000eefb0 sp=0x140000eef10 pc=0x104621400
runtime.gcBgMarkStartWorkers.gowrap1()
	runtime/mgc.go:1373 +0x28 fp=0x140000eefd0 sp=0x140000eefb0 pc=0x1046212e8
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x140000eefd0 sp=0x140000eefd0 pc=0x104681834
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1373 +0x140

goroutine 25 gp=0x14000183c00 m=nil [GC worker (idle)]:
runtime.gopark(0x114e23320?, 0x1?, 0x7d?, 0x8b?, 0x0?)
	runtime/proc.go:460 +0xc0 fp=0x14000997f10 sp=0x14000997ef0 pc=0x104678c00
runtime.gcBgMarkWorker(0x14000882000)
	runtime/mgc.go:1463 +0xe0 fp=0x14000997fb0 sp=0x14000997f10 pc=0x104621400
runtime.gcBgMarkStartWorkers.gowrap1()
	runtime/mgc.go:1373 +0x28 fp=0x14000997fd0 sp=0x14000997fb0 pc=0x1046212e8
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14000997fd0 sp=0x14000997fd0 pc=0x104681834
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1373 +0x140

goroutine 8 gp=0x14000983dc0 m=nil [select, 2 minutes]:
runtime.gopark(0x14000100f68?, 0x3?, 0x0?, 0xa0?, 0x14000100f62?)
	runtime/proc.go:460 +0xc0 fp=0x14000100de0 sp=0x14000100dc0 pc=0x104678c00
runtime.selectgo(0x14000100f68, 0x14000100f5c, 0x14000c9ee00?, 0x0, 0x0?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14000100f20 sp=0x14000100de0 pc=0x104656b4c
go.opencensus.io/stats/view.(*worker).start(0x14000c9ee00)
	go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0x84 fp=0x14000100fb0 sp=0x14000100f20 pc=0x105598f14
go.opencensus.io/stats/view.init.0.gowrap1()
	go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x28 fp=0x14000100fd0 sp=0x14000100fb0 pc=0x105598458
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14000100fd0 sp=0x14000100fd0 pc=0x104681834
created by go.opencensus.io/stats/view.init.0 in goroutine 1
	go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x94

goroutine 9 gp=0x140001381c0 m=nil [cleanup wait, 9 minutes]:
runtime.gopark(0x14000b8f200?, 0x1408f9c00?, 0x78?, 0x9f?, 0x10461b544?)
	runtime/proc.go:460 +0xc0 fp=0x14000889f40 sp=0x14000889f20 pc=0x104678c00
runtime.goparkunlock(...)
	runtime/proc.go:466
runtime.(*cleanupQueue).dequeue(0x1148a5200)
	runtime/mcleanup.go:439 +0x110 fp=0x14000889f80 sp=0x14000889f40 pc=0x10461ad40
runtime.runCleanups()
	runtime/mcleanup.go:635 +0x40 fp=0x14000889fd0 sp=0x14000889f80 pc=0x10461b550
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14000889fd0 sp=0x14000889fd0 pc=0x104681834
created by runtime.(*cleanupQueue).createGs in goroutine 1
	runtime/mcleanup.go:589 +0x108

goroutine 26 gp=0x140001396c0 m=nil [chan receive, 2 minutes]:
runtime.gopark(0x140001d9c10?, 0x140001d9b90?, 0xeb?, 0x35?, 0x2f3295cfbf415ee6?)
	runtime/proc.go:460 +0xc0 fp=0x140008896d0 sp=0x140008896b0 pc=0x104678c00
runtime.chanrecv(0x140001d9b90, 0x140008897a8, 0x1)
	runtime/chan.go:667 +0x428 fp=0x14000889750 sp=0x140008896d0 pc=0x10460e248
runtime.chanrecv2(0x14000650c60?, 0x14000206098?)
	runtime/chan.go:514 +0x14 fp=0x14000889780 sp=0x14000889750 pc=0x10460de04
github.com/awnumar/memguard/core.NewCoffer.func1(...)
	github.com/awnumar/memguard@v0.23.0/core/coffer.go:39
github.com/awnumar/memguard/core.NewCoffer.gowrap1()
	github.com/awnumar/memguard@v0.23.0/core/coffer.go:44 +0x54 fp=0x140008897d0 sp=0x14000889780 pc=0x104dcf284
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x140008897d0 sp=0x140008897d0 pc=0x104681834
created by github.com/awnumar/memguard/core.NewCoffer in goroutine 1
	github.com/awnumar/memguard@v0.23.0/core/coffer.go:36 +0x108

goroutine 27 gp=0x14000902a80 m=nil [select, 72 minutes, locked to thread]:
runtime.gopark(0x140016557a0?, 0x2?, 0xa8?, 0x56?, 0x14001655790?)
	runtime/proc.go:460 +0xc0 fp=0x14001655610 sp=0x140016555f0 pc=0x104678c00
runtime.selectgo(0x140016557a0, 0x1400165578c, 0x0?, 0x0, 0x0?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14001655750 sp=0x14001655610 pc=0x104656b4c
runtime.ensureSigM.func1()
	runtime/signal_unix.go:1085 +0x154 fp=0x140016557d0 sp=0x14001655750 pc=0x104672cd4
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x140016557d0 sp=0x140016557d0 pc=0x104681834
created by runtime.ensureSigM in goroutine 1
	runtime/signal_unix.go:1068 +0xcc

goroutine 28 gp=0x14000902c40 m=15 mp=0x140003dc808 [syscall, 72 minutes]:
runtime.sigNoteSleep(0x0?)
	runtime/os_darwin.go:133 +0x20 fp=0x14001655f90 sp=0x14001655f50 pc=0x10463d310
os/signal.signal_recv()
	runtime/sigqueue.go:149 +0x2c fp=0x14001655fb0 sp=0x14001655f90 pc=0x10467b30c
os/signal.loop()
	os/signal/signal_unix.go:23 +0x1c fp=0x14001655fd0 sp=0x14001655fb0 pc=0x104dd1d6c
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001655fd0 sp=0x14001655fd0 pc=0x104681834
created by os/signal.Notify.func1.1 in goroutine 1
	os/signal/signal.go:152 +0x28

goroutine 29 gp=0x14000902e00 m=nil [select, 72 minutes]:
runtime.gopark(0x14000886738?, 0x3?, 0x0?, 0x0?, 0x140008866ca?)
	runtime/proc.go:460 +0xc0 fp=0x14000886540 sp=0x14000886520 pc=0x104678c00
runtime.selectgo(0x14000886738, 0x140008866c4, 0x0?, 0x0, 0x0?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14000886680 sp=0x14000886540 pc=0x104656b4c
main.(*Telegraf).reloadLoop.func1()
	github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:185 +0x84 fp=0x140008867d0 sp=0x14000886680 pc=0x10b3857b4
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x140008867d0 sp=0x140008867d0 pc=0x104681834
created by main.(*Telegraf).reloadLoop in goroutine 1
	github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:184 +0x1a4

goroutine 30 gp=0x14000902fc0 m=nil [chan receive]:
runtime.gopark(0x14000994e18?, 0x104d4490c?, 0x50?, 0x15?, 0x14002d12290?)
	runtime/proc.go:460 +0xc0 fp=0x14000994dc0 sp=0x14000994da0 pc=0x104678c00
runtime.chanrecv(0x1400149d1f0, 0x14000994f50, 0x1)
	runtime/chan.go:667 +0x428 fp=0x14000994e40 sp=0x14000994dc0 pc=0x10460e248
runtime.chanrecv2(0x140013e1550?, 0x10f1940f0?)
	runtime/chan.go:514 +0x14 fp=0x14000994e70 sp=0x14000994e40 pc=0x10460de04
github.com/influxdata/telegraf/agent.(*Agent).runOutputs(0x1400105df78, 0x14000658e80)
	github.com/influxdata/telegraf/agent/agent.go:864 +0x1c0 fp=0x14000994f90 sp=0x14000994e70 pc=0x104e49710
github.com/influxdata/telegraf/agent.(*Agent).Run.func1()
	github.com/influxdata/telegraf/agent/agent.go:177 +0x4c fp=0x14000994fd0 sp=0x14000994f90 pc=0x104e440ec
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14000994fd0 sp=0x14000994fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*Agent).Run in goroutine 1
	github.com/influxdata/telegraf/agent/agent.go:175 +0x5d4

goroutine 31 gp=0x14000903180 m=nil [sync.WaitGroup.Wait, 72 minutes]:
runtime.gopark(0x1148d2120?, 0x1?, 0xe0?, 0x41?, 0x1148a2860?)
	runtime/proc.go:460 +0xc0 fp=0x14000106ce0 sp=0x14000106cc0 pc=0x104678c00
runtime.goparkunlock(...)
	runtime/proc.go:466
runtime.semacquire1(0x140015ffcc8, 0x0, 0x1, 0x0, 0x19)
	runtime/sema.go:192 +0x204 fp=0x14000106d30 sp=0x14000106ce0 pc=0x1046578f4
sync.runtime_SemacquireWaitGroup(0x10464d8f0?, 0xe0?)
	runtime/sema.go:114 +0x38 fp=0x14000106d70 sp=0x14000106d30 pc=0x10467a848
sync.(*WaitGroup).Wait(0x140015ffcc0)
	sync/waitgroup.go:206 +0xa8 fp=0x14000106da0 sp=0x14000106d70 pc=0x10469be28
github.com/influxdata/telegraf/agent.(*Agent).runInputs(0x1400105df78, {0x10f0ecff0, 0x14001499220}, {0x0?, 0x0?, 0x1148a2860?}, 0x14000658ec0)
	github.com/influxdata/telegraf/agent/agent.go:445 +0x468 fp=0x14000106f60 sp=0x14000106da0 pc=0x104e462d8
github.com/influxdata/telegraf/agent.(*Agent).Run.func5()
	github.com/influxdata/telegraf/agent/agent.go:205 +0x54 fp=0x14000106fd0 sp=0x14000106f60 pc=0x104e43d34
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14000106fd0 sp=0x14000106fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*Agent).Run in goroutine 1
	github.com/influxdata/telegraf/agent/agent.go:203 +0x7c8

goroutine 32 gp=0x14000903340 m=nil [select, 2 minutes]:
runtime.gopark(0x14000887f58?, 0x2?, 0xa0?, 0xd3?, 0x14000887f0c?)
	runtime/proc.go:460 +0xc0 fp=0x14000887d90 sp=0x14000887d70 pc=0x104678c00
runtime.selectgo(0x14000887f58, 0x14000887f08, 0x3e926aee6df?, 0x0, 0x0?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14000887ed0 sp=0x14000887d90 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0x140016441c0, {0x10f0ecff0, 0x14001499310}, 0x14001499360)
	github.com/influxdata/telegraf/agent/tick.go:87 +0xd0 fp=0x14000887f80 sp=0x14000887ed0 pc=0x104e4cc70
github.com/influxdata/telegraf/agent.(*AlignedTicker).start.func1()
	github.com/influxdata/telegraf/agent/tick.go:65 +0x50 fp=0x14000887fd0 sp=0x14000887f80 pc=0x104e4ca30
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14000887fd0 sp=0x14000887fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*AlignedTicker).start in goroutine 31
	github.com/influxdata/telegraf/agent/tick.go:63 +0x144

goroutine 33 gp=0x14000903500 m=nil [select, 2 minutes]:
runtime.gopark(0x14001784f00?, 0x2?, 0x2?, 0x0?, 0x14001784efc?)
	runtime/proc.go:460 +0xc0 fp=0x14001784d70 sp=0x14001784d50 pc=0x104678c00
runtime.selectgo(0x14001784f00, 0x14001784ef8, 0x14000659380?, 0x0, 0x10f076250?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14001784eb0 sp=0x14001784d70 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0x1400105df78, {0x10f0ecff0, 0x14001499220}, {0x10f1399a0, 0x14000659380}, 0x14001359e00, {0x10f076250, 0x140016441c0}, 0x2540be400)
	github.com/influxdata/telegraf/agent/agent.go:573 +0x98 fp=0x14001784f30 sp=0x14001784eb0 pc=0x104e474b8
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0x0?)
	github.com/influxdata/telegraf/agent/agent.go:441 +0x60 fp=0x14001784fb0 sp=0x14001784f30 pc=0x104e466b0
github.com/influxdata/telegraf/agent.(*Agent).runInputs.gowrap1()
	github.com/influxdata/telegraf/agent/agent.go:442 +0x2c fp=0x14001784fd0 sp=0x14001784fb0 pc=0x104e4661c
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001784fd0 sp=0x14001784fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs in goroutine 31
	github.com/influxdata/telegraf/agent/agent.go:439 +0xc0

goroutine 66 gp=0x140009036c0 m=nil [select, 2 minutes]:
runtime.gopark(0x14001786f58?, 0x2?, 0xf0?, 0xd4?, 0x14001786f0c?)
	runtime/proc.go:460 +0xc0 fp=0x14001786d90 sp=0x14001786d70 pc=0x104678c00
runtime.selectgo(0x14001786f58, 0x14001786f08, 0x1b10cd36f3d?, 0x0, 0x0?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14001786ed0 sp=0x14001786d90 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0x14001644200, {0x10f0ecff0, 0x14001499400}, 0x14001499450)
	github.com/influxdata/telegraf/agent/tick.go:87 +0xd0 fp=0x14001786f80 sp=0x14001786ed0 pc=0x104e4cc70
github.com/influxdata/telegraf/agent.(*AlignedTicker).start.func1()
	github.com/influxdata/telegraf/agent/tick.go:65 +0x50 fp=0x14001786fd0 sp=0x14001786f80 pc=0x104e4ca30
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001786fd0 sp=0x14001786fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*AlignedTicker).start in goroutine 31
	github.com/influxdata/telegraf/agent/tick.go:63 +0x144

goroutine 67 gp=0x14000903880 m=nil [select]:
runtime.gopark(0x14001787f00?, 0x2?, 0x2?, 0x0?, 0x14001787efc?)
	runtime/proc.go:460 +0xc0 fp=0x14001787d70 sp=0x14001787d50 pc=0x104678c00
runtime.selectgo(0x14001787f00, 0x14001787ef8, 0x140006593a0?, 0x0, 0x10f076250?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14001787eb0 sp=0x14001787d70 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0x1400105df78, {0x10f0ecff0, 0x14001499220}, {0x10f1399a0, 0x140006593a0}, 0x14001359ec0, {0x10f076250, 0x14001644200}, 0x2540be400)
	github.com/influxdata/telegraf/agent/agent.go:573 +0x98 fp=0x14001787f30 sp=0x14001787eb0 pc=0x104e474b8
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0x0?)
	github.com/influxdata/telegraf/agent/agent.go:441 +0x60 fp=0x14001787fb0 sp=0x14001787f30 pc=0x104e466b0
github.com/influxdata/telegraf/agent.(*Agent).runInputs.gowrap1()
	github.com/influxdata/telegraf/agent/agent.go:442 +0x2c fp=0x14001787fd0 sp=0x14001787fb0 pc=0x104e4661c
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001787fd0 sp=0x14001787fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs in goroutine 31
	github.com/influxdata/telegraf/agent/agent.go:439 +0xc0

goroutine 68 gp=0x14000903a40 m=nil [select, 2 minutes]:
runtime.gopark(0x14001651f58?, 0x2?, 0x40?, 0xd6?, 0x14001651f0c?)
	runtime/proc.go:460 +0xc0 fp=0x14001651d90 sp=0x14001651d70 pc=0x104678c00
runtime.selectgo(0x14001651f58, 0x14001651f08, 0x399fd55f6ec?, 0x0, 0x0?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14001651ed0 sp=0x14001651d90 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0x14001644240, {0x10f0ecff0, 0x140014994f0}, 0x14001499540)
	github.com/influxdata/telegraf/agent/tick.go:87 +0xd0 fp=0x14001651f80 sp=0x14001651ed0 pc=0x104e4cc70
github.com/influxdata/telegraf/agent.(*AlignedTicker).start.func1()
	github.com/influxdata/telegraf/agent/tick.go:65 +0x50 fp=0x14001651fd0 sp=0x14001651f80 pc=0x104e4ca30
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001651fd0 sp=0x14001651fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*AlignedTicker).start in goroutine 31
	github.com/influxdata/telegraf/agent/tick.go:63 +0x144

goroutine 69 gp=0x14000903c00 m=nil [select]:
runtime.gopark(0x14001998f00?, 0x2?, 0x2?, 0x0?, 0x14001998efc?)
	runtime/proc.go:460 +0xc0 fp=0x14001998d70 sp=0x14001998d50 pc=0x104678c00
runtime.selectgo(0x14001998f00, 0x14001998ef8, 0x140006593c0?, 0x0, 0x10f076250?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14001998eb0 sp=0x14001998d70 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0x1400105df78, {0x10f0ecff0, 0x14001499220}, {0x10f1399a0, 0x140006593c0}, 0x140015fa000, {0x10f076250, 0x14001644240}, 0x6fc23ac00)
	github.com/influxdata/telegraf/agent/agent.go:573 +0x98 fp=0x14001998f30 sp=0x14001998eb0 pc=0x104e474b8
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0x0?)
	github.com/influxdata/telegraf/agent/agent.go:441 +0x60 fp=0x14001998fb0 sp=0x14001998f30 pc=0x104e466b0
github.com/influxdata/telegraf/agent.(*Agent).runInputs.gowrap1()
	github.com/influxdata/telegraf/agent/agent.go:442 +0x2c fp=0x14001998fd0 sp=0x14001998fb0 pc=0x104e4661c
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001998fd0 sp=0x14001998fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs in goroutine 31
	github.com/influxdata/telegraf/agent/agent.go:439 +0xc0

goroutine 70 gp=0x14000903dc0 m=nil [select, 2 minutes]:
runtime.gopark(0x14001652f58?, 0x2?, 0x90?, 0xd7?, 0x14001652f0c?)
	runtime/proc.go:460 +0xc0 fp=0x14001652d90 sp=0x14001652d70 pc=0x104678c00
runtime.selectgo(0x14001652f58, 0x14001652f08, 0x22ec71efd29?, 0x0, 0x0?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14001652ed0 sp=0x14001652d90 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0x14001644280, {0x10f0ecff0, 0x140014995e0}, 0x14001499630)
	github.com/influxdata/telegraf/agent/tick.go:87 +0xd0 fp=0x14001652f80 sp=0x14001652ed0 pc=0x104e4cc70
github.com/influxdata/telegraf/agent.(*AlignedTicker).start.func1()
	github.com/influxdata/telegraf/agent/tick.go:65 +0x50 fp=0x14001652fd0 sp=0x14001652f80 pc=0x104e4ca30
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001652fd0 sp=0x14001652fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*AlignedTicker).start in goroutine 31
	github.com/influxdata/telegraf/agent/tick.go:63 +0x144

goroutine 71 gp=0x14000a02380 m=nil [select]:
runtime.gopark(0x14001a00f00?, 0x2?, 0x0?, 0x0?, 0x14001a00efc?)
	runtime/proc.go:460 +0xc0 fp=0x14001a00d70 sp=0x14001a00d50 pc=0x104678c00
runtime.selectgo(0x14001a00f00, 0x14001a00ef8, 0x14000659400?, 0x0, 0x10f076250?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14001a00eb0 sp=0x14001a00d70 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0x1400105df78, {0x10f0ecff0, 0x14001499220}, {0x10f1399a0, 0x14000659400}, 0x140015fa0c0, {0x10f076250, 0x14001644280}, 0x6fc23ac00)
	github.com/influxdata/telegraf/agent/agent.go:573 +0x98 fp=0x14001a00f30 sp=0x14001a00eb0 pc=0x104e474b8
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0x0?)
	github.com/influxdata/telegraf/agent/agent.go:441 +0x60 fp=0x14001a00fb0 sp=0x14001a00f30 pc=0x104e466b0
github.com/influxdata/telegraf/agent.(*Agent).runInputs.gowrap1()
	github.com/influxdata/telegraf/agent/agent.go:442 +0x2c fp=0x14001a00fd0 sp=0x14001a00fb0 pc=0x104e4661c
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001a00fd0 sp=0x14001a00fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs in goroutine 31
	github.com/influxdata/telegraf/agent/agent.go:439 +0xc0

goroutine 72 gp=0x14000a02540 m=nil [select]:
runtime.gopark(0x14001653f58?, 0x2?, 0xe0?, 0xd8?, 0x14001653f0c?)
	runtime/proc.go:460 +0xc0 fp=0x14001653d90 sp=0x14001653d70 pc=0x104678c00
runtime.selectgo(0x14001653f58, 0x14001653f08, 0x3ed9fb2154?, 0x0, 0x0?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14001653ed0 sp=0x14001653d90 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0x140016442c0, {0x10f0ecff0, 0x140014996d0}, 0x14001499720)
	github.com/influxdata/telegraf/agent/tick.go:87 +0xd0 fp=0x14001653f80 sp=0x14001653ed0 pc=0x104e4cc70
github.com/influxdata/telegraf/agent.(*AlignedTicker).start.func1()
	github.com/influxdata/telegraf/agent/tick.go:65 +0x50 fp=0x14001653fd0 sp=0x14001653f80 pc=0x104e4ca30
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001653fd0 sp=0x14001653fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*AlignedTicker).start in goroutine 31
	github.com/influxdata/telegraf/agent/tick.go:63 +0x144

goroutine 73 gp=0x14000a02700 m=nil [select]:
runtime.gopark(0x1400188ff00?, 0x2?, 0x0?, 0x0?, 0x1400188fefc?)
	runtime/proc.go:460 +0xc0 fp=0x1400188fd70 sp=0x1400188fd50 pc=0x104678c00
runtime.selectgo(0x1400188ff00, 0x1400188fef8, 0x14000659420?, 0x0, 0x10f076250?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x1400188feb0 sp=0x1400188fd70 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0x1400105df78, {0x10f0ecff0, 0x14001499220}, {0x10f1399a0, 0x14000659420}, 0x140015fa180, {0x10f076250, 0x140016442c0}, 0x6fc23ac00)
	github.com/influxdata/telegraf/agent/agent.go:573 +0x98 fp=0x1400188ff30 sp=0x1400188feb0 pc=0x104e474b8
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0x0?)
	github.com/influxdata/telegraf/agent/agent.go:441 +0x60 fp=0x1400188ffb0 sp=0x1400188ff30 pc=0x104e466b0
github.com/influxdata/telegraf/agent.(*Agent).runInputs.gowrap1()
	github.com/influxdata/telegraf/agent/agent.go:442 +0x2c fp=0x1400188ffd0 sp=0x1400188ffb0 pc=0x104e4661c
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x1400188ffd0 sp=0x1400188ffd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs in goroutine 31
	github.com/influxdata/telegraf/agent/agent.go:439 +0xc0

goroutine 74 gp=0x14000a028c0 m=nil [select, 2 minutes]:
runtime.gopark(0x14001654f58?, 0x2?, 0x30?, 0xda?, 0x14001654f0c?)
	runtime/proc.go:460 +0xc0 fp=0x14001654d90 sp=0x14001654d70 pc=0x104678c00
runtime.selectgo(0x14001654f58, 0x14001654f08, 0x1f6e59dcaf4?, 0x0, 0x0?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14001654ed0 sp=0x14001654d90 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0x14001644300, {0x10f0ecff0, 0x140014997c0}, 0x14001499810)
	github.com/influxdata/telegraf/agent/tick.go:87 +0xd0 fp=0x14001654f80 sp=0x14001654ed0 pc=0x104e4cc70
github.com/influxdata/telegraf/agent.(*AlignedTicker).start.func1()
	github.com/influxdata/telegraf/agent/tick.go:65 +0x50 fp=0x14001654fd0 sp=0x14001654f80 pc=0x104e4ca30
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001654fd0 sp=0x14001654fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*AlignedTicker).start in goroutine 31
	github.com/influxdata/telegraf/agent/tick.go:63 +0x144

goroutine 75 gp=0x14000a02a80 m=nil [select]:
runtime.gopark(0x14001b04f00?, 0x2?, 0x0?, 0x0?, 0x14001b04efc?)
	runtime/proc.go:460 +0xc0 fp=0x14001b04d70 sp=0x14001b04d50 pc=0x104678c00
runtime.selectgo(0x14001b04f00, 0x14001b04ef8, 0x14000659460?, 0x0, 0x10f076250?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14001b04eb0 sp=0x14001b04d70 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0x1400105df78, {0x10f0ecff0, 0x14001499220}, {0x10f1399a0, 0x14000659460}, 0x140015fa240, {0x10f076250, 0x14001644300}, 0x6fc23ac00)
	github.com/influxdata/telegraf/agent/agent.go:573 +0x98 fp=0x14001b04f30 sp=0x14001b04eb0 pc=0x104e474b8
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0x0?)
	github.com/influxdata/telegraf/agent/agent.go:441 +0x60 fp=0x14001b04fb0 sp=0x14001b04f30 pc=0x104e466b0
github.com/influxdata/telegraf/agent.(*Agent).runInputs.gowrap1()
	github.com/influxdata/telegraf/agent/agent.go:442 +0x2c fp=0x14001b04fd0 sp=0x14001b04fb0 pc=0x104e4661c
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001b04fd0 sp=0x14001b04fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs in goroutine 31
	github.com/influxdata/telegraf/agent/agent.go:439 +0xc0

goroutine 76 gp=0x14000a02c40 m=nil [select, 2 minutes]:
runtime.gopark(0x14001669f58?, 0x2?, 0x80?, 0xdb?, 0x14001669f0c?)
	runtime/proc.go:460 +0xc0 fp=0x14001669d90 sp=0x14001669d70 pc=0x104678c00
runtime.selectgo(0x14001669f58, 0x14001669f08, 0x3ac9d932eeb?, 0x0, 0x0?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14001669ed0 sp=0x14001669d90 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0x14001644340, {0x10f0ecff0, 0x140014998b0}, 0x14001499900)
	github.com/influxdata/telegraf/agent/tick.go:87 +0xd0 fp=0x14001669f80 sp=0x14001669ed0 pc=0x104e4cc70
github.com/influxdata/telegraf/agent.(*AlignedTicker).start.func1()
	github.com/influxdata/telegraf/agent/tick.go:65 +0x50 fp=0x14001669fd0 sp=0x14001669f80 pc=0x104e4ca30
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001669fd0 sp=0x14001669fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*AlignedTicker).start in goroutine 31
	github.com/influxdata/telegraf/agent/tick.go:63 +0x144

goroutine 77 gp=0x14000a02e00 m=nil [select]:
runtime.gopark(0x14000990f00?, 0x2?, 0x2?, 0x0?, 0x14000990efc?)
	runtime/proc.go:460 +0xc0 fp=0x14000990d70 sp=0x14000990d50 pc=0x104678c00
runtime.selectgo(0x14000990f00, 0x14000990ef8, 0x14000659480?, 0x0, 0x10f076250?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14000990eb0 sp=0x14000990d70 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0x1400105df78, {0x10f0ecff0, 0x14001499220}, {0x10f1399a0, 0x14000659480}, 0x140015fa300, {0x10f076250, 0x14001644340}, 0x2540be400)
	github.com/influxdata/telegraf/agent/agent.go:573 +0x98 fp=0x14000990f30 sp=0x14000990eb0 pc=0x104e474b8
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0x0?)
	github.com/influxdata/telegraf/agent/agent.go:441 +0x60 fp=0x14000990fb0 sp=0x14000990f30 pc=0x104e466b0
github.com/influxdata/telegraf/agent.(*Agent).runInputs.gowrap1()
	github.com/influxdata/telegraf/agent/agent.go:442 +0x2c fp=0x14000990fd0 sp=0x14000990fb0 pc=0x104e4661c
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14000990fd0 sp=0x14000990fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs in goroutine 31
	github.com/influxdata/telegraf/agent/agent.go:439 +0xc0

goroutine 39 gp=0x14000a82380 m=nil [select, 2 minutes]:
runtime.gopark(0x14000995e08?, 0x4?, 0xf0?, 0xd8?, 0x14000995d48?)
	runtime/proc.go:460 +0xc0 fp=0x14000995b90 sp=0x14000995b70 pc=0x104678c00
runtime.selectgo(0x14000995e08, 0x14000995d40, 0x10f076228?, 0x0, 0x14002693a40?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14000995cd0 sp=0x14000995b90 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*Agent).flushLoop(0x1400105df78, {0x10f0ecff0, 0x14001682000}, 0x140013e1550, {0x10f076228, 0x1400168a000})
	github.com/influxdata/telegraf/agent/agent.go:909 +0x12c fp=0x14000995f00 sp=0x14000995cd0 pc=0x104e49cdc
github.com/influxdata/telegraf/agent.(*Agent).runOutputs.func1(0x140013e1550)
	github.com/influxdata/telegraf/agent/agent.go:860 +0xe4 fp=0x14000995fb0 sp=0x14000995f00 pc=0x104e49a94
github.com/influxdata/telegraf/agent.(*Agent).runOutputs.gowrap1()
	github.com/influxdata/telegraf/agent/agent.go:861 +0x2c fp=0x14000995fd0 sp=0x14000995fb0 pc=0x104e4997c
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14000995fd0 sp=0x14000995fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*Agent).runOutputs in goroutine 30
	github.com/influxdata/telegraf/agent/agent.go:854 +0x90

goroutine 78 gp=0x14000a02fc0 m=nil [select, 2 minutes]:
runtime.gopark(0x14000887758?, 0x2?, 0xd0?, 0xdc?, 0x1400088770c?)
	runtime/proc.go:460 +0xc0 fp=0x14000887590 sp=0x14000887570 pc=0x104678c00
runtime.selectgo(0x14000887758, 0x14000887708, 0x2f956956615?, 0x0, 0x2?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x140008876d0 sp=0x14000887590 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0x14001644380, {0x10f0ecff0, 0x140014999a0}, 0x140014999f0)
	github.com/influxdata/telegraf/agent/tick.go:87 +0xd0 fp=0x14000887780 sp=0x140008876d0 pc=0x104e4cc70
github.com/influxdata/telegraf/agent.(*AlignedTicker).start.func1()
	github.com/influxdata/telegraf/agent/tick.go:65 +0x50 fp=0x140008877d0 sp=0x14000887780 pc=0x104e4ca30
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x140008877d0 sp=0x140008877d0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*AlignedTicker).start in goroutine 31
	github.com/influxdata/telegraf/agent/tick.go:63 +0x144

goroutine 79 gp=0x14000a03180 m=nil [select, 2 minutes]:
runtime.gopark(0x14001881f00?, 0x2?, 0x2?, 0x0?, 0x14001881efc?)
	runtime/proc.go:460 +0xc0 fp=0x14001881d70 sp=0x14001881d50 pc=0x104678c00
runtime.selectgo(0x14001881f00, 0x14001881ef8, 0x140006594a0?, 0x0, 0x10f076250?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14001881eb0 sp=0x14001881d70 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0x1400105df78, {0x10f0ecff0, 0x14001499220}, {0x10f1399a0, 0x140006594a0}, 0x140015fa3c0, {0x10f076250, 0x14001644380}, 0x2540be400)
	github.com/influxdata/telegraf/agent/agent.go:573 +0x98 fp=0x14001881f30 sp=0x14001881eb0 pc=0x104e474b8
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0x0?)
	github.com/influxdata/telegraf/agent/agent.go:441 +0x60 fp=0x14001881fb0 sp=0x14001881f30 pc=0x104e466b0
github.com/influxdata/telegraf/agent.(*Agent).runInputs.gowrap1()
	github.com/influxdata/telegraf/agent/agent.go:442 +0x2c fp=0x14001881fd0 sp=0x14001881fb0 pc=0x104e4661c
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001881fd0 sp=0x14001881fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs in goroutine 31
	github.com/influxdata/telegraf/agent/agent.go:439 +0xc0

goroutine 80 gp=0x14000a03340 m=nil [select, 2 minutes]:
runtime.gopark(0x14001a05f58?, 0x2?, 0x20?, 0xde?, 0x14001a05f0c?)
	runtime/proc.go:460 +0xc0 fp=0x14001a05d90 sp=0x14001a05d70 pc=0x104678c00
runtime.selectgo(0x14001a05f58, 0x14001a05f08, 0x397a9d6de43?, 0x0, 0x0?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14001a05ed0 sp=0x14001a05d90 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0x140016443c0, {0x10f0ecff0, 0x14001499a90}, 0x14001499ae0)
	github.com/influxdata/telegraf/agent/tick.go:87 +0xd0 fp=0x14001a05f80 sp=0x14001a05ed0 pc=0x104e4cc70
github.com/influxdata/telegraf/agent.(*AlignedTicker).start.func1()
	github.com/influxdata/telegraf/agent/tick.go:65 +0x50 fp=0x14001a05fd0 sp=0x14001a05f80 pc=0x104e4ca30
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001a05fd0 sp=0x14001a05fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*AlignedTicker).start in goroutine 31
	github.com/influxdata/telegraf/agent/tick.go:63 +0x144

goroutine 81 gp=0x14000a03500 m=nil [select, 2 minutes]:
runtime.gopark(0x14001a06f00?, 0x2?, 0x2?, 0x0?, 0x14001a06efc?)
	runtime/proc.go:460 +0xc0 fp=0x14001a06d70 sp=0x14001a06d50 pc=0x104678c00
runtime.selectgo(0x14001a06f00, 0x14001a06ef8, 0x140006594e0?, 0x0, 0x10f076250?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14001a06eb0 sp=0x14001a06d70 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0x1400105df78, {0x10f0ecff0, 0x14001499220}, {0x10f1399a0, 0x140006594e0}, 0x140015fa480, {0x10f076250, 0x140016443c0}, 0x2540be400)
	github.com/influxdata/telegraf/agent/agent.go:573 +0x98 fp=0x14001a06f30 sp=0x14001a06eb0 pc=0x104e474b8
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0x0?)
	github.com/influxdata/telegraf/agent/agent.go:441 +0x60 fp=0x14001a06fb0 sp=0x14001a06f30 pc=0x104e466b0
github.com/influxdata/telegraf/agent.(*Agent).runInputs.gowrap1()
	github.com/influxdata/telegraf/agent/agent.go:442 +0x2c fp=0x14001a06fd0 sp=0x14001a06fb0 pc=0x104e4661c
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001a06fd0 sp=0x14001a06fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs in goroutine 31
	github.com/influxdata/telegraf/agent/agent.go:439 +0xc0

goroutine 82 gp=0x14000a036c0 m=nil [select, 2 minutes]:
runtime.gopark(0x14001b01f58?, 0x2?, 0x70?, 0xdf?, 0x14001b01f0c?)
	runtime/proc.go:460 +0xc0 fp=0x14001b01d90 sp=0x14001b01d70 pc=0x104678c00
runtime.selectgo(0x14001b01f58, 0x14001b01f08, 0x2fbabfeca44?, 0x0, 0x0?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14001b01ed0 sp=0x14001b01d90 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0x14001644400, {0x10f0ecff0, 0x14001499b80}, 0x14001499bd0)
	github.com/influxdata/telegraf/agent/tick.go:87 +0xd0 fp=0x14001b01f80 sp=0x14001b01ed0 pc=0x104e4cc70
github.com/influxdata/telegraf/agent.(*AlignedTicker).start.func1()
	github.com/influxdata/telegraf/agent/tick.go:65 +0x50 fp=0x14001b01fd0 sp=0x14001b01f80 pc=0x104e4ca30
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001b01fd0 sp=0x14001b01fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*AlignedTicker).start in goroutine 31
	github.com/influxdata/telegraf/agent/tick.go:63 +0x144

goroutine 83 gp=0x14000a03880 m=nil [select, 2 minutes]:
runtime.gopark(0x14000101f00?, 0x2?, 0x2?, 0x0?, 0x14000101efc?)
	runtime/proc.go:460 +0xc0 fp=0x14000101d70 sp=0x14000101d50 pc=0x104678c00
runtime.selectgo(0x14000101f00, 0x14000101ef8, 0x14000659500?, 0x0, 0x10f076250?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14000101eb0 sp=0x14000101d70 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0x1400105df78, {0x10f0ecff0, 0x14001499220}, {0x10f1399a0, 0x14000659500}, 0x140015fa540, {0x10f076250, 0x14001644400}, 0x2540be400)
	github.com/influxdata/telegraf/agent/agent.go:573 +0x98 fp=0x14000101f30 sp=0x14000101eb0 pc=0x104e474b8
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0x0?)
	github.com/influxdata/telegraf/agent/agent.go:441 +0x60 fp=0x14000101fb0 sp=0x14000101f30 pc=0x104e466b0
github.com/influxdata/telegraf/agent.(*Agent).runInputs.gowrap1()
	github.com/influxdata/telegraf/agent/agent.go:442 +0x2c fp=0x14000101fd0 sp=0x14000101fb0 pc=0x104e4661c
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14000101fd0 sp=0x14000101fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs in goroutine 31
	github.com/influxdata/telegraf/agent/agent.go:439 +0xc0

goroutine 40 gp=0x14000a82540 m=nil [select, 2 minutes]:
runtime.gopark(0x14000886f28?, 0x2?, 0x40?, 0xc1?, 0x14000886f24?)
	runtime/proc.go:460 +0xc0 fp=0x14000886da0 sp=0x14000886d80 pc=0x104678c00
runtime.selectgo(0x14000886f28, 0x14000886f20, 0x140013e1550?, 0x0, 0x14001682000?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14000886ee0 sp=0x14000886da0 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*RollingTicker).run(0x1400168a000, {0x10f0ecff0, 0x14001682050}, 0x140016820a0)
	github.com/influxdata/telegraf/agent/tick.go:258 +0x94 fp=0x14000886f80 sp=0x14000886ee0 pc=0x104e4d5c4
github.com/influxdata/telegraf/agent.(*RollingTicker).start.func1()
	github.com/influxdata/telegraf/agent/tick.go:248 +0x50 fp=0x14000886fd0 sp=0x14000886f80 pc=0x104e4d490
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14000886fd0 sp=0x14000886fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*RollingTicker).start in goroutine 39
	github.com/influxdata/telegraf/agent/tick.go:246 +0x14c

goroutine 84 gp=0x14000a03a40 m=nil [select, 2 minutes]:
runtime.gopark(0x14001a01f58?, 0x2?, 0x40?, 0xc1?, 0x14001a01f0c?)
	runtime/proc.go:460 +0xc0 fp=0x14001a01d90 sp=0x14001a01d70 pc=0x104678c00
runtime.selectgo(0x14001a01f58, 0x14001a01f08, 0x399fde9e823?, 0x0, 0x0?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14001a01ed0 sp=0x14001a01d90 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0x14001644440, {0x10f0ecff0, 0x14001499c70}, 0x14001499cc0)
	github.com/influxdata/telegraf/agent/tick.go:87 +0xd0 fp=0x14001a01f80 sp=0x14001a01ed0 pc=0x104e4cc70
github.com/influxdata/telegraf/agent.(*AlignedTicker).start.func1()
	github.com/influxdata/telegraf/agent/tick.go:65 +0x50 fp=0x14001a01fd0 sp=0x14001a01f80 pc=0x104e4ca30
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001a01fd0 sp=0x14001a01fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*AlignedTicker).start in goroutine 31
	github.com/influxdata/telegraf/agent/tick.go:63 +0x144

goroutine 85 gp=0x14000a03c00 m=nil [select, 2 minutes]:
runtime.gopark(0x14001a02f00?, 0x2?, 0x2?, 0x0?, 0x14001a02efc?)
	runtime/proc.go:460 +0xc0 fp=0x14001a02d70 sp=0x14001a02d50 pc=0x104678c00
runtime.selectgo(0x14001a02f00, 0x14001a02ef8, 0x14000659540?, 0x0, 0x10f076250?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14001a02eb0 sp=0x14001a02d70 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0x1400105df78, {0x10f0ecff0, 0x14001499220}, {0x10f1399a0, 0x14000659540}, 0x140015fa600, {0x10f076250, 0x14001644440}, 0x2540be400)
	github.com/influxdata/telegraf/agent/agent.go:573 +0x98 fp=0x14001a02f30 sp=0x14001a02eb0 pc=0x104e474b8
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0x0?)
	github.com/influxdata/telegraf/agent/agent.go:441 +0x60 fp=0x14001a02fb0 sp=0x14001a02f30 pc=0x104e466b0
github.com/influxdata/telegraf/agent.(*Agent).runInputs.gowrap1()
	github.com/influxdata/telegraf/agent/agent.go:442 +0x2c fp=0x14001a02fd0 sp=0x14001a02fb0 pc=0x104e4661c
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001a02fd0 sp=0x14001a02fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs in goroutine 31
	github.com/influxdata/telegraf/agent/agent.go:439 +0xc0

goroutine 86 gp=0x14000a03dc0 m=nil [select, 2 minutes]:
runtime.gopark(0x14001889f58?, 0x2?, 0x90?, 0xc2?, 0x14001889f0c?)
	runtime/proc.go:460 +0xc0 fp=0x14001889d90 sp=0x14001889d70 pc=0x104678c00
runtime.selectgo(0x14001889f58, 0x14001889f08, 0x2cd19de3688?, 0x0, 0x0?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14001889ed0 sp=0x14001889d90 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0x14001644480, {0x10f0ecff0, 0x14001499d60}, 0x14001499db0)
	github.com/influxdata/telegraf/agent/tick.go:87 +0xd0 fp=0x14001889f80 sp=0x14001889ed0 pc=0x104e4cc70
github.com/influxdata/telegraf/agent.(*AlignedTicker).start.func1()
	github.com/influxdata/telegraf/agent/tick.go:65 +0x50 fp=0x14001889fd0 sp=0x14001889f80 pc=0x104e4ca30
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001889fd0 sp=0x14001889fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*AlignedTicker).start in goroutine 31
	github.com/influxdata/telegraf/agent/tick.go:63 +0x144

goroutine 87 gp=0x14000b02380 m=nil [select, 2 minutes]:
runtime.gopark(0x14000102e20?, 0x3?, 0x58?, 0x2c?, 0x14000102dc2?)
	runtime/proc.go:460 +0xc0 fp=0x14000102c10 sp=0x14000102bf0 pc=0x104678c00
runtime.selectgo(0x14000102e20, 0x14000102dbc, 0x14000102ea8?, 0x0, 0x14000102f00?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14000102d50 sp=0x14000102c10 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*Agent).gatherOnce(0x14000102f00?, {0x10f1399a0, 0x14000659560}, 0x140015fa6c0, {0x10f076250, 0x14001644480}, 0x2540be400)
	github.com/influxdata/telegraf/agent/agent.go:600 +0x140 fp=0x14000102eb0 sp=0x14000102d50 pc=0x104e47680
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0x1400105df78, {0x10f0ecff0, 0x14001499220}, {0x10f1399a0, 0x14000659560}, 0x140015fa6c0, {0x10f076250, 0x14001644480}, 0x2540be400)
	github.com/influxdata/telegraf/agent/agent.go:575 +0xbc fp=0x14000102f30 sp=0x14000102eb0 pc=0x104e474dc
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0x0?)
	github.com/influxdata/telegraf/agent/agent.go:441 +0x60 fp=0x14000102fb0 sp=0x14000102f30 pc=0x104e466b0
github.com/influxdata/telegraf/agent.(*Agent).runInputs.gowrap1()
	github.com/influxdata/telegraf/agent/agent.go:442 +0x2c fp=0x14000102fd0 sp=0x14000102fb0 pc=0x104e4661c
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14000102fd0 sp=0x14000102fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs in goroutine 31
	github.com/influxdata/telegraf/agent/agent.go:439 +0xc0

goroutine 88 gp=0x14000b02540 m=nil [select, 2 minutes]:
runtime.gopark(0x14000996f58?, 0x2?, 0xe0?, 0xc3?, 0x14000996f0c?)
	runtime/proc.go:460 +0xc0 fp=0x14000996d90 sp=0x14000996d70 pc=0x104678c00
runtime.selectgo(0x14000996f58, 0x14000996f08, 0x14f4285e310?, 0x0, 0x0?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14000996ed0 sp=0x14000996d90 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0x140016444c0, {0x10f0ecff0, 0x14001499e50}, 0x14001499ea0)
	github.com/influxdata/telegraf/agent/tick.go:87 +0xd0 fp=0x14000996f80 sp=0x14000996ed0 pc=0x104e4cc70
github.com/influxdata/telegraf/agent.(*AlignedTicker).start.func1()
	github.com/influxdata/telegraf/agent/tick.go:65 +0x50 fp=0x14000996fd0 sp=0x14000996f80 pc=0x104e4ca30
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14000996fd0 sp=0x14000996fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*AlignedTicker).start in goroutine 31
	github.com/influxdata/telegraf/agent/tick.go:63 +0x144

goroutine 89 gp=0x14000b02700 m=nil [select, 2 minutes]:
runtime.gopark(0x14000105e20?, 0x3?, 0x58?, 0x5c?, 0x14000105dc2?)
	runtime/proc.go:460 +0xc0 fp=0x14000105c10 sp=0x14000105bf0 pc=0x104678c00
runtime.selectgo(0x14000105e20, 0x14000105dbc, 0x14000105ea8?, 0x0, 0x14000105f00?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14000105d50 sp=0x14000105c10 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*Agent).gatherOnce(0x14000105f00?, {0x10f1399a0, 0x14000659580}, 0x140015fa780, {0x10f076250, 0x140016444c0}, 0x2540be400)
	github.com/influxdata/telegraf/agent/agent.go:600 +0x140 fp=0x14000105eb0 sp=0x14000105d50 pc=0x104e47680
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0x1400105df78, {0x10f0ecff0, 0x14001499220}, {0x10f1399a0, 0x14000659580}, 0x140015fa780, {0x10f076250, 0x140016444c0}, 0x2540be400)
	github.com/influxdata/telegraf/agent/agent.go:575 +0xbc fp=0x14000105f30 sp=0x14000105eb0 pc=0x104e474dc
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0x0?)
	github.com/influxdata/telegraf/agent/agent.go:441 +0x60 fp=0x14000105fb0 sp=0x14000105f30 pc=0x104e466b0
github.com/influxdata/telegraf/agent.(*Agent).runInputs.gowrap1()
	github.com/influxdata/telegraf/agent/agent.go:442 +0x2c fp=0x14000105fd0 sp=0x14000105fb0 pc=0x104e4661c
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14000105fd0 sp=0x14000105fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs in goroutine 31
	github.com/influxdata/telegraf/agent/agent.go:439 +0xc0

goroutine 90 gp=0x14000b028c0 m=nil [select, 2 minutes]:
runtime.gopark(0x14001664758?, 0x2?, 0x30?, 0xc5?, 0x1400166470c?)
	runtime/proc.go:460 +0xc0 fp=0x14001664590 sp=0x14001664570 pc=0x104678c00
runtime.selectgo(0x14001664758, 0x14001664708, 0x356780a047d?, 0x0, 0x0?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x140016646d0 sp=0x14001664590 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0x14001644500, {0x10f0ecff0, 0x14001676000}, 0x14001676050)
	github.com/influxdata/telegraf/agent/tick.go:87 +0xd0 fp=0x14001664780 sp=0x140016646d0 pc=0x104e4cc70
github.com/influxdata/telegraf/agent.(*AlignedTicker).start.func1()
	github.com/influxdata/telegraf/agent/tick.go:65 +0x50 fp=0x140016647d0 sp=0x14001664780 pc=0x104e4ca30
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x140016647d0 sp=0x140016647d0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*AlignedTicker).start in goroutine 31
	github.com/influxdata/telegraf/agent/tick.go:63 +0x144

goroutine 91 gp=0x14000b02a80 m=nil [select, 2 minutes]:
runtime.gopark(0x14001782f00?, 0x2?, 0x2?, 0x0?, 0x14001782efc?)
	runtime/proc.go:460 +0xc0 fp=0x14001782d70 sp=0x14001782d50 pc=0x104678c00
runtime.selectgo(0x14001782f00, 0x14001782ef8, 0x140006595c0?, 0x0, 0x10f076250?, 0x1)
	runtime/select.go:351 +0x6bc fp=0x14001782eb0 sp=0x14001782d70 pc=0x104656b4c
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0x1400105df78, {0x10f0ecff0, 0x14001499220}, {0x10f1399a0, 0x140006595c0}, 0x140015fa840, {0x10f076250, 0x14001644500}, 0x2540be400)
	github.com/influxdata/telegraf/agent/agent.go:573 +0x98 fp=0x14001782f30 sp=0x14001782eb0 pc=0x104e474b8
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0x0?)
	github.com/influxdata/telegraf/agent/agent.go:441 +0x60 fp=0x14001782fb0 sp=0x14001782f30 pc=0x104e466b0
github.com/influxdata/telegraf/agent.(*Agent).runInputs.gowrap1()
	github.com/influxdata/telegraf/agent/agent.go:442 +0x2c fp=0x14001782fd0 sp=0x14001782fb0 pc=0x104e4661c
runtime.goexit({})
	runtime/asm_arm64.s:1268 +0x4 fp=0x14001782fd0 sp=0x14001782fd0 pc=0x104681834
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs in goroutine 31
	github.com/influxdata/telegraf/agent/agent.go:439 +0xc0

[truncated because this field can not be longer than 65536 characters)
```

### System info

Telegraf 1.36.2, Chrony 4.8

### Docker

_No response_

### Steps to reproduce

1. add the inputs.chrony snippet above to telegraf.conf
2. let it run for a few days
3. eventually observe the panic

### Expected behavior

Telegraf should not panic.

### Actual behavior

The process panics..

### Additional info

This had previously been reported as https://github.com/influxdata/telegraf/issues/17453 (released in Telegraf 1.36.0), but it looks like the fix was not sufficient.

### PR DESCRIPTION
**Pull request by skartikey**
## Summary

The chrony plugin was experiencing intermittent panics with error `runtime error: index out of range [256] with length 256` when multiple `Gather()` calls executed concurrently.

Root Cause:
The plugin creates a single `fbchrony.Client` instance shared across all `Gather()` calls. When Telegraf triggers a new `Gather()` before the previous one completes (e.g., when collecting sourcestats with multiple sources), both goroutines
access the shared client concurrently:

1. Both goroutines call `client.Communicate()` simultaneously
2. Both modify [n.Sequence++](https://github.com/facebook/time/blob/main/ntp/chrony/client.go#L34) without synchronization (NOT THREAD-SAFE - Race condition here!)
3. Both call `binary.Write()` concurrently (Concurrent writes corrupt memory)
4. Memory corruption occurs during packet encoding
5. Panic occurs with `index out of range [256]`

This race condition is intermittent because it only manifests when gather operations overlap, typically when sourcestats collection takes longer than the configured interval.

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #17757

### CODE REVIEW

**Comment by carsonsaldanha** [comment]
Hi, @skartikey. I have nearly an identical change as this but for the CSV parser in #17573 that's still not been addressed in over a month. A review would be much appreciated. Thanks.

File: plugins/inputs/chrony/chrony.go [hunk 1]
```diff
@@ -40,6 +41,11 @@ type Chrony struct {
 	client *fbchrony.Client
 	source string
 	local  string
+
+	// clientMu protects concurrent access to the chrony client.
+	// This prevents race conditions when multiple Gather() calls
+	// access the same client instance concurrently.
+	clientMu sync.Mutex
```
Comment (srebhan) [inline plugins/inputs/chrony/chrony.go]: How about

```suggestion
	// This prevents race conditions when multiple Gather() calls
	// access the same client instance concurrently.
	sync.Mutex
```

and then use just `c.Lock()` and `c.Unlock()` below?

**Review by srebhan — COMMENTED** [review]
Thanks @skartikey! Just one small suggestion...
