### PR TITLE
fix(opcua): clean client on disconnect so that connect works cleanly

### LINKED ISSUE #9582: OPCUA Input: client should be set to nil after closing
Bug in the `opcua` input:

In [`disconnect`](https://github.com/influxdata/telegraf/blob/de01d37a36288fd1688797ec50a5f58a578dab76/plugins/inputs/opcua/opcua_client.go#L507), the connection is closed which leads to `Connect` being invoked on the next `Gather` cycle which in turn finds tries to invoke [`CloseSession`](https://github.com/influxdata/telegraf/blob/de01d37a36288fd1688797ec50a5f58a578dab76/plugins/inputs/opcua/opcua_client.go#L409) on an already-closed connection.

This results in the looped error output which cannot be recovered from:
> Error in plugin: opcua: sechan: secure channel not open.

We'll test out adding `client = nil` and create a merge request if that turns out to fix the issue.

### PR DESCRIPTION
**Pull request by milgner**
- [-] Updated associated README.md.
- [-] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary) (e.g. feat: or fix:)

resolves #9582 

If the client connection only gets closed, the next invocation of `Connect`
(via `Gather` loop) would try to invoke `CloseSession` on an already-closed
client.

It might be possible to get rid of the nil-check
```
if o.client != nil {
```

in `Connect` but further investigation is needed.

### CODE REVIEW

**Review by srebhan — APPROVED** [review]
Thanks @milgner for this PR! 

The code looks good to me.  And it potentially saves out souls for the (seemingly) related #9551.

File: plugins/inputs/opcua/opcua_client.go [hunk 1]
```diff
@@ -503,6 +503,7 @@ func disconnect(o *OpcUA) error {
 	case "opc.tcp":
 		o.state = Disconnected
 		o.client.Close()
+		o.client = nil
```
Comment (helenosheaa) [inline plugins/inputs/opcua/opcua_client.go:506]: Should we also be at least logging the return of o.client.Close()?

Comment (milgner) [reply plugins/inputs/opcua/opcua_client.go:506]: Good question. I had a look at [the source code](https://github.com/gopcua/opcua/blob/baabb9b14fd272417c63c27cfce625a16c519518/client.go#L501) and it doesn't seem to have any code path that could actually produce errors.  Since `Close()` methods are usually called via `defer` and their return code ignored, I'd hazard a guess that this probably won't change anytime soon either.

**Review by sspaink — APPROVED** [review]
lgtm
