### PR TITLE
fix: Proxmox input: Changed VM ID from string to int, fixes #9611

### LINKED ISSUE #9611: Error getting VM curent VM status - Proxmox error
### Relevant telegraf.conf:
```toml
# Provides metrics from Proxmox nodes (Proxmox Virtual Environment > 6.2).
[[inputs.proxmox]]
  ## API connection configuration. The API token was introduced in Proxmox v6.2. Required permissions for user and token: PVEAuditor role on /.
  base_url = "https://localhost:8006/api2/json"
  api_token = "<api_token>"
  ## Node name, defaults to OS hostname
  #node_name = ""

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"

  ## Use TLS but skip chain & host verification
  insecure_skip_verify = true
  # HTTP response timeout (default: 5s)
  response_timeout = "5s"
```

### System info:

PVE 7.0-11 based on debian 11
Telegraf version 1.19.2, installed according to [this ](https://docs.influxdata.com/telegraf/v1.19/introduction/installation/) guide.

### Steps to reproduce:

1. Start the telegraf service

### Expected behavior:

I expect telegraf to behave normally and to not spam errors in syslog.

### Actual behavior:

The following error on every poll:
```
Aug 11 12:51:05 Raptor telegraf[625244]: 2021-08-11T10:51:05Z E! [inputs.proxmox] Error getting VM curent VM status: json: cannot unmarshal number into Go struct field VMStat.data.vmid of type string
Aug 11 12:51:05 Raptor telegraf[625244]: 2021-08-11T10:51:05Z E! [inputs.proxmox] Error getting VM stats: %vjson: cannot unmarshal number into Go struct field VMStat.data.vmid of type string
```
Besides the fact that current is spelled with only 1 R, I expect the data from proxmox to be gathered and sent to my output plugins.

### Additional info:

I can confirm that the api token I use is correct, because if I change it, I get a completely different error.

### PR DESCRIPTION
**Pull request by atetevoortwis**
Small fix to properly parse JSON data from Proxmox >=7.0 installs.

### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #9611

- Updated the VMStat schema to use a Number for ID.
- Changed getCurrentVMStatus and getVmConfig accordingly.
- Added case to testdata to check that both string representations and integers work in JSON.

### CODE REVIEW

**Comment by atetevoortwis** [comment]
@rare-magma, Finally found some time for this, continuing here...

**Comment by atetevoortwis** [comment]
@srebhan With regards to your comment (originially on #9820):
> is this a bug that was there from the beginning or does it depend on the proxmox version? If the latter, you need to 
> unmarshal to the respective type, i.e. you try with an int first and if that fails, you use it as a string...

To be honest I'm not sure: I experienced this bug when upgrading to Proxmox 7.0.0, so I expect it to be related to a change on their API.
I've updated the unit test to both use a string (representation of an int) and int's in the test JSON and that seems to work...
Although I'm completely new to Go, so let me know if this is not the way :-)

File: plugins/inputs/proxmox/proxmox.go [hunk 1]
```diff
@@ -163,8 +163,8 @@ func gatherVMData(px *Proxmox, acc telegraf.Accumulator, rt ResourceType) {
 	}
 }
 
-func getCurrentVMStatus(px *Proxmox, rt ResourceType, id string) (VMStat, error) {
-	apiURL := "/nodes/" + px.NodeName + "/" + string(rt) + "/" + id + "/status/current"
+func getCurrentVMStatus(px *Proxmox, rt ResourceType, id json.Number) (VMStat, error) {
+	apiURL := "/nodes/" + px.NodeName + "/" + string(rt) + "/" + string(id) + "/status/current"
```
Comment (srebhan) [inline plugins/inputs/proxmox/proxmox.go:167]: Is this change necessary? Can we keep the string?

**Comment by srebhan** [comment]
@atetevoortwis the code looks good so far. Can you please check the documentation to make sure previous IDs were struct numerical and not `"abc2347jddh"` type of values?

**Comment by atetevoortwis** [comment]
> @atetevoortwis the code looks good so far. Can you please check the documentation to make sure previous IDs were struct numerical and not `"abc2347jddh"` type of values?

As far as I know Proxmox VM ID's always have been integers: https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc/{vmid} .

**Review by srebhan — APPROVED** [review]
Looks good to me, assuming the backward compatibility is given as discussed. Thanks @atetevoortwis for your work!

**Review by reimda — APPROVED** [review]

**Comment by reimda** [comment]
Thanks @atetevoortwis
