### PR TITLE
fix(inputs.prometheus): correctly track deleted pods

### LINKED ISSUE #12527: prometheus input attempts to contact deleted pods
### Relevant telegraf.conf

```toml
[[inputs.prometheus]]
monitor_kubernetes_pods = true
metric_version = 1
monitor_kubernetes_pods_method = "settings+annotations"
kubernetes_label_selector = "app = myapp"
monitor_kubernetes_pods_port = 7354
pod_scrape_interval = 60
```

### Logs from Telegraf

```text
Don't have exact line, because it was fixed in our systems, but error was from the `inputs.prometheus` and error text is clear that it network error while contact Pod metrics endpoint.
```

### System info

1.25.0

### Docker

_No response_

### Steps to reproduce

Left running telegraf with inputs.prometheus and monitor_kubernetes_pods enabled long enough in the active cluster, where pods ofter recreated, control plane upgraded, etc.

### Expected behavior

Deleted pods are never contacted by the telegraf

### Actual behavior

Observe telegraf eventually reporting error contact URL to scrape. When checking for the IP used in the URL there is no pod with such IP, meaning telegraf missed pod deletion.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by redbaron**
# Required for all PRs

- [ ] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

Deleted pods were not always unregistered. It was happening when telegraf is briefly disconnected from Kubernetes API server, in that case Informer OnDelete doesn't just return corev1.Pod object, but a special marker indicating that pod was deleted, but it's state might not be up to date. This PR accounts for such behaviour.

It also reworks Informer is used to track pods, summary is like following:
- register/unregister Pod now tracks each pod by their ID "$namespace/$podName"
- state of the pod passed in the Informer handler funcs is used as is to simplify tracking logic

Fixes #12527

### CODE REVIEW

File: plugins/inputs/prometheus/kubernetes.go [hunk 1]
```diff
@@ -388,7 +354,7 @@ func registerPod(pod *corev1.Pod, p *Prometheus) {
 		p.lock.Lock()
 		defer p.lock.Unlock()
 	}
-	p.kubernetesPods[podURL.String()] = URLAndAddress{
+	p.kubernetesPods[PodID(pod.GetNamespace()+"/"+pod.GetName())] = URLAndAddress{
```
Comment (powersj) [inline plugins/inputs/prometheus/kubernetes.go:357]: Why prompted this change?

File: plugins/inputs/prometheus/kubernetes.go [hunk 2]
```diff
@@ -134,76 +133,43 @@ func (p *Prometheus) watchPod(ctx context.Context, clientset *kubernetes.Clients
...
-			if err != nil {
-				p.Log.Errorf("getting key from cache %s\n", err.Error())
-			}
-
-			namespace, name, err := cache.SplitMetaNamespaceKey(key)
-			if err != nil {
-				p.Log.Errorf("splitting key into namespace and name %s\n", err.Error())
+			newPod, ok := newObj.(*corev1.Pod)
+			if !ok {
+				p.Log.Error("[BUG] Not a Pod, report it to the Github issues, please")
```
Comment (powersj) [inline plugins/inputs/prometheus/kubernetes.go:138]: I realize in the current situation we ignore any error, but if this error should start happening for someone, is there anything we can print to point the user or us to a root cause?

File: plugins/inputs/prometheus/kubernetes.go [hunk 3]
```diff
@@ -134,76 +133,43 @@ func (p *Prometheus) watchPod(ctx context.Context, clientset *kubernetes.Clients
...
 		},
-		UpdateFunc: func(oldObj, newObj interface{}) {
-			newKey, err := cache.MetaNamespaceKeyFunc(newObj)
-			if err != nil {
-				p.Log.Errorf("getting key from cache %s\n", err.Error())
+		// On Pod status updates and regular reList by Informer
+		UpdateFunc: func(_, newObj interface{}) {
+			newPod, ok := newObj.(*corev1.Pod)
+			if !ok {
+				p.Log.Error("[BUG] Not a Pod, report it to the Github issues, please")
```
Comment (powersj) [inline plugins/inputs/prometheus/kubernetes.go:149]: Same question here re: printing something

File: plugins/inputs/prometheus/kubernetes.go [hunk 4]
```diff
@@ -134,76 +133,43 @@ func (p *Prometheus) watchPod(ctx context.Context, clientset *kubernetes.Clients
...
-			oldNamespace, oldName, err := cache.SplitMetaNamespaceKey(oldKey)
-			if err != nil {
-				p.Log.Errorf("splitting key into namespace and name %s\n", err.Error())
-			}
-
-			oldPod, _ := clientset.CoreV1().Pods(oldNamespace).Get(ctx, oldName, metav1.GetOptions{})
-
-			if shouldScrapePod(oldPod, p) {
-				if oldPod.GetDeletionTimestamp() != nil {
-					unregisterPod(oldPod, p)
```
Comment (powersj) [inline plugins/inputs/prometheus/kubernetes.go:186]: Any checks to `GetDeletionTimestamp` are now gone, why?

**Review by powersj — COMMENTED** [review]
Hi,

Can you please file an issue that includes an example of what a user might see or not see in logs when this situation occurs? I'd like to have the history and additional background for the fix.

Also want to ensure that the metrics are not changing due to this only the internal handling.

Some questions, primarily to understand the changes are inline.

Thanks!

File: plugins/inputs/prometheus/kubernetes.go (hunk 2 above)
Comment (redbaron) [reply plugins/inputs/prometheus/kubernetes.go:138]: this error shouldn't happen in practice, because we create Informer for Pods and it will be Pod objects which we receive in Add/Update/Delete handlers, so this cast will never fail. It can only start happening if future refactor of this code changes something.

File: plugins/inputs/prometheus/kubernetes.go (hunk 4 above)
Comment (redbaron) [reply plugins/inputs/prometheus/kubernetes.go:186]: we don't need it, we base our actions only on the new state of the pod, regardless what was the previous state. Previously code accounted for pod name change, no update to the pod can change it's name, only delete+create can.

File: plugins/inputs/prometheus/kubernetes.go (hunk 1 above)
Comment (redbaron) [reply plugins/inputs/prometheus/kubernetes.go:357]: Pod Informer gives us stream of Add/Update/Delete events, which we use to decide whether pod is of our interest or not. Natural key for the pod is "$namespace/$name" as it can't be changed for the duration of the pod life.

If we track pods by their natural keys, we avoid awkward conversion from pod spec to the URL every time just to check if we already track pod or not.

**Comment by redbaron** [comment]
I created the issue and linked this  PR to it

> Also want to ensure that the metrics are not changing due to this only the internal handling.

What do you mean?

**Comment by powersj** [comment]
> > Also want to ensure that the metrics are not changing due to this only the internal handling.
> 
> What do you mean?

It appears all of these changes are only to the internal tracking of pods, but I wanted to ensure that no tags or field values are changed due to this PR.

File: plugins/inputs/prometheus/kubernetes.go (hunk 2 above)
Comment (powersj) [reply plugins/inputs/prometheus/kubernetes.go:138]: I guess I am wondering what to do if we tell someone to file a bug the only response I have is "that shouldn't happen."

I'd rather this say something like "failed to convert to a pod" and print the string representation of the interface or something to give a hint at what was trying to be converted.

Does that make sense?

Comment (redbaron) [reply plugins/inputs/prometheus/kubernetes.go:138]: Whether it will be triggered or not is dependend entirely on the code, not on environment user runs telegraf in. I figured if they report that they see this log line in the issue, it will be trivial for devs to figure out what exactly is being passed here.


We can remove check and convert just with:

```
newPod := newObj.(*corev1.Pod)
```

which will panic should `newObj` be of the wrong type and it will have all necessary details printed

**Comment by redbaron** [comment]
>  but I wanted to ensure that no tags or field values are changed due to this PR.

that's correct, there shouldn't be any changes like that

File: plugins/inputs/prometheus/kubernetes.go (hunk 2 above)
Comment (powersj) [reply plugins/inputs/prometheus/kubernetes.go:138]: > it will be trivial for devs to figure out what exactly is being passed here.

I would hopefuly agree, but given how hard it is to get logs from some users I'd rather we give the user as much info as possible without just telling them to file an issue.

> which will panic should newObj

While an option I'd prefer we not panic anywhere in plugins.

I think all I am after is an updated error message, like "did not receive a pod" and print the interface should something ever go wrong.

**Review by powersj — APPROVED** [review]
thanks!

**Comment by redbaron** [comment]
Problem reappeared even with this fix applied, please hold on merging it.

**Review by srebhan — APPROVED** [review]
Looks good to me. Thanks for fixing this issue @redbaron!

@powersj can you please give this a second look after the additional fix?!?!
