### PR TITLE
fix(inputs.ping): Warn on using timeout parameter for native method

### LINKED ISSUE #18395: inputs.ping with method "native" ignores "timeout" parameter
Using the ping input using `method = "native"`, I have noticed warning about pings that were taking longer than the defined interval even though I had set a timeout. After looking at the input's implementation, I noticed that the parameter is actually ignored when doing the native pings (unlike in the `exec` implementation).

I also looked at the native pinger implementation [here](https://github.com/prometheus-community/pro-bing/blob/main/ping.go). It seems that what their pinger call `timeout` is what iputils' ping call `deadline`, and that there is no per-ping timeout implemented. 

A workaround is to use `deadline`, as it is [used](https://github.com/influxdata/telegraf/blob/1d574f61977928252c559e93925156c8cad76628/plugins/inputs/ping/ping.go#L164-L166), but it is not strictly a replacement since it is an int while `timeout` is a float. 

Expectedly, the behavior is not documented in the ping input's readme.

### PR DESCRIPTION
**Pull request by WZH8898**
## Summary

Warn when the `timeout` parameter is set with `method = "native"`, since the native pinger ignores per-ping timeouts.

Updated documentation and sample config to clarify that `deadline` should be used to control timeout behavior for the native method.

## Checklist

- [x] No AI generated code was used in this PR
- [x] AI generated code used in this PR follows the [InfluxData Policy on AI-Generated Code Contributions][policy]

[policy]: https://www.influxdata.com/ai-generated-code-contributions-policy

## Related issues

resolves #18395

### CODE REVIEW

**Comment by srebhan** [comment]
@WZH8898 please restore the PR description template, especially the AI section, so we can review your contribution!

**Comment by WZH8898** [comment]
> @WZH8898 please restore the PR description template, especially the AI section, so we can review your contribution!

Thanks! I've restored the PR template and added the AI checklist section.
Please let me know if anything else needs to be adjusted.

**Comment by srebhan** [comment]
@WZH8898 to be honest I don't like the approach too much as it has too many assumptions. How about rather than trying to guess ask the user to use the `deadline` configuration option instead as this is what is used already? I.e. if you see `timeout` to be set with the `native` method, you should error out (or warn) in `Init()` that this parameter is not used for the method and what to do instead. Maybe also add some documentation to the README?

**Comment by WZH8898** [comment]
> @WZH8898 to be honest I don't like the approach too much as it has too many assumptions. How about rather than trying to guess ask the user to use the `deadline` configuration option instead as this is what is used already? I.e. if you see `timeout` to be set with the `native` method, you should error out (or warn) in `Init()` that this parameter is not used for the method and what to do instead. Maybe also add some documentation to the README?

Thanks for the suggestion! I've updated the implementation to warn when `timeout` is used with the native method and documented the behavior in the README.
Please let me know if further adjustments are needed.

File: plugins/inputs/ping/ping.go [hunk 1]
```diff
@@ -90,6 +90,10 @@ func (p *Ping) Init() error {
 		p.calcTimeout = time.Duration(p.Timeout) * time.Second
 	}
 
+	if p.Method == "native" && p.Timeout > 0 && p.Log != nil {
+		p.Log.Warn(`"timeout" is ignored when method = "native"; use "deadline" to control the total runtime`)
+	}
```
Comment (srebhan) [inline plugins/inputs/ping/ping.go]: `Log` always is non-nil at runtime. If you see a panic here it's because the tests do not define `Log` which is a bug and should be fixed by setting the logger in the test!

File: plugins/inputs/ping/ping.go [hunk 2]
```diff
@@ -160,7 +164,6 @@ func (p *Ping) nativePing(destination string) (*pingStats, error) {
 
 	pinger.Source = p.sourceAddress
 	pinger.Interval = p.calcInterval
-
```
Comment (srebhan) [inline plugins/inputs/ping/ping.go:163]: Please keep the newline.

File: plugins/inputs/ping/sample.conf [hunk 3]
```diff
@@ -21,11 +21,13 @@
   # ping_interval = 1.0
 
   ## If set, the time to wait for a ping response in seconds.  Operates like
-  ## the "-W" option of the ping command.
+  ## the "-W" option of the ping command.  This setting is used by the "exec"
+  ## method only.
```
Comment (srebhan) [inline plugins/inputs/ping/sample.conf]:
```suggestion
  ## the "-W" option of the ping command (for "exec" method only)
```

File: plugins/inputs/ping/sample.conf [hunk 4]
```diff
@@ -21,11 +21,13 @@
...
   # timeout = 1.0
 
-  ## If set, the total ping deadline, in seconds.  Operates like the -w option
-  ## of the ping command.
+  ## If set, the total ping deadline, in seconds.  Operates like the "-w"
+  ## option of the ping command.  Use this option to control timeout behavior
+  ## when using the "native" method.
```
Comment (srebhan) [inline plugins/inputs/ping/sample.conf]:
```suggestion
  ## If set, the total ping deadline, in seconds. Operates like the "-w"
  ## option of the ping command.  Use this option to control timeout behavior
  ## when using the "native" method.
```

**Comment by WZH8898** [comment]
> Thanks @WZH8898! Some more small comments...

Thanks for the suggestions! I've updated the code and applied the suggested changes.

**Comment by Hipska** [comment]
This PR now adds this warning even when not setting a `timeout` when using native method..

**Comment by Hipska** [comment]
Bummer this got released 😞
