### PR TITLE
fix(outputs.influxdb_v2): Use dynamic token secret

### LINKED ISSUE #16627: outputs.influxdb_v2 does not use new secret value when changed
### Relevant telegraf.conf

```toml
[[secretstores.docker]]
  id = "k8s_secrets"
  path = "/secrets"
  dynamic = true


[[outputs.influxdb_v2]]
  tagpass = {"?dlg_destination"=["data"]}
  tagexclude=["?dlg_destination"]
  urls = ["${DESTINATION_URL?:err}"]
  token = "@{k8s_secrets:dest_token_w}"
  organization = "allseas"
  bucket_tag = "?dlg_destination_bucket"
  timeout = "15s"
  exclude_bucket_tag = true
  content_encoding = "gzip"
  influx_uint_support = true
```

### Logs from Telegraf

```text
2025-03-13 13:10:57	2025-03-13T13:10:57Z E! [outputs.influxdb_v2] When writing to [http://*.allseas.global:8086/api/v2/write]: failed to write metric to ais (403 Forbidden): forbidden: insufficient permissions for write
```

### System info

Telegraf 1.34

### Docker

_No response_

### Steps to reproduce

1. Revoke existing access token (accidentally oops)
2. Update access token in k8s config
3. New token is not automatically used
...

### Expected behavior

The new token is used when it is updated, because `dynamic = true` is set.

### Actual behavior

The old token is still used.

### Additional info

Issue is here, the token should be read every time a request is made instead of just once at Init.

https://github.com/influxdata/telegraf/blob/1464e4fcf2c635fa1b9ec5db265a86841e5fff59/plugins/outputs/influxdb_v2/http.go#L78-L85

### PR DESCRIPTION
**Pull request by LarsStegman**
## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #16627

### CODE REVIEW

File: plugins/outputs/influxdb_v2/http.go [hunk 1]
```diff
@@ -75,14 +75,6 @@ func (c *httpClient) Init() error {
 		c.headers = make(map[string]string, 2)
```
Comment (srebhan) [inline plugins/outputs/influxdb_v2/http.go:75]: This should be
```suggestion
		c.headers = make(map[string]string, 1)
```
shouldn't it?

File: plugins/outputs/influxdb_v2/influxdb_v2_test.go [hunk 2]
```diff
@@ -859,3 +859,52 @@ func TestStatusCodeUnexpected(t *testing.T) {
...
+	}
+	// Write the metrics the first time and check for the expected errors
+	err := plugin.Write(metrics)
+	require.ErrorContains(t, err, "failed to write metric to my_bucket")
+	require.ErrorContains(t, err, strconv.Itoa(http.StatusForbidden))
+
+	err = secretToken.Set([]byte(token))
+	require.NoError(t, err)
+	err = plugin.Write(metrics)
+	require.NoError(t, err)
```
Comment (srebhan) [inline plugins/outputs/influxdb_v2/influxdb_v2_test.go:909]:
```suggestion
	require.NoError(t, secretToken.Set([]byte(token)))
	require.NoError(t, plugin.Write(metrics))
```

**Review by srebhan — COMMENTED** [review]
Thanks @LarsStegman for the fix! Just two small comments...

**Review by srebhan — APPROVED** [review]
Thanks a lot @LarsStegman! Much appreciated!

**Review by mstrandboge — APPROVED** [review]
