### PR TITLE
fix: Histogram Aggregator break metric expiration inside Prometheus client output

### LINKED ISSUE #10043: Histogram Aggregator break metric expiration inside Prometheus client output
### Relevent telegraf.conf

```toml
[agent]
  interval = "30s"
  round_interval = true
  metric_batch_size = 20000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_jitter = "0s"
  debug = true
  quiet = false

[[inputs.socket_listener]]
  service_address = "udp://:8125"
  data_format = "influx"

[[outputs.prometheus_client]]
  listen = ":9201"
  expiration_interval = "30s"
  metric_version = 2

[[aggregators.histogram]]
  period = "30s"
  drop_original = true
  reset = false
  cumulative = true

  [[aggregators.histogram.config]]
    measurement_name = "test"
    buckets = [0.0, 100.0, 300.0, 500.0, 700.0, 1000.0, 1500.0]
```

### System info

Telegraf 1.20.0

### Docker

_No response_

### Steps to reproduce

  1. Send `test ms=1` to udp://:8125
  2. Check /metrics endpoint -> buckets for test metric should be shown
  3. Wait for more that `expiration_interval `(30 seconds)
  4. Check /metrics endpoint

### Expected behavior

There are no metrics inside `/metrics` endpoint due to its expiration.

### Actual behavior

Expired metrics are still presented.

### Additional info

It's important for cases described in https://github.com/influxdata/telegraf/issues/10517 It allows to significantly decrease service loading. 
Following the code, Histogram Aggregator always pushes metrics with the current timestamp (historgram.go:173).

### PR DESCRIPTION
**Pull request by opengamer29**
### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #10043

Add a boolean flag to aggregator histogram config. Setting this flag to true allows pushing to output only updated histogram values and control metrics expiration inside output plugins. It allows increasing performance when there are a lot of metrics (for example during collect metrics from mobile devices as described in https://github.com/influxdata/telegraf/issues/10517)

### CODE REVIEW

**Review by powersj — APPROVED** [review]
Thanks for this!

File: plugins/aggregators/histogram/histogram.go [hunk 1]
```diff
@@ -66,7 +68,8 @@ type groupedByCountFields struct {
 // NewHistogramAggregator creates new histogram aggregator
 func NewHistogramAggregator() *HistogramAggregator {
 	h := &HistogramAggregator{
-		Cumulative: true,
+		Cumulative:       true,
+		PushOnlyOnUpdate: false,
```
Comment (srebhan) [inline plugins/aggregators/histogram/histogram.go:72]: This doesn't to be set as it is the Golang default, so please remove the `PushOnlyOnUpdate: false,` line.

File: plugins/aggregators/histogram/histogram.go [hunk 2]
```diff
@@ -151,6 +158,9 @@ func (h *HistogramAggregator) Add(in telegraf.Metric) {
 				index := sort.SearchFloat64s(buckets, value)
 				agr.histogramCollection[field][index]++
 			}
+			if h.PushOnlyOnUpdate {
+				agr.pushed = false
+			}
```
Comment (srebhan) [inline plugins/aggregators/histogram/histogram.go:163]: Maybe you should name the field `updated` and set it here unconditionally to `true`. This removes the `if` here and moves the whole effect of the `h.PushOnlyOnUpdate` option down to the `Push` function. This makes the code a bit easier to follow I think.

File: plugins/aggregators/histogram/histogram.go [hunk 3]
```diff
@@ -161,7 +171,15 @@ func (h *HistogramAggregator) Add(in telegraf.Metric) {
...
-	for _, aggregate := range h.cache {
+	for id, aggregate := range h.cache {
+		if h.PushOnlyOnUpdate {
+			if h.cache[id].pushed {
+				continue
+			}
+			aggregation := h.cache[id]
+			aggregation.pushed = true
+			h.cache[id] = aggregation
+		}
```
Comment (srebhan) [inline plugins/aggregators/histogram/histogram.go:182]: Given that you renamed the field to `updated` as suggested above you could do
```suggestion
		if h.PushOnlyOnUpdate  && ! h.cache[id].updated {
			// We only want to push aggregates that were updated between two pushes, so skip this one
			continue
		}
		aggregate.updated = true
		h.cache[id] = aggregate
```

**Review by srebhan — COMMENTED** [review]
Nice addition @opengamer29! I have some minor improvements that make the code more readable IMO.

File: plugins/aggregators/histogram/histogram.go (hunk 3 above)
Comment (opengamer29) [reply plugins/aggregators/histogram/histogram.go:182]: I think we can avoid the execution of the following code when off pushOnlyOnUpdate is turned off. It saves some milliseconds.
```
aggregation := h.cache[id]
aggregation.updated = false
h.cache[id] = aggregation
```

Comment (srebhan) [reply plugins/aggregators/histogram/histogram.go]: Honestly speaking, I prefer the better readability over the micro/nano-seconds that you might save (if the compiler optimizations miss it).

File: plugins/aggregators/histogram/histogram.go [hunk 4]
```diff
@@ -90,6 +92,10 @@ var sampleConfig = `
   ## Defaults to true.
   cumulative = true
 
+  ## If true, aggregated histogram are pushed to output only if it was updated since
+  ## previous push. Defaults to false.
+  push_only_on_update = false
+
```
Comment (srebhan) [inline plugins/aggregators/histogram/histogram.go:98]: Options with a default should be commented like
```suggestion
  ## If true, aggregated histogram are pushed to output only if it was updated since
  ## previous push.
  # push_only_on_update = false

```

**Review by srebhan — COMMENTED** [review]
Just a small comment on the `sampleConfig`, @opengamer29. Can you please also update the README?

File: plugins/aggregators/histogram/histogram.go (hunk 3 above)
Comment (opengamer29) [reply plugins/aggregators/histogram/histogram.go]: I work as a performance Engineer that's why sometimes I overoptimize something. Thanks for helping me with common sense.

**Review by srebhan — COMMENTED** [review]
Almost @opengamer29. Please also document the new option in the `README.md` file, plus a suggestion to save one more line... ;-P

File: plugins/aggregators/histogram/histogram.go [hunk 5]
```diff
@@ -161,7 +168,13 @@ func (h *HistogramAggregator) Add(in telegraf.Metric) {
...
 	metricsWithGroupedFields := []groupedByCountFields{}
 
-	for _, aggregate := range h.cache {
+	for id, aggregate := range h.cache {
+		if h.PushOnlyOnUpdate && !h.cache[id].updated {
+			continue
+		}
+		aggregation := h.cache[id]
+		aggregation.updated = false
+		h.cache[id] = aggregation
```
[the remark this answers is not in the document]
Comment (opengamer29) [reply plugins/aggregators/histogram/histogram.go]: Mostly android performance engineer 🤷 Didn't face programming on Go before. Thanks for the help.

**Comment by reimda** [comment]
I'm not understanding why someone would want to push only on update. Can you explain more about you use case.

I'm also wondering if there are other conditions for pushing? For example if there's a third condition it might be better to use a string setting instead of a boolean so we an add future conditions.

**Comment by opengamer29** [comment]
> I'm not understanding why someone would want to push only on update. Can you explain more about you use case.

I use telegraf to collect metrics from mobile devices (socket listener + histogram aggregator + prometheus output plugins). All my metrics contain the application version as one of the tags. And not all users update their applications often. 
For example, the current version is 1.7, but there are a few users with versions 1.4, 1.5, 1.6. So I have four times more metrics inside telegraf. The thing is that metrics with old tags are rare (but not rare enough to be ignored completely), that's why I tried to use Prometheus client output plugin expiration_time setting, but it didn't work due to the fact the metrics are pushed always.

This MR works great with the [new feature for expiration time setting inside the aggregator plugin](https://github.com/influxdata/telegraf/issues/10517) and additionally decreases output metrics count. And if the expiration interval for Prometheus output is set to twice more (or four times more) than the scraping interval there will not be any data miss with decreased overhead.

> I'm also wondering if there are other conditions for pushing? For example if there's a third condition it might be better to use a string setting instead of a boolean so we an add future conditions.

I can't find another condition.

**Comment by powersj** [comment]
@opengamer29,

This has prompted some more questions

> For example, the current version is 1.7, but there are a few users with versions 1.4, 1.5, 1.6. So I have four times more metrics inside telegraf. The thing is that metrics with old tags are rare (but not rare enough to be ignored completely), that's why I tried to use Prometheus client output plugin expiration_time setting, but it didn't work due to the fact the metrics are pushed always.

What is your goal with these older versions? get rid of them? ignore them?

Once you push to Prometheus are you then consuming them with something else and viewing the metrics?

**Comment by opengamer29** [comment]
@powersj 

No, those versions are not ignored. 
We use Grafana to display our data. And almost all our graphs are built on [rate function](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate) (which requires data to be presented only at the start and end of interval). There is one more Prometheus feature to help save data quality - [staleness](https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness). Wich allows using up-to-5-minutes-old data if data in the current timestamp is absent.

Here is a simplified example (in the real world push and scraping, happen at different times):

following metrics are reported:
```
0s
time_start_app,ver=1.5 ms=10
time_start_app,ver=1.6 ms=10
time_start_app,ver=1.7 ms=10
30s
time_start_app,ver=1.7 ms=10
60s
time_start_app,ver=1.7 ms=10
90s
time_start_app,ver=1.6 ms=10
time_start_app,ver=1.7 ms=10
```

following histograms will be pushed to output and will be scraped WITH fix:
```
30s
time_start_app_ms_bucket,ver=1.5,le=+Inf 1
time_start_app_ms_bucket,ver=1.6,le=+Inf 1
time_start_app_ms_bucket,ver=1.7,le=+Inf 1
60s
time_start_app_ms_bucket,ver=1.7,le=+Inf 2
90s
time_start_app_ms_bucket,ver=1.6,le=+Inf 3
120s
time_start_app_ms_bucket,ver=1.6,le=+Inf 2
time_start_app_ms_bucket,ver=1.7,le=+Inf 4
```

following histograms will be pushed to output and will be scraped WITHOUT fix:
```
30s
time_start_app_ms_bucket,ver=1.5,le=+Inf 1
time_start_app_ms_bucket,ver=1.6,le=+Inf 1
time_start_app_ms_bucket,ver=1.7,le=+Inf 1
60s
time_start_app_ms_bucket,ver=1.5,le=+Inf 1
time_start_app_ms_bucket,ver=1.6,le=+Inf 1
time_start_app_ms_bucket,ver=1.7,le=+Inf 2
90s
time_start_app_ms_bucket,ver=1.5,le=+Inf 1
time_start_app_ms_bucket,ver=1.6,le=+Inf 1
time_start_app_ms_bucket,ver=1.6,le=+Inf 3
120s
time_start_app_ms_bucket,ver=1.5,le=+Inf 1
time_start_app_ms_bucket,ver=1.6,le=+Inf 2
time_start_app_ms_bucket,ver=1.7,le=+Inf 4
```

By setting expiration_interval for prometheus_client at twice more than the scraping interval we can be sure that all data will be scraped and at the same time using rate functions and prom staleness allow us to work with ommited (in current timestamp) data. If prom rate func interval starts or ends with where are no scraped data up-to-5-minutes-old data will be used and it's fine because it (in fact, previous scraped value will be used). The count of scraped metrics will be significantly decreased as well as Prometheus scraping time.

**Review by srebhan — APPROVED** [review]
Looks good for me. Thanks for working on this @opengamer29!
