### PR TITLE
fix(outputs.nebius_cloud_monitoring): replace reserved label names

### LINKED ISSUE #13596: Nebius Cloud Monitoring has reserved "name" tag, so it must be replaced
### Relevant telegraf.conf

```toml
# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true
  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000
  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 10000
  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"
  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"
  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = ""
  ## Log at debug level.
  debug = true
  ## Log only error level messages.
  # quiet = false
  ## Log target controls the destination for logs and can be one of "file",
  ## "stderr" or, on Windows, "eventlog".  When set to "file", the output file
  ## is determined by the "logfile" setting.
  # logtarget = "file"
  ## Name of the file to be logged to when using the "file" logtarget.  If set to
  ## the empty string then logs are written to stderr.
  # logfile = ""
  ## The logfile will be rotated after the time interval specified.  When set
  ## to 0 no time based rotation is performed.  Logs are rotated only when
  ## written to, if there is no log activity rotation may be delayed.
  # logfile_rotation_interval = "0d"
  ## The logfile will be rotated when it becomes larger than the specified
  ## size.  When set to 0 no size based rotation is performed.
  # logfile_rotation_max_size = "0MB"
  ## Maximum number of rotated archives to keep, any older logs are deleted.
  ## If set to -1, no archives are removed.
  # logfile_rotation_max_archives = 5
  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to
  ## Note: Most, but not all, udev properties can be accessed this way. Properties
  ## that are currently inaccessible include DEVTYPE, DEVNAME, and DEVPATH.
  # device_tags = ["ID_FS_TYPE", "ID_FS_USAGE"]
  #
  ## Using the same metadata source as device_tags, you can also customize the
  ## name of the device via templates.
  ## The 'name_templates' parameter is a list of templates to try and apply to
  ## the device. The template may contain variables in the form of '$PROPERTY' or
  ## '${PROPERTY}'. The first template which does not contain any variables not
  ## present for the device is used as the device name tag.
  ## The typical use case is for LVM volumes, to get the VG/LV name instead of
  ## the near-meaningless DM-0 name.
  # name_templates = ["$ID_FS_LABEL","$DM_VG_NAME/$DM_LV_NAME"]
# fieldpass = ["reads","writes","read_bytes","write_bytes"]
[[inputs.netstat]]
[[inputs.ntpq]]

[[inputs.procstat]]
  exe = "docker"
# Get kernel statistics from /proc/stat
[[inputs.kernel]]
  # no configuration
# Read metrics about memory usage
[[inputs.mem]]
  # no configuration
  fieldpass = ["available","used_percent"]
# Get the number of processes and group them by status
[[inputs.processes]]
  # no configuration
# Read metrics about swap memory usage
[[inputs.swap]]
  # no configuration
  fieldpass = ["free","used_percent"]
# Read metrics about system load & uptime
[[inputs.system]]
  ## Uncomment to remove deprecated metrics.
  # fielddrop = ["uptime_format"]
  fieldpass = ["uptime"]
[[inputs.systemd_units]]
  unittype="service"
  #pattern = "telegraf*"
[[inputs.net_response]]
  protocol = "tcp"
  address = "localhost:22"
[[outputs.nebius_cloud_monitoring]]
```

### Logs from Telegraf

```text
2023-07-11T13:11:52Z I! Loading config: /etc/telegraf/telegraf.conf                                                               2023-07-11T13:11:52Z W! DeprecationWarning: Option "dns_lookup" of plugin "inputs.ntpq" deprecated since version 1.24.0 and will b
e removed in 2.0.0: add '-n' to 'options' instead to skip DNS lookup                                                              2023-07-11T13:11:52Z I! Starting Telegraf 1.28.0-35010d74
2023-07-11T13:11:52Z I! Available plugins: 237 inputs, 9 aggregators, 28 processors, 23 parsers, 59 outputs, 4 secret-stores      2023-07-11T13:11:52Z I! Loaded inputs: cpu disk kernel mem net_response netstat ntpq processes procstat swap system systemd_units
2023-07-11T13:11:52Z I! Loaded aggregators:                                                                                       2023-07-11T13:11:52Z I! Loaded processors:
2023-07-11T13:11:52Z I! Loaded secretstores:                                                                                      2023-07-11T13:11:52Z W! Outputs are not used in testing mode!
2023-07-11T13:11:52Z I! Tags enabled: datacenter=hrc host=ua-vm-exporter                                                          2023-07-11T13:11:52Z W! Deprecated inputs: 0 and 1 options
2023-07-11T13:11:52Z D! [agent] Initializing plugins                                                                              2023-07-11T13:11:52Z D! [agent] Starting service inputs
> systemd_units,active=active,datacenter=hrc,host=ua-vm-exporter,load=loaded,name=accounts-daemon.service,sub=running active_code=0i,load_code=0i,sub_code=0i 1689081113000000000
```

### System info

Telegraf 1.28.0? Ubuntu 20.04.6 LTS

### Docker

_No response_

### Steps to reproduce

1. Launch 1.28 telegraf agent on ubuntu with outputs.nebius_cloud_monitoring plugin

### Expected behavior

systemd metrics must be written to Nebius Monitoting backend.

### Actual behavior

systemd metrics will not be written to Nebius Monitoting backend.

### Additional info

Answer from Nebius support:

> 
> Indeed you cannot use:
> %%(json)
> {
> "name": "systemd_units_load_code",
> "labels": {
> "active": "active",
> "datacenter": "hrc",
> "host": "ua-vm-exporter",
> "load": "loaded",
> "name": "accounts-daemon.service",
> "sub": "running"
> },
> "ts": "2023-06-06T11:10:50Z",
> "value": 0
> }
> %%
> where "name" is defined twice (one at top level of JSON metric, one at labels section)
> 
> => Can you try to remove the %%(json).labels.name%% and use only "name" at top level?
> 
> Thanks in advance for your attention and feedback
> 
> >

### PR DESCRIPTION
**Pull request by abrekhov**
# Required for all PRs

- [X] Updated associated README.md.
- [X] Wrote appropriate unit tests.
- [X] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #13596

### CODE REVIEW

File: plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go [hunk 1]
```diff
@@ -242,3 +242,13 @@ func init() {
 		return &NebiusCloudMonitoring{}
 	})
 }
+
+func replaceReservedTagNames(tagNames map[string]string) map[string]string {
+	for tagName, tagValue := range tagNames {
+		if tagName == "name" {
+			tagNames["label_name"] = tagValue
```
Comment (powersj) [inline plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go:249]: can you get a screenshot or let us know how this will appear in the nebius UI? I want to be clear as to what this might look like and ensure the double "label" name makes sense.

**Review by powersj — COMMENTED** [review]
Hi!

Thanks for the quick fix. Can you also please add a section to the plugin README called "Reserved Labels" and explain that tags with the key "name" are renamed.

One question inline as well about what this ultimately looks like in Nebius.

File: plugins/outputs/nebius_cloud_monitoring/README.md [hunk 2]
```diff
@@ -34,3 +34,57 @@ Folder ID from instance metadata. In this plugin we use [Google Cloud notation]
 This internal metadata endpoint is only accessible for VMs from the cloud.
 
 [Google Cloud notation]: https://nebius.com/il/docs/compute/operations/vm-info/get-info#gce-metadata
+
+### Reserved Labels
+
+Nebius Monitoring backend using json format to receive the metrics:
+
+```json
+
```
Comment (Hipska) [inline plugins/outputs/nebius_cloud_monitoring/README.md:43]:
```suggestion
```

File: plugins/outputs/nebius_cloud_monitoring/README.md [hunk 3]
```diff
@@ -34,3 +34,57 @@ Folder ID from instance metadata. In this plugin we use [Google Cloud notation]
...
+```json
+{
+"name": "metric_name",
+"labels": {
+"key": "value",
+...
```
Comment (Hipska) [inline plugins/outputs/nebius_cloud_monitoring/README.md:49]:
```suggestion
"key": "value",
"foo": "bar"
```

File: plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go [hunk 4]
```diff
@@ -242,3 +242,15 @@ func init() {
 		return &NebiusCloudMonitoring{}
 	})
 }
+
+func replaceReservedTagNames(tagNames map[string]string) map[string]string {
+	newTags := make(map[string]string)
+	for tagName, tagValue := range tagNames {
+		if tagName == "name" {
```
Comment (Hipska) [inline plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go:249]: Is `name` the only reserved keyword?

File: plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go (hunk 1 above)
Comment (Hipska) [reply plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go]: I agree, maybe `_name` would be better?

File: plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go [hunk 5]
```diff
@@ -242,3 +242,15 @@ func init() {
 		return &NebiusCloudMonitoring{}
 	})
 }
+
+func replaceReservedTagNames(tagNames map[string]string) map[string]string {
+	newTags := make(map[string]string)
```
Comment (Hipska) [inline plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go:247]:
```suggestion
	newTags := make(map[string]string, len(tagNames))
```

File: plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring_test.go [hunk 6]
```diff
@@ -137,3 +164,39 @@ func TestWrite(t *testing.T) {
...
+				tagNames: tagMap,
+			},
+			want: wantTagMap,
+		},
+	}
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			if got := replaceReservedTagNames(tt.args.tagNames); !reflect.DeepEqual(got, tt.want) {
+				t.Errorf("replaceReservedTagNames() = %v, want %v", got, tt.want)
+			}
```
Comment (Hipska) [inline plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring_test.go:199]: Why not this?
```suggestion
			got := replaceReservedTagNames(tt.args.tagNames)
			require.EqualValues(tt, tt.want, tt.got)
```

**Review by Hipska — CHANGES_REQUESTED** [review]

File: plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go (hunk 4 above)
Comment (abrekhov) [reply plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go:249]: As I understand from support team - yes. There are direct message from support in linked issue.

Comment (Hipska) [reply plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go:249]: So, what about `ts` and `value`? They work correctly?

File: plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring_test.go [hunk 7]
```diff
@@ -1,10 +1,12 @@
 package nebius_cloud_monitoring
 
 import (
+	_ "embed"
```
Comment (Hipska) [inline plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring_test.go:4]: I don't think this is needed here?

File: plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go (hunk 4 above)
Comment (abrekhov) [reply plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go:249]: Yes. I will attach screenshot how it looks like in Nebius. Right now it's working correctly. I just want to use suggestion about _name.

File: plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring_test.go (hunk 7 above)
Comment (abrekhov) [reply plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring_test.go]: Yeap, I've removed it. Take a look.

File: plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring_test.go [hunk 8]
```diff
@@ -119,6 +119,31 @@ func TestWrite(t *testing.T) {
...
+					},
+					time.Unix(0, 0),
+				),
+			},
+			handler: func(t *testing.T, w http.ResponseWriter, r *http.Request) {
+				message, err := readBody(r)
+				require.NoError(t, err)
+				require.Len(t, message.Metrics, 1)
+				require.Equal(t, "cluster_value", message.Metrics[0].Name)
+				require.Equal(t, "accounts-daemon.service", message.Metrics[0].Labels["_name"])
```
Comment (Hipska) [inline plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring_test.go:142]: Shouldn't the check better be if `_name` label exists?

**Review by powersj — APPROVED** [review]

File: plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring_test.go (hunk 8 above)
Comment (srebhan) [reply plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring_test.go:142]: That's what is done, isn't it?

File: plugins/outputs/nebius_cloud_monitoring/README.md [hunk 9]
```diff
@@ -34,3 +34,55 @@ Folder ID from instance metadata. In this plugin we use [Google Cloud notation]
...
+"labels": {
+"active": "active",
+"host": "vm",
+"load": "loaded",
+"_name": "accounts-daemon.service",
+"sub": "running"
+},
+"ts": "2023-06-06T11:10:50Z",
+"value": 0
+}
```
Comment (srebhan) [inline plugins/outputs/nebius_cloud_monitoring/README.md:87]: Can we maybe prettify the JSON sections with some indentation to make them more readable?!

File: plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring_test.go (hunk 8 above)
Comment (Hipska) [reply plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring_test.go:142]: No, as it now will panic or error out if `message.Metrics[0].Labels` doesn't have an item called `_name`.

File: plugins/outputs/nebius_cloud_monitoring/README.md (hunk 9 above)
Comment (abrekhov) [reply plugins/outputs/nebius_cloud_monitoring/README.md]: done

File: plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring_test.go [hunk 10]
```diff
@@ -137,3 +162,38 @@ func TestWrite(t *testing.T) {
...
+
+	type args struct {
+		tagNames map[string]string
+	}
+	tests := []struct {
+		name string
+		args args
+		want map[string]string
+	}{
+		// TODO: Add test cases.
```
[the remark this answers is not in the document]
Comment (abrekhov) [reply plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring_test.go]: done

File: plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go (hunk 4 above)
Comment (srebhan) [reply plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go:249]: @Hipska I think you are mixing up two things here. It's not that you cannot use `name` because it exists above the `labels` list, it's because it seems to be reserved in Nebius which creates a `name` label itself. Therefore there might be no relation to `ts` and `value` just because it also exists in the JSON... In any case, if we find more reserved labels later, we can still add them.

**Review by srebhan — APPROVED** [review]
Looks good to me. Thanks for the fix @abrekhov!

File: plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go (hunk 4 above)
Comment (Hipska) [reply plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go:249]: It would clear up if @abrekhov would quickly test it, just to be sure.

Comment (abrekhov) [reply plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go:249]: I hope that nobody will put ts and value as labels :) But if there will be cases - we will add it.

Comment (Hipska) [reply plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go:249]: But did you test if they give problems or not?
