### PR TITLE
fix(inputs.tail): Prevent leaking file descriptors

### LINKED ISSUE #7959: inputs.tail is not releasing file descriptor when file is deleted
### Relevant telegraf.conf:

```toml
[[inputs.tail]]
  ## files to tail.
  ## These accept standard unix glob matching rules, but with the addition of
  ## ** as a "super asterisk". ie:
  ##   "/var/log/**.log"  -> recursively find all .log files in /var/log
  ##   "/var/log/*/*.log" -> find all .log files with a parent dir in /var/log
  ##   "/var/log/apache.log" -> just tail the apache log file
  ##
  ## See https://github.com/gobwas/glob for more examples
  ##
  files = ["/tmp/metrics/*.out"]
##   ## Read file from beginning.
   from_beginning = true
```

### System info:
centos7 telegraf 1.15.2 

```bash
[vagrant@localhost telegraf]$ ./telegraf version
Telegraf 1.15.2 (git: HEAD cd037b49)
```
### Steps to reproduce:

1. use configuration as provided
2. ./telegraf -config telegraf.conf
3.  run following command:
```bash 
mkdir -p /tmp/metrics &&  echo 'example,tag1=a,tag2=b i=42i,j=43i,k=44i'  >> /tmp/metrics/logs_00.out
```
4. wait 60 seconds
5. remove file:
```bash
rm -rf /tmp/metrics/logs_00.out
```
6. check file descriptor is not released:
```bash
[vagrant@localhost telegraf]$ lsof | grep metrics | grep logs_00
telegraf  18104              vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)
telegraf  18104 18105        vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)
telegraf  18104 18106        vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)
telegraf  18104 18107        vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)
telegraf  18104 18108        vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)
telegraf  18104 18109        vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)
telegraf  18104 18110        vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)
telegraf  18104 18112        vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)
telegraf  18104 18113        vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)
telegraf  18104 18114        vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)
telegraf  18104 18115        vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)

```

### Expected behavior:

It should release all deleted file descriptors. 

### Actual behavior:
It doesn't release the file descriptors.
### Additional info:
This is affecting functionality as when too many files are created and deleted telegraf stops working as it cannot open more files due to running out of file descriptors.

### LINKED ISSUE #16750: Telegraf process does not release the log files after writing
### Relevant telegraf.conf

```toml
Hi,

I am testing telegraf on an EC2 instance. The process is keeping too many log file descriptors open. Sometimes it hits the open files ulimit for the user (65535). 
Shouldn't the process release file descriptors to log file after writing?

The version I am testing is 1.24.2. Is this a known bug thats fixed in new version?
Do you have a work around for this version?


These are the only log specific config I have:


  ## Log target controls the destination for logs and can be one of "file",
  ## "stderr" or, on Windows, "eventlog".  When set to "file", the output file
  ## is determined by the "logfile" setting.
  logtarget = "file"

  ## Name of the file to be logged to when using the "file" logtarget.  If set to
  ## the empty string then logs are written to stderr.
  logfile = "/var/log/telegraf/telegraf.log"
```

### Logs from Telegraf

```text
From "lsof -p <telegraf-pid>"


telegraf 15580 telegraf  444r      REG              259,2   5291575  8885586 /var/log/telegraf/telegraf.log
telegraf 15580 telegraf  445r      REG              259,2   5291575  8885586 /var/log/telegraf/telegraf.log
telegraf 15580 telegraf  446r      REG              259,2   5291575  8885586 /var/log/telegraf/telegraf.log
telegraf 15580 telegraf  447r      REG              259,2   5291575  8885586 /var/log/telegraf/telegraf.log
telegraf 15580 telegraf  449r      REG              259,2   5291575  8885586 /var/log/telegraf/telegraf.log
telegraf 15580 telegraf  450r      REG              259,2   5291575  8885586 /var/log/telegraf/telegraf.log
telegraf 15580 telegraf  451r      REG              259,2   5291575  8885586 /var/log/telegraf/telegraf.log


At normal times:

$lsof -p 15580   | grep telegraf.log | wc -l
419


When it hits open files limit:


$lsof -p 2650 | wc -l
65539
$lsof -p 2650   | grep telegraf.log | wc -l
65502
```

### System info

Telegraf 1.24.2, Amazon linux 2 OS

### Docker

_No response_

### Steps to reproduce

Run "lsof" on the telegraf process, and check for how many instances of log files is open at a time. 

### Expected behavior

I expected a lower number as the log streams are closed after each execution or hit a timeout.

### Actual behavior

High number of file descriptors open accessing telegraf.log.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skartikey**
## Summary

The `inputs.tail` plugin leaks file descriptors across collection cycles, potentially exhausting the system's open file limit (ulimit). This happens because the plugin creates new tailers in each `tailNewFiles()` call without properly cleaning up tailers for files that no longer match glob patterns.

### Root Cause
In the `tailNewFiles()` method, the check `if _, ok := t.tailers[file]; ok {}` only prevents duplicate tailers within a single collection cycle but doesn't address the accumulation of unused tailers across multiple cycles. This leads to file descriptor leaks, especially noticeable when Telegraf monitors its own log file or rapidly changing sets of files.

### Fix Implementation
1. **Track current files**: Added a `currentFiles` map to keep track of files being processed in the current cycle
2. **Clean up unused tailers**: Added logic to identify and remove tailers for files that no longer match the glob patterns
3. **Enhanced cleanup in Stop()**: Modified to explicitly delete tailers from the map during shutdown
4. **Fixed goroutine closure**: Properly pass the tailer variable to avoid potential race conditions

This fix ensures that file descriptors are properly released when files are no longer being monitored, preventing resource exhaustion during extended operation.

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #7959
resolves #16750

### CODE REVIEW

File: plugins/inputs/tail/tail.go [hunk 1]
```diff
@@ -290,25 +310,62 @@ func (t *Tail) tailNewFiles() error {
...
+			if err != nil {
+				t.Log.Errorf("Stopping tail on %q: %s", tailer.Filename, err.Error())
+			}
+
+			// Remove from our map
+			delete(t.tailers, file)
 		}
 	}
+	t.tailersMutex.Unlock()
+
```
Comment (srebhan) [inline plugins/inputs/tail/tail.go:368]: Could we move this to an own function to be able to do `defer t.tailersMutex.Unlock()` and return an error please!? I feel like the code is complex enough that we later run into trouble if someone errors out and we keep the mutex locked...

File: plugins/inputs/tail/tail.go [hunk 2]
```diff
@@ -290,25 +310,62 @@ func (t *Tail) tailNewFiles() error {
...
+			// Save the current offset for potential future use
+			if !t.Pipe {
+				offset, err := tailer.Tell()
+				if err == nil {
+					t.Log.Debugf("Recording offset %d for %q", offset, tailer.Filename)
+					t.offsets[tailer.Filename] = offset
+				} else {
+					t.Log.Errorf("Recording offset for %q: %s", tailer.Filename, err.Error())
+				}
+			}
```
Comment (srebhan) [inline plugins/inputs/tail/tail.go:355]: Shouldn't this be done when reading the file? Otherwise the offset might be lost if Telegraf goes down without stop tailing a file...

File: plugins/inputs/tail/tail_test.go [hunk 3]
```diff
@@ -1030,3 +1030,172 @@ func TestInitInitialReadOffset(t *testing.T) {
...
+	defer tt.Stop()
+
+	// Wait for the plugin to process the file
+	acc.Wait(1)
+
+	// Make sure we got the first metric
+	acc.AssertContainsFields(t, "cpu",
+		map[string]interface{}{
+			"usage_idle": float64(100),
+		})
```
Comment (srebhan) [inline plugins/inputs/tail/tail_test.go:1064]: Please use a `require.Eventually` here. This type of code calls for trouble as if the test fails the CI pipeline will run until triggering a timeout which is an unnecessary waste of resources...

File: plugins/inputs/tail/tail_test.go [hunk 4]
```diff
@@ -1030,3 +1030,172 @@ func TestInitInitialReadOffset(t *testing.T) {
...
+
+	// Call Gather multiple times to simulate multiple collection intervals
+	require.NoError(t, acc.GatherError(tt.Gather))
+	require.NoError(t, acc.GatherError(tt.Gather))
+	require.NoError(t, acc.GatherError(tt.Gather))
+
+	// Verify we only have one tailer for the file, not multiple
+	require.Len(t, tt.tailers, 1, "Expected only one tailer despite multiple Gather calls")
```
Comment (srebhan) [inline plugins/inputs/tail/tail_test.go:1072]: Isn't this racy as the plugin is still running and might pick up new tailers?

File: plugins/inputs/tail/tail_test.go [hunk 5]
```diff
@@ -1030,3 +1030,172 @@ func TestInitInitialReadOffset(t *testing.T) {
...
+
+	// Call Gather multiple times to ensure the plugin sees the new data
+	for i := 0; i < 5; i++ {
+		require.NoError(t, acc.GatherError(tt.Gather))
+		// If we have the metric we're looking for, we can break early
+		if acc.HasPoint("cpu", nil, "usage_idle", float64(200)) {
+			break
+		}
+		time.Sleep(100 * time.Millisecond)
+	}
```
Comment (srebhan) [inline plugins/inputs/tail/tail_test.go:1097]: Use [`require.Eventually`](https://pkg.go.dev/github.com/stretchr/testify/require#Eventually) please!

**Review by srebhan — COMMENTED** [review]
Thanks for the fix @skartikey! Please find some comments from my side in the code...

File: plugins/inputs/tail/tail_test.go (hunk 4 above)
Comment (skartikey) [reply plugins/inputs/tail/tail_test.go:1072]: Thank you for catching that potential race condition.

File: plugins/inputs/tail/tail.go (hunk 1 above)
Comment (skartikey) [reply plugins/inputs/tail/tail.go]: Excellent point! Moved the code to its method.

File: plugins/inputs/tail/tail_test.go [hunk 6]
```diff
@@ -1030,3 +1060,198 @@ func TestInitInitialReadOffset(t *testing.T) {
...
+	tt.tailersMutex.RLock()
+	tailerCount := len(tt.tailers)
+	tt.tailersMutex.RUnlock()
+	require.Equal(t, 1, tailerCount, "Expected only one tailer despite multiple Gather calls")
+
+	// Reset the accumulator to make it easier to test for the new value
+	acc.ClearMetrics()
+
+	// Stop the current tailer to avoid race conditions
+	tt.Stop()
```
Comment (srebhan) [inline plugins/inputs/tail/tail_test.go:1117]: Hmmm this might influence the testing result... Imagine in a future PR we accidentally are not closing the tailers correctly during normal processing but _do_ close them on `Stop()`. Your test would still work pass but the code is broken.
You don't need to worry about getting partial data as the underlying `tail` library will only return whole lines (i.e. it blocks until it sees a newline).

File: plugins/inputs/tail/tail_test.go [hunk 7]
```diff
@@ -1030,3 +1060,198 @@ func TestInitInitialReadOffset(t *testing.T) {
...
+	// Wait for tailers to initialize
+	require.Eventually(t, func() bool {
+		tt.tailersMutex.RLock()
+		tailerCount := len(tt.tailers)
+		tt.tailersMutex.RUnlock()
+		return tailerCount == 2
+	}, time.Second, 100*time.Millisecond, "Expected two tailers to be initialized")
+
+	// Now stop all current tailers to avoid race conditions
+	tt.Stop()
```
Comment (srebhan) [inline plugins/inputs/tail/tail_test.go:1194]: See above.

**Review by srebhan — COMMENTED** [review]
@skartikey just two more comments on the tests...

**Comment by srebhan** [comment]
@skartikey would this PR also potentially solve #7959?

File: plugins/inputs/tail/tail_test.go (hunk 6 above)
Comment (skartikey) [reply plugins/inputs/tail/tail_test.go]: Thanks for catching that! You're right, by calling tt.Stop() between test phases, I was potentially masking bugs that could occur during normal operation. I've updated both tests accordingly.

**Review by srebhan — APPROVED** [review]
Awesome. Thanks @skartikey!

**Review by mstrandboge — APPROVED** [review]
