### PR TITLE
fix(inputs.procstat): Handle newer versions of systemd correctly

### LINKED ISSUE #17904: [[inputs.procstat]] plugin does not show Systemd children
### Relevant telegraf.conf

```toml
[[inputs.procstat]]
systemd_unit = "falcon-sensor.service"
include_systemd_children = true

[[inputs.procstat]]
systemd_unit = "splunkforwarder.service"
pid_tag = false

[[inputs.procstat]]
systemd_unit = "qualys-cloud-agent.service"
pid_tag = false

[[inputs.procstat]]
systemd_unit = "sshd.service"
pid_tag = false

[[inputs.procstat]]
systemd_unit = "cron.service"
pid_tag = false

[[inputs.procstat]]
systemd_unit = "telegraf.service"
pid_tag = false

[[inputs.procstat]]
systemd_unit = "ntp.service"
pid_tag = false

[[inputs.procstat]]
systemd_unit = "nss_updatedb.service"
pid_tag = false

[[outputs.graphite]]
servers = ["xxxx:2003"]
prefix = ""
graphite_tag_support = true
timeout = 2

[[outputs.prometheus_client]]
  listen = ":9100"
  path = "/metrics"
  metric_version = 1
  expiration_interval = "60s"
```

### Logs from Telegraf

```text
Oct 29 04:13:50 imvaultstg-co-1 systemd[1]: Starting Telegraf...
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z I! Loading config: /etc/telegraf/telegraf.conf
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z I! Loading config: /etc/telegraf/telegraf.d/graphite_output.conf
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z I! Loading config: /etc/telegraf/telegraf.d/prometheus_output.conf
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z I! Loading config: /etc/telegraf/telegraf.d/system_debian_systemd.conf
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z I! Loading config: /etc/telegraf/telegraf.d/system_metrics.conf
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z I! Loading config: /etc/telegraf/telegraf.d/vault_network.conf
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z I! Loading config: /etc/telegraf/telegraf.d/vault_ping.conf
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z I! Loading config: /etc/telegraf/telegraf.d/vault_service.conf
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z I! Starting Telegraf 1.35.2 brought to you by InfluxData the makers of InfluxDB
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z I! Available plugins: 238 inputs, 9 aggregators, 34 processors, 26 parsers, 65 outputs, 6 secret-stores
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z I! Loaded inputs: cpu disk diskio file (2x) kernel kernel_vmstat mem net net_response (2x) netstat ping processes procstat (8x) swap system systemd_units (3x)
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z I! Loaded aggregators:
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z I! Loaded processors:
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z I! Loaded secretstores:
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z I! Loaded outputs: graphite prometheus_client
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z I! Tags enabled: datacenter=co host=imvaultstg-co-1 zzz_team=psa
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"imvaultstg-co-1", Flush Interval:10s
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z W! [agent] The default value of 'skip_processors_after_aggregators' will change to 'true' with Telegraf v1.40.0! If you need the current default behavior, please explicitly set the option t>
Oct 29 04:13:50 imvaultstg-co-1 systemd[1]: Started Telegraf.
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z D! [agent] Initializing plugins
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z W! DeprecationWarning: Value "false" for option "ignore_protocol_stats" of plugin "inputs.net" deprecated since version 1.27.3 and will be removed in 1.36.0: use the 'inputs.nstat' plugin i>
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z D! [agent] Connecting outputs
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z D! [agent] Attempting connection to [outputs.graphite]
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z D! [outputs.graphite] Successful connections: 1 of 1
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z D! [agent] Successfully connected to outputs.graphite
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z D! [agent] Attempting connection to [outputs.prometheus_client]
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z I! [outputs.prometheus_client] Listening on http://[::]:9100/metrics
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z D! [agent] Successfully connected to outputs.prometheus_client
Oct 29 04:13:50 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:13:50Z D! [agent] Starting service inputs
Oct 29 04:14:00 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:14:00Z D! [outputs.prometheus_client] Wrote batch of 77 metrics in 1.654693ms
Oct 29 04:14:00 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:14:00Z D! [outputs.prometheus_client] Buffer fullness: 0 / 10000 metrics
Oct 29 04:14:00 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:14:00Z D! [outputs.graphite] Wrote batch of 77 metrics in 15.971111ms
Oct 29 04:14:00 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:14:00Z D! [outputs.graphite] Buffer fullness: 0 / 10000 metrics
Oct 29 04:14:10 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:14:10Z D! [outputs.prometheus_client] Wrote batch of 78 metrics in 2.924033ms
Oct 29 04:14:10 imvaultstg-co-1 telegraf[4130045]: 2025-10-29T11:14:10Z D! [outputs.prometheus_client] Buffer fullness: 0 / 10000 metrics
```

### System info

"Debian GNU/Linux 11 (bullseye)", Telegraf 1.35.2

### Docker

_No response_

### Steps to reproduce

We have a falcon systemd unit running a process that spawns several child processes

```
─falcon-sensor.service …
             │ └─sensor.falcon
             │   ├─1856439 /opt/CrowdStrike/falcond
             │   └─1856440 falcon-sensor-bpf
```

PID ```1856439``` is a parent process of PID ```1856440 ```

```
root     1856439       1  0 Oct14 ?        00:00:00 /opt/CrowdStrike/falcond
root     1856440 1856439  0 Oct14 ?        03:04:22 falcon-sensor-bpf
```

### Expected behavior

We expect that we can see metrics from both processes

- falcond
- falcon-sensor-bpf

### Actual behavior

We don't see any metrics at all for any processes from ```falcon``` systemd unit.

```
# TYPE procstat_child_major_faults untyped
procstat_child_major_faults{cmdline="/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d",datacenter="co",host="imvaultstg-co-1",process_name="telegraf",status="sleep",systemd_unit="telegraf.service",user="telegraf",zzz_team="psa"} 2
procstat_child_major_faults{cmdline="/usr/local/qualys/cloud-agent/bin/qualys-cloud-agent",datacenter="co",host="imvaultstg-co-1",process_name="qualys-cloud-agent",status="sleep",systemd_unit="qualys-cloud-agent.service",user="root",zzz_team="psa"} 2739
procstat_child_major_faults{cmdline="/usr/sbin/cron -f",datacenter="co",host="imvaultstg-co-1",process_name="cron",status="sleep",systemd_unit="cron.service",user="root",zzz_team="psa"} 575
procstat_child_major_faults{cmdline="/usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 106:112",datacenter="co",host="imvaultstg-co-1",process_name="ntpd",status="sleep",systemd_unit="ntp.service",user="ntp",zzz_team="psa"} 0
procstat_child_major_faults{cmdline="splunkd --under-systemd --systemd-delegate=no -p 8089 _internal_launch_under_systemd",datacenter="co",host="imvaultstg-co-1",process_name="splunkd",status="sleep",systemd_unit="splunkforwarder.service",user="splunkfwd",zzz_team="psa"} 846
procstat_child_major_faults{cmdline="sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups",datacenter="co",host="imvaultstg-co-1",process_name="sshd",status="sleep",systemd_unit="sshd.service",user="root",zzz_team="psa"} 150
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by srebhan**
## Summary

This PR adapts the `/sys/fs` path for newer systemd versions and uses the correct filtering for systemd units when using the new filter scheme.

## Checklist

- [x] No AI generated code was used in this PR
- [ ] AI generated code used in this PR follows the [InfluxData Policy on AI-Generated Code Contributions][policy]

[policy]: https://www.influxdata.com/ai-generated-code-contributions-policy

## Related issues

resolves #17904

### CODE REVIEW

File: plugins/inputs/procstat/os_linux.go [hunk 1]
```diff
@@ -81,14 +82,15 @@ func findBySystemdUnits(units []string) ([]processGroup, error) {
 	}
 	defer conn.Close()
 
-	sdunits, err := conn.ListUnitsByPatternsContext(ctx, []string{"enabled", "disabled", "static"}, units)
+	sdunits, err := conn.ListUnitFilesByPatternsContext(ctx, []string{"enabled", "disabled", "static"}, units)
```
Comment (skartikey) [inline plugins/inputs/procstat/os_linux.go:85]: @srebhan Why `ListUnitFilesByPatternsContext` is needed instead of `ListUnitsByPatternsContext` for newer systemd versions. Is this a bug in the dbus library? A change in systemd's behaviour?

Is there any risk that `ListUnitFilesByPatternsContext` returns unit files that aren't actually loaded/running, potentially causing issues?

The switch from `ListUnitsByPatternsContext` to `ListUnitFilesByPatternsContext` changes the behaviour:                                                                                              
  - Before: Lists units filtered by their `active state` (enabled, disabled, static refers to the systemd state of loaded units)                                                                    
  - After: Lists unit files filtered by their `enablement state` (enabled, disabled, static refers to whether the unit file is enabled)

File: plugins/inputs/procstat/os_linux.go [hunk 2]
```diff
@@ -81,14 +82,15 @@ func findBySystemdUnits(units []string) ([]processGroup, error) {
...
 		return nil, fmt.Errorf("failed to list units: %w", err)
 	}
 
 	groups := make([]processGroup, 0, len(sdunits))
 	for _, u := range sdunits {
-		prop, err := conn.GetUnitTypePropertyContext(ctx, u.Name, "Service", "MainPID")
+		name := path.Base(u.Path)
+		prop, err := conn.GetUnitTypePropertyContext(ctx, name, "Service", "MainPID")
 		if err != nil {
 			// This unit might not be a service or similar
```
Comment (skartikey) [inline plugins/inputs/procstat/os_linux.go:95]: Would it make sense to add debug-level logging when `GetUnitTypePropertyContext` fails, so users can more easily troubleshoot why certain units are not being monitored?

File: plugins/inputs/procstat/os_linux.go (hunk 1 above)
Comment (srebhan) [reply plugins/inputs/procstat/os_linux.go:85]: `ListUnitsByPatterns` does not work and will always return an empty list of services for newer versions of systemd. I was bitten by this in the [`systemd_units`](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/systemd_units) plugin. Try it and add use an "active" service with `ListUnitsByPatternsContext`!

File: plugins/inputs/procstat/os_linux.go (hunk 2 above)
Comment (srebhan) [reply plugins/inputs/procstat/os_linux.go:95]: I don't think so. This failing is expected for non-service units so I don't think there is a benefit in outputting those?

File: plugins/inputs/procstat/os_linux.go (hunk 1 above)
Comment (skartikey) [reply plugins/inputs/procstat/os_linux.go:85]: Thanks for the clarification. I verified that `systemd_units` plugin already uses `ListUnitFilesByPatternsContext` with the same pattern, which confirms this is the established approach for newer systemd versions.
