### PR TITLE
fix: ensure folders do not get loaded more than once

### LINKED ISSUE #10548: snmp: lengthy & multiple loading of MIBS
### Relevent telegraf.conf

```toml
[[inputs.snmp_trap]]
  path = ["/usr/share/snmp/mibs"]
```

### Logs from Telegraf

```
2022-01-31T15:58:39Z I! Starting Telegraf 1.21.3
2022-01-31T15:58:39Z I! Loaded inputs: snmp_trap
2022-01-31T15:58:39Z I! Loaded aggregators: 
2022-01-31T15:58:39Z I! Loaded processors: 
2022-01-31T15:58:39Z I! Loaded outputs: file
2022-01-31T15:58:39Z I! Tags enabled: host=ryzen
2022-01-31T15:58:39Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"ryzen", Flush Interval:10s
2022-01-31T15:58:56Z I! [inputs.snmp_trap] Listening on udp://:162
```

Note the timestamp difference between the agent settings and snmp_trap finally saying it is listening.

### System info

telegraf 1.21.3 + master

### Steps to reproduce

1. Configure `snmp_trap` input with a directory with lots of MIBs
2. Start telegraf

### Expected behavior

Telegraf to load files quickly and start listening on port immediately.

### Actual behavior

Telegraf seems to hang in input initialization with lots of files/big files/malformed files. Does it also appear to read them multiple times?

### LINKED ISSUE #10590: v1.21.3 not starting due to errors without config change
I updated today from 1.21.2 to 1.21.3. In a Raspberry PI, no issues, but an identical config in Ubuntu brings lots of:

Feb 05 09:02:31 Camaras systemd[1]: Stopped The plugin-driven server agent for reporting metrics into InfluxDB.
Feb 05 09:02:31 Camaras systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
Feb 05 09:02:31 Camaras telegraf[4094]: 2022-02-05T08:02:31Z I! Starting Telegraf 1.21.3
Feb 05 09:02:31 Camaras telegraf[4094]: 2022-02-05T08:02:31Z W! DeprecationWarning: Plugin "inputs.io" deprecated since version 0.10.0 and will be removed in 2.0.0: use 'inputs.diskio' instead
Feb 05 09:02:40 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/DPI20-MIB:9:4: unexpected "ibm" (expected ";")
Feb 05 09:02:41 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/HPR-MIB:494:30: unexpected "HprRtpCounter" (expected "}")
Feb 05 09:02:45 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/SNMPv2-PDU:73:1: unexpected "max-bindings" (expected "END")
Feb 05 09:02:46 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/TCPIPX-MIB:63:12: unexpected "tcpIpxConnLocalPort" (expected "}")
Feb 05 09:02:46 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/miblist.txt:1:12: no match found for .
Feb 05 09:02:48 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/DPI20-MIB:9:4: unexpected "ibm" (expected ";")
Feb 05 09:02:48 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/HPR-MIB:494:30: unexpected "HprRtpCounter" (expected "}")
Feb 05 09:02:48 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/SNMPv2-PDU:73:1: unexpected "max-bindings" (expected "END")
Feb 05 09:02:48 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/TCPIPX-MIB:63:12: unexpected "tcpIpxConnLocalPort" (expected "}")
Feb 05 09:02:48 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/miblist.txt:1:12: no match found for .
Feb 05 09:02:51 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/DPI20-MIB:9:4: unexpected "ibm" (expected ";")
Feb 05 09:02:51 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/HPR-MIB:494:30: unexpected "HprRtpCounter" (expected "}")
Feb 05 09:02:51 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/SNMPv2-PDU:73:1: unexpected "max-bindings" (expected "END")
Feb 05 09:02:51 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/TCPIPX-MIB:63:12: unexpected "tcpIpxConnLocalPort" (expected "}")
Feb 05 09:02:51 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/miblist.txt:1:12: no match found for .

and never starts.

Can't see why same configs fail in one system, not in the other ... unless is not telegraf itself but some library that the update is not "updating" ?

reverting to 1.21.2, makes it work again.

Any hint about how to resolve this?

### LINKED ISSUE #10603: [input.snmp] not working/hanging
### Relevant telegraf.conf

```toml
[[inputs.snmp]]
  agents = ["udp://192.168.23.239:161"]
  version = 2
  community = "public_ro"

# test collect
  [[inputs.snmp.field]]
# working until v1.21.2
    #oid = "RFC1213-MIB::sysUpTime.0"
# need to change to get working since telegraf v1.21.0
    oid = ".1.3.6.1.6.3.15.1.1.4.0"
    name = "uptime"
```

### Logs from Telegraf

```
# telegraf-1.21.3/usr/bin/telegraf --config snmp.conf --test --debug
2022-02-08T00:24:45Z I! Starting Telegraf 1.21.3
2022-02-08T00:24:45Z I! Loaded inputs: snmp
2022-02-08T00:24:45Z I! Loaded aggregators: 
2022-02-08T00:24:45Z I! Loaded processors: 
2022-02-08T00:24:45Z W! Outputs are not used in testing mode!
2022-02-08T00:24:45Z I! Tags enabled: host=switch01
2022-02-08T00:24:45Z D! [agent] Initializing plugins
```

### System info

Telegraf 1.21.3, Arch linux

### Docker

_No response_

### Steps to reproduce

I'm compleetly new and started from scratch, this is why I take it simple: 
1. downloaded latest version 
2. telegraf --usage snmp > testconfig.conf
3. edit testconfig to below one
3. telegraf --config testconfig.conf --test
This was but I was not able to get it working after a few hours of testing and modifiing I try later version and my config worked.

### Expected behavior

```
 # telegraf-1.21.2/usr/bin/telegraf --config snmp.conf --test --debug
2022-02-08T01:04:04Z I! Starting Telegraf 1.21.2
2022-02-08T01:04:04Z I! Loaded inputs: snmp
2022-02-08T01:04:04Z I! Loaded aggregators: 
2022-02-08T01:04:04Z I! Loaded processors: 
2022-02-08T01:04:04Z W! Outputs are not used in testing mode!
2022-02-08T01:04:04Z I! Tags enabled: host=arch-influxdb
2022-02-08T01:04:04Z D! [agent] Initializing plugins
2022-02-08T01:04:11Z D! [agent] Starting service inputs
2022-02-08T01:04:11Z D! [agent] Stopping service inputs
2022-02-08T01:04:11Z D! [agent] Input channel closed
> snmp,agent_host=192.168.23.239,host=arch-influxdb uptime=26i 1644282251000000000
2022-02-08T01:04:11Z D! [agent] Stopped Successfully

real    0m7.272s
user    0m7.111s
sys     0m0.896s
```

### Actual behavior

```
# telegraf-1.21.3/usr/bin/telegraf --config snmp.conf --test --debug
2022-02-08T01:05:59Z I! Starting Telegraf 1.21.3
2022-02-08T01:05:59Z I! Loaded inputs: snmp
2022-02-08T01:05:59Z I! Loaded aggregators: 
2022-02-08T01:05:59Z I! Loaded processors: 
2022-02-08T01:05:59Z W! Outputs are not used in testing mode!
2022-02-08T01:05:59Z I! Tags enabled: host=arch-influxdb
2022-02-08T01:05:59Z D! [agent] Initializing plugins
^Z[1]   Killed                  telegraf-${vers}/usr/bin/telegraf --config snmp.conf --test --debug

[2]+  Stopped                 telegraf-${vers}/usr/bin/telegraf --config snmp.conf --test --debug

real    1m26.923s
user    0m0.000s
sys     0m0.002s
```

### Additional info

As listed in Expected behavior, config is running fine with telegraf version 1.21.2

Since v1.21.0 the oid in config has to be adjusted to numbered notation to get it working:
from: oid = "RFC1213-MIB::sysUpTime.0" 
to: oid = ".1.3.6.1.6.3.15.1.1.4.0"

Debug Output of version 1.20.4 with 'oid = "RFC1213-MIB::sysUpTime.0" '
```
# telegraf-1.20.4/usr/bin/telegraf --config snmp.conf --test --debug
2022-02-08T01:03:02Z I! Starting Telegraf 1.20.4
2022-02-08T01:03:02Z D! [agent] Initializing plugins
2022-02-08T01:03:02Z D! [agent] Starting service inputs
2022-02-08T01:03:02Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "RFC1213-MIB::sysUpTime.0"
> snmp,agent_host=192.168.23.239,host=arch-influxdb uptime=18089086i 1644282183000000000
2022-02-08T01:03:02Z D! [agent] Stopping service inputs
2022-02-08T01:03:02Z D! [agent] Input channel closed
2022-02-08T01:03:02Z D! [agent] Stopped Successfully

real    0m0.621s
user    0m0.556s
sys     0m0.217s

```

Also you can see, there is an large time lag.
v1.20.4: real    0m0.621s
v1.21.2: real    0m7.272s

### PR DESCRIPTION
**Pull request by MyaLongmire**
### Required for all PRs:

- [ ] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #10548, resolves #10590, resolves #10603

The root folder was getting appended every time we loaded another folder, making root get appended exponential times. This pr should ensure that each folder only gets loaded once by checking symlinks and if it is a directory.

### CODE REVIEW

File: internal/snmp/translate.go [hunk 1]
```diff
@@ -80,6 +93,7 @@ func LoadMibsFromPath(paths []string, log telegraf.Logger) error {
 			return fmt.Errorf("Filepath %q could not be walked: %v", mibPath, err)
 		}
 
+		folders = unique(folders)
```
Comment (Hipska) [inline internal/snmp/translate.go:96]: How would it ever be possible to have a folder in there multiple times?

**Review by Hipska — APPROVED** [review]
Coding-wise it looks okay for me, but I don't see why this change is needed.

File: internal/snmp/translate.go (hunk 1 above)
Comment (Hipska) [reply internal/snmp/translate.go:96]: Thanks

File: internal/snmp/translate_test.go [hunk 2]
```diff
@@ -87,3 +89,54 @@ func TestTrapLookupFail(t *testing.T) {
...
+	return nil
+}
+func TestFolderLookup(t *testing.T) {
+	paths := [][]string{
+		{"testdata"},
+		{"testdata", "loadMibsFromPath"},
+		{"testdata", "loadMibsFromPath", "linkTarget"},
+		{"testdata", "loadMibsFromPath", "root"},
+		{"testdata", "mibs"},
+	}
```
Comment (reimda) [inline internal/snmp/translate_test.go:113]: This test is currently kind of halfway written as a table test. There's only one entry in the table so there's not much benefit to having a table. If we're never going to have more than one entry, we should probably remove the table code.

`paths` conceptually belongs with `name` and `files` in the table but it's outside.

We either need to remove the table code or move `paths` inside the table. It should replace `folders` in the table.

File: internal/snmp/translate_test.go [hunk 3]
```diff
@@ -87,3 +89,54 @@ func TestTrapLookupFail(t *testing.T) {
...
+			err := LoadMibsFromPath([]string{"testdata"}, testutil.Logger{}, &loader)
+			require.NoError(t, err)
+			for _, pathSlice := range paths {
+				path := filepath.Join(pathSlice...)
+				tt.folders = append(tt.folders, path)
+			}
+			require.Equal(t, tt.folders, loader.folders)
+			if runtime.GOOS == "windows" {
+				tt.files = []string{"emptyFile", "symlink", "testmib"}
+			}
```
Comment (reimda) [inline internal/snmp/translate_test.go:138]: This special case for windows doesn't make sense if this is going to be a table test. It could be moved into the table or we could have a separate test for windows since symbolic links don't work the same way on windows.

File: internal/snmp/translate_test.go [hunk 4]
```diff
@@ -87,3 +89,54 @@ func TestTrapLookupFail(t *testing.T) {
...
+			name:  "loading folders",
+			files: []string{"emptyFile", "testmib"},
+		},
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			loader := TestingMibLoader{}
+
+			err := LoadMibsFromPath([]string{"testdata"}, testutil.Logger{}, &loader)
```
Comment (reimda) [inline internal/snmp/translate_test.go:129]: I thought we were going to have the test load testdata/loadMibsFromPath/root, not testdata. If we load testdata here, when we modify other tests that use files in testdata, like testdata/mibs, it will affect the paths in this test.

If we load testdata/loadMibsFromPath/root, this test won't be affected when other tests change the contents of testdata outside of testdata/loadMibsFromPath.

Also, this path should be in the table along with files and paths

**Review by reimda — CHANGES_REQUESTED** [review]

File: internal/snmp/translate_test.go (hunk 3 above)
Comment (MyaLongmire) [reply internal/snmp/translate_test.go]: I changed the format to match what I found in another test (config_test.go). I am not certain this is the correct way to do it, if not let me know and I can change it :)

File: internal/snmp/translate.go [hunk 5]
```diff
@@ -18,14 +19,21 @@ var m sync.Mutex
 var once sync.Once
 var cache = make(map[string]bool)
 
-func appendPath(path string) {
+type MibLoader interface {
+	loadModule(path string) error
+	appendPath(path string)
+}
+
+type GosmiMibLoader struct{}
```
Comment (Hipska) [inline internal/snmp/translate.go:27]: I don't see the added value for this? Could you explain?

Comment (MyaLongmire) [reply internal/snmp/translate.go:27]: Sure! This is called dependency injection. It lets us have mock functions in tests so the tests won't call gosmi since we just want to check the logic of traversing the folders.

Comment (Hipska) [reply internal/snmp/translate.go:27]: Thanks. Maybe the struct could also be used for the lock,once and folder cache?

Comment (Hipska) [reply internal/snmp/translate.go:27]: They are used in the method `appendPath` and `loadModule`, but also in the function `walkPaths`. So if that `walkPaths` could be transformed to be also a method of `GosmiMibLoader`, then these snmp package vars could be moved into that struct..

Comment (MyaLongmire) [reply internal/snmp/translate.go:27]: since `walkPaths` is what we want to test it cannot be added to the interface and mocked the same way as `appendPath` and `loadModule`. It doesn't seem important to but the mutex and cache in `gosmiMibLoader` when gosmi is a global library.

File: internal/snmp/translate_test.go [hunk 6]
```diff
@@ -87,3 +89,60 @@ func TestTrapLookupFail(t *testing.T) {
...
+		files        []string
+		windowsFiles []string
+	}{
+		{
+			name:         "loading folders",
+			mibPath:      [][]string{{"testdata", "loadMibsFromPath"}},
+			paths:        [][]string{{"testdata", "loadMibsFromPath"}, {"testdata", "loadMibsFromPath", "linkTarget"}, {"testdata", "loadMibsFromPath", "root"}},
+			files:        []string{"emptyFile"},
+			windowsFiles: []string{"emptyFile", "symlink"},
+		},
```
Comment (powersj) [inline internal/snmp/translate_test.go:123]: Add another case for a directory structure that is 2-3 deep:

testdata
-- loadMibsFromPath
---- root
------ file here

and point the test at root.

**Review by powersj — APPROVED** [review]
