### PR TITLE
fix(outputs.sql): Allow to disable timestamp column

### LINKED ISSUE #16621: outputs.sql: setting timestamp_column to "" does not disable the timestamp_column
### Relevant telegraf.conf

```toml
[[outputs.sql]]
  timestamp_column = ""  # disable the timestamp
```

### Logs from Telegraf

```text
2025-03-13T08:54:28Z E! [agent] Error writing to outputs.sql: execution failed: mssql: Invalid column name 'timestamp'.
```

### System info

Telegraf 1.34.0, Docker iamge

### Docker

_No response_

### Steps to reproduce

1. Create SQL output plugin
2. Set `timestamp_column = ""`

### Expected behavior

Timestamps are not written like described in the docs

### Actual behavior

Timestamps are written to column `timestamp`.

### Additional info

Issue in here: https://github.com/influxdata/telegraf/blob/1464e4fcf2c635fa1b9ec5db265a86841e5fff59/plugins/outputs/sql/sql.go#L282-L284

### PR DESCRIPTION
**Pull request by srebhan**
## Summary

This PR allows to set the timestamp column to empty to not insert the timestamp column.

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #16621 
based on #16624
superseeds #16623

### CODE REVIEW

File: plugins/outputs/sql/sql_test.go [hunk 1]
```diff
@@ -434,3 +437,87 @@ func TestClickHouseDsnConvert(t *testing.T) {
...
+			"/out":                                   outDir,
+		},
+		ExposedPorts: []string{servicePort},
+		WaitingFor: wait.ForAll(
+			wait.ForListeningPort(nat.Port(servicePort)),
+			wait.ForLog("mariadbd: ready for connections.").WithOccurrence(2),
+		),
+	}
+	require.NoError(t, container.Start(), "failed to start container")
+	defer container.Terminate()
```
Comment (skartikey) [inline plugins/outputs/sql/sql_test.go:476]: The container termination is deferred, but if an error occurs early in the setup, the container might not be terminated. Consider a `t.Cleanup()` function to ensure proper cleanup even if `require.NoError(t, container.Start())` fails.

File: plugins/outputs/sql/sql_test.go [hunk 2]
```diff
@@ -434,3 +437,87 @@ func TestClickHouseDsnConvert(t *testing.T) {
...
+
+		require.Eventually(t, func() bool {
+			rc, out, err := container.Exec([]string{
+				"bash",
+				"-c",
+				"mariadb-dump --user=" + username +
+					" --password=" + password +
+					" --compact" +
+					" --skip-opt " +
+					dbname,
```
Comment (skartikey) [inline plugins/outputs/sql/sql_test.go:512]: nit: Instead of a string concatenation, consider using fmt.Sprintf() for clarity:
`query := fmt.Sprintf("mariadb-dump --user=%s --password=%s --compact --skip-opt %s", username, password, dbname)`

**Review by skartikey — APPROVED** [review]
Looks great! I have a couple of small suggestions.

File: plugins/outputs/sql/sql_test.go (hunk 2 above)
Comment (srebhan) [reply plugins/outputs/sql/sql_test.go:512]: Hmmm, well I usually like string concatenation more if you only deal with strings but I do agree for the special tests. Let's  do this in a separate PR to not clutter the fix. Do you want to try putting up that PR?

File: plugins/outputs/sql/sql_test.go (hunk 1 above)
Comment (skartikey) [inline plugins/outputs/sql/sql_test.go:476]:
```suggestion
    // Register cleanup function early to ensure it runs even if startup fails
    t.Cleanup(func() {
        if container.IsRunning() {
            container.Terminate()
        }
    })
    
    // Start the container
    require.NoError(t, container.Start(), "failed to start container")
```

Comment (skartikey) [reply plugins/outputs/sql/sql_test.go:476]: Re-read the code, `require.NoError(t, container.Start())` starts the container, followed by `defer container.Terminate()`. However, if an error occurs before reaching `defer` (e.g., during file path resolution), the container won’t be terminated properly.  

Using `t.Cleanup()` instead ensures cleanup runs even if the test fails early.  

Please see the suggestion below. let me know your thoughts!

**Comment by srebhan** [comment]
Maybe I'm missing something but if starting the container fails, how can it be in running state?

**Comment by skartikey** [comment]
> Maybe I'm missing something but if starting the container fails, how can it be in running state?

You're absolutely right, if starting the container fails, it won't be in a running state, so the existing code handles that correctly.

The key improvement here is about using `t.Cleanup()` rather than `defer`. When `t.FailNow()` is called (or any of its variants like `t.Fatal()`), it immediately stops test execution, and deferred functions won't run. This could leave containers running if a test fails early.

`t.Cleanup()` is specifically designed for this scenario - it's guaranteed to execute even if the test fails, skips, or terminates unexpectedly. This ensures proper resource cleanup in all scenarios.

**Comment by srebhan** [comment]
@skartikey agree with `t.Cleanup` is a much better alternative. However, we try to avoid `t.FailNow` and all of the tests make heavy use of deferred functions so cleaning up only this one won't do much good. So can we postpone this and do the change in a different PR?

**Review by mstrandboge — APPROVED** [review]
