### PR TITLE
Log permission error rather than add to filecount input

### LINKED ISSUE #5449: Filecount: directory permission denied blocks input regardless of recurse parameter
### System info:
Telegraf 1.9.4 (git: HEAD 4da8d0a4)
Ubuntu 16.04

### Steps to reproduce:
1. create this architecture in /tmp:
> foo
> |-- [-rw-rw-r--]  aaa
> `-- [d---------]  bar

   `foo` and `bar` are directories
   `aaa` is a regular file
   `bar` cannot be read by telegraf user (here, it is simulated by a 000 chmod)
2. Create the file `/tmp/aaa.conf` with this content:
> [[inputs.filecount]]
>   directory = "/tmp/foo/"
>   name = "aaa"
>   recursive = false
3. execute config file: `telegraf --config /tmp/aaa.conf --test`

### Expected behavior:
Telegraf process should return: 
    > filecount,directory=/tmp/foo/,host=computer count=1i 1550582182000000000

### Actual behavior:
Telegraf process returns:
2019-02-19T13:17:01Z E! [inputs.filecount]: Error in plugin: open /tmp/foo/bar: permission denied

### Additional info:
Since recurse is set to false, telegraf should not care about subdirectories, especially, it should not go into error. 
I am still looking for a workaround.

### PR DESCRIPTION
**Pull request by glinton**
Resolves #5449

### CODE REVIEW

File: plugins/inputs/filecount/filecount.go [hunk 1]
```diff
@@ -203,6 +208,13 @@ func (fc *FileCount) count(acc telegraf.Accumulator, basedir string, glob globpa
 		Callback:             walkFn,
 		PostChildrenCallback: postChildrenFn,
 		Unsorted:             true,
+		ErrorCallback: func(osPathname string, err error) godirwalk.ErrorAction {
+			if os.IsPermission(errors.Cause(err)) {
+				log.Println("I! [inputs.filecount]", err)
```
Comment (danielnelson) [inline plugins/inputs/filecount/filecount.go]: Use `D!`, since I think most will just want to ignore this error.  Can you paste an example of how the error looks here, we might need some leading context.

Comment (glinton) [reply plugins/inputs/filecount/filecount.go]: Meant to do that,
```
2019-02-25T23:33:30Z D! [inputs.filecount] cannot ReadDirents: cannot Open: open /tmp/foo/bar: permission denied
```
