### PR TITLE
fix postgresql connection leak

### LINKED ISSUE #2410: Postresql plugin does not close connections properly
## Bug report

when using the postgresql plugin and let it run for some time (1 hour should be enough) the postgresql server will claim, that there are no more free connections.
A look with netstat will confirm this (my current limit is 500 connections, all of them are in use)

    Active Internet connections (w/o servers)
    Proto Recv-Q Send-Q Local Address           Foreign Address         State
    tcp        0      0 dbserver.:postgresql grafana.:60496 ESTABLISHED
    tcp        0      0 dbserver.:postgresql grafana.:54826 ESTABLISHED
    tcp        0      0 dbserver.:postgresql grafana.:33832 ESTABLISHED
    tcp        0      0 dbserver.:postgresql grafana.:48662 ESTABLISHED
    tcp        0      0 dbserver.:postgresql grafana.:34264 ESTABLISHED
    tcp        0      0 dbserver.:postgresql grafana.:34470 TIME_WAIT
    tcp        0      0 dbserver.:postgresql grafana.:34382 ESTABLISHED
    tcp        0      0 dbserver.:postgresql grafana.:51706 ESTABLISHED
    tcp        0      0 dbserver.:postgresql grafana.:38296 ESTABLISHED
    tcp        0      0 dbserver.:postgresql grafana.:37974 ESTABLISHED
    tcp        0      0 dbserver.:postgresql grafana.:53828 ESTABLISHED
    tcp        0      0 dbserver.:postgresql grafana.:35974 ESTABLISHED
    tcp        0      0 dbserver.:postgresql grafana.:38496 ESTABLISHED
    tcp        0      0 dbserver.:postgresql grafana.:43290 ESTABLISHED
    tcp        0      0 dbserver.:postgresql grafana.:36564 ESTABLISHED
    .........
    tcp        0      0 dbserver.:postgresql grafana.:35250 ESTABLISHED
    tcp        0      0 dbserver.:postgresql grafana.:58990 ESTABLISHED
    tcp        0      0 dbserver.:postgresql grafana.:60576 ESTABLISHED
    tcp        0      0 dbserver.:postgresql grafana.:44946 ESTABLISHED
    tcp        0      0 dbserver.:postgresql grafana.:41526 ESTABLISHED
    tcp        0      0 dbserver.:postgresql grafana.:34516 TIME_WAIT
    tcp        0      0 dbserver.:postgresql grafana.:36100 ESTABLISHED
    tcp        0      0 dbserver.:postgresql grafana.:44844 ESTABLISHED
    udp        0      0 localhost:43693         localhost:43693         ESTABLISHED

### Relevant telegraf.conf:
    [[inputs.postgresql]]
            address = "host=dbserver.my.domain user=user password=passwd"

### Versions
    $ telegraf --version
    Telegraf vdev-49-gc8cc01b (git: master c8cc01b)

    $ postgres --version
    postgres (PostgreSQL) 9.4.6

This is, at least for me, always reproducible, even after I restart postgres, telegraf or influx. None of that worked

### PR DESCRIPTION
**Pull request by james-lawrence**
fixes #2410

the connection leak caused by how pgx manages connection pools and how telegraf connects to generate the sql.DB connection. We needed to close the pool in addition to the db connection.

I've patched pgx to handle both DSN and URI based connection strings natively. this fixes the issue.

### CODE REVIEW

**Comment by james-lawrence** [comment]
My changes to pgx to avoid this issue entirely have been given the okay. Once they are merged I will update this PR.

**Comment by james-lawrence** [comment]
updated PR using fix in the driver.

File: plugins/inputs/postgresql/connect.go [hunk 1]
```diff
@@ -79,21 +75,3 @@ func ParseURL(uri string) (string, error) {
 	sort.Strings(kvs) // Makes testing easier (not a performance concern)
 	return strings.Join(kvs, " "), nil
 }
-
-func Connect(address string) (*sql.DB, error) {
```
Comment (danielnelson) [inline plugins/inputs/postgresql/connect.go]: I think this is used by the `postgresql_extensible` input, can you flip through that plugin and make sure its working and connecting in the correct way?

Comment (james-lawrence) [inline plugins/inputs/postgresql/connect.go]: Yup, I added the connect method originally. I'm just fixing the regression for the code I commited. You'll notice I changed postgresql_extensible as well in the diff.

Thanks for the review. =)

**Comment by anilkulkarni87** [comment]
Can we get to Redshift using this plugin?

**Comment by danielnelson** [comment]
@anilkulkarni87 I think so, but I have never tried, you could ask over on the [InfluxData Community](https://community.influxdata.com) site.

**Comment by anilkulkarni87** [comment]
@danielnelson I have been trying to connect. but doesnt connect to Redshift though. Let me tryasking in the community.

**Comment by james-lawrence** [comment]
@anilkulkarni87 its not intended to. so short answer is no =)

**Comment by anilkulkarni87** [comment]
@james-lawrence Thought so after all the going through the .Go script. But do you know if there are any plugins which can connect to redshift?

**Comment by james-lawrence** [comment]
no idea, doesn't look like. You'll likely have to write one.

**Comment by danielnelson** [comment]
@anilkulkarni87 You can create a feature request issue, make sure to include what happens if you try to use the existing postgres inputs.

**Comment by anilkulkarni87** [comment]
@danielnelson created a feature request issue
https://github.com/influxdata/telegraf/issues/2683
