### PR TITLE
remove sleep from tests

### LINKED ISSUE #2382: Remove Sleep from tests
### Steps to reproduce:

1. Run the tests on all plugins

### Expected behavior:
All pass

### Actual behavior:
Occasionally some will fail, such as:
```
--- FAIL: TestRunParserAndGatherJSON (0.14s)
	Error Trace:	accumulator.go:234
			mqtt_consumer_test.go:183
	Error:      	unknown measurement nats_json_test
FAIL
```

### Additional info:
Many of the plugin tests use `time.Sleep()` to give their goroutines time to process data. This is a bad idea as it makes the test take longer, and the times may not be adequate to avoid failures.

Unfortunately `go test -race` doesn't detect these issues, because the plugins are using methods such as `acc.AssertContainsTaggedFields()` and `acc.NMetrics()`, which use locks and atomic operations. It's just that the locks are being grabbed before the goroutines have time to call `acc.AddFields()`.

b3537ef2 added a `testutil.Accumulator.Wait` method which should alleviate the majority of the need for `Sleep` statements. We might want to provide a convenience function though to avoid the need for:

```
acc.Lock()
if acc.NMetrics() == 0 {
  acc.Wait()
}
acc.Unlock()
```

But it's not that much code, so I'm not completely convinced of the need.

However it does seem like we need something similar to `acc.Wait()` such as `acc.WaitError()`. I've seen some tests which are doing `time.Sleep()` and expecting an error to happen.

### PR DESCRIPTION
**Pull request by phemmer**
This removes `time.Sleep()` from the majority of the tests. This should alleviate the racyness that causes the CircleCI tests to randomly fail. It also makes the affected tests significantly faster.
The few tests where `time.Sleep()` wasn't removed generally one of 2 cases. Either doing so would have made the code very complex, or I don't have the ability to test the change.

### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Fixes #2382

### CODE REVIEW

**Comment by phemmer** [comment]
Tests are unfortunately failing on the tail input plugin. The github.com/hpcloud/tail package is racy as hell. Am going to try to submit a patch on it to fix some of the more critical issues. But I can't even get that package's own tests to pass on my system (even on a completely unmodified master), so it might take a little work.

**Comment by danielnelson** [comment]
We could merge everything except the tail changes now, and fix those tests later.

File: plugins/inputs/tail/tail_test.go [hunk 1]
```diff
@@ -60,13 +59,19 @@ func TestTailFromEnd(t *testing.T) {
 
 	acc := testutil.Accumulator{}
 	require.NoError(t, tt.Start(&acc))
-	time.Sleep(time.Millisecond * 100)
+	time.Sleep(time.Millisecond * 200) //TODO remove once https://github.com/hpcloud/tail/pull/114 is merged & added to Godeps
```
Comment (phemmer) [inline plugins/inputs/tail/tail_test.go]: This solves the race detector issues.

**Comment by danielnelson** [comment]
@phemmer Getting lots of failures over the last few days from the tail tests, any sense on if this might be fixed by your upstream fix? https://circleci.com/gh/influxdata/telegraf/6404

**Comment by phemmer** [comment]
Hrm. Looks different. Still a race condition, but I don't think related to my upstream PR. Will look into it later tonight.


-------- Original Message --------

**Comment by phemmer** [comment]
That library is so incredibly messy. If there were an alternative available, I'd recommend switching. But I find no alternatives.
Anyway, found & fixed the issue, upstream PR here: https://github.com/hpcloud/tail/pull/116

Looking at the history of the project, PRs seem to take months to merge. The last PR took 5 months to merge in, and there were no changes that had to be made during review process.
Given that, I'm not sure how you want to proceed. The telegraf tail test failures aren't just the tests failing. They're legitimate issues. We can add hacks to get the tests to pass, but that kinda defeats the point of the tests, as real world users can experience the issues.

**Comment by danielnelson** [comment]
I think we will have to use a fork at least until your changes are accepted.  Would you rather merge both of your changes onto a single branch on your fork or should I make one on our organization?

**Comment by phemmer** [comment]
I think I would prefer it be part of influxdata, or an official member of the team :-)

**Comment by danielnelson** [comment]
Can you open the PRs on https://github.com/influxdata/tail.  I really appreciate all the help, you are official to me but perhaps not to the legal team ;)
