### PR TITLE
fix(parsers.xpath): Handle protobuf maps correctly

### LINKED ISSUE #13715: [BUG] unable to parse complex protobuf message
### Relevant telegraf.conf

```toml
[[outputs.postgresql]]    
  connection = "postgres://username:password@postgresql.dbs.svc/ApplicationDbErrorReporting?sslmode=disable"

[[inputs.kafka_consumer]]
    brokers = [
    "kafka.cern.ch:30092"
  ]
  client_id = "ers-telegraf"

  consumer_group = "ers-telegraf"
  data_format = "xpath_protobuf"
  topics = [
    "ers_stream"
  ]
  xpath_protobuf_file = "/mnt/issue.proto"
  xpath_protobuf_type = "dunedaq.ersschema.Context"
  [[inputs.kafka_consumer.xpath]]
    metric_name = "string('ProtobuffReports')"
```

### Logs from Telegraf

```text
2023-07-27T23:34:34Z D! [parsers.xpath_protobuf::kafka_consumer] raw data (hex): "0ae6020afe010a1c2f6166732f6365726e2e63682f757365722f722f7269656865636b791283012f746d702f726f6f742f737061636b2d73746167652f737061636b2d73746167652d6572736b61666b612d4e4232332d30372d32362d69616f37626f67666c6373796f7a72686d7a626e6f74643667667178367079652f737061636b2d7372632f746573742f617070732f70726f746f6275665f73747265616d5f746573742e6378781a15696e74206d61696e28696e742c20636861722a2a2922116c78706c75733739302e6365726e2e636828213207756e6b6e6f776e58b7f80160b7f80168e48d0872087269656865636b797a0d45525353747265616d5465737412136572736b61666b613a3a5465737449737375651a0a6572733a3a49737375651a136572736b61666b613a3a54657374497373756522197468697320697320697373756520776974682049443a2031342a013430aaeae8cc99313a080a02696412023134520d54657374506172746974696f6e5a0d45525353747265616d54657374" (skip 0 bytes)
2023-07-27T23:34:34Z E! [inputs.kafka_consumer] Error in plugin: proto: field dunedaq.ersschema.Context.cwd contains invalid UTF-8
```

### System info

telegraf-1.27.2

### Docker

Running inside kubernetes

### Steps to reproduce

1. serialize complex message using provided schema
2. send to kafka
3. try to collect via telegraf

### Expected behavior

Parse the message out into some sort of object tree

### Actual behavior

Unable to parse message

### Additional info

protobuf schema : https://github.com/DUNE-DAQ/ers/blob/develop/schema/ers/issue.proto
https://github.com/DUNE-DAQ/erskafka/issues/20

### PR DESCRIPTION
**Pull request by srebhan**
- [ ] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #13715

Currently, Telegraf panics if you use maps (such as `map<string, string>`) in your protocol-buffers. This is mainly due to a bug in the protocol-buffer parsing code of the `protobufquery` library.

This PR bumps the dependency of the library and adds a unit-test based on the data of #13715. While at it I unified the location of the xpath-querying libraries under the `srebhan` account.

### CODE REVIEW

**Comment by jcpunk** [comment]
I can confirm this parses for my use case.

File: plugins/parsers/xpath/protocolbuffer_document.go [hunk 1]
```diff
@@ -138,7 +138,6 @@ func (d *protobufDocument) GetNodePath(node, relativeTo dataNode, sep string) st
 		if n.Parent != nil && n.Parent.Value() != nil {
 			kind = reflect.TypeOf(n.Parent.Value()).Kind()
 		}
-		fmt.Printf("node %q: %v (value=%v)   parent: %v\n", n.Data, kind, n.Value(), n.Parent.Value())
```
Comment (powersj) [inline plugins/parsers/xpath/protocolbuffer_document.go:141]: Are these helpful? should they be log messages? Same question in xpath/parsers.go

Comment (jcpunk) [reply plugins/parsers/xpath/protocolbuffer_document.go:141]: I'd love to have those at the debug level.

**Review by powersj — APPROVED** [review]
