### PR TITLE
chore(linters): Fix remaining errcheck warnings

### LINKED ISSUE #13013: Review not needed and missing blank identifiers used for `error`
### Use Case

`errcheck` linter has default exclusion list (which can be extended in `.golangci.yml`) 
https://github.com/kisielk/errcheck/blob/master/errcheck/excludes.go#L11
```go
	// bytes
	"(*bytes.Buffer).Write",
	"(*bytes.Buffer).WriteByte",
	"(*bytes.Buffer).WriteRune",
	"(*bytes.Buffer).WriteString",

	// fmt
	"fmt.Print",
	"fmt.Printf",
	"fmt.Println",
	"fmt.Fprint(*bytes.Buffer)",
	"fmt.Fprintf(*bytes.Buffer)",
	"fmt.Fprintln(*bytes.Buffer)",
	"fmt.Fprint(*strings.Builder)",
	"fmt.Fprintf(*strings.Builder)",
	"fmt.Fprintln(*strings.Builder)",
	"fmt.Fprint(os.Stderr)",
	"fmt.Fprintf(os.Stderr)",
	"fmt.Fprintln(os.Stderr)",

	// io
	"(*io.PipeReader).CloseWithError",
	"(*io.PipeWriter).CloseWithError",

	// math/rand
	"math/rand.Read",
	"(*math/rand.Rand).Read",

	// strings
	"(*strings.Builder).Write",
	"(*strings.Builder).WriteByte",
	"(*strings.Builder).WriteRune",
	"(*strings.Builder).WriteString",

	// hash
	"(hash.Hash).Write",
```

### Expected behavior

For excluded functions, there is no need to simulate handling `error` by using `_ := function1(...)`, or `_, _ := function2(...)`.
Remove blank identifiers for such cases (to find them something like this can be used: `grep -nr '_, _ = (\w\+\.)\+Write' * `).

### Additional info

Also, it would be good to handle errors properly for cases when blank identifier is used for non-excluded functions.

This configuration can find such cases:
```
linters-settings:
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
    # Such cases aren't reported by default.
    # Default: false
    check-blank: true
```

### PR DESCRIPTION
**Pull request by DStrand1**
## Summary
Fixes remaining errcheck warnings in input/output plugin directories and removes remaining temporary .golangci.yml exclusions

## Checklist
- [X] No AI generated code was used in this PR

## Related issues
resolves #13013

### CODE REVIEW

File: plugins/inputs/gnmi/handler.go [hunk 1]
```diff
@@ -164,7 +164,11 @@ func (h *handler) handleSubscribeResponseUpdate(acc telegraf.Accumulator, respon
 	prefix := newInfoFromPath(response.Update.Prefix)
 
 	// Add info to the tags
-	headerTags["source"], _, _ = net.SplitHostPort(h.address)
+	var err error
+	headerTags["source"], _, err = net.SplitHostPort(h.address)
+	if err != nil {
+		h.log.Debugf("unable to parse address %s: %v", h.address, err)
```
Comment (powersj) [inline plugins/inputs/gnmi/handler.go:170]: Same question here, error? warning? or print once?

File: plugins/inputs/webhooks/artifactory/artifactory_webhook_test.go [hunk 2]
```diff
@@ -1,6 +1,7 @@
 package artifactory
 
 import (
+	"github.com/stretchr/testify/require"
```
Comment (powersj) [inline plugins/inputs/webhooks/artifactory/artifactory_webhook_test.go:4]: Let's move this down out of the std imports please

File: plugins/inputs/webhooks/github/github_webhooks_test.go [hunk 3]
```diff
@@ -1,6 +1,7 @@
 package github
 
 import (
+	"github.com/stretchr/testify/require"
```
Comment (powersj) [inline plugins/inputs/webhooks/github/github_webhooks_test.go:4]: Move this out of std imports please

File: plugins/inputs/webhooks/mandrill/mandrill_webhooks_test.go [hunk 4]
```diff
@@ -13,19 +13,21 @@ import (
 	"github.com/influxdata/telegraf/testutil"
 )
 
-func postWebhooks(md *MandrillWebhook, eventBody string) *httptest.ResponseRecorder {
+func postWebhooks(md *MandrillWebhook, eventBody string, t *testing.T) *httptest.ResponseRecorder {
```
Comment (powersj) [inline plugins/inputs/webhooks/mandrill/mandrill_webhooks_test.go:16]: Can testing be the first attribute please?

File: plugins/inputs/webhooks/mandrill/mandrill_webhooks_test.go [hunk 5]
```diff
@@ -13,19 +13,21 @@ import (
...
 	w := httptest.NewRecorder()
 
 	md.eventHandler(w, req)
 
 	return w
 }
 
-func headRequest(md *MandrillWebhook) *httptest.ResponseRecorder {
-	req, _ := http.NewRequest("HEAD", "/mandrill", strings.NewReader(""))
+func headRequest(md *MandrillWebhook, t *testing.T) *httptest.ResponseRecorder {
```
Comment (powersj) [inline plugins/inputs/webhooks/mandrill/mandrill_webhooks_test.go:28]: Same here

File: plugins/inputs/webhooks/papertrail/papertrail_test.go [hunk 6]
```diff
@@ -15,8 +15,9 @@ const (
 	contentType = "application/x-www-form-urlencoded"
 )
 
-func post(pt *PapertrailWebhook, contentType string, body string) *httptest.ResponseRecorder {
-	req, _ := http.NewRequest("POST", "/", strings.NewReader(body))
+func post(pt *PapertrailWebhook, contentType string, body string, t *testing.T) *httptest.ResponseRecorder {
```
Comment (powersj) [inline plugins/inputs/webhooks/papertrail/papertrail_test.go:18]: Move testing to front

File: plugins/inputs/webhooks/particle/particle_webhooks_test.go [hunk 7]
```diff
@@ -1,6 +1,7 @@
 package particle
 
 import (
+	"github.com/stretchr/testify/require"
```
Comment (powersj) [inline plugins/inputs/webhooks/particle/particle_webhooks_test.go:4]: Move this out of std imports

File: plugins/inputs/webhooks/particle/particle_webhooks_test.go [hunk 8]
```diff
@@ -9,8 +10,9 @@ import (
 	"github.com/influxdata/telegraf/testutil"
 )
 
-func postWebhooks(rb *ParticleWebhook, eventBody string) *httptest.ResponseRecorder {
-	req, _ := http.NewRequest("POST", "/", strings.NewReader(eventBody))
+func postWebhooks(rb *ParticleWebhook, eventBody string, t *testing.T) *httptest.ResponseRecorder {
```
Comment (powersj) [inline plugins/inputs/webhooks/particle/particle_webhooks_test.go:13]: testing to front please

File: plugins/inputs/webhooks/rollbar/rollbar_webhooks_test.go [hunk 9]
```diff
@@ -1,6 +1,7 @@
 package rollbar
 
 import (
+	"github.com/stretchr/testify/require"
```
Comment (powersj) [inline plugins/inputs/webhooks/rollbar/rollbar_webhooks_test.go:4]: move this down please

File: plugins/inputs/webhooks/rollbar/rollbar_webhooks_test.go [hunk 10]
```diff
@@ -9,8 +10,9 @@ import (
 	"github.com/influxdata/telegraf/testutil"
 )
 
-func postWebhooks(rb *RollbarWebhook, eventBody string) *httptest.ResponseRecorder {
-	req, _ := http.NewRequest("POST", "/", strings.NewReader(eventBody))
+func postWebhooks(rb *RollbarWebhook, eventBody string, t *testing.T) *httptest.ResponseRecorder {
```
Comment (powersj) [inline plugins/inputs/webhooks/rollbar/rollbar_webhooks_test.go:13]: test to first

**Review by powersj — COMMENTED** [review]
Thank you for doing this!! very excited about getting this turned on. I have a few spots with small changes and two questions about error messages.

File: plugins/inputs/amd_rocm_smi/amd_rocm_smi.go [hunk 11]
```diff
@@ -104,7 +104,10 @@ func (rsmi *ROCmSMI) pollROCmSMI() []byte {
 		"--showtoponuma",
 		"--json")
 
-	ret, _ := internal.StdOutputTimeout(cmd, time.Duration(rsmi.Timeout))
+	ret, err := internal.StdOutputTimeout(cmd, time.Duration(rsmi.Timeout))
+	if err != nil {
+		rsmi.Log.Debugf("failed to execute command in pollROCmSMI: %v", err)
```
[the remark this answers is not in the document]
Comment (DStrand1) [reply plugins/inputs/amd_rocm_smi/amd_rocm_smi.go:109]: I decided to move this to a returned error in `Gather()`

File: plugins/inputs/gnmi/handler.go (hunk 1 above)
Comment (DStrand1) [reply plugins/inputs/gnmi/handler.go:170]: I decided to log this at `Error` level which matches other logging calls in this function

File: plugins/inputs/amd_rocm_smi/amd_rocm_smi.go [hunk 12]
```diff
@@ -33,7 +34,10 @@ func (*ROCmSMI) SampleConfig() string {
 
 // Gather implements the telegraf interface
 func (rsmi *ROCmSMI) Gather(acc telegraf.Accumulator) error {
-	data := rsmi.pollROCmSMI()
+	data, err := rsmi.pollROCmSMI()
+	if err != nil {
+		return fmt.Errorf("failed to execute command in pollROCmSMI: %v", err)
```
Comment (powersj) [inline plugins/inputs/amd_rocm_smi/amd_rocm_smi.go:39]:
```suggestion
		return fmt.Errorf("failed to execute command in pollROCmSMI: %w", err)
```

**Review by powersj — APPROVED** [review]

File: plugins/outputs/postgresql/postgresql_bench_test.go [hunk 13]
```diff
@@ -33,7 +33,8 @@ func benchmarkPostgresql(b *testing.B, gen <-chan []telegraf.Metric, concurrency
 
 	p.TagsAsForeignKeys = foreignTags
 	p.LogLevel = ""
-	_ = p.Init()
+	err = p.Init()
+	require.NoError(b, err)
```
Comment (srebhan) [inline plugins/outputs/postgresql/postgresql_bench_test.go:37]:
```suggestion
	require.NoError(b, p.Init())
```

File: plugins/inputs/burrow/burrow_test.go [hunk 14]
```diff
@@ -27,6 +27,7 @@ func getResponseJSON(requestURI string) ([]byte, int) {
 	}
 
 	// respond with file
+	//nolint:errcheck // should fail tests later on if this read fails
 	b, _ := os.ReadFile(jsonFile)
 	return b, code
```
[the remark this answers is not in the document]
Comment (DStrand1) [reply plugins/inputs/burrow/burrow_test.go]: Since this function was called nested a few functions deep in test cases with no access to `testing.T`, I decided to panic here if there is an error instead

File: plugins/inputs/ecs/client_test.go [hunk 15]
```diff
@@ -106,6 +105,8 @@ func TestEcsClient_Task(t *testing.T) {
 			name: "happy",
 			client: mockDo{
 				do: func() (*http.Response, error) {
+					rc, err := os.Open("testdata/metadata.golden")
+					require.NoError(t, err)
```
Comment (srebhan) [inline plugins/inputs/ecs/client_test.go:109]: I would do
```suggestion
					if err != nil {
						return nil, err
					}
```
Same below.

**Review by srebhan — COMMENTED** [review]
Thanks @DStrand1! Just one (actually two) suggestions left...

**Review by srebhan — APPROVED** [review]
